package topc.test.search;

import junit.framework.*;
import org.junit.Test;
import static org.junit.Assert.*;
import topc.search.*;

public class MatchStringTest {
  MatchString matchstring = new MatchString();

  @Test
  public void case1() {
    String matchString = "TOP";
    String[] matchWords = { "TIK", "PPPO", "OP" };
    assertEquals(5, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case2() {
    String matchString = "MUTO";
    String[] matchWords = { "MAMA", "DUDU", "TIT", "EGO" };
    assertEquals(1, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case3() {
    String matchString = "BAKAR";
    String[] matchWords = { "BATA", "TATA", "OSKAR", "KRAJ", "RAJ" };
    assertEquals(5, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case4() {
    String matchString = "EEA";
    String[] matchWords = { "GEGA", "TOPCODER", "TEST" };
    assertEquals(-1, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case5() {
    String matchString = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    String[] matchWords = { "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBABB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA" };
    assertEquals(1225, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case6() {
    String matchString = "BETI";
    String[] matchWords = { "BABA", "VETARE", "TORO", "IMEI" };
    assertEquals(3, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case7() {
    String matchString = "AB";
    String[] matchWords = { "ABA", "ABAB" };
    assertEquals(1, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case8() {
    String matchString = "UHJPFMKNNUWYAIGHFYQSJPFNYQOAVPPOPPKRZFQVSXCMGENSAD";
    String[] matchWords = { "LUVDKETPLTSUNTMIXUVMULUMQHOLCBI", "PNH", "RPDSFCLCRGQWGXCKLBOJJEVJCSCEIQFCSUHOSRTNQ", "UWZAEFESEKXLZGRQZBJCJVXRZLFQMTAXUSPAXFWKWCWUAHXK", "DJFGQLLZQHRBMWIFAIMWSLIQBSYEBWFVDYMQKPTIWYS", "ZMFURIKSPQFVUIFYAUQZMSANYH", "KV", "GNDZNFXEPMWDKYTOYUXHNWLOAAJELDXZNLHZXJEEZTE", "MFJWAPSSLCMOGNOVLSHKSGQXKBGASHYSVSUEKV", "PUMVTWCGJULCLUTWBBYUVEVVRDQAOAYQYUWBQMMKNFTJ", "VTVDMFMMGUARITYKCJWCGMPKSZ", "QIAIYUQGY", "YIMJZITZUYCMHAGXMFXEXCEKPAYEDKWGHAEITC", "NCORVIFMXAUNVQVYRFBXNQHCSKWNAOKBEYBWDIE", "VXKVFDKSAZQXGYIIPBTWAQYGFZRLNDKRTSTEZGUL", "BDMKYFYHOFEHDTGPIPCYEIFKSXRASEIZWUHTGMXAVMCM", "UFDLO", "IYEIUCVHLGFWMYMMQWSSCQCYBETSMTPPWATJOGTSY", "RHSFJQIL", "S", "JMRGYXD", "PEQCUXRPMLOEF", "BSZLJFCKAMWHZFAUNMFNZYNMZGUBSLBVYNIOF", "YLHMVLYNRNCNQULR", "ZSY", "VIADNROAARHQHOTZERTQ", "OOXLFXCWP", "JLUCSABDZTQCZQOLSGWVHAHVGUO", "VIVJYIKFSNKAQBNJPPPCVRKTFJZI", "ZKZCPCNDAXSPBHYTAUTCGOPDQ", "SPSFWVTCNAURNKYIGSOMEVQUFQAVPTG", "CFLLGWZTWAWQEOALGKICQDEAHIKUXV", "IRZRAWTLHPRYTAVCNFOTHOCLTGKQXO", "QUJIYPHSJR", "WUPFQBPGUJMUFVKALPWZFFMA", "EWFEMHRAHEELGWYIFRITHEIOZBPWQUDJTK", "DANZVDLBDAPAINSEKR", "BLYXKIEGAJYWCQUIEQHFSINMWXGHKKMBZPKUOQ", "SNWJCQCHTPRCUZWMQYCDKZSGBPTM", "CFIHCQDRTQZAGXHDIWTOUEVROUUQSICADZZV", "YZRLRHSSAMZHCOCOZLPBZTZ", "VQKIFOXYPKSANAFBOVLZWEWXFIMPVYWVTKZGJMH", "EXRRIICGEEZSI", "IZQVOVCOMWNMQVEDIMSGGQ", "ERANAAKRBREUPIVTXWSJGFAVU", "KWQBAYEQYZX", "KOTBGZTPJLWAZVSBKTWYBQNQFGVDXPNTRIYXF", "CSPFRUABHFQNH", "HCGMBFISWMHTQJGZPIBAELCCYHERJIMVPNR", "DHWVFNVMLGAHXPSPZDTBWRYMYFD" };
    assertEquals(919, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case9() {
    String matchString = "AAMHXMABOGIPLQPELLCAUMZDCM";
    String[] matchWords = { "UANZFKZUGPOJOMZSXSGUXKFLKRCIRAZLVWAUZFSLGX", "BGBBFWZIMEHDYVLOUPOBAWAG", "DWVQHREM", "FMFNBHBVOBKUSHRMVO", "RFZTWNJIKYWMZWVCTLXPLJLSTFNYFLECB", "PNCAAPGNRKEZWMJNWT", "AD", "QMZSKSJGBANJENSYUZXODZRVJILBBAVRVODNCVZVPLNUFRD", "ADXDKOW", "PCMRDGHJGPX", "RAYWSNBIYSJERXBOAFBFNKTNYBTNJEHCFJFRRQKR", "HHP", "RDTJVAL", "ZXYKXHOTNMSQPRSELLDAMTZGJHGTQUHDSYBXIRUGIESL", "SRZRXLVCHPOA", "XAECOX", "EJFLEOWFCVWRTJEFVLSDBBI", "ZLCIHCFTL", "ZUEWKYOICSECDCZKOOCDNREPNCOUZAQCZAFRBOGGUS", "LKPAACGZ", "OU", "EVWMNQMDVEQHFKDIVASZSAQCYGJQXTFNIUFSUSP", "LRQVPXXUZTZEYDCKDUSKTZRGXBJMMCKGLREZTCKCDBJBY", "LIDSPMTYYVZJQBRXSOBBSURDNIVNVBYKCFYD", "IMHFFLDXC", "GUYCECMUWYGMJCTFHSCSYVLLYIMTWSGDBRQVQKUNKLP" };
    assertEquals(305, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case10() {
    String matchString = "NIEBXEYQETUPRZRZDBIKPVOCM";
    String[] matchWords = { "RDWTTEEWBFGJWPXANQYLDXVCKBUIYAJVBWYLYLKPNVDZXJEF", "ABQQUAKBWICUCXVKZBOXDLKISJALTOLILJMYWOVTZYMKON", "EE", "GKWMFZMDHJRDVQNBAECJFZXS", "QRWLTJWXOZEACTUW", "E", "YNS", "JSTQ", "FOTXJYEIZWKAVFKQH", "YYHSVJBSSGGDTROB", "EHTDTQKDDYJHIHWXSUSFURAVMDAOWAWXAQVXFW", "ZCYCAGMHXZFPAQSJRJDYWPDAOATXHIJ", "NEADOQXIZFPDDFZHUBVBIURBMRCBGMZQNUZTJRQZWISFO", "ZZGDERBQVSDDCA", "QERBGOXPYDQJOYP", "BRYFHMSBYMYHHYVDHZXAFBBWL", "USRXCJZYOFPPBQAGJCWPDOJXRAMURMPRXNETDYPLWJRG", "EQBZBWAOTUNOSU", "XHDBVTKJWXINSIQAZMVCIHL", "XECJOQVPLIJKSOLZSQUVBMCIVACCFIZORXKWBVYOA", "QHTPVEPOCGBESI", "EWGFWCMYILFYNNKTLRWXILTBACQNUJPHDTDZRAVYJTSS", "WUSMPZBGYFEBYUVIFFYSODONAKJ", "JNWWSLZCJLKGBLKRQHY", "WQXWMPFKFSECMMDBPUTMVXDUWY" };
    assertEquals(575, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case11() {
    String matchString = "YULRQAHWPAVAW";
    String[] matchWords = { "YAZAAKHFECWJXWQFYQNHOYLKZHGC", "AGTPMUCTDAQLISWQEHVLVYGPGHCUVYWSWT", "CHLCIULXGX", "TJKVOTMMVLZHXOJNDRKCWUX", "YTUSPSSTVPSQQHU", "EA", "JAXVWHKUNJNVBRHVPGAIAP", "PTGYLRLMBXQSWCEACYTGWGGLNOMAI", "PF", "ABCFITCVQOZHTZEDIJIV", "GMVMMXCSWZMLNUSSF", "SEDCADYIALSOBSVXD", "BWPRLDC" };
    assertEquals(127, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case12() {
    String matchString = "CJPXSKBUBIMSUUBZDEHWTESG";
    String[] matchWords = { "CUEEBHFPXPDJUYZLXBEGAFZATKUKRKQGSFYVV", "HUZVJLNQATMJ", "HJPPSKBQDUTBXLDJDA", "SRDVXILBMEGXBNPGNTIDNKBTJ", "PSPKQOEISHAVE", "WYWSNSDIDNCCNKZVKASYUKHJKVTHWCZCADLYAARRBUYDMYJU", "LDGUUXJCXHDDCEKCB", "KAXRQVQWNSWHDIEFWUPDXAOFY", "DLAAHENGYRYQEZFYMBZAHGREGUQDAHWLOIUVIMDNL", "I", "ZIXMYLGIZGKJCIPVBYLJCASQUDUGPY", "PPMUQTTGHGMNYWVIOVNRAESSQHHHJRFLCMMXFYHA", "FJYWCJWQXRU", "YJWPYWNRPZIEWEZVKZOMDDVQQHEJFXGFRLOZUTFIBRA", "ZBNATFZOXIGP", "ZIPHSJLODGDDNTXSJKYNJHOATCCZDGCGYSDZDRES", "GCAJROMTIIHRXDBTFBUSTKZJZGPSVJVMKZI", "HTSJQXOYSPPRQTVTERHFPIIUDS", "HVORNXJDLLAZMLGHDWACVLSMLNHBUUELJSEM", "WB", "JIZQAUCDMYTLZUTLRDYKJJFKOZMJYKJJIUINOPQZDNFF", "AOOQYQSUWTTNDKOUHBKGVEATKSDUTQWAIWZGMXFUCGXNDZCJTG", "USPZSWSODNGVNY", "GYZPVKKWVMFPGTOYHMOYNTGAYUSYOBFGDDECMJHHC" };
    assertEquals(522, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case13() {
    String matchString = "CEEJUXABUDOJCAGKCARKKMHMFCZIBI";
    String[] matchWords = { "DLRKYYPYPQPRBIKYTCGDHYGLCKVBUDMNZMUAAFOLT", "AVIIQBCHNZEZAP", "DETKJXCTVGSDPVWFUPKWEPPCKUOTCJHRRVGMWREYO", "CRSDVEVDJWCPPNTPZJVXULERCIAZVVDH", "BFJFNCSIDLMUPJFFNNHUGMLUNAB", "HTYVNJISXHUYURQECMDOWK", "TXUTGAWKTANTYDGWNPGSPDZNYLUWJXTXZXOJFPNJONLYGDSQE", "LGYTHZOWVDISPHTDSFXDBCD", "JRQZHEKZTUPJ", "NIOHZVDDZNNQ", "ZTLWCEGSTDIPWHLLAOH", "JFHAIYYMOJRLLHAKKPOGTKOVBLFQTEPASSLLXHUGZ", "PKCCTUMBLEVHWSYVRDFXZDQQGMVPHXKMBAYTC", "SALONPUSHQBHDDFCLXWJTERLPZJAKQJJDAEZM", "HIURIVLWERRHCDZLQUAWJWZYJACSWMNQWSAYAAGAUZBUT", "MLK", "KASICAIKCTPAPMGEUTEOVR", "TCDIIPAMPCMZMQTCJOTADG", "GLSNUJHAPFFEOSEVERLI", "UK", "MUOGTJAPTPMRWDQMRKVRMMPWKZVMVNAQEYIBYMDK", "MERPWVJPXR", "XQDKSFHEVTRWIKYXDDKBDPHCVFOHRCRSZMVVS", "PNMMEIJSKXMNPQRHWBQVZDVWQMXPOU", "FWIKMIQWMFST", "FAONQAHGJBDUUHVDPOKMRXBXMCYBQ", "CBIQIXEYIBYZSKCOIWKEPKYBYTTCSJKHEBPAKZTCVEOGOC", "DYIXQIYSIKMKUUSGUGDMHDEDEDGGYGCIGMRXKBDU", "RMJKNOCGWWBYYLBRJ", "PRAGRJCFZSTHCJSOOCIFEEODVL" };
    assertEquals(585, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case14() {
    String matchString = "RQKDKBHYJNQYGZJAJPOHEWTXAS";
    String[] matchWords = { "YLR", "JCZNSBKYRWHXZRXMNMJAIVMYGWPJXMGFKHHZZSKRQ", "JEAXFLOKV", "QUJCDSNEIYGVVIMSWWJYMDPIFKIWUOLGOX", "LSOOVZLKBJPQGSCGZAJNTQUREHCXJTHISCNXEGLIMIEPVFNKM", "EBZZIDBCAKXWEFQEFTZBBBUPTNN", "MHYBAUUULWHFZEVRNDZGHGXDT", "IBTRHOPHGJCYQDWPRLVIYCIIDBVMEPAXHNKEWZJTACFZCKLWY", "LSFRZYGWSEJREMJFPJMBTBQZGG", "OIDQQNDJPHCWITDUIJATYSCWNSTBVBRJEXCGNHNUUZB", "AEPRPCSLBYXKPSOAHFGAUQWXWUNOQLYYKIDTOOSLNVIBGLFFA", "XYKHGQJ", "OATCYGZCRSWAETIQKVNGDQME", "FZHTCRUHEXOPT", "PLLGVSBNHUOAAKTHCNHJN", "YETBUCLHFANVAWSUNEGVQIDSMXO", "GXYEWBDBWCJJSDZPTFBRRISRFCO", "WMOQQP", "GWUDZGOQAODBAXLGFQXXDEQHOKVYMNYDZYSIUGAZECOVT", "MH", "MDEVSVWXTRCVEBLPDGMMULEOAZHEPVXB", "ZTPTRQAKBWGUZZOAETBMWXMPYLJGS", "TLJRH", "UXSMQTOSGNHKVNZBOVIGBUGUOLIFTDXHMMBVWPCKIBMJOM", "XHBLOYOZYYIBGAHAFCQFPENBPCYSOZPAQYBKGZORGLF", "ZLGFYLYLXSVY" };
    assertEquals(609, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case15() {
    String matchString = "HQHPXVWEDJFWJTCGHLZZJ";
    String[] matchWords = { "OJETEBGTBZNDTOHUWIFOZSHL", "DWHHQEZWSRSZVTOQJALWXNWOY", "IJARKQQWHXWTFEHDOOFTTJFEQHJEZSUDVFXZEZKCLYFYZW", "OQZHRHTQVSHDCUKGMWUSAGTJYPDRHROPZM", "X", "KZTTGGODZIMHKVVWEVFGMZDR", "MQWUYNYEOXSQPEDABPUBCXGYCXEXTCAOSKWMWHJARJUOVXPOZR", "AWYTGSKJKXYEUTXJUXXTMFKQUCRIOIVEFI", "QDLB", "WNCUPSVSZDVGXFJHYBCMJDGGFVCPSJJMDBFUWWNWAEBHR", "JNCGJUIUDVUNDYLEJJVAUF", "FNUWTVQUVKWUAGVFZLCVBYFHTPGLWSSYPJLFIPDFCFBRRLMV", "JDXGXXBVJZMECNYVUEOVUABHDKMSNQYSDNUTWMFAYUSEPJ", "GQATEDBTOBEUOONVOVEBHVKGKAEHOWL", "DTCBIPBI", "FGWJNYZZQVGEMNJUOKRNIY", "ELDKRHKGSEAMFNVFBSNFHTHIYBQZHAN", "LGFOPUVXJQMZDYPPAHEKYDEYJLXGNJ", "AVQIQCEUBKJNUPSIQEJEVNUAZOQOMGDVJMPQYXMRZWOEBU", "Z", "DOUJZKFEKJHAUKIVFQNHWJSMKPSHSHAYIRFCMZEB" };
    assertEquals(237, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case16() {
    String matchString = "EPYMHKMQBOTKTEXDNTWXAKHYMZEW";
    String[] matchWords = { "JTJFEEHWHGRKMGZPHIRUMTZIKCEHKTLWMXQEWAIMV", "EWHFPRJKXOQJBTOCORJFMEWR", "RHFEDAMMAXEMYGFIQHEBFEDLXEPYCONCYSPWMKN", "CMUEWUIUAFXGORCATKMWN", "PESRFNXCXTGDIJCGOBHCVTEAGMFMAWHLHEARDSN", "PMLXTWDAQCNDVOKYWFLDP", "WYYCXKQRJOFJQVAODZJZUBLQDMWHYTEXZLCXKHYNSCMLNQZ", "BMHNMTQZUISUH", "ZWFNCGTAEXDNPQZMXBCWIKIHVABTUYELAEY", "GAKMROYB", "CVYDXYYAURDTSLQWJTPVIU", "JVMNUAOPZKZFBYIAGSIULYFASELWDV", "TSCQ", "SZHAUXKELIPQEOBXYEQKZOQRDEABFRCXQGXPZJCNECLS", "AHQIYFGTKDMFYUHMWLZYXGXKLHTIKDVCFVIP", "D", "KRWESLMZCZCZZVOAFTCEHGJAWDVNYILJRTHPLM", "ZCWALTGTJDYEBBTDHJ", "SWFMGICKED", "YPXHUK", "OTQKPGLVFGMAJZWPKEUTAOANEFPHHTKGHQYKQLXQP", "PAEUMFYVQQXKZYGOQPUOKLJPSCYHHTZRUSSHVUJIQFJZUFF", "DQSSJOPRUEIQYAZERZSFHLESV", "YCRTBGYTSBOXTBTBNYOAJISXXF", "BLOTFGMMXVCXLWHGMUZOHXAJLKZDRVIJHXYH", "Z", "JFBZPECAEYEIGQINSVYPDYCUINMIWGJZWZDWTUVZ", "NWYUJFLJNRCOWOQVVGBCEXDFWKENEAJFNUFM" };
    assertEquals(341, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case17() {
    String matchString = "AJADNRGFYQCE";
    String[] matchWords = { "RYDMHDJIA", "UQHXIGUGOCSKXHKEJLYS", "TDCFZTVAVSSGAMV", "PDVXCTZKCDIDEJJPFMFDALDPGYDVRBCSRZ", "QEZJDRFBDUYNPDINUPVPYFSQWXCDMNBRCXUMPAN", "LMPTKCNJRUXZCVEZPVXUXRS", "LTFKPPKUKCBGPJGA", "JKQXMRSYKQKPLNCZFDFQLKWAUCUJCCFOMMR", "YYXIQZKWKWHTDEMJW", "XAKRAYXBKQBO", "ZQWPEZXGWXGCMLYOBHOFKFGDZRKXAVXSBTFCTSYOGPE", "JICWKFVFKIUTWEKSDTDSIWIYKYKNXQXNWTJYK" };
    assertEquals(58, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case18() {
    String matchString = "ADSJIU";
    String[] matchWords = { "CRAGUKGBYEGKXFZAXP", "VSBDCJDEBSXGQKJTDYAGIYGTP", "HSRRPOKVZFMPCVCSHNWYRZUIHSRMGMYTLK", "VPXKGZMAGDCRJRFTYBZA", "JHOFDBTFXSHELFKXNBPHUQMWZLIPGHNTMDMOFM", "BUNKAXHHUJIYEKVYQCXPWTPJUT" };
    assertEquals(38, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case19() {
    String matchString = "ZJBNMKVOCPEZWHDZRDBGRILFPIYEZYMHIHNKDLYOE";
    String[] matchWords = { "DIVIWBJCPUFATTVLFSZUB", "VZFXLCAPXJHY", "OVEVCPHYLVXKCUNXYXNSWVZHNDBBE", "TDMFKKNLNJDVZYHXKQHTPGTKBKTM", "SMNVJHYPDBSLBTZMGMFJRNFXLC", "VIRSEKBLKOU", "PUSKVXLPIEZUDPIEOY", "FELAFYHGNQEXDBTPSWUICMNCKVIWLFGYCORKHEHDQNJUHRO", "LWPRLEZOYKSBMEWMQXMBRMIFQDCYHVEHXHCYWRC", "SJWULUGVLAVQBHDVQLHEFRIPVNRGEGSYUXT", "CHANNVBSWSGPBCETRSXLEOE", "IAGOKHZCK", "XXFUWIINMTOMEEOG", "FTFXHMAVVJEKAQZCXGISZMGMG", "GTOBEDNPNMEVFWUFMMGAEECSVIJNMCGOMHEKJFQYOBVOMIDDJV", "JFAJZCPCZJTOKDLQLXXNX", "IIGRDDNUVVFBPGE", "PIRKKOVPASOKOCCLUQWDITSLMDG", "JNRSSTOTZJB", "LSNBNOWLDGFTLIZGIAZSWMGYJVLCONZIVYZGQ", "TXGOKZTHSQBSUATKMAKGSUHZRXKD", "IFNHXLTTJBCYJM", "CFCDYAAYMUPPEBKBTSIBILMLCTBQMFWSD", "MUAFJKKXLXDFHSFXRLYITPDYVENBBLRNFKZQZKDHMFPQJXQH", "ATTQGEQPEERWMP", "BOWACKGRJXAPMQBOUIOVCWMWHCPFISUZ", "PYQCR", "XEAP", "DPZEGDFDP", "YTR", "M", "PQWQTCTIYRHCAGDHEBGUTGUJKCDZTKZA", "ABTKUXXVFLGDWZFRVFETIMWLHGURANRVICKHNKNWPR", "AVEMVDUKHZJLBPG", "ZVPNEOYTQTIXXTDPVJLGYNDQZTFNUHIJLTSSN", "QUKOPMMF", "DJWMEWCSDOAUN", "GKGOGTXLMUZGHROIALSEUQCONSQXVECX", "XPJLQYZ", "FEHOHSPWWFSRWSGWKWKYNHJR", "LXNRPDIZMEFHHZYPYTIJAYZO" };
    assertEquals(821, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case20() {
    String matchString = "MAUWHJOSJFNUDAOXLBBRTUZSYDPKKYSWXZSXX";
    String[] matchWords = { "FVEOKDYTHNTTVHMNMORFHPSMMLQCKFSUDT", "LGJIRENTQFTVCTJGPVAUALMSDOEOAZVDVNAQYNFUV", "BGWHUSGRX", "GVJQOKWVCZSINVJNDQFZLYDAKDSMBFZFCXNBMMVPZ", "MHEXLJWIKPAKWYFMSUEKDI", "JJYOYAUAZTA", "DWYMOEJXWQFONK", "KVBQSLINXWMSLFBCMAWEDMZBGCZQCMDF", "NVJTZRMRBAKPMLMFYNSQAOISQXCPZXJYBHBZLAJUY", "MIKMBJLAXITVCTIUFMDTTYRULLIAZOCVFFAHYKSEXTVNEQF", "CNOOHZQBHOSQGMPJYXBZRAD", "VLUGXO", "RMJD", "ACVJINRY", "OOLSZELDPAHARPUAZNDAGGMBLYQVYTYGYXITJZSKFMD", "JGTXKCLHFLHXSLBSWNHVBAKXTVBZWEUQNOLZYAJNJPLM", "LP", "LFESUISPWNBIMMDDHAFQRWRBUSBEKSMFQRDCPJ", "QVSTCGMMMFAQOOVUBYYCGHOALEQKI", "NGRWMFFMXZBPGXHTUIJYZCPVQWXFGTHKK", "NMZNBKTKSHRDDD", "CRJVCHEXEJQTSXUNSARNLUOMPPQYLJHJUMBNQIESHWAXUH", "ZQGZCHBEG", "MRJVOIAXACXPSUTEGR", "TYKBAXNEJDXENFYTCJHRMEMIEDYQFTTYXSZNR", "BQHTLXSEWBOKIYLAXLD", "YZMLWITDDEPHXAOTTCREKMCAPLPPECN", "XHUITWICWNNTHIBQZBTWYSSVKQKBVCDTUXGM", "LCWKKLDDBZFBMCOOLNETKCHGLNXUWJTI", "QIBXANJIIPXCKMYKNGQT", "QTRMRWUSUJIVYEYQW", "FXGAPYTXOZWAMHSXIEHQZBQIWEKPSIXNQMSLIJOCNGBEL", "LCFYRXJGVXKBZSQFDHSATIINVLCXBMR", "GHNVZLZZA", "TPQBDUZCYDVRAHDXJWKVQBSOS", "TPMDBTYUALTTYKXDRSPRCLTALIPVXOPST", "USPHIZNXXIBMKPGXOGNXMXCXSUXIUOIYMD" };
    assertEquals(457, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case21() {
    String matchString = "QDTPVQYTQKJL";
    String[] matchWords = { "OXUQIOMPWCMVMPUVEQHLHFXUQOGJXMKBSHQIMBPHDYLSWVQ", "KRUSBDXAAWSNFMGAVVGC", "QEWILHDLEERMSETGXNIMBNRCUCDCMM", "FUCRIMZXEVRWBSVGHLVOTEPALHABEZNIQ", "GHPXFHLWKV", "RIBLKDJBASOQQDWI", "Y", "VNXIWZTETPRHZPVYYAJACNCOYDPXHS", "QQWGO", "WXMVVXK", "J", "HIXEINFIQAVCHPHIDLEOTSBZPGBPKFREQPQXONJQBAS" };
    assertEquals(153, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case22() {
    String matchString = "LAYHAEAKADDBUKTLKVOLIWAWFFNAARP";
    String[] matchWords = { "NDUOFYLBFZVJGHSTQFVLNRWIHJOEWJ", "YLHMWXAWHNJVYLKOCTYVDDTKUGATCWOQTSYIO", "SDIYLMBXBLUFHYFBEUWKNGMQLNIQDQRCHFIYYEPKYGJDAHEC", "TXJUTUHCR", "UBFITXHNTKGQOHQAWYNKDTNN", "YJDEPSN", "HTNORWMXAZ", "UEKGM", "OSAJIVLTPHTUBHFGUBXDVXXZYNWALRZEAGBIJGSKPSTNZ", "DVGOHPQZUZVKYVDADTQJLXGMRCCMZDMJLPCYEZFYVT", "GUHCBFPDOMXMEQKCYJ", "YJEKABHDIOXECNJMZKLHXUWNTXXKUNFSLHTTZKYRZNUP", "OUFQHUGWSKGYYMFPXTQNGZFPJMYOCBAXNJLFNVWZVQL", "NFLTLHISGFEUKEPGHDTNWXGCSZBLP", "RQVEYQIUYKZVKMBCXDBKRPXUWJMMXPUIYANBTANRLU", "WNEKOLSWTPXOEDHKN", "UZDRDTUKWMGVDWFYGAKIEO", "EPHXAIYNGTNRGJHPLQOWNVTTGMVBXYLWMQENRT", "O", "NYQKZZZOLHDWZOXZLZOJKPIBLVPEQWVOFMRDCWM", "VBSIQRRYUSTEGPQMYLHTYHHZRZCJEITBTDCUVR", "CTNREWPSIERXTKCEKVRBKGWF", "NAUMPODUXVV", "DIDMZGBYEVVKUGXCSSNLELLIUW", "KTTTKUAJJZUAJIGTKSVGSZXLFGFFISLXGKUZLW", "HSIGBLFAWHJHHEFPZZFMUVCTLCFUOXLJLVHWEQTFNFDANXOGR", "MUN", "UFHVXRBIPHUXAHTAJMABUSFLJMGCOUS", "NEWCHDETJGGLKBGJVKYCSCWGSQQAJA", "MLAOLCTHNOGRVGW", "WQMJMQGUVLZNKWUYAILBEELFFLEWQZHIPKMO" };
    assertEquals(580, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case23() {
    String matchString = "MQQQXGJUJDXIQDMSVRUNBLCBCLKI";
    String[] matchWords = { "MSBPOZDYEAGMIDIXLHQVDYHHE", "RRRAARMPIWAIRBDGVCCAWCZQQEGQXSWXSKSEDBUQFPLLIUM", "QFSW", "PBTRJVYNGZQAZR", "OAIXGHNOQAUJILRBMCFKZYKG", "ROGABGAVL", "WYQIWYVCJSIPDPQWEQIHTMYCGEOTEILTBQHIPBOKU", "SCLKPYJWZCZDXRQTTKOEFTEXUEVZIUHUWRPSNXZO", "QFQRJOUDTKXWLDWJSLATFVDBCFPJAKKIUAYMLAGPG", "OLLVBNDSKNBVUKJVOLCNQXZDTZAEZGGGR", "EVXPQZXDUKJUNKHIGZLJQ", "RILSUMBYQBZZSLWZJBBPNKTKJRRRBA", "QUDOFFLXQDTVKKWZSTFLZV", "RFQJMJCKMJDEHNEXJFTJVUKQHZYCJVAKFXAFGJZWHMPOXGCGD", "ZXVVLFDIUMKFKFEKMD", "ZSX", "WNCGJMAJMPKAZTJVSBAENTOMJQDKPCVGFVGNDVN", "RFHFYBRNBPHBCXGRJWQTYQCFHKOKOO", "UC", "FLDNGONRHXAUQIFUWEZZUOSAASNNMKGKIJFDQPQOVZAFZBVY", "OOCWSQBVJRYXDUOLFDKYVHVBXBCCOFKLRNVPEFCBXABMHSINQV", "ELBFNSLYGIROSSCLYWAONBPIJRW", "ZBBYCCASGUGTTCOIAEZVIFCXNF", "WJBSQFEVFRBBGBBPFOPPMGYW", "LYZSTIOKLLAOMHJAYJGERLRGCPLOACEZIFSKFRKVATSFTLFHW", "VLGHDTFIQWRRZJURULTTXEWISTRUBHECBUPF", "VGDZDZHXTYVXKTMP", "VOPGDJPIVMQGWBLUYEQE" };
    assertEquals(337, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case24() {
    String matchString = "TUKRJIQOYTCDVMNFZXHE";
    String[] matchWords = { "MTSKTP", "GVEUIMWVIEGDJQHOEACM", "ZQWOANJJCOKFICQXWJYSIBWNBEZPZZVHRGXDWRNWKECEG", "ABMRPC", "FDOYSCHISESMVHEDZTJFWPEXJVQDECRHAVOC", "GIMXSOXHCNIHZIIPWVHCPZ", "RUCYAOPEQWIUEM", "GMYWOLYNHIHWOX", "LBXQHNRJSYIEPZOTPBCRDF", "TLKSHIQXZPSJJWFQTXHVNEDTVNDKWLAHBLUMUBYH", "WNMEEPYQZTGFKCKI", "FWHCDEFKQPCOVKAEDMZSTOPIVHUUNDUYFJVIHHHGTNBYUC", "UEXFEQOELBXDWXVVVNQIHAGONVJZRCSJLHKVMTSXAUOLLJVSJ", "FOPWJBMKOMABFZAUIYQOTGNKQDYV", "IVVWHKSYPCKAZWCBOWCTZYZFJFPEDNTYBMHJLPJFFEDN", "QTMHNFFTJULAUGTSAMGJC", "UPVEGAHZFS", "XXAMUK", "HC", "TOTSJXGXZCTMIXJIFCOCBGE" };
    assertEquals(329, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case25() {
    String matchString = "KCEQRRUPKLIICJPBKREDYXAOMRXKJR";
    String[] matchWords = { "CWLHANKXJAYTVWHCOPCAYKSIGPFMDKFAATXWVZLV", "RAJCSVXXPVQKKCBZWETZJBZPLLLNZKEGBRDEAFPDWE", "LGDMTEISRAQFOUEIDSMXI", "SHSOJHTMLYTJAISECKRKQJ", "NSDFLRVREQMSKXKRBCYOUMDXNVFOLATILUHVQSBW", "ANLVBGHYFFPITAGEQQDRWFGPNLLIRY", "ACBBURMSLBJJWWUUUJBOHTJHBKSUIJZON", "MGRDXGPGBWWU", "WNJDRKZNSCAXQMEQLISRHBHWELIKGPENDWUY", "XJFQZKNSCYRLIZTDVLPMRWGYYKSFHEXBNFTRXZPLN", "HJKPQYVFGJEHGNI", "KZFI", "AKNPYYGYZLJCHGYEICMRDKOJDXRTJQENJHAYYUTVCD", "EGQFUBLTKFBPBTCPQBQGJXUYCIHWTQAHFVGIUOZ", "BLJXLTLRERYGEEXCXQHPPQJASLGIAUUDDRHEMSIILXRKEV", "RTFXTNTJWSICSTBWGWICEMOBJXBGE", "DBLSFFUPKKZMREVWGTQDHKKKGMQSKJPOPHIOZDSVTTPSPRGSX", "FFHRSWPQYCNUIYYHLEAKTRNLXFXBPZJK", "KRKUDQXLWKEHSWBWENH", "DWJHVYJY", "NKYG", "DNPZUYVWSBFOVTJRSXXHOPSMQEXGXNGANYMNIGEXSR", "QYRTTTCTEQCAU", "KDDOGLZTWDWAWFEDX", "OCGWKLMNBZDQSXSHJOVAXBQIESBVEKLMSNNAYMROC", "QRXPA", "UFUPXSOXQCAPGNVWZ", "SYYJINHMJVYCOXMSHTECMGNRJRJCXPHWQLTOMENQVKL", "GHTUWAQZVMLINYNJUSRXKUOVYJUYDTLUWFRIFBFILV", "OKRENORJLGBCYHNDZMYI" };
    assertEquals(652, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case26() {
    String matchString = "JAYKYGWABQUQKLFGDOFTUNWWIDJLLLBULXXQYESYSAMTODFK";
    String[] matchWords = { "FLDPCKXJAJXE", "BCQRBLGBGAUSFCUKVIOMAIQICTOHYCBFMAWUIDFBSMA", "AWKAWVTEZQRJSAYFWBRHGBOAUYYOUJLOCYHGNDDZZMCS", "SLUWHRJYBEKMWMTCYDGYLJOBCEUDIC", "YSMTNNJWUXLQZ", "VBQKFGDLWHQIZBBPESRB", "DAIVZTDPUQPUJHLOIGFTNGJUWXYYGJPNB", "YDQYQOTLTCSGKIOTUQINUXYOUUKBWGMZHHLOGHA", "BAIQVTRGZKPHTSNXBLSQCPAJVJJDOPPSBAHTOMTUA", "YMHILKBUYWJYHHQYETDAZERCWBBUFZTNXXCGB", "FYOAEQJYMSJQYJDKTDHALWIWSRIUGYTWE", "OMUVIIQYPBJBWHTFKH", "ZTRVCJKINUTH", "JHKLYIYMWEKNFP", "LIMVRARISMNRGCYXODSOYZHPIGOOJBDMFE", "GXWPVDK", "YGGOQRMZRTNCTEZUARZBPDRVIGRRDALTARFFK", "SFENXDPRZXLTUCLHYZWURYKCOIQPWHMTEXENTLO", "EFKMORPUHFYAALAKRLTYNNZZCCCVGAYIEYDCP", "WMXAUMCAPBQODORXXNUQTKLIYHSQJTBBSIGFYAFPAFBUI", "SISKGUKPOYDORNHSDOPJMFAEKPZCBEJKJ", "HSNOQEQSUPBGSCHJLMXUYJHLTANQZDBMWFOK", "HOQZOYTTMAVHCIWCJUSRUBPTPVZQGEHHEHF", "AWNCWVNVMVULVTBMSLGEDWYWQRKYBJWNYQHPHPGNYEVVEUR", "WWYNHMSBZXNTPGCKRQRWTJFMCCEYJYHBQIILYICJGUPTJ", "CRNIDPTZBMCEFZVTJXZDIBXMLUA", "BEEQCHBJPTXZPMJLJYQGOAUMIZJYTBWFO", "SWSOLXINWYFXANOBNBOLHL", "OQGLKEOB", "VLLUAL", "LBYTBYCCWWJYDAPVEFFHCYZRWSXPBHDQLOXEGLJONQIRLXRI", "FSUJFIBSWGOTXHDKVQPOVDGWKJLCAIHKJBIJWOZDJNNRULI", "VHZCFALOLYWOTAJPQBWWXHPWDBFXYKV", "XEIFBDWVKCDPIZUOLPNQLEY", "WXCWMINDPBUAOVTRAY", "UURSDJMBXPKIDAQNNECQ", "QYYIQIZRDWDTYZYGHUVLENXVLIXAMCXVVQBZ", "MWYKVDKHHLPSRSEQQSBOLHLSKQXVXQZLGDYM", "QOPXJMDYEAGXOHYAUAVIWUSGRZDIDZH", "UEYDQRZTTYCZUGR", "IERSIUVKVHWQZVTEENZKSI", "RUIAJFIWCOXZL", "XZCTMEECMYSOHRBNBGX", "NXSAWQCEGRISYAYIZJRFPNOQIXJRZEMTNDNUW", "MUVJKJXOHYBAPEYVLEJFPKGMCOULOHUMOYGFROQYJON", "EFEKYZUUXJEMLSNDYHQJAMJPF", "JQFLDHBJKUNOJ", "UMADIBRPISAROVUDQKKJNRJEJFPNIUFUWJVNVZL" };
    assertEquals(1011, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case27() {
    String matchString = "RNOWPQWNUJZNFDRCJDYJKDQCOH";
    String[] matchWords = { "PPEINDYJBUTKVXMSMREWSMENTTPNSEH", "QLOYNMNMFYMORMWXUSWJRBNRLFSDWYBOEPTAAFGNUHW", "O", "TVJEFWOECWRNKNTXQAYGQUDUWQMWWKVRCLRFND", "BVDWXDHPODCPCBIWLJH", "QUJY", "IXSXTQFJJEQWAIFBPYUGQNAKRBDITBXOJNJHTEWPJYITUUO", "EBFLKBEPLTBUNCZXXKYY", "CSJFXTOGRVYDYUIEEEDOUZIRUTLKMIV", "NSLBPKUMAWPGJNTXEMFQZPBPVZQIXSCROLVG", "MXZAZIKNOYPIZMHEKZZFEONLI", "CUSGPYEEIRJQFZZQIUVXKPJPFCMYNBWIJIMQTRMMDBBQHHROO", "JFI", "QRD", "RRS", "HZWFVZFAZCOPLGOLEKERLCUXIJUSXRFAGSGNMIFE", "VUCJLR", "TDDNGW", "LKHJWVORHBWOYXOCAEDLHGIMMSDCRJGDJKFBHUUIHXZZ", "WHXVDMLCZOUJSINKOJGVKEFUVEMIFKNAG", "MTLRFCKCIXXKYHMIXR", "NCKMKMUYRTTVMZHGJGIETUUBFGDPOXWGJ", "NFGHKJPBTMWQECUKJRKHHH", "QNRFDLTICOAOLXFKANMPJZLZRMITOHMKF", "IJSSBREQUGRPFOWKBKLYKSSTNPNBEYLDLYEUGJKZPFXAW", "EKSQVCUHYPAXOUNHYWCPKERKB" };
    assertEquals(402, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case28() {
    String matchString = "ZGRNZJGMKOSILQPMVJCFZYQJDBUYKPAEXOOPIRFJT";
    String[] matchWords = { "ODNIZRZUWCLOXSXGETMQMWMXJIGAOBLIWNEPGPOWDUFIZN", "IMVXYKEIGQTSDGMJDTMXZMPST", "VYVTRBBIWXVUXOIYMJPNJEIDWXCTKPHERZOOSFRQTQRJN", "SXAOQLGQEGMEOZOYHHYWWBNL", "UTVSYDIXYASYHPDOZD", "ZKCNAEJVIFOWMNEMKSKOECZXIJJUYKXOERXPYXID", "BXLNUGMMLAIQYZAILOIKIPV", "GALMABIDCEJAYLCZCLFGFWMVB", "XOVMJOHZPISCGFFCWCKFUGIPXDYHDEFZ", "YOITXORQX", "FNSYDCBRUKDDPYXCXONWXTDWKBSCRKXSMJZ", "KKIP", "PGIYVQLQPBNIOIRWMFEBWMMYFMVYEYLYKWU", "WZKFBPKQHYFOWTXXTHAEZBQFPQJWRRD", "FUIPQUXP", "CVMSWOFPMVHEMYFW", "DTDDCVMZVKVWB", "IIJZSNETESQNONYEWFBNYIVFKXDWGJPJBDC", "TCQIPTQLSIODVIUXTFBCEVKOIBLJOGVLEFGHFWRRSNAGFUWZLF", "TUVLFHUFXS", "MXZNRLOCYFEUIMHYQKP", "OVZYWMERUDBVLWXQEKXNQUYVPHYHRDWBCAQUGWYGDSXE", "CIOQFRXKCENJPAOLNWYBQEDCPNSWWMRUWEJUCMFSPJ", "EEAPBFSUYLACFZDBYPJBJNZF", "RXDJZUFVGV", "TFBUOPOHUJJTEEMWOPHYVNUIWBWNOFAWIS", "HBXKAEQRWIRIPYGQVCDFNICZXNXZTXUUOOQLEWVBCRQOF", "KRCEZYBQGWLNIRUKIGEDT", "AQHYYTODDXBZXBGVIWBUWKTPKZTFIYATCHCAXQFEZW", "XMCXKNNSSPZHBLYKKB", "QLPDHWFNOIJAALO", "YE", "LCXK", "OXVQZCDWUVZOTRMBPALISVPTTAS", "KFNTDDSGGGTGWARRKWHEOEFEEPNSWVIAANYUDKIXJN", "AQMBJZKDITGTMXOPNQVSDTKPM", "I", "RDDQGJTWHYLJGXUSVRHXBVCIRGSTBTWORLJLUXMEPHVZQCHBS", "SBXSWJHFESCOPJFAISDFQOYMMEANPIVTWNMXDZ", "NBXKCCJDUHZKRWDTHQJEVIKBNQJ", "MTNJXTWZUZ" };
    assertEquals(620, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case29() {
    String matchString = "UYNMXMEKJHABQWQIPOSJLRLLFZVBMVWNLYMPBM";
    String[] matchWords = { "LNWMYWBXEINUXARTQOZAQETIQIGVFUOJUXKLFB", "JUEVOQOBSPIYMVSPDAPWLYYUOGOZZBURGFLELTFOARPBD", "LYAFGLSCYHRIXYPWNZAFXCWQ", "UHCRHPUWJEQVIPENMLMMHQLWOXMNJSRISANWJFLLWTDZA", "APQUNBPRREWTXXXVOJGUCRMH", "DZEXMRGDCEBJYSYLPTCMCEYIGTBPEMXZAAIBURPYI", "ZYDCUYAXEOGZBWKJMMQZTEPRCJIWQPVOE", "MKC", "EIVXQJBBJRZU", "VBHXKHO", "QHPAOXZWQEJNEAULOMSS", "BAILXOFNXIQMBGRHITCU", "XEMVYPQTGDVTQSGMRMJO", "RMDSVPUXGGYQOYQWWSNWUR", "FZDYLRSOUQOZXEDBLKIEWCWPVWUYPQAVBSPUGOYUVZWDT", "YYOMDPTI", "MTAGANNFTWDTWCUXMPGFOZHEFQXHWOBXEFYCCQPAXB", "OO", "MSMWBH", "RNGJOPVVGZWINOMKXKUPH", "GDXLIOZWBNBUDODBOBHLT", "WKVQPAREYCPBSSYDUGRNMIGDIWXOTG", "PJDL", "UFJYUPESMJVGETLDSA", "KWYLDWGMIXOMXFBYIXJDCRFFXZFR", "LFYPFZP", "OVITELZKDRBNWSFWUWRSXWPEZWLROLWQWVSQASEVLLRUKSSI", "ZIDUBNTWKAIKPIHDZTXNBHHILGCPMZTMPMIYA", "RCEAMPHWFBDQDLC", "QMQTXXACREXWCCVQM", "WCPQPENOSSIQCDNJCFQXZWQHIHAWWCDOD", "TENFEGHECL", "CTSL", "EHIYWGXJL", "DJGYDEBSGKYMEIEYXQBAXXIYAZU", "UGLHLOWQRWJUAYRRRPWIVYVAZTJYGOBAVYBAHBQQSKUYLKLD", "B", "SKGQMXTBRBQ" };
    assertEquals(354, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case30() {
    String matchString = "OUQXNKAYGFADTCEQZXUIAIZVRMYSVVPRVSKEWIOL";
    String[] matchWords = { "KYRBIBHQMYTLOMPG", "QMYUTRMQRTZFTBIEQIYAMAPILGMCNKCJOHFXAJVJEUNSHED", "ALZDJRTCXRGYIOKOWLVPMEANKQMQHLQHNSFKWZ", "LYOYEMZRYCRIXRXOQWXGJGKSSJIOSOH", "TJILRSXJIVPNZDCVAPBNXQICAWJOJXCTYYTJWPK", "ACZGOHUHBBVTKMKIAOSKQMGSDPILGRNEZLYMFBA", "PUDTUFOADF", "KTWGQFWIULKYSFYZRLLLHGBH", "TAIEKRCXG", "XJXKCAZXFZK", "KZZEPHXMEAYKJPSLD", "CXYDLPP", "TAEBOSKGNUPWD", "CU", "UAGCQKYVRPRVVBIGRUSSTUEURSNPORENLDWEUGRXFMNCQBAD", "LCEOUTPGLXBUGAYAGNEKFLIWWINQHCRBGNZDTHDKVHXNMZLQ", "TOIJXOONFXDZ", "TMRTOOMGSXPJRWKOJ", "BSGZVJUVAZEOOITMTWWPFJUXJPIABAHCGSQWORRFQTIDL", "BRPFTQGHIIJTVSQHMVGNBPOUEMDCC", "HCVYTJXZIDAXR", "LQFFZQPWIEIXRBYJUKYNBZUNJTXZSPUQSEYLDWTAIQIRJFJQ", "UCUYGNWIZYOPZODUZYHVKQUUGC", "QTUUBVFAMRNDV", "IEWHGRSXXNYRYDTCUOAFKSLUTULMAURKEYEXGTXNWLHOWUX", "UMPKQENAMICBSE", "DFJJAYWQQYFKTCFKZBIEWEUXFBRXWIJIKYLXJQKT", "WVXBTFEWKQCSXUANFBMDKFILBGZSMVKTXMWPWEMW", "TXFYTVJUFCAOABPNNIMOCXWPRUDXLVRXIJEZMD", "CUTEFVYAZGTIV", "IKXPXMKTOIZ", "EZWUPJWJKDJBCCXRWKFIUZEKYJPXSIHT", "AKLWVDCCU", "EWOQLYBSO", "K", "UTYLOMTOEEKVFHBAYKUXAFW", "JCMWRBXTEWIKUAWXLJIFEM", "ACTXCZNTAOHBIPQVJXETCS", "MFLIVTVKKGULTHMBIJAXAO", "LTYLNYGMITMCAJQ" };
    assertEquals(625, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case31() {
    String matchString = "ZOCSBYYMQPBRWKFJEYPHSDG";
    String[] matchWords = { "Z", "LCZSMXKLJEBHZUMQACGSUPFMTAPRJO", "OOCOSQZYCTKCQGNQNXCTTBIUKSWTCUPHBQSRZRGJQXLNYJLPA", "QVWJMSITUGFZJATOYVIDOSYRNHLUSLPPPCFOUX", "B", "WCXCWYPRKAWMQNQCGVDRYFECYVVEJMBUVOVPMQKZCKGLS", "COKYS", "M", "FWPRYHDIMPRDBQWYKJJOHUKQGRGKLHN", "IQQOIWVQZRPYEGEQKULMQKAYDBLGRJWQJLCALLYFOEJTJZIZ", "QAGIDCCHGIJSEBLOASGDYCBLN", "HWNUBLQUFDINRGGK", "XOSOPBIIWSKRWLZDVEDIZUL", "KX", "MWNFV", "NYQGGROSCQUCUIMPEWKJVEIRJCREYPK", "THKFVTWESGSLNNMIQCKZCYMNWF", "RBCQYXKGJLVRIQSBYECIODKKYKONBZSIRFPFDIDUWCI", "KPDXDPCSELLLO", "YHDPGEMPSSVLNCZSRUICRQXNII", "QSNQDR", "GWTPJGMSODQRUWWDNHCRAHFDXRHDHJJKJVKKV", "IXPCSPUSEJZNQKMRGBONZZVH" };
    assertEquals(368, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case32() {
    String matchString = "DL";
    String[] matchWords = { "AZDKRONKDCVOSMGDDDNTMWVHV", "YRZTTCQKUKXPOQFEZORLRPBIMAKHFSLRANYHHCAYGSSEAR" };
    assertEquals(2, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case33() {
    String matchString = "LFIBSNFXPF";
    String[] matchWords = { "NHOAWYDNVWQKSOTGCLVTSXHIRYCWYLBVHHZONS", "CEOGKQZHANKDFDUCFKT", "OVOOYTJVSPWZZITIJ", "ZGRNVEQAYWTKTSJKNCVDBIPDUSHNWMZWKOQFAYWUSD", "HNHFEIYWAZKSMNRWHMDQYWSPF", "VXTSRRARNKYDMGMALRCZSZYZT", "OOJFURPKASOZRUFKKIBAQRDERGSJRMJNYZVCMCIZRXODTF", "NEUOVUHFAIZFDWENOMRXCO", "KXTRCULSPZRRLKDQNBMYZPPFNOBJQTLSNQ", "FYPWZYWUFYOKIINFUQJ" };
    assertEquals(52, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case34() {
    String matchString = "EIL";
    String[] matchWords = { "RLECSLLSOLZJBGLLKH", "WICDZQNNHOMRFAYECGWTLQECQIUIJPAL", "IGJOLOWGSGVLCTWEOPDAKJMWLQ" };
    assertEquals(5, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case35() {
    String matchString = "WCCRAODXC";
    String[] matchWords = { "PGW", "DSMFEXQEBCPAELHKETOF", "ESVOWVBYVKPNISNECMXRYXEUUAOYNKWHEQYIHXRLQCBO", "DMHCVTKYWYLGIVEXHLNBEJGRAGPRBRZZYZYBZUVRNBKUS", "UPAUFBZJDUFJJHDLGRKP", "BFWAFEKOZOSQVAAGYTTQUMAZHBCJJTZPNLBFVUSPOX", "RNKFLQDOCBMHECJZMPCENWOMRUU", "GZGWSFKSVRCKHPHWBXLKHRRMRONOREUW", "IFOPC" };
    assertEquals(119, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case36() {
    String matchString = "BHLBBGOV";
    String[] matchWords = { "HIWTZPUUFEKACVWPVTOWLEMWPCDIBNVQZMVKYVFMI", "UDMTCJDHTHSP", "WTWRDJVKZUGJMXAOQADROSAFLS", "RIBQRQIO", "DDXEICXTRTBAAIBPPB", "BATSLPGRYHMDSKTQGLTSPMQPFCR", "FXXNDKCLEWUVZWDAOSXITW", "NCERDBFJOZJCRAVFVQNYEPFNBBRUGXOLXT" };
    assertEquals(96, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case37() {
    String matchString = "UHNVOEKAEKBWXPQJLWU";
    String[] matchWords = { "SGEQESELJFZNJXVKJOYTTAGCUQV", "RWUBBMLHVVCKBDFZCMBBF", "NJMTLJLGIWCFBRGKBIJIBPNMFNSODBXRKVKUUERYHT", "OVAATUVRXTDSWBTMLMUKYLLYDNUUHRBQWY", "WULRBLTHLSILTLPEOZRZHHKLVXTFLACFLR", "EEAPVDZFXG", "OYDDYGSPJUDGOFKGLHLIVY", "RJLGQPEEOTZARJBAMYV", "YAAZAGQLPYEORCLEOZLFWUJPRTXLLZRYACBCEBVROFJHLYOF", "YYDPJSEMIERNTHERPCZGHKQUTXJZHZHLGFJYGAZWFFGDZLO", "SFJLKFGAQWGFDDBJCBCKNTLVMYCFAQIKJDBXIOBQPPFFIDO", "BHXHGDKXUIUDYSPGESHQRKLLRNDBGMHXGRHVNUYHXIWGW", "WHISWPOVTCIJJQHXSLDNJBHOQYIPMSXIFWMZNHTLQIFXGAV", "PJQKEQMLBDPCFUBEIWKGLWEBVOZCF", "IMFEGKBXWQXPZATJF", "ZJUJQHHFJKPCVJCZRJMMTPEISMWTNJAONXZCDCOXJAAQGK", "UQPTQBKFOQBCRMSNGGLTUT", "DVXCXYBW", "MKPVFWLWUBH" };
    assertEquals(431, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case38() {
    String matchString = "ZIKJIEJWRNYMBGTFJMRGIYUCTFSCUV";
    String[] matchWords = { "MHENFUPBDUDMZBGGMHZNGDQGVAQKJZKUHWIYYJZODWVSCIDMEH", "LVVBDXDDWXFRUWGVVBJCAMMKWFTEVRFAFSIYTUPGRONSYQLSFD", "LUGKSEHFMDXVRCIR", "PRYGDBDEXADPFDONRRGSLJN", "RMUQOQMUBTWDGLFNVNTISDPQNQSVEMBCGBXCJXJAECDKR", "IVXEVMDZAN", "MSELKMJAHIOCSZWSTMRJELBOZNQHIBVQJCLBPILSRMXETHYMI", "XEEQWXP", "MYQZNIXURXGIHHDWWWCUALVCFMJGXNGNSST", "TFZCFTNGKOCPMKZIOLHREDE", "YSAXQVQKOIZPMLEX", "CFMOUWDVEGRWJSEYMQ", "TNVWBZXDYLDMGTNYQLBFVCEUJBTTOYTDFSQ", "JSGXYGUW", "TTJBWXIHJSDRETRPJENBNONWFYIOQFHUCK", "TFIXWCDNFUUFNSWQRWLQLZOLWTMLU", "GKIGXCUJFFEJJGNEPYXFENAKTJV", "ANNZMU", "DLQNRZYC", "ORGKJOYKBSDWKCRNAN", "SPEI", "CLPUOTEYZGQEJSRJFOMKCUBVBKZYCDU", "JURWCLIQYUFLQJDJBCZYEFSMUPUENOXKQVGQVRDRYURY", "HACJJYBTTKDTXBUDUOBEZXCO", "UDGFSDABMRUNLJTUWEKFBDMVNJOSBKHV", "JFFPVRPBWHWZFGEGJHXYCAWVGNFV", "YAZZLFDXAHPRKQOTBZAVUFJZAIJUBBSLAVKGBYFJUIBKLZZ", "KWAJUCN", "HMUJSZLHCXDASULUMRFENIEAUECGGPHHD", "VYRGG" };
    assertEquals(579, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case39() {
    String matchString = "YISXMOPBXBNRSGQTJTITZXDTMFEGYX";
    String[] matchWords = { "GKYUPTZMEOZZPMWAWQVNDPCFAIJOPRMYYFB", "ZAPXIHCWQNWKVFPKWSBBZYJIMXOFQGPWYRRJIV", "UVCJFOISGUWYZJYJGNXDFGMBYARKJQPUDHDWWYCQTTQNQRFYJP", "YOUIWUBYOATBDJCQYOTIMWXBXXFXZKVLMRT", "NNDJM", "USTAKZKRBQNXYOV", "RPE", "YFGIOMMTORTOPCZEOVJDWBFTBRABAUJOXAMWXBJBIVOY", "DKAXQGLK", "YDRUFGPKPDXIQHCKQCIXBDUMHIWVHOCV", "QXRCEQXZCNYHJHHTNORYG", "CUYZJGROPY", "HUYTSFTORUNAFLSUEOEYOICVZIGRTYKKKPSURQNIDMC", "JQFHQFJUAGLOBTNEMTT", "QOAJQTPQMMCDFFNSLTIZQGOVXTUKSBECNMKZRQJQWXHW", "YDXONZEDJEZMNLCQMDVTDJEDIUWEBQTZ", "GLDQTFKAOAPZJZVVNTFHHDIZRPBRWNUTXFEVRKHKPOPWKJPC", "WDGVMTANVY", "QDJWICVMJMMTFJJZDIM", "NFJSMOZRPRVOHDHFWSVZCGTJGJDDGDQVIHJ", "MQISDKESNLMNZLHHKGBE", "WMFONCUAXOGMUGAOMZSOGPNKPTLVTXTAHYPFPVVXQTJPAF", "QODJX", "WJZYNT", "RWBCBBYUHRFTSZLWOYUDJUJULVRMFLJHZWRJ", "RJAOKLWNBBBNGFIVECRS", "YLJEFLRAVHNQVYNDUVCQYEX", "SGC", "AXQJYAJKDKGLH", "UIWGVYMNBVFWHLCSXSYJUKALDDQDDUBUGVDQYTOUPDRDEQ" };
    assertEquals(434, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case40() {
    String matchString = "GOWC";
    String[] matchWords = { "UBCG", "UTWDOBO", "VXLUQLNMENVKMPRQISDOPWABRQMARVUGUWTS", "CGCFLFLAIBIWLBHDXQMFEFRNKKWBZQZOSDUAOKKEDFXPQ" };
    assertEquals(52, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case41() {
    String matchString = "CDZNFFNNBJX";
    String[] matchWords = { "GOVIOKWRQAKQCQARFDCWJRPJE", "FBOWXHDKRPYSYN", "DPWVFKBRZJBZZUMKEDZFVYOKE", "JZGCTFVUNSQEBDVGQDNOLZBR", "ICJYTWPIAHFI", "WMCIFTACWNKEUHRNVPUXUFLGUKVSGQSWHGHOVCBPAAKTYE", "KLYSFWJZQJOUMAVACNMYNEYYPWAHSC", "LWTQTBUSNLZWNYJXRXYHPLMFHVRPDRNB", "ZKNEBEKPLSNUBMGCL", "AVWXQYHENLGZLEENMWJVRO", "DZNNVOPBHZRZFAXFBCSWYKK" };
    assertEquals(51, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case42() {
    String matchString = "KWOV";
    String[] matchWords = { "KMT", "MHYAYSXUVOLVHVZUXWJSHNIXICLPDFXGJHDNDR", "MQQDZISWUOLZUAKUEJYNSIR", "BVHPMUVILGULCJR" };
    assertEquals(36, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case43() {
    String matchString = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    String[] matchWords = { "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA" };
    assertEquals(2401, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case44() {
    String matchString = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    String[] matchWords = { "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" };
    assertEquals(49, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case45() {
    String matchString = "ZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZX";
    String[] matchWords = { "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO", "TOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTOPCODERTO" };
    assertEquals(-1, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case46() {
    String matchString = "FIND";
    String[] matchWords = { "VERYFAST", "OPINION", "SPENDING", "ODD" };
    assertEquals(3, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case47() {
    String matchString = "TOP";
    String[] matchWords = { "OUTTHERE", "FROM", "NOPQRSTU" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case48() {
    String matchString = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    String[] matchWords = { "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case49() {
    String matchString = "A";
    String[] matchWords = { "A" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case50() {
    String matchString = "H";
    String[] matchWords = { "UYTUYWTEUYTWUERTWUETRUWYRYUWETRUHWRUTWUYWERT" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case51() {
    String matchString = "K";
    String[] matchWords = { "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case52() {
    String matchString = "A";
    String[] matchWords = { "B" };
    assertEquals(-1, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case53() {
    String matchString = "OPOPPP";
    String[] matchWords = { 
        "OPOPP", 
        "PPPOP", 
        "POOPO", 
        "POOP", 
        "OOOPP", 
        "OPOOP" };
    assertEquals(3, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case54() {
    String matchString = "OMLO";
    String[] matchWords = { "MNMOLNLOLL", "NMNOLOMML", "OMMMNLOLLM", "MNLOLOMOO" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case55() {
    String matchString = "WWVVWVWV";
    String[] matchWords = { "VVWWVVWWVV", "VWVVVVWVVW", "VVWWVWWVWW", "WWVWVWVWVW", "WWVWVWWWVV", "VWWWWWVWVV", "VVWVVVWVWV", "VVVVWVVVWV" };
    assertEquals(2, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case56() {
    String matchString = "UTUTUUTTTT";
    String[] matchWords = { "UUUTTTUU", "TUUTUUUT", "TTTUTTTU", "UUUUUUTT", "TTUTTTTU", "UTTUTUTU", "UTTUTUUU", "UUTTUUUT", "TUTUUUUT", "TTUUUUUU" };
    assertEquals(9, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case57() {
    String matchString = "VUUUVUUUVU";
    String[] matchWords = { "VUVUUUV", "UVUUVVU", "VVVUVVU", "UVUUVUU", "UUUVVUV", "VUVVUUU", "VVVVVUU", "UVVVVVU", "VUVUVVVU", "UVVVVVU" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case58() {
    String matchString = "EEA";
    String[] matchWords = { "TOPCODER", "TEST", "GEGA" };
    assertEquals(8, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case59() {
    String matchString = "TOP";
    String[] matchWords = { "TIK", "PPPO", "OP" };
    assertEquals(5, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case60() {
    String matchString = "FIND";
    String[] matchWords = { "VERYFAST", "OPINION", "SPENDING", "ODD" };
    assertEquals(3, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case61() {
    String matchString = "TOU";
    String[] matchWords = { "STATE", "SDOU", "GIMMEU" };
    assertEquals(5, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case62() {
    String matchString = "BBBBBBB";
    String[] matchWords = { "ABCD", "DABC", "CDAB", "BCDA", "CDAB", "DABC", "ABCD" };
    assertEquals(9, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case63() {
    String matchString = "TOP";
    String[] matchWords = { "OOOOOT", "OPPPPPPPOOP", "OOPOOOOP" };
    assertEquals(4, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case64() {
    String matchString = "AC";
    String[] matchWords = { "ABA", "BCC" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case65() {
    String matchString = "FOREVER";
    String[] matchWords = { "ORF", "OPAQUE", "RESET", "SOME", "VI", "EAST", "ARC" };
    assertEquals(15, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case66() {
    String matchString = "TOP";
    String[] matchWords = { 
        "TT", 
        "ZZZZOO", 
        "PAAAAP" };
    assertEquals(4, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case67() {
    String matchString = "AB";
    String[] matchWords = { "ABAAA", "ABABB" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case68() {
    String matchString = "TTTT";
    String[] matchWords = { "T", "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOT", "T", "T" };
    assertEquals(129, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case69() {
    String matchString = "PHQGHUMEAYLNLFDXFIRCVSCXGGBWKFNQDUXWFNFOZVSRTKJPRA";
    String[] matchWords = { "PGGXRPNRVP", "STMWCYSYYCQPEVIKEFFMZNIMKKASVWSRENZKYCXFXTLSH", "YPSFADPOOEFXZBCOEJQ", "VPVABOYGPOEYLFPBNG", "LJVRVIPYAMYEHWQNQRQPMXUJJLOOVAOWUXWHMSH", "CU", "XCOKSM", "ZKVATXDKNLYJYHFIXJSWNKKUFNUXXZRZBMNMGQOOKETLYHNE", "OAUGZQRCDDIUTEIOJWAYYZPVSCMPSAJLFVGUBFAAA", "VLZYLNTRKDCPY", "SRTESJWHDIZCOBZCNFWLQIJTVDWVXHRCBLDVGYLWGL", "USBMBORXTLN", "CSMPXOHGMGNKEL", "FDXOTOGBGXPEYANFETCUKEPZSHKLJUGGGEKF", "DQZJENPEVQGXIEPJSRDZJD", "ZUJLLCHHBFQMKIX", "WZOBIWYBXDUUNFSKSRSRTEKMQDCYZJEF", "UHMSRQCOZIJIPFIONEEDDPSZRNAVYMMTATBDZQSI", "EMUVNPPPSUACBAZUXMHECTHLEGRPUR", "KDMC", "PPWEQTGJOPARMOWZDQYOXYTJBBHAWDYDCPRJBXPHOOHPV", "WQYUHRQZHS", "BNFUVQNQQLRZJPXIOGVLIEXDZUZOSRKRUSC", "OJBRZMX", "ZPOWKJILEFRAAMDIGPNPUUHGXPQNJWJMWAXXMNSNHHLQQRG", "UDLTFZOTG", "JTNZXUGLSDSMZCNOCKVFB", "JFRMXOTHOWKBJZWUCWLJW", "RIMPMYHCHZRIWKBARXBGFK", "BCEYHJUGIXWTBVTREHBF", "CPXIFBXVFBCGKCFQCKCOTZGKUBMJRN", "BSZTSSHFROEFWSJRXJHGUZYUPZWWEIQURPQ", "XIQFLDUUVEOOWQCUD", "HNEFNJHAIMUCZFSKUIDUBURISWTBRECUYU", "ABFX", "VKDZEZTOIDUKUHJZEFCZZZBFKQW", "PQZF", "KFOBUCDHTHXDJGKJELRLPAXAMCEROSWIN", "DPTPCCLIFKELJYTIHRCQAYBNF", "FXNXVGZEDYYHNGYCDRUDMPHO", "ECKOTRWZ", "SPOFGHFOZQVLQFXWWKV", "FXDYYGMDCASZSGOVSS", "DKJGR", "CWMBMXRMHUYFYQGAJQKCKLZNAT", "XQKQOYZWMYUBZAZCPKHKTKYDZIVCUYPURFMBIK", "GEKYRGZVXDHPOAMVAFYRARXSVKHTQDIHEJ", "SIGBHZJZUJXMMYSPNARAEWKEGJCCVHHRJVBJTSQDJOOTGPP", "NFPFYCGFIEOWQRWWWPZR", "QMETOGEPSPXNVJIUPALYYNMKMNUVKLAHS" };
    assertEquals(1107, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case70() {
    String matchString = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT";
    String[] matchWords = { "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case71() {
    String matchString = "TOP";
    String[] matchWords = { "PPPTXYT", "OXYTXYO", "PAAAAPA" };
    assertEquals(1, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case72() {
    String matchString = "EEA";
    String[] matchWords = { "GEGA", "TOPCODER", "TEST" };
    assertEquals(-1, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case73() {
    String matchString = "TOC";
    String[] matchWords = { "POT", "POPOR", "DOC" };
    assertEquals(1, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case74() {
    String matchString = "AAAAAAAAAAAAAAA";
    String[] matchWords = { "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case75() {
    String matchString = "IJMX";
    String[] matchWords = { "ABCDEFGHIJ", "IJKLMOPQMN", "MNABCDEFGH", "GHXXXXJJJJ" };
    assertEquals(18, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case76() {
    String matchString = "AAB";
    String[] matchWords = { "AAA", "AAA", "AAB" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case77() {
    String matchString = "AA";
    String[] matchWords = { "AXA", "XAA" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case78() {
    String matchString = "AB";
    String[] matchWords = { "AAA", "ABA" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case79() {
    String matchString = "FIND";
    String[] matchWords = { "VERYFASF", "OPINIONI", "SPENDINN", "ODDDDDDD" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case80() {
    String matchString = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB";
    String[] matchWords = { "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB" };
    assertEquals(1225, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case81() {
    String matchString = "FINDLMNOPQRSTUVWXYZLMNOP";
    String[] matchWords = { "VERYFAST", "OPINION", "SPENDING", "ODD", "TALHJHJL", "MIOOOMHSJAKM", "YUIYIUNJIOJNJIN", "YUIYIUOPPPWE", "YUIYUIPHUIYPUIP", "QRRRERQUYUTQTUYTQTYUTQ", "TUYTRQYUTUYQRTUYTRTYUR", "FTSRTYRSYIUYUISUIOS", "IOUTUIOUOITUIOUIOUTI", "YUHJKHKJHU", "HVIOPIOPIOV", "UIOUIUIWJLKJWJKW", "YUIYXUIOUX", "YUIOUOINYNHKY", "ZUIIYHIZHUIOUYOZ", "FHGLGHAFGSHFLASVGL", "GSAMHSAMGHSJDAGM", "GSHJGSNHGAJNHGSHNKAJSHN", "OGASJAOHJAGSJOJAGSJO", "GHSGAPHJKHP" };
    assertEquals(55, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case82() {
    String matchString = "BAK";
    String[] matchWords = { "ABCB", "ADBA", "KDAK" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case83() {
    String matchString = "XX";
    String[] matchWords = { "XXX", "XXX" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case84() {
    String matchString = "AAAAAAAAAAAAAAA";
    String[] matchWords = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case85() {
    String matchString = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    String[] matchWords = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case86() {
    String matchString = "ABC";
    String[] matchWords = { "CABBBBA", "BACCCCB", "CDCCCCC" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case87() {
    String matchString = "DFCFBG";
    String[] matchWords = { "ABCDEF", "DFE", "ABC", "FDC", "BCD", "AG" };
    assertEquals(11, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case88() {
    String matchString = "AB";
    String[] matchWords = { "XXXAXXXA", "XXBXXXXB" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case89() {
    String matchString = "ABC";
    String[] matchWords = { 
        "AABBA", 
        "CCAB", 
        "CCCCC" };
    assertEquals(1, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case90() {
    String matchString = "TOP";
    String[] matchWords = { "AATTT", "AOAOAO", "PAAPAAP" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case91() {
    String matchString = "ABCDEFGHIJKL";
    String[] matchWords = { "HDJKFJKDJFBBHHSDHBA", "NMASKDHDASDDASDADASDASB", "ASDASYAHDASJDKASJDKYYC", "KJSASPJJKSAIIIKD", "ASKHBVFJSJAKSLDLASDASSSSSSSSSSSSSSSSE", "ASDASJDHASLAHHHHHHFFASDASSSSSSSSSSSSSSSSSSSSSSSSF", "ASDABFJJAKKAHJJAKKKGGGGGGJAJSDJGGG", "ASDKAIFGABBGBSGHHHHHHHHHHHHHHH", "ASDAKSDAJSDASNBAJIIIIIIIIIIIIIIIIIIIIIIIII", "SDASDJJJJJJJJJJJJJJJJJJJJJJASDSDJJJJJJJ", "BBFASDADKJJJJJJJKKKKKKKKKKK", "ASDNNDASDLLLLLLLLLLLLL" };
    assertEquals(120, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case92() {
    String matchString = "ABCDEFG";
    String[] matchWords = { "BBBBBABBBAAAABABA", "CCCCCCBSBSBDB", "DDDYYYCYSYSHDNCHCHDC", "ABCBABSBDBDBDDBFBD", "YHGEEFSREEGGDDDDSF", "UUGHHSJJAGGGFFFFRFD", "EUSHDNFHAHGUHGHGHGGG" };
    assertEquals(9, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case93() {
    String matchString = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    String[] matchWords = { "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA" };
    assertEquals(1176, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case94() {
    String matchString = "AB";
    String[] matchWords = { "AXXA", "XBXB" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case95() {
    String matchString = "AAAA";
    String[] matchWords = { 
        "ABBBA", 
        "BABBA", 
        "BBABA", 
        "BBBAA" };
    assertEquals(0, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case96() {
    String matchString = "PP";
    String[] matchWords = { 
        "PAAAAAAAAAAAAAAAAAAAP", 
        "AAAAAAAAAAAAAAAAAAPP" };
    assertEquals(1, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case97() {
    String matchString = "AAAAA";
    String[] matchWords = { "AOOOOOA", "OOOOOA", "AOOOOOOOOOOOA", "AOOOOO", "AOOOOOOOA" };
    assertEquals(19, matchstring.placeWords(matchString, matchWords));
  }

  @Test
  public void case98() {
    String matchString = "EEA";
    String[] matchWords = { "AAAE", "ABCDE", "BBBBA" };
    assertEquals(1, matchstring.placeWords(matchString, matchWords));
  }

}
