package topc.test.sorting;

import junit.framework.*;
import org.junit.Test;
import static org.junit.Assert.*;
import topc.sorting.*;

public class FunctionDependencyTest {
  FunctionDependency functiondependency = new FunctionDependency();

  @Test
  public void case1() {
    String[] funcs = { "B", "C", "A" };
    String[] depends = { "1", "", "1" };
    assertArrayEquals(new String[] { "C", "A", "B" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case2() {
    String[] funcs = { "B", "C", "A" };
    String[] depends = { "1", "", "0" };
    assertArrayEquals(new String[] { "C", "B", "A" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case3() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8" };
    assertArrayEquals(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case4() {
    String[] funcs = { "K", "Z", "Y", "X", "T", "R", "C", "B", "A", "E" };
    String[] depends = { "", "", "1", "2", "3", "4", "5", "6", "7", "8" };
    assertArrayEquals(new String[] { "K", "Z", "Y", "X", "T", "R", "C", "B", "A", "E" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case5() {
    String[] funcs = { "B", "C", "A", "AAAA", "BBBBBB" };
    String[] depends = { "1", "", "0", "", "0 1 2 3" };
    assertArrayEquals(new String[] { "AAAA", "C", "B", "A", "BBBBBB" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case6() {
    String[] funcs = { "M", "BBHHOMOXUZ", "SKFYNVNOIANBMPZKLYFDPYGDEMXQUSJDWCRYME" };
    String[] depends = { "1", "", "1" };
    assertArrayEquals(new String[] { "BBHHOMOXUZ", "M", "SKFYNVNOIANBMPZKLYFDPYGDEMXQUSJDWCRYME" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case7() {
    String[] funcs = { "APDIGTMAZKOBHLQKTOVMWSHTPDIWOLGZAZYBNPDV", "HPSCSVDTCTBFKYOPTVEAXKXC", "WSFLWPGPTFRYGJMPCPYHH", "BDIWRZXBQRNKERVWTATOXLCQKVNDXQLNLB", "XLAWAANPBJMFFJJDUROMLX", "RRATOSCHVJFFMHTUUURFDDMLRYY", "QIKNGIGXVTNRDGYYXLDGQOZC", "ENAZCONQVHPWAKJKEAXBPMKHZPQXMGMHVWWRFMZR", "ZNEWMLKMBUGMTXUKPTFNJOVRYU", "IPDXVWBWWIKAFBDHXQTNHMK", "SEROFENZNUG", "KKAOBWNKYJTYWCFSDSJODRDQ", "YXWUZPOSXEYLABRELIULAOMNRKXTSDEORQVFBMHHWGRBRJALQS" };
    String[] depends = { "7", "", "", "11 8", "", "7 2", "", "4", "7 5", "11 2", "7", "", "11" };
    assertArrayEquals(new String[] { "HPSCSVDTCTBFKYOPTVEAXKXC", "KKAOBWNKYJTYWCFSDSJODRDQ", "QIKNGIGXVTNRDGYYXLDGQOZC", "WSFLWPGPTFRYGJMPCPYHH", "IPDXVWBWWIKAFBDHXQTNHMK", "XLAWAANPBJMFFJJDUROMLX", "ENAZCONQVHPWAKJKEAXBPMKHZPQXMGMHVWWRFMZR", "APDIGTMAZKOBHLQKTOVMWSHTPDIWOLGZAZYBNPDV", "RRATOSCHVJFFMHTUUURFDDMLRYY", "SEROFENZNUG", "YXWUZPOSXEYLABRELIULAOMNRKXTSDEORQVFBMHHWGRBRJALQS", "ZNEWMLKMBUGMTXUKPTFNJOVRYU", "BDIWRZXBQRNKERVWTATOXLCQKVNDXQLNLB" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case8() {
    String[] funcs = { "QGLRTNVAJXIVFWCBKBONMLQZJJRNTFEFP", "EZECNSUZ", "UNJFMJCOENJWEZYJGKUUJCSHLMJILLSUYMGORMADJFNRZ", "YBBATNJIKEUGKCLLPLCRNYVVJSWGYXTHWGTHCINKUGWEGTA", "EGAWFJGQRQLGRMSGFHCUWBBMKXKXXFMEZPNQIRGAMJXXTHFZP", "XFCQISTPFDJJBFOYHQYTBEHIZVEHMPM", "XGWZNHKQBLTDBFKRFOCPZFQWNSAIUH", "RYMDAAIVNTOBLUJBFACTAIH", "KHFG", "LFZFTRZPAAQPACGDM", "CXNUAZIPDKAZZFTMQRCJKQWMIIRTMELTAFMKWJIHIE", "REWYIYLVHLCUXKBNDRLYGJNQOJCN", "EFQXWGIVLXRBDVCKLFHYXWGO", "GWXNBHJGWBKEEEFQMKJNTCFXGUUFISUK", "WCJEVCAPPUAQTOBOWWQUAKKMVJQTNBDNLUZILUC", "ASMMKBHPUEMVEELKDHEAAPLXJQILLRZTEVPRIX", "YYZCTVRNJNHWBMNVIMIMLBVEATVKBWFEADYNNGBFU", "YUTEZUFMMMFQMFZPIXOHDXGESUAUMACQYXBJEX", "FTHRLSRZLZDCWWNBUYYEQCMRXYGVJFSWKVASSTBMDMDPWN", "UUGAVDBDYKPXZLHRNWIRGTSWWJLYXO", "QXYJZYOONIWOXL", "NJFKYGEVTROAOPZHHDUAXYKDSDECMFDYBIJTIVKHBAYU", "DSHRRVVNXDGSOXWAYXYDCKSC", "WITJKMVNAVRTMEWWABQHZ", "WBRDVETCYBKHAIKYIWUGJYCTQXZYTWTEQPKVHCTQNTAKZKIWOE", "UYTDLLBYDDURHZQYGTKWDMONZVCOBFLISNSYYZHTYYQCAPE", "TIQNJMNWIRZO", "YTYIIIZCWSJQJYLG", "GDPDHAC", "QZRSOQKKC", "XMEQQTHRMOFERFXPAKYXEFYSICKHDGNJT", "THJICOT", "ZPCMDNIFCMHGNAOZZXGDCZDLQJCGEZTWTF", "RAUVUHEHYITRMWWNTU", "HOHHOEMVUHDJEJOITGBK", "ZLXXVPOUSRNOQHLOSDZCBOMIGTBLTYPZZWHPDRLVRTHFWEG", "ODJZKQZQYSWDMLCGPRWZOQXJHBPNJLCHKMWSLXGVEKQCO", "KNNVOJ", "AJFHRITHQKPV" };
    String[] depends = { "", "21", "", "27 28", "34", "", "5 18", "20 14", "7", "", "13", "", "", "", "15", "", "12 22", "19", "34", "8 36", "5 28", "", "3 15", "", "4 31", "28", "", "", "", "35 30", "28 6", "", "1 35", "", "", "", "10 32", "30 14", "35" };
    assertArrayEquals(new String[] { "ASMMKBHPUEMVEELKDHEAAPLXJQILLRZTEVPRIX", "EFQXWGIVLXRBDVCKLFHYXWGO", "GDPDHAC", "GWXNBHJGWBKEEEFQMKJNTCFXGUUFISUK", "CXNUAZIPDKAZZFTMQRCJKQWMIIRTMELTAFMKWJIHIE", "HOHHOEMVUHDJEJOITGBK", "EGAWFJGQRQLGRMSGFHCUWBBMKXKXXFMEZPNQIRGAMJXXTHFZP", "FTHRLSRZLZDCWWNBUYYEQCMRXYGVJFSWKVASSTBMDMDPWN", "LFZFTRZPAAQPACGDM", "NJFKYGEVTROAOPZHHDUAXYKDSDECMFDYBIJTIVKHBAYU", "EZECNSUZ", "QGLRTNVAJXIVFWCBKBONMLQZJJRNTFEFP", "RAUVUHEHYITRMWWNTU", "REWYIYLVHLCUXKBNDRLYGJNQOJCN", "THJICOT", "TIQNJMNWIRZO", "UNJFMJCOENJWEZYJGKUUJCSHLMJILLSUYMGORMADJFNRZ", "UYTDLLBYDDURHZQYGTKWDMONZVCOBFLISNSYYZHTYYQCAPE", "WBRDVETCYBKHAIKYIWUGJYCTQXZYTWTEQPKVHCTQNTAKZKIWOE", "WCJEVCAPPUAQTOBOWWQUAKKMVJQTNBDNLUZILUC", "WITJKMVNAVRTMEWWABQHZ", "XFCQISTPFDJJBFOYHQYTBEHIZVEHMPM", "QXYJZYOONIWOXL", "RYMDAAIVNTOBLUJBFACTAIH", "KHFG", "XGWZNHKQBLTDBFKRFOCPZFQWNSAIUH", "XMEQQTHRMOFERFXPAKYXEFYSICKHDGNJT", "KNNVOJ", "YTYIIIZCWSJQJYLG", "YBBATNJIKEUGKCLLPLCRNYVVJSWGYXTHWGTHCINKUGWEGTA", "DSHRRVVNXDGSOXWAYXYDCKSC", "YYZCTVRNJNHWBMNVIMIMLBVEATVKBWFEADYNNGBFU", "ZLXXVPOUSRNOQHLOSDZCBOMIGTBLTYPZZWHPDRLVRTHFWEG", "AJFHRITHQKPV", "QZRSOQKKC", "ZPCMDNIFCMHGNAOZZXGDCZDLQJCGEZTWTF", "ODJZKQZQYSWDMLCGPRWZOQXJHBPNJLCHKMWSLXGVEKQCO", "UUGAVDBDYKPXZLHRNWIRGTSWWJLYXO", "YUTEZUFMMMFQMFZPIXOHDXGESUAUMACQYXBJEX" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case9() {
    String[] funcs = { "IEEIGIXNOAMGKQ", "NBNOZZHTZGXYGBSCMU", "EDDTNZIKFFXYYKRFYGPBKYNIUPOSSVZ", "ZWPSVPWTKES", "MQJWRWLLNUMABXLSOUQQQJXIJTYRAABZNR", "ESSUPQXXQUABWDTONCOIURXJWCRFAOXDUDTXQGRNVAXQJA", "NNMKFFH", "WZSANZDTUJYVCTYODGTMLI", "HHHTSTURTHRWAFAVPQNEXQCFXOOCPVYTRRNY" };
    String[] depends = { "2", "3", "4", "4", "5", "", "3 7", "", "4 1" };
    assertArrayEquals(new String[] { "ESSUPQXXQUABWDTONCOIURXJWCRFAOXDUDTXQGRNVAXQJA", "MQJWRWLLNUMABXLSOUQQQJXIJTYRAABZNR", "EDDTNZIKFFXYYKRFYGPBKYNIUPOSSVZ", "IEEIGIXNOAMGKQ", "WZSANZDTUJYVCTYODGTMLI", "ZWPSVPWTKES", "NBNOZZHTZGXYGBSCMU", "HHHTSTURTHRWAFAVPQNEXQCFXOOCPVYTRRNY", "NNMKFFH" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case10() {
    String[] funcs = { "MYELRDPQFLHYIEEFVXHYNKHUUOFFMWKMDWBWECKDWARBYPDQTO", "EWMWQMS" };
    String[] depends = { "", "0" };
    assertArrayEquals(new String[] { "MYELRDPQFLHYIEEFVXHYNKHUUOFFMWKMDWBWECKDWARBYPDQTO", "EWMWQMS" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case11() {
    String[] funcs = { "A", "C", "I", "MM", "T" };
    String[] depends = { "2 3 4", "2 3 4", "4", "2 4", "" };
    assertArrayEquals(new String[] { "T", "I", "MM", "A", "C" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case12() {
    String[] funcs = { "SFSYXGWSBMDDFBXRIXE", "XOABPIMSYNKTSAWNBFRHLZYCIZLKHJMRPPTLRHYIDWRVSZ", "OYFPSOLYTMYYJYBMQXZQQQWVXTELOCEMOJXRXSDQOMROJOCR", "PKSNUERUPZVW", "VZW", "ZZSED", "XDUFKLQPVNMZZJLBLLBUPXAZWXAN", "ERGF", "YZIWUVWK", "NZRTLFCZKSYZAAOSHXCVFVJUXBBUVTAIIJZHKPIKRBKVRS", "TKCDUBGOAANJUEVFJLCOFLXXBPPQSJIOTUOPSFVMGIQ", "WKPR", "XATRDPQNHFWVTHNKOFUTHZYDWGKGBKGBTCTVZB", "NSVJGGALISYYC", "DRJRHRCPQSAZGXWNSPQYHMGMXDFHRKVFQNOVSEN", "TVFRHMXGZKPZPLXYJJRIIKEEZGKHJER", "DKJUFSCTFMAWPOJDUYKVTGGCMQOCDYTE", "ECLXYPNWPOQ", "BVQPQAWXEG", "PLRHAUXTJZBPFLPDHNWHHHLYEFGKQNH", "TLJYWZGYA", "XIDMGBZBPXVNJQZLROYOOJHLIBO", "AFNRIQNIRWGZLNSZSEJEZHQOERRGFQBMHEJDYOHH", "CO", "BCUZS", "TCVRSUIS", "PRTGKGHXTLEJPN", "IDATBVLBOBWTZO", "XNHJKATBD", "HLLPPGXXXCLIUDMDVTMLCWVUCYRIW", "FTMQLZOKNTEWGODWWZEEZYTNBNUBNZAWCVEREISDSFTA", "REWVLXSFK", "IBDEKAZMDGGCERPJOYUKEGODFVYTCHSKMKZBPF", "NXGLBVASVXT", "XBOCIELXNYDVZBPNDHCOLHQTWHENJHSRBGBFBUFR", "Y", "PUGECGETXNLXQFFFZGWIVPLVUOHQSZSMZBGREFWDFBOP", "ZGEZUUCRJIWUDUGLFYAVDE", "DSAIJHTGQXBBLFGQPCMFCCMPFNGMCGEPK", "JJHNFKPTHWGVIKBPPYPRMELQIYQSKBJ" };
    String[] depends = { "18", "", "0 3", "27", "24", "11 35", "", "14 25", "1", "", "", "22 22", "31", "16", "2 23", "25", "", "", "3 20", "", "16", "23 19", "6 31", "", "", "21", "35 5", "", "19 13", "11 28", "", "38 13", "31 22", "", "5", "", "5 20", "25 8", "14", "14" };
    assertArrayEquals(new String[] { "BCUZS", "CO", "DKJUFSCTFMAWPOJDUYKVTGGCMQOCDYTE", "ECLXYPNWPOQ", "FTMQLZOKNTEWGODWWZEEZYTNBNUBNZAWCVEREISDSFTA", "IDATBVLBOBWTZO", "NSVJGGALISYYC", "NXGLBVASVXT", "NZRTLFCZKSYZAAOSHXCVFVJUXBBUVTAIIJZHKPIKRBKVRS", "PKSNUERUPZVW", "PLRHAUXTJZBPFLPDHNWHHHLYEFGKQNH", "TKCDUBGOAANJUEVFJLCOFLXXBPPQSJIOTUOPSFVMGIQ", "TLJYWZGYA", "BVQPQAWXEG", "SFSYXGWSBMDDFBXRIXE", "OYFPSOLYTMYYJYBMQXZQQQWVXTELOCEMOJXRXSDQOMROJOCR", "DRJRHRCPQSAZGXWNSPQYHMGMXDFHRKVFQNOVSEN", "DSAIJHTGQXBBLFGQPCMFCCMPFNGMCGEPK", "JJHNFKPTHWGVIKBPPYPRMELQIYQSKBJ", "REWVLXSFK", "VZW", "XATRDPQNHFWVTHNKOFUTHZYDWGKGBKGBTCTVZB", "XDUFKLQPVNMZZJLBLLBUPXAZWXAN", "AFNRIQNIRWGZLNSZSEJEZHQOERRGFQBMHEJDYOHH", "IBDEKAZMDGGCERPJOYUKEGODFVYTCHSKMKZBPF", "WKPR", "XIDMGBZBPXVNJQZLROYOOJHLIBO", "TCVRSUIS", "ERGF", "TVFRHMXGZKPZPLXYJJRIIKEEZGKHJER", "XNHJKATBD", "HLLPPGXXXCLIUDMDVTMLCWVUCYRIW", "XOABPIMSYNKTSAWNBFRHLZYCIZLKHJMRPPTLRHYIDWRVSZ", "Y", "YZIWUVWK", "ZGEZUUCRJIWUDUGLFYAVDE", "ZZSED", "PRTGKGHXTLEJPN", "PUGECGETXNLXQFFFZGWIVPLVUOHQSZSMZBGREFWDFBOP", "XBOCIELXNYDVZBPNDHCOLHQTWHENJHSRBGBFBUFR" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case13() {
    String[] funcs = { "CCWBUQOFWEXMNDMNBR", "GGROBWOPWVYXSBZUHBHGBMZTHZZEUN", "EDNWRFRIPWWTWVBARZBZCTVUTWNYWFQALGKMZD", "SAUIMIOKHZPOJCEEUMNW", "PTTPYYTBMUGWLCATJWJZHNKDIGWDLT", "QLHCSESGJEAOYICTGZPEGBEHWTWCYEYGTJSZLRWTZCT", "BHHGQGSEHXYBHMYFLFMVOMZRAZWZP", "XPLUAINECQFIGLAMK", "SBTISSYMOQCTWWKYEJTTPUQVE", "NHSUDFYHFPXFNQGDZVKTCVMPUINDGBIZDIAMBPIJGK", "XRLFBXAYZYOLZRUYFWOWHMIROBAZXHNXXFFPX", "BBQVLHASZNCJQXHA", "FBARBKR", "BEDEPFOUMTQTDIIQXUROQOCMKZXXSJXUVVHQI", "BYUHISEJYOUJRQENEDUKPZDJHN", "UPXZIHISITRMRZNTUGDSVPYDIADLXHRZEZFRFOSWXWXIVUI", "CKIKYVPBVASUNHBQZIWQRIWYBN", "THWSSKYNJKGZEWOZJTTKNGOEYGZPOURGA", "NMAQUZVTGUENOFICZOJAOJUNYSJDEXFKF", "BXXZWMHVSVWRUDMGTHGSIX", "XBDAZMCJIMFEURFSXLUKQYKPHKCNOSBK", "GV", "RB", "IYZPMSKKYTBMCKY", "ULYNIECKSVQFDJALOCF", "SAG", "KFDWWHYPKNAONUQOYCWJGGOEKNUQVA", "INAKAONBRWGHFAS", "ANQOIHQVYIAKKSZTDQZMZEKNA", "LKOTGVIVFKBDVAHTJSIGDTNFWATNFLH", "X", "PPQ", "ZGPCQTCFUAJJNJWLBQLSKOGYXMJWKMFNNGPFCYS", "YOUAYZIAHINEYETGLLRNZHEENFYLLS", "JGUKIQZXPRRWCJHBMLHOQIYXYMOMLTXCPICZYRHVIVBGCUUJ" };
    String[] depends = { "15 15", "30 18", "20", "31 21", "29 33", "15", "21", "11 17", "", "13 14", "", "16 29", "", "1", "32", "", "", "20 14", "14", "30", "", "8", "", "", "", "21 7", "28 13", "33 13", "10 1", "22", "12", "7", "16", "2", "" };
    assertArrayEquals(new String[] { "CKIKYVPBVASUNHBQZIWQRIWYBN", "FBARBKR", "IYZPMSKKYTBMCKY", "JGUKIQZXPRRWCJHBMLHOQIYXYMOMLTXCPICZYRHVIVBGCUUJ", "RB", "LKOTGVIVFKBDVAHTJSIGDTNFWATNFLH", "BBQVLHASZNCJQXHA", "SBTISSYMOQCTWWKYEJTTPUQVE", "GV", "BHHGQGSEHXYBHMYFLFMVOMZRAZWZP", "ULYNIECKSVQFDJALOCF", "UPXZIHISITRMRZNTUGDSVPYDIADLXHRZEZFRFOSWXWXIVUI", "CCWBUQOFWEXMNDMNBR", "QLHCSESGJEAOYICTGZPEGBEHWTWCYEYGTJSZLRWTZCT", "X", "BXXZWMHVSVWRUDMGTHGSIX", "XBDAZMCJIMFEURFSXLUKQYKPHKCNOSBK", "EDNWRFRIPWWTWVBARZBZCTVUTWNYWFQALGKMZD", "XRLFBXAYZYOLZRUYFWOWHMIROBAZXHNXXFFPX", "YOUAYZIAHINEYETGLLRNZHEENFYLLS", "PTTPYYTBMUGWLCATJWJZHNKDIGWDLT", "ZGPCQTCFUAJJNJWLBQLSKOGYXMJWKMFNNGPFCYS", "BYUHISEJYOUJRQENEDUKPZDJHN", "NMAQUZVTGUENOFICZOJAOJUNYSJDEXFKF", "GGROBWOPWVYXSBZUHBHGBMZTHZZEUN", "ANQOIHQVYIAKKSZTDQZMZEKNA", "BEDEPFOUMTQTDIIQXUROQOCMKZXXSJXUVVHQI", "INAKAONBRWGHFAS", "KFDWWHYPKNAONUQOYCWJGGOEKNUQVA", "NHSUDFYHFPXFNQGDZVKTCVMPUINDGBIZDIAMBPIJGK", "THWSSKYNJKGZEWOZJTTKNGOEYGZPOURGA", "XPLUAINECQFIGLAMK", "PPQ", "SAG", "SAUIMIOKHZPOJCEEUMNW" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case14() {
    String[] funcs = { "JZXYSGSXUEQII", "YPAAYFPGQLGLRPEZQJHTJMLYSPU", "OLDQZFAPQFQ", "MRGPXASZQEH", "MFVBUHYZOSSROKMAYN", "VQHGZPFDRYLCVFLZBIUXNLKGDDZBIUMMQLCXRSMONWAJG", "LBOUWKVFWWOBSKPBJPDJX", "RCDDDWQSQANFANIZASHSMSKEVSKJYUMUASLCZIBVZYX", "ZYYKBWZZKPVABQZYMCPITKQMQRDJIBXL", "M", "GZPGVXASQHSGNJSADWDBOPHOYT", "VVPNUFVUJKMLXQQ", "PFBAOXMTYKLQFGFOXXINNYQJQWRHERAYGFEMZGNGPF", "BUZUTLWRUOCLFGIAXGLOYNREMCWCLHEUZ", "SNUTV", "VRIHGPZBTZO", "TRSPKQJEHIJI", "YDKOBZLZPGEKXAHEDSCGYNAQKLWRYZXZBXNZRMXRDP", "NLNHQLO", "ISGYQESCN", "EYWHSVZWMDICAFONROOTSNXEB", "UTXATECBWJDLKYDRJGCKKKRPGVWCYRCJNXOOFIYSKCXI", "DOBDIOVZKQA", "KQAGLMZFKLVW", "UMXGQNHUZTBE", "L", "TSHVITHVUL", "GAEUPDWXSPA", "ODNJO", "DHXTCZMIVXNZCPCPJNHIILIYRAXM", "KBGPKCSXOPEMYGHPR", "VTAXC", "SBBHKGCOKYAAVPW", "QPTLKXACZSOXJHS", "FJSMFMHKXQQDOJOLRVSHJLLUAHOOOKNKMRSYNNHZKNYMRGZ" };
    String[] depends = { "9", "31 25", "24 29", "11 10", "11", "3", "28 0", "", "10 11", "", "14", "33", "27", "", "", "21", "26 4", "25", "17", "", "3", "30", "10", "14", "26", "8 24", "31", "18 16", "25", "", "", "33", "", "", "" };
    assertArrayEquals(new String[] { "BUZUTLWRUOCLFGIAXGLOYNREMCWCLHEUZ", "DHXTCZMIVXNZCPCPJNHIILIYRAXM", "FJSMFMHKXQQDOJOLRVSHJLLUAHOOOKNKMRSYNNHZKNYMRGZ", "ISGYQESCN", "KBGPKCSXOPEMYGHPR", "M", "JZXYSGSXUEQII", "QPTLKXACZSOXJHS", "RCDDDWQSQANFANIZASHSMSKEVSKJYUMUASLCZIBVZYX", "SBBHKGCOKYAAVPW", "SNUTV", "GZPGVXASQHSGNJSADWDBOPHOYT", "DOBDIOVZKQA", "KQAGLMZFKLVW", "UTXATECBWJDLKYDRJGCKKKRPGVWCYRCJNXOOFIYSKCXI", "VRIHGPZBTZO", "VTAXC", "TSHVITHVUL", "UMXGQNHUZTBE", "OLDQZFAPQFQ", "VVPNUFVUJKMLXQQ", "MFVBUHYZOSSROKMAYN", "MRGPXASZQEH", "EYWHSVZWMDICAFONROOTSNXEB", "TRSPKQJEHIJI", "VQHGZPFDRYLCVFLZBIUXNLKGDDZBIUMMQLCXRSMONWAJG", "ZYYKBWZZKPVABQZYMCPITKQMQRDJIBXL", "L", "ODNJO", "LBOUWKVFWWOBSKPBJPDJX", "YDKOBZLZPGEKXAHEDSCGYNAQKLWRYZXZBXNZRMXRDP", "NLNHQLO", "GAEUPDWXSPA", "PFBAOXMTYKLQFGFOXXINNYQJQWRHERAYGFEMZGNGPF", "YPAAYFPGQLGLRPEZQJHTJMLYSPU" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case15() {
    String[] funcs = { "FNCZUKCEUVQOYQNWCBYBMEYFZFNPRRUGUVLIONLIVFZ", "LGRRBHBHJEEVHXRSSUYDAGNSNHXIPQKHGBLWASVQZESQEDJK", "XKIPYGJ", "IYYTEWXPPFGQJGLNQBMHYNZDNPPFVOQQDXYZVFBOKKQ", "GDZDDNDGKBTWFXTMZHUCFFDWPJAJBLT", "LMNZFOITNVZNLTOBKKBJDHHDOGBDA", "KEXCJFJNXLIUXFTOTPEUTPLOFKSUMAWQJCSZT", "EXPZWVXCSSEUHJEYPJQIDVOFCQLZXZAKCAFZEWDJWPPGVAPO", "EKQVHOVGBJL", "AKTTJNEGTZDSRTRTRGPUJFWUDU", "WIZ", "OAFBPHIEDMR", "THMRDGMGVJYTCENAMXAXBWSOFEJQW", "NWOXNYAPOQWOHYUKAXQDHEALEJCNMFMXTDRWSDKRTXMIB", "WSPVV", "OROSXRVQKOALSNPQTXIIIGED", "VJZN", "QHPCQODPWZYJNKRGWPNWVOPVLJBWICBNOZFBIWGIUYVGZRWKBD", "SXEVTXKVUUANPCZEFPOKZDXXXKFQEQSDDRE", "FASEHTQDJVSHGON", "TKIYYXWFSERPSBJHIIPVAHVGZHNHVFSFUDPSAMPXEELVEETBHJ", "QRJNCPZWZOOZKGWCZWDGZSELRCAEY", "SZIVCQZJLDDDQG", "GDGOBXUSNSCWFQNFJVGSFMBELFTOENMSAMMEHWBL", "JTEDBUCUGUOLNRYZVCAKFMKQKEREAAJKPWL", "HVXROZQEGLPEUOHKTGEIMSULJOV", "YVKBJNYEGGTCTGKDRPDWDQHFFOIRAPBDZBWKIULMWZ", "WAZRBZPJLLNAKCBBPXAKLFYPDFPTRYQEC", "OQBGY", "VRXRETRUUDSBXDWJABTCZAOBLZWPHACDPWQNOPUH", "SQKSJHZQXGUNPEBPTWWZVKEMCPWUHUHURRQAJPFRSYCMFXBFK", "REEHTBITYZGCQWBSCZREV", "PTHZKESYZLIDPEPCPYCIBDCXWRASWLPPOPRFTIX", "NVCZQLNDZDNZGHLMDMSKKU", "UQJMHSUIIBMHVWMHXM", "PBJYLJXZLFX" };
    String[] depends = { "30 2 29 34 3 14", "30 11 22 13 6 31 26", "25 5 3 18 26 32 20", "5 9 6 19 11 29 17 30", "7 11 24 24 24 14 7 8", "35 10", "24 18 7 35 22 22", "15", "21 16 31 28", "20 10 27 11 21", "26 32", "24", "18 28 19", "35 23", "", "31 19 20 20", "20 19 25 25", "28 32 34", "27 27", "25 21", "27", "23 30", "25", "28", "", "", "33 29", "29", "35", "", "34 33", "", "34", "", "", "" };
    assertArrayEquals(new String[] { "HVXROZQEGLPEUOHKTGEIMSULJOV", "JTEDBUCUGUOLNRYZVCAKFMKQKEREAAJKPWL", "NVCZQLNDZDNZGHLMDMSKKU", "OAFBPHIEDMR", "PBJYLJXZLFX", "OQBGY", "GDGOBXUSNSCWFQNFJVGSFMBELFTOENMSAMMEHWBL", "NWOXNYAPOQWOHYUKAXQDHEALEJCNMFMXTDRWSDKRTXMIB", "REEHTBITYZGCQWBSCZREV", "SZIVCQZJLDDDQG", "UQJMHSUIIBMHVWMHXM", "PTHZKESYZLIDPEPCPYCIBDCXWRASWLPPOPRFTIX", "QHPCQODPWZYJNKRGWPNWVOPVLJBWICBNOZFBIWGIUYVGZRWKBD", "SQKSJHZQXGUNPEBPTWWZVKEMCPWUHUHURRQAJPFRSYCMFXBFK", "QRJNCPZWZOOZKGWCZWDGZSELRCAEY", "FASEHTQDJVSHGON", "VRXRETRUUDSBXDWJABTCZAOBLZWPHACDPWQNOPUH", "WAZRBZPJLLNAKCBBPXAKLFYPDFPTRYQEC", "SXEVTXKVUUANPCZEFPOKZDXXXKFQEQSDDRE", "THMRDGMGVJYTCENAMXAXBWSOFEJQW", "TKIYYXWFSERPSBJHIIPVAHVGZHNHVFSFUDPSAMPXEELVEETBHJ", "OROSXRVQKOALSNPQTXIIIGED", "EXPZWVXCSSEUHJEYPJQIDVOFCQLZXZAKCAFZEWDJWPPGVAPO", "KEXCJFJNXLIUXFTOTPEUTPLOFKSUMAWQJCSZT", "VJZN", "EKQVHOVGBJL", "WSPVV", "GDZDDNDGKBTWFXTMZHUCFFDWPJAJBLT", "YVKBJNYEGGTCTGKDRPDWDQHFFOIRAPBDZBWKIULMWZ", "LGRRBHBHJEEVHXRSSUYDAGNSNHXIPQKHGBLWASVQZESQEDJK", "WIZ", "AKTTJNEGTZDSRTRTRGPUJFWUDU", "LMNZFOITNVZNLTOBKKBJDHHDOGBDA", "IYYTEWXPPFGQJGLNQBMHYNZDNPPFVOQQDXYZVFBOKKQ", "XKIPYGJ", "FNCZUKCEUVQOYQNWCBYBMEYFZFNPRRUGUVLIONLIVFZ" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case16() {
    String[] funcs = { "IZLWOCEOXBOZGBOJGCPULFJODMAMXSSNAFDQLRTCQPQR", "RIINPDGYEKULKOZCD", "DYWVTQNSPVBFFARCLRUVLOXIPHAGGFZN", "ILX", "WRBHQZQKZDWZVEDBZMBHVWNCXHINHNUZRDQNEWIBWALEDIL", "XWLCEMTGWBYUZQWRVZJMPISXILVKTTDYYEMIMJJNTJHFPHNVX", "ENCUEUAJVVWZ", "SSJAGZCTRFFFAGZFEPXYYWWCLQWKVQPJ", "ZMAET", "INWQRNDI", "NOAPYYBYRUYMQEBSV", "PHJZCNVLQOZJUGQL", "AWPXBFDRYORXBUKTVCVMSJNHURDYKIXUD", "YYXXJARVGTWRWXNRLUIXUQHWPIFJOMVOCRWNDCPUCANGLDFIZ", "TGYRXXXKBMDTAWHRJVBWQSJHKKRLXJ", "KJEPKPZETJOGQQGQLTPVJRVFCYUIXL", "LSQMJY", "MPXMGPDOXHM", "PCQQLUZOHZNSURDYXAGSPJKXL", "JSEKKZRMTLWGLPQJIRSMESHCKAQOTZXLHZHERPN", "RYJTBOPBJGDZIHJIKZXKMDJIYHPSVTZJNBF", "ITZTQHJIDDXIHNQZDTQAJN", "EKWVDFTRMTRPCFSQ", "DQTUCOENGHMEPQTTZJVRWWCAYRETCKIHWFQJV", "TDJCSMQLFOAQURMJRGIDMJIIPEWHIRPSQAZPCPOYYUDBLSCCSH", "NJQYJVNRFQKIREHQFKEKZFPTCQNT", "NIBFOEZLGOUKJFDTPCWJLVDNJDMCCSLYKMKQWQMKEJTIGSZVFQ", "KZGVKPNVNPZG", "OYDEBRKFVDCICQZWGBFTTCOPGYHSZYESIVUGXZWSOZJVR", "CSBMKWQAGZPOMDZHGIZIWFFFWXPD", "GUEJ", "XCHCIRALYNWDJQMRV", "XOTZKQGSTZEEWPAAJXQTWXMZZEZRZOB", "MQIYOUUWYLREOJTMGQJVVGPDJRNARZBABWQVJINT", "AAVOQIPLSG", "YLMBPYWJRVBNFROFUDRNADAUVHBMLODU", "IMZDNSJZZIJLL", "UYDPJXFKSLFFIUPTYTWWAORWRQJFUIOFFUEMKMQBHJ", "CIBEWUMXXIJYDYR", "XXIMODKFSUEUQESLYPTTIYMKWCCQHVCLTVBOOEVDMSPCA", "MQCHJSWCUGBLIECZYYZVZGBBBWDHFAYJSRUOMLHWLISONAIBG", "YYRXVKDHYSPWFAKO", "PQKIYLOEOGNVSCK", "KQZQXBIDDHCPPPDYNIZVZWWSQACHPLFBILXGDYWBRUDW", "JIZNBONPREPYJENKJOTXOZMVTWYNRJUDRBRSLN", "NZIBQWDJTWJH", "OSCPNECVKEEJPF" };
    String[] depends = { "13 45 16", "16 35 12 22 39 46 19 25", "45 27 43", "45 22 41 7 14 32", "34 27 38 8 9 33 13 17 8", "34 34 40 35", "18 38 35", "44 46 15 31 29 18 17 20", "11 23 20 21 34 26 17", "23 16 22 32 10 36 30 31 32", "", "", "", "", "43 45 18 15 45 35 32 37", "41 16 37 42 29", "", "38 19 26 35 45 44 36", "36 33 39 26 45 45 46", "43 35 31 29 36 20 41", "40 34", "46 22 37 23", "46", "", "46", "", "41", "42 37", "40 30 45 29", "44 42", "", "42 37 38", "35 39", "40 38 46", "42 36 45", "37", "", "40", "", "", "41 41", "43", "43", "", "", "46", "" };
    assertArrayEquals(new String[] { "AWPXBFDRYORXBUKTVCVMSJNHURDYKIXUD", "CIBEWUMXXIJYDYR", "DQTUCOENGHMEPQTTZJVRWWCAYRETCKIHWFQJV", "GUEJ", "IMZDNSJZZIJLL", "JIZNBONPREPYJENKJOTXOZMVTWYNRJUDRBRSLN", "KQZQXBIDDHCPPPDYNIZVZWWSQACHPLFBILXGDYWBRUDW", "LSQMJY", "NJQYJVNRFQKIREHQFKEKZFPTCQNT", "NOAPYYBYRUYMQEBSV", "OSCPNECVKEEJPF", "EKWVDFTRMTRPCFSQ", "NZIBQWDJTWJH", "PHJZCNVLQOZJUGQL", "PQKIYLOEOGNVSCK", "AAVOQIPLSG", "CSBMKWQAGZPOMDZHGIZIWFFFWXPD", "TDJCSMQLFOAQURMJRGIDMJIIPEWHIRPSQAZPCPOYYUDBLSCCSH", "XXIMODKFSUEUQESLYPTTIYMKWCCQHVCLTVBOOEVDMSPCA", "YYRXVKDHYSPWFAKO", "MQCHJSWCUGBLIECZYYZVZGBBBWDHFAYJSRUOMLHWLISONAIBG", "MQIYOUUWYLREOJTMGQJVVGPDJRNARZBABWQVJINT", "NIBFOEZLGOUKJFDTPCWJLVDNJDMCCSLYKMKQWQMKEJTIGSZVFQ", "OYDEBRKFVDCICQZWGBFTTCOPGYHSZYESIVUGXZWSOZJVR", "PCQQLUZOHZNSURDYXAGSPJKXL", "RYJTBOPBJGDZIHJIKZXKMDJIYHPSVTZJNBF", "UYDPJXFKSLFFIUPTYTWWAORWRQJFUIOFFUEMKMQBHJ", "ITZTQHJIDDXIHNQZDTQAJN", "KJEPKPZETJOGQQGQLTPVJRVFCYUIXL", "KZGVKPNVNPZG", "DYWVTQNSPVBFFARCLRUVLOXIPHAGGFZN", "XCHCIRALYNWDJQMRV", "YLMBPYWJRVBNFROFUDRNADAUVHBMLODU", "ENCUEUAJVVWZ", "JSEKKZRMTLWGLPQJIRSMESHCKAQOTZXLHZHERPN", "MPXMGPDOXHM", "RIINPDGYEKULKOZCD", "SSJAGZCTRFFFAGZFEPXYYWWCLQWKVQPJ", "XOTZKQGSTZEEWPAAJXQTWXMZZEZRZOB", "INWQRNDI", "TGYRXXXKBMDTAWHRJVBWQSJHKKRLXJ", "ILX", "XWLCEMTGWBYUZQWRVZJMPISXILVKTTDYYEMIMJJNTJHFPHNVX", "YYXXJARVGTWRWXNRLUIXUQHWPIFJOMVOCRWNDCPUCANGLDFIZ", "IZLWOCEOXBOZGBOJGCPULFJODMAMXSSNAFDQLRTCQPQR", "ZMAET", "WRBHQZQKZDWZVEDBZMBHVWNCXHINHNUZRDQNEWIBWALEDIL" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case17() {
    String[] funcs = { "AFITZAFHBVRNXZNLT", "PHJVQHGXRAZGJVVBBNSSMIGHGCIKERNIHUAJQ", "AGPETGLMJXDPTSEKRJDYEWXZEMPUKYOWQJPHUQOFYX", "K", "PIJOGXLDCRJZIZSHIKHJIFVXCTXVEHIYCYEFCACCROQHBA", "LDHYMIAEXGCMIWMTQWBSXACGUIPTIUFZRZEVINMSMTPWSFCDVN", "XXGPHZQUPJTDCSPCUCADWMIGYGHRWFSYQOXB", "MIFDSAHTJPCTDBOBRNDPGHTIPETVBCBTB", "V", "RUFJLQGQS", "GQWCHUZJXYUMFJTBBYNJSSMEKISJNICHTCUQRKS", "PCOHHEXXRSPAXPLKLBXMZTPTOTGVKISIJ", "RICDUVJKDRKTV", "WZWPQULJHCAIMLHOTTXEQFRXSLWYHC", "XELJJNIYGJLWUXSSMIBCOXGWKFGOMOOAMWXEMSIJPKHQWT", "HHP", "ZBZEQJKFBZFZJMOTBOERANXZAFA", "GBBPIKWYGAVTBCJH", "CSJVHZHFFKYWMT", "YAHRYEPJANAGLLZKALWFF", "DADUKOYIZHPHUDOC", "KFZMCXSCGXSP", "BHSWDLMHALTVMBDKBUTZCPUUHOTSEZKCD", "SQMIDMWLCYYLUWDYFYZNLQIQZSCNVZESEHLOXPHZZNFQ", "ZPERGCXZBVOVCAKJR", "M", "SIIIZB", "NMOTHDGDDVUXXNOBIWDVPPKVOWKVYCZJSSIZE", "VNPMHQUKHSMVVXAEDKPPXDGIUMPESMNCDYE", "XIECWGIZHVFU", "WEUFLUBHVFSBJXTYCUXYBOZZHYEVTQVSWKLNYDTGZNHQWUBBQ" };
    String[] depends = { "14 19 3 15 16", "15 9 10 24", "27 23 5 3 8 12", "", "24 23 14 19 20", "23 23 13 8 6", "24 8 14", "15 13 11", "13 28", "", "", "17 30 15 22", "18 19", "", "21", "22 30 26", "", "23 23 25", "27", "", "24", "", "29", "30 24", "30 26", "30", "29", "", "", "", "" };
    assertArrayEquals(new String[] { "GQWCHUZJXYUMFJTBBYNJSSMEKISJNICHTCUQRKS", "K", "KFZMCXSCGXSP", "NMOTHDGDDVUXXNOBIWDVPPKVOWKVYCZJSSIZE", "CSJVHZHFFKYWMT", "RUFJLQGQS", "VNPMHQUKHSMVVXAEDKPPXDGIUMPESMNCDYE", "WEUFLUBHVFSBJXTYCUXYBOZZHYEVTQVSWKLNYDTGZNHQWUBBQ", "M", "WZWPQULJHCAIMLHOTTXEQFRXSLWYHC", "V", "XELJJNIYGJLWUXSSMIBCOXGWKFGOMOOAMWXEMSIJPKHQWT", "XIECWGIZHVFU", "BHSWDLMHALTVMBDKBUTZCPUUHOTSEZKCD", "SIIIZB", "HHP", "YAHRYEPJANAGLLZKALWFF", "RICDUVJKDRKTV", "ZBZEQJKFBZFZJMOTBOERANXZAFA", "AFITZAFHBVRNXZNLT", "ZPERGCXZBVOVCAKJR", "DADUKOYIZHPHUDOC", "PHJVQHGXRAZGJVVBBNSSMIGHGCIKERNIHUAJQ", "SQMIDMWLCYYLUWDYFYZNLQIQZSCNVZESEHLOXPHZZNFQ", "GBBPIKWYGAVTBCJH", "PCOHHEXXRSPAXPLKLBXMZTPTOTGVKISIJ", "MIFDSAHTJPCTDBOBRNDPGHTIPETVBCBTB", "PIJOGXLDCRJZIZSHIKHJIFVXCTXVEHIYCYEFCACCROQHBA", "XXGPHZQUPJTDCSPCUCADWMIGYGHRWFSYQOXB", "LDHYMIAEXGCMIWMTQWBSXACGUIPTIUFZRZEVINMSMTPWSFCDVN", "AGPETGLMJXDPTSEKRJDYEWXZEMPUKYOWQJPHUQOFYX" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case18() {
    String[] funcs = { "NFCTZYRTUKBICUKJEAFNGNYUIVPJWOVXBU", "TWOGSYPJWDIMTXEYSEAOQNBJQKTONTCSWUDETFUYVIS", "DWUMWOMORKOQRXIMUT", "ATNSLDSMFXIZWVGLETAXVECVUGBHOYHBFHQ", "XCQFPXUDXBERMCF", "FLTLGEMQPILTRFUXMZC", "MQIFLDVZTUUXSTOWKEVLPEJHWHS", "CAGZHWRGJJJWKMLNEJQRSBUSKVHFDIA", "QOIBLJKGOZYYWBUHNPEKOQ", "MYMIBXDIJAUJHIYFHYHSSOGNEQSIOHQCVDMPIOLJMDCQGIIUKL", "URWWGGMZFRKWTSXCIPOBTUXRFLWJ", "PXBKJERROXSBIGDQECPPJHSCIFVIKJURWHCR", "XLKCWDYZGEJHQGQFDH", "DAWBQFKJ", "MZTDMZEYFPBFUURB", "JOPNMNGEBPSVYKYKXUGHAOB", "IONITDNLGNBWCWRPRCEPHMTYGZGSKGOUQPMFWLSNCSFN", "VLEZSNZDFVAFLQFWXKVUJOXWGROHGMZSBQWIQGIGGENDIY", "FEQWCYJTPF", "NAHMOHGFOXYZANHUJHVTA", "SIXUOJFUZYGP", "R", "LBGDBWEOPZTMXCNCREMUEIDQHFJRJORWXDUN", "O", "HJYCTIGVWIFDKOLEMUOQ", "NDYJMCVQCDDPOWVBVMESANIRFABDCSVIJVAQY", "KIPTZYZJZJQXDBMSBOJFGAAHZHGULDC", "OOTOLRJEPNCTEHMLKXJ", "INJZBQIGTFR", "I", "XUAGOXSMLCXVW", "IQLEVAVKEEAHNINESGHNH" };
    String[] depends = { "", "6 11", "", "5 25 12 7 30 20 29", "8", "9 7 11 27 16 6 26", "18 25", "29 24 17", "22 17", "31 13", "25 18", "26", "", "24 14", "", "19 27", "25", "28 27", "", "23 29 28", "", "", "", "", "", "", "27", "", "", "30", "", "" };
    assertArrayEquals(new String[] { "DWUMWOMORKOQRXIMUT", "FEQWCYJTPF", "HJYCTIGVWIFDKOLEMUOQ", "INJZBQIGTFR", "IQLEVAVKEEAHNINESGHNH", "LBGDBWEOPZTMXCNCREMUEIDQHFJRJORWXDUN", "MZTDMZEYFPBFUURB", "DAWBQFKJ", "MYMIBXDIJAUJHIYFHYHSSOGNEQSIOHQCVDMPIOLJMDCQGIIUKL", "NDYJMCVQCDDPOWVBVMESANIRFABDCSVIJVAQY", "IONITDNLGNBWCWRPRCEPHMTYGZGSKGOUQPMFWLSNCSFN", "MQIFLDVZTUUXSTOWKEVLPEJHWHS", "NFCTZYRTUKBICUKJEAFNGNYUIVPJWOVXBU", "O", "OOTOLRJEPNCTEHMLKXJ", "KIPTZYZJZJQXDBMSBOJFGAAHZHGULDC", "PXBKJERROXSBIGDQECPPJHSCIFVIKJURWHCR", "R", "SIXUOJFUZYGP", "TWOGSYPJWDIMTXEYSEAOQNBJQKTONTCSWUDETFUYVIS", "URWWGGMZFRKWTSXCIPOBTUXRFLWJ", "VLEZSNZDFVAFLQFWXKVUJOXWGROHGMZSBQWIQGIGGENDIY", "QOIBLJKGOZYYWBUHNPEKOQ", "XCQFPXUDXBERMCF", "XLKCWDYZGEJHQGQFDH", "XUAGOXSMLCXVW", "I", "CAGZHWRGJJJWKMLNEJQRSBUSKVHFDIA", "FLTLGEMQPILTRFUXMZC", "ATNSLDSMFXIZWVGLETAXVECVUGBHOYHBFHQ", "NAHMOHGFOXYZANHUJHVTA", "JOPNMNGEBPSVYKYKXUGHAOB" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case19() {
    String[] funcs = { "FNZWCLLZMLOMMCRIWSTFVWKITUVSTLFRQQ", "UGHGNSGPZGDRXEIFA", "QC", "APNIUSGKIHEODDGWTWN", "MAJS", "EFKRHHGCI", "UNETUCWQSDUBBNNMHOOKTTNYXERPAVGMQIS", "YYPWTSBHCYOQEXMLAURMCXNS", "DRBKPAZWSTBFGSRBXFDFYQCPGXCMIRGE", "WNQUYZPIQIQDNUZHTDACUCMZNWPUVXREDDWGFDDRMWOUHJVB", "VBTRBSYTYYTWHERSYPKRCORQVMQ", "ARBTIWGCRIZXNCOMCQKYEJRAMWGJIZATKOFTVZ", "WNIBGT", "RMZEGAYTLDZCHYOPLZENMULZRSIUBC", "YMRPUCILFDSGHSPRUGIAORDJIJLSTXRTQKVPNXB", "IDOYMLSUDWMPSUCSOOWJELIVHUSPJOOFQXMSSIMDE", "HMARYRHSSXEQIFJCDIKXBUPUFEYHFVLCM", "NGYKYFVASKXZKTVKQYWSVF", "BHHFZLNXBGLJBCLXIWPJIZCQMCNGCV", "JZTETVSKGZFDOTIUUNQDALOPHFVONED", "IQJWCMUCKYLGSSBTH", "CZCLTPOGVZYAG" };
    String[] depends = { "6 13 4 7 11 2 4 1", "", "21 15", "20", "5 21 20", "12 7", "14", "18 16 11", "13 18 10", "19 19", "20", "", "17 16", "19 20", "17 16", "", "", "", "19", "", "", "" };
    assertArrayEquals(new String[] { "ARBTIWGCRIZXNCOMCQKYEJRAMWGJIZATKOFTVZ", "CZCLTPOGVZYAG", "HMARYRHSSXEQIFJCDIKXBUPUFEYHFVLCM", "IDOYMLSUDWMPSUCSOOWJELIVHUSPJOOFQXMSSIMDE", "IQJWCMUCKYLGSSBTH", "APNIUSGKIHEODDGWTWN", "JZTETVSKGZFDOTIUUNQDALOPHFVONED", "BHHFZLNXBGLJBCLXIWPJIZCQMCNGCV", "NGYKYFVASKXZKTVKQYWSVF", "QC", "RMZEGAYTLDZCHYOPLZENMULZRSIUBC", "UGHGNSGPZGDRXEIFA", "VBTRBSYTYYTWHERSYPKRCORQVMQ", "DRBKPAZWSTBFGSRBXFDFYQCPGXCMIRGE", "WNIBGT", "WNQUYZPIQIQDNUZHTDACUCMZNWPUVXREDDWGFDDRMWOUHJVB", "YMRPUCILFDSGHSPRUGIAORDJIJLSTXRTQKVPNXB", "UNETUCWQSDUBBNNMHOOKTTNYXERPAVGMQIS", "YYPWTSBHCYOQEXMLAURMCXNS", "EFKRHHGCI", "MAJS", "FNZWCLLZMLOMMCRIWSTFVWKITUVSTLFRQQ" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case20() {
    String[] funcs = { "DDCLBZYERCYIA", "DXYMWAXZPHWYEITIBSUZDWKFMPBBQLUEVULKRRQOFGRIUKV", "RLXTOHYBOUHVFGUY", "HKG", "XWZ", "XUXXGXNSDMJRXGWWMJGYWOSPAWXGXDPUU", "RUZMLZJNTUVVCFHH", "CMPWHRUGOUYUIRFNT", "DKGWDVDFGDKWDXXGMUWXHFHTVABDNIATJXIGHL", "GZK", "XYXTISXCJJ", "RXIQVWHZYESGYEANTBPHJASFVVVQUSAQBKYC", "NPLUCSXXIKAOVQESXMU", "YJITPJXQMGULUJPUSXHAIKUU", "PNZEIMYVVMSQIKTFTDWGSIHEUUAWDTQVARZM", "GNRUKMOABR", "AMLPQONQYUSPOVLKMCNNEYMOTPUZLTSINIWMEFU", "WTXDSXMNLEIYH", "CRGKNOPLBBVZAPJEJEBAIERWAJ", "IGKOVRFUFJZPZCCMYPOFJNPDA", "IKRICCXZNAVNHZNDWJHBOZOLAUROQOEBIAFTWWJJ", "S", "VBHQPWBHFRWFIRCZTLWWY", "MKMWHDEMQMZSGAORPWWORKZDFGKEQNEIWCWEWOE" };
    String[] depends = { "21 22 5 9 10 2", "21 2 22 7 9", "11 7 3 9 18", "", "13", "16 7 10", "18 8 11", "18", "18", "19 13 22 10", "18", "13 18", "", "15 22 17", "", "", "23 19", "18", "19", "", "", "", "", "" };
    assertArrayEquals(new String[] { "GNRUKMOABR", "HKG", "IGKOVRFUFJZPZCCMYPOFJNPDA", "CRGKNOPLBBVZAPJEJEBAIERWAJ", "CMPWHRUGOUYUIRFNT", "DKGWDVDFGDKWDXXGMUWXHFHTVABDNIATJXIGHL", "IKRICCXZNAVNHZNDWJHBOZOLAUROQOEBIAFTWWJJ", "MKMWHDEMQMZSGAORPWWORKZDFGKEQNEIWCWEWOE", "AMLPQONQYUSPOVLKMCNNEYMOTPUZLTSINIWMEFU", "NPLUCSXXIKAOVQESXMU", "PNZEIMYVVMSQIKTFTDWGSIHEUUAWDTQVARZM", "S", "VBHQPWBHFRWFIRCZTLWWY", "WTXDSXMNLEIYH", "XYXTISXCJJ", "XUXXGXNSDMJRXGWWMJGYWOSPAWXGXDPUU", "YJITPJXQMGULUJPUSXHAIKUU", "GZK", "RXIQVWHZYESGYEANTBPHJASFVVVQUSAQBKYC", "RLXTOHYBOUHVFGUY", "DDCLBZYERCYIA", "DXYMWAXZPHWYEITIBSUZDWKFMPBBQLUEVULKRRQOFGRIUKV", "RUZMLZJNTUVVCFHH", "XWZ" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case21() {
    String[] funcs = { "WDAEMPSCALFXVGDAZUZKKWVXTPWPWAM", "EUGUUHUKISYBKSGJB", "QVWGKYOLKLV", "MCPIEMBKUFKVJISGJWX", "FUBQIDFYIKWVLEIFGCXAQUMIXPKWLVPWCZSZ", "RYPBEQKHWNAVIZDELQTYPDQIOHE", "GKJYYVYAOTDYKHGJBZUKJBPXCNPYHEFNJWULEB", "OJWAHDVLGZNZDYXLEXHSGIKM", "BRHXQVTDJREGIHEWYHUJKIUDUBCBYDNCFOXIQFIDJV", "SFVXQRYGYANFGNNSJLNWSNDRNLL", "ZBYEOCPFYACITCOEXYGRABSACUBQMJQJBI", "DTHTPFRMDTXRGNTZXZDWNQUAUAQYYTXVLEBLQ", "MRRVSZYLUINCXDYTJQECOOXNPWDSRVUIFJYXVRUDUZNHR", "UWFOVQLPVTDNFILBRYQFZWNWJAPOYMSQOJ", "MUMNGEVJ", "SVPHTEOWWQCTELXTVPIFVQY", "CQCQ", "FAISFLSPJSAPCULSVPFEMTNDDKX", "XMYKGWTEJGLTZXGFEXDOPJOACHSZFITVGXHIJTL", "EIRRKYHSTS", "FEAMLIFZXILDHORWWYKATOZNYAPTETNCFXJQKCWLLVNVGSCV", "LQDXKKEDHPIQCPRDGERAHLHCEK", "RRKIUGFMSRYTRPUQBQEWLQ", "FGUGRLTWQQIX", "GUXSDEWLFHYJOJQVSKHZDOPSZZ", "ADPVOLKNLGXMKEWUDCDESLZDPTMTQHFN", "GIOPWNVICTAUDREPT", "DRFUPSBLZNVYIEYMHTCPPBROTSRCWMNKSWMFJZEJPO", "MVFHYIHPAQ", "AIAKFQPJLTHMVRIC", "EVX", "IUDIQZGYDSRFWCYKPFYOTCQUPFRTSASKVZOBLNWQLOWF", "FOSMLWXIK", "XIUJIZKDIJEDNHEGGGBNCCRI", "PCUNKNERJWWUVHIEKFOUBHOHBXGXOUMUK", "JKWRXQAEUEDYMMJVLVRDZIFXUPMVDQITGQQGVITOVMWRRUP", "MSBYRVDWTHTAMTSJCEPKBGZUQUXSDPNZILCBTIGOUZ" };
    String[] depends = { "26 23", "18 22 5 24 19 28", "3 22 30 5 5 13 17 20 22", "", "26 15 15 34 26 21", "35 6 27 32 23 35", "18 28", "17 30 18 18 34 16", "30 24 27 9 28 21 22", "27", "26 24 33", "19 28 23 35 19 34", "24 21 17 20 32 14", "26 36 17 17", "15 35 20", "16 25 22", "17 31", "24 24 27", "33 33 19", "", "32 21 25 31", "28", "25 32", "", "29", "31 29", "28 34", "34", "", "31 31", "33 36", "", "36", "", "", "", "" };
    assertArrayEquals(new String[] { "EIRRKYHSTS", "FGUGRLTWQQIX", "IUDIQZGYDSRFWCYKPFYOTCQUPFRTSASKVZOBLNWQLOWF", "AIAKFQPJLTHMVRIC", "ADPVOLKNLGXMKEWUDCDESLZDPTMTQHFN", "GUXSDEWLFHYJOJQVSKHZDOPSZZ", "JKWRXQAEUEDYMMJVLVRDZIFXUPMVDQITGQQGVITOVMWRRUP", "MCPIEMBKUFKVJISGJWX", "MSBYRVDWTHTAMTSJCEPKBGZUQUXSDPNZILCBTIGOUZ", "FOSMLWXIK", "MVFHYIHPAQ", "LQDXKKEDHPIQCPRDGERAHLHCEK", "FEAMLIFZXILDHORWWYKATOZNYAPTETNCFXJQKCWLLVNVGSCV", "PCUNKNERJWWUVHIEKFOUBHOHBXGXOUMUK", "DRFUPSBLZNVYIEYMHTCPPBROTSRCWMNKSWMFJZEJPO", "DTHTPFRMDTXRGNTZXZDWNQUAUAQYYTXVLEBLQ", "FAISFLSPJSAPCULSVPFEMTNDDKX", "CQCQ", "GIOPWNVICTAUDREPT", "RRKIUGFMSRYTRPUQBQEWLQ", "SFVXQRYGYANFGNNSJLNWSNDRNLL", "SVPHTEOWWQCTELXTVPIFVQY", "FUBQIDFYIKWVLEIFGCXAQUMIXPKWLVPWCZSZ", "MUMNGEVJ", "MRRVSZYLUINCXDYTJQECOOXNPWDSRVUIFJYXVRUDUZNHR", "UWFOVQLPVTDNFILBRYQFZWNWJAPOYMSQOJ", "WDAEMPSCALFXVGDAZUZKKWVXTPWPWAM", "XIUJIZKDIJEDNHEGGGBNCCRI", "EVX", "BRHXQVTDJREGIHEWYHUJKIUDUBCBYDNCFOXIQFIDJV", "XMYKGWTEJGLTZXGFEXDOPJOACHSZFITVGXHIJTL", "GKJYYVYAOTDYKHGJBZUKJBPXCNPYHEFNJWULEB", "OJWAHDVLGZNZDYXLEXHSGIKM", "RYPBEQKHWNAVIZDELQTYPDQIOHE", "EUGUUHUKISYBKSGJB", "QVWGKYOLKLV", "ZBYEOCPFYACITCOEXYGRABSACUBQMJQJBI" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case22() {
    String[] funcs = { "EXJWWLLVHJHSTWEDRXDMDES", "VPCYGVBFBBXKPDVIYWFLBRVCAFEDTTOJZF", "UIYVMOMTILQAPOTIWLLUHWFOBRSNBNAIUCDRSMXXOTC", "AYRRYFIRDBMHGEFBCERMXXNEHPZLXT", "BBVFFNPMXBISJOMKUXTULZZGVQSHJJSOXAB", "BOYCCK", "OWXZMFYACEYRNECPPRVZWTKI", "EYNITQHSUEWOVNUFSSFMUEAMMFVTBONMQOPHKDOTFILUFCVUC", "WGCFUPTJM", "KYIHMJLDOHAKCGZIWC", "MJGYZTPRRNFGXGXOBRFIBUOMGNUUJJXTYOVTXEULHVSK", "FXAKIAPFPHTBMYDBEYGWRVNC", "EXDTSGHUHMBLSMTOXPJBOINWOCWUEOTREUWGEBLNNSPBEGVDWT", "GOPYZFEQWTEAUDYDJYDDXZNSEIFPWMBICVGLAIDUAMPBVO", "OEZSNM", "QBVC", "EJGHGQIOFOHWAGGCAJTBWSDCSUFXICIVU", "NEIX", "VKBLCYOZABXFPRYJOYKUBCYABOOSOHWMHEDHPGZOPIZGN", "YOJHUGXCMZPQJGESRZHRFFFPOXDZDJOLTP", "YNYEYRESEZNWHGIBAYORQJXXFWXNSJKGBCITIOMSIZY", "QRJYLUUTZJNFDTHFD", "YWVBUHWFVVHXXKMZBDBGHGJRPHXIYJIGAZIYSRFPDLFF", "WLEHYBYNYJFBLSBGVYNPWUHNQBVGTFNDMEHYSNIUQS", "VZROQ", "RTPUIQQZBWDBLIEA", "KZQRZOCAIUDZHMQE", "WBDMLMVURQCDKHONGBQLGBYXWFUUFOBFJYIJJXBPUUIMGCNQSG", "EGJDYZMFQFWANZTBWUBKIITGYADXV", "LRTZUHKZGLJX", "SWQSNLDRMAHWBAGHICS", "ATUCZIVUQLSVUIFDWRUPASNKXGGGLNCDWPDBZTKJYLAAXXPHFC", "OPKYPYELWY", "GDH", "LMWTQGNWFTSRTMTFSJYDLUIHGWMUCIMFBCHHKUMHTTWROYP", "UURZYFGDCCRTOYOZLTYKQEBFAVA", "XAZQVQKYJDUHJGFYOHTVZFMEFTJFKUWISZZBFQXAPXD", "METLYQDFBGO", "BUPTHKZBXBVHJPSHNUMMVQXGQHYRDPU", "COVKEKCEJPPXRIOUCAYQULKJONGUODXPEIHRJ", "WPZVNKOPBNFXREVHVWQOHATOMEGKCDIWX", "SASHLDXNTSWRIBWUTTEZDR", "PGBLGLWWRLNI", "SUSUQTQPR", "FDUJBEDHUUAOLQDKLJBPNNTH", "LTIENHILY", "RCCCEUVMFHTVGHOLLMXZMXKBQPZPKHGJYMH" };
    String[] depends = { "4 44 36 27", "6 9 40", "12 28", "15 38 39 29 37", "6 24 46 23", "31 23 16", "31 37 41", "8 20 32 16 23 16", "10 38 33 41 43 29 34 35 39", "40 17 15 22 27 27", "31 11 20 37 17 32 31 41", "28 43", "20 32 23", "43 44 39 29 37 39 21 44", "42 40 32 26", "23 32 33 45 38 46 31", "17 27 32 32 26 27 32", "25 35 41", "20 43 43 36 39 28 21", "44 27 37", "35 22 22 34 39 32", "", "28 23 35 40", "25 45 29 25 42", "36 39", "45 41 44 29", "38 43 30", "", "35 37 44", "41", "31", "41 41 43 43", "", "36", "", "36 40", "44 42", "46", "42 46", "", "43", "45", "", "", "46", "", "" };
    assertArrayEquals(new String[] { "COVKEKCEJPPXRIOUCAYQULKJONGUODXPEIHRJ", "LMWTQGNWFTSRTMTFSJYDLUIHGWMUCIMFBCHHKUMHTTWROYP", "LTIENHILY", "OPKYPYELWY", "PGBLGLWWRLNI", "QRJYLUUTZJNFDTHFD", "RCCCEUVMFHTVGHOLLMXZMXKBQPZPKHGJYMH", "BUPTHKZBXBVHJPSHNUMMVQXGQHYRDPU", "FDUJBEDHUUAOLQDKLJBPNNTH", "METLYQDFBGO", "SASHLDXNTSWRIBWUTTEZDR", "LRTZUHKZGLJX", "RTPUIQQZBWDBLIEA", "SUSUQTQPR", "ATUCZIVUQLSVUIFDWRUPASNKXGGGLNCDWPDBZTKJYLAAXXPHFC", "GOPYZFEQWTEAUDYDJYDDXZNSEIFPWMBICVGLAIDUAMPBVO", "OWXZMFYACEYRNECPPRVZWTKI", "SWQSNLDRMAHWBAGHICS", "KZQRZOCAIUDZHMQE", "WBDMLMVURQCDKHONGBQLGBYXWFUUFOBFJYIJJXBPUUIMGCNQSG", "WLEHYBYNYJFBLSBGVYNPWUHNQBVGTFNDMEHYSNIUQS", "WPZVNKOPBNFXREVHVWQOHATOMEGKCDIWX", "OEZSNM", "XAZQVQKYJDUHJGFYOHTVZFMEFTJFKUWISZZBFQXAPXD", "GDH", "QBVC", "AYRRYFIRDBMHGEFBCERMXXNEHPZLXT", "UURZYFGDCCRTOYOZLTYKQEBFAVA", "EGJDYZMFQFWANZTBWUBKIITGYADXV", "FXAKIAPFPHTBMYDBEYGWRVNC", "NEIX", "EJGHGQIOFOHWAGGCAJTBWSDCSUFXICIVU", "BOYCCK", "VZROQ", "BBVFFNPMXBISJOMKUXTULZZGVQSHJJSOXAB", "EXJWWLLVHJHSTWEDRXDMDES", "YOJHUGXCMZPQJGESRZHRFFFPOXDZDJOLTP", "YWVBUHWFVVHXXKMZBDBGHGJRPHXIYJIGAZIYSRFPDLFF", "KYIHMJLDOHAKCGZIWC", "VPCYGVBFBBXKPDVIYWFLBRVCAFEDTTOJZF", "YNYEYRESEZNWHGIBAYORQJXXFWXNSJKGBCITIOMSIZY", "EXDTSGHUHMBLSMTOXPJBOINWOCWUEOTREUWGEBLNNSPBEGVDWT", "MJGYZTPRRNFGXGXOBRFIBUOMGNUUJJXTYOVTXEULHVSK", "UIYVMOMTILQAPOTIWLLUHWFOBRSNBNAIUCDRSMXXOTC", "VKBLCYOZABXFPRYJOYKUBCYABOOSOHWMHEDHPGZOPIZGN", "WGCFUPTJM", "EYNITQHSUEWOVNUFSSFMUEAMMFVTBONMQOPHKDOTFILUFCVUC" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case23() {
    String[] funcs = { "DBGJTSACTIIUDCPSIRJVXQCJI", "CYGAXNXDQDOTAKRVDQ", "PUVASCGVBDHREAAIWFUEAYMXPYGKDSLVCKWBWSG", "VIWFQGMLTTSSIDIAKJY", "XCBPQZHHUGRWDHNTKUGYUATHUHOEGSXKVHLKL", "MLDT", "NCMRBERGCEOFSYLCRJPPGOJM", "REWIOHMRXLTXNYIDAWOTOPW", "WOKATICBMVUSTVSORTDBEQLKNNFEFUTUYBSNAFEO", "OTJHLZNOWFITTMDVZOUPBQZSSYNBCQDJYBCYDFTTJLLYJIQCWZ", "JKMQJZMUNYJDULFRG", "JQKUEHJLXFMQXQEYDAAKUCCUHVKQOXYXHJQQWORCDCCWTLR", "OLXOFGJSHLJBMNRBXHQMWBOHXPECYON", "PECYEAASIJVFMHBLDQOUQORCD", "VVVTJPFLTCBFSVGUYQWCUBWSODOWQNTNEOVUXZHQCNIODCZA", "WCQNYZUUBASEQPNMXJNTRSYGVJXXNLJTLORWDLDKCLYW", "QGUIWQORLRJLOZRENBUWR", "OSDC", "SGIKYSAIKSYZAIDPZIODBDLCSWOE", "ZXKNWPKEVBFQHHSTHPCYCMYFETWMMXL", "VVCAQOPGURPPBJKXHIAVGMRROGFRZXYSQDUSZAPDPERTJAR", "DPOGEICMFHIXSJJXHEREITBVBUP", "RZEQVSVQHWUQACIREBKQSEWYCNRLEVMWJ", "QFFY", "PAVLEWYKMRTRXULOMRCAYTPNXUAQJFOFQUZRDSDRWRFWSLGWJL", "VKUIWHLRWCTWQHY", "FPKZJJOF" };
    String[] depends = { "3 15 23 26 5", "23 20 22 4 8 18", "19 21 26", "19 12", "", "17 14 24 19 15", "21 16 13", "", "", "10 16 10", "20", "25 17 26 17", "15 15 18", "17 23 18 21", "19 20 23", "17 21", "", "", "24", "22 24", "24", "23", "26", "", "25", "", "" };
    assertArrayEquals(new String[] { "FPKZJJOF", "OSDC", "QFFY", "DPOGEICMFHIXSJJXHEREITBVBUP", "QGUIWQORLRJLOZRENBUWR", "REWIOHMRXLTXNYIDAWOTOPW", "RZEQVSVQHWUQACIREBKQSEWYCNRLEVMWJ", "VKUIWHLRWCTWQHY", "JQKUEHJLXFMQXQEYDAAKUCCUHVKQOXYXHJQQWORCDCCWTLR", "PAVLEWYKMRTRXULOMRCAYTPNXUAQJFOFQUZRDSDRWRFWSLGWJL", "SGIKYSAIKSYZAIDPZIODBDLCSWOE", "PECYEAASIJVFMHBLDQOUQORCD", "NCMRBERGCEOFSYLCRJPPGOJM", "VVCAQOPGURPPBJKXHIAVGMRROGFRZXYSQDUSZAPDPERTJAR", "JKMQJZMUNYJDULFRG", "OTJHLZNOWFITTMDVZOUPBQZSSYNBCQDJYBCYDFTTJLLYJIQCWZ", "WCQNYZUUBASEQPNMXJNTRSYGVJXXNLJTLORWDLDKCLYW", "OLXOFGJSHLJBMNRBXHQMWBOHXPECYON", "WOKATICBMVUSTVSORTDBEQLKNNFEFUTUYBSNAFEO", "XCBPQZHHUGRWDHNTKUGYUATHUHOEGSXKVHLKL", "CYGAXNXDQDOTAKRVDQ", "ZXKNWPKEVBFQHHSTHPCYCMYFETWMMXL", "PUVASCGVBDHREAAIWFUEAYMXPYGKDSLVCKWBWSG", "VIWFQGMLTTSSIDIAKJY", "VVVTJPFLTCBFSVGUYQWCUBWSODOWQNTNEOVUXZHQCNIODCZA", "MLDT", "DBGJTSACTIIUDCPSIRJVXQCJI" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case24() {
    String[] funcs = { "CEYFGQCGZEKRVRJXZONCUKKLYKNH", "FSTUIWHSFLBCDVU", "XORPCYTDNTHQRNTMTPPUU", "QNBG", "COYZCEUPYPTLNUYXFPVOZTJCZWTWBXFBYU", "TFISSZICUIYPJOLPFCAPIIVBLSPZINCARFDZBPOEGZVKRPNZG", "HAHRYEXZWFLSTHGM", "GRRPCJWFZXECDFAJH", "ZM", "VDNOMMBXALT", "OESASLVZ", "H", "FQPBAODSISSJRLQGAMNDJT", "EDTCNCBUVKBMCXYAZSBACFJEQUFBHOHYHPBFBZDPNVZBHOEP", "NMNPVHZNKSNYJGBINEEEHEPWRZS", "RISQWKPOEGYDZOGZLPDOC", "MSQHTCBNXGXJHOYLRVYHZVSFTCMJEHM", "LKSMXNDEAPXKGQXCDEUKZUTGICCQBUUOMBETZKDMLFIKM", "XXKJHQ", "JFFLTZKQHGDBMRFXACZQWULXGCJXEEZOWGPNWTRXEYDO", "WUORHEYJANLKQCZJCOYM", "ZXFCO" };
    String[] depends = { "14 2 3 8 13 9", "19 13 17", "17 11 14", "21 17 14", "17 15", "20", "18 18", "", "14 20", "17 14 19", "21 13 16", "", "17 21", "15", "", "", "20", "", "", "", "", "" };
    assertArrayEquals(new String[] { "GRRPCJWFZXECDFAJH", "H", "JFFLTZKQHGDBMRFXACZQWULXGCJXEEZOWGPNWTRXEYDO", "LKSMXNDEAPXKGQXCDEUKZUTGICCQBUUOMBETZKDMLFIKM", "NMNPVHZNKSNYJGBINEEEHEPWRZS", "RISQWKPOEGYDZOGZLPDOC", "COYZCEUPYPTLNUYXFPVOZTJCZWTWBXFBYU", "EDTCNCBUVKBMCXYAZSBACFJEQUFBHOHYHPBFBZDPNVZBHOEP", "FSTUIWHSFLBCDVU", "VDNOMMBXALT", "WUORHEYJANLKQCZJCOYM", "MSQHTCBNXGXJHOYLRVYHZVSFTCMJEHM", "TFISSZICUIYPJOLPFCAPIIVBLSPZINCARFDZBPOEGZVKRPNZG", "XORPCYTDNTHQRNTMTPPUU", "XXKJHQ", "HAHRYEXZWFLSTHGM", "ZM", "ZXFCO", "FQPBAODSISSJRLQGAMNDJT", "OESASLVZ", "QNBG", "CEYFGQCGZEKRVRJXZONCUKKLYKNH" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case25() {
    String[] funcs = { "QKQKVTZHNSHERFFLAXJMPISWSMUBYPQLJZPFHP", "ZCINGCTAODIKFZOVCFKTBJGSWCUEKX", "VYYHZYCYFTDNNYPKH", "JRXSXVJVMWHGULDAUPOLTGEXPLQ", "OLNYUIDKTVZBFEWACNXZFIECGHISGEPOADXDEKJJZTAKXUTA", "AN", "YNTEUOCARSKAECWWDYMWVFVQGTXNSOK", "ODDYMOVPPCXQDUUYJYLEKQWNXBFUHPZYUH", "RNVZFQJZQDUCDMLBQ", "QMVMUPDYRPFGYEQAXXQLNPJGQEFFNIMLSCISYXUUJTHQEO", "DJCSSQQBQ", "MYDEDAFKEVENDCADUYOZLNBRWDBTABNWJEYKINIG", "DO", "DIVPCXRLSZYKRSDVPOZIGPHHXGZTDZNG", "SHFEAQNHVXBYGQZJXFTNCVWRMILWESKCPPOHAEHBH", "FANEEDJK", "QJFCQONWRMUDWFXDZTWUXTUIJILMWFQO", "FDCQRRPXRKNBVJNPXJATKAZJKCXMSDZYKEVPFZCZOGNOUEENJK", "OP", "SKOUMWFAMYTBJKJQYJYYFGIKREVOWDOVBXODHXXLQKAKTALSQ", "NDPCUIOZCNNMORMHFVH", "DOWRAXZHTKSMDMSZJZIJZYBLYT", "YGOOQDOUFMECDNXTBPSQUJPNRGMNYZF", "HNXCCFOXLGXDNCIFNPJILCHRJRUXWXDXTTOYXRTTSASCGS", "QGAEWWVGIVANGEATERTFEXTHWLQHBIQOQSOUGXWPA", "CIPSPEGMHLUZTHTBWGBPFSQH", "WO", "LOGRRXYLZPPQDZUDZXYZNIBZRKF", "FBUQVEOWOWJGJDVMCMF", "RJAOICEKI", "YJXZZCKSNMMWXZBYKMZNDADTMHBGJTKDHRWIDVIHPW", "POQKGXZMWPQQHV", "OLSYGLUSXUIUZAJMRRICPDVL", "BOWMBQPPIFWDYAXTYPVODJS", "UIFYUSFRVCRYGLAXPYKHUMQGMX", "LSCYNONYTIDTWVFXGBTEHVWOBCSHDCJUVZCPMSZFHZO", "WSZNTOCLOTCDRCGIFKYNA", "XCF", "SWVVOQLCKKSZZGMZPCLWPDFBSZHCBVMOSVQBRWJRN", "KLAAUEKIQPICASRCYHBFCQC", "AW", "LLDJOCCQDIAPSOMYQHBX" };
    String[] depends = { "12 30 20 27 32 27 35", "12 15 11 32", "39 28 5 6", "41 35 6 7", "19 26", "7 38 31 16 33 22 26 34 23", "12 31 27", "34 13 14 28 29 29", "30 26 9 39 26 17 26 13", "25 18 26 19", "22 20", "38", "25 41 35 24 15", "17 32", "29", "35 41", "18 27", "38", "24 29 24", "30 40 32 21 38 37", "32 28 30 21", "40 35 29 41", "25 39 25 39 34", "30 33 40", "", "33", "", "29 34 38", "39 39 40", "38 40 40", "34", "", "33 40", "", "", "37 41", "38", "41", "39", "", "41", "" };
    assertArrayEquals(new String[] { "BOWMBQPPIFWDYAXTYPVODJS", "CIPSPEGMHLUZTHTBWGBPFSQH", "KLAAUEKIQPICASRCYHBFCQC", "LLDJOCCQDIAPSOMYQHBX", "AW", "FBUQVEOWOWJGJDVMCMF", "OLSYGLUSXUIUZAJMRRICPDVL", "POQKGXZMWPQQHV", "QGAEWWVGIVANGEATERTFEXTHWLQHBIQOQSOUGXWPA", "SWVVOQLCKKSZZGMZPCLWPDFBSZHCBVMOSVQBRWJRN", "FDCQRRPXRKNBVJNPXJATKAZJKCXMSDZYKEVPFZCZOGNOUEENJK", "DIVPCXRLSZYKRSDVPOZIGPHHXGZTDZNG", "MYDEDAFKEVENDCADUYOZLNBRWDBTABNWJEYKINIG", "RJAOICEKI", "OP", "SHFEAQNHVXBYGQZJXFTNCVWRMILWESKCPPOHAEHBH", "UIFYUSFRVCRYGLAXPYKHUMQGMX", "LOGRRXYLZPPQDZUDZXYZNIBZRKF", "ODDYMOVPPCXQDUUYJYLEKQWNXBFUHPZYUH", "QJFCQONWRMUDWFXDZTWUXTUIJILMWFQO", "WO", "WSZNTOCLOTCDRCGIFKYNA", "XCF", "LSCYNONYTIDTWVFXGBTEHVWOBCSHDCJUVZCPMSZFHZO", "DOWRAXZHTKSMDMSZJZIJZYBLYT", "FANEEDJK", "DO", "YGOOQDOUFMECDNXTBPSQUJPNRGMNYZF", "YJXZZCKSNMMWXZBYKMZNDADTMHBGJTKDHRWIDVIHPW", "HNXCCFOXLGXDNCIFNPJILCHRJRUXWXDXTTOYXRTTSASCGS", "AN", "NDPCUIOZCNNMORMHFVH", "DJCSSQQBQ", "QKQKVTZHNSHERFFLAXJMPISWSMUBYPQLJZPFHP", "SKOUMWFAMYTBJKJQYJYYFGIKREVOWDOVBXODHXXLQKAKTALSQ", "OLNYUIDKTVZBFEWACNXZFIECGHISGEPOADXDEKJJZTAKXUTA", "QMVMUPDYRPFGYEQAXXQLNPJGQEFFNIMLSCISYXUUJTHQEO", "RNVZFQJZQDUCDMLBQ", "YNTEUOCARSKAECWWDYMWVFVQGTXNSOK", "JRXSXVJVMWHGULDAUPOLTGEXPLQ", "VYYHZYCYFTDNNYPKH", "ZCINGCTAODIKFZOVCFKTBJGSWCUEKX" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case26() {
    String[] funcs = { "CPKFMEUZRLKYOLPBIHHROLHNBHWPKRVTZWMCIZ", "WPBOL", "EFUHACAGKFCZO", "CEUKINOPEZSW", "GRYMLNEWJQPOMANWQTZSSTQCROANY", "XURFWGSZEAQABNUQZLCVJRPZITOUBISOZDXPNXP", "AVBBSASSJMJSRCIXHXCDYUXNWHZRHPOQNYTRXFTQLRN", "ECLWGFKNAAYA", "XYKKMFRKCRUXHLVAQN", "FXMIBJLVNFLMFQUQDT", "KNXW", "ZJJQWBMZZQZRLZI", "S", "XHFDPIUNQFPAKCKQZOTOJZVMM", "ETAXYAVWECJKQYLN", "CHCMFWYMVGIAOMQBHPMLYUQW", "CSZEAT", "UOFLHOEVNDVUAOCXIBQMLIZBWXEBKXHOUFIQZOSOGCM", "AEBLLLFJRYINATTEURNKSIKIN", "ZLSCEJUYYMIUFKUEBBFRG", "LUWCFYGTZQHIPFTRKIDUPDLVXOPLDSR", "NVTMZAWGOUDXMMFTAWBEZMXYFPILKYWOG", "PHQQDBKKWABXJWV", "DKCXLAXX", "WSITQSTTIWWYMRZYLZNFGZQTFPKZIBXBMSY", "ECRRKHQEUNBSY" };
    String[] depends = { "10 15 6 16 23 8 12 4 25", "6 23", "22", "", "", "7 11 14 17", "7 16 20 7", "", "16", "14", "12 24", "23 19", "22 14", "24", "18 18", "17", "", "23", "", "", "23", "22", "24", "", "", "" };
    assertArrayEquals(new String[] { "AEBLLLFJRYINATTEURNKSIKIN", "CEUKINOPEZSW", "CSZEAT", "DKCXLAXX", "ECLWGFKNAAYA", "ECRRKHQEUNBSY", "ETAXYAVWECJKQYLN", "FXMIBJLVNFLMFQUQDT", "GRYMLNEWJQPOMANWQTZSSTQCROANY", "LUWCFYGTZQHIPFTRKIDUPDLVXOPLDSR", "AVBBSASSJMJSRCIXHXCDYUXNWHZRHPOQNYTRXFTQLRN", "UOFLHOEVNDVUAOCXIBQMLIZBWXEBKXHOUFIQZOSOGCM", "CHCMFWYMVGIAOMQBHPMLYUQW", "WPBOL", "WSITQSTTIWWYMRZYLZNFGZQTFPKZIBXBMSY", "PHQQDBKKWABXJWV", "EFUHACAGKFCZO", "NVTMZAWGOUDXMMFTAWBEZMXYFPILKYWOG", "S", "KNXW", "XHFDPIUNQFPAKCKQZOTOJZVMM", "XYKKMFRKCRUXHLVAQN", "CPKFMEUZRLKYOLPBIHHROLHNBHWPKRVTZWMCIZ", "ZLSCEJUYYMIUFKUEBBFRG", "ZJJQWBMZZQZRLZI", "XURFWGSZEAQABNUQZLCVJRPZITOUBISOZDXPNXP" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case27() {
    String[] funcs = { "WDSMTJQDNCQTKQVGUWAWMNEJJXCWKJLWOWDFK", "TUQHHEBXFKOXTLTTILIFNQFSSZNZTSASFOTTIOANVZHJJ", "XPXPLJPNTGTZBPBJKLDHERJ", "BDUWGLMISRXRYOYBTP", "UMXOPJVMYDDWYZJCBSGOMZSJPEWAOBK", "HBAWUQLIKXJKSOXSJ", "ZEIMIIHJNJLJIXKADLIAZROVNMCOJUTFTVGZEVRUROENAKA", "JVSHBOICRQMUMGCWTCQGYWPULBCGEWCJXPG", "JAQCCKIZVEICD", "YBGNZPALRJKHMHYFKRPCJBWH", "ZCPJHBMOGTUTMNGGRJSCTOGOIIVLFEWVOYNBQRSVODSVUDZG", "TEWBYGCZGFTYDRILAAILCQGUAICSAFCXFSQMGSMLBHFLYEX", "ACDAOUFSCQMQIKFKJIKGQF", "MICSA", "ZXJNUIPESBCASWTEEZEXCASGGIXUREZSOTYGDW", "CYGSLOEJTZUAMAKDHIPMBBNPZMW", "V", "PANAFKZ", "HUGJBSSDMU", "AHYUGQDSGRHXWLKNMHWIRDGTXFBILCZCWWDRHLXBKN", "EIIYIVXYDBPCMCQVXBFYGJRVIGVDENWU", "ODXCPNKBIPOOMT", "EYSZKBDTLCSDGBCNVOVPYJLBUOBYDOYTSDNKSMRT", "XZFJOPPOLGHAPEPXSWNJXQLGROLJDRPPS", "QUQVWBEIGOVBXCWYOLAGRKPRKNQO", "Z", "IQOSEAAUYUPRORBCEJMMDGVYUO", "KTWLJGOXKAYBJBDK", "ATKIMFRTUXESWFXBPWPHEQZETIXWO", "BCXXVRUJELNMDYTQLCOVDIAFXPVZDJIOU", "OWYEYDCAUSISJCCAANTMSNWFRSMWGDRCLMKUXU", "AZJLAQWAKKTAVEVZNPHNLISXRXNXPNP", "ZOHDWLGJUCGQJGLLBCLZCJNQZKSCQUWCMVEAISOHRNWHD", "RLJOBLXIVBOJXPXOWJZHXUKIAYPBIPEZSBYIVQUCZGYCV", "LSVWB", "EBEFXMBDLFMMYMK", "OFXOFLRCIGIFCTGGUNPGOCREYUDFPWEQATFRVTGTCSNYYE", "PO", "UKFXXOSAEDZJWYAZTICIGLZCCURIZSGRSNEBHRLNODI", "ZFJOOKIJ", "PTDBRMHQA", "QKOSTJYXZJDYJBXTCRVTAOQELMNTHNXNK", "JCDRVZBQBDEPJAHDMRKYXAQJFRLDUQRIWQITQIJKTDSEAYTY", "JRVXDMTRPYACVAOZP", "DVVOQEHEGHIEDFDAUYFNQUTWS", "UETQGVHVFJ", "FURLOWFUCGPIMCLCLMMUMKUW", "WLVAHJVTAKGGLNWVZOAXNYEQZWSLJLYCUNG", "UHVTEMFUUTLIQBIQHRVEQFBKNWASFFCPNSLCPCVO" };
    String[] depends = { "27 27 27 23 11 40", "", "12 9", "31 31 17 39 31 34 8 23 24 32 43 38", "17 37 32", "20 32 46 45 28 10", "37 13 30", "", "10 15 16", "", "", "29 17 14 43", "", "38", "40 37 18 26 18 15 24 22", "39 23 34 27 30", "45 22 41 25 39 31 32 24", "39 23 33", "", "27 46", "42 23", "34 26 35 38 32", "33 43 27", "47 42 46 32 48 25", "39 46 38 33", "26 41", "", "31", "", "38 45", "48", "47 45 36 41", "34 44", "45", "38 41", "42 47 40", "43", "45 43 41", "", "44 47", "", "47 44", "", "48", "47", "48", "47", "", "" };
    assertArrayEquals(new String[] { "ACDAOUFSCQMQIKFKJIKGQF", "ATKIMFRTUXESWFXBPWPHEQZETIXWO", "HUGJBSSDMU", "IQOSEAAUYUPRORBCEJMMDGVYUO", "JCDRVZBQBDEPJAHDMRKYXAQJFRLDUQRIWQITQIJKTDSEAYTY", "JVSHBOICRQMUMGCWTCQGYWPULBCGEWCJXPG", "PTDBRMHQA", "TUQHHEBXFKOXTLTTILIFNQFSSZNZTSASFOTTIOANVZHJJ", "UHVTEMFUUTLIQBIQHRVEQFBKNWASFFCPNSLCPCVO", "JRVXDMTRPYACVAOZP", "OFXOFLRCIGIFCTGGUNPGOCREYUDFPWEQATFRVTGTCSNYYE", "OWYEYDCAUSISJCCAANTMSNWFRSMWGDRCLMKUXU", "UETQGVHVFJ", "RLJOBLXIVBOJXPXOWJZHXUKIAYPBIPEZSBYIVQUCZGYCV", "UKFXXOSAEDZJWYAZTICIGLZCCURIZSGRSNEBHRLNODI", "BCXXVRUJELNMDYTQLCOVDIAFXPVZDJIOU", "MICSA", "WLVAHJVTAKGGLNWVZOAXNYEQZWSLJLYCUNG", "DVVOQEHEGHIEDFDAUYFNQUTWS", "EBEFXMBDLFMMYMK", "FURLOWFUCGPIMCLCLMMUMKUW", "QKOSTJYXZJDYJBXTCRVTAOQELMNTHNXNK", "AZJLAQWAKKTAVEVZNPHNLISXRXNXPNP", "KTWLJGOXKAYBJBDK", "AHYUGQDSGRHXWLKNMHWIRDGTXFBILCZCWWDRHLXBKN", "EYSZKBDTLCSDGBCNVOVPYJLBUOBYDOYTSDNKSMRT", "LSVWB", "PO", "YBGNZPALRJKHMHYFKRPCJBWH", "XPXPLJPNTGTZBPBJKLDHERJ", "Z", "ZCPJHBMOGTUTMNGGRJSCTOGOIIVLFEWVOYNBQRSVODSVUDZG", "ZEIMIIHJNJLJIXKADLIAZROVNMCOJUTFTVGZEVRUROENAKA", "ZFJOOKIJ", "QUQVWBEIGOVBXCWYOLAGRKPRKNQO", "ZOHDWLGJUCGQJGLLBCLZCJNQZKSCQUWCMVEAISOHRNWHD", "ODXCPNKBIPOOMT", "V", "XZFJOPPOLGHAPEPXSWNJXQLGROLJDRPPS", "CYGSLOEJTZUAMAKDHIPMBBNPZMW", "EIIYIVXYDBPCMCQVXBFYGJRVIGVDENWU", "HBAWUQLIKXJKSOXSJ", "JAQCCKIZVEICD", "PANAFKZ", "BDUWGLMISRXRYOYBTP", "UMXOPJVMYDDWYZJCBSGOMZSJPEWAOBK", "ZXJNUIPESBCASWTEEZEXCASGGIXUREZSOTYGDW", "TEWBYGCZGFTYDRILAAILCQGUAICSAFCXFSQMGSMLBHFLYEX", "WDSMTJQDNCQTKQVGUWAWMNEJJXCWKJLWOWDFK" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case28() {
    String[] funcs = { "BQARQHGQVRRXQKAMGZGWBZKIJDTEJXLK", "IZTGWJPAYELSCBSJDMKYUOIAGJONNLYVHHECWNSWNZKWWGWAV", "QYNEEJLZFB", "MNVDHSXIPJ", "YMMSSLEKRVKSEDDQGZYRYNKDIKC", "GMTDTCOZROZRDUKXW", "NXFTOZVLXWLBEZQCEWMEJG", "MMYUMMENWPJVUTQWEHFZRSNPJYWRFRFZFBKCIK", "HLQERKJICO", "IMPLQDEIHVNIOLNXESSYPCZXMHAFSOPUJNGFZGLOH", "OAXDLIMBAWAALSLECZKGCNLOC", "EACAAFTOWCUQKRSADCSJFVZNCFAFTEMXXLZXQMM", "FINCEEECQJSBZVDPLMHFMXVKVOBNHWDKMXNYWZUX", "VIEWSXZC", "TUSGO", "P", "FDEWDGKVSOSSYHINMXA", "T", "SCJFRTBOWYICKBXCPDZDUWDY", "NCPQFAVYMAUMXTUGIJPEYVRTWGZIZRSIUAMVXEWLHQT", "IANMNEYPBHVNBKK", "OAILKEXUOPIVPBKGMHMEORMW", "THNSJQIEOPWJNCQTRAWKHBOXYNAMVKDBPXLXBZCISIGTYI", "AWSCSDYIELJPIMANAFJXPITYOXGGO", "XSVOEGPPKTTDUQCO", "FJAOQXDEZKMDMVODGUCFYBNQZGLQTVYN", "OLEFUKOJJWWQOOGHKZ", "VDUACCUQQPOYCFWAJJZFIANCKVHOBE", "CPXKTJYPPXJIFQURWROUJYXURJQ", "IQRFNXIEDXFFGGGEOCVIOWMUIKMCKF", "KVG", "LQJMBMVNBLHFYHPXFUNCU", "VJWAQBQKZYOGRJZBIIPY", "HOSJMRKJNUULAMIGSDGBTACMBUDOFEMENZCNE", "EASQWIAJCSBX", "PKFYKNKARSFXIZBSGLFWETHWSWYCSDTATLOQ", "WTYVHDYU", "RVRVAGLQPBSCODWXRNSJMYJBTFFOIKHO", "TYXCDMKMTMHRYVMNLPSIPRDHDXAECLTJTFEVHZCWFE" };
    String[] depends = { "26 15 12 32 8 4 23 2", "16 30 7 10 38", "8", "28", "11 7 5 27 8 24 19 23", "26 28 37 20 37 8", "25 28 32 33 20 8 11 7", "24 24 12 8 19", "35 20 36", "29 23", "24 36 11 28 25 18 26", "26 34 20 28 32", "13 16 13 30 19 27 37", "", "", "31 26", "", "26 36", "25 25 19 27", "21 25 21 25", "35 24 22", "", "37 29 28 28", "29 24 36 38", "", "28", "29 35 30", "38", "29 33", "38", "35", "", "", "35 35", "35", "37", "", "", "" };
    assertArrayEquals(new String[] { "FDEWDGKVSOSSYHINMXA", "LQJMBMVNBLHFYHPXFUNCU", "OAILKEXUOPIVPBKGMHMEORMW", "RVRVAGLQPBSCODWXRNSJMYJBTFFOIKHO", "PKFYKNKARSFXIZBSGLFWETHWSWYCSDTATLOQ", "EASQWIAJCSBX", "HOSJMRKJNUULAMIGSDGBTACMBUDOFEMENZCNE", "KVG", "TUSGO", "TYXCDMKMTMHRYVMNLPSIPRDHDXAECLTJTFEVHZCWFE", "IQRFNXIEDXFFGGGEOCVIOWMUIKMCKF", "CPXKTJYPPXJIFQURWROUJYXURJQ", "FJAOQXDEZKMDMVODGUCFYBNQZGLQTVYN", "MNVDHSXIPJ", "NCPQFAVYMAUMXTUGIJPEYVRTWGZIZRSIUAMVXEWLHQT", "OLEFUKOJJWWQOOGHKZ", "P", "THNSJQIEOPWJNCQTRAWKHBOXYNAMVKDBPXLXBZCISIGTYI", "VDUACCUQQPOYCFWAJJZFIANCKVHOBE", "SCJFRTBOWYICKBXCPDZDUWDY", "VIEWSXZC", "FINCEEECQJSBZVDPLMHFMXVKVOBNHWDKMXNYWZUX", "VJWAQBQKZYOGRJZBIIPY", "WTYVHDYU", "T", "XSVOEGPPKTTDUQCO", "AWSCSDYIELJPIMANAFJXPITYOXGGO", "IANMNEYPBHVNBKK", "EACAAFTOWCUQKRSADCSJFVZNCFAFTEMXXLZXQMM", "HLQERKJICO", "GMTDTCOZROZRDUKXW", "IMPLQDEIHVNIOLNXESSYPCZXMHAFSOPUJNGFZGLOH", "MMYUMMENWPJVUTQWEHFZRSNPJYWRFRFZFBKCIK", "NXFTOZVLXWLBEZQCEWMEJG", "OAXDLIMBAWAALSLECZKGCNLOC", "IZTGWJPAYELSCBSJDMKYUOIAGJONNLYVHHECWNSWNZKWWGWAV", "QYNEEJLZFB", "YMMSSLEKRVKSEDDQGZYRYNKDIKC", "BQARQHGQVRRXQKAMGZGWBZKIJDTEJXLK" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case29() {
    String[] funcs = { "LMNAZIUCIVVRZDNAWWHAGWXKRFPLDFPSUBP", "PORLIWOO", "XXPSQZWVYNELMWNPWKTKGGTZUZVKWWCACIMVXKUKDXV", "CGICRCLGWUARILXRQZLZDLKFPWXOXXAYADADAKLKVLCE", "WJCDEUHJDYXPPLVQGJSCSTIIDKXCODBEBU", "GSFLHDTXVXNRTSPFGISDZBATOJGVGUYPXYYA", "FOIFBHSQCHMJG", "C", "ZYYBESZHUJSACDNREZ", "PIXLSED", "KSVTXSUPPGODSXVELMXMZURJZA", "KJTVJGBIQAYFSAXZTYWWYDJLLNW", "CEKICAPYBTORHDN", "HFJEKJMGCZAWXTDMHDULBBLFQXLZGPFOJEYHPKOOQXTJLBL", "ATKBWYDGDOBLAVUSASYLWLVMPUVBPWNGIZOHZALTPQRFDHB", "FUPUTYC", "ANMEVOEEFQOIZSDHZBNLDIUKAHFNUFDUXBC", "SODGSSQHKLZQKRXGOKTGMDCTMTTMJHWCUGGFWBCJ", "PUIWMDWXWSGPFMSJXSKICDHPBHSSPFSPQIDJHMJ", "DMDLLRMACTFXKDLPKAJHGHLLWJQABFZPQVNZSY", "XTSOCDDTKRFWP", "PUUUSNTSPVZTOBIZOEQGJDXEMKNHQWRLKVFSCKRDYBLXK", "KCWKQAMOKLKNMPCAOWZUG", "JZUFOVNN", "GJZCCOLWMQ", "FGUCKYHZRTJLHXCWQHSZRFEONKVZGOOFETZDHIXSR", "EAPWRANQORRYVSLMAYLMHOPFQCOWLAILEHCLONNAQBXDLJD", "SVFXVTSUGLZDWTWNXQPITJVOKM", "LZKWPIAJLES", "PJOJWHVQFWMWEHKVKMKJMNTYYNWRUKHFVMWLQSEWTP", "QRFOSUHECYCH", "SSWXONMEPETAEDRWGRHULNSUUMGFMRZGA", "IWMOCZCYQXDQGWXOBZDHUJOMAO", "IRAAKTHDOCXMIWWCGUFVWYCLNRSIWWVJCIGYY", "AFOKGXWYQVYGEFAJXZHICEEG", "AAUGVRYUJPWGMBFBWVMZFRSCKOQVIYNIKCAGYCNKH", "LGLMCWYWKZYGKOKLLEWRCEDKWNJTRROUA", "XRAXSDXKPJWBQWTJAXLBVXHLH", "UHWBMGZDI", "VRYPIMLHTYJTWFWVFREEWXFDXMUVXJMQXLKTIEPDJSHPQ", "WGYT", "CHLLXHBUMVZXXQOEFRZSI", "DJELAUCPD", "KQJULSWKOVLYNRAEGOKFQVHNTMPBDXXQLCETNTWPGDHAER", "HCDZMXZFRQWJBENAKMVJRWEEEWXBPTHBLDPFYVHXS", "TVGYBP", "UAOAIOUDT" };
    String[] depends = { "15 1", "8 33 26 26 2 33 45 12 19 21 26 20", "24 15 10", "40 31 36 11 6 31 26", "16 5 15 27 32 31 46 38", "31 30 44 43 46", "41 34 44 34 46 28 16 17", "42 20 30", "32 11 15 16 25 18 21 12 35", "22 21 31 32 11 36", "32", "37 42 25 33 17 34 20 18", "24", "27 30 37 32", "42", "30 34 22", "30 18 21 32 40 23", "32 27 21 26 28 46 22", "46", "23 38 39 41 36 31 40", "29 21", "30 28 33 42 41", "", "35 36", "30 40 42 37 33 25", "44 43 39 33", "28 41 31 33 41", "31 39 31", "31", "", "", "33 40 42 39", "36", "", "40 38 44", "40 36", "43", "39 42", "", "43", "42", "43", "43", "45", "45", "46", "" };
    assertArrayEquals(new String[] { "IRAAKTHDOCXMIWWCGUFVWYCLNRSIWWVJCIGYY", "KCWKQAMOKLKNMPCAOWZUG", "PJOJWHVQFWMWEHKVKMKJMNTYYNWRUKHFVMWLQSEWTP", "QRFOSUHECYCH", "UAOAIOUDT", "PUIWMDWXWSGPFMSJXSKICDHPBHSSPFSPQIDJHMJ", "TVGYBP", "HCDZMXZFRQWJBENAKMVJRWEEEWXBPTHBLDPFYVHXS", "KQJULSWKOVLYNRAEGOKFQVHNTMPBDXXQLCETNTWPGDHAER", "CHLLXHBUMVZXXQOEFRZSI", "DJELAUCPD", "ATKBWYDGDOBLAVUSASYLWLVMPUVBPWNGIZOHZALTPQRFDHB", "LGLMCWYWKZYGKOKLLEWRCEDKWNJTRROUA", "IWMOCZCYQXDQGWXOBZDHUJOMAO", "KSVTXSUPPGODSXVELMXMZURJZA", "UHWBMGZDI", "VRYPIMLHTYJTWFWVFREEWXFDXMUVXJMQXLKTIEPDJSHPQ", "FGUCKYHZRTJLHXCWQHSZRFEONKVZGOOFETZDHIXSR", "WGYT", "AAUGVRYUJPWGMBFBWVMZFRSCKOQVIYNIKCAGYCNKH", "AFOKGXWYQVYGEFAJXZHICEEG", "FUPUTYC", "JZUFOVNN", "SSWXONMEPETAEDRWGRHULNSUUMGFMRZGA", "DMDLLRMACTFXKDLPKAJHGHLLWJQABFZPQVNZSY", "GSFLHDTXVXNRTSPFGISDZBATOJGVGUYPXYYA", "LZKWPIAJLES", "EAPWRANQORRYVSLMAYLMHOPFQCOWLAILEHCLONNAQBXDLJD", "PUUUSNTSPVZTOBIZOEQGJDXEMKNHQWRLKVFSCKRDYBLXK", "ANMEVOEEFQOIZSDHZBNLDIUKAHFNUFDUXBC", "SVFXVTSUGLZDWTWNXQPITJVOKM", "SODGSSQHKLZQKRXGOKTGMDCTMTTMJHWCUGGFWBCJ", "FOIFBHSQCHMJG", "WJCDEUHJDYXPPLVQGJSCSTIIDKXCODBEBU", "XRAXSDXKPJWBQWTJAXLBVXHLH", "GJZCCOLWMQ", "CEKICAPYBTORHDN", "HFJEKJMGCZAWXTDMHDULBBLFQXLZGPFOJEYHPKOOQXTJLBL", "XTSOCDDTKRFWP", "C", "KJTVJGBIQAYFSAXZTYWWYDJLLNW", "CGICRCLGWUARILXRQZLZDLKFPWXOXXAYADADAKLKVLCE", "PIXLSED", "XXPSQZWVYNELMWNPWKTKGGTZUZVKWWCACIMVXKUKDXV", "ZYYBESZHUJSACDNREZ", "PORLIWOO", "LMNAZIUCIVVRZDNAWWHAGWXKRFPLDFPSUBP" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case30() {
    String[] funcs = { "AJUDSOXEPAFKRUGNVWOGCAJCXVPQQVCUOGXOSMFWMJCRZ", "WKZAKQXSAVHVHSFVEJF", "TFIUPPNMACCWAXOAXJXBZARBLOQMNLQOEJTBMDKKWZCVDUHZ", "TGPQJRPZNBINVOBBHCTGHTBOPGSQUTVLADVJSALUVRXPFNNJG", "LHUGPAEPCWTRRHNQIPVIQWUPTD", "HZZOEQBLNZDBKNHLRMKMAQS", "GFZQAJOHLLUMGWXAGGUMTMIQ", "IREIFELMFESCIGNQYTIW", "HICMYTVOIDNGAYURINQRGHYDRYPNSIFQODSQ", "EUFSRSGIAOMPMJOEPUHDHYF", "ULGEFTUGZTBXBPKNRTFKDIZVYSKDKH", "IZ", "ZNIWZGMYOICWRMFOJDFGYDQXYBBJAUFCLA", "RFIYLHINDDEYDNFN", "LYYOMHZUFXTVDAXXNKQMTJDCVLCQEAVJOGD", "NGZFQOWCPAXEYJWDMVSKTGZEVAYXHXNRPIVHIS", "ZJIBENEYQADBRYLXYBOQYSVINFYJRIFYSYLFMHSCCX", "YPMZBDKBRFVXWKZMHBQZNJXSCVFVPSQVD", "ISVVIXVIQCLMJJLBHYUETNNWLNUOUBLAOQLGLOYXFG", "YXBOIJZBFAIFFXQX", "WTPVFOENGKSRPHTXDWMPVAPSGOANRBGUKHLXGKIUHVZFU", "AOQGXKT", "RVYOSMUUBMYDSXUDEFBGNGURMAWPSNERPQRTBTGQRAAPENVP", "ZCBCKSVIMJIPNCDQJYNUYCOJRDERIKTBFZSNINMXCSWKCOFBEH", "UTKLJNVGYBNMRCEONS", "PLZKOWXPUEEGPTWD", "ATQFUJGRCTHA", "EBAGJZWUOFVGNIQNWJUONDMZVOGQJUNLJURPIZFYUNEOL", "XVLDAHZ", "LIFOCOCFLYZOLUBXXCEMTKACVMGLWMHDNOCGEDB", "FERKHB", "IMCLDNBKVVFYJELPTDLDQIRMAFYBJCTMUFQFN", "UVUFXEWXKBDRWATM", "LLXZVLTCLTQODQCWKPMGQA", "SWVNMKRORDZPCPREKVUBQXPSQGRABYWGPCIDEYKMSSBUBCDHY", "KYQCJDHPRGDTKQJZFWRGZCVIHWQXUYZJFQIMZ", "EOANFTRBHQA", "TBKJIDEFR", "RCWVQQMPMWOGHGCOSLQGGKGYTEKIGGXFXQUIH", "YEXARYBXPWOQS", "LAWQALKZAJCZKMBAQYLWHPXRTWLHGPTWCKLTGAQJBYBTGOZ", "GD", "IRMLRAMLNVFDGVZSYNXINXMOCNSVNRESEBOPBHFK", "GKAEBDNWUXT", "AHJTEWWRKNBCLTQAEMBZQBUUKGPECAGYAV", "JGZKPAOPSYYWRDQ" };
    String[] depends = { "25 44", "", "15 18 36 34 26 24 4", "", "17 23 6 25 38", "32 23 45 31 34 26 25 9 35", "29", "13 17 43 40 23", "34", "20 25 29 31 27 44", "26 23 40 14 12 37 14 44", "26 17 26 29 39 42 28", "30 16", "", "35 32 16 36 24 24", "33 35 39 45 26 37 20", "34 20 17 20", "32 37 18 26 29 26", "", "31", "33", "24 32 31 26", "30 24 23 44 28", "34 40 39 34", "36 30", "", "33 34 35", "36 36 30", "38", "41 31 34 45", "", "33 33", "38", "42 45 34", "35 39", "", "37 44", "43", "39 42", "40", "", "45", "", "44", "", "" };
    assertArrayEquals(new String[] { "AHJTEWWRKNBCLTQAEMBZQBUUKGPECAGYAV", "FERKHB", "GKAEBDNWUXT", "IRMLRAMLNVFDGVZSYNXINXMOCNSVNRESEBOPBHFK", "ISVVIXVIQCLMJJLBHYUETNNWLNUOUBLAOQLGLOYXFG", "JGZKPAOPSYYWRDQ", "GD", "KYQCJDHPRGDTKQJZFWRGZCVIHWQXUYZJFQIMZ", "LAWQALKZAJCZKMBAQYLWHPXRTWLHGPTWCKLTGAQJBYBTGOZ", "PLZKOWXPUEEGPTWD", "AJUDSOXEPAFKRUGNVWOGCAJCXVPQQVCUOGXOSMFWMJCRZ", "RFIYLHINDDEYDNFN", "TBKJIDEFR", "EOANFTRBHQA", "EBAGJZWUOFVGNIQNWJUONDMZVOGQJUNLJURPIZFYUNEOL", "TGPQJRPZNBINVOBBHCTGHTBOPGSQUTVLADVJSALUVRXPFNNJG", "UTKLJNVGYBNMRCEONS", "WKZAKQXSAVHVHSFVEJF", "YEXARYBXPWOQS", "RCWVQQMPMWOGHGCOSLQGGKGYTEKIGGXFXQUIH", "SWVNMKRORDZPCPREKVUBQXPSQGRABYWGPCIDEYKMSSBUBCDHY", "HICMYTVOIDNGAYURINQRGHYDRYPNSIFQODSQ", "LLXZVLTCLTQODQCWKPMGQA", "ATQFUJGRCTHA", "IMCLDNBKVVFYJELPTDLDQIRMAFYBJCTMUFQFN", "LIFOCOCFLYZOLUBXXCEMTKACVMGLWMHDNOCGEDB", "GFZQAJOHLLUMGWXAGGUMTMIQ", "UVUFXEWXKBDRWATM", "AOQGXKT", "WTPVFOENGKSRPHTXDWMPVAPSGOANRBGUKHLXGKIUHVZFU", "EUFSRSGIAOMPMJOEPUHDHYF", "NGZFQOWCPAXEYJWDMVSKTGZEVAYXHXNRPIVHIS", "XVLDAHZ", "YPMZBDKBRFVXWKZMHBQZNJXSCVFVPSQVD", "IZ", "YXBOIJZBFAIFFXQX", "ZCBCKSVIMJIPNCDQJYNUYCOJRDERIKTBFZSNINMXCSWKCOFBEH", "HZZOEQBLNZDBKNHLRMKMAQS", "IREIFELMFESCIGNQYTIW", "LHUGPAEPCWTRRHNQIPVIQWUPTD", "RVYOSMUUBMYDSXUDEFBGNGURMAWPSNERPQRTBTGQRAAPENVP", "TFIUPPNMACCWAXOAXJXBZARBLOQMNLQOEJTBMDKKWZCVDUHZ", "ZJIBENEYQADBRYLXYBOQYSVINFYJRIFYSYLFMHSCCX", "LYYOMHZUFXTVDAXXNKQMTJDCVLCQEAVJOGD", "ZNIWZGMYOICWRMFOJDFGYDQXYBBJAUFCLA", "ULGEFTUGZTBXBPKNRTFKDIZVYSKDKH" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case31() {
    String[] funcs = { "ORJOWHBFWJUJZZLZNJMPOTEFRPGOIXQOFAPFXFCMAFHRGG", "YVWWXGVMWHEDYERQPWMRND", "HNCQISSGJICPREIZTUGZQTVCXCNIUCYZHJYXBZSUXEHY", "XFARB", "HWPUZCBZXAKTJUBMIPZSRRMH", "GRHR", "SWJAYKBXMFLQAYUJQRDDICRJIAIHZZUASHNFIDEYMDGR", "YBTCIRULGOQRIAKJRDUER", "Q", "IBWZPPJEEXOOLFTYP", "DQEISJU", "UCYDLLLMIDOTWUADMYWZEHN", "NFLQKNSO", "MAEUFVHAWWAHVXODJNIFBMKKKBEQIXFHKTJVDX", "OHNRVUFXEUI", "AUVRNGYGNISFAXCBRUDBQJIZ", "GJZHIETTAATMVYDGCOIRYYMORWOXEGFV", "UPDYZKPGKKYDZCZCVJWQEYPJNOZSESQRVMI", "QSQZLLOEAKWYZBGYTSYINUOBASDSYLPOCA", "VMPA", "XJB", "KFNY", "BTDGCHERMOJNGNRENBGASYSOGSC", "QHQLHFIDEUEBIZCYSUZWOTVJM", "GXJZMRCFCJSLKOWUACNQNRPAOAJIBYUVRVZAVHIZHGNPXYYWU", "IQDCRYLPHWMFICAGJAPVEFIYBWKSETMQB", "MPSEPLO", "QOYMIBUCJQJPEKQKJFJBDAAHBONJDMLS" };
    String[] depends = { "", "11 17", "6 15 11 18", "20", "24 15 12 9 10", "7 12 22 17 12", "12", "24 18", "12", "", "15 25 27 22", "", "14", "23", "25 18 16", "16", "", "", "23 21", "", "21 27", "", "", "25", "", "", "", "" };
    assertArrayEquals(new String[] { "BTDGCHERMOJNGNRENBGASYSOGSC", "GJZHIETTAATMVYDGCOIRYYMORWOXEGFV", "AUVRNGYGNISFAXCBRUDBQJIZ", "GXJZMRCFCJSLKOWUACNQNRPAOAJIBYUVRVZAVHIZHGNPXYYWU", "IBWZPPJEEXOOLFTYP", "IQDCRYLPHWMFICAGJAPVEFIYBWKSETMQB", "KFNY", "MPSEPLO", "ORJOWHBFWJUJZZLZNJMPOTEFRPGOIXQOFAPFXFCMAFHRGG", "QHQLHFIDEUEBIZCYSUZWOTVJM", "MAEUFVHAWWAHVXODJNIFBMKKKBEQIXFHKTJVDX", "QOYMIBUCJQJPEKQKJFJBDAAHBONJDMLS", "DQEISJU", "QSQZLLOEAKWYZBGYTSYINUOBASDSYLPOCA", "OHNRVUFXEUI", "NFLQKNSO", "HWPUZCBZXAKTJUBMIPZSRRMH", "Q", "SWJAYKBXMFLQAYUJQRDDICRJIAIHZZUASHNFIDEYMDGR", "UCYDLLLMIDOTWUADMYWZEHN", "HNCQISSGJICPREIZTUGZQTVCXCNIUCYZHJYXBZSUXEHY", "UPDYZKPGKKYDZCZCVJWQEYPJNOZSESQRVMI", "VMPA", "XJB", "XFARB", "YBTCIRULGOQRIAKJRDUER", "GRHR", "YVWWXGVMWHEDYERQPWMRND" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case32() {
    String[] funcs = { "AOLI", "FGUJQ", "IIDYUMDRMCQLQJXZNQNXKDUDBRBCIT", "QZZJXBLXLBVEWOFOJHOASEGFPR", "ZULPIFIVCOKNPSJPVCFCKMDONSQOHGWPCHLBOSCQKWBWSWEA", "CXDYSVHCVBFPNNGKMPGUODYGSHQVJIVR", "WNSNCKSXSJQVIPXHFJMDDNRALZLPNQXXLLGGV", "MXXFYODHRPOOGWYYTSTBCYPDLOWZ", "IRKJ", "XVBDRZSIXZOEIXMQNBHVIXGPMITFNQLGALNYT", "BJOVZLCBXTABQQL", "JWMQUFDWTKMEVJDXTQTEZCZBBXOHPUUBWJ", "BSVGUHCQEO", "QMUAVFENTNZCJXSSDTTXXTAKRABGRQFVARGMACBCGERD", "ZOUGJBLXXIJEFESZSIQBEEWPAEHGQEAAUPLXPV", "LQDDOCPLTNLSNONCXCAMMOOOKKKCXCBEVCXCPGKHIFCMFN", "CENDBTPUTFZMCZMUDHMG", "BIPGYZUIXTUTSKCLWKYLSTKWZLCSEXSGTB", "DXZBQKWSZUX", "BORANFURWQQYVTOTGKAH", "NJMWLOGRRFOHQACZZHWLTSLIHOXBWXWNAHNKVLLURMDOXDE", "HKKADINFBCTCWJYTSWTQJEGEAVQGDQHLK", "YZNCIIJHVUFBPP", "IRZULTSBLQUBELIRBYURTUPLJQNSRUYTTWWXXZKBMPO", "MTDHYYVLXAXQKRSBUQSSJVRNEY", "GCDAG", "DUPBMMO", "ZEEQNTDDDUYH", "UJYRR", "KSMBUSGWOCEVJTIJDSBQIHBURFQGWFCLQXLSEMJJQIIAZJGM", "UAKBE", "MSRRYPQGAXEHAXLAJKRIYTUW" };
    String[] depends = { "22 7 2 7 29 24 29 12", "2 7 8 24", "30 12 5 13 24 19 22", "6", "", "18 10 9 21 18", "25 20 10 21", "27", "29 12 16 10", "21", "24 21 29 14 31 13", "13 31 31 26", "17", "19 20 23", "", "", "", "18 20 20 27", "21", "25", "23 22 23", "", "27 25", "", "26 28", "28 28", "31", "", "31", "", "", "" };
    assertArrayEquals(new String[] { "CENDBTPUTFZMCZMUDHMG", "HKKADINFBCTCWJYTSWTQJEGEAVQGDQHLK", "DXZBQKWSZUX", "IRZULTSBLQUBELIRBYURTUPLJQNSRUYTTWWXXZKBMPO", "KSMBUSGWOCEVJTIJDSBQIHBURFQGWFCLQXLSEMJJQIIAZJGM", "LQDDOCPLTNLSNONCXCAMMOOOKKKCXCBEVCXCPGKHIFCMFN", "MSRRYPQGAXEHAXLAJKRIYTUW", "DUPBMMO", "UAKBE", "UJYRR", "GCDAG", "BORANFURWQQYVTOTGKAH", "MTDHYYVLXAXQKRSBUQSSJVRNEY", "XVBDRZSIXZOEIXMQNBHVIXGPMITFNQLGALNYT", "ZEEQNTDDDUYH", "MXXFYODHRPOOGWYYTSTBCYPDLOWZ", "YZNCIIJHVUFBPP", "NJMWLOGRRFOHQACZZHWLTSLIHOXBWXWNAHNKVLLURMDOXDE", "BIPGYZUIXTUTSKCLWKYLSTKWZLCSEXSGTB", "BSVGUHCQEO", "QMUAVFENTNZCJXSSDTTXXTAKRABGRQFVARGMACBCGERD", "JWMQUFDWTKMEVJDXTQTEZCZBBXOHPUUBWJ", "ZOUGJBLXXIJEFESZSIQBEEWPAEHGQEAAUPLXPV", "BJOVZLCBXTABQQL", "CXDYSVHCVBFPNNGKMPGUODYGSHQVJIVR", "IIDYUMDRMCQLQJXZNQNXKDUDBRBCIT", "AOLI", "IRKJ", "FGUJQ", "WNSNCKSXSJQVIPXHFJMDDNRALZLPNQXXLLGGV", "QZZJXBLXLBVEWOFOJHOASEGFPR", "ZULPIFIVCOKNPSJPVCFCKMDONSQOHGWPCHLBOSCQKWBWSWEA" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case33() {
    String[] funcs = { "DRCKHZCVBYOJUXSGMAZVQ", "NRZPNXXHGOTPA", "PPOGELQOBQSPFRHXOCYJALEL", "QAVJVFXADQDDSRCMHDAWVMPVGVAIRWDHVMEV", "XGZHZOUZVOJSPOJSRLVKTRVPTNCRISBLEAW", "EMCPFMEQTIQQAAYLLKLMZCNXFKAIEUCUZAZVBJHWGGNVTWQ", "NFBQS", "YITIPRDBBRZCHZMTDETKZQ", "LGDPDOHCBVSQNQTDIEIWWZGQFDJXWWHVHFJKEWUILNWMYDUKE", "PGGXARFQEKPDCMAYOPLXJMFLNASYEADNEWIAMTICKWQS", "DCWNTWPHUVANVVYCF", "OXHEFZBCXWYBLHWBJZQOUXJVQQPHCXBLIOF", "KUSZLHIVGFXKVTUNKLKUSPZEHUUVIXHCLDXPE", "RBBLJTRPYUKFAERGRMLDNMXSFG", "JTLLGOSTFKPIJTKQM", "PXIGGLEKWLVOHXTLBSJT", "GUFKDTWJANRNUPLNFEQOLYBFBNDYIOVNMNXVPOXSLQAM", "XVIQKIAFXIATAYQTQNTIQQHBPOMWBPBFZESPFRW", "LATWMBSJKKN", "LPJYPMSEDOTPQARBVVOVKVNIFPQOQDXMEYO", "KHLGDACGQCGXNWRMNJGANUAUCLYPEUMPU", "SZHEPPTBMBQBTOOIAVQTIKPYQZSIODMJNJXF", "CUNJKKMGLJIWSVPCWWHANASKTHXXFHFICNDAVCJUQRB", "NLOXNSDDCLCMVAZXMSKOASQKGAUVLGDWFSTGUYEA", "FPKTLGOBLXDHEPOQMYYIXHCQZIQDIZS", "QL", "YHKWVTWNHQSNUSZRRLCNTLMRXPHFFZS", "UKBXTYLHLYQISZBNWPGELKHUNPTPBNQESOWR", "HVYDVZAGQIAJEKBQFZPKCZVNPIPCNNFPBDAU", "MPIXZS", "YFGFBSPYWQALKYLKBROIONBUOTC", "CDCUSIUCGPJNRKDUHQHZZYTVBEQOYLPSMYUOFLQDDVI", "HYGKNPQHAAUYVGFNAFCWJOFFGDWIXN", "OOWJGIY", "RAN", "REXIBQSPDZEZEQDNNWWFUFWNGBWAOSDPVJGNP" };
    String[] depends = { "23 6 18 23 33", "31 5 2 22 23", "7 25 22", "8 35 17 5 14 33", "15 13 24 17", "19 16 22", "31 22 34 20 24 18", "21 20 19 26", "26 13 35 31 19 15", "14 26", "22 16", "19 12", "30", "28 31", "32 16 18", "34 28 24 20", "", "19 27 30", "29 25 25", "21", "", "30", "35 32 26 24", "32 26 26", "", "32", "", "35", "", "33 30", "", "", "34", "", "", "" };
    assertArrayEquals(new String[] { "CDCUSIUCGPJNRKDUHQHZZYTVBEQOYLPSMYUOFLQDDVI", "FPKTLGOBLXDHEPOQMYYIXHCQZIQDIZS", "GUFKDTWJANRNUPLNFEQOLYBFBNDYIOVNMNXVPOXSLQAM", "HVYDVZAGQIAJEKBQFZPKCZVNPIPCNNFPBDAU", "KHLGDACGQCGXNWRMNJGANUAUCLYPEUMPU", "OOWJGIY", "RAN", "HYGKNPQHAAUYVGFNAFCWJOFFGDWIXN", "PXIGGLEKWLVOHXTLBSJT", "QL", "RBBLJTRPYUKFAERGRMLDNMXSFG", "REXIBQSPDZEZEQDNNWWFUFWNGBWAOSDPVJGNP", "UKBXTYLHLYQISZBNWPGELKHUNPTPBNQESOWR", "YFGFBSPYWQALKYLKBROIONBUOTC", "KUSZLHIVGFXKVTUNKLKUSPZEHUUVIXHCLDXPE", "MPIXZS", "LATWMBSJKKN", "JTLLGOSTFKPIJTKQM", "SZHEPPTBMBQBTOOIAVQTIKPYQZSIODMJNJXF", "LPJYPMSEDOTPQARBVVOVKVNIFPQOQDXMEYO", "OXHEFZBCXWYBLHWBJZQOUXJVQQPHCXBLIOF", "XVIQKIAFXIATAYQTQNTIQQHBPOMWBPBFZESPFRW", "XGZHZOUZVOJSPOJSRLVKTRVPTNCRISBLEAW", "YHKWVTWNHQSNUSZRRLCNTLMRXPHFFZS", "CUNJKKMGLJIWSVPCWWHANASKTHXXFHFICNDAVCJUQRB", "DCWNTWPHUVANVVYCF", "EMCPFMEQTIQQAAYLLKLMZCNXFKAIEUCUZAZVBJHWGGNVTWQ", "LGDPDOHCBVSQNQTDIEIWWZGQFDJXWWHVHFJKEWUILNWMYDUKE", "NFBQS", "NLOXNSDDCLCMVAZXMSKOASQKGAUVLGDWFSTGUYEA", "DRCKHZCVBYOJUXSGMAZVQ", "PGGXARFQEKPDCMAYOPLXJMFLNASYEADNEWIAMTICKWQS", "QAVJVFXADQDDSRCMHDAWVMPVGVAIRWDHVMEV", "YITIPRDBBRZCHZMTDETKZQ", "PPOGELQOBQSPFRHXOCYJALEL", "NRZPNXXHGOTPA" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case34() {
    String[] funcs = { "BTWMSXALYGKHNF", "YDZRTZAFMALPOJZNLYYUIIRGHXACDH", "LEYBBVBWGLTOK", "HDEYZYNZWUQVYUDFOZQTAMNWNXAOESHUQHD", "LWQTDXGZJQBXEZDNSMQGCUMTRCVFECLTPYQDZSC", "LVIRWYALFEXLPETYLVNKSEEVUHBMCVGVMKPW", "OIKWSWUURTAUBYTAEHXFCLF", "YRISPHZRKBHXHBTM", "PX", "ZORWUWWFLHTKRLBLOZIJEGBRZZSKVHMITYOBRYQAOELDSOYZK", "IGOYOJAEBK", "WRCMQVJLNCZOPUHSBXOILLDEETJOFFFMIJOJDWO", "QFIQCDRIAVMLIBVRYMXSPPPQTMZOZDLKIVIXFXBEL", "AZHOCTHSFRVPKWDYSFSZTWQWIOMMFYIFM", "X", "RAHIROMQJWOQZLWVI", "OGOTKHYITMDTSVKEYFMOCCHGZLBMYBXAEXHPOTZXSJF", "GLBVGHZVDJXSMIGKND", "CMRVHKGEKGSCYAP", "QIMKMFYBXCDWLCLGQNN", "ZOFGKKMZROQEICRBTUDNLVVC", "GJPIIHMVMAZQGOETKAFMRUGSLJAATHIILIB", "YYDZTBFSSWYGBEHUBTEOSCKGVKTOGSLWJKSPXURIXHQL", "LFXHKF", "CSKWDDSLEZOZQNMVKPECWTLJ", "HSMJ" };
    String[] depends = { "15 15 4 15 21 12 18", "12 6", "13 4 23 20 6", "21 22 23 13 18", "18 7 12", "", "10 14 15", "", "12", "14 23 25", "17 25", "23", "21", "19 20 18", "", "16 16", "21", "25", "", "20", "24", "", "23", "25", "25", "" };
    assertArrayEquals(new String[] { "CMRVHKGEKGSCYAP", "GJPIIHMVMAZQGOETKAFMRUGSLJAATHIILIB", "HSMJ", "CSKWDDSLEZOZQNMVKPECWTLJ", "GLBVGHZVDJXSMIGKND", "IGOYOJAEBK", "LFXHKF", "LVIRWYALFEXLPETYLVNKSEEVUHBMCVGVMKPW", "OGOTKHYITMDTSVKEYFMOCCHGZLBMYBXAEXHPOTZXSJF", "QFIQCDRIAVMLIBVRYMXSPPPQTMZOZDLKIVIXFXBEL", "PX", "RAHIROMQJWOQZLWVI", "WRCMQVJLNCZOPUHSBXOILLDEETJOFFFMIJOJDWO", "X", "OIKWSWUURTAUBYTAEHXFCLF", "YDZRTZAFMALPOJZNLYYUIIRGHXACDH", "YRISPHZRKBHXHBTM", "LWQTDXGZJQBXEZDNSMQGCUMTRCVFECLTPYQDZSC", "BTWMSXALYGKHNF", "YYDZTBFSSWYGBEHUBTEOSCKGVKTOGSLWJKSPXURIXHQL", "ZOFGKKMZROQEICRBTUDNLVVC", "QIMKMFYBXCDWLCLGQNN", "AZHOCTHSFRVPKWDYSFSZTWQWIOMMFYIFM", "HDEYZYNZWUQVYUDFOZQTAMNWNXAOESHUQHD", "LEYBBVBWGLTOK", "ZORWUWWFLHTKRLBLOZIJEGBRZZSKVHMITYOBRYQAOELDSOYZK" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case35() {
    String[] funcs = { "B", "C", "A" };
    String[] depends = { "1", "", "1" };
    assertArrayEquals(new String[] { "C", "A", "B" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case36() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I" };
    String[] depends = { "", "", "1 3", "0", "3", "1", "5", "6", "7", "8" };
    assertArrayEquals(new String[] { "A", "E", "F", "G", "H", "I", "K", "C", "B", "D" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case37() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8" };
    assertArrayEquals(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case38() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I", "ER", "AA", "BB", "CE", "AE", "BA" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8", "", "1 2", "3 4", "", "1", "2" };
    assertArrayEquals(new String[] { "A", "AE", "B", "AA", "BA", "C", "CE", "D", "BB", "E", "ER", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case39() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I", "ER", "AA", "BB", "CE", "AE", "BA", "BAA" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8", "", "1 2", "3 4", "", "1", "2", "2" };
    assertArrayEquals(new String[] { "A", "AE", "B", "AA", "BA", "BAA", "C", "CE", "D", "BB", "E", "ER", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case40() {
    String[] funcs = { "AB", "AA" };
    String[] depends = { "", "" };
    assertArrayEquals(new String[] { "AA", "AB" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case41() {
    String[] funcs = { "B", "C", "A" };
    String[] depends = { "1", "", "1" };
    assertArrayEquals(new String[] { "C", "A", "B" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case42() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I" };
    String[] depends = { "", "", "1 3", "0", "3", "1", "5", "6", "7", "8" };
    assertArrayEquals(new String[] { "A", "E", "F", "G", "H", "I", "K", "C", "B", "D" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case43() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8" };
    assertArrayEquals(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case44() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I", "ER", "AA", "BB", "CE", "AE", "BA" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8", "", "1 2", "3 4", "", "1", "2" };
    assertArrayEquals(new String[] { "A", "AE", "B", "AA", "BA", "C", "CE", "D", "BB", "E", "ER", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case45() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I", "ER", "AA", "BB", "CE", "AE", "BA", "BAA" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8", "", "1 2", "3 4", "", "1", "2", "2" };
    assertArrayEquals(new String[] { "A", "AE", "B", "AA", "BA", "BAA", "C", "CE", "D", "BB", "E", "ER", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case46() {
    String[] funcs = { "AB", "AA" };
    String[] depends = { "", "" };
    assertArrayEquals(new String[] { "AA", "AB" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case47() {
    String[] funcs = { "B", "C", "A" };
    String[] depends = { "1", "", "1" };
    assertArrayEquals(new String[] { "C", "A", "B" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case48() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I" };
    String[] depends = { "", "", "1 3", "0", "3", "1", "5", "6", "7", "8" };
    assertArrayEquals(new String[] { "A", "E", "F", "G", "H", "I", "K", "C", "B", "D" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case49() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8" };
    assertArrayEquals(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case50() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I", "ER", "AA", "BB", "CE", "AE", "BA" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8", "", "1 2", "3 4", "", "1", "2" };
    assertArrayEquals(new String[] { "A", "AE", "B", "AA", "BA", "C", "CE", "D", "BB", "E", "ER", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case51() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I", "ER", "AA", "BB", "CE", "AE", "BA", "BAA" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8", "", "1 2", "3 4", "", "1", "2", "2" };
    assertArrayEquals(new String[] { "A", "AE", "B", "AA", "BA", "BAA", "C", "CE", "D", "BB", "E", "ER", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case52() {
    String[] funcs = { "AB", "AA" };
    String[] depends = { "", "" };
    assertArrayEquals(new String[] { "AA", "AB" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case53() {
    String[] funcs = { "B", "C", "A" };
    String[] depends = { "1", "", "1" };
    assertArrayEquals(new String[] { "C", "A", "B" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case54() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I" };
    String[] depends = { "", "", "1 3", "0", "3", "1", "5", "6", "7", "8" };
    assertArrayEquals(new String[] { "A", "E", "F", "G", "H", "I", "K", "C", "B", "D" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case55() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8" };
    assertArrayEquals(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case56() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I", "ER", "AA", "BB", "CE", "AE", "BA" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8", "", "1 2", "3 4", "", "1", "2" };
    assertArrayEquals(new String[] { "A", "AE", "B", "AA", "BA", "C", "CE", "D", "BB", "E", "ER", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case57() {
    String[] funcs = { "K", "A", "B", "C", "D", "E", "F", "G", "H", "I", "ER", "AA", "BB", "CE", "AE", "BA", "BAA" };
    String[] depends = { "", "", "1 1", "2", "3", "4", "5", "6", "7", "8", "", "1 2", "3 4", "", "1", "2", "2" };
    assertArrayEquals(new String[] { "A", "AE", "B", "AA", "BA", "BAA", "C", "CE", "D", "BB", "E", "ER", "F", "G", "H", "I", "K" }, functiondependency.scriptingOrder(funcs, depends));
  }

  @Test
  public void case58() {
    String[] funcs = { "AB", "AA" };
    String[] depends = { "", "" };
    assertArrayEquals(new String[] { "AA", "AB" }, functiondependency.scriptingOrder(funcs, depends));
  }

}
