package topc.test.easy;

import junit.framework.*;
import org.junit.Test;
import static org.junit.Assert.*;
import topc.easy.*;

public class WinterAndReindeersTest {
    WinterAndReindeers winterandreindeers = new WinterAndReindeers();

    @Test
    public void case1() {
        String[] allA = { "X" };
        String[] allB = { "X", "Y" };
        String[] allC = { "X" };
        assertEquals(1, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case2() {
        String[] allA = { "ABCXD" };
        String[] allB = { "BCDEF" };
        String[] allC = { "CD" };
        assertEquals(3, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case3() {
        String[] allA = { "WE", "LOVE" };
        String[] allB = { "WORKING", "FOR", "SANTA" };
        String[] allC = { "JK" };
        assertEquals(0, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case4() {
        String[] allA = { "ABCDE" };
        String[] allB = { "CDEAB" };
        String[] allC = { "B" };
        assertEquals(2, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case5() {
        String[] allA = { "A" };
        String[] allB = { "A" };
        String[] allC = { "A" };
        assertEquals(1, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case6() {
        String[] allA = { "A" };
        String[] allB = { "B" };
        String[] allC = { "C" };
        assertEquals(0, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case7() {
        String[] allA = { "A" };
        String[] allB = { "B" };
        String[] allC = { "B" };
        assertEquals(0, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case8() {
        String[] allA = { "BA" };
        String[] allB = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
        String[] allC = { "AA" };
        assertEquals(0, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case9() {
        String[] allA = { "GHUMEAYLNLFDXFIRCVSCXGGBWKFNQDUXWFNFOZVSRTKJPREPGG", "XRPNRVYSTMWCYSYYCQPEVIKEFFMZNIMKKASVWSRENZKYCXFXTL", "SGYPSFADPOOEFXZBCOEJUVPVABOYGPOEYLFPBNPLJVRVIPYAMY", "EHWQNQRQPMXUJJLOOVAOWUXWHMSNCBXCOKSFZKVATXDKNLYJYH", "FIXJSWNKKUFNUXXZRZBMNMGQOOKETLYHNKOAUGZQRCDDIUTEIO", "JWAYYZPVSCMPSAJLFVGUBFAAOVLZYLNTRKDCPWSRTESJWHDIZC", "OBZCNFWLQIJTVDWVXHRCBLDVGYLWGBUSBMBORXTLHCSMPXOHGM", "GNKEUFDXOTOGBGXPEYANFETCUKEPZSHKLJUGGGEKJDQZJENPEV", "QGXIEPJSRDZJAZUJLLCHHBFQMKIMWZOBIWYBXDUUNFSKSRSRTE", "KMQDCYZJEEUHMSRQCOZIJIPFIONEEDDPSZRNAVYMMTATBDZQSO", "EMUVNPPPSUACBAZUXMHECTHLEGRPUNKDMBPPWEQTGJOPARMOWZ", "DQYOXYTJBBHAWDYDCPRJBXPHOOHPKWQYUHRQZHNBNFUVQNQQLR", "ZJPXIOGVLIEXDZUZOSRKRUSVOJBRZMWZPOWKJILEFRAAMDIGPN", "PUUHGXPQNJWJMWAXXMNSNHHLQQRZUDLTFZOTCJTNZXUGLSDSMZ", "CNOCKVFAJFRMXOTHOWKBJZWUCWLJFRIMPMYHCHZRIWKBARXBGF", "CBCEYHJUGIXWTBVTREHBBCPXIFBXVFBCGKCFQCKCOTZGKUBMJR", "MBSZTSSHFROEFWSJRXJHGUZYUPZWWEIQURPIXIQFLDUUVEOOWQ", "CUDHNEFNJHAIMUCZFSKUIDUBURISWTBRECUYKABFCVKDZEZTOI", "DUKUHJZEFCZZZBFKQDPQZIKFOBUCDHTHXDJGKJELRLPAXAMCER", "OSWITDPTPCCLIFKELJYTIHRCQAYBNEFXNXVGZEDYYHNGYCDRUD", "MPHMECKOTRWOSPOFGHFOZQVLQFXWWKMFXDYYGMDCASZSGOVSOD", "KJGHCWMBMXRMHUYFYQGAJQKCKLZNAYXQKQOYZWMYUBZAZCPKHK", "TKYDZIVCUYPURFMBISGEKYRGZVXDHPOAMVAFYRARXSVKHTQDIH", "ERSIGBHZJZUJXMMYSPNARAEWKEGJCCVHHRJVBJTSQDJOOTGPKN", "FPFYCGFIEOWQRWWWPZSQMETOGEPSPXNVJIUPALYYNMKMNUVKLH", "SECDWRACGFMZKGIPDFODKJMJQWIQPUOQHIMVFVUZW" };
        String[] allB = { "YVIJGFULLKJDUHSJAFBTLKMFQRMYJFJNHHSSQCTYDTEAMDCJBP", "RHTNEGYIWXGCJWLGRSMEAEARWTVJSJBAOIOJLWHYPNVRUIHOSW", "KIFYGTYDHACWYHSGEWZMTGONZLTJHGAUHNIHREQGJFWKJSMTPJ", "HAEFQZAAULDRCHJCCDYRFVVRIVUYEEGFIVDRCYGURQDREDAKUB", "NFGUPROQYLOBCWQXKZMAUSJGMHCMHGDNMPHNQKAMHURKTRFFAC", "LVGRZKKLDACLLTEOJOMONXRQYJZGINRNNZWACXXAEDRWUDXZRF", "USEWJTBOXVYNFHKSTCENAUMNDDXFDMVZCAUTDCCKXAAYDZSXTT", "OBBGQNGVVPJGOJOGLMKXGBFCPYPCKQCHBDDZWRXBZMQRLXVOBT", "WHXGINFGFRCCLMZNMJUGWWBSQFCIHUBSJOLLMSQSGHMCPHELSO", "TFLBGSFNPCUZSRUPCHYNVZHCPQUGRIWNIQXDFJPWPXFBLKPNPE", "ELFJMTKUQPZOMWNLMBUPMKTLPTNDMPDSYDSGVFPENEMWBORIFS", "UQHCESKMKHSSMVNONWAFXWHGBIBABVQOPQFOVIUSSQFQWEHTXD", "ZUJTLNTXMRJXXWTLGGKYTBIOLYDNILQADOJSKKVFXAHHJMBOCL", "JARINTDWCLDVDXROPBYJZWYYOJUOTHWMLVRGLFZDZDBTUBXUOF", "FVNCRSWSAZNMOIJOIVVGOBQPNCKWVNHKEBMTDHVYGKJISUXHAT", "MUUDQBHMKNHFXAXQXKJLZZQTSJFAEEDFUUJKOLXJOQKDVFEPVL", "HVHRWTFDUKXFFJPSSWYXLIJJHEVRYXOZBAFPFMOWGRGONUATDQ", "LAHYGGYLJDDJHMLTEDZLODSRKEUTGTNKNTARJKPXINOVGZDTHU", "NWOOXVJJMPSVKNHKWJOPMMLEBKSUCVZQLYQNWCMBVBHRMLOWPJ", "BWYVWTGTOQNMICXAPZARKNNXTUUFARZROSDQWSMTCJGHECQUDO", "SRTJXYAAYKQRXYCRXUWJXNPQJNBKCPDMOKALXAPEMVBQLZSVXZ", "KUTAPPWGZPDPYZKZCVBNTCVFXSXPJAOXTFHVXXYTGOKRCXAETA", "UQGNDMPHWZYIAYABJRQGEPPXYJSTTYZUVLDVYBSUXKBMFZVRTN", "OVIDZNPGHOZVAFMSNSNQIVMVUBCWTFSRQTMKNEPBHOWEJAZHKW", "CMMTPIXXXLZQYSXTWWTAIDYAXYQLEPRXIBEXXYFVSDDYGTHCUY", "YFWPJSFYBGLGZMBINTATTNHODTONPYZWOTKGNGUPHPKXEATOWZ", "ABSDNVQHKFCMOFISFRFQGVPMVORPJFZSLZMPJJNEHRYKXJZUBU", "ACCLFKCYZOBGHTUOXRAJVPRECWGXXPSWCGMMVEDEWDMFNQWCUQ", "DSCILIQECIHLUILGMFCSWTWKKXLCBHQKVCSWJEBKRJLPGFGRAT", "ZBSGUVZIFNHYXWJSJAVWAUXPANNAMXJDVZUHNACZYHEPWZOLHU", "SLRKVWPNVGZMIIZWUDWDFZLKTBQDXGYYIUDSJVEZKMESBJLKYE", "RTAHNEXHUQMJICBMUSQDKLASOLWJXPTXXEUMZFWYUCPABQSEFF", "UNQPKFNNBECBBCJPDYJLIBITLLPLXELRDKEXDTQUVPTTEYHTLQ", "LBBBVOQOZKYNAYYRBAQMYJHZXNDSIYFSEXWBIOEWQVQRTCDLPQ", "MVJIFVGYMKGOTZJMNZQTMRPNDEVNMTHJITSSPAQNJRDOYJWPYA", "TMLEYQSVKPAMSVBMVXRLLIVFEDKJIGAVYXJVEQVRBACUIGAIPY", "HBBXIPBZNCWHRBLIRIZXOQPTQQWEAAFJEQIOZPYFAUUQMVHXKM", "NXMSYAMPTLZANOTLSLWUHTFQJRRWBWHMQHZKHDKCRFVBEIYIPV", "FVPZHYUJABTQWWTBKDOGKEMHIBYXRNXSXRZLETBQEXKRQOIERN", "APLQYJPQOUBVJSEBALWNKSVLOIDZFPIRWYCZTWZZVEWXOTAKUD", "KPEDUPKCZLHWUSKDNEVDCPLBKLPJMPFDCYQTRCVVVTRFFVPEKK", "QMCUPRYJAUTEUVCZVICTHRXSXCLPRGDLWXFAIGAYRUEICUFDIA", "MHTKBXOTDIRXXGVZQMEYROVFICHQNIVFJZAUQFDFTGMOPSRGPU", "GXTUHLCVSPIHAZRSSFSZWXBQMURWMXCDBHUMRGJQMVNKYRTNSJ", "VWZXSSQXNJOMUYJNJ" };
        String[] allC = { "UWRSYXWQY" };
        assertEquals(498, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case10() {
        String[] allA = { "SZPOKLWJDRLTBSCIEDPIWLAQIGESJSQHSJLRGLMWANRXRFNWAK", "ZTGJHXAUNFQJVXIOHNJQRJSHYMDOVWGEFHJESVHTIZIOJLJDPM", "OXBYUYOPQJKZTVJGKWXKEWPZHBJSUTHSYOEFJGWWYEOZLUHMGA", "BBSQRHCRTXMJVCAXXSUFAHYYAYZKHUHJRJSVOQHTYDWPBSZXSB", "ZIYRVGQMLUNWSCPIRZFCBTSEPLKGWFKHROUOYSRWMQOJAHYQMF", "EVSDCOMRYHGDMLXUKWYZCPRSKWGXULSUCKBSEPJEISZSGCEZWA", "PQRVLWIGROVJCDZXXPHQLSRZIHMGZRIOQRQETKZFBLDJIEMSFZ", "BHZFNWYWMXXGDPYLRAXGLMTBIYLBHCWHLSYOYHGMGOPPRZAXQM", "OMSYHGAGIUPJQBZXTHTOPOTMITNQWTOETONXWZGHUTIFKLGKLR", "NUWKMSYQCPUIVAHQATMSCKMAALKICSNXUCOVTYKRXAWZADJXWX", "QMNDHLDTTXSKNXTEZNJSQTFBCCFQMWHBVSSIIGVIJSUXIICAAH", "MKWYWTTJZPPKWLBMJAHTPUTIEBPBBMUEGYRHLTHXWGJPRWVHSH", "ZYAVQYECZTOZOABNANHRRBDDNDODXEUIOZIOIUOZXQTIHWAURO", "QRDQWCVLXZIPODIISPQNZOMCWVAPTGRGDFNYYTKWWQQTMIUUYV", "GAIHFSHCCXHUUYYHTGDGLFCIEBDUTOEUNFHDAXPHBSYWZTPWJN", "GJNCPXRJVBVCCEFKBEMGSDYMZMMKWDEHFKRUQBYVECMPESROMD", "XLLUBRYYESHQLZMREWQNKQITXGIIGQUSKWTCZNLTERXBLTZYDY", "ZVAHNKIXJWZZTDJPQSUOWKVFCCOCKVRJBFRJPCGDJDRWDNPOSR", "JGDRQRVQTVPPAZHLTJQVCCLPEZTSJPYNZFROTQPOXMWHHWEWNV", "CBVDKUZIFIFRTWQQEOJUEQBNSKWZEEWZKAOJURSQGSCZVHHUJZ", "UMIGOFHWBKKFLUWZKCTKAGXKSMFAUWINSJLSOJTRXHWMHLVBYP", "ECJEIWWSTNEUIQUBPGUGWGNMIKDWICKDILSNPDQSVMTERDFBLH", "WBAFBGARCSFIJYLBIIMOFGXEIRPBTYWQZAPKKCAFCOMVNTMDHZ", "XLEFPPYEBEOEQZNBHYCWMFYAQQIANNYHQOUIZVEAVGZJWOBLSG", "WNKVJLNIVQCWVZXTCTHYNMUXQKWWMTFISGGLGCOXPIPYTDBAMR", "YKBOKMWGSDDPQKRZYJCHZTMIEPAGWHROQKHWUDBCIHPQWAQZXU", "GKVAKVLAVKSWFZSDBVQIDHTBCDEYTMPPHKUHSXORPUFWHJRUTK", "SSLHLRXLYDXVKOSAGGMPBG" };
        String[] allB = { "ZVBAFAZJOHQSSWTORCKQAXSREHNRLYJIWTMHGLKOZFKMMXTYVO", "XHFKXOPVYBJZOXHZUBDNTOAMZOTTCJTUEGMPQKCDBBGCKJQTEB", "ICHZNPPRQISWBDHOYNCSAETLGBFVIOCFWXWDRNLFFBFHVYXZUK", "JWOCYHZQJZDHTBRRRLLKTCHFNCTPIRNAWONYDWWVUABUQCIMCN", "LHQODEMAKMUNMAXIOMKEYWCOFQBKDMZOIZGQIPZAYIXRYDWSOV", "HZTKGZSKWPTKQCEXRNNXSKYWNDQIZLZKLNISSAMQAZHLNDNVIL", "TKOIAFMEICGGUZXHRDJZZHERUSWAVNVSLONOASRUDRNLDKLDKF", "ZTAGIENATJZWXCLKKULNCAQPTONEQLNBTODDBMIVAZXZMCOJDH", "ISWKAXIAGTUTAFRSVPPHURAAAIXZTWDYRUUMQADJEPVVCVOIDW", "MTPBNMQUIOPIWPUWCZDAPDZGHAVVIYIROJNOLSOWRMVVJIQSWR", "ICMZSXAVDQAMNFHWFGEOHSKKEFUTXXIBHPULNLWXQWWZDGDJGE", "QWAPBHLPUDOEMNNTPOUAHGXJHZJBEPLTTRIABWUCRJMBVBOZVM", "XOBATKHQSQCHLHTBOFUIKWAFKCOWUUNTFHPKDEYHOKQUWQVWTT", "HHHUGJZMFEUINIPBNCIZOCKAADALLJREQTKHUDBLPRZLSRWXOC", "CSLUTWQZSQTIJVCWNPFLRLUKDIAOHQJHRAGLGRIYKLDKDFRDRX", "JSTCWRSXGYWFNHCBKPMESUPMTRVIPFBKTBWZFAHOEVNHXBRHHF", "OBGYWCVHKTDOXQTEKIWWURZBLMLDLFIBDVEMUNNLXUBYKVVRGK", "TRERPTISIZXHREVNXQUEZXKUGROOHRHUDIDGVHTJHYEZKYHPFX", "WGPRPSEACCXKWVIXVFHQFAWKFDJPYEEVDGGATFIEKIXEYRFCPX", "SCJKCFGQMYHJMJTIMDSPIZHWZIZCYUCEGLMMBGYGFVTQVZQATX", "LGIBYZZKIAJXMBHMKQLWHQNGHLVLZGPPXOOEOQXPPBPMBLXNKE", "OFMNIUMJCAFCUYVDCUETERQPJJWAKNKXTLZQFLJNWKXGKFYLNU", "KBIYSPLKHJUCFUWOHZVPHJBJYOVDLNBFRKVBEMWYTFJYNQMGZA", "GBKWEKKOUXDCYNKHTOSFYTLUCENTOILFULDVRXLONVKXZECXEP", "KMZZGXLUAHMJYECSLDJESDCPJIKVPAUDVKXGLLISAAMBOVJKDQ", "RKDORJFNYGHHHPTZIFAWFTZQGEMNH" };
        String[] allC = { "PQYICTM" };
        assertEquals(408, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case11() {
        String[] allA = { "PCVKCAODAKJACQAUZYOWDZSFQHKPLFBYZMNIMDLXMJYDAXYJNE", "CXSJJBHIQNVOCDENQMWILXXZOQFOTPIKPQUDMOMIKPPZHDHFQS", "GBXIISYZWNHXYFVYDFMPDWOMCIUDCNYNDGCNFJITPPMYMXIISN", "EBPYWSGQSXDJPLWZFMJOOPYYIFVKMWWPGPLJEAWPVAPIHOXUUF", "FBRWHPEVCOQRGRQWZHIBNORKHZMLBZFHXUNRKLIBVPSZZNOPFG", "AXZGFLTLSXBTUMILOCLTGCOZGTZIUFUZIMXEEKWNYSBICRFXDI", "OGCSEOZPSCRHJOTYCZCWMBAAOLSVUBPYLONMWAJGXZGYZAOVEN", "FVOCIKQJTXGVENKSPPWWPLHXTGYBVMAJEYFAXEGSEIJIKCMDUC", "LAAIOISSISIYPPNZDUBPTSAVESZSIPPQMOTJHKUDNVQZBKATNE", "FULGEXKTRMHDDAPSWPTFVOVUJIUWBMIBRUCTTMRVZNJRCHJWZW", "MOZECRZNJKFRVKRMRDWROAOCQPKTLMWXWTNUAMQELRWBGBIJIL", "NHIIULLTOVBEFLWLPBHYFFHBAVHFUAHLINDJDFPEKXGLIXLAXX", "TOLHGLVWXKYVULCYJEFLLOQZHLTMGTUJDCUUGNROTLOTCPBNYF", "HEJEGCMFPTQMVEGHMFBMVKLSQFUBVXCTEPVMLJOHZXXOOLNVLA", "YGUOKQDAUPTYVJAFZZKQTAXJLRBRUKKKIGJMXQRBAZLPDEVPEZ", "PBWSHVPCKLDQGIVLQPIRQVWQQUYXPIXQIREUQAMFFSVVNTGUXE", "SIDRNWWTQKDOZFPKDUULIFZDPOHCGUBKUREHRQBBXAJEFBFHKZ", "BPKAPBSZYSPDAAOXRAOJOTJUFSTURTJHUDPETSGRZUIGUSNWLY", "RVFNKKMSDBUHVHFQTDVTNLEWFQUUHTAINKEBBVZHTQBKDBMVHB", "SNJBTVJTQNBCHIWFUQLZSMXVFJTVQUITIVYHZPXCDJWIKFATCA", "NCHXSSJLUHLYOEBCGNSQFZXXWGLIUEJOBCFPVNYRRPKEGEQPVL", "HXEEOCMERJMZIUDTSQQOZVEJNRTIBVNJEPFQDSMVSTMMWWWQKN", "NRMQMJCCPAOWAZFEURGPBFRYEDQJRLTMYMHYSOICWUOHFEREBE", "ACAZUVJOXYIPMSGUFJIWLCFYWXTEYYQDHXWJHIUDGHYXYOXBSC", "EFTDRQELXFVCFBBJJYFSVKVSAPDSHAKGDVHCFMCEZTGJCMHXLH", "ASQKAUQLNFHGGTAGRNFFMNPINWLEXRQXISBFNHJZQVOXKUKYLZ", "CRUPMIBACPJZSNACLMNUQNBDIFZLUJQVNFJXXVKCZFKZZJQNAQ", "POHYGJSJTAKZRSOSYQHQUHKJCJYUGTEDOGFURKXIYQUFOTIAJM", "WHYILTHMOEVLWLRXPWPZHSVBFZVTVHWYCFZNMAOMAFSYVYRQPI", "ZTEUOXGTHFXSMXJRWPSURSGWTHHILGDHZFZAXADTKLHYHQZFDI", "MSRUEECXKQKRUDLMZGDTNHMIVNNKCLGARYGY" };
        String[] allB = { "DQDHLTRSTHIDZYQAZFNOVKTQCOTCHCOLINEIYTYMRJSCYOEIVD", "YHPHLJZHEZOHMIURCPBLVWAAJIQUGTAOQMEMJLHGOXPRURTYMK", "KTDBNOXWTTGEEQIMLHCZTCTYPHMEQDSUYVKKJOPLMZDCAKPJVO", "ZIMHXXQHDUIQEDLNGWGOOOUPNEDKSDGPMHHDAQBSQRFPDRSYKH", "BUTSNUWJPPGDEEBJGSDYFOECQQNLEMKIMIPECEHLBTMBWNKDXY", "MECLSSHVKMYWJXESHOIHMLGVXILJVWLLFPNJZYWCPAMEVWTYGF", "PHIFUBTTNWNPHDBYTWODCLRJPRSEQWRDWSVYNCGFRAZZAODGGX", "WWBTJQUJRMCDPOMJRYLEDHUFHWKHZKTNKYTGJPMMGVXJCNJGZU", "HWQQSLDZCSFOJSWRQCNBQYXAAGIBPVTXDONPEASHNROHUVOGLD", "XHSPRNGSOQDJFQTEXYRWIZZOEOWAQEZDLMWAFCOZVQCIEWGKEK", "FGRCYVZSAHPSZOBRIXWXKPICLQLJTKVNBIMPDKYEBCWLFKFFRL", "ZZMKVMHNLCIVWHWZTZRBXJCRTUVTXFKIDXHOAFYESYVIZVOZSQ", "ORQMQLESIXRNERZOOWRVWPMIBHHYFFUVKOUKDWJCVXQGLSCHJA", "GQUEHPNHKYCPMJTGLUDHRBEFJJFYTKXLBNVMDWSYXHGSCZHYJG", "DFGNWFPDTLKHPEKHJNCYLCQMSSYGHWDVAEQJKZMHIYDLXDJOHN", "SCGHBTUSWZUMSQOYKIIDFWFXYAAAYMOIVFHJLRWYAXAWGEURBR", "NBERAZSXTKAQUEHJFCEWCTBFJTPQDLJHEHJOBMARGUQWSOKLDZ", "SCSFACXFZXFJQOVERSCJZBKMZDNDOSIYHTYAVOXHTAPYEKTUAT", "PRWSKXZCZNFDIUEHUWYMTXDRNKLSMDUSKVUTKFIUBZYBLWMPAR", "MJDSPXYWXERFTZLKORIEBSUPCPXCJWKUVEERENLAITVYCICYZA", "LWUIUZTEYCTMUIFEFYGAIAIOIIEDBYWRGRTDXVDKOCSAEHFCIL", "QJOEVAJNJTTKNRSPRTKRLKJAPYMUZRPHZLCEPAYTFAVEOPSZRN", "KVNEHRJSTZFLVYAHORKTKMGYCOUIERTLPBJCSXQLGYGLMVLYQX", "IXIPVWOQLNKAEQMARVXUMKRNJCOKVFKTQJDCUGBIDVBXRNSAQW", "XTBFTQSNPAVYTODPJDPVYQXKSUVZWZTJRWOVTTLNKZNQDQIAUA", "PWKCZXRXOPENEUXFLGBDWJMHJGUZPEUDDFEIMOZYFRQMFOZISS", "CCRIFWQBHXYEHKTUSDGZXLAEYKEXQGQOEVJTFRAMUQGBDNRSMB", "XRVBTFGLOWFFCTUJTZQWZGGTLBHROPKWKBBWVNAKWVVDYCXCZO", "ZQIWORVPWKOQMQHCALYZVQNKCXEKJQZVUESWQKNZPYVYSDKHSO", "ICMHCZOHEFNASLXWXLLXLEWTZUWBSUVSENEIQWHNEZOJKXHORY", "ESUGDHTJCKQJDFGNRDOIZPYFMDLQLWQIODCWFYGKIVBUJFINZY", "HCEJCJOJONHGUSTQJFNECOLOCMFHPZXTGFPMUSCRLDURENNLQK", "WHHYIPQZEVBYKTBVTPWVTTGECAJYLQVUIZFSOAYXZILJZEGBLC", "ATMVEFQRZXWKTNDPBBZDRWLPHLGDYWDOFNZXQLXVKHDJYALHVV", "PAANGODNLXHLSXSHHTIFXICKOBIXBBDUZVNGQIAGGCXFGRJMAR", "WUPAYBNQGUDBEWKGWGTOCBLXJECCGQHBCZIBHQUFQQXVLLVMTZ", "HFMBEZPLHQAKBMMVAFQYXJYEXDSSWBJIOUYMHLZCLTJUDOBFUO", "IWUBGEIDPMVKHOZHKDUCOMLGLTLVEINNCAIKNSUGJQCCASDXDA", "ZCRTVLLKFVTEZAZZCSCTLEGENLLTVKZDQOWGOLJPDSYQNCSDJS", "DCXXYRGHRWPQINXMRIDXPDPQUNVKWXRYKXTLXYPPFMAJFHQYUD", "WTIGBJTMQMDLTCQZ" };
        String[] allC = { "GCAIWSWFY" };
        assertEquals(533, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case12() {
        String[] allA = {"CWWIARUHIIBUJOPGRQNPIUGKDQTESOJACQHNWDAGNVXESFRFIE", "FAABRADQEELKPKECVPSDWELPDJMMBPDUPZVTVJXYDKDNCUGGHO", "NUCWEGVFJZBDWKBEVKGDWUBTJVTOQOTHGGTDRDOLGJMFUBZZPN", "HJAQWOTZQBLHMRFZFGYKZMUCWWPDYJVCTVFAMCGLTMJTMRCJIV", "HSYTNWMQQJVMOHFYESQXDVRJGFVGYMHLWDXLOZMCQMVHTCEXAM", "EYKVIXDAQVSSDWWOEDKLQENAFBCFNHWRHDKJCSXOHDVRBNLBLS", "EENDUBKXAORTEJLRCMCVOVRSQRCOPNNPKUNKKCPOENVPKVYGUN", "PABOUJVIRELEHLGECTNAZVQPSOUUBCPYFIKGQTUFVQQEVCPCJP", "MJHPUACSIASPTSKQYHITAUZFABLPQLKUKAHMLIVZAPROTLQDIU", "OEEYKIQZAHFAVZZRFRZZEMIYZVOBXUOJORAWURHJOPPNNCTEHR", "ULPGKOZUYWMOBCDLBOFBJEJAZSRULVQTAMMEMHQPYIOWMNLQAE", "FZSIOTPXJWOCJEUMCJDQSZRRRUGIMNJBJALQLRCEZJFXCHWDDX", "ONZMNJVLRJXRXWKDUOOERCTEEQDVDLRWAMNKYXJSXPFDLZEHBG", "KVYPXFSMQHIBNGJTGRKPFERAYXDZNPGKSDFPDJOBICQFQMFSTQ", "HPFMCPMFDCDCCMODLQJQGWJOFNUQNPMHDVKZEBNLIGKJFSWCXW", "CUJWHEPDBSGTFFKBYKEUHNFZNGKPMVQTHEJJRBZHRCGGOEWVRX", "BWYSZBLQGPWJPLTJFRQCOCQXYLUTTLWHTZASNQEOYJBXKIQMAJ", "AGFHZZFBDVFUYURLVURNWRAMCADUNWUGTUESHXMGZVSRMCIFBV", "RASUCUVIVOWLZIVLIICZPUSSWAFKENWEMOCIMLMSLEBFIIARGF", "MUABIZMYQPTHDMZEIEGQCJTSJHQKMVWZEDALKJDVMZGRXOKCHG", "OALGUQCNQYROKQMJSZJWSDGCOFGLCQGDNDBYPQQIDCLZXSQBJW", "IPLOXDERKLGBXGOGNWYUNRNUMFOLBALEZROKNKJNWRWEBGELZB", "GIQDSCWTSBXXZKGHSKGEXLEVGXNYDQVTYJSLLQKEHTLIAUYICC", "QDMFIEJRQNRNAZCRFHPBJMRFBYQMHDABALHTIGPQMWFONTEPRC", "HDDWEQDOHSPJDGVLZMJBMWEOILEJRPKSBXEESTGPSMNMALPUSW", "IBUBAQVOTCAYTBTUZDTWSYSJRVRWGIXZHXWHIUHVQTKJPQZYYH", "HTXMJFMQLFWZJFQVBENLERLKYAWOLVBTYZGEWXCCHSWMWGHBBA", "NCUEJVMWGSFFVOWDLRYINXFIWFHTLDYTYGQKXRWDVRKCOYTXKC", "WEAGYDMHRPYQUIMWRBVEZZVVJPGIHCYFQZVADTDFYEMFQVYNBD", "LRQHVAPGYSGGXDORKVMVQEXPJFGVPIFYIDTTGGSDYJBVOLBMCG", "BRRVKUPTANLZOSCTFNYSZKLRNZRKUXYJPWWMINHPLXGXWULGXH", "LMSBZRQUAJUAXPDPSMWIWXXDVIPOUXTLKQWWOWRQEATQBMMILP", "OXBIPWWEGHTFIQJQKBNJHXDKUNEBQGRIZKEKGERQQLYYFESOYK", "MVAYQBNKSTMDEFRMTWKYLNONCHIGMTFBOURZHMFFFSRCBDZDFB", "EOSTFVSKREBTLJHZKRGHTSGBBDHLSICUTFMMJOUTFVEXDCZSCH", "YTBCRKLIWCXKGOQVUFYOGVFRNYMOPFWPNFUZEIHXYXANSPRGGW", "DYAFAWQGQBTDGFFCEGTPCYBQVRQUSQSYDYMVPEIBGXFFNOPFYM", "RMQHUCGOMDIUXEMXBZYSLVLITWUBNSPBMEWWHGPMPRKCYFDXKM", "TUHEVOIXRWLMXWGCNOYZMMYOVRTEPQTIBDVTHMPOAQYDDQRXNV", "KIYADVLOYEMCYCFCPYUWKZEBCJAEDSBVQQIJQLGJYCJPKPXFLC", "EONIYVQVURDIAQMSRTFGWTPEPUNUGEAJDGZSJEWSQRMJZSSBXJ", "VOTJVJQCFQPTBZGKETQKITTRHYUBKEWFEKRCIHHXJEIGUTWIGD", "BBDXRBWMBRMBVGAOWLVDJYDDYCTCOCKMGZVARPFOBGMHPAOJOI", "QPQTXTUCRORYSMGTXCFZLBJBIPFIMUNEZPQAQJASIXVWOQYJVX", "KHCQPQIABUBQQDOFEHHJTZYQKTDMKAPSPBMYKOYLPNZOIPZWDM", "KRBHDNTDKVPDELORQCJKQZZPINOQLUIBJGNQQLFEWIOAMGMRCE", "MOAXVUFYQYPCHHGFMIZRCKLYHBPJJZRRUGOFLUIOIVOVXMRAWZ", "SWPFNCNFYTMCFVWNRMFZGPZPOLT"};
        String[] allB = {"VNBMVWTHJSVHBXSEWQYCKWEXZPMIEXGRJXJMDWBQYUIPXARRBP", "HNZWKBCLGBVOCYUZUTZYPIROCYYUCCLQZCXTAWHXKHALPUKJRM", "GSXOCKDRAAUACXKPMRFLSPDLQKEWYQJFTFWAHGQOHKQNKTTIQF", "YRHDSGEUEIVKRNEZUMCIRZFQXOZFCUHCNSCQKCJBCHVRSPZOTK", "DBIDWWYGOWWQHNZFJQHFGIMWJGRJVQSPOOSLAQKXZEHZEGKWUT", "IYPZVVZTDURGODXVAAHGUIGPSGLHABNQBWTQMBDSMBFZTHYUMQ", "UOWLDNOVUCOIMMQSZMSRZQPMADDCVHINJJDFYWRWSDAGMVYQHT", "QWFYIAISTVHBZVROOVJFTEGSKJRJYNGLSSHITXZGFWAWLYZGKX", "YSPEKDARMEQDKXJFLKJWNWWFZINWTXSCJBPAWNHBSKILHSDUDS", "LMCRFIPQQBPBFGCQYXEJHGAHXWJMSKGAPLCJJLTQTROZAMUINY", "STPKLZLIVFHVSJTKZMNKABBALEIZTJPZHZTQHVNSJBJULUSJTY", "YNQGPYSVALZDFEDGAUFCHGKGXAPVWBNUHYMEAHSCSNSIIMBMTJ", "STPVRJUFSIKDVWYRIZUBLBBGWADBFZRWMOHSCFWYGAVZJAOXRD", "ILPOMOISJJSWFDYYNVLQRMHJCSZFRZPSFCCTAYVFICQBEBAZKL", "EEWJYNEZRXDMFQYWOHWHRGVTZCDVSFDVHPVSNLCWNNDAEFGENZ", "GLNXHOMKSIGNQHQGXATPXWLDSXUFANNEBAVSPETVUCZJMUTKXZ", "YBNIEHUESBLHLPXNPOYMJEEBHDJHTJQFJKHAWWTKGUWTZEFPXP", "BDRXFUTVBUUFJVGZPDFSCRZSWPQDBDZVNJDAKGVQXHGKASGYRK", "PCZGBHHEVOOKFPDEQKOHKTEVFNORJBEZAWPYZAUDWUXQLDJWJR", "IQAQSJRQJGOAXIUSXHARYEVOZNQGQBTEQMPPCIIDGZFVGQVZEE", "MWWAZSTQOCWVNTDNAQYBCFRMNZRSLRDEXUPSXUHACPTTDYFAQW", "CGPWVNKRVKCOFDGBBGPDOXJUUYYCKITFDRCLZMSHGHTLFSPJHC", "GFASDVWJGPLBQZJBBLLFHNHECBJSNTZZIOXAUWZKJZHZDFWDSV", "WYXGHQILWNCNKIJCAPBYQUXVEJECIZVVIZTCBDOQJHVEIGVEKK", "FKZNCNKYVOGUWPIIKTAJDJNTSGIECRPWINBUMVKTIZKXNRSDKQ", "BVAPLUDLBEGDRHPTKWPIGFRCDMGZJEIBTERRWDLCECZOTVIWLP", "FIBYANRAAHOAWOMXZORZGVKTIAZLZYNKMWBCRUJPDZQSGQLAOM", "TKVBHGFSEIEXVJVWWKASYMWIAMMKEMPNJQCAELFYYVPYMRGUJZ", "ATFSNHTNIWLWSDFWYIJFZSHTEPEJVTZNHVPFHATICQJESFYHNI", "DZHVMUGGAZMNUPBPKMSZDBNOFAJLJBROERTESEFXNIPPEWOXVK", "ZDNRLUZLWFHLMWUMCLZYSTOXJRSOQFWLUEHQFRNCFKPYSQLHLA", "NROCCWZLIKUMOYYOKHAOKILPEEMNQYGSFJNYUCTKFZBLTINMZB", "KJYLQWJIAMFKOFJJJJRJUUURRYCHYIVIFYAXLHWABBSWJDYSEJ", "WSWZSLXVYILCLPGQLAKDKNFAOYZQRQIVMEDBURFWKBKRDXWPWE", "FAUCLTZWSXZIMWDLHFECVIFLJZUSPROLQKNJXFMZMHBZFPQICS", "BRLPRBIRDVSLYHRSEHXZUENMSDPAKEEARMHLFFBPNSHTJSBIAV", "EXUURSPATTALNFBQZRONMFDWGPBEPEUHGBJBVNAXRHRVUWPTSB", "ZAKOKKPATUTBDJEVVJJOQRBMAQVJQKQWHAPAHWEXTJGXWTCKLK", "DAOXFQKAYCROESDTDLZTHUJQUPNRRKAKLCXGDCGTFOXKPJMRCI", "XNSDOLJZXHPPXLLZWWSMZTOLXGLQTLMCJVRQLOHVZXWAIPJWIV", "MNVQJBZKQFJJHWECXFCOESKFKADCHWQSQTXMUNCWIREGVULRWL", "ZWHIFHDNQUBWBWTCYXWUJMJQHBJMJYFVTBMVWHQZJQRFBFDXDX", "GMFKWMLPLKPRLTGXGIBTAFVDIRJMSSZGABDVXILMGQAQLXFIMF", "DZXXAYWMVYKPWXLZIONEMYRDBVOWPGWMOOQRLNTGRRTZHZLOLM", "CGVRUNCMAWFLYQRTBBOHDYMIGGAVYT"};
        String[] allC = {"LBRRBBLYGYEHEFIHVFEWLICDPQ"};
        assertEquals(616, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case13() {
        String[] allA = {"VUTBXUJQYYOKCJGBECATMJDVMAJKPVUNLGCBNWWVMLQTZZRBUO", "IWQQYPFIIYZUROCACWEPXEJXXFVJEGLKCTGAVRYGKJNHZQNXNT", "TIHVNIOGBJMVIVGGJZQXVDKGQYYGMJUXMVGRRPSMNRUICLCIPO", "MCSIJVJVDFEVWRHJMRCSURUCSDSKGXBOTWUXHBXVSVANDSEWRN", "FWNSZWGDUGNUQFBKOOQPOWBPUFJLHOBDWXADYSONQDGBNPZLER", "QOOVEIBTUAKBMUZAQVIOUHHDENOWZYXEZBQZQPGNHOBDUWBZBD", "FTZRAINJRUUCOCIGRAJYFAAZGAIGRNBCQJCWYVEFLCLGTEOSBN", "BFVUTGHCJEKKNLSCTWPOPABJPLIWZKBNDGPZBBXOMKCJDZLQUO", "DWMUWTIDGDPHKVEXBSZTRINTJAPPSXGTYKUQATMJCRVBSAMZLV", "ZTAWFOVJKFEOXKYKDAOBDCDSZGCOVKQSNHGCGBAIOSRKHERCHT", "QDNLYWPYVIQRFRGEMKOGQVQEHDRCVRKMAPQVDBURJAHMTTYQQQ", "AYGTWRXUNNUGTKYFGVSMSKSCINMQJLGCCFNFKGPHXBABRGLOUY", "QPRLRNQWTOTEIGEOKDFWFQCBYLQKBYXVOFGLFMJXBMTHZBOOXO", "BHXRBNBEWHGEHLCDIMXUFHCGEQFVDMJYJNOAQTCYRBZZCYRJBU", "SMDDVCMJOEKRLZVNGDHSFTCZZZLHOJLCEKTMECJJTANFDJJBAZ", "SVOPQHEOUDDJETHWMGWMVGPXUTVCCEPMNOQSGYLGJNDLBHAJWG", "VOHTWRVFYMYBQNXZGSFRRJDEXWKKSBDNMETGLMNKLUVNXDBLZD", "KYSMYZVLVNXKIYCZTMIVAACEVFUABUXWYMXIWTAWLCKMPATHUA", "ORSGAPJKLMFBIZMVBXYUVGMGCBUTUCZJUGOFGWKLEOUXCATYEW", "URSBVOBDGIQQIMILVPWTYTNBSDBZXDMBPVBDQXQKRFQNDQZSBX", "RCBWFBRWDQERIMXFBWPANFHDWHPQAFIPCFHVTHCRQRXRPFKCTI", "JGDKPQSKWWOIRIPGXYORHTICWGSOTNIGGIVZALJKQLXOSQZMYN", "MHEMHWPPVNWNWWHUZCQXMKHGFDJGBPOOHRMTAXRYKRZQXFCTCH", "JPXCQWNWCFZNZRGDKKOLEEJQDFPGFWVACGTXYQQIQQYDFDCVOF", "MAFZDNTOSDJKIDROLOIVODQISBZIMRYRKECDQZLYEMSSSQMIVP", "BYWESONNVULTKJJZTHQILBNTCVCZVJKUETXCKNHXRFZQSXPPPS", "EWXWNUEQOVZYHQFJXQMZVKWMOGPFOCENYWXGEACXRWEPIIQKXR", "PVRCFSNUSUWECJJLCXPMQFLAUCCEFEEHUQTJQWZPHIWOSEWPTC", "DQTMFXOBKHXGKZHTIQTXGIOSGEEQDBCZPDDBATTYUVIDXJODXV", "IPPWESKZAWJZFJHHFSCDROMEHNCPBPMIVEZZHKLQXAPLWUMKPM", "YCKNBUZGGFKOQREZGCTQIQOFQFQTS"};
        String[] allB = {"SFWUQBYSRTFWPOYQEDIUMVEFMNSGXCZRDUUNAQXKFXINHSOUIK", "QWHZBUKAUPZUJROOLAULKABPORPSDTYPAVKHVWNVEMHMCZBADV", "OPEMTLPSHWWUYQHQVAXXEQWUOUOXVYPPKQACGBPLSNPXJGSQKD", "PPXZZYORYLRSPVYOENVPXNUHKCZYFDUMMMZYRMYTKYXFODMSSQ", "GFWMUQDSWILNJNIRUDOGVSALZLRVOQLDTDYJTHYUISKVCYTZYW", "LWBZPGVUNXNVPJANTJJAWJBXPUHBQWUXDKKFSUVRTGJTPPHCSW", "IILCJTMAFRROUROWZSYSGCRWTSWNNBNTRFMBNWGSCJXXFPMTBO", "YUPRARCJPDCDPLFTIQRZMNUVESXXKSEGKSEFXMUOPWRKVESZEY", "CQWXLLNNBFNONUSHMVDMPLYKYISJHHVSZHJPFSWWBOLZUMMWRH", "YLYJLBUWXYWXYQSJBCXQNSBUJWVERQNVIZAKOZDKSCFYKPVYLK", "UFCEJDBNIJJYCJNPPSAVNSEAEYRQQNBUCWXGLPXXRUUQETPXOE", "BJNRZODFAFPCSXAXLUOPBZETSUCQZZFFSKDOKROSZVJZTRQGTL", "ZAPBVOSPELNNQXARGFXVUQJOYRVEUQNNAMEEXBAEBCISVMMHZT", "TLDFUROUJREGCEYRAGQQBRSDANMNHIGBXYGLMFVGLXOLYMFLMK", "NANRZPZUVEJIEWSBEKBUZEWNOSZAJZXXNEVPUIKXFVFTCYPGZY", "IFWJENZSBDOYBVQAURPWEUSEHRPMSZBXBRQOAAXWKLOUWFMSZM", "GERSZCHAOEEBCVYATGAJTNTRUJKUIXZVWRTZLNQPZAGHSBJWZC", "FGASMUOHHOHSDYUYZPYLVPRNFEQMTLTFAEGZIEHOWKJSCUEVZN", "WRCNUHKMQLFYBGHLXWMEIHVPHBAOZASEHCZXMIEMCAQPOILYOD", "KMNTFZPNYEFBPUPSFANJAHRJPSHXUPMTEFOYMGPGUOUKJVDPUI", "HIJDTTCOUHPTXJQSXOORDUUJIDXYMEDEWDMMADBRRMYZUFWBEC", "GFVLXETWAXIDIBGVHRGUZMDFMPVTPBDOHVLZMIOVRIWKBHBYBV", "EBYERLKQQBASQGXNVFHBXYETAERLHHFHETDLVCDZFKPFKHWGRK", "IBXGWLOHBLNQCVOVTGIYYTKLPHNPHBWYOSTMWHSJRQPRXNTMLQ", "YLKMNJGCRBIOYHDOBNXPWDBPBHLNNPEGBEOIIVALOFWWTGAJHR", "GPFDGQBURVYYKUJNUGJAFDUTWPLPEFBRKRZEEUTLFBCVCOWWDZ", "TVHZZAXWUYAQBRSZRCYAWWSXHGEJMMUNOLBVBICIOEHEOXMIWV", "PILVOVGSLWOPGBVTVVPDUDLFMUMSDNGISTGJOJUBPMGYMWJLCO", "BGWXWTCHYOBSJNCHOGOARHVXTATCJFPNGSENBVDAYHDBDECJJI", "TPILYPIUUEWRGOBYXJKLULFFPDCIPYPMCRJKGIREZNUQRQCIBN", "BKEGXHALLBBEEMPAWCXUQGLFKXWYXUALAYYIUCJVGVVKYSXGBN", "MNGYJVVWTABKTYBJRKXMCWAFULLLUOYCNHOFISJNNNXWNUUKKH", "GVWLLYJPVHMNZDHEYSPKJSFIDTKOXZECWNVDIUPSFZKIXEVKJG", "VRBQVJQZYHYGUHJJGUXHZYPLWIIRESTLDULAKYQQUQGQCCSLRC", "GSQHVDEHNJLJKWOMIPKSJEQXFWHILZBOYFORVESPPHLUEJHKGO", "TYZUDUNGHUUELFXMGEZQDNGRTNPKGGIWPZYOKLMAEKFXPQQXMY", "NTPIOTQCVGYSUYOUSEYSAQNRYWNTTRYDLUZYFHUKIHCYHDZJJD", "YVTOXLATEOBSBRYMVTNGUIWRJMHUYSHKRCXJABNLKDIKAYVRKA", "LJFKWOWYCNEOVTCHRKVGEEWQIEBOSHTVFEKXQHSQCUEOHWPUDV", "UKJAVFEPISIIFKKNAKNHUIFJUUZSFCFMASBBSMTHYHLOXNWUEE", "OSIUUPSZLXKYFRLLOMGVPSNEVMIDMRPBHEPWGDMEZXCDPTWOKI", "IOXHOPMTRBQBPDIQHOHVETJEDBJPAHGZTEZSBCVLGNEFHPWIWU", "INNFVPLGXTUQWPMYQXCACIICDPRELAZHPXAXUHTNLXBYLUNBGJ", "AGGZYRFXDTUBZQCQVHSIKBRVVULNNLPYQKXUVERKQALNYVZZFV", "ZYFYUAZWRIOQVQWLYTEWACBADOMHGNKQGLAVIUJFVZMJRCUIVD", "UHQTEZGBAZRFWFHEITDNRUZVLLHYNRMOGEZEVKMCWPNGFJSACI", "JICHTXRPRXZNXIOSBRBWDJDOKNXFTXZLMMVVNTDZQFPVIYRXGN", "CVODQMXFVHZVIZOPVRWXETIUKPSZRSWAJGHZOGRNNTIGGCHNJH", "ASNTXPRODMSENWOPFREVCFWMZZWNCZFKEYQJTWNRPSFNWEPPHZ", "LZEXPZAKCRFJZAYVIP"};
        String[] allC = {"IBPAZIVNRQORXEKVOXIEYVLGAZIABPMVYNEHJFKDGCLNYYVM"};
        assertEquals(298, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case14() {
        String[] allA = { "GOLOMIRQJJZJHZIKPPSYURTDINRLQVTLCMWMSFGOPGMINKIWHN", "QODMLBNZPCGVUNQMRYDTLZDVIACDSNMINQPBCPEBXUGBLHDFSJ", "WURJTANGFUFUOEBHEETEUDDIZXYTMZDYKLJYQGDEDNHIAVQBQD", "FQWEPNCXCYZHPONWERXLRPSOMAFCJYKBKPWUXRPRAIOVCWTMVG", "TGCMGRKHRPFDHUQGGFLONBTGOKDMHPZIYNVCIKDVVUOTXJRAHJ", "YJVRMZOOQDAGJCSEXMPJTLVFMUXJJXCKNIXFEIPBNYSEDYHHHR", "YCQXEYXKOYXAGWNILYGIYJHISEDOLMIEBWAPQVSCUIKTGVYZHM", "BPHPCOLPKKUCZVEJLGEMBMIAQEITGDHQYWYJONFHSWFPNVTFZB", "VCALBCVASBIKJTNNACIWPVFPHQOCGIJFXDOATZYJZJEYFOYEUD", "XZDPMTFHKKNQEZFTIORTTFSKWIFWPWAAFXMMQJHFMIMAKBSSUO", "NDSADNFTNDFSTBWDFWTBBAULFFDBNCUMAJCVPXVPOCBVSUYEGO", "MJWYOCAVMFYHHVNNGOZVJLDKJCHTZXQMQOHYNQAFTUNHJFKLBK", "XNJJTNPDPLWHGTUJRCFFOVYFFKMZCDOBKMHXUQVUBPYJMNIEXR", "WVTREVHHWNXSWKBDUUFLAOLTTUGFHRJTDOPVZDZCEEKSIIWSQZ", "IMLLWGTTAPHNRVNTGNRJQMVLWOBUVGHCWSRGCUIKQKEEWFWGLD", "PPVYTNEVABZLQSEVRUABLOGGLPHJMPRVRQOOMZILXZZRKPOMQA", "RJSOEVUTQGLIRYAAWGUVOGCDOGJFVRLVHQHRMBFTGVXSXEUOIJ", "SQXNFVSNJPXHHPRUWYEOPYVCJLNEHHQGYXQXLWOIKCZGBZZCZN", "KFWNWGGYBZMCFBSRCKYOBYEVSSDVMQLLMEIZQFQHXJXMIBLDFP", "CCJYMXOFNXZPVQGYUAHUBZRCSCBWIEUIORFKFOYFDCIMGZJZML", "ONUPVFOVCURTSFFOZGLOHNEREHWECCPTOVPSFHFFOBCVTQRIWU", "WKRKTPIWPMSHRXSFWRBUVDUNVDXVYTFOKQQKGPKMSSVQKUMPOD", "GNZGPSHTHMLUWMGBPKRBZCTXLUDVYCRPZMAPIVXEWBCIPANSCE", "GLIUUQVBUJRIYVFDKXDWKPVWNUHTRWVESQRTWLSIFFKAPACKJH", "CIFXCRUVSZYYCUGWJFZPAPVEZIWLIJVYSYILPJIYIYQCQMXCYC", "YKWJROHFURKOOEKIBWAYEGBOMBBMMZNEJPNULELOFVJAQMIOEH", "DYWIAZCBEHQYPHWIJSHDRWRWCDTGZMHMSPILMBQTOZUSGFWIDX", "TSEOLRXGDOWMRYRTQHFONLKZHFLAXWOLXCVMJJCCSVLBRFQHDD", "NYMUYUEOWDPEQLAIEJNNTNMOGTEQPEMEIQFXKGJTOEPFOVTBMX", "OLAPGQWRSNPIHLKGOYUXIUWULRHQYDPTECBSFQDJJPXKIHLOJK", "OOVIMIHZJMTXOZUXLYBGXYUPQUBLBCSNCOFMNIMZCAOIMEAXR" };
        String[] allB = { "QECCKYTSKUAKGFGXLDTISBCTKGNTHCZYHRCXOUEXIUQEUYRCUD", "QHYYZROMPYMDZUBGVQIAEGSYSJKZLMBRLPYZNLOSLRQHMMJVRW", "JSLMOAQVNOTVMVAXDYLCBKWHPLUFNPUEZOGAJUKQHHARJOWRPX", "LWPOQTOBQXPAOFDMTXHVBBVXNNGDHKKSQNTBOKVDUCNMENPQKX", "DLKDPXWWLDUVYTMAMFEWFYHNZQMMQUBUCCXNQXSFSFECFJGCEK", "VFLCCZWAXSTHPRCXKXYNJDPEKJVBOJDJLDEZAWSDZVBUIBJWQH", "OGACFPRVCCZIHLLGRSKBADNNXNPQBGLCSGDKQJTHGEYYGOOSYZ", "YHTQGVDYEIAJQJJFXGXZXXVAFZPEIEWAZLNHJKKCCWTFNVBCXF", "DFZOKONEBCWLRQHXOQJPABYOGPKMTDLVXRVLJSUPQIUEFBURED", "XUZRNSYVQWVWNDWJODYXPBRWTVPMXCVDGSNNEANNQRNQYQISVC", "LPOHQODESTJFUKEJGJEFSCOZVNUIEXPIISATFNPIXOJBTSIYAX", "YYJUEYHSGLFIPIPYCGWFASXWKQNAHSJCOHXNVSVFXSLPFTYQVP", "DGNVCRMTWRMFTODJAQBRFIAAVYFMIBCODWBTUATJNDYUZIGDLJ", "PJKOGMZEWLZVVZIZETANVIUYMPTICTWDUPIVSHVKAHCIXUJSHE", "YAVYRSPLMKSQGBLOPLTFGJIZZIISDAIQNYDMDNPLFHBEFMRBBL", "QWCWTLLKORCOPYILTFKLZJOTYOZIMGYSNBMGKRHXGLUYRYEJDJ", "JOVCNHLVMKRBKPRJYOSSPXZAPYRMERQROSMTJHBNMNYRFABYFN", "FNCYWXZHJNMFMAEVMEFBABFLIZEDKDZMSDOYGKJJDXVTOUHHXG", "TMSILKZFZWDBQRNEHHBPQKQEXOWYRVHLSUQSPZGGZVJSEYIKIK", "ZOQHZYUZZVDSHKGRZVJAMJPLHZXBUXXWLUELAUKOATGONWVWLM", "VPDMJWNNUZSPQRPIYQWRTTSNMDZNDHWGPRGOZKQWYBNAJFGRCV", "TMBYGSAGXEYEDGRXTMPBJBTDUESRRFONTVOLLCGNWMOYEDHOVG", "NOBRGTLDCRDEUHCSUMYKHYYHHBYJBQWVWENKRXABRFZZRNPUXZ", "TAVYPPUKVGDFBWMNGMKGAZEKPVVWGACZVJPDNAXBPZURPRCJVS", "PTBKJMCNVASAJVPWWTZUYSRXAWDPWMDZWPALZSYPYDTXWEOXGN", "LXROQMTHQGDEXURDAWQOLNOISGXGFJIZQJIXIVXKFLPKNHPWQV", "AUKZHJOLOVDOSQEKHKTTAXNTZZITQRDXRJYHDWIXBIHLFYMUKH", "OIQKWQDTFJZLPVYZRFQKLPKSQRRFPVIANDFSHTSAZJRRHEHSRE", "SFCZWAZWOKCDCIBNYBNWYDHISLJSXTVXNZKCPQKTYTMMCPRCCL", "TSSIKMUTRTRCGDYLTQDSSXXASFPRORXFUAMLJMGXSDHLYYJFQU", "IIMKVGJTNEJKYOPOCVGUFILAPZKNYMVXYCHPANHLMLKWHUTLYY", "EXLFDSFFUERUSDBNEFNZTRQPSOEXSUEXHGRYFDPXCWAVLXTODO", "WNIXGWRAXQBRLCXHVDTTKTMGNOUJSCPVRWLWAGEXBHBZKDFNZS", "LYVRAQYZKIYIAWCMDRLUBZMKLLDFITZUYHGFTRMOMXUSZATFXK", "PAFHZDVXVOOEVUCBWLNZTKVZCGKMIJOOHMZICNDFUDZGRVOFNX", "JBOOJIEGEWBACGBPALOPTOOKENLAZJTTYKWIPEMFSLYOQYRLTM", "VPHLZVRWFACNAJSWRQQJYIBDLTQVSOIVXLYBXBRWWGQACLXCXG", "TTQZSRXTTATFWBFNMHCCFHSTXNTOHVFQVGCEVGYEFJKNQFYWMR", "JUQEGWQJAPUTSJNBZMXYOSJTEQXWEVVTSHBQDVVWFI" };
        String[] allC = { "DJSMWTBVYAZUWRFUAKCYWEWYXJKMDU" };
        assertEquals(363, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case15() {
        String[] allA = {"IGLAXQXINVZGRRRIUQJOLWMBWOXQNTZQMOCQTKMIBHPWZABILY", "WKEYTDMBDRJPMRVQLBXZTVLUKAMYLDZGDDIUJSTQLVUVKZYIDS", "APBXYGNXBVMQMGBREOICKYBOWQXRWWBSHEMCISGXRJWDRENVQO", "TVQLDDPDOMMATYLOEJQYXPEWDFHQRZTXVWVIBMNWCIMSPXAXTZ", "GYQWGYDPJKXSBTOEFHCAJWPHFPZHDCMSYMGKDWFAZVUEROAFHE", "PDGXREYVMRHLPFEUUCUMUZXFALMJJHOIBQHZGVBJANYCWBHWYU", "DSKHZTZZGQULFTVQYUJBHAZWBBQHDGOFWYRXVEWJYBBRKKSKBI", "XNGYUIISYQCHWPQSHLBWHXHGOSBZZFLVCETXCQTHIQBZNTBKBO", "BNFLHMEKCJVDPFITTSFVDEYPTZQSOUXQZUOPABMJHMTTKKRHSQ", "FVEWFQSADRKFLMZOCEGFYBAEVPYFYZINXBOHXXBEWVRRCQGFWX", "QNAEDHTCFUXRCWRDJPEDJXRVAURYPEGTIJQBWXLOBPEYJLDAKQ", "IHAOFGGWOYXLMNARJDNXAUYSYSISDEKESOBKGOALRLQSRRFDCF", "UWJFWFLLIRMETRVJFFGKSTVJKFJZIFYDLIMLBCIKXUQHSDHZKU", "URCQQUKQEUDYWKQEJHRBTMDHNOYQSXEVPMZWAINLTQUPQTOMOL", "CBWLHOBSZMWHMCLEKITSIRAGUGQBQCOGFIYFSWWXYAGGNFEGVQ", "YGTQKZGEVDTSDMZMTTJBZWRCWLGOMNBPGGJHJIBPUTJCPERRAB", "YSBXJSALOJJYNOZKLZNSIBBISWPZHTTUDSVYNIEZTYHLBDHLPW", "VLHUSUZDYYTOMLSLDYHEQCTUYREIALUGDACGKLBRWWMEKLXVDI", "QIRHPDOAZKDZQFWVAXVEKXZHTRRJYVWVRIIRMDJIIFCHLBUFWO", "DMTIQIPDFUKECYQNEGMGBIUYZGOTVIHFDYNMDRRXBBMYRFDZLV", "OOTREVTPJVONLXXFAVGXBPAENMMUTSNUTDANAZRRKXVDYBDJNY", "LEBERERQRMKAWXRREPWMZHDCAQCNIIZKJLMPQGZUXNQXZFLPHN", "ZKTGNAUABJUTGVRZRBHFPKOSLPNPIAMEODATJTUIFJUILCFGAB", "OQICMUKIYFUUTGGJMCFJXQEVWCIRNNZDZMZQEJVYAIVYSIOTHW", "IPFJEGEECKPSRCPCIWKVTHBWGEXHUNRMPNCKPKJTGJUGWHWNGW", "VRBWAQSOTNWYPRYTG"};
        String[] allB = {"OSDFAWSSVGOIONDDTEBSIKIHELHWGQSNWODEZXBVGBWHJKFUWQ", "QRBZWXFMIIANWUPMELFEWYAAPMDIYPJPXFSZRLYPHHQAHEEUOD", "UVJSSSJTDXEQFIIKECJTYDOTAIRYQWZQVCHFXVVIAQZXLYTSKP", "BOITZVNLSLPLTMEHKFJHDGNUDXMKWIUDAPFLPVVQLNCWKZYUBX", "RQOGRNIYNUGRHQYUKFSRMQJSWXHFUJLBJZGGRERIJXLVTNRJCU", "JUNJOICPUXAMBZWOCEBOKMAKPISBNUYFWSHNLKHBESHTGHUFML", "IJNIJBOTPQIKNNMIIDIDASGYZUQUQXOFNTOTUQUOVPPPZLLBQY", "PDOYKJHOMRVLYAPVNHBYBDYRUXHJASGXMKJXKNBQXYHDUFRKMY", "PKBLAMANARHLQDZBSSRZMTFXNNJYEHBJPNMMMWRWXWTOFQYIDW", "CUNTTMXGGRHPQORJBQEEOARRONNEZVUUDMNLTMSGDBFMJHZMAU", "XNFNDXDUOMFIOARXNRVRUBFUPMRJIAQNPYCJUOEJOBUOSJQBRY", "NJMBASLKWDAUWXYGKGXGJMNFMOQHOJCLKFTNKIKNAIWPWKNDTY", "KTAZGNJOGLZJQAESAUVRZXTRRUEGFVQNQDDCMIVCVOBPQYKASC", "BVPXRDISXSABJDHIOUCEGQBOYMSZDNJGFIVQKBKBEQMARCFLHK", "IMOVFABMNELEMVHUGSCUYRTKECKSDJDDLDUADCCUOIAPJFIENR", "SXFKRBKYYCSHYXUXTEHDUJGBWYHTRSAEQITOQXLXUNUJESSJDY", "XQMKMQPHKVWOKLKDXAYJSPDHCOPHAXRXTNCPMIORROPJGKSKIL", "FLQNVUWAHYOYZAYDIGNJEJJPIPZRASLRJZSWBDRSQNDLTWBRRL", "ILDHGARROXYAJLIULENSXVQLJUNIIVAOGVWFHISYWAGMZYYAUR", "ITDRXNHCYWIWPFCPFXSDHTATMEUOKGTQWUOVMRFJCWBTVQJNGY", "IKNEHRAMLOCWZYEYVFNXOUYHREWGQVDALKCMPXRHHGNGPWFGHM", "PZVQFLDTUWUSMPGBKOHHBNKBCRARPSSPHBNVBCCFZMOYTCECDG", "ZZPGDYDTDXNGDERCNSVRAXDIIEFOWKFYHZOPTXSWDYZIVGPLNU", "AGWEOPLVUZFJYZEZHVRJCDBRUJXCMQUDXSWBOLUGTXZGGRRBPG", "QRWWNVCCCCZVDALZGYTWEVLDBESLOZMQWFIJGYJTPPGBXCINFX", "SFYQWTZJCFQJBVCBJTSDJOPFOKRRLJBRXIHNSLOIXXJLWLAQDO", "SZMRJDNSQEAFGZFLIKPDSHIGCWGCNRUJWOULWGLWTEPZUPVFLF", "DQGDJCTNVCBRUQRNXOGCWIZLQCEIBCTHPLHTMZZTEVHZXTOGOG", "KQSUBPZMMXLXLFLYTBAPXCULKTVRNMXSRRLFTNIJLUQISIPLDQ", "ORGGNWVLQSHGYZKXYNECNCPEQRXEDMDTEUPWUIFORPAGVNIMFD", "FFMXHUCLZNXOSITWUPLLMFMYXRMOYOTPTUAFOEIWRQPLKZNZUB", "NYHGSPGEHABDHLVTPWXUXYCGZDEJAXFBKEIEIZQFURYLLSSCIC", "LNJSTARXZLCNMMBUUECOCPRXMYHWXPAWUWGUERBYYWFWBUPATK", "YWRBSUVKRKMCPKTKSIYNCCMPVTBIDAMDRWWLGEEJZSGTXTCXGT", "KIIJVIIFRVSVEEQKVWPRMJSUDODJUSOEXDICKJCHFHUNPLRODU", "BZKMJLUNZMJGBNWBJFXDOAGPAQQNVHBMOVZAEZFRYJMFEKCUEE", "HHOVMIJBDZCQOHAMBCGSCZAEUUVOMVYDIFWHAKVGNJUBSNPGZJ", "RBDMIZUFRNOFTJRQYKALRWSZFCRZNFJQFGZMCLNNJNZCSXPPCG", "HKLRFUPTFNPECDOXKLSFPFUQJWCPEWUGKYRDJJOSECNLOMLBII", "AMVHLXGUBXTWOMQQOTDBOEFFDQAGKWVQAAGBGYXFUPEIXESNWR", "ICEAQKBHHKMFUIVNLWIZRCZYGANNQNAEQEUAKABVCENMBWRJXA", "LUIMMGRKMJFSMQIZFWHOJZSXEBCJZKHLJFEHPRGZWRXTPDNDWV", "NQRBHENVLGQWGFUNOHTIUEZPHZBGOIBVDEVREZUAHPOLVRCZWD", "EWOEVNZKMHRIOYEGWHIZCKYXHVDOHKDGXJDCQCGNWQCJYZMRCQ", "MVMKTORSAUZAGYVPPUAQNXTVBPMNDNWLSNKPMMOOPFCLASWLFK", "NZWSKJMKUHMIFIQUFHEKTXPNXIKNEHDNAOKZPBWCTRBXXDIHFY", "KYYTVKWHJFHVWYPDZMXFVNNVXVAAUSKSZUXDUIECGNZZQPTQOQ", "SVYSYDRMZIHLS"};
        String[] allC = {"NGGYGDTSEVWBOQJXQTOXKHUMXOMRVZPJKETDATZNPFIEBPDTQF", "AKEGVNRPAEHLNXMUYSDKGQWWMWWVDJKBNRTQAVHDAJRHIWZWXZ", "ABANZLRQHLQKYSMROYKKBHGOQZSSFNJMPYZDGWLG"};
        assertEquals(0, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case16() {
        String[] allA = {"UORTKVUNHVNKFIVVXXABLMNBLWDOOUGMCCOCBKIMSCAZGHZVWH", "WBITZRDJOHODYBQYOVQAJLITBITVQTPNCMKVZSKKKBKFWXXQRG", "QCFHKNXFOQJLWARAPBFZELJDARZRLATLXZJVSGHKJMLRXOSGVJ", "PIPYSXVAKAIEJUHCGXWTODJLGQCJRVIHKPNWAUZCWFTKMFESDU", "HCFJSRTCQIJHOHITLPPLFXHQSZFOSOFZSHCSGUVAKGSLUIIXBX", "FYICUPYCXFYXFAZGSODENDAQAUHLWSUSVCOZRVVXUELKCDLMBM", "TOEJXZWCJXUIJPSFBAXZAKOPTPAHCUUXWFQFXSLPXBFJKJIMHH", "QDBGAXHOSJGXZTETGYCGBCJMUDPMFXSVDAQBGVDBDIXIRMSYIB", "OKGWJDDMMGKTBPRRXPDOTRSLHUTJRXTERNPKXFWCBRXZADSECI", "OMTJOYQZBYDQFDLZIPVRMPUEBNHPFQSNCLNPWVUTWJPBHHEYSP", "VPBFXQJCMJKUUXEOSDNTISCYZKENFYVCSTUIFTQHXCKSOOESOR", "EJGDEOTKPTSQVPIAWFEFLVUKNOJKDRYUUHTOEMLMLAGDKTUCGP", "EEKQBTQVXBYSVKDGGLFYDYGNCRCSHBPLPFMMMQWHEGCGHPGFJD", "MOQSJQZMWPLKJLVSBAZAUAMUFGYUSOWZXSGYJIAYPFUTNHETHJ", "HHRQDZRUKGYIIFSXSJJGBESYEUZSQNNLWPPWSVUGXZZOARINBI", "TCLUXBTQOTTZUDJDDYBCQBCTKQYKTUNVVFVKPPIMYCMXFAPZVB", "RISYQKIRXEUVSSHYZLJUZKQGHJNIDLUKDCFIXWTILNGEWDNRUS", "ILBKDWCJASIDYVLFTXOLOTKJSSFLUCOXNKIATKPVUJKWMPCLFY", "TLEIWTBOGAWQNQOGLTJZAVIHIVDPVSRRMOGOPWAYTSSAFKUEQD", "JSZRULNSNJHRNKFQBERGGLVKGRMTZIQCMRQNBURDKWLMXXEXYJ", "CPWGOWQINRIJVHGBQVUOLSPRJPFHUIYNHHAQBTUTIOZTGQARPJ", "YFJEISOZEANKPWKNNLOKYSCFFFPONPUSYILBCIQKYASZYOMHZZ", "VSFKEPRENFWUNDOYVHGJLPOSOZHJKXCNTLOWOKASYFWYZEPCMN", "LYVWBJFDFFAETIGRWYYCRAUDCKSXPCSOSGGDNLVHCYOZVRNCXD", "GNULPFDXFHNSMIWREFWPWHNALSSEMZQGMYMNFEBBOKRILBCERY", "EOSETTKJWNGDOVLVSJUUTBOAKGJWGDMGBSEIMQZVGSRRUIBYJW", "URCLXQNAYXHXXMWWDZHYVAMHDRPITGMSASDESIUIEKDNPDZRBI", "AGYANSASFATSUGCBVDFCAORLYZXUBZDNCKAFUZKUHZCMANMERG", "MDNEUJJCRBYMBXDLZMAKIHDSGKJDCISMRTOSGLHNNQOTPEOFTE", "SJIIQVGUAGQNGKMNNUDPWIYVILTMMKGJBHCPEESPPVQPSIJJLA", "EPAIBUZVFKUQIFAFLAQUHCBZKJVXOTTDFFKGCOVFPIRWEYXWBD", "XEZULTSMEKWQIKQSKEKZOHYXDKEXJYRJIRJAMFFAXNBMJWZUZP", "LFZDIVTOWPFPOLEVPYRLFVCWFBDTMVSXFYQYLOZJGFEGIJZAHQ", "VRHLPWKYAFHAARKNIEZPPWKQVAWBAWNKXDUGWMQWHFRIWQQMAL", "FIKRYJJIEHPZDSFDVYILXYMEGDVINBJGOTHXGNLIREGBNZABHN", "VCNPJKXHOWZPSVLCDXXZTUXTWLLSKJIDMVLGDKZPUMONETNWZJ", "UUQQIQMEOQWX"};
        String[] allB = {"TIIADGBDWDJJDTGPGMFJNSOWAREXGDOWFKGMOSCLOHQAMFCPNI", "DSPPAMBSGILTSBGKRWNFHJRHYITQZKKSBTUSYGDKROLJEJDFYI", "MDKKDYCVIWDXJLIZYNOAYVXFUABGGLYZXOMOPTNDZDABCTQDLK", "MADVXEAPRQVSDOEIUCVUCTITPMRQFZBINDGPFKROCSONUNRANQ", "TZCADVTESDVRDPROZPRBXNOLGKLJLTQXTGVDZGGCXMLAZZUGKU", "OEVIUINZFWUHUMBSGSUGIHVFFVOHBBDNDXDBNPCSCPXWKJZFWK", "LHYAKBYGFWCPGBCBYKYOPQQHEENHZJAUWLURLLYESAUDPUDBPP", "ENJCLECPSPRLREEHNGPASKTHGQWULBAVNZEKITFQNPLYGWYMYN", "WGRUANEJFDMGPXVZCSRPAGDJGUMPMUEKMRCXLSQYXSVTXXPUMM", "YMXVPRIXQQPTUTCTWGLXXZQQBKTDTBXJLSJDGDEAVRRHRNVKIB", "JZDGSUNKLCOCLLHNCJFHDRTTSTEFRPVHROZPJMGPCCZZXEHUFX", "XLGSZFBZZWZOVLAQKMNRCOETLWHKYBYLFTAPQUQVDGRJBDKQVN", "AJSUDMBZRPNQRETHXHJMBQDUBCTHTWZKKOCXJXYFZCAUYIKOIL", "LTEUMQHANOROBNELLCGGJBHURUTYPPWHPRXUTXRKONKDOPIILQ", "MOWBTOBOXWZZJPOYBYFSPCZDVLLRSVBBSJUTJOMUFWSKADWASO", "FFZMMSSJAEQMCJEMMNXMFLPZADFEGAZDMHWGLGORQUEIHEDJJC", "IHTECPJOKKBBAFVIQRVTMBSRGEXAEAGWIHTIENBIPFMGCJSRAR", "CVWCJWWICHLIQZKGMWNBLMXUITPLIRTQXOCKUWGINPMXMWZZCW", "VVXIMUMQVNIIBRNQMTOCRAUOJKAITMOQUYMRLXXESWZLQCBJSW", "IAFDLOOTHLKJUPIIBLZPYUFWAZRUWNJLJCDSBHCKRMHDHCKFLF", "ILYBUPWSTYNDAKUOOJZRISACPRJGOJPWADLBIOQJSJLQPOTCWI", "HUQTJPSZXBHFMYFBUUSCGBTRABPTZADBZJHTBJTLAZOALUBTQK", "YIFMYELEMGTUMXILXXQBAPCMRMGHRKMBOPOMLMDCKNIOKGCBSZ", "KKXYFOOJATSVTTWGOMORLNLYJOTQQPYJMBYIQTVVFSICAAYYAZ", "TNORZUYBQOMVUIGVVJXVQDNZUDMCLKZSYIPATTKWBEMOQEVQSS", "PWGSBKUWNPGNSFVRNHJWXYMLVDRYLAYPDCJIIRWCSCTXAZRTFQ", "MBADNAOSZWSQVDMYXPQCSHGYDQGDSSKPTWRLGWZCHMOZIMNZUD", "BCKTMKGMSFTEURQALTVRUKFVRBEWZQGRMXYTRSYITULWMJLRBA", "QFEKNRMLLYVLVDDABMYGROWYUYHNYJOFMWHZCXCMVOYQHBNSXM", "SJPOUSSYUARTTGPFAYVNSASDSKEEAUNBWAKUUVDFELJPELLJYT", "KNOWKLSQEXAWCOFGXITZHNFYLBIOEVCRGCFFOKFXBWPMEXLRQL", "AQBAULHSVBWZVVXEKLAPMBOZVYFYTBAYPVNZTXYQLUPCYLVTUE", "TEGKPRHKBBAMIKXBFEFNSGTIBUETUPWFFFGOOEWYUHVWUVTJVQ", "KYFMYMZDFQWXCMRBHJZIYBNPLTIPYYNJDTBGLVWYUZLQZTDSPV", "MFKUWFZVLNTUFXDWCZFDEFSTNEVIEGHXQGASHPMUGHDVRTRHPN", "CDIWWUKRPASGBYERQNQDUMRVBMDRORQTCGQLDCSAJDOZHVSCKL", "ZUQQJQQQPIEZSTHUWJEHSPEOQXQGZFUZMGTJUYQSGKKVQPIHOJ", "YYYCNGBUPGJYNQBPQEYAMYIRSICMBUUDPJYCGBPGITQENPWISD", "NQMEZIVBMKSULFEOMNNKQHHWUWMBDKQKVGEIBTZCUTVZJTFMKB", "LCYPFOVNGWPFPWUDXUIGIMAQRYBEQLDNGNVWIPJZOQAPAQIRSQ", "OTUOLBGSUNQWAMBYHHBQJWJWLJOPAGJITBASYGZOGKQAVYPCQP", "KTJFUNHZBNIBHUAHCTLSIMHJPZNHLNLPJBOGYLMBOSTEAYPVAI", "LYKUFWACSTKAGXGHDLLRKFSAUNNBEHJPUYMPEYJCSODEHCLVOF", "JAYYIPLZSKPEXGOSLEBHCSTJPTAKNMPYNWATNLOTQQWSXMNUI"};
        String[] allC = {"YXDHQJJNBPNNJJVLTLQWCJPIHLFIALIUFYZTQSCJXKOEGVWQCV", "HOKYNPLWKFJRAQMNHRVQWWOPLQQBJDKXGZJGDQZFNXPDAISSSY", "QYTHOMSIQ"};
        assertEquals(0, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case17() {
        String[] allA = {"IDAIABBBGAIICIFJDJJJBGIDEABJEGEJHFFIEJBBEEEJIFAIFA", "HEBBIDHJFCEDEBHBDAIGHIIBJHFIGEDGGDFABGCHHEBDCGGCHF", "AIEFHFJDJDJIGFIJBGDJFGJHICFCBIAEIFFIDGDHEIJBGCHAAA", "CCAEDIGCBIDGIIDBHCBAGHABDEIDAHDIDIBHBJIHEAIJDIIIAA", "GDABJBEABJIBIFGDADICIJEJJFABCIDECJJHCDBAFGIHAIHCHH", "GACHJGBAFFDGAHIJGAEHEADIEEEJDJHEBFFHGBCGCFICHHDDJG", "AIDFEJBHCFDIDEGDGGCFDDJIEHJHBFGACEAAEBHBIAHHCIEGDF", "HAFHJBHIEBACHCCDHGIDGEHGDJEEDJFABJCIBDECGCHHDIFBGI", "JBFDIJIEBCFAFHEAJHJBBAFDFBFHAFFAHHAHIHIACAJGHHBCDA", "BGCAEDBFBAIDAFHIJDEJFHEJJDIHHAAFFIIBEDIHFJAGDBJAAC", "IDFIADBCJDAFGCGIDJBDAJHIIIIJEGAFAAFECFDGACAAEHEFJB", "HAHEIIGCFFFDGBBFIEGGIABEJBBAHGGBEIAGCFBEAAAFGIIACJ", "IGHDBDABABCADEFAEIHGGAGDIFABDFDHCIGIHFJEDDICFCJGBF", "ACJAIFBHGGBEJECFDDIEEBHGFJGCHBGIDCBEAHECFJBBDHCGGD", "AJCEBBDCIICAICHFGDGFGECDDBJCEGCACABEHJJABFBHDJHEJJ", "BIHGDDJAJCABCAFCGAICHBCBBJHCGABJBAAJEGGCCCCICGJDII", "CADIHJDIFFAHCJCHEGFBDAHFEFEFBAGHEDBCEHIHJHBIJICGFA", "JCFGECEAGAJJEDAFIECJICDEHEJCEGIJGBBDBEBJJGACGDBJJJ", "CJDIHJIEBHFEGEIGBGFIICDBDCIBCDEAEFIIGDEDBCDJHJIEFF", "IIDHGICACAJDFAAEDDBIJGBDGDEIECIBCHCGDIDCIDDBGFFEAC", "CFAGEDACDBBFDCBIJBCIBHEBFFEEHECFHIAABECCBGBIJFAAHJ", "GHGBBFIHJIECDJEJJBEDECHFIFAGICEEHAGCCGCFJAAFGADBDH", "CICJJIDIGFJHIDFIFEHBJJJDAFFIGAJBGDFIIBCIJEBAEHFCAJ", "GCABCIFEEEFGFCICCECIIJFFIDFGHBCBCCCICGBCIFEFJBDBDF", "EIFGACJFDCGDJGJADAFGIABEBHGDCFIFFHHEHDAIHCGFBCHHIG", "GHAIHEEJAHDCEHJHJGFDBEBFJEEIJCAHHHGBDFHJFIDDHFHGJB", "FCHECDAFHEJEFJGBAEFHIGEEGADEAEGEBAAFJDDHGDJAGEHIIB", "FDAGDEHEIJEHEECBDJGHAFFAEIGHFHHCGHCIDHDBFDCJBBEFBA", "IDACDHIBHCJHIFHCBAGAEHFHHFACCCBFAJHCECEGCEFJFCCBJG", "AIFBEGJDDGJGBAJFFABGICABJGFGDDAHGAAJGHHFAGHFBEDBBC", "BHEIJCHGGAAJFJEHAEDEFFHDBAFBACAEGGJBBJIEFABHBHIHCI", "ACAFBGJDHBBAAHJHFGDGAFBFCICBJFJGJCBDBCIFFGHGHEFFCI", "ADBIEBDFHIGBJACHIDHDFDDEEBJEDGDADJIAFCCHBAFAIADIGH", "DECBJCJJCCFIGIIIAAJGBGIJGIIEAEDEDHEJJJJAEEFJHBHBJB", "AHGCBJFEFEEEIEADCEACEEFJAEHCGHBIJDGDJGAHDJAJGEJCCJ", "BFHHCEJJFIJIFEHBEFIJAHBDBCDJIIJGHDHGAHHDHEGIFDIFIF", "HCEDIJJFEBHDJIIJEDECIBHBDBJEBICAHAAHDJEHEEIAFBAGGC", "AECJGEAFHCEBDG"};
        String[] allB = {"ADAAEGEHFDIHCDEFIIHIJGIDJGACEEFCCEAGHAEEIDDCIAIABH", "HGDFHJAEBHEHIEGJFGDFDHIEJJAGCGABAAADBCHCACEBEEJEID", "FCHCBDBJBBDFIEDBEHHIGAHEFFGCAGJGADCCJEBCJIECFDCJBB", "IIGEABEBFHEHAIHHGFFHAEEDFJDGHDBADHAAEIDGFBBGBDEAAE", "EGEHCBEHFBGABGBDFGJGGECHFHFCJDHBHHBGFBDHABEJCHHGFI", "DCGHEJDFAJBCJJHAGFJDEFEIAHHBIHCIBFGDIGEGEEFDEHEBFD", "AHGBGIAGCGJCJBGAJIFBIEGGJICGIBJEGHEEFDGDJCHIFHEECC", "FBCBJGGDBJAAEHDHIIFDAAHJAEGBHGBBIDJJHIEFCIBICJHCAA", "DHDADBGBHECJCBCAFHECIACEHBAJACDDIEFFFJAGJIDHGDIDHA", "DFHJHJJDEGCADCAGEGEDEACJEJGBGAFEIADGDHGGFFAEIIEIHA", "BHEAHFDIEFAEEGDDDADBEGFJDDFEBEFBCBHCFADJDJHBJCGFAJ", "JGIAGGCJIBFCACAFFBCJDJAFDFCEGAJIBGBDFHJABIEIABEBHB", "JIHHBBFDCEEAADCHBJAHIDHDDEGDIBBIEDFGBDBAGEADDDEGID", "HDICCHJAAIDEJDIGBABEHEIBICDCJHJDCIICBDGBADGJIJAFEG", "DACDCFGBFBAFDJEDECAAHJCHBECGGEEDDHEICBIDJCACHBCFDE", "DDHBDJFCICFHFCGDIFBGFAICFCIBCCCFJFBEAAEHEIGAGGFCAJ", "HIIBFAFAAEEBDCCHHAJDDJEEDJIGDEEHGDBBCDIDBEIIDAJHDH", "AFDIDDEFJDHBBCIDGJGIFHEGBIJIACHHBGEDDDHEHEDBHJEGGE", "EBEIAFCFJAHEJGHBFIIACBDEHAAJCHGFIFHHDFDACHDCFJBBIE", "AIHHJBCFBDGDBDBCDAGAEIJBCGACJHACAJIABCFGHFAABADBEA", "GCDJAAEAFCBGAEBGDEDEIEHAFFAFBAHEJHDEHCIGDDHJGEBAAA", "EGCEDAACICAGADECGBHDEFGEHFFGADCEFBEJDBCJHFCEJCGCAJ", "FDIDGJAACIEEGJAEEEFAFADFAEJIDHAECIBECEJHJIIBJHJCDJ", "HEBBCBABAIHCGFAGDEHGCGHGFCJDEBEBCJBHHFBJHIJFJHFFDA", "AJBHBFBEJBIIHBEFCGHDEJCHIEHEJEHJHEJFJFECFBFFIDFJJB", "AGEFJEJBGJJFHECEGBDGICCBFGEIJBIHAGJCHEHFFGBCCADBGJ", "GGIJDCFCIGBEJIECJBIEGEGGBDIBAJIFFDCBCEEIBJBHAECHGF", "IBCBAJBGJHBAIEJHGGECCACAJJJDCAGJIGGCFIEAGFGIHIBGHB", "FDJAHFEHCFJGJBIEBIBIECEJBHBADIEBEBAFAHFEAEFEEGGHBJ", "JAJCDCGBADHCDJAGDFEAIJGCGJIIFGJFJBBHHJEJJECGCIFIAF", "AJFGFGDJIGDBEIIEDJIDIHGIBEBCEFJAEIDCDAGFACDCIGEIEI", "EHFHBIAAABEFDFDJAEHGCAIFHGCEJHDICAFJJHICBIJABHAICF", "FADJBGFEFACCAHBBFJAJIACBJHHDHJEIAGHDEHIAFDJIDHFAFJ", "EBCAHHFEBABBGAFIJJIDCBEDICHAIGJHIFDHAFFJJIBJEEAIHC", "AIGHHFFBHHDEFJBAFFHEJCGEBDFHEFDFCDGJFBHADGCBIIHGFF", "BFDJECFEBCBFICICCFDIFIEDFCGCEHIDBIGAHGAGEJIHFCHCJA", "ACDFHAJCJEIBCGBEGDGFJFJBAGEHGIBBAEFGGHCCIBHBACBHCF", "IIFHBHDIBBDJCBJAFHEGAGCFJHFACGDEFFDCAIIBIFGGHJAJCF", "CBAFFGCFDIIJEJDEBJIBGAHEEBAFGHJAIDJBEBDFJDBJDFDGDC", "FBDCJAJFHABFEJFBGAFCBAAHAJICFJEAGBGFDCBGDHEGJBABGD", "DAHBGFFHFIBIBCJBGCJECIBHIJCADAAJDJJHCFCCEFJIEAAIHB", "FBHABGFDEFECJCJEFHCHCEHHAGGGCFFADFHDHIECHEIHEIEDIJ", "HHDGDJFDEGFHJJI"};
        String[] allC = {"DHEJHDHBIEHCCJCFHIDCAJFIGGGEBCIHIDABJHCBBJCJAFBJE"};
        assertEquals(793, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case18() {
        String[] allA = { "HIDBCDAHCJDGJBDABJDFCAHFDCFJGAHCEADCHCECJGGJJAJDHB", "AGIBECBACIGAIAIJHGGJDGBEGCAJHACIJABACJAIJHJJGBEIHJ", "DDBHDGHEJIDJIBCHDIIFGFCFEJJDCGFJEGCEJICBEABJHABABC", "CEBBAHGCJFHEHBGHCFABAJHGJGACCDDGGGAJHHBHACJFDIEDFA", "DDDJHADCGCFBEBAFCEBDEAEHHFIGIEFIJBHEFHJEHCFIJCCIEE", "JDHIJHFCEJGFGJHCJEGGDDHDCIBBHDCCGEDACJIBCAHEFDEGAJ", "BHCCJBCEHIJAJBAGGJDEBDJHBACJHDEICHGHDHDEEGCCAHGBDD", "JFIADCBGEICGAHHAJAIABDHGBAEAACFEHFBHGDGGEECGAAHHDD", "JGIHBFEEIBICBEHIJDFDHJCFEAGDABAGHAEIEEACIBGBAFJAII", "IBBIADFHGHFIIFFECJFFIBHBCBGDDBBEGDJDDAEHCBFHFEGJGC", "JECDBGGHICDABEFHGDIBEAGAIEJBJCEFHIDIBIAFJIIIFJGHAH", "JDCJGBGACIGJCGIGHGDFGDCFIFAAHCCHBEDFFHIGHIEFICFHJE", "EGIHECGDJECAAACEJDDJIFGCCBEADBBHFCHCEGAIJDDJEAIHBJ", "HIHHHFFDEABCHFGHDFFIDHFHBIBADIJJCHAAEBAEICHCFIDEAG", "GIDIBBGEGFHBJJEAJAJECDFCGBBAHIGBGIDFEGDHHJCIEJDJAH", "IHIIJJCDDCCDHAFJJHJIHHEBIHHBAHFFFJGEBCBFFGDIEGAAGA", "FEEFGFHACAGIIBFJBDAFEAAGHCEEICIDDDEHBEAGADJEIGAIDA", "GGEHIBFDDAEDACIHDHEHFGBDIAHJIJHAFDDCHAAAACBJAJBBHD", "EDEJCCFBCIHJFDAAAAFBFFFCGEIJGGGGAGBBJHGBDFHBCJIGDB", "IEJFAAAAAFAIIJBAAIDGBGIHGGBHHEFFIHDJHDFDCBGGGEIIDH", "DEACADAACBEEAEHJHDCGCGHCJDAJEHEGGABDACDJIDFADJJDGI", "BFBAIFABGCHGAJFICEGAJBFHIBDGHGBCFGCADBEAAACHJBGDFE", "GCHFGGJDDFJJDCIGCCJIIHIJBHHCCDHJBJFJFDEIIFAEBFDBIB", "IBFHIJCBFFDBEFFBDJDIJJIBFBGCFBIIAACFEHCBAACIAJFHFG", "DDCAIBCCFBGHEJHFHJHGGBJBHEFBEBDJCCICFGDJACEDDGDJJA", "JIEGJDDEFFJFDIBIFFCHFDIDDCJAGEDFHJCHACBFGCBCBDGJGJ", "IIBHDCDIDGFCCGICDEIIFHEABEGBIFIJACBCEHHFFAEHFIGFDE", "CEGDIHCBIGADIBFFCGJDDEBHGIJJHCHCGIEAICGBHGBIBBIEEH", "IBIDFGEEDIHHCDJEAEGHGHHFJGBEIGDADAEEJDCFFJGHDBAJAJ", "GJHACCEDHHHJJIFICEADEHGHBHDEFIHICIADAAGCAGIGICEDGF", "DBIBCDEHHJGBCICGIIHJFDIHCEGGGGBHHFCJBHHBEJICEACCAD", "BDECGGEHGCFIBBGCHHAEGHIHDDIFCAHFGEDJAFDJCCCCDHBDDE", "EBHCGBGGAHGIGHDFJDCFIEJEIIDIBACIDJEEIEFBHIFHIBEAAJ", "AJIGIECGGFDJCBHIJBGBBAFFDCFAJDEBGDAHHEFIGBCBHAFGAC", "BGCIGHGFGHAFIDHHDJIDFCJGGDHFDADEEDAEJGAGECJBDHFJBC", "BAIIJJGEIACFJHJFCBFDHBGECHJEJGBAGHDAEDIJE" };
        String[] allB = { "AFJEDIFIFJBHABIHHCGIBEBCGCEEABIHGJFDHAEFHAGAIDADGB", "BIEDJDCCAHIBDJEFIJDDCFHICDADIGACEFBFICFGHGGFDJCAEG", "JADHHBEIIBFCFACJIGJFBFEFCGDBJFEAHCFBICCFIGHBHAFABH", "FJJEEAIADFFEDAGIAJAJGIGIAJJFBHDAHCJAJHDICBGCFGHHGH", "FJCDBAEIAIJDFAFGBGEEGADDEDJHEIBBFJFGGFEEIIEGBJHCCA", "DJIBICIEGHJIFABEFDBCGHBABJJIICGHEGABIFGFCDCBEJABHI", "GAHHFCHAEGFDGIBFFFIGAIDFGEFCICEHFBAHHBEHIGECAGFHCE", "IGIDAHFBBADCFJDGCJGIECDDIDEAGACDGBIDEDBEJJHBACCJDD", "DGIIEJAJDJCIABJHDEEGHEJBFDDIEJBJBEBJFHADFCIFGDCEIF", "EGGIJGGDEJAAFDFHIIFGFEDHHHGDEGEDAAGAIACIJHHFEJCIDD", "EHIFJHJCACIJFEEJHCDGDBCABHBFDBGDEJFIFAFGJEIEBEBDGF", "BCFBFGEACIFHHIAJFGCAHEDDCFHHCAJDIFEEACDBAICIGAIEJJ", "ICGDCGDFFDCIIDAIFGFAGECHCFDBCDJHDFJBBGAHJBEBBCBHBC", "HHFEIHIGIFJHFCAFIBDADDAGEJBFJJEGHDAHAEAABDEGEAFAAJ", "IFJBGBAAJDIHIHAJGCDECGIHDHBDABCFEJDGGIIHHDIIIECEBA", "GDDAGAEGJBAGFHCHFHCCIAFEHHEBDEJECBHFGAFFEABEBIEGEC", "CEJJJAFICCGICDBIEJDEAECAIJACAJCGFHGAEIDGJEGIEFDJBF", "JCAJFEHBJIGJCJFAIBEGIJHHDJIHGGHDEFAFAGAEBIFHJJAHJC", "BIHFJIGDBFFFAADDADBGICAJGEBIDBFDGFIGJAAHIJAEADJJAG", "GGFGFHHDBIDEDFGIJCBBBIBIBJFGHDGGJIIBFGIDEHGCGCFJDH", "IHAFCBCCFBJIHAFHFIGHDCEFACGBFEBFAGGJGICFJFJEGBIACH", "BBBFDEJJEHBIGHFGHCHDBBIIDAJAIJGHDIBDFBHGFADBAHCGAH", "FFHEABHJAEDBHJIDFHFIFGDGJGBGHFGAJGAAJFDEFBCCDGGGJE", "BGGFFBJCBHGHHIIDJJEBJAIAIECJCFDHBAIJIFGCAACHBJCGHJ", "JEHBIBEBDCHCHBEEJFCFJBIBEFHEGDICCFJIIFGBFAEBCIGIJF", "EFEADGAHIDJHFCIHAHAIGEIFAIHFEFHGEFHEFDGHHDCJBJFJBE", "EFHICEBHEEDIEHBDEBIBJEDCBJIECHFFFDEEEFBIFFHJADIJIE", "BAAIEBBBFJFIICDHHACBBAJFFDDBFFJJFCAEGEIAAHECIDCAJG", "IDEDABIAHHJHBIBDGEEGAGIJGHAAFEJGJJCIAAJCBEBJJCDFAB", "HDEAADBFFJGCJIFHGEAJEJBCDBCGDIGAFBGDIFJGCCIFGIGEFD", "CADJDIDICGCAAGHAICJCFJBCHCFGFIDFBGJHCAJCFEBJDGECDG", "CFFBGBHBAHHEHHBCHJABDCCJBJEFCGFCFADDBDBEAEADCAEGEG", "AGBHFJIFFCIIGHGAEHGGFDGBCGEGDEAGDJJHAJHHGDEDBDCBIC", "BAHGCHBGGIEJJGIBHCDEDDIJFHIJAFEJEBICCEFEGCDGJEBEBH", "HJEBBICJEEDEEFHDHBBGFDFGBHGICJDEDBADJAJJDDAIAJCJCG", "IFIAEEGEEHDEFADJGHCIHHDFFBFECBFBAEGJBAEAJEIAFDHIJH", "DDBAFDCFBBEHIAEHFJDCIBDFDECEBGHIDFHA" };
        String[] allC = { "BGEBHCBDFJADJFCHGCCJEBBJCGECIAHCBJGHDCBBFACIHIDHFE", "H" };
        assertEquals(726, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case19() {
        String[] allA = {"CIAEEAGBDGGFACFACHFCHBIJDHBADACDGHBBDAHCDBJAJJADHJ", "FAGIGDBIABBHCDCHCFGBACDHEHEGCIJFBFHHDFBGBJJBCGGCEA", "EIACHIBBHBFIFGFBJCHHHDABFGFDDDHBDBDBHGEHHFCIHECBHH", "DGJBIHEADGBJJEBHDIFHFAJJBEHCFADJAIJGBEHJCEDCJAECEA", "HCHHHFCDBHEDJCHAHBHIICJICGHHFEBEHDHFCCGJHBHBEACCEC", "JGABCBIFFAAGCEBHHAFCFGHGGGDGHAJBBDCFJICDBFJEBHGADB", "CFEFFBBFBCAADFFBHDJBDEIAHEDDFJHBJJFDJHDABEDJAICDHG", "EHBCHDBAACFIEBHIIBHIDIBCJDCCJBADHHDCIAHABHGFDCBCEC", "EHDJBHEEGDBIFAEABEFEHJAFEGGHGHBEDAHGEFCIJGGAHCJFIE", "AFIHBEIEBDAICHHFCIHABAEJGAHEJFDGCCIDFCFDECHDBFACIG", "HHCJFCBFFEABGAJHBDEABECFJJAJAJDHGGCAIIDAEFEEACBDFG", "DCDGBGEJCBEACDIFJGFFHEGFAJJGBEFCIFIJJGCFFDDBHFBGBB", "IDBCGGDICBCAIHHGGFBDHJHDGFBDDDAFBCBHHGEGCDECGHBIGA", "IIFGHCJIEHAGFDGEBDHAFCCFDADFAEBIIICDHIAJEIFHEDJGAD", "FEGHGGABHBEHDGJBEAFIDBADHJFGIHGIFHDIACHDHIAAFDIAJE", "EIGAEAHCFJIBJHCCGGCFADHDDBEBFDJJJDJGEDBIBDCBGFFHCI", "IFFHJACBGBCDDHAICADJCJFJHBAFCJBAEGFBEJIHEDFGCEJIFH", "ACCFDGDBHGEFBFHBBFBGEAAHHJCEGCEHJDBGGJFFDIAICEGAHF", "GFBFEHIJEFHFGJAIJGEEFHBEGJBEAHJCEJAHEDGDDFGECDHHBF", "DAHFJABGDAFCHHFJEDFCDCJJFFHFIBHCJAHDDCCCFFIFGCCDJG", "HGDEHHBJDDAJDHFFGGJHDBGAJCECIADHEIFGDABJCJCBEHAIEC", "CECFBCADJJFEEEDDCGEJCADHEBJDACFDBBGEJCJGCJIBBABHFA", "DIIBFGAAADHCAFEAGCJIDFIIGJGECIIBAFDBAGECEFFCICHIJJ", "IHCDHABCDHJAFGCBIJFCJCGGDJBCAFAJEGCIBEGGFGBDFCGJEG", "HDAFIJFHHHAIJCBIABHIAADAEAGIGJCHFHGCDIFCHCECADAIDH", "FJHIDCFAICCAIAFAEIHCEHJCFGIGJBHAHGIBBEHFIEHGGIBIJB", "BBGHHJIDABGGFGDJBCEBCGIEEFGIEFIEEBCIDCGGAEIBIECCJB", "GIGJFJEHCJHAEDCAJIEDIAJHHHCEHBBGFIAEDHEECADEGJCACA", "FEDEICICFFACBCIAFBGGIIAHAFIAEJDIABCCBBFACBBEGEBJEG", "DAEBGFJICBBEIHIBHBHBEAEHGEEECCHEIBJCIADJJJAJDFCAID", "HHAJCHCGADCIEJGIEHADAIFFAJAIEJGEJHJDBDFDHBDGJGHBFF", "GAEHIGJFBCFJDCFCEGHHJBDCIGFCFJBHAACFDGFFGHJADBAEFD", "EGFAJEFJGBHHJFBIHAECEJFCFBHCJDGGDGICABCEGBDEDDCBFD", "GIGBCGEDHDBFGGDGCHBDICIAJFIEHAHEDGBHICGHEAAHBIAJBG", "ICHACAEDFFAJGAHJBAGAEAIHBFJJJBJFJHDHFDIDEIABJDFAGI"};
        String[] allB = {"HHBCHFHIGIBADFFAJICBHCIAHICDDFEAHGBIGDGHBGGAGJFIHB", "HBAEGBDIJCDAGIGCGIBAFEBIDHFDHIFHDJJCIHICDIEIJDJAJI", "GJEFICJHFFIGGFDHBCECBJBGBJDJAAFGEECCIBEGFHJEECAHIG", "BAHGECBABCFDBADBADFDBHIBEAEFEJADIBGICHHFGJDFAIFBAI", "AJBIBACIFJBBIGGDCDEBCAIEFHCEJEEFCFGDFDADIJIJCFHHHD", "GJJAICDDHABHBHFHGGCGIBDDGAEEBHEIBDHGIEFECJEDDGDBAD", "EAGGEIICFGGEFBACDAFCFJCJABGIEGBIHJJAJAICGFCFGCDGHE", "AJHIJHBGIHDAGFCHIDFIIDEIHIGJHAHBDEAJCCIIEDIAADEEGF", "BGIHEAHJEEGCDDBEBJCEJEEGDFHAFCCCAHCIFCEBEEDHAFBGIE", "BHHCJEJHJFBGCIGIIDIJCFIHJDBCBEFBIEGDGBHIFDICIJCJHF", "GEJDDACBHHIJBDADCDCEDHECHJJGIBCIEIJAFBJCDDHFEFHFGF", "HDJBAEHCIFGGGJGBIEIDFBGHGGEIIEEGBAJAGJDHFJFBBAGAJD", "AFGJBEHEIDFHIHABFGAHIAHDJAEFIGDFEEJGDEFDEDDIFFCAJI", "FJDFHIGEFAHEGCBJHHBAHFEHDJAIHDBICHJCHBAGFBABEGFHGE", "HDEAFFDGAJDIJDBJHIEACHJEBEBBEBJHFAIGJCIDHHEIFCBFEI", "HGFGHBIIAGGJGIEEHDBJCBBDGBJABHGIAHDFEDFEHDICIBACHA", "BHAGECEEAGADJBFGIHIEJFCGAFICFHBFBFHDAFBHJCCDHBDHEE", "EDAFIBIHEBABDGGGEDIFCBADJHBCBHEJJDCDIGDDFABHJHGDDI", "BHBABJGHGCIABAHGCAEHCADHBDBIEACGCIIJDAAIGDFJEIBGBD", "BGHJFJEDAGCGGFGAIAEHFCFGGIAAAIFBAFGHGCGEECCBIBDGCE", "AJAIBFHCCECJCEJEABAAADHAFIFJBJJJIHCFBCJFBHAJCDEGJJ", "GJCAFFHDHHAGBGIIFBIDFCEFDHEECHDEHJGHJHAEJJFIAHGCIA", "FBHHGBFFHECDGDHIJDGAHHCBJGEGDBCDHFIIFJAHCFJIFHBIIB", "HICBABCFJJHGBGBEHHFEBJGAIIFJCEADCFBGDFGFJAHHCCEHGE", "FFHFFIDBGDIEIEJJFIAFEJJCFBIDBAEAJFFFDCAICIACBFFGEB", "GBIBGAHFHGDFICBDJHEBCFDCAAIDJJHGAFIBBAEAFBCFECAHGG", "AFEHEGHAEDHIEEEDGEEDAHHCCICBEIDAEHEBIIICIBGFJGICDB", "EDDEIDFBFHCAAGDHBHJDFGIDDGJBEGAGAIEEBJEBCIADCJECEH", "JIDICIAJAFIJDBCEGJGGEHGICGDJHEBFEIIHCCEIAICHCHEDAC", "DFJCCBBCIAGBHFIABBDIEDCFCIDEFDHFCFDCCADEEIEJDIGCFH", "IDGJHCIBBFEBCFCIIIEDEFJBDHFFBJGAEIFDDEEDBADFGHHGFG", "HJHJHGJDCCBBDECGABGCBAADJEEFHFDGGHAAHFFFJIACJBFGHA", "EDEDDAJFFIABDHDJHFEIFIGHFHCGABIGJEIAFDHIHIBEGCBHDI", "JBEEFBCJHEAJIHGIFDFFEBCIICBIDDJAJGAGFAHIJHGJGFGGHG", "AJJGGIFGFCBJHEIDDHHIJAAAIIBBHGDFDIAJCBGIDEIIJBIGCC", "CIECIHCBEJDFICEIADFCGECGDBJACJDIEGIGEAHHFCJAHCFIEE", "JCCAFHIIHBDIBHHBCBBBHHIGJIBHHBCBECDCBJCAJBACECHABB", "CIEIAEBEIECIDGCBDIDFHFFIFBIEIDHAIHDAAAABICAABGAAEC", "JIAFDIADAGCEGFJGGGGIEEIFIJEIEFBDJJGGDGHEIEBDABJIGG", "DBHDFBECACCDJFIJBADHIECCDCFEDDJCICIDFGDBAHBBIFBGIF", "EEJBFEECEAIGJBHJCAEAJJCJJEJADBBEDAGDBGHAECGABCAHCI", "BEEICABHHEGIDHGFHHEJFCHAADBAAGJCAIFHJHIBADIJFDJBAF", "HFHFFFHDDGIFGBBFCHAEHBHDFDDFFIAHIJJFHIDBCADAABEBDI", "JFGHDCBBEDEDEHGDAEDEHEFACBCAIFBFHEFCCJECBHAEBBDDII", "JGGAJGJGHJADCGDBGBFGIBGGBBBFHEHFEDEABDIAJIAGCIDBEH", "AHBC"};
        String[] allC = {"IDCGCFJDFGCGHEGEABGCDEGDGDADICDBECEFJFDGJBCJCEFECJ", "IHGAAAJDFCIBJDGABDFDHB"};
        assertEquals(734, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case20() {
        String[] allA = {"BAABABBABBABAAABBAAAABBBAAAABBBABAABABBBABBBABABBB", "BBBBBABBABAABBABABAABBAABABBBBBAAABBABBBBBBBBBBBBB", "BABAABABABBBBBBBBAABAABBBABABABBBBBABBAAAAAAAABBAA", "BAABAABABBBBBABBBAAABABBAABBABAABABBABAAAAABABABBA", "BBBBAAABBABAAAABBABBBABBAAABBAAABBABABABBBBAABBBBB", "ABBAABABBBBBABBABBABBBAAABAAABBBBBABAAABBABABAAAAB", "BBAABBABBBBAAAABBABBAAABAABBBABBABBAAAAAABAAAABBBA", "BABBBBABAAABAAAAABABAAABBBAAAABAABABBBABAAAABBBBBA", "AABBABAAABBBAAABBAABBABBBAABAAABBBBBAABBAAAABAAABA", "BBABBBABBAAAAABBBAABBABABBBBABAAAAAABABBAAABBAABBB", "BAAABBAABABABBBAABBBBBABBABBABBBBAABBBAAABABAAABBB", "ABBABBAAABBABBBABABBBBABBBAABABBBABAAAABABABABAABB", "AAABABAAABBBBBAABAAAAABBBAABBAAABAABBBBABBABBABBAB", "ABBABBBAAABBAABAAAAAAAABBAABBAABBBBBAABBBBAABBBBBA", "ABAABABAAABBABBABBABAABBBBBBABBBAAAABAAABABABABAAA", "BABAAAABBBBABBBAABAAAABBAAAAABBBABBBAABBBAABBABABA", "ABBABAAAAAAABABBBABBBAABAAAABABBABBBBABAAAAABBAABA", "BBBABABBABAAAABBBABBBABBABABBAABAAABBBBAABBBABBABA", "BAABAAABABABAABABABABABABABAAAAAABABBBABABAABBABAA", "BBABBABAAABBABABAABBBBABABABBBBAABAABAABBAAAAABBAA", "BABBAAAAABABBABABABBABBAAAAABABAABBBBBBBBBBAABAAAA", "ABAABABAAABAAABBBAABBABAABBAABBAAAAABBBBBABBBABBAB", "ABAABABABBBABAABBBBBBBBAABAABBAAABAABABBBABBBABABB", "BAAABAAABABBBBABBBABABAABAAAABBABBABABAAABAAAABABB", "AABBAABABAABAAABBBABBBAAABAAABBABBBAABAABABAAABBAA", "AAABBAABBABBBBBAAAABAABAAAABABBBBAAAABAAABAAAAABAB", "AAAABAAAAAABBBABABBBABBAAABBBABBBAABABBABBBBBAAABB", "BBABAAABABBBBAABABAAABBBBBABBABAAABABAABBAABBAABAA", "BABBBAABBBAABBBBBAABAABBBBBBAAAAABAAAAABBABAABAAAA", "BABABAAABBAABAABABBBABBAAABAABABABBBBBBABAABABBBBA", "BAABBABBBBBAAABABBABAABBBABBBAAAABBAABABBAABBBBAAB", "AABABBBABABABBBAABBABAAABAAAABBABABABBBAAABABBAABB", "BBABAABBABBBBBBAAABBAAAAABABBAAABBBAAABBBABBAAABAB", "BBBABBBBABBABAABAAABABBBABBBABBBAABBBBBBBBBBAABBAB", "BABBBAABABBAAAABAABABABBBAABAABBBBABBBAAABBAABABBA", "BAAABABBBAAABBBBAAAABBBBBBABBAABAABABBAAAABAABABBA", "BABAAABABABABBBAABAABABAABABABBBBABBABAABBABBAAAAB", "ABAABBBBBAABAABBBABBBBABBBBABBAAABABAABBBBAAABABBA", "AAABBAAAABABBBAABAAABBBBBBBABABBBABAAAAABBBBABAABB", "ABBABABBBAABBBBABBAAB"};
        String[] allB = {"BAAABABBAAAABABBABAABABBBABABABABBABBAABABABAAABBA", "ABAABABBABABABBBABABABAAABBAABBABABBAAABBAAAAAAABA", "AABBBAABAAABBAAAAAAAABBABBBBBBAAABAAABBBBBABBABAAA", "BBBAABABBBABBBABAAAAABBABBBBAABAABABBBBABABBABABBB", "BABBBAAABBBAAAAABBBAABABBAAABAABBABBBABAABBBBBBABA", "ABAAABBAAABBAAABBABABAAAAAABBBABBAAAAAAABAABBBAABA", "ABABBBABAABAABAAAABAAABABBABAAAAAABBBBBBBBBBABABAA", "BBBBABBBBAABAABABAABAABBBAAAAAABBBBBAABABBAAABBBAB", "BAAABABAABABABAAABBBABBAABBBBBBBBAABBAABBBBAABAAAA", "BABBBBBABAAAAABAABBABABAAAABAABAAABBAAAABBAAABBBAA", "AAAAABBAAABABAAABABBBABABAAABABBABABBABAABBAAABAAB", "ABAAAABAABAAAAABAABBBBABAABBABABBABABBBBBAAABAAAAB", "ABBBBBBABBABBBABBBBABBABBBBAAABBABBAABBABBAABBABAB", "ABBABAABBABBBABBAABABABAAABABAABAAABABBBBABABABBBB", "AAABBBABBBBAAABBBBBBBBAABAABAABBAAABABBBBBABBBBAAA", "BAAABABAABAABABABBBAAABBBBBBAABAABAAABBAAABABABBAA", "BBAABBABABBBBAABAAAAABBABBBABAAAAABAABBAAABAAAAAAB", "ABAABAAAAABBBBAABABAAABABBABBAABABBAAABABBBBABBBAA", "BAAABABBBABABBAABABABAAAAABABABAAAAAABBAAAABABBABA", "BAABAAABBBAABAABBAAAAAAABBAAABABBAAAAAAABAABBAAABA", "BABABBABBAAAABAAABAAAABBBAAAAAAABABABABBBAABBBAAAB", "BBAAAABBABAABBBBBBABABABABABBAAAAABBBBBBABBABBAABB", "BBABABAABAABAABBBABAAABABBBBABBBBBABAABBABABBAABAA", "ABBBABBBBABBABBAABABAAAABAABAABAAAABBBBBBAAABBABAA", "AABBBBAABBAABAABBBBBBBBBBAABBBAAAABBBBABABBBBBBBBA", "AAAABBAAABBBBABABBBABBBBBABABABAAAABBAABBABBBBBBBB", "ABAABBBBBABBAABBBAABBBAAAAABAABAABABAAABBAABAAAAAA", "BBBBAAAABAAAAABBBBABABBBAABBBBBBBABBBABABABABBBAAA", "BBABAAAABBABAAABBAABAAABABBBABBBBBAAABBAABABABBAAA", "ABBBAAABBABBBABBBBBBBAAAABABABAAAAAAAAABBABBBBABAB", "BBBBBAABABAABBABABABAABBABBABABBBAABBAAAAAABAAAABB", "AAABABAAAAAAABABABAABAABAABABABAABBBBABBABBAAAABBB", "BBBAAABABBABBBBABBBBABAABBBABBABBBAAAABBAABAAABBAA", "AAABBAAABBBAABBBABABBAABBBAABABBABBABBAAABABAABAAB", "BAAAAABABAAAAABABBBAABBABAAABBBAABABAABBBABBAABBAA", "AAAABABAAAABBBABABAAAAAAAABBAABAAAABABAAABBAAABBBB", "ABBABBAABBB"};
        String[] allC = {"BBBABBBABABBBBBAAABBABAABBBABBBBBBABBAABBAABAAAABB", "ABAABABABABBABABBBBBBBBAAAAAAAAAAAABABBAAAABABABAB", "BABABAAABBBABAAAAAAABABBAAAABBBA"};
        assertEquals(1464, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case21() {
        String[] allA = {"ABBAABBABABABAABAAABAABAABBBABBABBBBAAAAABBBAABABB", "ABBABBBAAABBAABBBBABABBAAAAABAAABABBABBAAAABAAABBA", "AABABABAAABBBABBBBABBBBBABABAABBBBBBAABAAABBBBBAAB", "BABABAABAABBABAABBBAAABBBBBABAABBABBBAAABAAAAAABAA", "BBABABABABBBBBBBABAAAABAAAAABABBABBBBBAAABABAABABB", "ABAAABABAABBABBAAABABBBBAAAABBABBBABBAABAABBBBBAAB", "AAAABABAAABBABBAABAAAABBAABAABBBBBABABAAABABAABBAA", "ABBBBAABBABABBBABAAABBABAAAABAABBAAAAAABAABBAAAABB", "AAAAABBBBABAABBAAAAABAAAABAAABBBBBABAABBBAAABABABA", "ABBABBBBABAABAAABBABABBBBBABBBBABABBBBABBABBBBBBAB", "ABBAABAAAABAAABBABABAABBAABAABBAAABAAABABBAAAAABAB", "AAABABABABABABABBAAABBBAABBAAAABBAABBBBABBABABBABB", "ABAABBBABAAABBBABBAABBABBABBABBABAABAAABAABABAAABB", "BBBABBAAABABAAABBABAAAABBBABBBBABAAAABBABABBAAABAA", "ABBAABABBBBBAAAABBAAAAABBABBBBAAAABABAAABBBBABBBAA", "BAABABBBAABBBBAAAAAAABBBBAABABBABAAABBAABAABBAABAA", "BBAABBBBBABBABBBAABABBBBABABBBBBABAABBABAABABBBABA", "BBABAABBBBBABBAABBBABABBABABAABABABAAABAABAABBAAAB", "BABBAAABAABABBBAAAAAAABABAABAABABBAAABAAAABBABABBB", "ABAABAAABBBAAABBAAABAABAABABAAABABAAABBAABAAAABABB", "ABABBAABABABBABBBBBBAAABBABBBBBABBBABABABBAAAAABBB", "BAABBABABBBAAAABABBABBABABBAAABBBBAABBBAABBAABBBBA", "AAABBABBBABAABBAAABBBABBBBBABBABBAABAABABABAAABABA", "BAABABAABBBABAAAAAABBAAAABAABAAABBBBBABBBBBAAAAABB", "AABAAAAAAABBBABBABBBAAAABBBBBBBBABBABAAABABABBABAB", "BAABBBABAAABAABBABAAABAABAABBABABAABABBABAAABBABAA", "AAAABABABAAAAABBAABBBAABBAABBABBAAAABABBBABAAAABBB", "BABBBBABBBBBABABBABAAAABAABAABBBBABBBAABBABABAABBB", "BABBBAABABBABAAABABABAAABAABAAAAABBBBABBBBABAAAAAB", "BAABABABAAAABABBABABBBBBBBABBBBABAAAAAABAAABBAAAAA", "AABABBAAABBBABABBBABAAAAAAABBAABABAABBAABAABAAABBA", "BBBAABAAABBBAABAAAABBABAAAABBABBBBBBAAABABBBAAABBA", "BBAABABAAABBAAAABBAABAAAAABBAAABAABBBABABBBBBBBBBA", "AAABABAAAABBBBABAAAAAAABAABAABAAAAAABBBABBBBABAAAA", "BABBBAAAABAABABBBBBBBAABBABAAABAAABBABBAABBBBAAABA", "AABBBBABBBABBAAABBAABAAABAAAAABBBBBAABABBBBBBBBABA", "AABBBABAAABAAAABBBAAAABBAAABABBBBAAABBBBBABBBAAABA", "AABABAAAABABABAAAABBBABABAABBBAAAABBBAABBBABBABBBA", "AABAAAAABABBAAAABBAAAABAAABBABBBAAABBBBAAABBBABBAB", "BBABABAAAAAABABABABBAABBBABBBAABAABBBAABAAABBBAAAB", "BABBABBABBAAAABAABBAABBBAABBBABBBAAABBAAAABAAAAABB", "ABAAB"};
        String[] allB = {"ABBAAAAAABBBAAAAABAABBABBBBAABBAAAAAABAABABAABABBA", "BBAAABBBBBBAAABBBAABAABBABABAABBBBBBBBBBBABABBABBA", "BAAABBAABBAABBBABBBBAAAABBBBBBAABBAAAABBBAABABBBBA", "BBBAABAABBBBBBABAAABAABAABBBAAABBABABBBBAAABABBBBB", "ABBBBBABBABBBBAABBAAAABBBAABABBBAAAAAAABABABBAABAB", "BBABAABBBBABAAABBABABBBABABBBABBAABBBBBBBBABABBAAA", "BBBBBAABBBBBBABBAAABABAABBBBABBABABABABAAAABAABBBA", "ABABBAABBABBAABAAABABBABAABBAABABAABABABAAAAABAAAB", "BBBBBBBABBABBBBAAAAAABBAAABBAABABABAAAAABBABBBABBB", "AAABAAABBABABABBAAABBAABABBBABBAAABABAAAAAABABAAAA", "ABAABBABAAAABAAABBBABAAAAABBAABABABBBAABAABAAAAAAB", "BBAABBAABBAABABAABABABABBBAAAAAAAAAABBBBABABBBAABA", "BABBBABBABBABABBAAAABABBAABBABABABABAABAAAABAAAAAB", "AAAAAAABABAABBABBBAABBBBBBABBBAAAAABBAAAABBBBABBBA", "ABBBBBBAABBBBBAAABABBAABAAAABAABBBBBBAAAABAABBAAAB", "BAAAAAABBBABAAAAABABAABABABBABAABBAAAABABBBABBBBAB", "BBBAAABAABAAAAABBBBBBBBAABBBBBAABABAAABABAABBABAAA", "AABAAAABAABBBBBBABABABBBAABBBAABBABBAAABBAABBBBABA", "BBAABABABAAAAABBAAABAAAABBBAAAABABAAAABBBBAABAABBA", "BAAAAABAAAAAAABAABABABAABABAAABABBBBAABBBBBAAABABB", "AAAABABBBBBABBBAABABBBBBABABBBBAAABBBABBBABABBBABA", "ABAAAAAAABAABAABBBBBBAABABAABAAAABBBBABBBBBAABAAAA", "ABABAAABABBAABABBBABBBABBAABABAABBABAABAABAABBBBBA", "BBBBBBBBABBBBBABAABABBABAAAABAAAABBBBAABAAABAAAAAA", "ABBABBAAABAABABAAAAABAAAAABBABAAABBBABABABABBBABBA", "ABABBBBAAABABABABBABBABBBABABABABAABBAABBAAABAAABA", "AABBBBBBBAABBBBAAAABAAAAABBABBBAAAAABBAAABABABABBB", "AAAABAAAABABAABBBBBAAABBBBBBABABBABAAABAABABBBABBB", "ABBABBBAABAAAAABAAABABAAAAAAABAAABBABAAAAAABABBBAB", "BBBABBABAABBBAAABAAAABBBBAAABBBABABAABAABABBAABABB", "BABBBAABBAABABAABBAABABBABBBBBBBAABABABBAABAAAAAAA", "BABBAAAAABBBBAABBAAAAAAAAAAABBBAAABBAAABBABABABABB", "BABBABBBBABBABBABABBAAABABAABBBBBBABBABAABAAAAAABB", "BBBABAABBBBBAAAAABABABABAABBABAABAAAABABAAABABBBBB", "AABABAAAABABBBBBAABAB"};
        String[] allC = {"BAAAABBBBBAABAAAAABBBBAABABABBAAABABABBBBABAAAABAA", "BBBABBBBABBAAAABBABBBABAABBBABAAABABABBBAABAAAAAAB", "ABBBBBBAABAAAAAAAAAAABBAABABBAABABABABBABAABAAB"};
        assertEquals(1435, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case26() {
        String[] allA = {  };
        String[] allB = {  };
        String[] allC = {  };
        assertEquals(0, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case27() {
        String[] allA = {  };
        String[] allB = {  };
        String[] allC = {  };
        assertEquals(0, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case28() {
        String[] allA = {  };
        String[] allB = {  };
        String[] allC = {  };
        assertEquals(0, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case40() {
        String[] allA = { "ABCABDEGAXAHDJBAAHFJDXBB", "ABHFHCDALFDJDBBA", "BABBAXAXXX" };
        String[] allB = { "ABLOCBAXBAHAJDXBIJKA", "JBABCDAHKFIUDALPJAH", "AABACX" };
        String[] allC = { "AXBADXBBAB", "CDD" };
        assertEquals(23, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case41() {
        String[] allA = { "AAABACADAEAFAGAHAIAJAKALAMANAOAPAQARASATAUAVAWAXAY", "AZA" };
        String[] allB = { "AAABACADAEAFAGAHAIAJAKALAMANAOAPAQARASATAUAVAWAXAY", "AZA" };
        String[] allC = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ" };
        assertEquals(29, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case42() {
        String[] allA = { "BABBCBDBBEBFBGBHBIBJBKBLBMBNBOBPBQBRBSBTBUBVBWBXBY", "BZB" };
        String[] allB = { "AAABACADAEAFAGAHAIAJAKALAMANAOAPAQARASATAUAVAWAXAY", "AZA" };
        String[] allC = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ" };
        assertEquals(26, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case43() {
        String[] allA = { "ZAZBZCZDZEZFZGZHZIZJZKZLZMZNZOZPZQZRZSZTZUZVZWZX", "ZYZ" };
        String[] allB = { "ZAZBZCZDZEZFZGZHZIZJZKZLZMZNZOZPZQZRZSZTZUZVZWZX", "ZYZ" };
        String[] allC = { "ABCDEFGHIJKLMNOPQRSTUVWXY" };
        assertEquals(27, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case44() {
        String[] allA = { "ZYX" };
        String[] allB = { "XYZ" };
        String[] allC = { "XYZ" };
        assertEquals(0, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case45() {
        String[] allA = { "ZYX" };
        String[] allB = { "XYZ" };
        String[] allC = { "X" };
        assertEquals(1, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case46() {
        String[] allA = { "ABXBA" };
        String[] allB = { "BAXAB" };
        String[] allC = { "X" };
        assertEquals(3, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case47() {
        String[] allA = { "BAX" };
        String[] allB = { "ABX" };
        String[] allC = { "X" };
        assertEquals(2, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case48() {
        String[] allA = { "XAB" };
        String[] allB = { "XBA" };
        String[] allC = { "X" };
        assertEquals(2, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case49() {
        String[] allA = { "ABCX" };
        String[] allB = { "XABC" };
        String[] allC = { "X" };
        assertEquals(1, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case50() {
        String[] allA = { "XABCDEY" };
        String[] allB = { "XEDCBAY" };
        String[] allC = { "XY" };
        assertEquals(2, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case51() {
        String[] allA = { "YABCDEX" };
        String[] allB = { "XEDCBAY" };
        String[] allC = { "XY" };
        assertEquals(0, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case52() {
        String[] allA = { "ABCABDEGAXAHDJBAAHFJDXBB", "ABHFHCDALFDJDBBA", "BABBAXAXXX" };
        String[] allB = { "ABLOCBAXBAHAJDXBIJKA", "JBABCDAHKFIUDALPJAH", "AABACX" };
        String[] allC = { "AXBADXBBAB", "CDD" };
        assertEquals(23, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case53() {
        String[] allA = { "ABCDE" };
        String[] allB = { "CDEAB" };
        String[] allC = { "B" };
        assertEquals(2, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case54() {
        String[] allA = { "XYZAXXBXXAXXBXYZ" };
        String[] allB = { "XYZXXAXXBXXXYZ" };
        String[] allC = { "AB" };
        assertEquals(10, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case55() {
        String[] allA = { "UIRTEAYXX", "YBCDEFGHIJK", "AEFGYAUUUU" };
        String[] allB = { "POWYQBDAYAYA", "BCDEFGHIJ", "AYAEFGYA", "XXXX" };
        String[] allC = { "AYA" };
        assertEquals(15, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case56() {
        String[] allA = { "XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY", "XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY", "XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY", "XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY", "XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY" };
        String[] allB = { "XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY", "XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY", "XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY", "XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY", "XYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXY" };
        String[] allC = { "XY" };
        assertEquals(230, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case58() {
        String[] allA = { "AAAACDBBBBBCE" };
        String[] allB = { "CAAAACDBBBBBE" };
        String[] allC = { "CE" };
        assertEquals(6, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case59() {
        String[] allA = { "ABCABDEGAXAHDJBAAHFJDXBB", "ABHFHCDALFDJDBBA", "BABBAXAXXXCAAAABC" };
        String[] allB = { "ABLOCBAXBAHAJDXBIJKA", "JBABCDAHKFIUDALPJAH", "AABACXCAAABCASD" };
        String[] allC = { "AXBADXBBAB", "CDDC" };
        assertEquals(23, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case60() {
        String[] allA = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
        String[] allB = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
        String[] allC = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
        assertEquals(196, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case61() {
        String[] allA = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
        String[] allB = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
        String[] allC = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
        assertEquals(500, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case62() {
        String[] allA = { "ABCDBAXBZZBBCC", "A", "Z", "AA", "BBBBBBBBBBBBBBBBBBB" };
        String[] allB = { "ACDXBABABXXC", "ZZZZBBBB", "ZZZZZBBBBBBB", "ZZZZZZZZZZZZZZZZZZZZZ" };
        String[] allC = { "AB" };
        assertEquals(20, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case63() {
        String[] allA = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
        String[] allB = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
        String[] allC = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
        assertEquals(450, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case64() {
        String[] allA = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD" };
        String[] allB = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD" };
        String[] allC = { "ABCD" };
        assertEquals(102, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case65() {
        String[] allA = { "CBBD" };
        String[] allB = { "CBBD" };
        String[] allC = { "CD" };
        assertEquals(2, winterandreindeers.getNumber(allA, allB, allC));
    }

    @Test
    public void case69() {
        String[] allA = { "AABBAABB" };
        String[] allB = { "AAAA", "B" };
        String[] allC = { "AB" };
        assertEquals(5, winterandreindeers.getNumber(allA, allB, allC));
    }

}
