package topc.test.search;

import junit.framework.*;
import org.junit.Test;
import static org.junit.Assert.*;
import topc.search.*;

public class GemsTest {
  Gems gems = new Gems();

  @Test
  public void case1() {
    String[] board = { "ABC", "ABC", "BAD" };
    assertEquals(1, gems.numMoves(board));
  }

  @Test
  public void case2() {
    String[] board = { "ABB", "BAA", "ABB" };
    assertEquals(3, gems.numMoves(board));
  }

  @Test
  public void case3() {
    String[] board = { "ABA", "BAB", "ABA" };
    assertEquals(4, gems.numMoves(board));
  }

  @Test
  public void case4() {
    String[] board = { "ABC", "DEF", "GHI" };
    assertEquals(0, gems.numMoves(board));
  }

  @Test
  public void case5() {
    String[] board = { "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA" };
    assertEquals(4704, gems.numMoves(board));
  }

  @Test
  public void case6() {
    String[] board = { "JGBBDTGRERJIJRGATPHTJA", "FHGAQQAERQYDQGEEJEDCFF", "EHQYJCPTQFDIYYAHDPETPI", "HCPJDFTEJECCRJAJPBPEDQ" };
    assertEquals(4, gems.numMoves(board));
  }

  @Test
  public void case7() {
    String[] board = { "QKGQHGUVFKGJVUJQVHV", "FXQGXUVKQJKKVFJXJFU", "GXGXUVGXUQHUQXQGHVH", "UFVGHKQHVFKFVUQJKKQ", "QHXHJVJXVXKUHJJXJJF", "HGFJJUXKJKGHFXVVKKF", "VJUXQJUQFHFUVKFUHJH", "UVUKGJJUJQHQKXGJQKX", "XUVVXKHKFVHXJHJGUKF", "JHFFJQJVGGFQVVQFQGV", "UKJJQXUJUUKQJJHQHQJ", "JXQXGHVVXHHVHHGKJXQ", "UJJGHFKUGUVQQJJVVKF", "HGQQXVUGGXXHKKVFKGQ", "JHUQJVUKUFGKQUXVUUK", "XFQXHUQVHUKHKXQHJKU", "HGJVJGXVJXXKHHXFGHK", "XQHHGGXJGQQVKFKFUQG", "UQHJGVGQVFJVUKQXQXX", "GGQHXKXQFUFFVXFVUUQ" };
    assertEquals(57, gems.numMoves(board));
  }

  @Test
  public void case8() {
    String[] board = { "XNUPPEXPUUPAWALXNAPTPNUAEXUPA", "ANWTXWXWEUMMLNUMLWXUMXNEWWPXU", "TAMALXUMLNWTUALEEWTTLLEAAPWXL", "TTXUPLLTULUANNWWTEUTTLAMAPWEX", "NMUPTTNLUUPXUTWTLXTLUNXPPNXXE", "MATMUTXXWEUUAMTPLNTPTLTUNMNNA", "PLENLXXUTUNEEAWWTMLTAAXXEPLEW", "MELWTTMPAULTUALAEUAPEXWMLTPWU", "NLAPPUMAUNETXEAUTMWUMNLMWELNM", "LWEXMLANXNXALXPNWWXAMWTUAULEN", "XUNXXWMNLALXNLNAXWWXPNTXNUTTM", "UEATWELPXAUMNXUXEATPMWXLANWMM", "LMNUPUAWXUMPTAELNXEXMUPMUXNLA", "ELANAETTMAPNUTPAELUUNAWLPPUUM", "LMAUNETMWUWEPTEXAXTWLELAPNXML", "AWUXWXAPUWPUTUMXTXPPMXUXTTLNX", "UXPMXTANPPWAEPWWLNMTUNUXAAPXW", "MEWWEXLENMPTMUEUPELMATXMANENL", "PNWLUMNWXTXALMWNWNEPXXTWEAWLX", "UAXPPTNTLMEATXTEXLELTENEPUWWT", "XXNNMXPTNXAXPMXWLWWLXWNWATUWX", "WWUWTEXLMLUTTAELPMXPMTUNLPTLA", "UEAALTWNXPLNUULEELMMPAEMNMNLN", "MNTLUPAAULPMPNUEUXTLATEXNLPUU", "TNXLAUNNUWEWMNWXUETPXNAUTXWPP", "UTEUTEMUENNENTNNPNNLNPTWXAPWM", "NAUAUXAELPWEPNPEWWPENLXWUNMLU", "PNUWLUPALUXXNTUTAULXPMEPPEXMX", "TNLWEPNWXTNMNWPWEUAPMXEWPUEEN", "UWEPTTUENTNXTNMAATEWULAXNTXLP", "MTUENPLUTAUMLWETLEMTAANUENXXP", "EUAPEAEAEEUPANPEXTMLWEALAUNTN", "NPUPXLWMWXAMWAENTUEMXXMWUMUTT", "EUTXAAEMAUTAPPAWTLXTPUPNPWWLW", "LEUMXEXPTPUMUWMXNTLMWWELXNNUL", "PTNMXPTEEMPPXMLEENUXUANMWWMTP", "AXLXMTNXEPMUPANXPPNMUUMANAXAP", "MNUNUWXLMUUPXNUAXNAATTLNUXMMN", "TWNAEPXUATPAPWNWLTEMUAWMXNTXM" };
    assertEquals(147, gems.numMoves(board));
  }

  @Test
  public void case9() {
    String[] board = { "LAPONLLNLBPAPPBBAALNBOOLLNBLBBAPPBBAPLBNBPNNPLNBP", "PNLBNBPNBLLPALNOLNNBNNPPNABNOBNLNLPOOBPLLPPLPAAOB", "OBOBAPNALAPLNLLNNLPLOOLLNBAPBLONBPBPPLLPPNBNANNOP", "AOOPAOOPABONBPLBAOLAPNLAANNLLNANNLBAPLBLBPBNAPALL", "ONPNPPLPALOBOONLLPOPLAABPNLLNNBPPLLOBPBLOALBOALBN", "BLOBLNPAOPALBNNOPNBPAONBBAAOBAOALNAPBPNNBONALAAOB", "OABLAPPNLOAPNALNLAAOOLPONLLALLNLOBPNNONOPNAANOONA", "OBAAONBNLBOBLLBPOONBBLANNBOOAALPPOBNPBPLBNLNAOPNB", "BPPBAAPANNLALAALBPAPLALLANBBOBPPNPPBPABNLABPPLALO", "NPLNOOANALOPBNPPOBLAPPOLALBPAPBNAANNBBLBOONBPLAPN", "NAOALLPOBLAOPLNBLNANBOPPBNABANOLOALLOOANBOBBOPOAP", "POAOLBPPBBOAPLPLPNLOAPAPOLLPOPNBALNNLOBLNNLAPLNLB", "LPBONLBAAOOAANBNLLPNPLOOLBNPOOBBPNBOLPLOOBAABLPNA", "BOLBNABBABLLOABAOOLAAOPBBLPNPBBPNPBBNLBANNPLBOBOB", "AOPOPLNPNOOBAANANPPBNLOPBNNPPLAAOOPAOPAPOALBLOLLB", "LLPOOLLALLNAONPPBOAPPBLBLLPBBOBLLONNOBAPNPNOBLBBA", "PLNBPABBLLBAOOPBPOOLOPNONLBOAPLALLNOPNBAOOBAOPNPP", "BNPLLOBANNLPABBABNBLNPNNOBBAPLNANOOLABALPONLNBLNB", "NBPOOLNBOPNAOAOALBNNPNOLLANLNLBBAAOPLABBPPLPAOPNB", "OPAANOOPPBNNAPBONBALBPBPPBANOBLPNAPBABOOLBLBNBLPN", "AAPONOOBNALBLNOPPANBLLNOOLLOPLNBAOOLABLLBPNAOPPNN", "OOLOLNPBAPNOPOBOONBAAPBNPAOOLLOANAONNPPBNNBAPPLLP", "OABLBOBPOAANBONOALAPLLNPLOBLNAAONLPLOOAPBOPPOBNPB", "LABAPPBAPPNAOLPBNAPLLONPOBBABNANOLOPNABPOLONALBLL" };
    assertEquals(368, gems.numMoves(board));
  }

  @Test
  public void case10() {
    String[] board = { "CEQB", "ICBY", "BCWY", "HECW", "QQWC", "IHHQ", "CCYU", "IEUE" };
    assertEquals(3, gems.numMoves(board));
  }

  @Test
  public void case11() {
    String[] board = { "VSFVHHFVFSVSVVFSFFSHSFS", "SSVHHVHSHFSSFHSSFSFSFSS", "VFSFVSHHFFSHSVHFSHSHHFV", "SSVSHSSHVHVFVHFFSHSHFFV", "SFHVFFVSSFVFFSVVHVVFHSF", "VSHHVVHSVSSVHVSVHHVVHFF", "SFFHHVSVVHSSVHHFFSHFVVH", "HVVFSHSVHVHSVHFHFSSVVSH", "SHSVHFVHFVVHHFFSSVSVFVV", "SFFSHSHFSHHFSFVHHSVSFSF", "VVHSFSSVSSVVSSHFSSVFSSF", "HFSFSHVSVSHFHVFVHVHFHVH", "SFVSHSSVFVFSVHSVFVFSFHH", "VHSSHFSHVVSHHVSHSFVSSVF", "SSVFVFVFVSHVSHHVFSSVFFV", "SSVVHSHHFVVFHVFHSFFSFHH" };
    assertEquals(213, gems.numMoves(board));
  }

  @Test
  public void case12() {
    String[] board = { "IFTOHGZQVOYPQNZWEHSBECWVIHJGRJNDMZV", "CBDZMIRTBFWPSFIWBPZQVFCTACLQPWZCALS", "QAICTNZGIIBIPSEHVFCHWJCKHVPYHSTHISX", "MOSPFDNSDQTCSBBKZCJPGFEDBLGBDQOHOJR", "EHPMJPUFPNANVYFRGNSBXANNFABXBTSLMYB", "WMGPXXNURZACYSVBELKDHRPJRHZUAUHCGIY", "FFCVEGJQPWOSEIYFTIWSPSJPXYZOITFBUNT", "QKEUGBQPMAQENRWQSBTHISZUSQYEMYFYTDT", "HRIPSUACVUATMZBXRUIWOPFFCBULOPEKJOG", "VSYKMWPNOKDZCWUMQCXXSYLRQAALLRHWBNC", "LZCMFOBICQGMGNQMCSDNHTLBLFARQNVZWZO", "HCQRGXWVMXVDFZQTHKMOQIEAZDRHCXZTEMY" };
    assertEquals(6, gems.numMoves(board));
  }

  @Test
  public void case13() {
    String[] board = { "MUINOJUJRRUJNNPUJMJMJBBRMMNPJIJIPMNMOJNOUPR", "IPBUBPJIOBJBUPJOIJPJUBJNBBIJIMJINRIMUPNUPNJ", "JNPMNPRNNMPJBRBPPMPUUPBBPJIMORPPBMUPBPMUMUP", "OIJIPRRONUJPMMBIRPOMJJBPIJJRBMUJOINNRMPJJMM", "OBMPBIINMUBIPMMNOONNBBOPOUNUUBMIJNPUBRNNUIO", "BJBROOMBUNINJUBUIMBOJBPNBJIOPINNRNRUJOJRNNB", "NIOONUIMBMORPMMUNRUMMOBONNPRNOJPUPINIIURUOP", "JNNMMRBUPMUPOUPPRMMIMPBJBONBPUJBJUNOUROUUNN", "UMMUOJNNJIMBPMMOMNPUBIJBMORBURPROUIJNIOBNUM", "UPJBJMPPUBUBUBURRIRRIIPIOIBMPBJNJPRUIPBBONO", "BJNBNPBPRMINROMIMPRMPNBMUBJBMNJBURNRJJINRUO", "RMRIMJONMNMMOJPPNOBJNOPROPOURJBBJOPJORIRIJB", "JNMBJPNUBRRBUIOPNRBBPUIPPMNRPRNRBJRMIBNIJOR" };
    assertEquals(89, gems.numMoves(board));
  }

  @Test
  public void case14() {
    String[] board = { "AHQPTJPGTAQVBBLP", "ABQGGSBLBPQOOVOG", "OLVSVHGBSAJABJPP", "QABJHJAQAOSTBQTB", "VVQLLTHJJHBHPHGV", "VHVJVVHBBGQVVBQQ", "ASSQTJSTAPVAPPHV", "AOAGOTVLVQJHAJPV", "GTSATOAGBHQBOATJ", "LHQLPALQBSSBLHGJ", "GAOJBOOPPOPSQJBG", "PHPTAHQJVTOGAHPS", "JOVGBBPTLQPLAGOB", "LOSVJGOQPBHABPGV", "HJTTAAGSHTHPJQTL", "HPPHQGJBJOQTPOQH", "AJVQLOBGOAQQOOJB", "OVPJQTVPGLJSQPLB", "BPSBPBLVSTPQPVVG", "VSLPGPTLQJLOJTJS", "SVGVLOSBTTVHLPJH", "SBSVGBHAGGHSHTQQ", "QJOLVTHJJHQHLSPG", "OTSPSHVPPHBTQBOT", "PPTLTPJTJGOJLJVS", "JTAJBGTSABOJASVO", "LTAVLBJQGGTHPOGO", "PHJGOVHPHOVOJGHJ", "LTPABVQAALHLJGBQ", "HOOVHGJAABOSHAJL", "TVAVVTVOTLAGOVAL", "LHTQSPVGVJGQSHHB", "APQVHOOLPHGVBLVB", "HGAJVSLBJLLPJHGT", "BOVLLPGVOSTBVGVT", "HTAVVTVLBLAAJQQB", "LQOOALPQLPOOLLAJ", "VBVASAATOOJTJQGG", "SHHLPLQHHJBHGVGB", "OGAHOPLJABQOJQBQ", "LOATLBQJBLQTVLVO", "GGPVTBBPSHJPPTOO", "PLLHJHSOHAGASASJ", "VTVSLABLJAJLVHPB", "TOOPLBOHHSTSTLAB", "LSJGQSAOGOPOAOVO", "TJSQGABGGJGBOABS" };
    assertEquals(45, gems.numMoves(board));
  }

  @Test
  public void case15() {
    String[] board = { "DFFAEAHCICGEIEHIAFEGFFCFGZDGZMKMMFGII", "FAKGGIKMCZFMEHAZAGEHCHFGZZKMZAEFHGZAM", "HEADGIZFAZGDEZGCGIDMHGHKDGMIDHMHKKFZC", "HFIGMCMZZKDCZZIKGKAEGZAZAZIIKCIEDFMAZ", "ECMEGKMIGFDFCKDKMKDZDZGECMKCEAIACFHFA", "DCHIGDGHFDIFMCMCDHMCDIIEGMKFHAGDFADEH", "AICDAMIFEHKHAIMEGFFEHKIMGDHKHZGZAMAIK", "HMFGECAMHCIEGKFAAMZAZGZEDFGMCEIMFCFIZ", "FICMDHKAFEEMIACGFDFKCGDICMEDDFIGAAKEA", "CACAMMZZHHCGFEGCGZZAHAFMHFZMHMFHGKAMA", "KDKGHECZDKCDKIAZCEZKACAHKDDIZKDFHAMDZ", "MFKEKCGCFIEHEHDEEIKEZEFHAHEIGMGDCKGHG", "IIHFHAKKCFKZIZEMZAZDGEFZAIIKHGZHAAEEH", "ZEHDKGIHEKEGFFDEGZMDHIKICGGCKZIHZDHIC", "FDGDZAZMEHEDDHDEEFGGAGAAGHKECMCAHIKIC", "IFAZCHADFHGGDZAMZCZGDAEFMHCZCACEDGGHH", "ZDFEMGEKFZDCEDGHZAIKHHIFAIGAKAEKEGIMK", "DCMIAIIMIGMEAKAHHCGFCDIGZIIZHKAKCZFDI", "CFACMZMHMGIHKIZDKHKEHKAAICAEMGIEEMFHD", "KFEGKADKZKEGKAMMAIAKHDMHAECGEEKADZKGD", "KMCGECDCGGMIEKCEAMEZEDKMDEEFKFMFZKGEZ", "MMCZKHIMIKEIEGMDKDFZGIFEFHHKHHCCDDKDH", "DZAZIMHFIIMHHCGHEZIKDAKMHADZKMZCFGGZF", "HKHEECGZMIMIZEFIEGHFEZKAADEIGGHMACHDA", "KMCHHEFFMFFZDZMFGFIZZGICGEEGMDIEHHAIA", "KECFDGGDCFZZFHAMFIMKCDKZDAGHFZEAHMCAD", "DKFICZZIFIHCIECAAKMHHFMKGCGMAZDAGICHI", "CCGFCFIEHCFHKFHGFEDHCZFADHMHZEMMDFFEZ", "IIACMDDZEDCEEAFDCDIAFIFIHACHZGICAFZEH", "DCZDGZZFIIHFCZDMKEIEIMKCEGCGGKDKDICGD", "HDICIAGGCACMZHKZEDKDZKKFAAFIZAMHDZFDZ", "ZGKZKCMDEGFAHCMGMHFGECAZMEEHMKFIMCKGK", "MACHGFGMIGHEKEHDKAMZZCAEEGZFDECKCHEAE", "ZEIFAAZAGCEAGAKMZMCDEFEMKZGHDDMZCGDGK", "ZGFFMIIHGACEAFFDDZZEEAKMZHGDMZHZFZICC" };
    assertEquals(127, gems.numMoves(board));
  }

  @Test
  public void case16() {
    String[] board = { "QYFDRFVUNNXYEPHWYKTSGFEFQPCUJPQLKLZLOYNJUJJWJUHO", "GKAGHGTBIHHJTOAXPYTYPNOFWFDIZEKAIPSOZKKIUPOLLZNL", "OFSOMLDVLBHMYTUKMIPVTNDWFMYETSAAMGZQQCESBMUXPZTJ", "RHCAIXPDFUYWEXGSBQHSGRCTBBEOZJLSXJQYXZZDWUGWVBNE", "EVLNJDFEUKNFYAFADXOCUXDQLMVAGSZOSCSWZBWOAWMNIWDX", "DYESCBDMMBHPHRFVYDHMGISZIXJZTNBOSRSGETDXGZAQDLZV", "UNQQWTHUUVUOEQWXULLKMFFXAUXIGVDUOEFSZTUPALFBBIMC", "AXSUJABSGWSXZOPQXQPGWBGBKYSMLTYTLCLQEGZDXLOETNUR", "CBEAUGBUCQRZMPWNWPLWBHLTHFGZLZMTWHNNBYCZRUVVHPAD", "FHJSWCCPXWPQXEIQVMRZQUUXEEFMDVTHAOEHDTQAKJXBCNKF", "VHRJNIPGQITWSHXRLVSRLFNLTUQLGCPWLAUWVPIIFAXXTEAC", "SGGZUUBQWSMUIWWFTTUTDGSSGFDAJKNMOINZDTHETZKBOUAY", "BNZPTOGHQZOXMZKXPRRCCPROGMOCRLDRWOOSVTZNBVAQXRII", "LNFAKJTWZEBFZXHQKMSSHMRLSNEUASDIKJJDFZGFYKMNTUTN", "OSHAZBPFOMBFNOWNUIRVKYYIPYRXKGACNASPBMSOFYWWRBZD", "ZYZCEQVIUZJOIVGTKUCZJPVUYLTKUMHOSFAJVSEPZEPTKDQB", "GLDPQWIPIZJAHZOSMDUASBSFDOSQSDAMLBHTXQAHSCNLGMOQ", "EOTDFGXWDRAMKCCDXALIEAZDEXUNSJSXLIXOVFZAVHWQUDEP", "VSSOITJHERBLMQNTTILYCUOANGAZOIEUGCXAIQVOKQPFQQHJ", "JCYQFGCNBISZNFCRBBPMSMIFZXHVMJOQDIMPPXDNGEAMRZLH", "SUUJXDXSPUYKJZHLDGZPCWYGMDLPPDPZOHWUUCOCBULKLYLH", "WWGGBYEKTPXEWWZBFGADUMUJMHJDIFKPRKQSWDZBEINVCGBB" };
    assertEquals(20, gems.numMoves(board));
  }

  @Test
  public void case17() {
    String[] board = { "CQQOC", "COJDC", "DQDCJ", "DOJJO", "JQCDO", "JQDOJ", "DCQOC", "ODODD", "QDQCJ", "QJOOC", "JQDDJ", "QJOOQ", "OOQJC", "ODCJQ", "QJJQJ", "OQJCO", "DOQOD", "ODCCQ", "CJDOQ", "DCJDC", "OJCJC", "OJCQQ", "JCOJQ", "DOQQJ", "OQDQQ", "OQCOQ", "QCCQO", "QJJCC", "ODQQC", "CQCDJ", "CJJDJ", "QODCO", "JOCQJ", "OJCCJ", "ODOJQ", "DDJCD", "CQDQQ", "DOCOJ", "JODCJ", "CDDCC", "QDCQQ", "JJQJJ", "JQJDQ", "DCCDJ", "CJDJO", "DQQOQ", "DJCJD", "JJDDO", "CCJOC" };
    assertEquals(71, gems.numMoves(board));
  }

  @Test
  public void case18() {
    String[] board = { "MCCPQTSAONEMDUOKQPBDEKCPMMPT", "JJDQRRSKOONSELRMRDJCTNPUKOCC", "MCJDERKSCRAKJEOSMRAOCKPQADRU", "OTOEUCAUQKDPSMNQEQRSMDOADRRO", "TUNDSDQOEEUMDOTCATRBPNDCCODM", "REQEMPCNKPDUQUQUSQBOPJPSSQDL", "EPMLSMOLJQQJNKPOCAKDMJSUEOJS", "PACCLKULQCEOSRCPOAQBTLLRDTAK", "PTDDPQPRSOEPCRROJMUQNRLEKROP", "LTSTOQQSDKLPOJEPPBMNDBQJBRND", "LQTEPPSLBAKJMDBJQLLSSOKCSQPL", "AAEETRABNSOJCOQJQBJMKOEMTEEU", "BMNDSKMNPSODUPKCJPSJAPTTATTB", "AKDLTERCDNDSNEDMRNALABLLNNAA", "DRSATKPTEASEQCJBDTKJPDDQJLDN", "CMEQNSQTKRKANUMBMJEBMAABURNN", "ASKBKRLQCOPUNDSLNBQNCQQUUMUR", "JLKROTJSODMEONTQBEQNQKQBECQT", "BLLUTNMASCESTBKUQKPJRUMTSUSO", "RURUSDUTCJCOATQJMUQMUQPJLJOB", "BCPDDAKROBEARQKUONLRAOSOPNPD", "QRMMQEKEOAOSBUEADDAPECNONEND", "JOESJAQLRQLLBOENBAUSQQDSPNMC", "OSCKCPUTUPTUQPUAALASTBNDBPTB", "LTPSDETNCSTCLTPEQQDPPQASRPTU", "UPCRPPUDLPQCAOTSASTRRJDDBLPQ", "KJKOBUENCDANKKMSCCTBKPTUMOQE", "SCNQDSDCUPPSQMBJLNRJNQDKMDOK" };
    assertEquals(32, gems.numMoves(board));
  }

  @Test
  public void case19() {
    String[] board = { "IBBXBXXIX", "IBHXBXHHA", "BIBHAAIHA", "HBIHXHBAB", "XIHAHIXHX", "HBAHBBHIH", "AXIXBBAHA", "BXXBIHHXH", "AAHXAIXXH", "IXBXABIIB", "IIBIHXHAA", "XBIIBBHBB", "XAIAABXAX", "IIXAIHXII" };
    assertEquals(44, gems.numMoves(board));
  }

  @Test
  public void case20() {
    String[] board = { "XJHXZJVHWXW", "WJXZGWXXIHJ", "WWJGWXWIXXI", "IIXVZFFJWFW", "WFXIJWVZIIG", "FWZHWVJVJHG", "GXWHFZXHHGF", "IWHZVIVWJJZ", "VIZWVZVVGHF", "WXHGGZWVHIV", "HJZGIWXGIIX", "VZFJFWJVVZJ", "WVVGXIZIJVI", "VJIIVWHJHFW", "HJJZVIVGXXV", "VVZHZZWFHJV", "VHHIGFHZXFX", "JHJXJZXZFHG", "VXXFZFHHXHG", "WFWWGHIJIGF", "GHVHXGXJZGX", "ZXGGFHJVVJW", "VIGXIXXJHHZ", "JHHFZGXFZFW", "XZGJXIFXXFW", "FJFWIIHWHWI", "ZGWJHFVHJIJ", "HXWJGXXGJGH", "JVIZIIFZVZI", "JWZXVWGXWIH", "XGJIJVVXIHJ", "VHIWXZWHIWG", "FGVHZXWGGHH", "ZIZWVHIXVHF" };
    assertEquals(50, gems.numMoves(board));
  }

  @Test
  public void case21() {
    String[] board = { "ZWELUENEUKBKKZFATCNH", "FYLNSBAVGCTKUCTGTENT", "RUATRTRNCAGRUYBCZLYS", "YNLBERFZHFGFRRBQRZTR", "ERCELZQRGZCKWCHHSTZZ", "HKBAHRYHNHHZKKQZRRUB", "KKRHGGEVRCTHYUSQQWNK", "FLTNBRNYFRBWKTZVKEFC", "LABHYVGEGHQCCLZSNTES", "CSWLZLZHATWCZAUKSRFY", "BBSTEVCVSFGEYKYSNKQC", "WZEUWANKCEASACWBRLCE", "NGWHNTAGLHQFSRNTUGSL", "SFWCRCHRHWRZSQKKZBBZ", "HKGGRSFLUGRRQVEBVAGR", "RSWVYYABGQVYSSHBWSFQ", "WZKBCZGKEBLZKTZTWBAG", "LUVAECWAQLAEWTQRBGKT", "FESGYRWGLYRLEGAKVNVK", "LGHGBGNCZUZQNKZUZBEB", "WNFVYCBCLLTBSKENVKRS", "CURSSACQVRANRCZGCLRY", "CQEBLAVHTNZZNSFVKFHH", "ZVGCNSBRBAVCZVLFLHYK", "UHFEEZKYFNEHCUVNWHUZ", "CQFZHVKKEWAYBLWCZFGE", "BVUBBNCSSYYSBLTWNRQW", "ZRYRSNHWZCSUTGUVAAUA", "RTCFHZFSVEYUTRCUURLC", "UQTNECQVUCGKUWNNKBNK", "NGCNATSSNFKYYVHGNHRK" };
    assertEquals(22, gems.numMoves(board));
  }

  @Test
  public void case22() {
    String[] board = { "IPTKRLYOPRTILQTZRVYTKKPQOTOZ", "LLNTNNZZVTOOVOQVJLPNZBBQYBRJ", "YQJPNQNZPPLJVRBTNROPIJRIQBJZ", "VNPYLJZJZRLVNLYZYRBITVTRVPVO", "PPVYZNIPJPOLQOOTJNJIYPVBRVLR", "RYYOBTQJOIZNPKZPOQYPQLBVZZIV", "JIRVBQVJRZPNPKVIKNINOPBPZQOK", "ORQOPYRKNZQTNNTZNYKZPNTJBVYB", "TRTBLNYZQTYQBTYOROIOTNNQNYQP", "JJPVILBNNIOYNBBTYRVJPVNJRZPK", "QTKZJNTPJIOLTOLZVIPVJRLTVOZL", "QZOTLBBLTBVIKLONZZOYZTIQVTKY", "LPKVORRQQIRPVOIPTZVLLIRVPZBL", "LJVILQLJLNVPBLJKNKQYYBKNVZQT", "OKRYTIPIYKVJBYJJZIQIBKPTLKRN", "NNYKKYBVBIJTYRBPZZVOBQOBTJIV", "OZVQBITVKVKPRZBZIYTVZILZZVIT", "LKYTVYKKRIJPYTQYRYJTLQVRZIRT", "PNQIPYVOTLIBQBPKNVZVIZNVIOQR", "ZIPJPIVRRZPKZBBVNQRJJQIPIJLT", "LLBIOVJLPNKZOKKYBORQJJRJKNOT", "VKPYTKBTLBJVNNYBLVKKIBBKYOLQ", "NZBYZYZRQPPRNRQRQPZQVPIPYOIN", "NIKIIRYRVIBKINOQOOZVOIVLIQNY", "TBIPYYBQPJPRZPRKNLJIYKLOIYYR", "IKOPBVJBJTYBKZIKIPJVNINLPKOY", "BTJTQOIQZOKQBRPOQINNZLYLJZIY", "BYTINNRPYZQKJQYBZOQTKKOOTTVR", "TKTRJORJBVRYOVLIYYVRYOQYNQIQ", "IVPNYPJLBYYPPZZOQYBNLZRIKNYP", "VQRLBIIVZZKBOLKIIPJNJLQOLIZO", "YNQBIVYKOQYJNKJQLOZZKBLIRLPT", "ROJNTOOLTRRTZZBIYRYTJNTNIKBQ", "YVNVJZNQOKVQBNZZVVIYBLVJJYPI", "VVRNQYBKQLJPOKPRYONOQIYLLQIJ", "IRTVOBJBNRINPNPJVKJRIRRJPLPJ" };
    assertEquals(73, gems.numMoves(board));
  }

  @Test
  public void case23() {
    String[] board = { "TDTIVQWMMITDTTMZAZGAADDMI", "ITXZTVVXXSAXVDSVVTSDXXVQA", "VIGMTGMDTTXXTIZMVDZVGZWXI", "VZISVSXGXGAWDMZIIATSQDZDM", "WWSSMGVDXTXQZGTXITGGAQVDQ", "ISADVMSGAZXSQMQMTWAGSGITQ", "QSWSGVTQAVMGZIAWSXVMTAZVZ", "DMQTZXXDWMIXDMWMAQQVTVMVA", "ITXTISGVMDMTIDQATWQGXZIDG", "MWTGAITWIZXWGXWIVGXXIXVVT", "MAQGIVVTMTGGDDIDGMZXASITV" };
    assertEquals(20, gems.numMoves(board));
  }

  @Test
  public void case24() {
    String[] board = { "NMUREHIMWYNNLSEWLRGUSGNGHR", "EHHTWEQULNLBPYLQIBRNIIRWMM", "QTHOEHYYBQANBPLMYQMEHIOMYO", "RONUSSHNMOVUPOBUZLTOPMVRYU", "UZGQVIZLRHAQLRAZAGOGZOOMLG", "VGUVGIOUNSPNUERQUVUZTOAPLY", "WZUYTOGHIMAYRHRNQANMNYPNAP", "YMRRUVEVEPYQEHGONTNYWAWPMY", "IUNGOBISEQUUTUYHRWAVMWZATY", "QNTEBINIULNRMMEGZVNLIVLPPS", "LTEMIVAPMYVLHBTQYULAVSQYOT", "GQOTPVTUBWSUEOUMWOEGRMMPZB", "SGPQIWIAYVSIWLVQAWSTWBGWUT", "MYGIYWGBVNRSAQORATOBYBSWNG", "PWVNMQMGUQWZTYRRZLUEYZGUBH" };
    assertEquals(12, gems.numMoves(board));
  }

  @Test
  public void case25() {
    String[] board = { "QXPEBOZWWDTLESIPLDFB", "XTZFONPFVCAQORNOLFND", "MOIZNDIPOTQJDUZOQRAM", "HJRMOEXWHJSQXHOAAFUF", "KIURMCROQUXTZWQHONAW", "DNAJKRDASEMTZHIHQKBM", "WUQFKBWHNCRQTXUBHSBS", "TBGEDMFLAPKBOJDNZCQJ", "QRITZUQOZVNPLEJNTIDF", "NGKBKFNVHKOQJXFECEUP", "GNCSGALKZQJZPAEMBMUG", "LRIOTZLCCQTTCBFREIET", "ZEXLGBDPWRJNNZMRFXHX", "GXPSDTZKOBTXAQXPUZUE", "HWLMLTGVUEWSGVQJRVJH", "DKCEOVEKHTJWJOKXBLFU", "EDJBWZFLRXGEVHIDTXAL", "ZRXFMAJWINSKOHUBVIZO", "ORNZTMCEPMXLSWAUUNTR", "BPTEKQDNAJWDSJOUFESK", "OORLNHOQZCMKWKDKOGTL", "OIXLWMWHVRIDRVXWAESC", "NQTBXIKFIJSPBSKGIZOG", "OMHLRWRLQJTURZSUGOTG", "RGMHPIZBWZQBSDCNLFSA", "IZDRJGKDXALUSFMQICKW", "CKUXPCSJJIKWEKWZVAVV" };
    assertEquals(10, gems.numMoves(board));
  }

  @Test
  public void case26() {
    String[] board = { "ZQFZZQZFZZQZFFQFQFQZFFQQFZFFZ", "QQZQZQQFQFZQZFFZQFFZQFFQQZQZQ", "QZFZQFQZQFFZQZZQFZQFFZFFQQFQQ", "FQQFQFFZFQFQZZQQFZZQFZQQFFZZF", "QZQZZQQFZQZQQFZFQQZFZQQZFQFQQ", "ZFFZQFFZFFQFFZQZZFFZZQFFQQZFQ", "ZZFQFZFZFFZZQFFQFZQQFZFZQFQZF", "FZZQZQZFQZFFQQZQQFQZZQZQFZQQF", "QFFZFZQZZQQFFQQFZQZQFQQFZFFQZ", "FZFZZFQZZQZZFFZZQQFQZZQQZQFZQ", "QFZQFFZFFZQFQZQQFFZZQZFZQQZQF", "FZZFZZFQQFFZFQFFZFQFZQFQFZQFF", "ZZQZZFFZFZFZFZZFQZQZQQZZQZQFZ" };
    assertEquals(307, gems.numMoves(board));
  }

  @Test
  public void case27() {
    String[] board = { "EGRGOEEI", "QXMINRGE", "MJRIMJQX", "TMXRELLU", "IXTTFUMQ", "QOGMERFJ", "TMIFQRLJ", "RELJRIQI" };
    assertEquals(2, gems.numMoves(board));
  }

  @Test
  public void case28() {
    String[] board = { "PLFQKGPK", "FYSZWOTG", "ZPTZXNTZ", "NTOAYVSP", "PXDFDSXF", "LXWWRXKN", "SDSFUDLE", "DTNFGSES", "LNGKUXLZ", "DGTZMZAA", "SSMGVVZD", "OFPVKYKM", "NGTNYEZN", "SOOSOPXE", "FNNYPOAV", "PKRPOFNE", "NFNEKZMD", "NEKFGNUQ", "ONEXNTNL", "WMRWOROG", "YLDSVFDT", "QMLMUQFZ", "SQAMLFVT", "ORRAQEDV", "TEMGURZM", "UTFXOPPW", "MGEKMFWD", "VKMLOPAD", "NZSETAWL", "XGQWYZQQ", "OKDVQWPL", "NLLFZYON", "XVKVMLGX", "WVTNEOXD", "MXPYNWLD", "NSDDFXKP", "QAEVUMPQ", "OXGLNWRM", "LFLWFXAA", "NPGPUYVW", "UMZFKRZA" };
    assertEquals(7, gems.numMoves(board));
  }

  @Test
  public void case29() {
    String[] board = { "PSDMMOPQIHIMQOMNIWWJJMHWJMSWJIWSWH", "SYODDOHWOYJDJHYSQDOYNNDSNDWWJMYMHN", "SHIQOSIMPOQDDWYHIJONSWYIJDINYMIJDQ", "OJINDWIHMOQWIJPIIYHPOJWNJWNMHNMOQM", "NSDMPYWHMHJOIIDISYHYIHSMPNPHHSMHIP", "NSSDQOHWDINMDDWYMNMWOYMWDIIHDONOQQ", "DYHPOHHIJJWJNMSQQJYWMJOYQYQJDNQWDN", "HIOHIOYYOIOMDHSOHYJOQHIIMOJYWMNPIQ", "DSMNSIIJMNYDHJIDOOPJNHYWOHOJNYOPPW", "QYWDNQPJISNYDSISYSHDIWJHIJONYHIYHD", "MYNOHIODWOWHSNPHSQQNSOWMDNQWIYOJWJ", "HMPPYJIPWYDQWYHIDOWDSSOPQYDNHYPWIH", "YNWNMSWOJIMMDYIQPMOPOSQPYIQJQWQNPW", "PQNNOSDHOJPMIPYOWQHSQPIWYSOIHHWIWQ", "NDHWWHSMDNPQPPNWJMPPOMIHOYQJNIHQYO", "MNQNDDNYIYSHDDPINNOJYSJQQMYSPOSYNO", "JPIIOSMMYQWQPJWSMHPPQDSWIDPNQONISH", "MWNSPIIDPPYONJYNQWDPHJQDDJDHMINYIH", "DONIOHHYHJPNJNPWQONOSMSOYIJHIDHYJM", "JWOHQNQMYNDDPHOQWYWQPDQHODIMHDHOQI", "SNOMNHOJHWSWQDPIQOSMSOYWPIDHNPINMI", "QPJPOWQPOQNPDYHMJMPJDYNNISWMSIOOSW" };
    assertEquals(58, gems.numMoves(board));
  }

  @Test
  public void case30() {
    String[] board = { "RLGGULMULURUZBFUG", "MBURZULMMBGLRRFUZ", "GRRMLFLBFGRURNLZR", "RBFFGLFMNNUUFUUMG", "BUGGMLGBZBMGLGFZF", "ZNLZZRZRGBRUGLBZM", "LMZGMLURNRGRGBMRU", "NRNZGUUBUGNLMFMLZ", "ZMNULUZRNZRGRZBGN", "MGGLRGZULFLZUMBGF", "UZMRBMFFBUBNUNUNZ", "MFUZNFNBZUGMMBBFF", "URULFMMULFGRZUFFU", "MBZZNUZRUNFMRGUGB", "GMMBZUMMRNGMMZBGU", "ZBGZNLUFNMLRRMRMZ", "MGFBRRNGFGGMFGBMN", "MUBGUZBGUMMGZBZZN", "LMNZULNLUBUGRBUZB", "GGBZLFUFZBMRMLURF", "MLGGRUNZGUNZBNZRN", "ZRUFBFNRLNZGGFGNL", "LNUBNGFZRGBBUNLFB", "URBZBMFRMZMMZZRZZ", "MNMRZBLNMRLNFBLBM", "MUBGRURLLZMNLMGZG", "GLUGNFFLGBFMMRUMZ", "RZRMGBZRLNUUGMMFB", "BRFUMFMFZBMRLMLLB", "NLGMZRUNZMMRRLBZU", "BFBRRZBBNFLMUMGBR", "BLRUMRRFZUNMGLBRG", "FFMBFRMLGNUZBGBZR", "FBGFRMNFZBBUUFZZF", "BUBMFZRBMZZGGUUNN", "UFRBGMBFNRNRFZFML", "NGMFUNNZLBZZUFFZZ", "LBMLBBLRGMLUZMRFL", "ZNFUULBNUZMGBZFBF", "ZGLRFNBZLRMNMMBFF", "NFFZMUMMBLRGNFRFZ", "RMGULLFZMNMNUNZLM", "LGMFRZBRNNGUNGNZN", "ZGRRFBFFNRZGGFMLG", "MZBBUNLBBUFZFULBM" };
    assertEquals(126, gems.numMoves(board));
  }

  @Test
  public void case31() {
    String[] board = { "RNMOHVPW", "CKNRWJRG", "DCMJYFEX", "GXFKIKPH", "XZEPKKTV", "UQJSPFAS", "RVOGOENM", "VJRMHAUR", "KFDSXIXU", "EPYFHXBH", "EGYJBYKZ", "VTMDVBTH", "DTICJAXP", "DMEVAAJV", "PQWICIXM", "JVUVNFPP", "JNMOPYTS", "KRINBESO", "OMESFFIA", "TJQFJDTS", "TRVNKYYC", "VNQNIRVX", "SIITAOTO", "AYKVCDEG", "WUBZZJGJ", "MEWUABOP", "QRHROJJP", "TOSWAOPK" };
    assertEquals(5, gems.numMoves(board));
  }

  @Test
  public void case32() {
    String[] board = { "DVFGFPZQ", "LOPFOHXO", "ZMIFGCYW", "WYXLRZDX", "WSKJNSID", "CJRKAOOI", "MPQHFAYH", "CQWCQGMY" };
    assertEquals(3, gems.numMoves(board));
  }

  @Test
  public void case33() {
    String[] board = { "FVVFAAFUSUXSVFAOPOOFOATASFXTTOTA", "PTXFOPVVSPOVSTTSUOPXVSPAPVVSTATA", "VPATXATFOTSPFXTXVUPOVTVSTVAPXAOV", "UXVSUAAXUPAFVPSPVSOSFVVFSFUAXFSX", "AOSFTOTPOSVSPFUOTOUXUUSXPVUXPSXS", "TXPPAOUUFUUSXUOXSTTPPUPPSPFXOOAF", "PSOAPATTUPSVTFOVVAXXOFUUTXOUVSUA", "TVUASOFOPSTSVFXSUAXSVUVVFVAXFUTS", "SSVUVAUTXVTFAXUTVPTOXSSAFSPSOXAS", "TTXUSVXPFVPFVSVXXTFVASPUUTVTOUFP", "VTSPFOUOPTTOVOXTPOOPATSSOTASUTUX", "OPPVXXPTXUUTPOOXTFXPPOVFTOOFFTOT", "UATFXTXPPVSXATOFTTXFTSOPPSFFAXUS", "XASVVSXUAUXPTOAUAVOFVSFTUTOUFXSX", "AVAUPTOXAATOFAPOOUFAFVTFATSPVOUU", "SPFSAOFFUOVUUTPXOSXFFSPXXAXFAFFX", "FUXPPXPTTSAPSUXOTOSVSXAOXAPTOOSX", "VTSASFOXOTVVOTFFVXSAXVFOOPPVOFFO", "SOUXUTPUAVTXSOXUTOUSXUXSVPAPXVVF", "FFVSXSSUVOOFUFFVFVVSATPTVTXUOUPA", "OPPASAFOFFVVXSVOTXPOOUFFUUVPPOFA", "AFOOTFPSUFFATPVPPSVSFPUATUOVUAPF", "SSPOFAPSTUVTUUFFPVOOUAATSOFFTVXS", "PUOPASOAUTOTPAVOUTTFSATFTUFATTFT", "FXXPVTTUOFVAFTPXAUFFSFOXVOUFAXTO", "TVXXOTAFAOVPOTAVVASOPTOUSUUFPTXS", "UXVPTSASFXOUVXSUSAVUXOUTTXAUPXVX", "FAPFPUPPATSUAFPUSTPTOPVAXAFOOPSX", "FTOXTSAVAUFVSAOXOAXSTTXTSFAXVVSP", "OVOXSVSXVXTOSFTFVFPPTFUFTPTSXXUU", "FASPUUAUUVSSVSUAFXOUATOSVSAUUXUX", "TAVVAUSAOSSAUOSUTVFXFUFUTTPTSOXU", "OFFXTTAAXPPVPOXTFXOPOTUSSXFFPVPT", "PUXAFTVFAAFXOPAPUSUSPASAPVPPVPXU", "TTXVUOTFXFXTPVXFOTVVOASPVTOOVTPF" };
    assertEquals(184, gems.numMoves(board));
  }

  @Test
  public void case34() {
    String[] board = { "UUKSUUKSUUKKU", "KUKKUUKKUSSUU", "KSUKSSUUSUUSS", "SKUSSKUUSUUSS", "SKSKKUKKUKKUU", "USSKSUKUUSSKK", "SUKUKKUSKUKSK", "UKSUUSUUKKUUS", "SUKSKKSSUUSKU", "UKSUSSKSUSKKU", "SSUSSKUKSUKSK", "SUKUKSKSKKUKU", "USKUKKUUSSKUS", "KKSKSSKSUUSUU", "KKSUSKUSUSKKS", "SUKSKKUKSKKSU", "UUSUKUSUUSUKU", "SKKUSKSSKSSKS", "SUKSUUKKSKSUK", "UUSKKSSKUKKUU", "SKUKSKSSKUKSU", "USUUKUUKSSUKS", "USKUKSSKKUUSS", "SKSSUKUUSKKSK", "USSUSSKUKSUUK", "SKKUSKKSKSSKS", "SSKSKUUSSKKUS", "USSKSUKUSKUSU", "SUUKSSKUKSUUS", "KSUUKUUSUSKKS", "SUKUSKSUSUUSU", "SUKSUUKKUKUUS", "KSUSKKUKKUSKS", "KKSKUKUUSKUKU", "USUUSSKUSKKSK", "SUSUSKKSKUSKK", "SKKSKKUUSSKUU" };
    assertEquals(369, gems.numMoves(board));
  }

  @Test
  public void case35() {
    String[] board = { "DIXXIJRTFLMCXAVLZQMQUQOBUGDMKVANZJERD", "RUZSUQMVRZOLMDYNPPQWYVPGNIKXOAPNYKFMW", "GPTDICVLVRGCXUOQUTHYAQCUAUAOWTLQNNJOH", "ISWPKUKQTISTTCWWVGBTRBXENVZTWVLWVPOZH", "HUOZOJUZRQLNMBHSXDWXAPPKBDGGUKQLEEYGR", "TZVHOVANYJFFQBOSWHKFCIROFZKXJSHWQCXKN", "AZDIQZPPZQNVIIZVXVYHXYJJEHEKQLBGUEEPX", "MCOCMSMHJKONKPLEETEFFRHXIMOSMHSZTWTSP", "DZTLTBAUZWOJLMWCUIOQYHPXBJRZOSMDTWUUZ", "UDVNGJROJXLMXDZAOWVZLVGUSVEOUNOKDPQJR", "QUMOKYAGGUDTMSEJIMNTTBJYLSGOQLYCMXIZD", "BPCMSHJDFKQOQULNUXXVGUBTSNKDHBNVGDOGE", "XKPCAORWRIUNVMQDSSGEATWHRFBVJKDLYMCAW", "CEEWFCPAMNBZOCPJCWMJLUQJFSEFPHYUNEVGG", "BQVCOQNZWENJNHFPSFADKOVQWMDVNCVXPZIJX", "FKXUSGNNHQDYUKKQLNDKOQEXROKAKDOLGAYGL", "ZHZARUUTCQFZELLHAOWMWUAMLUTKXLXBZCPVT", "BJRNATNKWGMAYNZMUBEXUOFVFKNEDVAXQDFMS", "HOHAEVKSGDZSIHEAVLCMZPMUPRAWDIJGWJIHP", "IRBTDMKDAMOOUDXOPEDOAFPVUFIQMOTEWLLRC", "XEOPPERXBZMJLCIUTRTZQGMFTDWGBGMBSTEJM", "SGIIMDRWOFASKJDDAYJOYQNHXCHFXNBCDCPIF", "BDHFZJQBCJWEOMLXZXTPUUAAQQBRCUTRSBLRY", "IMSKWSHHEJUPJTPYLBETLVBTAWUJDJURJECFH", "MSTHIMPWQQCMENSDKZDFQQVYVBVHLGWAUNMHH", "LTBVDCAACQUAEPIUSTEDNBETMZSFTDYPVVUDV", "YIMBMVGJAZPUBGTEGCPYCXJWPHBSQIAVQILNS", "UWMKPLRPJCHCMHJLOUHKTKCNQHDHBSOEOQLZH", "JJKDPENCDHFGYSCYGCVYOUBIDXYVEPOIIZJYW", "HVCGWXMUXCBDRTQXKDKUXHWUDKOIAOGCHCOGW", "SHUTVDETTQUSXCCPPTFNWHLNVOLOGHJHMYLLO", "VWVMHTPPESAMFYCTABSQYMPQKPLFQOSPFDTOP", "EXQFHYWDRPJAFRXHOJHVCOVSMQQGZVKBWCZEA", "ZWLIAVQECJWJHPCANTCAGXIVFGTLJLUVDMFWK", "KFJOUTKFTBEPIQMAHDIPHPLXOPKAJTZXLTENM", "ZXAADUQMHMBSKGZTMZYXPBSJPBGMXAJQJFVNC", "JDTXEVXQQEWNFSUWKEGEHFYAUUHYVQVHICBHC", "JJRBXACXHVFUVVKUSYKINOXKJXJJXNEBJCIDO", "AEXCPUUIKAEPLJIKCNOGCPKCSOFKUOQIXRVAG", "ONIJICRLIMNOIURCOQFZXNAQRTBLFJDQCILNS", "JTWLOHRETVMOINGCTFIFAGQHSHVOTRFANLWHL", "XEVMNZENVGEKZGWMGYXAZTUTSCUZPGVMPPNKG", "NRDZTXSARBMTKYRJOEXNNOMIFGALPXNVZSIGE", "RWFTYFGSCBTGLXWCRDSHTTRWHWYITYCMQWHVH", "TPLOBRQFIEJZWYVWLUQPIJCZYQMNARPDOHIQQ", "PJFGOBXROOHKVBIKFYJCLKVZECCFNGEONLJZV" };
    assertEquals(27, gems.numMoves(board));
  }

  @Test
  public void case36() {
    String[] board = { 
        "VBALHEWM", 
        "DOZCJFLD", 
        "EVUDMWGM", 
        "HQNKZBYJ", 
        "MIUWVUMP", 
        "UEHUTJGY", 
        "ZHKVYVXG", 
        "JBHUJVGU", 
        "JSSLHSVR", 
        "LKWHPBSA", 
        "OZJEXPHM", 
        "EKUMFGGD", 
        "CSVOJSXZ" };
    assertEquals(3, gems.numMoves(board));
  }

  @Test
  public void case37() {
    String[] board = { "BAXTTLTWYHKXPPXABYXWHMTPLYWYB", "XPKPXWLWYTAALTAAPLKHKMWWHPKHX", "HWLLMLPAPBPMPATTLMXTAABHTYLLY", "XXBWYPAPBMLYWMHYPLAWKAYALPYBX", "XKYXXYLAPAXTALPPAPMBXKAHYYXPP", "YMYYXKBLMBYLLAKLXHYYTLTXLWPWY", "LMMAWYLHXXKBAWAKWLTMHLPMAYPLH", "PABPBATAMHLWXXHMPXHMBTWTABAYA", "PAKATTPTXYWTPAMWLPAXYYHWWMBKL", "APKKMXHBBTBHTYTLHLXXPXPAXHTXT", "WTWXKHBHLKTYHHMKWWMAWYALLMPHT", "WYMYXPXLAHALKWWLWXYXLPXHLLATL", "TYLWXLAYTTXXWXBWMXWPMKLYKTWKW", "WHWATYAPAYLWHHPYATPYLBMTBTBYT", "KPLBPHBHKKWXYLTAHABYHAXMWWMHM", "MMWBWABPYWTWPYYXAKPLMMLPPLXXY", "KTAYMHHTMKBBXMAYMBMTLWWYYKHPL", "PYTKKBPXMKWBBWALMBWBMYMHLLXXA", "XPWHPWXBPPBYWKBLAYLTKLTLPTAXM", "PBYXAYHMTKMHYYXBKXHTHAKHXPTMP", "LHXAHLHLMLBHPTLMKKMHAXPHPMBML", "TAKYXWKHYHYKBBTTPHHKPPTTBPHPM", "HYLHYPMLKTAKLLABXWYYMTYXYPLLT", "LTTWMXHYLXXTWBLYHBAAHWHWKKPYK", "LMLTKPPBBKKYWMXXMWXKWAXYXAXMT", "AWYLWMHMKLLAKYAXATKWBTMWYLYYP", "YBHWLLAMYYKYKYHWKBMYMBXMLYXAM", "MKMTPWHALKLBMLHHAKYBMTYPLAAPT" };
    assertEquals(85, gems.numMoves(board));
  }

  @Test
  public void case38() {
    String[] board = { "HQUYRNVZAKVTYGANSPVUIUYKXQYRWLAHFNHHGWPGRRF", "QIWUYLLGBGIQQLIPSNILGUYGPBZBWSPFFLTQANSRGGW", "BGGRGRNYZYISSPNURSBGNSZPKYZSHNZFZHBZPHNKFPZ", "RZWRQFTHAQNVPULTHKHFPTHGLKWWULNXPYUPFNHTNSF", "PZLGAUNKAXYLYFHAQNBUVWHYNBFXXRSYUBSUNYXBZGL", "INFUHXNKKNTZPTKPWAPGUZUTXBXZKILBFSIZBYWPZWS", "WXRXYALFNGKBANKULPTVGPVIHRUVHNVVKLAYBBGSLWB", "QSWIQVSQNKWGNXIUIABFLQUBLYSZLUKIULVQLAKGFSW", "TVFNNXWLAZZRRIZLBSHRGQXAYSXQLIXZBYWTHNFXIZU" };
    assertEquals(10, gems.numMoves(board));
  }

  @Test
  public void case39() {
    String[] board = { "JHXYJDDYWWJMUYBTVJWBMTSIJTGNDBSYJXUBXT", "TMWTYWVMHNGTIDYMHYDXJBGSSTBVTSBHTUHVUH", "WGIJNIJNVCCBCIYYNVDNNJXWTXMBTSYTUNBJDG", "NXYUDXTUIJDCGHBYJYWIUMINWVWBBTHWVXMHSW", "DBVSUHJTWNYYTIWWNVSUMTWDDCJNJTDVHYMHTG", "NNCUXXVVDNJMXYWXHBGTHBDIHJHNNSSMJDDINX", "MISWJXUTWVDTWNJUSXWVNMDCCJYGYHGSHYMWTY", "TWUUJDUIBIISYJGDXYTTNMJMTUGDSSDBJSMCUY", "TIUYGTJMVMVDWJJDXGJUIXDCWXHNTNBJVXCDTB", "JGITVDDNJJUXNUSCHGCBBYHBTGGDDVVWWDBVYN", "DDTVBSDXDXJSUYSCNNCJMJBSMMDBDHVGIBSDCX", "VWJBGUTNDVXTWITUVTNBBXSGCXIUCGBGMNBJDM", "VVHNBIUHUCYMSNGYWNYBBVGIIHWCBGUXJVJSBH", "NBWSSWMMVIIXHHBBNSNSHHYHTUDXXWVIHIGHIW", "WCMJXWUMJMNINNSSTGIMNSHUCJNUNCIUSBUUBD", "JIJWMGCYCSCJGHNMNYIWWSTTYGXYGBMGJCUDMM", "XMJTGDHVWTSWICWDDUUTUYXCBWBXWBJBTWWTHT", "XMIWWGGICDXTNSWBMTXHVCMNUSIIJIYCCGVJGH", "WTTYMJWMXXIBYWDYVCVTYTNIXBWDWWCTDYDIVT", "CNYXJTWYWBBWNISDXHXBJHDTICHHWDMSXMCBYJ", "SMUSDJBBNIIWTYHMGDSDWDCITJYIIMYSNUXWCD", "SUTWINGIHISSWIYDBYGUBJVSIUNNJJCGWGWNTV", "VDYXGNYJSNHBCCJMCBJCGXNDXHGSTHCXUIYGIM", "VYUWUBCXXBTCDUDVTIXCUCDCDUYYXYGVIGHJBS", "TNGDUNHIMUBSIGISUIGBVDUCNDXTTBDUHICHYW", "SDWGNDYCSGNJUISNNGJVHBMTIIGIBDMSNTJUCJ", "WBTHNUCSJUGMTNXVIWTXUNHBTGIGXDNMUTGDIH", "GTSNWUYBITVMBTHXUMBJNDGVMGTJGGYNTBBNUD", "GHWUHHDIWSYSGSCTJGUDXDBNIXMSISDYVVMUHD", "NJUJJYUCCDTBDYGBIJDNDIJYSSUMYIJYCGBMJB", "TXTMTVUGVIIMDXXHYCYGGVUIJBTUBGUTWYNYTX", "THJBUXCNMGMVCDYYUGBTIYIXDGGBNNJXJSSVJD", "XXNNCJMJNWSXDDGBXWBWYSXIGVSGDCVMBTDVHH", "CXIWTCYHYUMHGMUWXIXBMSMCSUSTVXWVTMNNTG", "GDJDIDYYIXBWJJXNBIDDVMUYGNVCMDDSNYXDJD", "XNBTJJWUYVNNTNJCVWBJTMCNJJWHJNITCSJBJY", "MDJVWMUUHJWYBWXXSCGBSSGCYNTBSNXCBWWTHX", "UYMUJSXBMJCNSUHMYJXMGYUWJVYUCVYICBXXGN", "MNDNVMHJHUINGHHVWYDUNDVGVJWYJVMNVMNVNH", "YMIUWWXSSTNXSSDGVTSJWUCIJCIXSJITYNBSUN", "YYMYHIDVSHBCCDXDNMJYIXSYXJNITDHJSBXJHH", "TBUDHBYDDGCXVMUSTDGYGWIGVUSUVHJDCIGYHW", "YYCSUCMSWUWCYMIHHNMUJMYBIVYBXNMSJNGIWW", "VTXINBWIWUMHXTBUSUIJCDDMUBCNSIXBMGNVJG", "VTUYGHYGVWIGMYJJVBCDGCTYMSHVWUUSYSDBNN", "HBMMIGVVJXDGVGYNGTUBDSCMUIYGWDJUGUJWIG", "DNIXXDCTCXYTYJUCCSWMNJUTWGSVTGJCHYUCIB", "CJCJNSNWBMJVGTSUIXBTCWHNBYGWNNCBDVGBYX" };
    assertEquals(109, gems.numMoves(board));
  }

  @Test
  public void case40() {
    String[] board = { "SUMEEMEEPGPPG", "USPMIPSUSIISG", "UPSPGEGGPKEII", "KEMGISMKKIUIG", "MGSIIKMSISGKM", "SPGMSMIGMSMGM", "SSIIUKMPEPPUI", "UKUIUEMEEIGKE", "IPUPGUSEGSSUS", "EUPMKGGUKKEMI", "PEPSMUUEUSSIP", "SUMEEUSESUEKG", "EPSKUISGMSKGI", "IUGGUGGSIGUUP", "IUPIKKSGPPEEP", "KGEESGISPGGEM", "UEIUSSKPSSGPE", "KSUMKGEIMKPSE", "ESKEUEMMPPIGG", "UUIEUGGIGMEMK", "GPGMPPIUMEPMU", "IKIGGPIUEMIGS", "IPUSGUMKPKIPP", "UEEMUUEEGIPUS", "PPEKIKEMGGMSS", "EMKPMPUUMKEPU", "UKPGPKSUIEUPM", "PSUUMUKGIIPMS", "ESMGSKUEPGGEM", "SMEEIKGKGGPEG", "UEIEKPMESMEPP", "IPUIMGGMIPKMG", "ISSEKPKGKIUGU", "SSESKUGKISPUK" };
    assertEquals(83, gems.numMoves(board));
  }

  @Test
  public void case41() {
    String[] board = { "SBHRKLMI", "ESFGUMRQ", "PCWXJVVD", "LNRMBJIV", "RWVPWQUP", "ORKOQGWD", "OWSWTKBP", "UJFIUJRT", "WNIXIWLD", "WSFUHIHS", "UHVYCRQX", "KXVLUTMO", "MMIHAZSK", "DLACKUMU", "BCTDRHPO", "FUXTOADJ", "VQSIQDEJ", "ECCZMBOQ", "REJVAAFB", "DCOCIDJB", "LQRGNZSO", "QSOVTXHI", "MWDRBNTC", "CGRRLBMN", "MTMLAGGW" };
    assertEquals(2, gems.numMoves(board));
  }

  @Test
  public void case42() {
    String[] board = { "DZZMUUIDNMMUDNMMUQUNQMQZDZDNUDZQUQ", "MZUIZZIRIMDDMQRDQRRDQRRDMUZZQRNQNZ", "DMZZQUMQDRDQQMMIMQRNUZIDRDZMNNUDDU", "MRMDQRMRZMMUIUIDUIMUMNQQZRIZMUQUZM", "MDMQUMQNRIZNUDNRQUDMRUQURQRMRZNNDN", "RDQMMIQRZMQNIZRQQZQDIIRRDZUZZNQDUR", "ZIDMMDNDIRMRDQQUMUDZZIIZMNDRNDIMNM", "ZUUNDDQUQUDMDRZZUZDZDNIDUMRIUMRQNU", "RDQMUMINMUIMUNZRQDMQDZMQZMMIMNIZMR", "DQUZIMZNDRNQUQUZZQMIRZZIRIQNZQIURN", "DQNUDNQQZIRIMMIRMMUDMRQDNNUNMIRMRN", "UUZRQDMQZIDINRNIIDZQIMRDZDUIDNUMIR", "UUDZRQRUDZUMQZRQQZUQRUIQMRRQUQMUUM", "MRIZQUDUZUZDQQDIUZZMNQMQQMZNDQINUR", "IUMRIRNRIUURUIZIRQZUUMIMNMUMZZRDID", "NRZRDIQNIRMMIQUNDRDURRZNQIMQDRUQRZ" };
    assertEquals(90, gems.numMoves(board));
  }

  @Test
  public void case43() {
    String[] board = { "FIMWMZTIIJMXFFJJTUFJIUITMUJFFJXFWZZTFMUXZTMFUT", "TXXZWJUJIFXXTXZMMUXFZIMTXMIWMUZZUITFXIWZTJWJWU", "UMUTUWJTFIJMTUMTTFMZMXXUXMUXFITZWMXJZUWZXFJXJF", "TWIWIMJWWTUMZFIFZTZUZXZWJIIFFZUWZUTUZJXIXTUMZJ", "UWJMUZIUZMUJJTTUZFZMZJTUFMMFMZIUIUJXIXWXZIXIUJ", "FJTZIJWZFZTWWMTTIMUFIFTIXJFZZUZMIMWMJUTFUXTUXI", "ZMXIZUTJFZFFTXUUTUFZUMMFIFJTZMFUUMZFJWTJIFJWTF", "TJJXTJFZXFMXTXMFMFXJUFXJUIJZIXUIWTFITMJMFMJJMM", "ZIXTFUWXZTZTMTJUMITIZUWXWWXIXTZFWWZXIZWXWZTIXT", "JJIJMXMJUIUIXMUFJUFMWXZUXMZXXTZZJIZWJZFWTFTTZU", "MJJTITMWFUZXTTZZTMWMMXTUTFFUZMXUJTUJUXFUZMJTWM", "FUJZTUWZZIWWJFUWMIWZTTXWJMXXIUIFXJUFWZTIXJWZJZ", "JFTZFFTMIMJFUUMUTFXWXTFWIZXTXITZTWTWIMXWTZZXWF", "UXJFIZUXFFIIXJWZUIZXZJFXZXUJUZZFMMUFMFJZTJZUWI", "MUUTXTMXZWTJIZIFUIMFIXXMFXTIJZMIZUXUJZTXUFFIFT", "MUFJIZFUMWIZXXZWWFMFFTUUWFZTZUXJUUXIXUTWFUUMJW", "ZWZMJUTUTZZJXZWWMXZIUTFIZJXMMWZMWIFTIZUFFMMJTT", "MFFJMIMZUFJFTXIIFZWUMXJTXJTUFUIUIXUJZJIMXUTWJT", "FFTJMUIFWFXTUMJUFMZIZMWUFITFFXJFIMMJIITXTXFTFF", "TTXFUFXUXUWTITMUUZXFZMIFUWZTUWIWFMXUMJWJMZJWMF", "IMJUUZMUXTFWXWUWXIXIUUWJZFXJZFXZUFWIUFFMMUIWFI", "UIWFMFFWUWXMJUTUUJTJWMMIUZMTTFMFXWFXWWIWZZMUTI", "WJWMTIJWFIJIFMJIUZJTFJWXZFTMJMWXWTUITJXZFMITZT", "WZXMMFMFZUTJXIJTJWXJZMFTJXIUJMJZITZMUMUUFFWXTJ", "MTUFXUWUZWFXZFZXZXTFZMJWTJWFIWFMXWMTUUIXIUUJIU", "FXIFIXTMIJJXXJTUIXMWUFWUTZXIJWFIZUMZMJTWTTWUIZ", "MJJWMFWMIJJIUFIXUTXIUFZXZIWWIIMXXTFIUMXWXXWJFZ", "MXIIXXZUXMUTIWFZWJMJXWWXXTXWWUTXMMJFWWUMWIIUMM", "WXZWFWFFXMFMZXMTUTUXZITMUUFFMMWMTJFIFJZJZTZTUM", "TTMZFXIWUFJIUXTWIWMTTWUZMWFJTUUJMXMUXFITFXWMII", "MIIFUZMJZZUUITJTWZZIXXWXUJIFTWZZIZIZFXMMIFXIUW", "UFUWUUZTUUZJUTWFFXJMMWXXZTWUZMXZWIWFUWWUTJJWTZ", "IWUUWJTIIUFIIZFUWUIZTIITJMTITZTIJTJZFMMTWTWTXU", "FZFMZMJFJMWTMFIFXTTITXTIJFXXJZMITXJXUMUWZTXWTX", "UIIUIIMIFWJJZMMZZUWZZMWIWTWIMUMFTWWITJWWZJUZMU", "XFXMMWMUUIXFXXTUJUJWZWJMTIFTIXFIXWZXXTUUJXJZFF", "TJUTJIZXZWTWJMIWZXMZUXIIXJWTXXUUWXTFTFZMFZJUII", "JMIFZZITIMZIWIFIZIWUMTMFJTWWTMUFZZIMWWMXXTFMTZ", "ZJXXMMUZIXXTFMIJIXIJMIJWJXJIZFJZMXMIMUTUJTTZJJ", "UTIJIWMJXUTZJJMWWJTTXJMFUZTZUZMFMZFJMZTIJZFUIM", "ZTIXXUUTFUUMWZZMJXXIJWJXZWFZZTUJFWZTJUIUTXJMMU", "FZZWIIZTMFUWFJUWZXUXZIFJFMWJZIZXJXMMJJZZIZTWZI", "XUXIFFJXTWZTWFFUJTUJMIUMXIMMTJJZFFMJMUIMZXUXMI", "XWZFZTJTJWTIXXUIFXMIMTXTZTWMTZUFUWXIXZTFMIFWZM", "TWUMJFIWWUJUFTFFJFMXWITXIWZIJTJJFMWZUTZZFIFMFF", "TFXFIZZUJMFJXMJFMIXIIXTXFWITXIJTIFFWJMZMWZMMZX", "MUUWIZIWZTITIJFTWFUWMJFIMJZJJMUJJIWXXTMMIJWXXT", "ZFTFZTMTTZIFXUFFXWXFZFJFWJXZMZZIJWTTJXMJFWIXXZ" };
    assertEquals(332, gems.numMoves(board));
  }

  @Test
  public void case44() {
    String[] board = { "SSPDQQDMWDKDMPWSVMSDPV", "SSKDWQOOKQDSWWSQOMMWKK", "MDDWMKDQMOKMPKPPMVDSVK", "SMSMOWWMPQOQWVKKOMVDOQ", "OMSSPPVKVPMSKMSOWKDDPK", "QQPQPPQWSSPQWPKWMVWMQO", "PQOPVSMDDMPQPVMOSPPOWD", "QDWMQDOQSDKVQDQWWQPMKM", "VQPPMQOPMQWKWMWSSPKPQS", "WSVDSVKMSSOOSPOKDOQSOK", "OPQOPPMQVKQOOPKSOVMKKW", "KSOQVOKODWMQMVSQQSVWQS", "PQOVOQWVVQODSDOVMOSMWP", "DKKVVDSMSMKWVSVPMPSOQM", "MMVQVKVQSQSMQPOKOQMDVS", "PWDVQODKOOWVSVVMDKWQDP", "SSMWVSWMMDVVSKKSQMOKDQ", "DDQWPKVWQWQPWDSDKQVVMS", "OSMKMQSQQDKMSWMQQWKMOM", "WODQVOVKOWSDMKVWSPSDKD", "PPKOKVDKOVDSKWQOQPVKSP", "SMMSKMKWSQOSWSKMOSOVPV", "PKMMDWPWWMDPDVVKKMVVKP", "PDWODQSKKPWPVDMVQVKMMS", "VPPSWKDMPWDDKKDDOKMPOD", "SWPDKPKSDQPQMDMPPOQWWP", "QDWSWOVVQMSWVOQMSWQVMO", "WSSKMOSWQSVDWOOKMKWODM", "SDMKSSQKDQSMPPVWKQVOOS", "WPPMWMDOKWPVKWPVDWQMSP", "PSDKPOWKQDQPDDOSSVWPSP", "MOKSVMMWMQWQKKMVSVKDQW", "DMOOPWSVMVQPMDMSPDKSWS", "KVOSKMDODVOOQSVDVOQSVP", "VPPSMDQMVOVMKDOKQSOMOO", "DSOOVPDQQDSQQPPKDPQDSV", "OWWVVQMKDSDPWVDPSMWMPW", "OSWOOKOWPKKMKPWSKQWVKQ", "VKDMOQMPPWKDDPVSMPQPKP", "OPPOMDKWWVVPSDVVSOQWDM", "VMDVMKVPKVDQMWMPDWSDWM", "DVMDQQSDSWQOSWVVSOMMQK", "VMQWKQOVWWSODOQQDVPQVV", "WMDKQVKSVOSPVPWDMSKSMQ", "MODOMWPWDKVOVSMSPWMQMO", "DQSQMQVSOMPPQPSPQSOSPV", "KSPQWMDMWVQOKKQKQOSKSK" };
    assertEquals(129, gems.numMoves(board));
  }

  @Test
  public void case45() {
    String[] board = { "EOUWROVXGWXRTUWMGXGVTLVUJVOTEJCUOMECM", "JWGVULXUPTUWVMOOWMMJGUWCQWEMXUCERGMVR", "LWVJLRCRJXEXQELTMGGCTWMOWUQEQQEXJTERV", "VTTMEUQQMTPECMMEEXVEPLOQTVGWOEVPEPJJC", "CMGRGMXQLQEWRLGMRLMQGQROXPGVELRMMPXRJ", "GWQUQXRWVPCPRTMWCOOELETWTLUETQTRPXROE", "ORJOMWQUQLEPJTJLVPXJPMUOOQGVGCTXQPREV", "CWUVLEXMMLRVPLQUUMOJGLJPOCMMEVPWXGWGV", "WEQRWPPUUXEUMRQLMUUPWPVOQQOVLOLXEXCJE", "EWVTECGUQLXVQJPREUPGRCXOJXRMVEUPWLXRP", "VGMVLJROCJEUMVJGLJTGXVCVVTLCVEOQMVPWR", "RRWVEEWPCWCMGQXPGOMWCQVOGLVWGRCRUJEPW", "UTULTMCMOVUUETTMVPLULQPTCPRUUOQGOJUPJ", "MLRVQEPRQVMERWWVMEOPPJCEOELRWOPLOPLCC", "PTCROUJOEUOCWLGTVCWWLJMJRGWMPUUPVMQUG", "ETPMLPWWEGEWUJJVTCEXULLVXMTOVCORJXQGR", "ULWJUEWPQEQLPRROWXVPVGPUQXVLCOMLOXUVG", "MGJUMTVERMTMMPQMGCPGEEPQVQVOEEPLUPWRE", "XOQXWMLQLCWUJMWMVMQWRPUVPEXXGCGEUGWGW", "RQJVXVWJOWQXLVLUTTLVOURPCUWEEVGMVWETQ", "EPWGXXEEMRXEJJQJPJTXWWUCTGWQVPQVELPVP", "WXEOLMJPOTLPJXGUECWXJUGVLWMUOGUGLUJWX" };
    assertEquals(51, gems.numMoves(board));
  }

  @Test
  public void case46() {
    String[] board = { "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA" };
    assertEquals(4704, gems.numMoves(board));
  }

  @Test
  public void case47() {
    String[] board = { "SUMEEMEEPGPPG", "USPMIPSUSIISG", "UPSPGEGGPKEII", "KEMGISMKKIUIG", "MGSIIKMSISGKM", "SPGMSMIGMSMGM", "SSIIUKMPEPPUI", "UKUIUEMEEIGKE", "IPUPGUSEGSSUS", "EUPMKGGUKKEMI", "PEPSMUUEUSSIP", "SUMEEUSESUEKG", "EPSKUISGMSKGI", "IUGGUGGSIGUUP", "IUPIKKSGPPEEP", "KGEESGISPGGEM", "UEIUSSKPSSGPE", "KSUMKGEIMKPSE", "ESKEUEMMPPIGG", "UUIEUGGIGMEMK", "GPGMPPIUMEPMU", "IKIGGPIUEMIGS", "IPUSGUMKPKIPP", "UEEMUUEEGIPUS", "PPEKIKEMGGMSS", "EMKPMPUUMKEPU", "UKPGPKSUIEUPM", "PSUUMUKGIIPMS", "ESMGSKUEPGGEM", "SMEEIKGKGGPEG", "UEIEKPMESMEPP", "IPUIMGGMIPKMG", "ISSEKPKGKIUGU", "SSESKUGKISPUK" };
    assertEquals(83, gems.numMoves(board));
  }

  @Test
  public void case48() {
    String[] board = { "GUMEEMEEPGPPG", "USPMIPSUSIISG", "UPSPGEGGPKEII", "KEMGISMKKIUIG", "MGSIIKMSISGKM", "SPGMSMIGMSMGM", "SSIIUKMPEPPUI", "UKUIUEMEEIGKE", "IPUPGUSEGSSUS", "EUPMKGGUKKEMI", "PEPSMUUEUSSIP", "SUMEEUSESUEKG", "EPSKUISGMSKGI", "IUGGUGGSIGUUP", "IUPIKKSGPPEEP", "KGEESGISPGGEM", "UEIUSSKPSSGPE", "KSUMKGEIMKPSE", "ESKEUEMMPPIGG", "UUIEUGGIGMEMK", "GPGMPPIUMEPMU", "IKIGGPIUEMIGS", "IPUSGUMKPKIPP", "UEEMUUEEGIPUS", "PPEKIKEMGGMSS", "EMKPMPUUMKEPU", "UKPGPKSUIEUPM", "PSUUMUKGIIPMS", "ESMGSKUEPGGEM", "SMEEIKGKGGPEG", "UEIEKPMESMEPP", "IPUIMGGMIPKMG", "ISSEKPKGKIUGU", "GSESKUGKISPUK" };
    assertEquals(81, gems.numMoves(board));
  }

}
