package topc.test.graph;

import junit.framework.*;
import org.junit.Test;
import static org.junit.Assert.*;
import topc.graph.*;

public class XorTravelingSalesmanTest {
    XorTravelingSalesman xortravelingsalesman = new XorTravelingSalesman();

    @Test
    public void case1() {
        int[] cityValues = { 0, 7, 11, 5, 2 };
        String[] roads = { "NYNYY", "YNYNN", "NYNNN", "YNNNN", "YNNNN" };
        assertEquals(14, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case2() {
        int[] cityValues = { 556 };
        String[] roads = { "N" };
        assertEquals(556, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case3() {
        int[] cityValues = { 0, 4, 8, 32, 512 };
        String[] roads = { "NYYYY", "YNNNN", "YNNNN", "YNNNN", "YNNNN" };
        assertEquals(556, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case4() {
        int[] cityValues = { 175, 432, 0 };
        String[] roads = { "NYY", "YNN", "YNN" };
        assertEquals(432, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case5() {
        int[] cityValues = { 580, 37, 468, 800, 867, 543, 879, 44, 213, 979 };
        String[] roads = { "NNYNNNNNNY", "NNNNYNNYNN", "YNNYNNNNNN", "NNYNNNNNNN", "NYNNNNNNYN", "NNNNNNYNNY", "NNNNNYNNYN", "NYNNNNNNNN", "NNNNYNYNNN", "YNNNNYNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case6() {
        int[] cityValues = { 737, 732, 434, 781, 230, 389, 859, 816, 931, 594, 128, 300, 490, 391, 55 };
        String[] roads = { "NNNNYNNNNYNNNNN", "NNNNNNNNNNNNNYN", "NNNYNNYNNNNNNNN", "NNYNNNNYNNNNNNN", "YNNNNNNNNNNNNNY", "NNNNNNNYNNNNYNN", "NNYNNNNNYNNNNNN", "NNNYNYNNNNNNNNN", "NNNNNNYNNNYNNNN", "YNNNNNNNNNNNYNN", "NNNNNNNNYNNYNNN", "NNNNNNNNNNYNNNN", "NNNNNYNNNYNNNNN", "NYNNNNNNNNNNNNY", "NNNNYNNNNNNNNYN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case7() {
        int[] cityValues = { 448, 892, 810, 745, 415, 599, 835, 831, 174, 984, 961, 68, 77, 848, 192, 491, 570, 320, 973, 240 };
        String[] roads = { "NNNNNNNNNYNNYNNNNNNN", "NNNNNNNNNNNNNYNNNNNN", "NNNNNNNNNNNNNNNNNNYY", "NNNNNNYNNNNNNNNNYNNN", "NNNNNYNNNNYNNNNNNNNN", "NNNNYNNNNNNNNNNNNNNY", "NNNYNNNNNNNYNNNNNNNN", "NNNNNNNNYYNNNNNNNNNN", "NNNNNNNYNNNNNNNYNNNN", "YNNNNNNYNNNNNNNNNNNN", "NNNNYNNNNNNNNNYNNNNN", "NNNNNNYNNNNNNYNNNNNN", "YNNNNNNNNNNNNNNNNYNN", "NYNNNNNNNNNYNNNNNNNN", "NNNNNNNNNNYNNNNNYNNN", "NNNNNNNNYNNNNNNNNNYN", "NNNYNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNYNNNNNNN", "NNYNNNNNNNNNNNNYNNNN", "NNYNNYNNNNNNNNNNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case8() {
        int[] cityValues = { 763, 859, 29, 59, 416, 385, 572, 464, 321, 244, 858, 641, 216, 730, 777, 999, 290, 635, 677, 479, 68, 452, 71, 549, 193 };
        String[] roads = { "NNNNNNNNNNNNNNNNYNYNNNNNN", "NNNNYNNNNNNNNNNNNYNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNYNN", "NNNNNNNNNNNNNNNNNNNYNNNYN", "NYNNNNNNYNNNNNNNNNNNNNNNN", "NNYNNNNNNNNYNNNNNNNNNNNNN", "NNNNNNNNNNNNNYNNNYNNNNNNN", "NNNNNNNNNYNNNNYNNNNNNNNNN", "NNNNYNNNNNNNNNNNNNNNNNNNY", "NNNNNNNYNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNYYNNNN", "NNNNNYNNNNNNNNNNNNYNNNNNN", "NNNNNNNNNNNNNNNNNNNNYYNNN", "NNNNNNYNNNNNNNNYNNNNNNNNN", "NNNNNNNYNNNNNNNYNNNNNNNNN", "NNNNNNNNNNNNNYYNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNNNNNNY", "NYNNNNYNNNNNNNNNNNNNNNNNN", "YNNNNNNNNNNYNNNNNNNNNNNNN", "NNNYNNNNNNYNNNNNNNNNNNNNN", "NNNNNNNNNNYNYNNNNNNNNNNNN", "NNNNNNNNNNNNYNNNNNNNNNNNN", "NNYNNNNNNNNNNNNNNNNNNNNYN", "NNNYNNNNNNNNNNNNNNNNNNYNN", "NNNNNNNNYNNNNNNNYNNNNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case9() {
        int[] cityValues = { 389, 29, 999, 596, 261, 365, 616, 950, 41, 101, 813, 95, 527, 762, 330, 412, 406, 695, 1003, 979, 696, 968, 891, 64, 913, 959, 614, 492, 960, 105, 777, 530, 587, 753, 102, 448, 94, 718, 374, 135, 887, 116, 230, 231, 427, 872, 363, 313, 349, 342 };
        String[] roads = { "NNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYN", "NNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNYNNNNNNN", "NNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNYNNNNYNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNYYNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNYNN", "NNNYNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNYNNNNNNNYNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNYNNYNNNNNNNNNNNNNNNNNNN", "NNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNN", "NNNNNNNNNNNNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNN", "NNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNN", "NNNNNNNNNYNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNYYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNYNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNYNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNYNNNNNNNNNN", "NNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNN", "NNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNYN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNN", "NNNNNNNNNNNYNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNYNNNNN", "NNYNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNY", "NYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNYNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNYNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNYNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNYNNNNYNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNN", "NNYNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNYNNNNNNNNN", "NNNNNNNNYNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNY", "YNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNYNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case10() {
        int[] cityValues = { 8, 512, 1 };
        String[] roads = { "NNY", "NNY", "YYN" };
        assertEquals(521, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case11() {
        int[] cityValues = { 128, 64, 4, 64, 16, 32, 725, 261, 2, 64 };
        String[] roads = { "NNNNYNNNYN", "NNNNNNYNNN", "NNNYNNYNNN", "NNYNNNNNNY", "YNNNNNNYNN", "NNNNNNNYNN", "NYYNNNNNNN", "NNNNYYNNNN", "YNNNNNNNNY", "NNNYNNNNYN" };
        assertEquals(1014, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case12() {
        int[] cityValues = { 512, 365, 775, 4, 64, 8, 16, 2, 32, 218, 512, 1, 64, 4, 878 };
        String[] roads = { "NYNNNYNNNNNNNNN", "YNNNNNNNNNYNNNN", "NNNNNNNNYNNNNNY", "NNNNNNNNNYNNYNN", "NNNNNNNNYNNYNNN", "YNNNNNNYNNNNNNN", "NNNNNNNYNNNNNNY", "NNNNNYYNNNNNNNN", "NNYNYNNNNNNNNNN", "NNNYNNNNNNNNNYN", "NYNNNNNNNNNNNYN", "NNNNYNNNNNNNNNN", "NNNYNNNNNNNNNNN", "NNNNNNNNNYYNNNN", "NNYNNNYNNNNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case13() {
        int[] cityValues = { 161, 617, 16, 512, 64, 1, 295, 270, 32, 4, 128, 128, 2, 64, 813, 32, 865, 512, 16, 32 };
        String[] roads = { "NNNNNNNNNNYNNNNNYNNN", "NNNNNNNYYNNNNNNNNNNN", "NNNYNNNNNNNNNNNYNNNN", "NNYNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNYNNNNNNNN", "NNNNNNNNNNNNNNYNNNNY", "NNNNNNNNNNNNYYNNNNNN", "NYNNNNNNNNNNNNNNNYNN", "NYNNNNNNNNNNNNNYNNNN", "NNNNNNNNNNYNNNNNNNYN", "YNNNNNNNNYNNNNNNNNNN", "NNNNYNNNNNNNNNYNNNNN", "NNNNNNYNNNNNNNNNNNYN", "NNNNNNYNNNNNNNNNNYNN", "NNNNNYNNNNNYNNNNNNNN", "NNYNNNNNYNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNY", "NNNNNNNYNNNNNYNNNNNN", "NNNNNNNNNYNNYNNNNNNN", "NNNNNYNNNNNNNNNNYNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case14() {
        int[] cityValues = { 256, 8, 2, 2, 512, 512, 88, 8, 2, 512, 2, 512, 16, 4, 620, 2, 8, 32, 951, 556, 16, 64, 256, 376, 4 };
        String[] roads = { "NNNNNNNNNNYNNNNNNNNYNNNNN", "NNYNNNNNNNNNNNNYNNNNNNNNN", "NYNNNNNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNYNY", "NNNNNYNNNNNNNNYNNNNNNNNNN", "NNNNYNNNNNNNNNNNYNNNNNNNN", "NNNNNNNNNYNNNNYNNNNNNNNNN", "NNNNNNNNNNNNNNNNNYNNNNNNN", "NNNNNNNNNNNNNYNNNNNNNYNNN", "NNYNNNYNNNNNNNNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNYNNNNYNN", "NNNNNNNNNNNNNNNNNNYYNNNNN", "NNNNNNNNYNNNNNNYNNNNNNNNN", "NNNNYNYNNNNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNYN", "NNNNNNNYNNNYNNNNNNNNNNNNN", "NNNNNNNNNNNNYNNNNNNNNNNYN", "YNNNNNNNNNNNYNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNY", "NNNNNNNNYNNNNNNNNNNNYNNNN", "NNNYNNNNNNNYNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNYNYNNNNNN", "NNNYNNNNNNNNNNNNNNNNYNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case15() {
        int[] cityValues = { 64, 4, 94, 1, 512, 128, 271, 8, 512, 8, 969, 128, 128, 4, 256, 256, 256, 4, 917, 256, 691, 4, 256, 1, 766, 653, 2, 16, 512, 256, 2, 996, 644, 4, 512, 1, 512, 8, 32, 1, 992, 512, 128, 16, 2, 128, 16, 4, 336, 8 };
        String[] roads = { "NNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNN", "NNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYN", "NNNYNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNN", "NNNNNNNNNNNNNNNNNNNYNNNNNNNNNYNNNNNNNNNNNNNNNNNNNN", "NNYNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNYNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNYNNNNNNN", "NNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNYNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNYNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNYNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNYNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNYNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNYNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNN", "NNNNNNYNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNYNNNNNNN", "NNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNN", "NYNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNYNNN", "NNNNNNNNNNNNNNYNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNN", "NNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNN", "NNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNYNNNNNNNNNN", "NNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYN", "NNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNY", "NNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNN", "NNNNNNNNNYNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNYYNNNNNNNNNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNN", "NNNNNNNNNNNNYNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNYNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNYNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNYNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNN", "NNYNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNY", "NNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNYNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case16() {
        int[] cityValues = { 878, 85, 760, 579 };
        String[] roads = { "NYNN", "YNYY", "NYNY", "NYYN" };
        assertEquals(981, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case17() {
        int[] cityValues = { 39, 519, 294, 188, 649, 457, 309, 503, 543, 726, 58 };
        String[] roads = { "NNNNNNYNNYY", "NNNNNYYNYNY", "NNNNYNNNNYN", "NNNNNNYYNNY", "NNYNNYYNNNY", "NYNNYNYNYYY", "YYNYYYNNNNY", "NNNYNNNNNNN", "NYNNNYNNNNN", "YNYNNYNNNNY", "YYNYYYYNNYN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case18() {
        int[] cityValues = { 852, 433, 279, 198, 964, 28, 823, 394, 732, 938, 803, 121, 320, 61, 624, 514 };
        String[] roads = { "NYNNYNNNYNNNNNNN", "YNYNYNNNNNNNNNNN", "NYNNYNNYNNNYYYNN", "NNNNYNNNNYYYYNYN", "YYYYNNNNNNNNNYNY", "NNNNNNNNNNYYNYNN", "NNNNNNNNYNNNNYYY", "NNYNNNNNYYNYNNNN", "YNNNNNYYNYNNNNNN", "NNNYNNNYYNYYNYNN", "NNNYNYNNNYNYNNNY", "NNYYNYNYNYYNNYYN", "NNYYNNNNNNNNNYNY", "NNYNYYYNNYNYYNYY", "NNNYNNYNNNNYNYNY", "NNNNYNYNNNYNYYYN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case19() {
        int[] cityValues = { 679, 757, 254, 1004, 931, 201, 142, 1016, 3, 109, 1002, 888, 800, 262, 78, 18, 123, 565, 87, 575, 109 };
        String[] roads = { "NNNNNNYYYYYNYNNYNYNNY", "NNNYNNYNNYNNNNYNYNNYN", "NNNNNYNNNNNNYNYNYNYNN", "NYNNNNNYNYNYNNNNNNNNN", "NNNNNYNNNYNNNYYNNNNYY", "NNYNYNYNNNNYNYNNNNYNN", "YYNNNYNNNYNNNNYYNNNNN", "YNNYNNNNNNNNYNNYNNNNY", "YNNNNNNNNNYNNYYNNNYYY", "YYNYYNYNNNNNNYNYYNNNN", "YNNNNNNNYNNYYNNYYNNYN", "NNNYNYNNNNYNNYNNNNNYN", "YNYNNNNYNNYNNNNYNNNNY", "NNNNYYNNYYNYNNNYNNNNN", "NYYNYNYNYNNNNNNNNYNYY", "YNNNNNYYNYYNYYNNNNNYY", "NYYNNNNNNYYNNNNNNNYNN", "YNNNNNNNNNNNNNYNNNNYN", "NNYNNYNNYNNNNNNNYNNYY", "NYNNYNNNYNYYNNYYNYYNN", "YNNNYNNYYNNNYNYYNNYNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case20() {
        int[] cityValues = { 609, 703, 396, 704, 875, 832, 389, 263, 410, 550, 860, 852, 816, 797, 1000, 448, 298, 68, 286, 70, 856, 48, 210, 336, 238, 536 };
        String[] roads = { "NNNNNYYYYNNNYYNYNNYNNYNNNN", "NNYYNNNNYNNYNYNYNYNNNNNNYY", "NYNNNNNYYNNNYNNNNNNNNNNNNN", "NYNNNNNYNYYYYNNNYYNYNNNNNN", "NNNNNYYNNYYYNNYNNNNNNNYYNN", "YNNNYNYNNNNNNYYNNNYNNYNNNY", "YNNNYYNNNNYNYYNNNNNYNNNNNN", "YNYYNNNNNNNNNNNYNNNNNYNYNN", "YYYNNNNNNNNNNNNNNNNYYNNNYY", "NNNYYNNNNNNYNYYNNNNYNYYNNN", "NNNYYNYNNNNYNNNNNYNNNYNNNN", "NYNYYNNNNYYNNNNYYNYYYNYNNY", "YNYYNNYNNNNNNYYNYNNYNNNNNN", "YYNNNYYNNYNNYNYYYYYNNNYYNN", "NNNNYYNNNYNNYYNNNNNYNNNNYY", "YYNNNNNYNNNYNYNNYNYYYNNYNN", "NNNYNNNNNNNYYYNYNYNYYNNYYY", "NYNYNNNNNNYNNYNNYNYNNNNYYY", "YNNNNYNNNNNYNYNYNYNNNNNNNY", "NNNYNNYNYYNYYNYYYNNNNYNNYY", "NNNNNNNNYNNYNNNYYNNNNYYNNN", "YNNNNYNYNYYNNNNNNNNYYNNNNN", "NNNNYNNNNYNYNYNNNNNNYNNNNN", "NNNNYNNYNNNNNYNYYYNNNNNNNN", "NYNNNNNNYNNNNNYNYYNYNNNNNN", "NYNNNYNNYNNYNNYNYYYYNNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case21() {
        int[] cityValues = { 179, 223, 973, 971, 934, 263, 221, 843, 866, 396, 330, 118, 364, 951, 120, 114, 699, 172, 109, 387, 376, 777, 924, 466, 160, 394, 806, 778, 431, 411, 892, 610, 91, 523, 558, 1, 813, 779, 845, 656, 183, 151, 774, 195, 78, 937, 309, 777, 85, 418 };
        String[] roads = { "NNNNNYNNNNNNYNNYNNYNNNYNNNNNNNNNNNNNNNYYNNNNNYNNYY", "NNYNNNNNNYYNNNNNNYYNNYYNNNNNNNNNNNNNYNNNNNNNNNNNNN", "NYNNYNYYNNYNNYNYYNYNNNYNNNNNNYNYNNNNNNYNYNYNNNNNYY", "NNNNNNNNNYNNNNNNNNNYNNYNYNNNYYYNNNNYNYNNNNYNYYNNYN", "NNYNNNNNNNNYYNNNYNNNYNNNNYNYNNNNNNNNYNNNYNNNNNNYYN", "YNNNNNYNYYNNYNNNNNNYNNYNNNNNYNNYNYNNNNNNNYYNNYYYYN", "NNYNNYNYYNYNNNNYNNYYYNNNYNYNNNYNNNNNNNNYYNNYNYNYNN", "NNYNNNYNYNNNNNNYNNNNNYYNYNYNNNNNNNYNYNNNNNNNNNYNYN", "NNNNNYYYNNNNNYNNNNNNNNYYNNNYYNNNNNNNNNNNNNNNNYNNNY", "NYNYNYNNNNNYNYNNYNNYNNYNNNNNNYNYNNNYYNYNYYNNYYNNNN", "NYYNNNYNNNNNYNYNNNNNNNNYYNNNNYYYNYNNNNNYNYNYNYYNNN", "NNNNYNNNNYNNYYYYYYNYNNNNYNNNYNYYNNYNYYNNNYNYNNNYNN", "YNNNYYNNNNYYNNNNNNNYNYNNYNNYNYYNYYYNNYYNNYNNNYYNNY", "NNYNNNNNYYNYNNNNNNNNNNNNYNNNNNNNNNNNNNNNYNNYNNNNNY", "NNNNNNNNNNYYNNNYNNYNNNNYYNYNNYNNNNNNYNNNNNYNNNNNNN", "YNYNNNYYNNNYNNYNYYYNNNNYYNYNNNNNYYNYNNNNNYNNNNNYYN", "NNYNYNNNNYNYNNNYNYNNNNYNNNNNNNNYNYNNNNNYNYNYNYYYYN", "NYNNNNNNNNNYNNNYYNNNYNYNNNNNYNYNYNYNNNNNNNNYNNNNNN", "YYYNNNYNNNNNNNYYNNNNNYNYNYYYYYNNNNNNNNNNNNNNNNNYNN", "NNNYNYYNNYNYYNNNNNNNNYNNNNYYNNYYNNNYNYYYYNYNYYNYNN", "NNNNYNYNNNNNNNNNNYNNNNNYNNYNNNYNYYYNNYNNNNNNNNNYNY", "NYNNNNNYNNNNYNNNNNYYNNNNNYNNNYNYYNYNNNNNNNYNYYYNNN", "YYYYNYNYYYNNNNNNYYNNNNNNNNNNNNNNNNYNNNNNNYNNNYNNYN", "NNNNNNNNYNYNNNYYNNYNYNNNYNNYNNNYNYYNYNYNNNNNYNNNYN", "NNNYNNYYNNYYYYYYNNNNNNNYNNYNNNYNNNNYYNNNYNYNNYNNYY", "NNNNYNNNNNNNNNNNNNYNNYNNNNNYNNNNNNNNYNNNYYNNYNNYNN", "NNNNNNYYNNNNNNYYNNYYYNNNYNNNYNYYNNNNNYNYNNNNNNYNYY", "NNNNYNNNYNNNYNNNNNYYNNNYNYNNNNNNNNNNNNNNNYNNNNNNNN", "NNNYNYNNYNNYNNNNNYYNNNNNNNYNNNNNNYNYNNYNNNNNNNNNYY", "NNYYNNNNNYYNYNYNNNYNNYNNNNNNNNNYYNYYNNYNNNYNYNYNNN", "NNNYNNYNNNYYYNNNNYNYYNNNYNYNNNNYNNNNNNYNNYNNNYNNNN", "NNYNNYNNNYYYNNNNYNNYNYNYNNYNNYYNYNNYYNNNNYNNNYNNNY", "NNNNNNNNNNNNYNNYNYNNYYNNNNNNNYNYNNNNNYYYYNNNNYNYNN", "NNNNNYNNNNYNYNNYYNNNYNNYNNNNYNNNNNNNYNYYYNYYYNYNNN", "NNNNNNNYNNNYYNNNNYNNYYYYNNNNNYNNNNNNNNYYYNNNYNNNNN", "NNNYNNNNNYNNNNNYNNNYNNNNYNNNYYNYNNNNYNNNNNNNYNNNNY", "NYNNYNNYNYNYNNYNNNNNNNNYYYNNNNNYNYNYNNYYYYNYNNNNNN", "NNNYNNNNNNNYYNNNNNNYYNNNNNYNNNNNYNNNNNYNNYYNNNYNNN", "YNYNNNNNNYNNYNNNNNNYNNNYNNNNYYYNYYYNYYNYNYYNNYNNNN", "YNNNNNYNNNYNNNNNYNNYNNNNNNYNNNNNYYYNYNYNYYNNNYYNNN", "NNYNYNYNNYNNNYNNNNNYNNNNYYNNNNNNYYYNYNNYNYYNYNNNNN", "NNNNNYNNNYYYYNNYYNNNNNYNNYNYNNYYNNNNYYYYYNNNNNNNNN", "NNYYNYNNNNNNNNYNNNNYNYNNYNNNNYNNNYNNNYYNYNNYNNNNNN", "NNNNNNYNNNYYNYNNYYNNNNNNNNNNNNNNNYNNYNNNNNYNNNNNNN", "NNNYNNNNNYNNNNNNNNNYNYNYNYNNNYNNNYYYNNNNYNNNNNNNYN", "YNNYNYYNYYYNYNNNYNNYNYYNYNNNNNYYYNNNNNYYNNNNNNNNNN", "NNNNNYNYNNYNYNNNYNNNNYNNNNYNNYNNNYNNNYNYNNNNNNNYNN", "NNNNYYYNNNNYNNNYYNYYYNNNNYNNNNNNYNNNNNNNNNNNNNYNYN", "YNYYYYNYNNNNNNNYYNNNNNYYYNYNYNNNNNNNNNNNNNNNYNNYNY", "YNYNNNNNYNNNYYNNNNNNYNNNYNYNYNNYNNNYNNNNNNNNNNNNYN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case22() {
        int[] cityValues = { 527, 294, 32, 520 };
        String[] roads = { "NYYN", "YNYN", "YYNY", "NNYN" };
        assertEquals(814, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case23() {
        int[] cityValues = { 109, 583, 256, 1, 4, 694, 32, 32, 2, 64, 682 };
        String[] roads = { "NYNNYNYNNYN", "YNNNNNYNYYN", "NNNNNNNYYNY", "NNNNNYNYNYN", "YNNNNYNNNNN", "NNNYYNNYYYY", "YYNNNNNNNNN", "NNYYNYNNNNY", "NYYNNYNNNNN", "YYNYNYNNNNN", "NNYNNYNYNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case24() {
        int[] cityValues = { 16, 256, 32, 128, 16, 1, 195, 188, 256, 64, 32, 323, 818, 199, 690, 256 };
        String[] roads = { "NYNNYNNNNNNYYYNY", "YNYNYNNYYYYNNNNY", "NYNNNNYYNNYNNNNY", "NNNNYNYNNNYNYNYY", "YYNYNNNNNNNYYNNN", "NNNNNNNNNNNNYNNN", "NNYYNNNNNNNNYYNN", "NYYNNNNNYYNYNNYY", "NYNNNNNYNNNNNYNN", "NYNNNNNYNNYYYNNN", "NYYYNNNNNYNYYYNN", "YNNNYNNYNYYNNNYN", "YNNYYYYNNYYNNNYN", "YNNNNNYNYNYNNNNY", "NNNYNNNYNNNYYNNN", "YYYYNNNYNNNNNYNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case25() {
        int[] cityValues = { 128, 2, 261, 868, 655, 16, 16, 0, 512, 1, 256, 16, 269, 512, 16, 256, 338, 703, 256, 16, 1 };
        String[] roads = { "NNNNYNNYYYNNYYYNYYYYN", "NNYNNNNNNNYNNYNYNYNYN", "NYNNNNYYNNNNYYNNNNYNN", "NNNNYNNYNNNYYNYNYNNNY", "YNNYNNNNNNYYYYNNNNNYY", "NNNNNNNNNNNYNYNYNNNNN", "NNYNNNNNNNNNNYNNNNNNN", "YNYYNNNNNYNNNYNNNNNNN", "YNNNNNNNNNNNNNYNNNYNN", "YNNNNNNYNNNYNNYNYNNNN", "NYNNYNNNNNNNNYNNYNNNN", "NNNYYYNNNYNNNNNNNYNYN", "YNYYYNNNNNNNNYNYNNNYN", "YYYNYYYYNNYNYNNNYYNNN", "YNNYNNNNYYNNNNNNNNYNN", "NYNNNYNNNNNNYNNNNYNNY", "YNNYNNNNNYYNNYNNNNNNN", "YYNNNNNNNNNYNYNYNNYYN", "YNYNNNNNYNNNNNYNNYNNN", "YYNNYNNNNNNYYNNNNYNNY", "NNNYYNNNNNNNNNNYNNNYN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case26() {
        int[] cityValues = { 32, 16, 256, 64, 4, 4, 64, 16, 4, 8, 32, 909, 1, 269, 64, 1, 520, 128, 223, 453, 16, 8, 1, 512, 16, 8 };
        String[] roads = { "NNNNNYYYYNYNNYNYNNNNYNNNYN", "NNYYYYNNNYNNYNNNNYYYNYNYNN", "NYNYYYNNNNNNNNNNNYNNNNYNNN", "NYYNNNNNNNNNNNNYYNYNNYNNNN", "NYYNNNNNYNNNYYNYNNYNNNYNNN", "YYYNNNYYNYNYNYNYNYNNYNYYNN", "YNNNNYNNNYNNNNNNNYNNYNYYNY", "YNNNNYNNNNNNNNNNNYYNYYYNNN", "YNNNYNNNNNYNYNNNNYNYYNNYYN", "NYNNNYYNNNNNNNNYNYYNNYYNNN", "YNNNNNNNYNNNYNNNNNYNNYNNNN", "NNNNNYNNNNNNYNNYNNNYNNNYYN", "NYNNYNNNYNYYNNNYYNYYNYNNNY", "YNNNYYNNNNNNNNYYNNNYYYNNYY", "NNNNNNNNNNNNNYNNNNYYNNNYYN", "YNNYYYNNNYNYYYNNYNNNNYNNNN", "NNNYNNNNNNNNYNNYNYNNYNNYNN", "NYYNNYYYYYNNNNNNYNNNYYNNNN", "NYNYYNNYNYYNYNYNNNNYYNNNNN", "NYNNNNNNYNNYYYYNNNYNYNNYNY", "YNNNNYYYYNNNNYNNYYYYNNYNNN", "NYNYNNNYNYYNYYNYNYNNNNNNNN", "NNYNYYYYNYNNNNNNNNNNYNNNYN", "NYNNNYYNYNNYNNYNYNNYNNNNYN", "YNNNNNNNYNNYNYYNNNNNNNYYNN", "NNNNNNYNNNNNYYNNNNNYNNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case27() {
        int[] cityValues = { 32, 128, 890, 1, 32, 32, 256, 256, 2, 512, 1, 16, 4, 64, 248, 32, 1, 32, 256, 8, 4, 4, 128, 64, 64, 256, 64, 191, 487, 28, 32, 8, 4, 197, 8, 128, 8, 8, 861, 623, 16, 256, 8, 128, 64, 2, 16, 64, 256 };
        String[] roads = { "NNYYNYNNYNYNNNNYNYNNNNNNYNNNNNNYNNYNYYNYNYNYNNNYN", "NNYYNNYNNNNNNNNYYYYNNNYYNYNYNYNNNNNNNNNYNNYNNNNNN", "YYNNYNNYNNNYYNNYNNNNNNYYNNNNNNYYYNYNNNNNNNYNYNNYN", "YYNNYNYYNNNNNNNNNNNYYNNYYNNNNYNNNNNNNYYYNNNYNNYYY", "NNYYNNNNNYNNYNNYYNYYNNYNNNYYNNNNNNNNNNYNNNYYNNNNY", "YNNNNNNNNNYNYNNYNNNNNNYYYNYYNNNYNNNNNNNNYNNNNNYNY", "NYNYNNNNNNNNYNNNNNNNNNYNNNNYNNNNYYNNYNYNNNNNNNNYY", "NNYYNNNNNYYNNNNNYYYNNNYNYNYNNNNNNNNNNNNNNNNYNNNNN", "YNNNNNNNNNNNNNNNNNNNNNYNNNYNNNNYNNNNYYYNYYNNNNNNN", "NNNNYNNYNNNNNNNYYNNNYNNYNNNNYYNNNNNNNNYNNNNNYNNNN", "YNNNNYNYNNNNNNNNNNYNNNNNYNYNNNYNYNYNNNNNNNNYNNNNN", "NNYNNNNNNNNNYNNNNNNNNNNNNNNNYNYYNNYNNNNNYNNNNYYNN", "NNYNYYYNNNNYNNNYNNNNNNNNYNNNNNNNYYNNNNYNYNNNYNYNN", "NNNNNNNNNNNNNNYNNNNNYYNNNNNNNNNYNYYNNNNNNNNNNNNNY", "NNNNNNNNNNNNNYNYNNNNNNYNNNNNNNNYNNNNNNNNNNNYNNYNY", "YYYNYYNNNYNNYNYNNNNYNNNNNNNYNNYYNNYNNNNNYYNYYYNNN", "NYNNYNNYNYNNNNNNNNNNNYNNNNNNNNNYNNYYYNNNNNNNYNYNN", "YYNNNNNYNNNNNNNNNNNNYYYNNNNNNNNYNNNNNNNNNNNYNNNNY", "NYNNYNNYNNYNNNNNNNNNNNYNYYNNYYNNNNNYNNNNYYNNNNNNY", "NNNYYNNNNNNNNNNYNNNNYYNYNNNNNYYNYNNYNYYYNNYNNNYYN", "NNNYNNNNNYNNNYNNNYNYNNYYNNYNYYNNNNYNNYNNYNNNNNNYN", "NNNNNNNNNNNNNYNNYYNYNNNYNYNNNNYYYNYYNNNYNYNNNNYYN", "NYYNYYYYYNNNNNYNNYYNYNNNNNNYNYNYNYNNYNNNNYNNNYNNN", "NYYYNYNNNYNNNNNNNNNYYYNNNNNNNYNNNYNNNYNNYYNNNNNNN", "YNNYNYNYNNYNYNNNNNYNNNNNNYNNYNYNYNYYNNNNYNYYNYNNY", "NYNNNNNNNNNNNNNNNNYNNYNNYNYNYNYNNNNNYNNYYNNNNYYYN", "NNNNYYNYYNYNNNNNNNNNYNNNNYNYNNNNNYYNNNNYNNNNYNNNN", "NYNNYYYNNNNNNNNYNNNNNNYNNNYNNNNYNYYNYNYYYNNYNYNYN", "NNNNNNNNNYNYNNNNNNYNYNNNYYNNNNNNNNNYNYNNNYNNYYNYN", "NYNYNNNNNYNNNNNNNNYYYNYYNNNNNNNYNYNNYNNNNNNYYYNNN", "NNYNNNNNNNYYNNNYNNNYNYNNYYNNNNNYNNNNNYYNNNNYNYNYY", "YNYNNYNNYNNYNYYYYYNNNYYNNNNYNYYNNNNNNNNNNNNYNYYNN", "NNYNNNYNNNYNYNNNNNNYNYNNYNNNNNNNNYNYNYNNYNNNNNYNN", "NNNNNNYNNNNNYYNNNNNNNNYYNNYYNYNNYNYNNNNNNNYYYNNNY", "YNYNNNNNNNYYNYNYYNNNYYNNYNYYNNNNNYNNNNNYNNNNNYYNY", "NNNNNNNNNNNNNNNNYNYYNYNNYNNNYNNNYNNNNNYYYNNNNNNNN", "YNNNNNYNYNNNNNNNYNNNNNYNNYNYNYNNNNNNNYYNNNYNNNNYN", "YNNYNNNNYNNNNNNNNNNYYNNYNNNNYNYNYNNNYNNYNYYYYNNNN", "NNNYYNYNYYNNYNNNNNNYNNNNNNNYNNYNNNNYYNNYYNNYYNYNN", "YYNYNNNNNNNNNNNNNNNYNYNNNYYYNNNNNNYYNYYNNYNYNNNNY", "NNNNNYNNYNNYYNNYNNYNYNNYYYNYNNNNYNNYNNYNNNNNNNNNY", "YNNNNNNNYNNNNNNYNNYNNYYYNNNNYNNNNNNNNYNYNNNNYYNNN", "NYYNYNNNNNNNNNNNNNNYNNNNYNNNNNNNNYNNYYNNNNNNNNYNY", "YNNYYNNYNNYNNNYYNYNNNNNNYNNYNYYYNYNNNYYYNNNNYNYNN", "NNYNNNNNNYNNYNNYYNNNNNNNNNYNYYNNNYNNNYYNNYNYNNNNY", "NNNNNNNNNNNYNNNYNNNNNNYNYYNYYYYYNNYNNNNNNYNNNNNNY", "NNNYNYNNNNNYYNYNYNNYNYNNNYNNNNNYYNYNNNYNNNYYNNNNN", "YNYYNNYNNNNNNNNNNNNYYYNNNYNYYNYNNNNNYNNNNNNNNNNNY", "NNNYYYYNNNNNNYYNNYYNNNNNYNNNNNYNNYYNNNNYYNYNYYNYN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case28() {
        int[] cityValues = { 912, 621, 441, 671, 756 };
        String[] roads = { "NNNYN", "NNNYN", "NNNYN", "YYYNY", "NNNYN" };
        assertEquals(1019, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case29() {
        int[] cityValues = { 526, 423, 276, 260, 450, 780, 533, 672, 544, 852, 811, 753 };
        String[] roads = { "NNYNNNNNNNNN", "NNYNNNNNNNNN", "YYNYYYYYYYYY", "NNYNNNNNNNNN", "NNYNNNNNNNNN", "NNYNNNNNNNNN", "NNYNNNNNNNNN", "NNYNNNNNNNNN", "NNYNNNNNNNNN", "NNYNNNNNNNNN", "NNYNNNNNNNNN", "NNYNNNNNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case30() {
        int[] cityValues = { 895, 887, 65, 627, 597, 591, 27, 874, 733, 477, 630, 361, 126, 150, 189, 159, 903 };
        String[] roads = { "NYNNNNNNNNNNNNNNN", "YNYYYYYYYYYYYYYYY", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case31() {
        int[] cityValues = { 82, 625, 640, 934, 79, 381, 271, 205, 396, 460, 364, 275, 12, 859, 126, 807, 810, 409, 153, 106, 721, 221 };
        String[] roads = { "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "YYYYYYYYYYYYYYYYNYYYYY", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case32() {
        int[] cityValues = { 592, 374, 344, 916, 236, 785, 792, 428, 652, 481, 851, 9, 848, 946, 472, 816, 728, 845, 863, 740, 465, 91, 124, 545, 707, 807, 983 };
        String[] roads = { "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "YYYYYYYYYYYYYYYYYYYYYNYYYYY", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case33() {
        int[] cityValues = { 865, 536, 590, 629, 404, 284, 285, 860, 764, 654, 32, 872, 481, 16, 989, 132, 962, 554, 599, 588, 103, 905, 954, 815, 863, 420, 187, 359, 693, 543, 575, 269, 55, 141, 139, 123, 425, 668, 983, 166, 55, 1015, 14, 536, 7, 1004, 669, 969, 534, 244 };
        String[] roads = { "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYY", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case34() {
        int[] cityValues = { 85, 128, 32, 64 };
        String[] roads = { "NYYY", "YNNN", "YNNN", "YNNN" };
        assertEquals(245, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case35() {
        int[] cityValues = { 32, 1, 2, 128, 945, 256, 963, 256, 256, 256, 1 };
        String[] roads = { "NNNNNYNNNNN", "NNNNNYNNNNN", "NNNNNYNNNNN", "NNNNNYNNNNN", "NNNNNYNNNNN", "YYYYYNYYYYY", "NNNNNYNNNNN", "NNNNNYNNNNN", "NNNNNYNNNNN", "NNNNNYNNNNN", "NNNNNYNNNNN" };
        assertEquals(995, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case36() {
        int[] cityValues = { 739, 4, 512, 221, 990, 32, 750, 937, 256, 2, 4, 64, 2, 499, 16, 512 };
        String[] roads = { "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNY", "YYYYYYYYYYYYYYYN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case37() {
        int[] cityValues = { 256, 128, 8, 128, 256, 16, 2, 512, 128, 16, 64, 8, 103, 8, 512, 932, 1, 256, 395, 64, 128 };
        String[] roads = { "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "YYYYYYYYYYYYYYYNYYYYY", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case38() {
        int[] cityValues = { 32, 256, 128, 2, 16, 665, 575, 256, 256, 4, 963, 8, 256, 16, 8, 723, 16, 4, 128, 4, 512, 961, 2, 753, 256, 64 };
        String[] roads = { "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "YYYYYNYYYYYYYYYYYYYYYYYYYY", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case39() {
        int[] cityValues = { 8, 8, 2, 1, 8, 8, 512, 128, 4, 512, 512, 1, 582, 1011, 4, 32, 8, 1, 821, 2, 2, 128, 16, 1, 2, 512, 659, 4, 60, 1, 2, 128, 64, 32, 512, 2, 256, 256, 256, 8, 512, 512, 241, 4, 1, 512, 1, 371, 512 };
        String[] roads = { "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "YYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYY", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case40() {
        int[] cityValues = { 965, 427, 985, 45, 1010, 52, 960, 736, 680, 774, 744, 919, 149, 431, 604, 481, 763, 975, 404, 371, 455, 400, 463, 703, 33, 471, 764, 92, 2, 267, 220, 779, 828, 181, 485, 680, 205, 390, 392, 60, 168, 932, 979, 318, 282, 559, 90, 677, 510, 797 };
        String[] roads = { "NNNYNYNNYNNNNNNNNNNNNYNNNNNNNNYNNNNNNNNYNNNNNNNNNY", "NNNYNNYNNNNYNYYNNNNYNNNNYNYNNNNNNNNNNNNNNNYYNYNYNN", "NNNNNNYNNNNYNNNNYNNNNNNNYYNNYNNNNYYNNNYNYNNNNNYNNN", "YYNNNNNNNNNNYNNYNYNNNYNYNNYNNNNNNNNNNYNNNNNYNNNNYN", "NNNNNNNYNNNNYNYNNYNNNNYNNNNYNNNNYNNNNNYNNNNNYNNNNN", "YNNNNNNNYYNNNNNNNNNNYNNNNNNNYNNNNYYNYNNNNNNNYNNNNN", "NYYNNNNYNNNNNYNYNNYNNYNYNNNNYNNNYNNYYNNNYNYNYYNNYN", "NNNNYNYNNNNNYYYNNYNNNNNYYNNYNNNNYNNNYYNNNNNNYNYNYN", "YNNNNYNNNYNNNNNNNNYNNYNYNNNNYYNYYYNNNNYYNYNNYNYNNN", "NNNNNYNNYNYNYYYNNYNNNNYYYNNYYNNNNNYYNNNYNYYYYNNNNY", "NNNNNNNNNYNNYNNNNNNNYYNNYNYNYNNYNNNYYNNNNNYNNNYYNN", "NYYNNNNNNNNNNNYNNYNYYNNNYYNNNYNYNNNNNYNNNYNNNNNNNN", "NNNYYNNYNYYNNNYNYYYYNNNNNNYYNYNNNNYNNNYYYNNNNNNNNN", "NYNNNNYYNYNNNNNNYYYNNNNNNNYNNNNYYNNNNNYYYNNNNNYNNN", "NYNNYNNYNYNYYNNNNNNNNYNNYYNYNNNYNNNNNNNNNNYNNYNYYY", "NNNYNNYNNNNNNNNNYNYYNNYNNNNNNYNNNNYNNNYNNNNNNNNNYN", "NNYNNNNNNNNNYYNYNNYNNNYNNNYNNNNNNNNNNYNNYNNYNNYNYY", "NNNYYNNYNYNYYYNNNNNNNNNNYNYNNYYNNNYNNNNNNNYYYNYNNY", "NNNNNNYNYNNNYYNYYNNNYNNNNNNNNNNNYYNNNYNNYYNNYNNNYN", "NYNNNNNNNNNYYNNYNNNNNYNNYYNYNNYNNYNNYNNNNYNNNNYNYN", "NNNNNYNNNNYYNNNNNNYNNNNNNNNNNNNYNYNYNYNNYNNNNNNYYN", "YNNYNNYNYNYNNNYNNNNYNNNNNNYNYNNNNNNNNNNNNNNNNYNYYN", "NNNNYNNNNYNNNNNYYNNNNNNNNNNNNYNNNNYYYYNYNNNNNNNNNN", "NNNYNNYYYYNNNNNNNNNNNNNNNNYNNYYNNNNYNYNNNYNNNNYNNY", "NYYNNNNYNYYYNNYNNYNYNNNNNNNNNYNNNNYNNYNNNNYNNNNNYN", "NNYNNNNNNNNYNNYNNNNYNNNNNNYNNNYNNNNYNNYNNNNYNNNNNN", "NYNYNNNNNNYNYYNNYYNNNYNYNYNNNYYNNNNNYNYNNNNNNNNNNN", "NNNNYNNYNYNNYNYNNNNYNNNNNNNNNYYYYNNNYNNNYYYYNYNNYY", "NNYNNYYNYYYNNNNNNNNNNYNNNNNNNNNNNNNNNYNYNNNNNNYYYN", "NNNNNNNNYNNYYNNYNYNNNNYYYNYYNNYNYNYNYNNNYYNYNNNNYN", "YNNNNNNNNNNNNNNNNYNYNNNYNYYYNYNNYNNNNNYNYNNYNNYNNN", "NNNNNNNNYNYYNYYNNNNNYNNNNNNYNNNNNYNNNNNNNNNNNNNYNN", "NNNNYNYYYNNNNYNNNNYNNNNNNNNYNYYNNNNNNNNYNNNNNYNNNN", "NNYNNYNNYNNNNNNNNNYYYNNNNNNNNNNYNNYNNNNNNNYNYNNYNY", "NNYNNYNNNYNNYNNYNYNNNNYNYNNNNYNNNYNNNNNNNYNNYNNNNN", "NNNNNNYNNYYNNNNNNNNNYNYYNYNNNNNNNNNNYNNNNYNYNNNNNY", "NNNNNYYYNNYNNNNNNNNYNNYNNNYYNYNNNNNYNYNYNNYYNYYYYN", "NNNYNNNYNNNYNNNNYNYNYNYYYNNNYNNNNNNNYNYNNNYNNNNNNN", "NNYNYNNNYNNNYYNYNNNNNNNNNYYNNNYNNNNNNYNYYNNNNYNNNY", "YNNNNNNNYYNNYYNNNNNNNNYNNNNNYNNNYNNNYNYNNNYYNYNYYN", "NNYNNNYNNNNNYYNNYNYNYNNNNNNYNYYNNNNNNNYNNYNYNYNNNN", "NNNNNNNNYYNYNNNNNNYYNNNYNNNYNYNNNNYYNNNNYNNNNNYNNN", "NYNNNNYNNYYNNNYNNYNNNNNNYNNYNNNNNYNNYYNYNNNYYNYYYN", "NYNYNNNNNYNNNNNNYYNNNNNNNYNYNYYNNNNYYNNYYNYNYYNYNN", "NNNNYYYYYYNNNNNNNYYNNNNNNNNNNNNNNYYNNNNNNNYYNYYYYY", "NYNNNNYNNNNNNNYNNNNNNYNNNNNYNNNNYNNNYNYYYNNYYNNNYN", "NNYNNNNYYNYNNYNNYYNYNNNYNNNNYNYNNNNNYNNNNYYNYNNYNN", "NYNNNNNNNNYNNNYNNNNNYYNNNNNNYNNYNYNNYNNYNNYYYNYNYN", "NNNYNNYYNNNNNNYYYNYYYYNNYNNYYYNNNNNNYNNYNNYNYYNYNN", "YNNNNNNNNYNNNNYNYYNNNNNYNNNYNNNNNYNYNNYNNNNNYNNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case41() {
        int[] cityValues = { 362, 756, 756, 680, 144, 725, 624, 69, 771, 399 };
        String[] roads = { "NNNNNNNNNN", "NNYYYYYYYN", "NYNYYNYNNY", "NYYNNNYNNY", "NYYNNYNNYN", "NYNNYNNYYY", "NYYYNNNYNN", "NYNNNYYNNN", "NYNNYYNNNN", "NNYYNYNNNN" };
        assertEquals(362, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case42() {
        int[] cityValues = { 565, 285, 115, 364, 227, 898, 567, 332, 106, 96, 1021, 542, 47, 160, 883, 224, 890, 314, 2, 1019 };
        String[] roads = { "NYYNNNNYYNYNYNYYNYNY", "YNNNYYNYYYNNYYYNNYYN", "YNNYNYYYNNNYYNNYNNYY", "NNYNNYYYYNNNYYYNYNNY", "NYNNNYYYYYYNYYNNNYYY", "NYYYYNYNNNYYNYNNYNYN", "NNYYYYNNYNNNYNNYNYYN", "YYYYYNNNYNNYYNYYNNYN", "YYNYYNYYNNYNNYYYYYNN", "NYNNYNNNNNYYYYYNYYNY", "YNNNYYNNYYNNNNYNYNYN", "NNYNNYNYNYNNYYYYNNNN", "YYYYYNYYNYNYNYNYNNYY", "NYNYYYNNYYNYYNNYNYNN", "YYNYNNNYYYYYNNNYYNNY", "YNYNNNYYYNNYYYYNYNNN", "NNNYNYNNYYYNNNYYNYNN", "YYNNYNYNYYNNNYNNYNNY", "NYYNYYYYNNYNYNNNNNNN", "YNYYYNNNNYNNYNYNNYNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case43() {
        int[] cityValues = { 268, 290, 691, 556, 905, 821, 540, 196, 354, 866, 551, 73, 644, 52, 787, 14, 566, 119, 637, 944, 584, 70, 608, 903, 387, 678, 129, 572, 333, 382 };
        String[] roads = { "NNNYYYYNYYNNYYYNNYYNYNNNYNNYYN", "NNYNNNNYNNYNNYYNNYNYNYYNYYNNNN", "NYNNNYYNNYYNYYNYNYYYYNYNYNYNNY", "YNNNNYNNYNYNNYNNYYNYYNNYNNNNNY", "YNNNNYNYNNYYNNNNNYYYNNNNYNYNYN", "YNYYYNNYYNNNYYYNNYNNYYNNYYYNNY", "YNYNNNNNNNYYNNYNYYNYNYYYYNNNNY", "NYNNYYNNNYNNNNNYYNYYYYYYYYYNYN", "YNNYNYNNNYYYYNNYNNYYYYYYNNYYNY", "YNYNNNNYYNYNNNNYYYNNYNYNYYNNNY", "NYYYYNYNYYNYNNNNYNNNNYNNYYYYNY", "NNNNYNYNYNYNNNYYNYYYYNNYYYNYNY", "YNYNNYNNYNNNNYNYYNNYNNYNYYNYYN", "YYYYNYNNNNNNYNNNNYNYYYNNYYNYNY", "YYNNNYYNNNNYNNNYNYNYYNNYYNYNNN", "NNYNNNNYYYNYYNYNNNYNYYNYYYNNYY", "NNNYNNYYNYYNYNNNNYYYYNYNNNYYYY", "YYYYYYYNNYNYNYYNYNNYYNYNYYNNYN", "YNYNYNNYYNNYNNNYYNNNNNYNYNYNYN", "NYYYYNYYYNNYYYYNYYNNNYNNYNNNYN", "YNYYNYNYYYNYNYYYYYNNNYYNYNYNNY", "NYNNNYYYYNYNNYNYNNNYYNNYNYNYYY", "NYYNNNYYYYNNYNNNYYYNYNNNYYYYYY", "NNNYNNYYYNNYNNYYNNNNNYNNNYNYYY", "YYYNYYYYNYYYYYYYNYYYYNYNNNNNNY", "NYNNNYNYNYYYYYNYNYNNNYYYNNYNNN", "NNYNYYNYYNYNNNYNYNYNYNYNNYNYNN", "YNNNNNNNYNYYYYNNYNNNNYYYNNYNYY", "YNNNYNNYNNNNYNNYYYYYNYYYNNNYNY", "NNYYNYYNYYYYNYNYYNNNYYYYYNNYYN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case44() {
        int[] cityValues = { 964, 645, 259, 223, 117, 316, 464, 673, 541, 441, 975, 262, 621, 753, 528, 3, 632, 16, 555, 140, 408, 49, 231, 574, 121, 198, 247, 724, 511, 131, 584, 451, 1021, 275, 593, 894, 429, 311, 543, 678 };
        String[] roads = { "NNYYNYNYNNYNNNYYNNNNNNNYNYYYNNYNYNNNNNNN", "NNNNYYYNYNNNYYNYYNYNNYNNYNNYNYNYYNYYYNNY", "YNNNYYNYYYNYNNYYNNYYYYNNNYYNYNYYNYNNNYYN", "YNNNNNYYYYYYYNYYYNYNNNYNYYNNNNNNYNNNYNYN", "NYYNNNYYNNYNNNNYNNNNNYYYYYYYYYNNYNNNNNNN", "YYYNNNYYYYNYYYYNYYNYNNNYYYNYNYYYNNYNYYYY", "NYNYYYNNNNYNNYYYYYYYNYYNYYYNNNYYYYNNYNNN", "YNYYYYNNNYYYYYYNYNYNYYNNYYYYYNNYYYYYYYNY", "NYYYNYNNNYNYNYYYNNYYNYYYNNYYNNYYYNNYNYNY", "NNYYNYNYYNNYNYNNNNNNNNYYNNNYYNNYNYNYNNYN", "YNNYYNYYNNNNNNNYYYYYNYYYYYNYNNNYNNYYNNNN", "NNYYNYNYYYNNNNNNNNYYYNNNYYNNYNYYYNYNNYYN", "NYNYNYNYNNNNNYYNNNYNNYNNYYNYNYNNNYNYYYYN", "NYNNNYYYYYNNYNYNYYYYYNYNNNNNYNNYNYNYNYNY", "YNYYNYYYYNNNYYNNYNYYNNNNYNYYNYNYNNYYNYNN", "YYYYYNYNYNYNNNNNYNNYNYNYNYNYNYNYYYNYYNNY", "NYNYNYYYNNYNNYYYNNYYYYNNNNYNNYYYYNYYNNYY", "NNNNNYYNNNYNNYNNNNYYYNYNNNNYNYYNYNNNYYYN", "NYYYNNYYYNYYYYYNYYNNYNNNYNYYYYYNNYNNYNYN", "NNYNNYYNYNYYNYYYYYNNNYNYNNYYNNNYNYNNNNNN", "NNYNNNNYNNNYNYNNYYYNNNNNYNYYNYYNYYYNYYYY", "NYYNYNYYYNYNYNNYYNNYNNNNYNNNNYYYYNNYNNYY", "NNNYYNYNYYYNNYNNNYNNNNNNNNNNYNYNYNYYYYYN", "YNNNYYNNYYYNNNNYNNNYNNNNNNYNNYNYYNNYNNNY", "NYNYYYYYNNYYYNYNNNYNYYNNNNYNYYYYYYYNNYNY", "YNYYYYYYNNYYYNNYNNNNNNNNNNNYNYNNYYYYNNYN", "YNYNYNYYYNNNNNYNYNYYYNNYYNNNNYYNYNYYNNYY", "YYNNYYNYYYYNYNYYNYYYYNNNNYNNYYYYNYYYYNYY", "NNYNYNNYNYNYNYNNNNYNNNYNYNNYNYNYNNNYYYYN", "NYNNYYNNNNNNYNYYYYYNYYNYYYYYYNNNYNNNNYNY", "YNYNNYYNYNNYNNNNYYYNYYYNYNYYNNNYYYYNYNNN", "NYYNNYYYYYYYNYYYYNNYNYNYYNNYYNYNYYNYYYYY", "YYNYYNYYYNNYNNNYYYNNYYYYYYYNNYYYNNYYYYNN", "NNYNNNYYNYNNYYNYNNYYYNNNYYNYNNYYNNYNYYYN", "NYNNNYNYNNYYNNYNYNNNYNYNYYYYNNYNYYNYYNNY", "NYNNNNNYYYYNYYYYYNNNNYYYNYYYYNNYYNYNNYNY", "NYNYNYYYNNNNYNNYNYYNYNYNNNNYYNYYYYYNNNNN", "NNYNNYNYYNNYYYYNNYNNYNYNYNNNYYNYYYNYNNYN", "NNYYNYNNNYNYYNNNYYYNYYYNNYYYYNNYNYNNNYNN", "NYNNNYNYYNNNNYNYYNNNYYNYYNYYNYNYNNYYNNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case45() {
        int[] cityValues = { 183, 306, 432, 834, 657, 260, 354, 14, 220, 223, 369, 500, 135, 599, 771, 32, 1012, 318, 910, 70, 480, 543, 637, 941, 50, 423, 685, 185, 104, 607, 603, 287, 430, 12, 249, 63, 384, 452, 791, 747, 675, 446, 223, 250, 74, 994, 767, 9, 928, 679 };
        String[] roads = { "NNYYNNNYNNYYYNYNYYYYYNYYNNYYNNYNNNYYYNNYNNYYYNNNNY", "NNNNNYNNNYYYYNYYNYYYNYNYYNYNNYYNNYYNYNNYYYNYNYYYNN", "YNNNNYNNNYNYYNNNNYYNYYNYNNYNYYYNNNNNNNYNYYYYNNNNYY", "YNNNNNNYNNNYNYYYYNYNNYYYYYYNNNNNNYYYNNYNNYNNNNNYYY", "NNNNNNYYYYYYYNYYNNYNNNNYNYYYYNYYYYYNYNYNYYNNNYNNNY", "NYYNNNNNNYYYYYNNNNYYYNYNNYNYNYYYNNYNNYNNYNNYYNNYNN", "NNNNYNNNYYNYNYNNNNYYNYYYNNYYNNNYYNNYNYYYNNYYYNNNYY", "YNNYYNNNYYNYNYNNNYNYNYNYYYYNYYNYYNNYYYYYNNYYNYNNYN", "NNNNYNYYNNYNNNYYNYYNNNYYYNNNYYNYYYYYNNNYYYYNNYNYYY", "NYYNYYYYNNYYNNYYNYYYYYNNYNNNYYNYYYNNNNNNNNYYYNYYYY", "YYNNYYNNYYNNNNNYNNNNYYNNYYYNNYYYNNNYYYYYNYNNYNNNYN", "YYYYYYYYNYNNYNNNYYNYNNNYYYYYYNYNNNYNYYYYNNYYYYNYNY", "YYYNYYNNNNNYNYYYNYYYNYNYNNYNYNYNYNNYYNYNYYNYYYYNNY", "NNNYNYYYNNNNYNNYNNYYNNYNYYNNYYYNYNNNYNYNNNNNNYYYYY", "YYNYYNNNYYNNYNNYNNYNNNNNNNYNYYYYYNNNYNNNYNYNYNYNNN", "NYNYYNNNYYYNYYYNYNYNYNNNYNYYYNNNYNYYNYYYYYNYNNNNNY", "YNNYNNNNNNNYNNNYNNYNNNNNNNYYYNNYNYNYNYYNNYYNNYNNYN", "YYYNNNNYYYNYYNNNNNYNYNYYYYNYYNYYYYNNNNNNNNNYNYYNYY", "YYYYYYYNYYNNYYYYYYNNNNYYYYNYYYYYYNYNNYNYYNYNNYYYNN", "YYNNNYYYNYNYYYNNNNNNYNNNNNNNNYNNNYYYYNYYYNYNNNYYNN", "YNYNNYNNNYYNNNNYNYNYNYNYNNYNNYNYNNNYNYYYYYNNNNYNNY", "NYYYNNYYNYYNYNNNNNNNYNYYNYNYNNNNYNYYYNNNYNYNYNNYYY", "YNNYNYYNYNNNNYNNNYYNNYNYNYNYYYYNNNNNNNYYYNNNNNNNNN", "YYYYYNYYYNNYYNNNNYYNYYYNYYNNNYNNYYNYNYNYNNNYYYYNYN", "NYNYNNNYYYYYNYNYNYYNNNNYNNYYNNNNYYYNNNNNNNYNNNYYNN", "NNNYYYNYNNYYNYNNNYYNNYYYNNNNNYNNYNNYYNNYNNYYYYNYYY", "YYYYYNYYNNYYYNYYYNNNYNNNYNNNYYNNYNNNYYYNNYYYNYNNNY", "YNNNYYYNNNNYNNNYYYYNNYYNYNNNYNYYNNYYNNYNYYNYYYYYNN", "NNYNYNNYYYNYYYYYYYYNNNYNNNYYNYYYNYYYNNYNYNYNYYNYYY", "NYYNNYNYYYYNNYYNNNYYYNYYNYYNYNYNYNYYNYNYNNYYNYYYNY", "YYYNYYNNNNYYYYYNNYYNNNYNNNNYYYNNNNYYYYNNNYNNYYYNYN", "NNNNYYYYYYYNNNYNYYYNYNNNNNNYYNNNNYNNYNYYNNYYNYYNYY", "NNNNYNYYYYNNYYYYNYYNNYNYYYYNNYNNNYNYNYNYYYYNNNNNNY", "NYNYYNNNYYNNNNNNYYNYNNNYYNNNYNNYYNYYNYYYYNNYYYYYNY", "YYNYYYNNYNNYNNNYNNYYNYNNYNNYYYYNNYNYNYNYNNYNYNYYNN", "YNNYNNYYYNYNYNNYYNNYYYNYNYNYYYYNYYYNYYYYNNNNNYNNNY", "YYNNYNNYNNYYYYYNNNNYNYNNNYYNNNYYNNNYNNYYYYNNNYYNNY", "NNNNNYYYNNYYNNNYYNYNYNNYNNYNNYYNYYYYNNNNNNNYNNYYNY", "NNYYYNYYNNYYYYNYYNNYYNYNNNYYYNNYNYNYYNNNYNYYYYNNYY", "YYNNNNYYYNYYNNNYNNYYYNYYNYNNNYNYYYYYYNNNNNYYNNNYYY", "NYYNYYNNYNNNYNYYNNYYYYYNNNNYYNNNYYNNYNYNNNYNYYYYYY", "NYYYYNNNYNYNYNNYYNNNYNNNNNYYNNYNYNNNYNNNNNYNNYNYYY", "YNYNNNYYYYNYNNYNYNYYNYNNYYYNYYNYYNYNNNYYYYNNNNNYYN", "YYYNNYYYNYNYYNNYNYNNNNNYNYYYNYNYNYNNNYYYNNNNNNNYYN", "YNNNNYYNNYYYYNYNNNNNNYNYNYNYYNYNNYYNNNYNYNNNNNYNNN", "NYNNYNNYYNNYYYNNYYYNNNNYNYYYYYYYNYNYYNYNYYNNNNYYNN", "NYNNNNNNNYNNYYYNNYYYYNNYYNNYNYYYNYYNYYNNYNNNYYNYNN", "NYNYNYNNYYNYNYNNNNYYNYNNYYNYYYNNNYYNNYNYYYYYNYYNYN", "NNYYNNYYYYYNNYNNYYNNNYNYNYNNYNYYNNNNNNYYYYYYNNNYNY", "YNYYYNYNYYNYYYNYNYNNYYNNNYYNYYNYYYNYYYYYYYNNNNNNYN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case46() {
        int[] cityValues = { 1, 16, 2, 64, 32, 128, 256, 512, 64, 128 };
        String[] roads = { "NYNNYYNYYN", "YNNYYNNYNY", "NNNNNYYYNY", "NYNNYYNYNN", "YYNYNYNYYY", "YNYYYNNYNY", "NNYNNNNYNY", "YYYYYYYNNN", "YNNNYNNNNN", "NYYNYYYNNN" };
        assertEquals(1011, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case47() {
        int[] cityValues = { 512, 64, 128, 512, 1, 512, 16, 512, 16, 8, 8, 1, 32, 16, 1, 1, 128, 16, 2, 128 };
        String[] roads = { "NYYNNYYNNYNYNNYYNNNY", "YNNNYYNNYYNNNYNYNYYN", "YNNNNYYNNNYNYYNNYYNY", "NNNNYYNYYNYYNNNNNNYN", "NYNYNNNNYYNYNYYNNYNY", "YYYYNNYYYYYNNYNYYNNY", "YNYNNYNNYYNNNNNYYYNN", "NNNYNYNNYNNNNNYNNYYN", "NYNYYYYYNYNYYNYNYNYY", "YYNNYYYNYNYYYNNNYYNN", "NNYYNYNNNYNNNYNNYYNN", "YNNYYNNNYYNNYNNYYYYY", "NNYNNNNNYYNYNYNNYNNN", "NYYNYYNNNNYNYNNNYNYN", "YNNNYNNYYNNNNNNNNYYN", "YYNNNYYNNNNYNNNNYNYN", "NNYNNYYNYYYYYYNYNNNN", "NYYNYNYYNYYYNNYNNNNY", "NYNYNNNYYNNYNYYYNNNN", "YNYNYYNNYNNYNNNNNYNN" };
        assertEquals(763, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case48() {
        int[] cityValues = { 4, 512, 256, 512, 32, 1, 59, 32, 128, 449, 128, 128, 512, 502, 754, 2, 8, 8, 512, 8, 645, 1, 2, 619, 8, 64, 64, 617, 116, 783 };
        String[] roads = { "NNNYYYNYYNYYNNNNNNNNNYNYYNYNYY", "NNYYNYNNNYNNYNNYYNYYYNNNNNNNNY", "NYNNNNYNYYYNYYNNNYYYYNNNYNNNNN", "YYNNYNNYYNNNYNYYNNNYNYNNNYYNNN", "YNNYNYNNYNNYYYNYYNYNNYNYNNNNNY", "YYNNYNYNNNYNNYNNNYYNYNYNNYYNNN", "NNYNNYNYNYYYYYYYNYNNNYYYYYYNNN", "YNNYNNYNNNNNYYYYNYYYYNYNNYNNNY", "YNYYYNNNNNYYNNNYYNYYYYYNYYYYNN", "NYYNNNYNNNNYYYNNNYNYNYNYYYNNNN", "YNYNNYYNYNNNNYYYNNNYNNNYNYYYNN", "YNNNYNYNYYNNYYNYNYYYYYYNNYNNNN", "NYYYYNYYNYNYNNYYYNYYNYYYNYYNYY", "NNYNYYYYNYYYNNNNNYYNYYYYNNNNNN", "NNNYNNYYNNYNYNNNYNNNNNYYYNYNYN", "NYNYYNYYYNYYYNNNYNNNYYYYYNNYYN", "NYNNYNNNYNNNYNYYNNNNYNYNNNNYYY", "NNYNNYYYNYNYNYNNNNNNNNYNNNYYYY", "NYYNYYNYYNNYYYNNNNNNYNNYNNYNYN", "NYYYNNNYYYYYYNNNNNNNYYNYNNNNNN", "NYYNNYNYYNNYNYNYYNYYNNYNNYYNNN", "YNNYYNYNYYNYYYNYNNNYNNNNYYNNYY", "NNNNNYYYYNNYYYYYYYNNYNNNNYNYNN", "YNNNYNYNNYYNYYYYNNYYNNNNYYYYYY", "YNYNNNYNYYNNNNYYNNNNNYNYNNNNYN", "NNNYNYYYYYYYYNNNNNNNYYYYNNYNNY", "YNNYNYYNYNYNYNYNNYYNYNNYNYNYNN", "NNNNNNNNYNYNNNNYYYNNNNYYNNYNNY", "YNNNNNNNNNNNYNYYYYYNNYNYYNNNNY", "YYNNYNNYNNNNYNNNYYNNNYNYNYNYYN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case49() {
        int[] cityValues = { 4, 32, 64, 8, 8, 1, 32, 32, 4, 8, 512, 461, 64, 23, 256, 1, 256, 102, 4, 512, 2, 64, 64, 823, 16, 8, 32, 4, 915, 16, 16, 4, 512, 1, 128, 16, 97, 4, 512, 16 };
        String[] roads = { "NNYNNYYNYYYNNYNNYNYYYYNNYYYNYYNYNYNNYYNY", "NNNNYNYYYNYNNYNNNYYYYYYNYNNYNNYYYNNYYNYY", "YNNNYYYYYYYNNNNNYNYYYYNYYYYYYNNNNNYYNNYN", "NNNNYNNNYNNNNYNNYNNYNNYNNYYYYNNYYYYNNYYY", "NYYYNNNYNYNYYYYYNYYYNYYNNYYYNNNNYNNYNNYY", "YNYNNNYYYYYYNNYYYNNNYNYNNYYNNYNNNYNYNNNY", "YYYNNYNYYNNYYNNNNNYYYNYYNNNYNYYYYYNNYYNY", "NYYNYYYNNNNYYNYNYYNNNNYYNNYNYNYYNYNYNNYN", "YYYYNYYNNYYNNNYNYNYYYNNYNNNYYYNYYYNYNNYY", "YNYNYYNNYNYYNNNNYNYYNYYNNYNNNYYYNNYNNYNN", "YYYNNYNNYYNNNNNNYNNNYYNNYNNYNYYNYYYNNYNY", "NNNNYYYYNYNNNNYNNYNYNYYNYNYYYNYNNYYYYYNN", "NNNNYNYYNNNNNYYNNYYNYNNYNYNYYYYYYYNYNYYN", "YYNYYNNNNNNNYNNNNNNYNNNNNNNYYNYYNYYYNNNN", "NNNNYYNYYNNYYNNYYNNNNYNYNNYYYNYNNNNNNYNY", "NNNNYYNNNNNNNNYNNNNYNNYNYNYYNNYNYNYYYYNN", "YNYYNYNYYYYNNNYNNNYYNYNYYYYNNYYNYYYYNNYN", "NYNNYNNYNNNYYNNNNNYYNYNYNYYYNYYYYYYYNYYY", "YYYNYNYNYYNNYNNNYYNYYYYYNYNNNYNYYYNNYYYN", "YYYYYNYNYYNYNYNYYYYNNYYNYYYYNYNNYNNYNNNN", "YYYNNYYNYNYNYNNNNNYNNYNYYYYNYYNNYNYNNNYN", "YYYNYNNNNYYYNNYNYYYYYNNNNYNYYYYNYYYNNYYN", "NYNYYYYYNYNYNNNYNNYYNNNNNYNNNYNNYNYNNNNY", "NNYNNNYYYNNNYNYNYYYNYNNNYYNYNNYNYYYYYYYY", "YYYNNNNNNNYYNNNYYNNYYNNYNNYNNNYYNYNYNYNY", "YNYYYYNNNYNNYNNNYYYYYYYYNNNYYYNYNNYYYYYY", "YNYYYYNYNNNYNNYYYYNYYNNNYNNYYYNNNYYNNYNN", "NYYYYNYNYNYYYYYYNYNYNYNYNYYNYNNYNYYYNNNN", "YNYYNNNYYNNYYYYNNNNNYYNNNYYYNNYYNNYNYNNY", "YNNNNYYNYYYNYNNNYYYYYYYNNYYNNNNNNYNYNNYN", "NYNNNNYYNYYYYYYYYYNNNYNYYNNNYNNNNNNNNNYN", "YYNYNNYYYYNNYYNNNYYNNNNNYYNYYNNNNYYNNYNN", "NYNYYNYNYNYNYNNYYYYYYYYYNNNNNNNNNYYNYNNY", "YNNYNYYYYNYYYYNNYYYNNYNYYNYYNYNYYNYNYNYN", "NNYYNNNNNYYYNYNYYYNNYYYYNYYYYNNYYYNNYYYY", "NYYNYYNYYNNYYYNYYYNYNNNYYYNYNYNNNNNNNYYN", "YYNNNNYNNNNYNNNYNNYNNNNYNYNNYNNNYYYNNYYY", "YNNYNNYNNYYYYNYYNYYNNYNYYYYNNNNYNNYYYNNN", "NYYYYNNYYNNNYNNNYYYNYYNYNYNNNYYNNYYYYNNN", "YYNYYYYNYNYNNNYNNYNNNNYYYYNNYNNNYNYNYNNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case50() {
        int[] cityValues = { 787, 16, 8, 567, 4, 32, 128, 2, 4, 168, 64, 806, 8, 2, 367, 887, 1, 16, 32, 164, 64, 535, 32, 1, 256, 512, 935, 2, 512, 503, 256, 1, 440, 16, 222, 512, 512, 509, 8, 16, 32, 2, 16, 512, 16, 767, 1, 808, 128, 128 };
        String[] roads = { "NYNYYYNYNYYNNNYYNNNYNYYYNNYNNYYYNNYNNYYNNYNNYNYNYN", "YNYNNNYYYYYNYYYYNNYNYNNNYYYYYYNYNNYYNNYNNYYNYYYYYY", "NYNNNNNNYYNNYYNYYYNNYNYNYYYYYYNNNYNNYYYYYNYNYNNYNN", "YNNNYNNNNYYYNYNNYNYYYYYNYYYYNYNNNNYNNYYYNNNNNNYYYN", "YNNYNNYNYNYYNNYYYYYNYYYYNYYNYNYNNNYYNNNYNNYYYNYNYN", "YNNNNNNNNNYYNYYYYNNYYYNNNYNYNNYNNNYNYYYYNNNYNNYYNY", "NYNNYNNNYYYNNNYYNNNYNYNYNNNNNYYYYYNNNNYNNYNYYNYYYY", "YYNNNNNNYNNYYNYNNYYYYYYNYYNYYNYYYYYNNYYYNNNYYYNYNN", "NYYNYNYYNYNYNNNYNNYYYYNYYNYNYNYYYNNNNNYYNNNYNNNNYN", "YYYYNNYNYNYNYNYYYYYNNYNNNYYNYYYNNNYNNNNYYNNYYNNNYY", "YYNYYYYNNYNNNNYNNNNNNNNNYNNNYYNNYNYNNYNYYYYNYYYYYN", "NNNYYYNYYNNNYYNYYYNYNYNNYNNNNYNYYYNNYNYNYNNNYYYNYN", "NYYNNNNYNYNYNYYYYNNYNNNYNYYNYNNYYYNNNNNNYYNYYYYNYY", "NYYYNYNNNNNYYNYYYYNNNYYYNNYYYNYNYNNYYNYYNNYYYYNYNY", "YYNNYYYYNYYNYYNYYYNNNNYNNNYNNNYYNNYYYNNYNNNNNYYYYY", "YYYNYYYNYYNYYYYNNNNNYYYYNNYNNNNNYYNYNYNYYYYYYNYNYY", "NNYYYYNNNYNYYYYNNYYNNYYNYYNNNNYNYYYNYYYNNNNYNYNNNN", "NNYNYNNYNYNYNYYNYNNNNNYNNYYYNNYNNNYYNYNYYYNYNNNNYN", "NYNYYNNYYYNNNNNNYNNNNNNYNNNNNNNYNYYNYYNYNYNNNNYYNN", "YNNYNYYYYNNYYNNNNNNNNNNYNYNYNNNYNNYYNYNYYNNNNYNNNY", "NYYYYYNYYNNNNNNYNNNNNYYNNYYNNNYNYNYNYYYNNNNNYYNYNN", "YNNYYYYYYYNYNYNYYNNNYNYNNNYNYNNNNYNNYNYYYNNNNYYNYY", "YNYYYNNYNNNNNYYYYYNNYYNNNYYNNNNYNNYYYYYNYNYNNYYNYN", "YNNNYNYNYNNNYYNYNNYYNNNNYYYYYNYYNYYNNNYNNNNYNYYYYY", "NYYYNNNYYNYYNNNNYNNNNNNYNYYNNYYYYNNYYNYYNNYNNNYNYN", "NYYYYYNYNYNNYNNNYYNYYNYYYNNNNYYNNNNYYYYYNNNNYYNYYY", "YYYYYNNNYYNNYYYYNYNNYYYYYNNNYYNNNNNYNYYYNYNNNYNYYY", "NYYYNYNYNNNNNYNNNYNYNNNYNNNNYYNYNYNYNYYYNNNNNYNNNN", "NYYNYNNYYYYNYYNNNNNNNYNYNNYYNYNNYNNNYYNYYYYYYYNNNN", "YYYYNNYNNYYYNNNNNNNNNNNNYYYYYNNNNNYNNYYNYYYNNNNNNN", "YNNNYYYYYYNNNYYNYYNNYNNYYYNNNNNYNNNNNNNNNYNYYNNNYY", "YYNNNNYYYNNYYNYNNNYYNNYYYNNYNNYNYYYYYNNYNNYYNYYNYN", "NNNNNNYYYNYYYYNYYNNNYNNNYNNNYNNYNNNYNNYYNYNYYNYNNY", "NNYNNNYYNNNYYNNYYNYNNYNYNNNYNNNYNNNNYYYYNNNYYNNYYY", "YYNYYYNYNYYNNNYNYYYYYNYYNNNNNYNYNNNYNYYNNYYNNNNYNN", "NYNNYNNNNNNNNYYYNYNYNNYNYYYYNNNYYNYNYNYNNYYNNNYNYN", "NNYNNYNNNNNYNYYNYNYNYYYNYYNNYNNYNYNYNYYYNNNNYNYYYY", "YNYYNYNYNNYNNNNYYYYYYNYNNYYYYYNNNYYNYNYYNNYYYNYNNN", "YYYYNYYYYNNYNYNNYNNNYYYYYYYYNYNNYYYYYYNNNYNNYYYYYN", "NNYYYYNYYYYNNYYYNYYYNYNNYYYYYNNYYYNNYYNNYNNYNYNYNY", "NNYNNNNNNYYYYNNYNYNYNYYNNNNNYYNNNNNNNNNYNNNNYYYNYY", "YYNNNNYNNNYNYNNYNYYNNNNNNNYNYYYNYNYYNNYNNNYNNYNNNN", "NYYNYNNNNNYNNYNYNNNNNNYNYNNNYYNYNNYYNYNNNYNYYNYNYN", "NNNNYYYYYYNNYYNYYYNNNNNYNNNNYNYYYYNNNYNYNNYNNNNNNN", "YYYNYNYYNYYYYYNYNNNNYNNNNYNNYNYNYYNNYYYNYNYNNNYYNY", "NYNNNNNYNNYYYYYNYNNYYYYYNYYYYNNYNNNNNNYYYYNNNNNYYY", "YYNYYYYNNNYYYNYYNNYNNYYYYNNNNNNYYNNYYYYNYNYNYNNYYN", "NYYYNYYYNNYNNYYNNNYNYNNYNYYNNNNNNYYNYNYYNNNNYYYNNY", "YYNYYNYNYYYYYNYYNYNNNYYYYYYNNNYYNYNYYNYNYNYNNYYNNY", "NYNNNYYNNYNNYYYYNNNYNYNYNYYNNNYNYYNNYNNYYNNNYYNYYN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case51() {
        int[] cityValues = { 37, 1, 19, 64, 42, 41, 64, 64, 54, 16, 256, 36, 64, 2, 4, 2, 62, 29, 58, 64, 1, 32, 16, 256, 17, 2, 17, 4, 1, 64, 21, 8, 256, 63, 3, 1, 43, 15, 8, 39, 41, 8, 16, 8, 16, 256, 64, 512, 45, 64 };
        String[] roads = { "NNNNNNYYYYNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNYNNNNNNNYNNNNNNNNNNNNNNNNYYNNNYYNN", "NNNNNYYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNYNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNYNNYNYNNNNNNYNNNNNNNNNNYNNNNNNNNNNN", "NNYNNNYNNNNNNNNYNNYNNNYYNNNYNYNNNNYNNNNNNNNYNNNNNN", "YNYNNYNYNNNNNNNYNNNNNNNNNNNNNNNNNNNYNNNNNNNNYNNYNN", "YNNYNNYNYNYYNNNNNNNNNNNNNNNNNNNNNNYNNYNNNNNNNNNNNN", "YNNNNNNYNNNNNNNNNNNNNNYNYNNNNNNNNNNYYYNNNNNNNYNNNY", "YNNNNNNNNNNNNNNNNYNYNYNYYNNNYNNNNYNNNNNNNNNNNNNNNY", "NNNNNNNYNNNNYNNNNNNNNYYNNNYYNNNNYNYYNNNNNNNNNNNNNN", "NNNNNNNYNNNNNNYNNNNYYNNNYNNYYNNNNNNNNNNNNNYNYNNNNN", "NNNNNNNNNNYNNNNNYNNNNYNNNNNNNNNNYNYNNYNYNNNYNYNNNN", "NNNNNNNNNNNNNNNYNNNNNNNNNYNNNNNNNNNNNNYNNNNNNNNYNN", "NNNNNNNNNNNYNNNNNYNYNNYYNNNNNYNNNNNNNNNYNNYNNYNNNN", "NNNNYYYNNNNNNYNNNYYNNYNNNYNYYNNNNNNNNNYYYNNYNNYNYN", "NYNNNNNNNNNNYNNNNNNNYNNNYYNNNYNNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNYNNNNYYNNNNNNYNNNYNNNNNYNNYNYYNNNNYNNNYNN", "NNNYYYNNNNNNNNNYNNNNNYNYNYNNNNNNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNYNYNNYNNNNNNYNYYYNNNNNNNNNNNYNNYNNNNNYNNN", "NNNNYNNNNNNYNNNNYNNNNYNNNYYNNNYNNNYNNNNNNNNNNYNYNY", "NNNNNNNNNYYNYNNYNNYYYNYNNNNNNNNYNYNNNNNNNNNNYNNNNN", "NNNNNYNNYNYNNNYNNYNNNYNNNNNNNNNNNYNNYNYNNYNNNNNNNN", "NNNNNYNNNYNNNNYNNNYYNNNNNNNNNNNNNNNNNNNNNNYNNNYNNN", "NYNNNNNNYYNYNNNNYNNYNNNNNNNNNNYNNNNNNYNNNYNNYNNNNN", "NNNNNNNNNNNNNYNYYNYYYNNNNNNYNNNNNNNNNNNYYNNNNNNNYN", "NNNNNNNNNNYNNNNNNYNNYNNNNNNNNYNNNNYNNNNNNYYNNNNYNN", "NNNNYYNNNNYYNNNYNNNNNNNNNYNNNYYNYNNNNNNNNNNNNNNNNN", "NNNNNNNNNYNYNNNYNNNNNNNNNNNNNYNNNNYNNNNNNNNYNNYNYN", "NNNNNYNNNNNNNNYNYNNNNNNNNNYYYNNNNNNNNYNNNNYNNNNNNN", "NNNNNNNNNNNNNNNNNNNNYNNNYNNYNNNNNYNNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNYNNNNNNNNNYNNNNNNN", "NNNNNNNNNNYNYNNNNYNNNNNNNNNYNNNYNNNYYNNNNNYNNNYNNN", "NNNNNNNNNYNNNNNNNNNNNYYNNNNNNNYNNNNNNNYNNYNNNNNNNN", "NNNNNYNYNNYNYNNNYNYNYNNNNNYNYNNNNNNYYNYNYNYNNNNNYN", "YNNNNNYNYNYNNNNNNYNNNNNNNNNNNNNNYNYNNNNNYNNYNNNYNN", "NNNNNNNNYNNNNNNNNNNNNNYNNNNNNNNNYNYNNNNNNYNNNNNNYN", "NNNNNNNYYNNNYNNNNYNYNNNNYNNNNYNNNNNNNNNNNYNNNNYNNN", "NNNNYNNNNNNNNYNYNYNNNNYNNNNNNNNNNYYNNNNYNNNNNNNNNY", "NNNNNNNNNNNNYNYYNNNNNNNNNYNNNNNNNNNNNNYNNNNNYNYYNN", "NNNNNNNNNNNNNNNYNNNYNNNNNYNNNNNNNNYYNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNNNNNNNYNYNYNNNNNNYNNYYNNNNNNNNNNNN", "NYNNNNNNNNNYNNYNNNNNNNNYNNYNNYNYYNYNNNNNNNNNYNNNNN", "NNNNNYNNNNNNYNNYNYNNNNNNNNNNYNNNNNNYNNNNNNNNNNNNNY", "NNNNNNYNNNNYNNNNNNNNNYNNYNNNNNNNNNNNNNNYNNYNNYNNNY", "NNNNNNNNYNNNYNYNNNNNYNNNNNNNNNNNNNNNNNNNNNNNYNNNNN", "NYNNNNNNNNNNNNNYNNNYNNNYNNNNYNNNYNNNNYNYNNNNNNNNNN", "NYNNNNYNNNNNNYNNNYNNYNNNNNYNNNNNNNNYNNNYNNNNNNNNNN", "NNNNNNNNNNNNNNNYNNNNNNNNNYNNYNNNNNYNYNNNNNNNNNNNNN", "NNNNNNNNYYNNNNNNNNNNYNNNNNNNNNYNNNNNNNYNNNNYYNNNNN" };
        assertEquals(895, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case52() {
        int[] cityValues = { 0, 7, 11, 5, 2 };
        String[] roads = { "NYNYY", "YNYNN", "NYNNN", "YNNNN", "YNNNN" };
        assertEquals(14, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case53() {
        int[] cityValues = { 728, 807, 991, 57, 985 };
        String[] roads = { "NNYNY", "NNNNY", "YNNNY", "NNNNY", "YYYYN" };
        assertEquals(998, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case54() {
        int[] cityValues = { 50, 1, 19, 64, 42, 41, 64, 64, 54, 16, 256, 36, 64, 2, 4, 2, 62, 29, 58, 64, 1, 32, 16, 256, 17, 2, 17, 4, 1, 64, 21, 8, 256, 63, 3, 1, 43, 15, 8, 39, 41, 8, 16, 8, 16, 256, 64, 512, 45, 64 };
        String[] roads = { "NNNNNNYYYYNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNYNNNNNNNYNNNNNNNNNNNNNNNNYYNNNYYNN", "NNNNNYYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNYNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNYNNYNYNNNNNNYNNNNNNNNNNYNNNNNNNNNNN", "NNYNNNYNNNNNNNNYNNYNNNYYNNNYNYNNNNYNNNNNNNNYNNNNNN", "YNYNNYNYNNNNNNNYNNNNNNNNNNNNNNNNNNNYNNNNNNNNYNNYNN", "YNNYNNYNYNYYNNNNNNNNNNNNNNNNNNNNNNYNNYNNNNNNNNNNNN", "YNNNNNNYNNNNNNNNNNNNNNYNYNNNNNNNNNNYYYNNNNNNNYNNNY", "YNNNNNNNNNNNNNNNNYNYNYNYYNNNYNNNNYNNNNNNNNNNNNNNNY", "NNNNNNNYNNNNYNNNNNNNNYYNNNYYNNNNYNYYNNNNNNNNNNNNNN", "NNNNNNNYNNNNNNYNNNNYYNNNYNNYYNNNNNNNNNNNNNYNYNNNNN", "NNNNNNNNNNYNNNNNYNNNNYNNNNNNNNNNYNYNNYNYNNNYNYNNNN", "NNNNNNNNNNNNNNNYNNNNNNNNNYNNNNNNNNNNNNYNNNNNNNNYNN", "NNNNNNNNNNNYNNNNNYNYNNYYNNNNNYNNNNNNNNNYNNYNNYNNNN", "NNNNYYYNNNNNNYNNNYYNNYNNNYNYYNNNNNNNNNYYYNNYNNYNYN", "NYNNNNNNNNNNYNNNNNNNYNNNYYNNNYNNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNYNNNNYYNNNNNNYNNNYNNNNNYNNYNYYNNNNYNNNYNN", "NNNYYYNNNNNNNNNYNNNNNYNYNYNNNNNNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNYNYNNYNNNNNNYNYYYNNNNNNNNNNNYNNYNNNNNYNNN", "NNNNYNNNNNNYNNNNYNNNNYNNNYYNNNYNNNYNNNNNNNNNNYNYNY", "NNNNNNNNNYYNYNNYNNYYYNYNNNNNNNNYNYNNNNNNNNNNYNNNNN", "NNNNNYNNYNYNNNYNNYNNNYNNNNNNNNNNNYNNYNYNNYNNNNNNNN", "NNNNNYNNNYNNNNYNNNYYNNNNNNNNNNNNNNNNNNNNNNYNNNYNNN", "NYNNNNNNYYNYNNNNYNNYNNNNNNNNNNYNNNNNNYNNNYNNYNNNNN", "NNNNNNNNNNNNNYNYYNYYYNNNNNNYNNNNNNNNNNNYYNNNNNNNYN", "NNNNNNNNNNYNNNNNNYNNYNNNNNNNNYNNNNYNNNNNNYYNNNNYNN", "NNNNYYNNNNYYNNNYNNNNNNNNNYNNNYYNYNNNNNNNNNNNNNNNNN", "NNNNNNNNNYNYNNNYNNNNNNNNNNNNNYNNNNYNNNNNNNNYNNYNYN", "NNNNNYNNNNNNNNYNYNNNNNNNNNYYYNNNNNNNNYNNNNYNNNNNNN", "NNNNNNNNNNNNNNNNNNNNYNNNYNNYNNNNNYNNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNYNNNNNNNNNYNNNNNNN", "NNNNNNNNNNYNYNNNNYNNNNNNNNNYNNNYNNNYYNNNNNYNNNYNNN", "NNNNNNNNNYNNNNNNNNNNNYYNNNNNNNYNNNNNNNYNNYNNNNNNNN", "NNNNNYNYNNYNYNNNYNYNYNNNNNYNYNNNNNNYYNYNYNYNNNNNYN", "YNNNNNYNYNYNNNNNNYNNNNNNNNNNNNNNYNYNNNNNYNNYNNNYNN", "NNNNNNNNYNNNNNNNNNNNNNYNNNNNNNNNYNYNNNNNNYNNNNNNYN", "NNNNNNNYYNNNYNNNNYNYNNNNYNNNNYNNNNNNNNNNNYNNNNYNNN", "NNNNYNNNNNNNNYNYNYNNNNYNNNNNNNNNNYYNNNNYNNNNNNNNNY", "NNNNNNNNNNNNYNYYNNNNNNNNNYNNNNNNNNNNNNYNNNNNYNYYNN", "NNNNNNNNNNNNNNNYNNNYNNNNNYNNNNNNNNYYNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNNNNNNNYNYNYNNNNNNYNNYYNNNNNNNNNNNN", "NYNNNNNNNNNYNNYNNNNNNNNYNNYNNYNYYNYNNNNNNNNNYNNNNN", "NNNNNYNNNNNNYNNYNYNNNNNNNNNNYNNNNNNYNNNNNNNNNNNNNY", "NNNNNNYNNNNYNNNNNNNNNYNNYNNNNNNNNNNNNNNYNNYNNYNNNY", "NNNNNNNNYNNNYNYNNNNNYNNNNNNNNNNNNNNNNNNNNNNNYNNNNN", "NYNNNNNNNNNNNNNYNNNYNNNYNNNNYNNNYNNNNYNYNNNNNNNNNN", "NYNNNNYNNNNNNYNNNYNNYNNNNNYNNNNNNNNYNNNYNNNNNNNNNN", "NNNNNNNNNNNNNNNYNNNNNNNNNYNNYNNNNNYNYNNNNNNNNNNNNN", "NNNNNNNNYYNNNNNNNNNNYNNNNNNNNNYNNNNNNNYNNNNYYNNNNN" };
        assertEquals(895, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case55() {
        int[] cityValues = { 0, 1023 };
        String[] roads = { "NY", "YN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case56() {
        int[] cityValues = { 8, 1 };
        String[] roads = { "NN", "NN" };
        assertEquals(8, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case57() {
        int[] cityValues = { 0, 3, 255 };
        String[] roads = { "NNN", "NNY", "NYN" };
        assertEquals(0, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case58() {
        int[] cityValues = { 0, 1, 2, 4, 8, 16, 32 };
        String[] roads = { "NYNNYNN", "YNYNNNN", "NYNYNNN", "NNYNNNN", "YNNNNYN", "NNNNYNY", "NNNNNYN" };
        assertEquals(63, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case59() {
        int[] cityValues = { 1 };
        String[] roads = { "N" };
        assertEquals(1, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case60() {
        int[] cityValues = { 666, 13, 78, 548, 511 };
        String[] roads = { "NYYYY", "YNNNN", "YNNNN", "YNNNN", "YNNNN" };
        assertEquals(987, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case61() {
        int[] cityValues = { 1, 512, 1 };
        String[] roads = { "NNY", "NNY", "YYN" };
        assertEquals(513, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case62() {
        int[] cityValues = { 4, 1, 3 };
        String[] roads = { "NYN", "YNY", "NYN" };
        assertEquals(7, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case63() {
        int[] cityValues = { 1, 4, 2, 2, 2 };
        String[] roads = { "NNYNN", "NNYYN", "YYNNN", "NYNNY", "NNNYN" };
        assertEquals(7, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case64() {
        int[] cityValues = { 0, 0, 5 };
        String[] roads = { "NYN", "YNY", "NYN" };
        assertEquals(5, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case65() {
        int[] cityValues = { 1, 2 };
        String[] roads = { "NN", "NN" };
        assertEquals(1, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case66() {
        int[] cityValues = { 2, 1, 5 };
        String[] roads = { "NYY", "YNY", "YYN" };
        assertEquals(7, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case67() {
        int[] cityValues = { 4, 1, 4, 6 };
        String[] roads = { "NYYN", "YNYY", "YYNN", "NYNN" };
        assertEquals(7, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case68() {
        int[] cityValues = { 12, 15, 742, 131, 623, 131, 153, 12, 74, 46, 253, 324 };
        String[] roads = { "NYYYYYYYYYYY", "YNYYYYYYYYYY", "YYNYYYYYYYYY", "YYYNYYYYYYYY", "YYYYNYYYYYYY", "YYYYYNYYYYYY", "YYYYYYNYYYYY", "YYYYYYYNYYYY", "YYYYYYYYNYYY", "YYYYYYYYYNYY", "YYYYYYYYYYNY", "YYYYYYYYYYYN" };
        assertEquals(1022, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case69() {
        int[] cityValues = { 1, 2, 4 };
        String[] roads = { "NNN", "NNN", "NNN" };
        assertEquals(1, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case70() {
        int[] cityValues = { 1, 5, 5 };
        String[] roads = { "NNN", "NNY", "NYN" };
        assertEquals(1, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case71() {
        int[] cityValues = { 197, 584, 952, 236, 592, 514, 230, 603, 805, 255, 750, 189, 102, 674, 842, 784, 613, 743, 460, 163, 786, 744, 261, 852, 333, 814, 585, 656, 626, 691, 734, 623 };
        String[] roads = { "NNYYYNYNNYYNYYYNYNYYNYYNYNYNNNYN", "NNYYYNYNYNNYYNNNNYNYNYNYYNYNYNNY", "YYNYNYYYYYYYNNYYNYNYNYNNYYNYNNYN", "YYYNNNNYNYNNYYNNNYYYYNNNYYNYNNYN", "YYNNNYYYNNNNNYYNYNNNNNYYYYNNYNNN", "NNYNYNYYYYNYYYNNYYNNYYYYYNNNYYYN", "YYYNYYNNNNNYYNNYYYYNNNNYNNYYYYYN", "NNYYYYNNYNYYYYNNNYYNYYNYYNYNNNNN", "NYYNNYNYNYNNNYNNYYNNNNNYNYYYYYYY", "YNYYNYNNYNYYYYYNNYNNNNYNYYYYNYYN", "YNYNNNNYNYNYYNNYNYNYNYNNYNNYYNNY", "NYYNNYYYNYYNNNYYNYYNYNYYNYNYNNNN", "YYNYNYYYNYYNNNYYYNNYNYYYNYYNNNYN", "YNNYYYNYYYNNNNNYNNNNNYYNYNNYYNNY", "YNYNYNNNNYNYYNNYYYYNNYNYYYYYNYNY", "NNYNNNYNNNYYYYYNYYNYYNNNNNYNYNYY", "YNNNYYYNYNNNYNYYNNNYNYYNYNNNYNNN", "NYYYNYYYYYYYNNYYNNNYYNNYNNYNNYNN", "YNNYNNYYNNNYNNYNNNNYNYNNNNNNNNNY", "YYYYNNNNNNYNYNNYYYYNNYYNYYYYNNYN", "NNNYNYNYNNNYNNNYNYNNNNYNYYYNNNNY", "YYYNNYNYNNYNYYYNYNYYNNYYYYNYYYYY", "YNNNYYNNNYNYYYNNYNNYYYNYNNYNNNNN", "NYNNYYYYYNNYYNYNNYNNNYYNYNYNYYNN", "YYYYYYNYNYYNNYYNYNNYYYNYNYYYNYNY", "NNYYYNNNYYNYYNYNNNNYYYNNYNNYNNNY", "YYNNNNYYYYNNYNYYNYNYYNYYYNNNYYYY", "NNYYNNYNYYYYNYYNNNNYNYNNYYNNYYYY", "NYNNYYYNYNYNNYNYYNNNNYNYNNYYNNYY", "NNNNNYYNYYNNNNYNNYNNNYNYYNYYNNNY", "YNYYNYYNYYNNYNNYNNNYNYNNNNYYYNNN", "NYNNNNNNYNYNNYYYNNYNYYNNYYYYYYNN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case72() {
        int[] cityValues = { 15, 33 };
        String[] roads = { "NY", "YN" };
        assertEquals(46, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case73() {
        int[] cityValues = { 1, 2, 4, 8, 16, 32, 64, 128, 256 };
        String[] roads = { "NYNNNNNNN", "YNYNNNNNN", "NYNYNNNNN", "NNYNYNNNN", "NNNYNYNNN", "NNNNYNYNN", "NNNNNYNYN", "NNNNNNYNY", "NNNNNNNYN" };
        assertEquals(511, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case74() {
        int[] cityValues = { 37, 1, 19, 64, 42, 41, 64, 64, 54, 16, 256, 36, 64, 2, 4, 2, 62, 29, 58, 64, 1, 32, 16, 256, 17, 2, 17, 4, 1, 64, 21, 8, 256, 63, 3, 1, 43, 15, 8, 39, 41, 8, 16, 8, 16, 256, 64, 512, 45, 64 };
        String[] roads = { "NNNNNNYYYYNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNYNNNNNNNYNNNNNNNNNNNNNNNNYYNNNYYNN", "NNNNNYYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNYNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNYNNYNYNNNNNNYNNNNNNNNNNYNNNNNNNNNNN", "NNYNNNYNNNNNNNNYNNYNNNYYNNNYNYNNNNYNNNNNNNNYNNNNNN", "YNYNNYNYNNNNNNNYNNNNNNNNNNNNNNNNNNNYNNNNNNNNYNNYNN", "YNNYNNYNYNYYNNNNNNNNNNNNNNNNNNNNNNYNNYNNNNNNNNNNNN", "YNNNNNNYNNNNNNNNNNNNNNYNYNNNNNNNNNNYYYNNNNNNNYNNNY", "YNNNNNNNNNNNNNNNNYNYNYNYYNNNYNNNNYNNNNNNNNNNNNNNNY", "NNNNNNNYNNNNYNNNNNNNNYYNNNYYNNNNYNYYNNNNNNNNNNNNNN", "NNNNNNNYNNNNNNYNNNNYYNNNYNNYYNNNNNNNNNNNNNYNYNNNNN", "NNNNNNNNNNYNNNNNYNNNNYNNNNNNNNNNYNYNNYNYNNNYNYNNNN", "NNNNNNNNNNNNNNNYNNNNNNNNNYNNNNNNNNNNNNYNNNNNNNNYNN", "NNNNNNNNNNNYNNNNNYNYNNYYNNNNNYNNNNNNNNNYNNYNNYNNNN", "NNNNYYYNNNNNNYNNNYYNNYNNNYNYYNNNNNNNNNYYYNNYNNYNYN", "NYNNNNNNNNNNYNNNNNNNYNNNYYNNNYNNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNYNNNNYYNNNNNNYNNNYNNNNNYNNYNYYNNNNYNNNYNN", "NNNYYYNNNNNNNNNYNNNNNYNYNYNNNNNNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNYNYNNYNNNNNNYNYYYNNNNNNNNNNNYNNYNNNNNYNNN", "NNNNYNNNNNNYNNNNYNNNNYNNNYYNNNYNNNYNNNNNNNNNNYNYNY", "NNNNNNNNNYYNYNNYNNYYYNYNNNNNNNNYNYNNNNNNNNNNYNNNNN", "NNNNNYNNYNYNNNYNNYNNNYNNNNNNNNNNNYNNYNYNNYNNNNNNNN", "NNNNNYNNNYNNNNYNNNYYNNNNNNNNNNNNNNNNNNNNNNYNNNYNNN", "NYNNNNNNYYNYNNNNYNNYNNNNNNNNNNYNNNNNNYNNNYNNYNNNNN", "NNNNNNNNNNNNNYNYYNYYYNNNNNNYNNNNNNNNNNNYYNNNNNNNYN", "NNNNNNNNNNYNNNNNNYNNYNNNNNNNNYNNNNYNNNNNNYYNNNNYNN", "NNNNYYNNNNYYNNNYNNNNNNNNNYNNNYYNYNNNNNNNNNNNNNNNNN", "NNNNNNNNNYNYNNNYNNNNNNNNNNNNNYNNNNYNNNNNNNNYNNYNYN", "NNNNNYNNNNNNNNYNYNNNNNNNNNYYYNNNNNNNNYNNNNYNNNNNNN", "NNNNNNNNNNNNNNNNNNNNYNNNYNNYNNNNNYNNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNYNNNNNNNNNYNNNNNNN", "NNNNNNNNNNYNYNNNNYNNNNNNNNNYNNNYNNNYYNNNNNYNNNYNNN", "NNNNNNNNNYNNNNNNNNNNNYYNNNNNNNYNNNNNNNYNNYNNNNNNNN", "NNNNNYNYNNYNYNNNYNYNYNNNNNYNYNNNNNNYYNYNYNYNNNNNYN", "YNNNNNYNYNYNNNNNNYNNNNNNNNNNNNNNYNYNNNNNYNNYNNNYNN", "NNNNNNNNYNNNNNNNNNNNNNYNNNNNNNNNYNYNNNNNNYNNNNNNYN", "NNNNNNNYYNNNYNNNNYNYNNNNYNNNNYNNNNNNNNNNNYNNNNYNNN", "NNNNYNNNNNNNNYNYNYNNNNYNNNNNNNNNNYYNNNNYNNNNNNNNNY", "NNNNNNNNNNNNYNYYNNNNNNNNNYNNNNNNNNNNNNYNNNNNYNYYNN", "NNNNNNNNNNNNNNNYNNNYNNNNNYNNNNNNNNYYNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNNNNNNNYNYNYNNNNNNYNNYYNNNNNNNNNNNN", "NYNNNNNNNNNYNNYNNNNNNNNYNNYNNYNYYNYNNNNNNNNNYNNNNN", "NNNNNYNNNNNNYNNYNYNNNNNNNNNNYNNNNNNYNNNNNNNNNNNNNY", "NNNNNNYNNNNYNNNNNNNNNYNNYNNNNNNNNNNNNNNYNNYNNYNNNY", "NNNNNNNNYNNNYNYNNNNNYNNNNNNNNNNNNNNNNNNNNNNNYNNNNN", "NYNNNNNNNNNNNNNYNNNYNNNYNNNNYNNNYNNNNYNYNNNNNNNNNN", "NYNNNNYNNNNNNYNNNYNNYNNNNNYNNNNNNNNYNNNYNNNNNNNNNN", "NNNNNNNNNNNNNNNYNNNNNNNNNYNNYNNNNNYNYNNNNNNNNNNNNN", "NNNNNNNNYYNNNNNNNNNNYNNNNNNNNNYNNNNNNNYNNNNYYNNNNN" };
        assertEquals(895, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case75() {
        int[] cityValues = { 0, 20 };
        String[] roads = { "NN", "NN" };
        assertEquals(0, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case76() {
        int[] cityValues = { 1, 100 };
        String[] roads = { "NN", "NN" };
        assertEquals(1, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case77() {
        int[] cityValues = { 1, 8, 2, 4 };
        String[] roads = { "NNYY", "NNNN", "YNNN", "YNNN" };
        assertEquals(7, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case78() {
        int[] cityValues = { 0, 11, 6, 4 };
        String[] roads = { "NYYY", "YNNN", "YNNN", "YNNN" };
        assertEquals(15, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case79() {
        int[] cityValues = { 556 };
        String[] roads = { "N" };
        assertEquals(556, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case80() {
        int[] cityValues = { 1, 2, 31 };
        String[] roads = { "NYN", "YNY", "NYN" };
        assertEquals(31, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case81() {
        int[] cityValues = { 818, 165, 899, 4 };
        String[] roads = { "NNNN", "NNYN", "NYNN", "NNNN" };
        assertEquals(818, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case82() {
        int[] cityValues = { 1, 11 };
        String[] roads = { "NN", "NN" };
        assertEquals(1, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case83() {
        int[] cityValues = { 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 359, 966, 105, 115, 81, 255, 74, 236, 809, 205, 186, 939, 498, 763, 483, 326, 124, 706, 84, 1016, 795, 488, 487, 909, 886, 346, 302, 611, 563, 927, 201, 922, 870, 306, 13, 951, 561, 88, 163, 346 };
        String[] roads = { "NYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYN" };
        assertEquals(1023, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case84() {
        int[] cityValues = { 138, 577, 27, 509, 184, 847, 872, 758, 626, 123, 20, 665, 973, 979, 781, 240, 68, 58, 948, 934, 870, 339, 51, 267, 971, 673, 16, 94, 588, 492 };
        String[] roads = { "NNNNNNNNNNNNNYNNNYYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNYNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNYNNNNNNNNYNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNYNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNYNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNYNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNNNNNNNYNNNN", "YNNNNNNNNNNNNNNNNNNYNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NYNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNYNNYNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNYNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNYNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNYNNNNNNNNNNNNNNNNNNNNNNNNNNN" };
        assertEquals(1019, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case85() {
        int[] cityValues = { 0, 2, 4, 5 };
        String[] roads = { "NYYY", "YNYY", "YYNY", "YYYN" };
        assertEquals(7, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case86() {
        int[] cityValues = { 264, 264, 64, 512 };
        String[] roads = { "NYNN", "YNYN", "NYNY", "NNYN" };
        assertEquals(840, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case87() {
        int[] cityValues = { 0, 7, 11, 5, 2 };
        String[] roads = { "NNNNN", "NNNNN", "NNNNN", "NNNNN", "NNNNN" };
        assertEquals(0, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case88() {
        int[] cityValues = { 1, 1023 };
        String[] roads = { "NN", "NN" };
        assertEquals(1, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case89() {
        int[] cityValues = { 0, 1 };
        String[] roads = { "NN", "NN" };
        assertEquals(0, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case90() {
        int[] cityValues = { 2, 32, 2, 64, 128, 32, 512, 4, 4, 2, 32, 512, 16, 2, 16, 16, 2, 32, 32, 0, 512, 64, 512, 64, 16, 0, 4, 128, 128, 32, 8, 64, 512, 16, 8, 256, 2, 256, 128, 128, 64, 128, 2, 128, 2, 16, 128, 4, 512, 32 };
        String[] roads = { "NYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYN" };
        assertEquals(1022, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case91() {
        int[] cityValues = { 0, 1, 0, 3 };
        String[] roads = { "NYNN", "YNNN", "NNNY", "NNYN" };
        assertEquals(1, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case92() {
        int[] cityValues = { 6, 2, 3 };
        String[] roads = { "NYY", "YNY", "YYN" };
        assertEquals(7, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case93() {
        int[] cityValues = { 37, 1, 19, 64, 42, 41, 64, 64, 54, 16, 256, 36, 64, 2, 4, 2, 62, 29, 58, 64, 1, 32, 16, 256, 17, 2, 17, 4, 1, 64, 21, 8, 256, 63, 3, 1, 43, 15, 8, 39, 41, 8, 16, 8, 16, 256, 64, 512, 45, 64 };
        String[] roads = { "NYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYN" };
        assertEquals(895, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case94() {
        int[] cityValues = { 10, 9, 111 };
        String[] roads = { "NYN", "YNY", "NYN" };
        assertEquals(111, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case95() {
        int[] cityValues = { 5, 6, 7 };
        String[] roads = { "NYY", "YNY", "YYN" };
        assertEquals(7, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case96() {
        int[] cityValues = { 5, 6, 6, 7 };
        String[] roads = { "NYYY", "YNYY", "YYNY", "YYYN" };
        assertEquals(7, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case97() {
        int[] cityValues = { 5, 1, 0, 3 };
        String[] roads = { "NYYN", "YNNY", "YNNN", "NYNN" };
        assertEquals(7, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case98() {
        int[] cityValues = { 0, 4, 8, 32, 512 };
        String[] roads = { "NYYYY", "YNNNN", "YNNNN", "YNNNN", "YNNNN" };
        assertEquals(556, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case99() {
        int[] cityValues = { 0, 10, 19 };
        String[] roads = { "NYN", "YNN", "NNN" };
        assertEquals(10, xortravelingsalesman.maxProfit(cityValues, roads));
    }

    @Test
    public void case100() {
        int[] cityValues = { 13, 7, 10, 5 };
        String[] roads = { "NYNN", "YNYN", "NYNY", "NNYN" };
        assertEquals(15, xortravelingsalesman.maxProfit(cityValues, roads));
    }

}
