package topc.test.graph;

import junit.framework.*;
import org.junit.Test;
import static org.junit.Assert.*;
import topc.graph.*;

public class EgalitarianismTest {
  Egalitarianism egalitarianism = new Egalitarianism();

  @Test
  public void case1() {
    String[] isFriend = { "NYN", "YNY", "NYN" };
    int d = 10;
    assertEquals(20, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case2() {
    String[] isFriend = { "NN", "NN" };
    int d = 1;
    assertEquals(-1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case3() {
    String[] isFriend = { "NNYNNN", "NNYNNN", "YYNYNN", "NNYNYY", "NNNYNN", "NNNYNN" };
    int d = 1000;
    assertEquals(3000, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case4() {
    String[] isFriend = { "NNYN", "NNNY", "YNNN", "NYNN" };
    int d = 584;
    assertEquals(-1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case5() {
    String[] isFriend = { "NYNYYYN", "YNNYYYN", "NNNNYNN", "YYNNYYN", "YYYYNNN", "YYNYNNY", "NNNNNYN" };
    int d = 5;
    assertEquals(20, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case6() {
    String[] isFriend = { "NYYNNNNYYYYNNNN", "YNNNYNNNNNNYYNN", "YNNYNYNNNNYNNNN", "NNYNNYNNNNNNNNN", "NYNNNNYNNYNNNNN", "NNYYNNYNNYNNNYN", "NNNNYYNNYNNNNNN", "YNNNNNNNNNYNNNN", "YNNNNNYNNNNNYNN", "YNNNYYNNNNNNNNY", "YNYNNNNYNNNNNNN", "NYNNNNNNNNNNNNY", "NYNNNNNNYNNNNYN", "NNNNNYNNNNNNYNN", "NNNNNNNNNYNYNNN" };
    int d = 747;
    assertEquals(2988, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case7() {
    String[] isFriend = { "NY", "YN" };
    int d = 0;
    assertEquals(0, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case8() {
    String[] isFriend = { "NYYNYNNNNN", "YNNNNYYNYN", "YNNYYYNNNN", "NNYNNYYNYN", "YNYNNNNNYY", "NYYYNNNNNY", "NYNYNNNYNN", "NNNNNNYNNY", "NYNYYNNNNN", "NNNNYYNYNN" };
    int d = 680;
    assertEquals(2040, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case9() {
    String[] isFriend = { "NYYYYYYYYYNYNNNYYYYYYNNYYYNYYYYY", "YNYYNYYYYYYYYYYYYYYYYYYYYYNYYNNY", "YYNYNYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYNYYYYYYYYYNNYYYYYYYYYYYYNYYYY", "YNNYNYYNYYYYYYYYYYNYYYYYYYYYYYYY", "YYYYYNYYYNYYYNYYYYYYNYNYYYYYYYYY", "YYYYYYNYNYNNYYYNYYNYYYYYYYYYYYNY", "YYYYNYYNNYYNYYYYYYNYNNYYYYYYYYYY", "YYYYYYNNNYYYYYYNYYYYYYYYYYYYNYYY", "YYYYYNYYYNYYYYYYYYNYYYYYYYYYYYYY", "NYYYYYNYYYNYYNYYYYYYYNYYYNYYYYYY", "YYYYYYNNYYYNYYNYYYYYYYYYYNYYNYYY", "NYYYYYYYYYYYNYYYYYYYYYYYNYYNYYYY", "NYYNYNYYYYNYYNNYYYYYNYYYNYYYYYYN", "NYYNYYYYYYYNYNNYYYYYYYYNYYYYNYYN", "YYYYYYNYNYYYYYYNYYYYYNYYYYYNNYYN", "YYYYYYYYYYYYYYYYNYNYNYNYYYNYYNNY", "YYYYYYYYYYYYYYYYYNYYNYYNYYYYYYYN", "YYYYNYNNYNYYYYYYNYNYYNYYNYYYYNYY", "YYYYYYYYYYYYYYYYYYYNYYYYYYYYYNYY", "YYYYYNYNYYYYYNYYNNYYNYYYYYYYYNYY", "NYYYYYYNYYNYYYYNYYNYYNYYYYYYNYYY", "NYYYYNYYYYYYYYYYNYYYYYNYYYYYYYYY", "YYYYYYYYYYYYYYNYYNYYYYYNYYYNNYYY", "YYYYYYYYYYYYNNYYYYNYYYYYNYNYYYYY", "YYYYYYYYYYNNYYYYYYYYYYYYYNYYYYYY", "NNYYYYYYYYYYYYYYNYYYYYYYNYNYYYYN", "YYYNYYYYYYYYNYYNYYYYYYYNYYYNYYYY", "YYYYYYYYNYYNYYNNYYYYYNYNYYYYNYYN", "YNYYYYYYYYYYYYYYNYNNNYYYYYYYYNYY", "YNYYYYNYYYYYYYYYNYYYYYYYYYYYYYNY", "YYYYYYYYYYYYYNNNYNYYYYYYYYNYNYYN" };
    int d = 341;
    assertEquals(682, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case10() {
    String[] isFriend = { "NYYY", "YNYY", "YYNN", "YYNN" };
    int d = 970;
    assertEquals(1940, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case11() {
    String[] isFriend = { "NYYYNNYNYNNNYNYYY", "YNYYNNNYYYNNYNNNY", "YYNNNYYYNNNNNNNYN", "YYNNYNYYYYNYYYYNN", "NNNYNYYYYNYYYYYNY", "NNYNYNYNNYNNYNYNY", "YNYYYYNNNNYNNYYYY", "NYYYYNNNYNNYNNNYY", "YYNYYNNYNYNYYNYYN", "NYNYNYNNYNNNNNNYN", "NNNNYNYNNNNNNYYYN", "NNNYYNNYYNNNYNNYN", "YYNYYYNNYNNYNYNYY", "NNNYYNYNNNYNYNNNN", "YNNYYYYNYNYNNNNYY", "YNYNNNYYYYYYYNYNN", "YYNNYYYYNNNNYNYNN" };
    int d = 669;
    assertEquals(2007, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case12() {
    String[] isFriend = { "NYYY", "YNYY", "YYNY", "YYYN" };
    int d = 777;
    assertEquals(777, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case13() {
    String[] isFriend = { "NNNNNNNNNYYNNNNYYNNNNNYNYNNNNYNN", "NNNYNNNYNYYNNNYNNNYNNYNNYNNNNYNN", "NNNNYNNNNNNYNYNNNNNNNNNNNNYNNNNN", "NYNNYYNNNNNNNNNNYNYNNNYYYYNYNNNN", "NNYYNNYYNNNNYYYNNNNNNNNNNNNNNYNY", "NNNYNNNNNNNNNNNYYNNNNNYNNNNYYNYN", "NNNNYNNNNYNNNNYNNNNNYNNNNNYNYNYN", "NYNNYNNNNNNNNNYNNYNNNNNNNNNNYNNN", "NNNNNNNNNNNNNYNNNNNNNYNNNYNYNYNN", "YYNNNNYNNNNNYNNNYNNNNNNYNYNNNNYY", "YYNNNNNNNNNNNNNNNYNNYYNNNNNNNYNN", "NNYNNNNNNNNNNNYNNNYNYNNNNNNNNNNN", "NNNNYNNNNYNNNNYYYNNYNNYNYNNYYNNY", "NNYNYNNNYNNNNNNNNNNYNNNNYNNNNYNN", "NYNNYNYYNNNYYNNNNNYYNNYNNNYNNNNN", "YNNNNYNNNNNNYNNNNNNYNNYNYNNNYNNN", "YNNYNYNNNYNNYNNNNNNYNNYNNYNNNNNY", "NNNNNNNYNNYNNNNNNNNNYNNNNNNNYNNN", "NYNYNNNNNNNYNNYNNNNNYNYYYNNNNYNY", "NNNNNNNNNNNNYYYYYNNNYNNNNNNNYNNN", "NNNNNNYNNNYYNNNNNYYYNNNNYNNYYNNN", "NYNNNNNNYNYNNNNNNNNNNNNNNNNNNYNN", "YNNYNYNNNNNNYNYYYNYNNNNYNNNNNNNN", "NNNYNNNNNYNNNNNNNNYNNNYNNNNYNNYY", "YYNYNNNNNNNNYYNYNNYNYNNNNNNNNNNN", "NNNYNNNNYYNNNNNNYNNNNNNNNNNNNNNN", "NNYNNNYNNNNNNNYNNNNNNNNNNNNYNNNY", "NNNYNYNNYNNNYNNNNNNNYNNYNNYNNNNY", "NNNNNYYYNNNNYNNYNYNYYNNNNNNNNYYN", "YYNNYNNNYNYNNYNNNNYNNYNNNNNNYNNN", "NNNNNYYNNYNNNNNNNNNNNNNYNNNNYNNY", "NNNNYNNNNYNNYNNNYNYNNNNYNNYYNNYN" };
    int d = 557;
    assertEquals(2228, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case14() {
    String[] isFriend = { "NYYYYYYYYNYNYYYYYYYYYYYYYYYYYNYNYYYYY", "YNYYYYYNYYYYYYYYYYYYNYYYYYNYYYYYYYYYY", "YYNYYYYYYNYYYNNYYYNYYYYYNYYYYYYYYYNYN", "YYYNYYYYNYYYNYYYYYYYYYYYYYNYYYYYNYYYY", "YYYYNYYYYYNNYYYYYYYYYYYYYYNYNNYYYYYYY", "YYYYYNNYYYYYNYNYYYYYYNYYYYYYYYYYYYYYY", "YYYYYNNYYYYYYYYNYYYYNYYYYYYYYYYYYYNYN", "YNYYYYYNYYYNYYNYYYNYYYNYYYYNYYNYYYNYY", "YYYNYYYYNYYYYYYYYYYYYYYNYYYYYYYYYYYYN", "NYNYYYYYYNNYYYYYNNYYYNYYYYNYYNYNYYYYY", "YYYYNYYYYNNNYNYNYYYYYYYYYYYYYYYYNNYNY", "NYYYNYYNYYNNYYYYYYNYYYYYYNYYYYYYYYYYN", "YYYNYNYYYYYYNYYYNYYNYYYYYNYNNYYYYNYYY", "YYNYYYYYYYNYYNYYYYYYYYYYYYYNYYYYYYYYY", "YYNYYNYNYYYYYYNYYYNYYYYYYYYYYYYYYNYNY", "YYYYYYNYYYNYYYYNYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYNYYNYYYNYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYNYYYYYYYNNYYYYYYYYYYYNYNYYYY", "YYNYYYYNYYYNYYNYYNNYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYNYYYYYYNNYYYYYYYYYNYYYYYY", "YNYYYYNYYYYYYYYYYYYNNYYYYNNYYYYYYYNYY", "YYYYYNYYYNYYYYYYYYYYYNYYYYYYYNYYYYYYY", "YYYYYYYNYYYYYYYYYYYYYYNYYYNNYYYYYYYYN", "YYYYYYYYNYYYYYYYYYYYYYYNYYYYYNYYNYYYY", "YYNYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYNY", "YYYYYYYYYYYNNYYYYYYYNYYYYNYYYNNYYYYNY", "YNYNNYYYYNYYYYYYYYYYNYNYYYNYYNYYYYYNY", "YYYYYYYNYYYYNNYYYYYYYYNYYYYNYNYYYYYYY", "YYYYNYYYYYYYNYYYYYYYYYYYYYYYNNYYNYYYY", "NYYYNYYYYNYYYYYYYYYYYNYNYNNNNNNYYYYYY", "YYYYYYYNYYYYYYYYYNYNYYYYYNYYYNNYYYYYY", "NYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYNYYYYY", "YYYNYYYYYYNYYYYYYNYYYYYNYYYYNYYYNYYYY", "YYYYYYYYYYNYNYNYYYYYYYYYYYYYYYYYYNYYY", "YYNYYYNNYYYYYYYYYYYYNYYYYYYYYYYYYYNYY", "YYYYYYYYYYNYYYNYYYYYYYYYNNNYYYYYYYYNY", "YYNYYYNYNYYNYYYYYYYYYYNYYYYYYYYYYYYYN" };
    int d = 284;
    assertEquals(568, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case15() {
    String[] isFriend = { "NYYYNYYNNYYYYYYYYYYYYYYYYYYYYNYYYYYYYYNYYYYY", "YNYNYNNYYYNNNYYNNYYNYYNYNYYYYYYNYYYNYYYYYYYY", "YYNYYYNYNYYYNYYYYYNNYNYYYYYYYYNYYYYNYYYYYYNY", "YNYNYNYYNYYYYYYNNYYYYYNYYYYNYNYYNNNYNYYYYYNY", "NYYYNYYYYYYYYYYYYYYYYYNYYYYYYYYNYYYYYYYYYYYY", "YNYNYNYNYNNYYYYYYYYYNYYYNYYNNYNYYNYYYYNYNYYY", "YNNYYYNYYYYYNNYYYYYYYNYYYYYYNYYYYNYYYYYYYYYY", "NYYYYNYNYYYNNYYYNNYYYYNYYNYYNYNYYYYYYYYYYYYN", "NYNNYYYYNNYYYYYYYNYYYYYNNNYYYYYYNYYYYYYYNYYN", "YYYYYNYYNNNYNYYYYYNYYNNNYYYYNYNYYYYYYYYYYYNY", "YNYYYNYYYNNYYYNYYYYYYYYYYYYYYNYYYYYYYNYYYYNY", "YNYYYYYNYYYNYYYYYYNYYYYNYYYYYYYYYYYYNYYNYNYY", "YNNYYYNNYNYYNNYYYYYYYYYYNYYYYYYYYYYYYYYYNYNY", "YYYYYYNYYYYYNNYNYYNYYYYYYYYYYYYYYYYYYYYYNYNY", "YYYYYYYYYYNYYYNYYYYYNNYYYYYYYYYYYNYYNYNYYYYY", "YNYNYYYYYYYYYNYNYYYYYYYYNYNYYYYYYYYYNYYYNYYY", "YNYNYYYNYYYYYYYYNYYYYNYYNYYYYYYYYYYNYYNNNYYN", "YYYYYYYNNYYYYYYYYNYYYYYYYYYYNYYYYNNYYNYNYYYY", "YYNYYYYYYNYNYNYYYYNYYYYYYYYYNYYYNNYYYYYYNYYY", "YNNYYYYYYYYYYYYYYYYNYYNNYYNNYYYYNYYYYYNYYYYY", "YYYYYNYYYYYYYYNYYYYYNYYNYYYYYYYYNNNYYYYYYNYY", "YYNYYYNYYNYYYYNYNYYYYNYYYYYYNNYYYYNYYYYYYYYY", "YNYNNYYNYNYYYYYYYYYNYYNYNYNYYYNYYYYYYYNYYNYY", "YYYYYYYYNNYNYYYYYYYNNYYNNYYYYNYYNYYYYNYYYYNY", "YNYYYNYYNYYYNYYNNYYYYYNNNYYYYYYNYYYYYYYYYNYY", "YYYYYYYNNYYYYYYYYYYYYYYYYNYYYYYNNYYYYYYYYNYN", "YYYYYYYYYYYYYYYNYYYNYYNYYYNYYNYYYYNYYYYYYYNY", "YYYNYNYYYYYYYYYYYYYNYYYYYYYNYYYNNYYYYYYYYYYY", "YYYYYNNNYNYYYYYYYNNYYNYYYYYYNYYYYNYNYNYYYYYY", "NYYNYYYYYYNYYYYYYYYYYNYNYYNYYNYYYYYYYNYYYYYY", "YYNYYNYNYNYYYYYYYYYYYYNYYYYYYYNYYYNYYNYYNYNY", "YNYYNYYYYYYYYYYYYYYYYYYYNNYNYYYNYYYYYYYYYYYY", "YYYNYYYYNYYYYYYYYYNNNYYNYNYNYYYYNNYYYYYYYYYN", "YYYNYNNYYYYYYYNYYNNYNYYYYYYYNYYYNNYYYYYYYYNY", "YYYNYYYYYYYYYYYYYNYYNNYYYYNYYYNYYYNYYYNYYYYY", "YNNYYYYYYYYYYYYYNYYYYYYYYYYYNYYYYYYNYYYYYYNY", "YYYNYYYYYYYNYYNNYYYYYYYYYYYYYYYYYYYYNYYYYYYY", "YYYYYYYYYYNYYYYYYNYYYYYNYYYYNNNYYYYYYNYNYYYY", "NYYYYNYYYYYYYYNYNYYNYYNYYYYYYYYYYYNYYYNYYYYY", "YYYYYYYYYYYNYYYYNNYYYYYYYYYYYYYYYYYYYNYNNYYY", "YYYYYNYYNYYYNNYNNYNYYYYYYYYYYYNYYYYYYYYNNYYN", "YYYYYYYYYYYNYYYYYYYYNYNYNNYYYYYYYYYYYYYYYNYY", "YYNNYYYYYNNYNNYYYYYYYYYNYYNYYYNYYNYNYYYYYYNN", "YYYYYYYNNYYYYYYYNYYYYYYYYNYYYYYYNYYYYYYYNYNN" };
    int d = 381;
    assertEquals(762, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case16() {
    String[] isFriend = { "NNNNNNNNNNYNNNNNNNNNNN", "NNNYNNNNNNNNNNNNNNNNNN", "NNNNYNNNYNNNNNNNNNNNNN", "NYNNNNNNNNNYNNNNNYYNNN", "NNYNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNYNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNYNN", "NNYNNNNNNNNNNNYNNNNNNN", "NNNNNNNNNNYNNNNNNYNNNN", "YNNNNNNNNYNNNNNNNNNNNN", "NNNYNYNNNNNNNNNNNNYNNN", "NNNNNNNNNNNNNNNNNNNNYN", "NNNNNNNNNNNNNNYNNNNNNY", "NNNNNNNNYNNNNYNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNN", "NNNYNNNNNYNNNNNNNNNNNN", "NNNYNNNNNNNYNNNNNNNNNN", "NNNNNNNYNNNNNNNNNNNNNN", "NNNNNNNNNNNNYNNNNNNNNN", "NNNNNNNNNNNNNYNNNNNNNN" };
    int d = 702;
    assertEquals(-1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case17() {
    String[] isFriend = { "NYYNYYYYYYNYNNNNYYYYNNNNNYNYYYNYNYNNYYYYY", "YNYYYNNYNNNNYNNYNYNYYYYYNYNYYNYNYNYNYNNYY", "YYNYYNYYNNNNNNNYYYYYYNYYYYNYYYNYYYNNYYNYY", "NYYNYYNNYNNYYYYYYYNNNYYNNYYNNYYYYNNNYYYYN", "YYYYNYYNNNYYNYNYYYNNYYYYNYNYNYNYNNYYYYNYY", "YNNYYNYYNYYNYYYNNNYYYNYYYYYNYNYYNYNYNYYYN", "YNYNYYNYYNNYNYNNYNYYYYYNYYNNYNNYNNNNYYYYN", "YYYNNYYNNYNNYYNYNNNNYYYYYNNNYYYYNNYNNYNNY", "YNNYNNYNNYYYYNNNNYNYYNYYYYYNYNYYYNYYYYYNY", "YNNNNYNYYNYNYYYYNNYYNNYNYYNNYNYNYYNNNNYYN", "NNNNYYNNYYNYYNYYYYYNYYNYYYYYNNYYYYNYNNNNN", "YNNYYNYNYNYNYYYNNYYYYNYYYYYYNYYYYNYNYNNYN", "NYNYNYNYYYYYNNYYNNYNYNYNYYNNNNYYYNYNNYYYN", "NNNYYYYYNYNYNNNYYYYNYYYYNYYNNYYNYNYYYYNYN", "NNNYNYNNNYYYYNNNYYNYYYYYYYYYYYYNNYNNYYNNY", "NYYYYNNYNYYNYYNNYNNYNYYNNYYNNNNNYYYYNNYYY", "YNYYYNYNNNYNNYYYNYNYNYYYNNYYYNYNYYYYNYNYN", "YYYYYNNNYNYYNYYNYNYYNYYYNNYYNYNYNYNYNYNYY", "YNYNNYYNNYYYYYNNNYNNNNNYNNNYYYNYNNNYNYNYN", "YYYNNYYNYYNYNNYYYYNNYNYNNNNYNYYYYYNYNYNNY", "NYYNYYYYYNYYYYYNNNNYNYNYNYYYYYYYYYYYYNNYN", "NYNYYNYYNNYNNYYYYYNNYNNNYNYYNNYNNYYYYYYNY", "NYYYYYYYYYNYYYYYYYNYNNNYNYYYNYYYNYNYNYYNN", "NYYNYYNYYNYYNYYNYYYNYNYNYNYYYYYNYYYYYYYNN", "NNYNNYYYYYYYYNYNNNNNNYNYNNYNYYNYNNNYNNYYY", "YYYYYYYNYYYYYYYYNNNNYNYNNNYYYYYNYYNYNYYNY", "NNNYNYNNYNYYNYYYYYNNYYYYYYNYNYYYYNNYYYYYY", "YYYNYNNNNNYYNNYNYYYYYYYYNYYNNNNNYYYNNYYYY", "YYYNNYYYYYNNNNYNYNYNYNNYYYNNNYYYYYYNYYYNY", "YNYYYNNYNNNYNYYNNYYYYNYYYYYNYNYNYNNYYNNYN", "NYNYNYNYYYYYYYYNYNNYYYYYNYYNYYNYYYNYYNNYY", "YNYYYYYYYNYYYNNNNYYYYNYNYNYNYNYNYNYYNNYYY", "NYYYNNNNYYYYYYNYYNNYYNNYNYYYYYYYNNNYYYYYN", "YNYNNYNNNYYNNNYYYYNYYYYYNYNYYNYNNNNYNNYNY", "NYNNYNNYYNNYYYNYYNNNYYNYNNNYYNNYNNNNYYNYN", "NNNNYYNNYNYNNYNYYYYYYYYYYYYNNYYYYYNNYYYYN", "YYYYYNYNYNNYNYYNNNNNYYNYNNYNYYYNYNYYNNYNN", "YNYYYYYYYNNNYYYNYYYYNYYYNYYYYNNNYNYYNNYNY", "YNNYNYYNYYNNYNNYNNNNNYYYYYYYYNNYYYNYYYNYY", "YYYYYYYNNYNYYYNYYYYNYNNNYNYYNYYYYNYYNNYNN", "YYYNYNNYYNNNNNYYNYNYNYNNYYYYYNYYNYNNNYYNN" };
    int d = 872;
    assertEquals(1744, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case18() {
    String[] isFriend = { "NYYNYNNNNNNNNYNNNNYNNYNYNNYNY", "YNNYYNNNYNNNYYNNNNNNNNNNNNNYN", "YNNNNNNYYYNYNNNNNYNNYYNNNYNNN", "NYNNNYNNNNNNNNNNNNNNNNNNNYNNN", "YYNNNNNNNNYNNNNNYNYYNYNNNYNNN", "NNNYNNYYNNNYNNNNNNNNYNNNYYYYN", "NNNNNYNNYNNNNNNYNNNYNNNYYNNNN", "NNYNNYNNNNNNNNNNNNNNNNNNNNNNN", "NYYNNNYNNNYNNNNNYNYNYNNNNNNNN", "NNYNNNNNNNNNNNYNNNNNNNNNYNNNN", "NNNNYNNNYNNYNYNNNNNNNNNYNNYYY", "NNYNNYNNNNYNYNNNNNNYNNNNYNNNN", "NYNNNNNNNNNYNNNYNNYNYNNYYNNYN", "YYNNNNNNNNYNNNNNNYNYNNYNNYNNN", "NNNNNNNNNYNNNNNNNNNNYNNNNNNNY", "NNNNNNYNNNNNYNNNNNNNNNNNNNYYN", "NNNNYNNNYNNNNNNNNNNNYNYYNNNNY", "NNYNNNNNNNNNNYNNNNNNNNYNNNYNN", "YNNNYNNNYNNNYNNNNNNNYNNNNNNNY", "NNNNYNYNNNNYNYNNNNNNYNNNNNYYN", "NNYNNYNNYNNNYNYNYNYYNYYYNNNNY", "YNYNYNNNNNNNNNNNNNNNYNYYNNNNN", "NNNNNNNNNNNNNYNNYYNNYYNNNNNNN", "YNNNNNYNNNYNYNNNYNNNYYNNNNNNY", "NNNNNYYNNYNYYNNNNNNNNNNNNNNNY", "NNYYYYNNNNNNNYNNNNNNNNNNNNNNN", "YNNNNYNNNNYNNNNYNYNYNNNNNNNNN", "NYNNNYNNNNYNYNNYNNNYNNNNNNNNN", "YNNNNNNNNNYNNNYNYNYNYNNYYNNNN" };
    int d = 80;
    assertEquals(240, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case19() {
    String[] isFriend = { "NYNYY", "YNYYY", "NYNNY", "YYNNY", "YYYYN" };
    int d = 921;
    assertEquals(1842, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case20() {
    String[] isFriend = { "NYYYYYYYYYNYYYYYYYY", "YNYYYYYYNYYNYYYYNNN", "YYNYYYYYYYYYYYYYYNY", "YYYNNYYYYYYYYYYYYYY", "YYYNNYYNYYYYYYYYNYY", "YYYYYNYYYYYYYYYYYYY", "YYYYYYNYYYYYYYYYYYY", "YYYYNYYNYYYYYYYNYYY", "YNYYYYYYNYYYYYYYYYY", "YYYYYYYYYNYYYYYYYYY", "NYYYYYYYYYNYYYYNNYY", "YNYYYYYYYYYNNYYYYYN", "YYYYYYYYYYYNNYYNNYN", "YYYYYYYYYYYYYNYYYYY", "YYYYYYYYYYYYYYNYYYY", "YYYYYYYNYYNYNYYNYYN", "YNYYNYYYYYNYNYYYNYY", "YNNYYYYYYYYYYYYYYNY", "YNYYYYYYYYYNNYYNYYN" };
    int d = 997;
    assertEquals(1994, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case21() {
    String[] isFriend = { "NYNYNNNYYNYYNNYNNNNNNNNNNNNNYYYYY", "YNNYNYYNYYYNYNNNYYYYYNNNYNYNYYNNY", "NNNYYNNYNYNNNNYYNYYNYNYNNYYYNNNNY", "YYYNNNNNNYNNNNYYYNNYYNYNYYYYYYYNY", "NNYNNYYYYNNYYYNNYYNNYYYNNYNYNYYYN", "NYNNYNYNYYYYYNYYNYYNYNNYYNYNYYNYN", "NYNNYYNNYYYYNYNNYYNNYNYYNNYNNNNYY", "YNYNYNNNNYYNYNYYYNYYNYNYYNYNNYNYY", "YYNNYYYNNNYYYNNNNYYNNNNNNNYYNYYYN", "NYYYNYYYNNYNYNYYYYNYNNYYYYNYYNYNY", "YYNNNYYYYYNYYYYNYNNNNYYYYNYNYNNNN", "YNNNYYYNYNYNNNYYNNNYYNYYNYNYYYYYY", "NYNNYYNYYYYNNYNYYYYYYNYYYYNNNYNYN", "NNNNYNYNNNYNYNNYNYNYYYYNYYNYNYNYY", "YNYYNYNYNYYYNNNNNYYYNYYYNNYYYYYNN", "NNYYNYNYNYNYYYNNNYNNYYYYYYYNYNYYN", "NYNYYNYYNYYNYNNNNYNNYNYNYYYYYNYNY", "NYYNYYYNYYNNYYYYYNYYYYNNNYYYNYNYY", "NYYNNYNYYNNNYNYNNYNNYNYNYNYYYYNNN", "NYNYNNNYNYNYYYYNNYNNNYYNYYNYNYYNN", "NYYYYYYNNNNYYYNYYYYNNNNYYNYYYNYYN", "NNNNYNNYNNYNNYYYNYNYNNYYNNNYYYYYY", "NNYYYNYNNYYYYYYYYNYYNYNYNNYYNNYNN", "NNNNNYYYNYYYYNYYNNNNYYYNYYYYNNYYY", "NYNYNYNYNYYNYYNYYNYYYNNYNNYYNYNYY", "NNYYYNNNNYNYYYNYYYNYNNNYNNYNYYYNN", "NYYYNYYYYNYNNNYYYYYNYNYYYYNNYNNYN", "NNYYYNNNYYNYNYYNYYYYYYYYYNNNNYNNY", "YYNYNYNNNYYYNNYYYNYNYYNNNYYNNNNNY", "YYNYYYNYYNNYYYYNNYYYNYNNYYNYNNNYY", "YNNYYNNNYYNYNNYYYNNYYYYYNYNNNNNYN", "YNNNYYYYYNNYYYNYNYNNYYNYYNYNNYYNY", "YYYYNNYYNYNYNYNNYYNNNYNYYNNYYYNYN" };
    int d = 591;
    assertEquals(1182, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case22() {
    String[] isFriend = { "NNNYNNNNNNNNNNNNNNNNNNNNNNYNNYNNNNNNNNNNNYNNNY", "NNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYN", "NNNNNNNNNNYNNNYNNNNNNNNNYNNNNNNNNNNNNNNNNNNNYN", "YNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNYNNYN", "NNNNNNNNNNNNNYNYNNNNYNNNNNNNNNNNYNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNYNNYNNNNNNNNYNYNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNN", "NYNNNNNNNNNNNYNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNYNNYNNNNNNNNNNNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNYNNNNNNNNNNNNNNNNNNYNNNNYNNNNNNNNYNNYNNNNNNN", "NNNNNNNNNNNNYNNNNNNNNNNNNNNNNNYNNNNNNYNYNNNNNN", "NNNNNNNNNNNYNNYNNNNYNNNNNNNNNNNNNNNNNNNYNNNNNN", "NNNNYNNYYNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNN", "NNYNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNN", "NNNNYNNNNNNNNNNNNNNNNNYNNNNNNNYYNNNNNNNNNNNNNN", "NNNNNNNNYNNNNNNNNNYYNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNYNNNNNNNNNNNYNNYNNNNYNNNNNNNNN", "NNNNNYNNNNNNYNNNYNNNNNNNNNNNNNYNNNNNNNNYNNNNNN", "NNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNY", "NNNNNNNYNNYNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNYNN", "NNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNYNNNYNNNNNNYNNN", "NNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "YNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNN", "NNNNNNNNNNNNNYNNNNNNNNNNNNNNYNNNNNNNNNNNNNNYNN", "NNNNNNNNNNNNNNNNNNYNNNNNNNNYNYNNNNNNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNYNNNNNNNNNNYNNNNNNNNNNNNNNYNN", "NNNNNNNNYNNYNNNYNNNYNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNYNNYNNNNYNNNNNNNNNNYNNNNNNNNNNN", "NNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNYNNN", "NNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNN", "NNNNNNNNNNYNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNYNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNYYNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNN", "YNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNN", "NNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNYNNNNNNNYNNNN", "NNNNNNNNNNNNNNNNNNNNNNYNNNNYNYNNNNNNNNNNNNNNNN", "NYYYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNN" };
    int d = 931;
    assertEquals(-1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case23() {
    String[] isFriend = { "NYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYNY", "YYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYNYYYYYYYYYYYYYNYYYYYYYYYYY", "YYYYYYYYYYYYYYYYNYYYYNYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYNYYYYNYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYNYYYY", "YYYYYYYYYYYYYYYNYYYYYYYYYYYYYNYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYNYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYY", "YYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYNY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYN" };
    int d = 434;
    assertEquals(868, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case24() {
    String[] isFriend = { "NYYYYYYYYYYYYYYYYYYYNYYY", "YNYYYYYYNYYYYYYYYNYNYYYY", "YYNYYYYYYYYYYYYYYYYYYYYY", "YYYNYYYYYYYYYYYYYYYYYYYY", "YYYYNYYYYYYYYYYYYYYYYYYY", "YYYYYNYYYYYYYYYYYYYYYYYY", "YYYYYYNYNYYYYYYYYYYYYYYY", "YYYYYYYNYYYYYYYYYYYYYYYY", "YNYYYYNYNYYYYNYYYYYYYYYY", "YYYYYYYYYNYYYYYYYYYYYYYY", "YYYYYYYYYYNYYYYYYYYYYYNY", "YYYYYYYYYYYNYYYYYYYYYYYY", "YYYYYYYYYYYYNYYYYYYYYYYY", "YYYYYYYYNYYYYNYYYYYYYYYY", "YYYYYYYYYYYYYYNYYYYYYYYY", "YYYYYYYYYYYYYYYNYYYYYYYY", "YYYYYYYYYYYYYYYYNYYYYYYY", "YNYYYYYYYYYYYYYYYNYYYYYY", "YYYYYYYYYYYYYYYYYYNYYYYY", "YNYYYYYYYYYYYYYYYYYNYYYY", "NYYYYYYYYYYYYYYYYYYYNYYY", "YYYYYYYYYYYYYYYYYYYYYNYY", "YYYYYYYYYYNYYYYYYYYYYYNY", "YYYYYYYYYYYYYYYYYYYYYYYN" };
    int d = 789;
    assertEquals(1578, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case25() {
    String[] isFriend = { "NYNNYNNNNNNNYNYYNNYNYNYYYNNN", "YNYNYYYNNYYYNNYNNNYNNNNNYYNN", "NYNYNNYYNNNNNNNNYNNNNYYYNNNN", "NNYNNYNYNNYYNNYNNYNNNNNNNNYN", "YYNNNNNNNYYNNNYNNNYYNNNNNYYN", "NYNYNNNNNNYNNNNNNNNNNNNNNYNN", "NYYNNNNNYYNNYYYNNNNYYNYYNNNN", "NNYYNNNNNNNYNNYNNNNNNNYNNNNN", "NNNNNNYNNNYNNNNNYNYYNYNNNNNN", "NYNNYNYNNNNNNYYYNNNYYNNNNYNN", "NYNYYYNNYNNYYNYNNNNNNYNYNNNN", "NYNYNNNYNNYNYYYNNNYNYYNNNNYN", "YNNNNNYNNNYYNNYNNNNYYNYNNNNN", "NNNNNNYNNYNYNNYYNYYYNNNNNNYN", "YYNYYNYYNYYYYYNNYYNYNYNNNNNN", "YNNNNNNNNYNNNYNNNYNNNNNYNNNN", "NNYNNNNNYNNNNNYNNYNYNNNNNYNN", "NNNYNNNNNNNNNYYYYNYNYYNYNNNY", "YYNNYNNNYNNYNYNNNYNNNYYNNNNN", "NNNNYNYNYYNNYYYNYNNNYYNNYNNN", "YNNNNNYNNYNYYNNNNYNYNNYNYNYY", "NNYNNNNNYNYYNNYNNYYYNNNNYYNN", "YNYNNNYYNNNNYNNNNNYNYNNYYYNY", "YNYNNNYNNNYNNNNYNYNNNNYNNNNN", "YYNNNNNNNNNNNNNNNNNYYYYNNNNN", "NYNNYYNNNYNNNNNNYNNNNYYNNNNN", "NNNYYNNNNNNYNYNNNNNNYNNNNNNN", "NNNNNNNNNNNNNNNNNYNNYNYNNNNN" };
    int d = 178;
    assertEquals(534, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case26() {
    String[] isFriend = { "NYNNNYYNNNNNNYNNNNNNNNNNNYYYYYNN", "YNNYYNNYYNYYYNYYYYNNNYYNNNNNYNYN", "NNNYNNYNNNNYNNNNYNNNYNNYNYYNNNNN", "NYYNNNYYNNNNYNNNNYNNYNNNYNYNNNNN", "NYNNNNNNNNNYYNNNNNNYNNYNNNNYNNNN", "YNNNNNYNNNNNNYNNNYNYNYNNYYNNNNYY", "YNYYNYNYNNNNYYYNNNYNNYYNYYYNYYYN", "NYNYNNYNNNNNNNYYNYYYYNNYYYNNYYNY", "NYNNNNNNNYNNYNNNNNYYYNNNNNNNNNYY", "NNNNNNNNYNYNNYNYNYYNYYYYYYNYNYYN", "NYNNNNNNNYNNYNNNYNNNYYNYYNNYNNYY", "NYYNYNNNNNNNNNYYNYNNYNNNNNNNNNNN", "NYNYYNYNYNYNNNYYNNYYNYNNNNNYNNNN", "YNNNNYYNNYNNNNYYNYYYNYYNYNYNNNNN", "NYNNNNYYNNNYYYNYYNYYYYNNNNNNNNNN", "NYNNNNNYNYNYYYYNYYYNNYNYYNNYNYNN", "NYYNNNNNNNYNNNYYNYNYNNYYNNYNNYYN", "NYNYNYNYNYNYNYNYYNNYNYYYYNNYYYNN", "NNNNNNYYYYNNYYYYNNNNNYNNNNYYNNNN", "NNNNYYNYYNNNYYYNYYNNNNNNNYNYNYNN", "NNYYNNNYYYYYNNYNNNNNNYYNNNYNNYYN", "NYNNNYYNNYYNYYYYNYYNYNNNNNYYYNNN", "NYNNYNYNNYNNNYNNYYNNYNNNYNNYNYNN", "NNYNNNNYNYYNNNNYYYNNNNNNYYNYNYNY", "NNNYNYYYNYYNNYNYNYNNNNYYNNYNNNNN", "YNYNNYYYNYNNNNNNNNNYNNNYNNNNNYYN", "YNYYNNYNNNNNNYNNYNYNYYNNYNNYNNNN", "YNNNYNNNNYYNYNNYNYYYNYYYNNYNYNNY", "YYNNNNYYNNNNNNNNNYNNNYNNNNNYNNNN", "YNNNNNYYNYNNNNNYYYNYYNYYNYNNNNNN", "NYNNNYYNYYYNNNNNYNNNYNNNNYNNNNNN", "NNNNNYNYYNYNNNNNNNNNNNNYNNNYNNNN" };
    int d = 716;
    assertEquals(2148, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case27() {
    String[] isFriend = { "NYYYYYYYYYYYYYYYYNYY", "YNYYYYYYYYYYYYYYYYYY", "YYNYYYNYYYYYYYYNYYYY", "YYYNYYYNYYYYYYYYYYYY", "YYYYNYYYYYYYYYYYYYYN", "YYYYYNYYYYYYYYYYNYYY", "YYNYYYNYYYYYYYYYYYYY", "YYYNYYYNNYYYYYYYYYNY", "YYYYYYYNNYYYNYYYYYYY", "YYYYYYYYYNYYYYNYYYYY", "YYYYYYYYYYNYYYYYYYYY", "YYYYYYYYYYYNYYYYYYYY", "YYYYYYYYNYYYNYYYYYYY", "YYYYYYYYYYYYYNYYYYYY", "YYYYYYYYYNYYYYNYYYYY", "YYNYYYYYYYYYYYYNYYYY", "YYYYYNYYYYYYYYYYNYYY", "NYYYYYYYYYYYYYYYYNYY", "YYYYYYYNYYYYYYYYYYNY", "YYYYNYYYYYYYYYYYYYYN" };
    int d = 600;
    assertEquals(1200, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case28() {
    String[] isFriend = { "NYYYNYYYYYNYYYNYYYYYYYNYNYYYY", "YNYYYYNYNYNYNYYYYYYYNYNYYYYYN", "YYNYYNNYYYNYYYYYYYYYNNNYNYYYY", "YYYNNNYNNYYNYNYYYYNYNYYYNYNNY", "NYYNNNYYYYYYYYYYYYYYYYNYYYNYN", "YYNNNNYYYNYYYNYNYYYNYYYNYYNNN", "YNNYYYNYYYYNYYNYYYNNYNYYYYYNN", "YYYNYYYNYYYYYNYYYNYNYYYNYNYNN", "YNYNYYYYNYYYYYYYYYYYNYYYYYYYY", "YYYYYNYYYNNNYYYYYYYYYYNYYNYYY", "NNNYYYYYYNNYYNYYYNYYYYYNYYNYN", "YYYNYYNYYNYNYYYNYYYYYYNYYYNYY", "YNYYYYYYYYYYNYYNYYYYYNYYYYYNY", "YYYNYNYNYYNYYNYNYYYYNYNYYYNYY", "NYYYYYNYYYYYYYNYYNYYYYNYYYYYY", "YYYYYNYYYYYNNNYNYNYYYYNYYNYYN", "YYYYYYYYYYYYYYYYNYNYYNYYNYYYY", "YYYYYYYNYYNYYYNNYNNYYYNYYYNYY", "YYYNYYNYYYYYYYYYNNNYYYYYNYNYN", "YYYYYNNNYYYYYYYYYYYNYYYYYYYYY", "YNNNYYYYNYYYYNYYYYYYNYYYNNNYY", "YYNYYYNYYYYYNYYYNYYYYNYYYYNYN", "NNNYNYYYYNYNYNNNYNYYYYNYYYYNY", "YYYYYNYNYYNYYYYYYYYYYYYNYYYYY", "NYNNYYYYYYYYYYYYNYNYNYYYNYYYN", "YYYYYYYNYNYYYYYNYYYYNYYYYNYYY", "YYYNNNYYYYNNYNYYYNNYNNYYYYNYN", "YYYNYNNNYYYYNYYYYYYYYYNYYYYNY", "YNYYNNNNYYNYYYYNYYNYYNYYNYNYN" };
    int d = 276;
    assertEquals(552, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case29() {
    String[] isFriend = { "NYYNNNNYNNYYNNNNYYNNNNNYNNNYN", "YNNYYYNNNNNNYYNNNNNYNNNYNNNNN", "YNNYNNYYYYYYYNNNNYNNNNNNNYYNY", "NYYNYNNYNNNNNNNYNYNNNNNNNNNYN", "NYNYNNYYNNNNYNNNNNNNNNYNNNNNN", "NYNNNNNNNNNYNNNYNNYNYNNNNYNYN", "NNYNYNNNYYYNNYNNNNYNYNNNNNYNN", "YNYYYNNNYYNNNNNYNYNNNNNNNNNNN", "NNYNNNYYNYNNNNNNYNNNYNNNNYYNN", "NNYNNNYYYNNNNNNNYNNNNYNYNNNNN", "YNYNNNYNNNNNNNNNYNNNNNYNNNNNN", "YNYNNYNNNNNNNNYNNNNNNNYNNNNNN", "NYYNYNNNNNNNNNNNNYNNNYNNNNNNN", "NYNNNNYNNNNNNNNNNNNNYNNNNNNNN", "NNNNNNNNNNNYNNNYNNNNNNYNNNNNY", "NNNYNYNYNNNNNNYNYNNNNNYNNNNNN", "YNNNNNNNYYYNNNNYNNNNNNNNNNNNN", "YNYYNNNYNNNNYNNNNNNNYNNNYYNNY", "NNNNNYYNNNNNNNNNNNNYNNNNNYNYN", "NYNNNNNNNNNNNNNNNNYNNNNNYNNNN", "NNNNNYYNYNNNNYNNNYNNNNYNYNNYN", "NNNNNNNNNYNNYNNNNNNNNNNYNNYYN", "NNNNYNNNNNYYNNYYNNNNYNNNNNNNN", "YYNNNNNNNYNNNNNNNNNNNYNNNNNNY", "NNNNNNNNNNNNNNNNNYNYYNNNNNNNN", "NNYNNYNNYNNNNNNNNYYNNNNNNNNNN", "NNYNNNYNYNNNNNNNNNNNNYNNNNNYY", "YNNYNYNNNNNNNNNNNNYNYYNNNNYNN", "NNYNNNNNNNNNNNYNNYNNNNNYNNYNN" };
    int d = 389;
    assertEquals(1556, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case30() {
    String[] isFriend = { "NYNNYYNNNYNNYNNNNNNNNYNNYNYNYNNYNYYNNNNNNNNNY", "YNYNNYYNYNYNYYNYYNNNNYNNNYNNYNNNYNNNNNNNNNNNY", "NYNYYNNYNNNYNYNNNNYNNNNNYYNNNNNNNNNYYYNNNNNNN", "NNYNNNNYYNYYNNNNNNNNNYYNNNNNNNNNNNNYNNNYYYYNN", "YNYNNNNNNYNNYNNNNNNNNNNYNNNNNNNNNNNNNNNYNNNNY", "YYNNNNYNNNYNNNYNNNNNNNNNYYNNNNNNYNNNYNNNNNNNN", "NYNNNYNNNNNNNNNYNNNNYNNNNNNNNNNNNNNNYNNNNNYNN", "NNYYNNNNYNNNYNNNNYNNYNNNNNNNNYNNNYNYYYNYYNYNN", "NYNYNNNYNNNYNYNYNNNNYNNNNNYNNYNNNNNNNYNNNNNYN", "YNNNYNNNNNNNYYNYNYNNNYYYNNNNNNYNNNYNYYNNYNNYN", "NYNYNYNNNNNNNNNNNNNNNNNYYNNNNNNNNNNNNYNNNNYNN", "NNYYNNNNYNNNNNYNNNYNYNNYNNYNNNNNNNYNNNNNNYNNY", "YYNNYNNYNYNNNNYNNNYYYNNYNNNNNNNNNNNNNNNNNNNYN", "NYYNNNNNYYNNNNNNYYNNYNNYNNNYNNYNNNNNNNNYNNNYY", "NNNNNYNNNNNYYNNYNNNNNNNNNNNNNNNNNNNNNNNNNNYNN", "NYNNNNYNYYNNNNYNYNNNNNYYYNYYNYYNNNNNNNYNNNNNN", "NYNNNNNNNNNNNYNYNNYNNYYNYNNNNNNNNNNYNNNNNNNNN", "NNNNNNNYNYNNNYNNNNNNNNNNNNNNNNYNNNYNNNNNNNYNN", "NNYNNNNNNNNYYNNNYNNYNNNYNNNYNNYNYNNYNNNNNYNNN", "NNNNNNNNNNNNYNNNNNYNNNNYNNNNNNNNNNYNNNYNNNNNN", "NNNNNNYYYNNYYYNNNNNNNNNNNNYNNNNNNNNNNNNNNYNNN", "YYNYNNNNNYNNNNNNYNNNNNNNNNNNYYNNYNNNNNNNYYNNN", "NNNYNNNNNYNNNNNYYNNNNNNNNNNNNYNNNNNNNYNNYYNYN", "NNNNYNNNNYYYYYNYNNYYNNNNNNNNNYNNNNNNNNNNNNYNN", "YNYNNYNNNNYNNNNYYNNNNNNNNNNNNNNNNNNNYYNNYNNNN", "NYYNNYNNNNNNNNNNNNNNNNNNNNNNNNYYNNNNYNNYYNNNN", "YNNNNNNNYNNYNNNYNNNNYNNNNNNNNNNNYYNNNYNNNNNNN", "NNNNNNNNNNNNNYNYNNYNNNNNNNNNNYYNNNYNNNNNNYNNN", "YYNNNNNNNNNNNNNNNNNNNYNNNNNNNYNNYNNYNNNNNNNNY", "NNNNNNNYYNNNNNNYNNNNNYYYNNNYYNNYYNNNNNYNNNYYN", "NNNNNNNNNYNNNYNYNYYNNNNNNYNYNNNNYNNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNNNNNNNYNNNYNNNNNNNNNNNNNNN", "NYNNNYNNNNNNNNNNNNYNNYNNNNYNYYYNNYNNNYNNYNYNN", "YNNNNNNYNNNNNNNNNNNNNNNNNNYNNNNNYNNNNNYYNNNYY", "YNNNNNNNNYNYNNNNNYNYNNNNNNNYNNNNNNNNNNNNNNYNN", "NNYYNNNYNNNNNNNNYNYNNNNNNNNNYNNNNNNNYNNNYNNNN", "NNYNNYYYNYNNNNNNNNNNNNNNYYNNNNNNNNNYNNNNNNNNN", "NNYNNNNYYYYNNNNNNNNNNNYNYNYNNNNNYNNNNNNNNNNYN", "NNNNNNNNNNNNNNNYNNNYNNNNNNNNNYNNNYNNNNNYNNNNN", "NNNYYNNYNNNNNYNNNNNNNNNNNYNNNNNNNYNNNNYNNNNNN", "NNNYNNNYNYNNNNNNNNNNNYYNYYNNNNNNYNNYNNNNNNNNN", "NNNYNNNNNNNYNNNNNNYNYYYNNNNYNNNNNNNNNNNNNNNNN", "NNNYNNYYNNYNNNYNNYNNNNNYNNNNNYNNYNYNNNNNNNNNN", "NNNNNNNNYYNNYYNNNNNNNNYNNNNNNYNNNYNNNYNNNNNNN", "YYNNYNNNNNNYNYNNNNNNNNNNNNNNYNNNNYNNNNNNNNNNN" };
    int d = 137;
    assertEquals(411, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case31() {
    String[] isFriend = { "NNYYNNNNYNNNNYNN", "NNNNNNNNNNNYNYNY", "YNNNNNNYNNNNNYNN", "YNNNYNNNNNNNYNNY", "NNNYNNNYNNYNNNNN", "NNNNNNNNNYNNNNNN", "NNNNNNNYYYYNNYNY", "NNYNYNYNNNYNNNYN", "YNNNNNYNNNNNNNNN", "NNNNNYYNNNYNYNYN", "NNNNYNYYNYNNYNYN", "NYNNNNNNNNNNNNNY", "NNNYNNNNNYYNNNYY", "YYYNNNYNNNNNNNYY", "NNNNNNNYNYYNYYNY", "NYNYNNYNNNNYYYYN" };
    int d = 886;
    assertEquals(3544, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case32() {
    String[] isFriend = { "NYY", "YNN", "YNN" };
    int d = 966;
    assertEquals(1932, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case33() {
    String[] isFriend = { "NYYYYYNNNNNNNNNYNYYYNNYYY", "YNNYNNYYNNNNYYYNNNNYNNNNN", "YNNYNNNYNNNNNNYYNNYYYNYNN", "YYYNYNNYYYYNYNYNNNYNYYYNN", "YNNYNNYNYNYNNNYNYNNNNNYNY", "YNNNNNNYNYYNNNNYNNNNNNNNY", "NYNNYNNYYYNYNNNNNYNYYNYYN", "NYYYNYYNNNNNYNNYNYNNNYNYN", "NNNYYNYNNNNYNYYYNNNNNNNNY", "NNNYNYYNNNNNYYYNYNYYNNNYN", "NNNYYYNNNNNNNYNYNNYNNNNNN", "NNNNNNYNYNNNYYNNNNNYNNYNN", "NYNYNNNYNYNYNYNNNNNNNNNNY", "NYNNNNNNYYYYYNNYNYNNNYYYN", "NYYYYNNNYYNNNNNNYYNYNNYYY", "YNYNNYNYYNYNNYNNNNNYYYYNY", "NNNNYNNNNYNNNNYNNNNNYYNNN", "YNNNNNYYNNNNNYYNNNNNNNNYN", "YNYYNNNNNYYNNNNNNNNNYNNNN", "YYYNNNYNNYNYNNYYNNNNNNNYN", "NNYYNNYNNNNNNNNYYNYNNYNYN", "NNNYNNNYNNNNNYNYYNNNYNYNN", "YNYYYNYNNNNYNYYYNNNNNYNNN", "YNNNNNYYNYNNNYYNNYNYYNNNN", "YNNNYYNNYNNNYNYYNNNNNNNNN" };
    int d = 593;
    assertEquals(1779, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case34() {
    String[] isFriend = { "NY", "YN" };
    int d = 808;
    assertEquals(808, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case35() {
    String[] isFriend = { "NYYYYYYYYYYYYYYYYNNYNYYYNYYYYYYYYYYYYNYYYYNYY", "YNYYYYYYYYYYYYYNYYYNYYYYYYNNYNYNNYYYYYYNNYYYY", "YYNYYYYYYYYYYYYNYYYYYYYYNYYYYNYNNYYYYYYNYYYYY", "YYYNNNYYYYYYYNYYYYYNYYYYYYYYYYYYNNYYYYYYYYYYY", "YYYNNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNNYNYYNYYY", "YYYNYNYYYYYYYYYYYYNNNYNNYYYYYYYYYYNNYYYYYYYNY", "YYYYYYNYYYYYYYNYYYYYYYYYNYYNYNYYYYYYYYYYYYYYY", "YYYYYYYNYYYNYNYNYYYYYYYYYYYYYYYYYYYYNNYYYYYYY", "YYYYYYYYNYYYYYYNYYYYYYYNYYYYYYYYYNYYYYYYYYYYY", "YYYYYYYYYNYYYYYNNYYYYYNNYYYYYYYNYYYYYYYYYYYYY", "YYYYYYYYYYNYYNYYYYYYNYYYYNYNYYYYYYYYYYYYYYYNY", "YYYYYYYNYYYNYYYYYYYYYNYNNYYYYYNNYYYYYYNYYYYYY", "YYYYYYYYYYYYNYYYYYYYYYYYYYNYYNYYYYYYYYYNYYYNY", "YYYNYYYNYYNYYNYYYYNNYYYYYYYYNYNYNYYNYNYYNYNNY", "YYYYYYNYYYYYYYNYYYYNYYYYYYYNYYYYYYYYYNYYNNYNY", "YNNYYYYNNNYYYYYNYYNYYYYNYYYNYYYYYYYYYNYYNYYYN", "YYYYYYYYYNYYYYYYNYYNYYNYYYYYYNYYNYYNYYYNYYYYN", "NYYYYYYYYYYYYYYYYNYYYYYNNYYYYNYNYNYYYYYYYNYYY", "NYYYYNYYYYYYYNYNYYNYYYNYYYYYYYYYYYYYYYNNNYYNN", "YNYNYNYYYYYYYNNYNYYNYYYYYYYYYYYNYYYYYYNNYYYYY", "NYYYYNYYYYNYYYYYYYYYNYNYYYYYNYNNNYYNNYNYYNYYY", "YYYYYYYYYYYNYYYYYYYYYNYYNYYYYYYYYNYYYYNYYYYYY", "YYYYYNYYYNYYYYYYNYNYNYNYYYYYNYYYYYYNYNYYYYYYY", "YYYYYNYYNNYNYYYNYNYYYYYNYYYYYYYYYYYYYYYNYYNYN", "NYNYYYNYYYYNYYYYYNYYYNYYNYYYYYNYYYYYYNNNYYYYN", "YYYYYYYYYYNYYYYYYYYYYYYYYNYYYYYYYYYYYNNNYYNYY", "YNYYYYYYYYYYNYYYYYYYYYYYYYNYYYYNYYYYNYYYNYYYY", "YNYYYYNYYYNYYYNNYYYYYYYYYYYNYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYNYYYYYYNYNYYYYYNYYYYYYYNYYYNYYYY", "YNNYYYNYYYYYNYYYNNYYYYYYYYYYYNYYYNYNYYYNYNYYN", "YYYYYYYYYYYNYNYYYYYYNYYYNYYYYYNNYYYNYYYYYYYYY", "YNNYYYYYYNYNYYYYYNYNNYYYYYNYYYNNYYYNYYYYYNYYY", "YNNNYYYYYYYYYNYYNYYYNYYYYYYYYYYYNYYYYYYNYYYYY", "YYYNYYYYNYYYYYYYYNYYYNYYYYYYYNYYYNYYYNYYYYYYY", "YYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYNYY", "YYYYNNYYYYYYYNYYNYYYNYNYYYYYYNNNYYYNYYYYYNYYY", "YYYYNYYNYYYYYYYYYYYYNYYYYYNYNYYYYYYYNYNYYYYYY", "NYYYYYYNYYYYYNNNYYYYYYNYNNYYYYYYYNYYYNYYNYYYY", "YYYYNYYYYYYNYYYYYYNNNNYYNNYYYYYYYYYYNYNYYYYYN", "YNNYYYYYYYYYNYYYNYNNYYYNNNYYYNYYNYYYYYYNYYYYY", "YNYYYYYYYYYYYNNNYYNYYYYYYYNYNYYYYYYYYNYYNYYYY", "YYYYNYYYYYYYYYNYYNYYNYYYYYYYYNYNYYYNYYYYYNYYY", "NYYYYYYYYYYYYNYYYYYYYYYNYNYYYYYYYYNYYYYYYYNNY", "YYYYYNYYYYNYNNNYYYNYYYYYYYYYYYYYYYYYYYYYYYNNY", "YYYYYYYYYYYYYYYNNYNYYYYNNYYYYNYYYYYYYYNYYYYYN" };
    int d = 412;
    assertEquals(824, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case36() {
    String[] isFriend = { "NNNYNYNNNNNYNNNNYNYYNNNYYNNNNNYNNNNNNYNNYNYNNNNNNN", "NNNNNNYNNYNNNNNNNNNNNYYNNNNNYNNNNNYYNNNNNNNNNNNNYN", "NNNNNNNNNNNNNNNNNNNNYNNYNNNNNNNYNNNNYNNNNNYNYYNNNN", "YNNNNNNNNNNNNNYNYNNNNNNNNNNNNNNNNNNNYNNNYNNNNNNNNN", "NNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNYNNNN", "YNNNNNNYNNYNNNNNNNNYNNYNNNYNNYNNYNNNNNNNNYNNNNNNNN", "NYNNNNNNNNNNNNYYNYNNNNNNNNNNYNNNYNYYNNYYNNNNNNYNNN", "NNNNYYNNNYNNYNNNNNNNNNNYNNYNNYNNNNYNNYNNNNNYNNNNNN", "NNNNNNNNNYNNYNNNNNYYNNYNNNNYNNNNNNYNNNNNYNNNNNYNNN", "NYNNNNNYYNNNNNNNYNNNNNNNNNNNYNNNNNNNYNNYNNNNNNNNNY", "NNNNNYNNNNNNNYNNYNNNNNNNNNNNNNNNNYNNNNNNNNNYNNYNNN", "YNNNNNNNNNNNNYNNYNNNNNNNNNNYNNNNNNNNYYNNNNNNYNNNNN", "NNNNNNNYYNNNNNNNNNNNNNNYNYNNNNNNNNNNNNNYNNNNYYNNNN", "NNNNNNNNNNYYNNNNNNNNNYNNNYNNNYNNNYNNNNYYNNNNNYNNNN", "NNNYNNYNNNNNNNNYNNNNNNYYNNNNNNNNYNNNYNNNYYNNNNNNYN", "NNNNNNYNNNNNNNYNYNNNYNNNNNNNNYNNNYNNNNNNNNNNNNNNNN", "YNNYNNNNNYYYNNNYNYNYNNNNNYNNNNNYNYYNYNNNNNNNNNNNYN", "NNNNNNYNNNNNNNNNYNNNNNNNNNNNNNYNNNNNNNYYNNNNNNYYNY", "YNNNNNNNYNNNNNNNNNNNNNNNNYNYNNYNNNNNNNNNNNYNYNNNNN", "YNNNNYNNYNNNNNNNYNNNNNNNNNNNYNNYNNNYNNNNNNNYNNNNYN", "NNYNNNNNNNNNNNNYNNNNNYNNYNNYYNNYNNNNNNNNYNYNNNNNNN", "NYNNNNNNNNNNNYNNNNNNYNNNNNNNYNNNNNYNYYNNNNNNNNNNNN", "NYNNNYNNYNNNNNYNNNNNNNNNYNNNNNNNNNNNNNNNNYNNYNYNNN", "YNYNNNNYNNNNYNYNNNNNNNNNYNNNNNNYNNNNNNNNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNNYNYYNNNNNNNYNYNNNNYNYNNNNNNNNY", "NNNNNNNNNNNNYYNNYNYNNNNNNNNNNNNYNNYNNNNYNYNNNNNNNN", "NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNYYNNNYYNNNYNNNNNN", "NNNNNNNNYNNYNNNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNYNNNN", "NYNNNNYNNYNNNNNNNNNYYYNNNNNNNNNYNNNNYNNNNNNNNNYNYN", "NNNNNYNYNNNNNYNYNNNNNNNNNNNNNNNYNNYYNYNNNNNNYNNNNN", "YNNNNNNNNNNNNNNNNYYNNNNNNNNNNNNNNNNNNNNNNNNNNYNYNN", "NNYNNNNNNNNNNNNNYNNYYNNYYYNNYYNNNNNYNNNNNNNNYNNYYN", "NNNNNYYNNNNNNNYNNNNNNNNNNNNNNNNNNNNYNYNNNNNNNNYYYN", "NNNNNNNNNNYNNYNYYNNNNNNNYNYNNNNNNNNNNNNNNNNNNNNNNY", "NYNNNNYYYNNNNNNNYNNNNYNNNYYNNYNNNNNNNYNYNNNYNNYNNN", "NYNNNNYNNNNNNNNNNNNYNNNNNNNNNYNYYNNNNNNNNNNNNNNNNN", "NNYYYNNNNYNYNNYNYNNNNYNNNNNNYNNNNNNNNNNNNYNYNYNYYN", "YNNNNNNYNNNYNNNNNNNNNYNNNNNNNYNNYNYNNNNYNNNNNNNNYY", "NNNNNNYNNNNNNYNNNYNNNNNNYNYNNNNNNNNNNNNNYNYNNNNNNN", "NNNNNNYNNYNNYYNNNYNNNNNNNYYNNNNNNNYNNYNNNNNNNNNNNN", "YNNYNNNNYNNNNNYNNNNNYNNNYNNNNNNNNNNNNNYNNNNNNNYNNN", "NNNNNYNNNNNNNNYNNNNNNNYNNYNNNNNNNNNNYNNNNNNNNNYNNN", "YNYNNNNNNNNNNNNNNNYNYNNNNNNNNNNNNNNNNNYNNNNYNNNNNN", "NNNNNNNYNNYNNNNNNNNYNNNNNNYNNNNNNNYNYNNNNNYNNNNNNN", "NNYNNNNNNNNYYNNNNNYNNNYNNNNNNYNYNNNNNNNNNNNNNNNNNN", "NNYNYNNNNNNNYYNNNNNNNNNNNNNYNNYNNNNNYNNNNNNNNNNYNN", "NNNNNNYNYNYNNNNNNYNNNNYNNNNNYNNNYNYNNNNNYYNNNNNNYN", "NNNNNNNNNNNNNNNNNYNNNNNNNNNNNNYYYNNNYNNNNNNNNYNNNN", "NYNNNNNNNNNNNNYNYNNYNNNNNNNNYNNYYNNNYYNNNNNNNNYNNN", "NNNNNNNNNYNNNNNNNYNNNNNNYNNNNNNNNYNNNYNNNNNNNNNNNN" };
    int d = 102;
    assertEquals(306, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case37() {
    String[] isFriend = { "NYYNNYNYNYNYYNYYYY", "YNYYNYYYYYYYNYNYYN", "YYNYNNYNNYYYYNYNNY", "NYYNYNYNYYYNYYNYNY", "NNNYNYYYYYYNYYYYYY", "YYNNYNNYYYNYYYYNYN", "NYYYYNNNYYYNYYYNYN", "YYNNYYNNYYYYYNNNNN", "NYNYYYYYNYYYYYYNNY", "YYYYYYYYYNYYYNYYYY", "NYYYYNYYYYNYNNNYYY", "YYYNNYNYYYYNNYNYNY", "YNYYYYYYYYNNNYNYYY", "NYNYYYYNYNNYYNNNYN", "YNYNYYYNYYNNNNNYYN", "YYNYYNNNNYYYYNYNYN", "YYNNYYYNNYYNYYYYNY", "YNYYYNNNYYYYYNNNYN" };
    int d = 268;
    assertEquals(536, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case38() {
    String[] isFriend = { "NYNYYYNYNNYYYNYNYNN", "YNYYYNNNYYNYNNNYYNN", "NYNYYNYYNNNYYYNNNYN", "YYYNNYNNYYNNNNYNYNN", "YYYNNNYYNYNYNNNNYYY", "YNNYNNNYNYNYYNNNNNN", "NNYNYNNNNYNYYYNYYNY", "YNYNYYNNNYNYNYYYYNN", "NYNYNNNNNNNYYYYNYYN", "NYNYYYYYNNYYYNNNNNN", "YNNNNNNNNYNYYYYNYNY", "YYYNYYYYYYYNYYNYYYN", "YNYNNYYNYYYYNYYNNNN", "NNYNNNYYYNYYYNYNYYY", "YNNYNNNYYNYNYYNNNYN", "NYNNNNYYNNNYNNNNNYY", "YYNYYNYYYNYYNYNNNYY", "NNYNYNNNYNNYNYYYYNN", "NNNNYNYNNNYNNYNYYNN" };
    int d = 563;
    assertEquals(1689, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case39() {
    String[] isFriend = { "NYNYY", "YNYNY", "NYNNY", "YNNNY", "YYYYN" };
    int d = 406;
    assertEquals(812, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case40() {
    String[] isFriend = { "NYYYNYNNNNYYYNNYYNYNNNYNNNYNYNYYYYYYNYNYNN", "YNYYNNYNNNYYNYNYYYYNYYNYYYYNNNNNYNNNYYYYYY", "YYNYYYYYYYNYYYNYNYNYNYYYYYYNYNYNYYYYYYYNYY", "YYYNYNYYYYNNYNYNNYYNYNNNNYYYNYYYNYNYNYNYYY", "NNYYNNYNYYNNYYYNNYYYYYYNNNNYYNYYYYYNYNYYYY", "YNYNNNYNNNNNYNYNYNYYYYNYNNYNNYNNYYNYNNYYNY", "NYYYYYNNYNNYYNYYYYYYYYYYNYYNYYNNNNNYYNYNNY", "NNYYNNNNNNYNNYYYNYNNNNYYYNNNNNYNYNNYNYNNNN", "NNYYYNYNNYNNYNYNYYNNYYYNYYYYYYNYNNNYNNYYNN", "NNYYYNNNYNYYNNNYNYNNYYYYNNYYNYNYNYNYNYNYYN", "YYNNNNNYNYNNYYYNYYYYYNNNNNNNNYYNNYYYYYYYYY", "YYYNNNYNNYNNNNYNNYNYNNYYYNNNYYYNNYYYNYNNYN", "YNYYYYYNYNYNNNNYYYNYYYNYYYNNNNNYYYYNYNYYYN", "NYYNYNNYNNYNNNNYYYNYNNNYNYNYYNYYYNNNYYNYYY", "NNNYYYYYYNYYNNNNYNNYNYNNYNNYNYNNYYYYNNNYYY", "YYYNNNYYNYNNYYNNYNYYNYYYYYNNYNYYNYYNYYYNNY", "YYNNNYYNYNYNYYYYNNYNNYNYYNYYNNYYNYYNNYNNNN", "NYYYYNYYYYYYYYNNNNYYYYYYNYNYNNYNYNNNNYNYNY", "YYNYYYYNNNYNNNNYYYNNNYNYYYYYNYNNNYYNYYNNNY", "NNYNYYYNNNYYYYYYNYNNNNYYYYYYYNYYYNYNNNNYNY", "NYNYYYYNYYYNYNNNNYNNNYNNYYNNNYNNYYNYYNYYNY", "NYYNYYYNYYNNYNYYYYYNYNNYNNNNNNNYNNYNNYNYNY", "YNYNYNYYYYNYNNNYNYNYNNNYYYYYNNNYNYYNNNNYNY", "NYYNNYYYNYNYYYNYYYYYNYYNYYYNYNYNYYNNYYYNNN", "NYYNNNNYYNNYYNYYYNYYYNYYNYNYYNNYNNNNYYNNNY", "NYYYNNYNYNNNYYNYNYYYYNYYYNYYYYYNYYYNYYYYYY", "YYYYNYYNYYNNNNNNYNYYNNYYNYNNYYYNNYYYYYNYYN", "NNNYYNNNYYNNNYYNYYYYNNYNYYNNNYYYNNYYYNNYYY", "YNYNYNYNYNNYNYNYNNNYNNNYYYYNNNYYYNNYNYYYNY", "NNNYNYYNYYYYNNYNNNYNYNNNNYYYNNYYNNYNNYYYNY", "YNYYYNNYNNYYNYNYYYNYNNNYNYYYYYNYYNNYNYYYNN", "YNNYYNNNYYNNYYNYYNNYNYYNYNNYYYYNYYNNYNNYYN", "YYYNYYNYNNNNYYYNNYNYYNNYNYNNYNYYNNNYYNNNNN", "YNYYYYNNNYYYYNYYYNYNYNYYNYYNNNNYNNYYNYNYYY", "YNYNYNNNNNYYYNYYYNYYNYYNNYYYNYNNNYNNYNYNYN", "YNYYNYYYYYYYNNYNNNNNYNNNNNYYYNYNYYNNYNYYNN", "NYYNYNYNNNYNYYNYNNYNYNNYYYYYNNNYYNYYNYYYNN", "YYYYNNNYNYYYNYNYYYYNNYNYYYYNYYYNNYNNYNYYNN", "NYYNYYYNYNYNYNNYNNNNYNNYNYNNYYYNNNYYYYNYNY", "YYNYYYNNYYYNYYYNNYNYYYYNNYYYYYYYNYNYYYYNNY", "NYYYYNNNNYYYYYYNNNNNNNNNNYYYNNNYNYYNNNNNNY", "NYYYYYYNNNYNNYYYNYYYYYYNYYNYYYNNNYNNNNYYYN" };
    int d = 393;
    assertEquals(786, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case41() {
    String[] isFriend = { "NNYYYYNYYNNNNNYNYYNNNYYYYYNYYYYNYYNYYYNYYYYNNNYYN", "NNNYYNYYYYYYNNNYYYNYNYYYYYNYNYYYYYYYYYYNNYNYYYYYY", "YNNNYYYNNNYYNYYYYYYYNNNYYYNNNNYYYNYNYNYNYNYNNYYYN", "YYNNYYYNYNYYNNYYNYNYYNYNYNYNYYYYYNYYNYYNYYYYNNNNY", "YYYYNNYNNNYYYYNYYNYYNYYYYYNYYYNNNYNYYYYYYYYNNNNYN", "YNYYNNYNYNNYNNNNNYYYYYYYYYYYNNYYYYYNYNYYNNYNYNYYN", "NYYYYYNYYYNYNNNNYYYYNNYYYNYYNNYYYNNYYYYNNYNYYYNYY", "YYNNNNYNNNYYYNNYYYNYYYYYNYNYYYNNYYYNYYNNNNNYYNYYY", "YYNYNYYNNYNYYYNNYYNYNYYNNNYYYYYNYNYNNNYNYYYNYYNYY", "NYNNNNYNYNYYYYYYNNYNNYNYNNYYNYNYYYNYYYYYYYYYYYYYY", "NYYYYNNYNYNNYNYNYNNNNYYNYYYYYNYYNYNYYYYYYYYYNYYYY", "NYYYYYYYYYNNNNNYYNYYYNYNYYYYYNNYYYNYYYNYYYYYNYYYY", "NNNNYNNYYYYNNNYNYYYNYNYNYYNNNYYYYYYYYYYNNNYNNYNYN", "NNYNYNNNYYNNNNYNNNYYYYYYYYYYNYYNNYNNYYNYYYYNYYNYN", "YNYYNNNNNYYNYYNYNNYNYYNNYYNYYNNYNNYNYYYYNYYNYNYNY", "NYYYYNNYNYNYNNYNYYYYNYYNYYNNYNNYNYYYNNNNYYYYYNNYY", "YYYNYNYYYNYYYNNYNYYNNNYYNYYNYYYNNYYYYYYNNYYNYYNNN", "YYYYNYYYYNNNYNNYYNNNNNYNYNNNNYNYYYNYYYNNYNYYYNYNN", "NNYNYYYNNYNYYYYYYNNYYYNYYYYYYNYNNNNNNYYYYYYYYNYYY", "NYYYYYYYYNNYNYNYNNYNYYNYYYYNYNYYNNYYNNYYYYYYNNYNN", "NNNYNYNYNNNYYYYNNNYYNYNYYYYYYNYYYNYNYNYYNNYYYNYNN", "YYNNYYNYYYYNNYYYNNYYYNYYYNYYNNNYYNNNYYNNNNYNNYYYY", "YYNYYYYYYNYYYYNYYYNNNYNYNYYYYNYYYYYNNYNNYYNYNNNYY", "YYYNYYYYNYNNNYNNYNYYYYYNYYYNYNNYNNNYYYYYNNYYNNYYY", "YYYYYYYNNNYYYYYYNYYYYYNYNYYYNYYNNNYNNYYNYYYYNNYYN", "YYYNYYNYNNYYYYYYYNYYYNYYYNYYYYYYYYYYYNNYYYNYNNYYN", "NNNYNYYNYYYYNYNNYNYYYYYYYYNNYYYYNNYNYYYNNNYYYYNNY", "YYNNYYYYYYYYNYYNNNYNYYYNYYNNYYYYYYYNNYYYYNNYYYNYY", "YNNYYNNYYNYYNNYYYNYYYNYYNYYYNYYNYYYNYYNYNYYYYNYYY", "YYNYYNNYYYNNYYNNYYNNNNNNYYYYYNNNNYYYNNYYYYNNYNNNY", "YYYYNYYNYNYNYYNNYNYYYNYNYYYYYNNYNYNYYNYNYYYNNYYNY", "NYYYNYYNNYYYYNYYNYNYYYYYNYYYNNYNYNYYYYYNYNYYYYYNY", "YYYYNYYYYYNYYNNNNYNNYYYNNYNYYNNYNNYNYYNYYYYYYNNNY", "YYNNYYNYNYYYYYNYYYNNNNYNNYNYYYYNNNYYYNYNYNYYNYYNY", "NYYYNYNYYNNNYNYYYNNYYNYNYYYYYYNYYYNNYNYYYYYYYYYNN", "YYNYYNYNNYYYYNNYYYNYNNNYNYNNNYYYNYNNYYYNYNYYYNNYY", "YYYNYYYYNYYYYYYNYYNNYYNYNYYNYNYYYYYYNYYYYYNYNYYYN", "YYNYYNYYNYYYYYYNYYYNNYYYYNYYYNNYYNNYYNYYNNNYYYYNY", "NYYYYYYNYYYNYNYNYNYYYNNYYNYYNYYYNYYYYYNYNNYNYYNYY", "YNNNYYNNNYYYNYYNNNYYYNNYNYNYYYNNYNYNYYYNYYNYNNNNN", "YNYYYNNNYYYYNYNYNYYYNNYNYYNYNYYYYYYYYNNYNYYYYYYYN", "YYNYYNYNYYYYNYYYYNYYNNYNYYNNYYYNYNYNYNNYYNNYNYYNY", "YNYYYYNNYYYYYYYYYYYYYYNYYNYNYNYYYYYYNNYNYNNNYYYNY", "NYNYNNYYNYYYNNNYNYYYYNYYYYYYYNNYYYYYYYNYYYNNYYNNY", "NYNNNYYYYYNNNYYYYYYNYNNNNNYYYYNYYNYYNYYNYNYYNYYYY", "NYYNNNYNYYYYYYNNYNNNNYNNNNYYNNYYNYYNYYYNYYYYYNNYN", "YYYNNYNYNYYYNNYNNYYYYYNYYYNNYNYYNYYNYYNNYYYNYNNYY", "YYYNYYYYYYYYYYNYNNYNNYYYYYNYYNNNNNNYYNYNYNNNYYYNY", "NYNYNNYYYYYYNNYYNNYNNYYYNNYYYYYYYYNYNYYNNYYYYNYYN" };
    int d = 783;
    assertEquals(1566, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case42() {
    String[] isFriend = { "NNNNYNNNNYYNNNNYNNNYYYNNYYNYYYNNNYY", "NNYNNNYNNYNNYYNNNNYYYYNNNNNNNYNNNYN", "NYNNYNYNYYYYNNNNYYNNYYNYNNYNNNNYYYN", "NNNNNNNYNNNNYYNNNNYNYNNNNYYNNYNNNYY", "YNYNNNNNYNYYNNNYYNNNYYYYNYNNYNYNYNY", "NNNNNNNNYNYYYNNNYNYNNNNNNNNNNYYNNNY", "NYYNNNNYNYNYNNYYYYYYNNYYNYNNNNNYNNN", "NNNYNNYNYYNNNNYNYYNYNYYYNYNYNYYNNYN", "NNYNYYNYNYNYYNNNYNNYYNNNNNYNNYNNNNN", "YYYNNNYYYNNNYYYNYNYNYNYNYYNNNNNNNNY", "YNYNYYNNNNNNNYNYYNNYYNNNYYYYNNYYNYN", "NNYNYYYNYNNNNNNNNYNNNYYNNYYNYNNYYYN", "NYNYNYNNYYNNNNNNYNNNYNYNNNNNNYNNYNY", "NYNYNNNNNYYNNNNNNNNNYYNNNNNNNYYNNNY", "NNNNNNYYNYNNNNNYNNYYNNNNNNNNYNYYNNY", "YNNNYNYNNNYNNNYNYNNNNNYYYYNYNNNNYNY", "NNYNYYYYYYYNYNNYNNNYYNNYYNNNYNYNNNN", "NNYNNNYYNNNYNNNNNNNYYYYNNNNNNNYNNNN", "NYNYNYYNNYNNNNYNNNNYYNYNNNYNYYNYYNY", "YYNNNNYYYNYNNNYNYYYNNNYYYYNYNNYNNYN", "YYYYYNNNYYYNYYNNYYYNNNYNNNNNYNNNYNY", "YYYNYNNYNNNYNYNNNYNNNNYNNYNNYNNNNNN", "NNNNYNYYNYNYYNNYNYYYYYNYNNNNYNNYNNY", "NNYNYNYYNNNNNNNYYNNYNNYNNYNNNNYYNYY", "YNNNNNNNNYYNNNNYYNNYNNNNNNNYYNYNYNN", "YNNYYNYYNYYYNNNYNNNYNYNYNNNNNYNYNNN", "NNYYNNNNYNYYNNNNNNYNNNNNNNNNNNNYNYN", "YNNNNNNYNNYNNNNYNNNYNNNNYNNNNYYYNYN", "YNNNYNNNNNNYNNYNYNYNYYYNYNNNNYYNNNN", "YYNYNYNYYNNNYYNNNNYNNNNNNYNYYNYNYNN", "NNNNYYNYNNYNNYYNYYNYNNNYYNNYYYNNYNY", "NNYNNNYNNNYYNNYNNNYNNNYYNYYYNNNNYNY", "NNYNYNNNNNNYYNNYNNYNYNNNYNNNNYYYNYN", "YYYYNNNYNNYYNNNNNNNYNNNYNNYYNNNNYNN", "YNNYYYNNNYNNYYYYNNYNYNYYNNNNNNYYNNN" };
    int d = 395;
    assertEquals(1185, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case43() {
    String[] isFriend = { "NYYNYNNYNYYYYNYYYNYYNNNNYYNNNNYY", "YNYNNYYYYYYYYYNYYNYNYYNYNNNYYNNN", "YYNYYYYYYYYYNNYYNNNNYYYYNYYNNYYN", "NNYNYYYNNYYYYYYYYYNYYYNYYYNNYNNY", "YNYYNNYNNYNNYYNYNNYNYYNNYNYYNYYY", "NYYYNNYYNNNYYYYYYYNYYYYYYNNNNYNY", "NYYYYYNNYYNNNNNNYYYNYYYYNNNYYNNN", "YYYNNYNNYNNYNYNNYNYNNYYYYYNYYYNN", "NYYNNNYYNYNYYYNYNYNNNNNYYNNYYNNY", "YYYYYNYNYNYNYNYYYNYNNNNYNNYYYNNY", "YYYYNNNNNYNYNYYNYYYYYNNNNNYYNNYN", "YYYYNYNYYNYNYYNNNNNYYYNYNYNYNNNN", "YYNYYYNNYYNYNNNYYYNNNNYNNYYYYYYY", "NYNYYYNYYNYYNNYYYNNNYYYNNNNNYNYN", "YNYYNYNNNYYNNYNYYYYYNNYNYYNNYNYY", "YYYYYYNNYYNNYYYNYYNYYNYYYNNNYYYN", "YYNYNYYYNYYNYYYYNYYNYNYYNYYYNNNY", "NNNYNYYNYNYNYNYYYNNNNNYNYNNNNYNY", "YYNNYNYYNYYNNNYNYNNYNYYNYYYYYNYY", "YNNYNYNNNNYYNNYYNNYNNNYYYNNNYNYY", "NYYYYYYNNNYYNYNYYNNNNNNYYYNNYYNN", "NYYYYYYYNNNYNYNNNNYNNNYYNNNYNYNY", "NNYNNYYYNNNNYYYYYYYYNYNYNYNYNNYY", "NYYYNYYYYYNYNNNYYNNYYYYNNNNYYYYN", "YNNYYYNYYNNNNNYYNYYYYNNNNNYYYYNN", "YNYYNNNYNNNYYNYNYNYNYNYNNNYNYNYY", "NNYNYNNNNYYNYNNNYNYNNNNNYYNNYYNN", "NYNNYNYYYYYYYNNNYNYNNYYYYNNNNNNY", "NYNYNNYYYYNNYYYYNNYYYNNYYYYNNNYY", "NNYNYYNYNNNNYNNYNYNNYYNYYNYNNNYN", "YNYNYNNNNNYNYYYYNNYYNNYYNYNNYYNN", "YNNYYYNNYYNNYNYNYYYYNYYNNYNYYNNN" };
    int d = 743;
    assertEquals(1486, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case44() {
    String[] isFriend = { "NY", "YN" };
    int d = 795;
    assertEquals(795, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case45() {
    String[] isFriend = { "NYYNNNNNYYYYNNYNNYNNNNYYYNNYNNNNNNYNNYYNYN", "YNNNNYYNNNYYNNNNYNNYNNYYNYNNNNNNNYYNNNNNNY", "YNNYYNNNYYNYYNYNYNNNNNYYYNNYNNNNNNNYYNNNNN", "NNYNYNYNYYYYNNYNNNYNNYYYYYNNNYNYNNNYNNYNYN", "NNYYNYYNYNNNNNNYYNNNNNYNYYYNNYNNNNYYYYNNNN", "NYNNYNNNYNYYYNYNNYYNNNYNNYNNYNYNNNNNYNNNYN", "NYNYYNNYNYNNYNNNNNNNYNNYYNNYNYYNNYNNNNNNYN", "NNNNNNYNNYNNNNNYNNNNYNNYNYYNNYNNNNYYNYNNYN", "YNYYYYNNNNNNNNNYNNNNNNNNNNYNNNNNNNNNNNNNYN", "YNYYNNYYNNNNNYYNYNYYNYNNYNNNNNYYYNNNNNNYNN", "YYNYNYNNNNNYNNNNYYYYNYNYNNNNNNYYYNNYNYNYNN", "YYYYNYNNNNYNNNNNNNNYYNNNNNNNYNYNYNNNYNNNNN", "NNYNNYYNNNNNNNNNNNYNNNYNNNYYNYNNYYNYYNNNNN", "NNNNNNNNNYNNNNNNNNNYNNNNNNYNYYNYNNNNYNNNNY", "YNYYNYNNNYNNNNNYYYNYNNNNYYYNYNNNNNYNNYNNYN", "NNNNYNNYYNNNNNYNNYNNNYYNNNNNNNNYYYYNNYYYNN", "NYYNYNNNNYYNNNYNNNNYYYYNYYNNNNNYNNNNYNNNNN", "YNNNNYNNNNYNNNYYNNYNNNNNYNYYYYNYNYYNNNYNYY", "NNNYNYNNNYYNYNNNNYNNYNNNNYYNNNNNNNYNYYYYNN", "NYNNNNNNNYYYNYYNYNNNNYNYNYNNYNYNNNYNYYYYNY", "NNNNNNYYNNNYNNNNYNYNNNNNYNYNNNNYNYNNNYNNNN", "NNNYNNNNNYYNNNNYYNNYNNNYNNYNNYYNYNYNNNNNNY", "YYYYYYNNNNNNYNNYYNNNNNNYNYNNNYNYNYYNNYNNYN", "YYYYNNYYNNYNNNNNNNNYNYYNNNNYYNNYNYYYYNYYNN", "YNYYYNYNNYNNNNYNYYNNYNNNNYNNNNNNYYNNNYYNNN", "NYNYYYNYNNNNNNYNYNYYNNYNYNYNYNNNYYNYNNNNYN", "NNNNYNNYYNNNYYYNNYYNYYNNNYNNNYYNNYNNNNNNNY", "YNYNNNYNNNNNYNNNNYNNNNNYNNNNYNNYNNYYNNYNNY", "NNNNNYNNNNNYNYYNNYNYNNNYNYNYNYYNNNNYNNNNNN", "NNNYYNYYNNNNYYNNNYNNNYYNNNYNYNYNNYYYNYNNYN", "NNNNNYYNNYYYNNNNNNNYNYNNNNYNYYNNYYYNNNNNNN", "NNNYNNNNNYYNNYNYYYNNYNYYNNNYNNNNNYNYNYNYNY", "NNNNNNNNNYYYYNNYNNNNNYNNYYNNNNYNNYYNNNYNNN", "NYNNNNYNNNNNYNNYNYNNYNYYYYYNNYYYYNNNYNYNYN", "YYNNYNNYNNNNNNYYNYYYNYYYNNNYNYYNYNNNNYNNNY", "NNYYYNNYNNYNYNNNNNNNNNNYNYNYYYNYNNNNYNNNYN", "NNYNYYNNNNNYYYNNYNYYNNNYNNNNNNNNNYNYNNYNNN", "YNNNYNNYNNYNNNYYNNYYYNYNYNNNNYNYNNYNNNNNYN", "YNNYNNNNNNNNNNNYNYYYNNNYYNNYNNNNYYNNYNNNNN", "NNNNNNNNNYYNNNNYNNYYNNNYNNNNNNNYNNNNNNNNNN", "YNNYNYYYYNNNNNYNNYNNNNYNNYNNNYNNNYNYNYNNNN", "NYNNNNNNNNNNNYNNNYNYNYNNNNYYNNNYNNYNNNNNNN" };
    int d = 70;
    assertEquals(210, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case46() {
    String[] isFriend = { "NYYYYNYYYNNNN", "YNNYNNYYYYYYN", "YNNYNYYYYNNNN", "YYYNYNYYNNYNY", "YNNYNYYNNYNNY", "NNYNYNYYYNYNY", "YYYYYYNNYNYYY", "YYYYNYNNNYNYN", "YYYNNYYNNNYNN", "NYNNYNNYNNYYY", "NYNYNYYNYYNYN", "NYNNNNYYNYYNY", "NNNYYYYNNYNYN" };
    int d = 490;
    assertEquals(980, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case47() {
    String[] isFriend = { "NYYYYY", "YNYYYY", "YYNYYY", "YYYNYY", "YYYYNY", "YYYYYN" };
    int d = 222;
    assertEquals(222, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case48() {
    String[] isFriend = { "NNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNN", "NNNNNYYNNNNNYNN", "NNNNNNNNNNNNNNN", "NNNYNNNNNNNNNNN", "NNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNY", "NNNNNNNNNNNNYNN", "NNNNNNNNNNYNNYN", "NNNNNNNNNYNNNNN", "NNNNNNNNNNNNNYN", "NNNYNNNNYNNNNNN", "NNNNNNNNNYNYNNY", "NNNNNNNYNNNNNYN" };
    int d = 811;
    assertEquals(-1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case49() {
    String[] isFriend = { "NYYYYYYYYYYNYYYY", "YNYYYYYYYYYYYYYN", "YYNYYYYYYYYYYYYY", "YYYNYYNYYYYYYYYY", "YYYYNYYYYYYYYYYY", "YYYYYNYNYYYYNYYY", "YYYNYYNYYNNNYNYY", "YYYYYNYNNYYYYYNY", "YYYYYYYNNYYYYYYY", "YYYYYYNYYNYYYYYY", "YYYYYYNYYYNYYYYY", "NYYYYYNYYYYNYYYY", "YYYYYNYYYYYYNYYY", "YYYYYYNYYYYYYNNY", "YYYYYYYNYYYYYNNY", "YNYYYYYYYYYYYYYN" };
    int d = 832;
    assertEquals(1664, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case50() {
    String[] isFriend = { "NYY", "YNY", "YYN" };
    int d = 501;
    assertEquals(501, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case51() {
    String[] isFriend = { "NY", "YN" };
    int d = 536;
    assertEquals(536, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case52() {
    String[] isFriend = { "NYNNYNYYYYYYYYYYYYYNYYYYYYYYYYYNYYNYYYYYNYYYYY", "YNYYYYYYYYYYYYYYYYYYYNYYYNYYYYYYYYYYYYYYNNYYYY", "NYNYYYYYYYYYNYYYYYYYYYYYYYYNYYYYYYYYNYYYYYYYNY", "NYYNYNNYYYYYYYYYYYYNYYYYYYYYYYYYYYYYNYNYYYYYYY", "YYYYNYYYYYYYYYYYNNYYYYNYNYYNYYYYYYYYYYYYYYYYYY", "NYYNYNYYYYYYYYYYYNYNYYYYNYYYYYYYYYYYYNNYYYYYYN", "YYYNYYNNYYNYYYYYYYYYNYNYYYYYYYYNYNYYYYYYYYYYYN", "YYYYYYNNYNYNYYYYYYYYYYYYNNYYNYYYYYYNYNYYYYYYNY", "YYYYYYYYNYYYNYNNYYYYYYYNNYYYYYYYNNYYNNYNYYNYNY", "YYYYYYYNYNYNYYYYYYNYYYNYYYYYYYYYYYYYYYNYYYYYYY", "YYYYYYNYYYNYYYYYYYYYNYYYYYYNNYNYYYNYYYYYYYYYYY", "YYYYYYYNYNYNYYYYYYYYNYNYYYYNYYNYNYYYYYYYYNYYYY", "YYNYYYYYNYYYNYYYYYYYNYYYYYYYYYNYNYYYYYYYYYYYNN", "YYYYYYYYYYYYYNYYYYYYNYYYYYYYYYYYYYYNYYYNYYYYYY", "YYYYYYYYNYYYYYNYYYYYYYYYNYYNYYYYYNYYNYYYYYYNYY", "YYYYYYYYNYYYYYYNYYYYYYYYNNYYYYNYNYNYYYYYYYNNYY", "YYYYNYYYYYYYYYYYNNYYNYYYYYYYYYYYYYNYYYYYYYYYNY", "YYYYNNYYYYYYYYYYNNYNYYYYNYYYYYYNYYYYYYNYYYYYYN", "YYYYYYYYYNYYYYYYYYNYYYNYYYYYNNYYYYNYYYNYYYYNYY", "NYYNYNYYYYYYYYYYYNYNNYYYYNYYYNYYYNYYYYNYYYYYYY", "YYYYYYNYYYNNNNYYNYYNNNYYYYYYYYYYNYYYNNYYYNNYYY", "YNYYYYYYYYYYYYYYYYYYNNYNYYNYYYYYYNNYNYYYNYYYYY", "YYYYNYNYYNYNYYYYYYNYYYNYYYYYYNYYYNYYYYYYYNYYYN", "YYYYYYYYNYYYYYYYYYYYYNYNYYYYYYNYYYYNYYNNYYYNNN", "YYYYNNYNNYYYYYNNYNYYYYYYNYYNNYYYYYYNYYYNYYYYYY", "YNYYYYYNYYYYYYYNYYYNYYYYYNYYYYYYYYYYNYYNYYYNYY", "YYYYYYYYYYYYYYYYYYYYYNYYYYNYYYYYNNNYNNYYYYYNYN", "YYNYNYYYYYNNYYNYYYYYYYYYNYYNYYYNYYYYYYYYNYNNYY", "YYYYYYYNYYNYYYYYYYNYYYYYNYYYNYYYYYYYYYYYYYYYNY", "YYYYYYYYYYYYYYYYYYNNYYNYYYYYYNYYNYNYYYYYYYNYYY", "YYYYYYYYYYNNNYYNYYYYYYYNYYYYYYNYYYYYYYYYYYYNYY", "NYYYYYNYYYYYYYYYYNYYYYYYYYYNYYYNYYYYNYYNYYYYNY", "YYYYYYYYNYYNNYYNYYYYNYYYYYNYYNYYNYYYYYNYNYYYYY", "YYYYYYNYNYYYYYNYYYYNYNNYYYNYYYYYYNYYYYYYYYYYYY", "NYYYYYYYYYNYYYYNNYNYYNYYYYNYYNYYYYNYYNNYYNNYYY", "YYYYYYYNYYYYYNYYYYYYYYYNNYYYYYYYYYYNNNYYYNYYNY", "YYNNYYYYNYYYYYNYYYYYNNYYYNNYYYYNYYYNNYYNYNYNNY", "YYYYYNYNNYYYYYYYYYYYNYYYYYNYYYYYYYNNYNYYYNYYYY", "YYYNYNYYYNYYYYYYYNNNYYYNYYYYYYYYNYNYYYNNYYYYYY", "YYYYYYYYNYYYYNYYYYYYYYYNNNYYYYYNYYYYNYNNYNYYYY", "NNYYYYYYYYYYYYYYYYYYYNYYYYYNYYYYNYYYYYYYNYYYYY", "YNYYYYYYYYYNYYYYYYYYNYNYYYYYYYYYYYNNNNYNYNYYYY", "YYYYYYYYNYYYYYYNYYYYNYYYYYYNYNYYYYNYYYYYYYNNNY", "YYYYYYYYYYYYYYNNYYNYYYYNYNNNYYNYYYYYNYYYYYNNYY", "YYNYYYYNNYYYNYYYNYYYYYYNYYYYNYYNYYYNNYYYYYNYNY", "YYYYYNNYYYYYNYYYYNYYYYNNYYNYYYYYYYYYYYYYYYYYYN" };
    int d = 518;
    assertEquals(1036, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case53() {
    String[] isFriend = { "NYNYNNNYNNYYNNNNNNNN", "YNYNYNYNYYNNNNYNYNNN", "NYNNNNNYNNNYNYNNNNNY", "YNNNNNNNNNNNNYNNNNNN", "NYNNNNNYNNNYNNNNNNYY", "NNNNNNYYNYNNNNYNNNNY", "NYNNNYNYNNNNYNNNNNNN", "YNYNYYYNNNYYNNNNNYNN", "NYNNNNNNNNNYNNNNNNYY", "NYNNNYNNNNYNNNNNNNYY", "YNNNNNNYNYNNNNYNNNYY", "YNYNYNNYYNNNYNNNNNNN", "NNNNNNYNNNNYNNNYNNNN", "NNYYNNNNNNNNNNNNNNNN", "NYNNNYNNNNYNNNNNYNNY", "NNNNNNNNNNNNYNNNYNNN", "NYNNNNNNNNNNNNYYNNYY", "NNNNNNNYNNNNNNNNNNNN", "NNNNYNNNYYYNNNNNYNNN", "NNYNYYNNYYYNNNYNYNNN" };
    int d = 421;
    assertEquals(1684, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case54() {
    String[] isFriend = { "NYYNNNNNNNNNNNNNNNNNN", "YNNNYYNNNYNYYNNNNNNNN", "YNNYNNYNNNNNNNNYNNNNN", "NNYNNNNNNNNNNNNNYNYNY", "NYNNNNNNNNYNNNNNNNNNN", "NYNNNNNYYNNNYNNNNNNNN", "NNYNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNYNNNNY", "NYNNNNNNNNNNNNNNNNNNN", "NNNNYNNNNNNNYYYNYNNNN", "NYNNNNNNNNNNNNNYNNNNN", "NYNNNYNNNNYNNNNNNYNNN", "NNNNNNNNNNYNNNYNNNNNN", "NNNNNNNNNNYNNYNNNNNYN", "NNYNNNNNYNNYNNNNNNNNY", "NNNYNNNNNNYNNNNNNNNNN", "NNNNNNNNNNNNYNNNNNNNN", "NNNYNNNNNNNNNNNNNNNYN", "NNNNNNNNNNNNNNYNNNYNN", "NNNYNNNNYNNNNNNYNNNNN" };
    int d = 412;
    assertEquals(2060, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case55() {
    String[] isFriend = { "NYYYYNYNYYNYYYYYYYYYNYYNNNNYNY", "YNYYNYYNNYYYYYYNYNYYNNNYNYYYYY", "YYNNNNYYYYYYYNYYNYYNYNYNNNYYYN", "YYNNNNYNYYNYYYYYYYNYYYYYYYYYYY", "YNNNNYYYYYNNYYYNYNNYYNNNYNYNYY", "NYNNYNNNYNNYYYYNYYNYYYYNYYYNNY", "YYYYYNNYNNNNYNYYYNYNNYNYYYYNYY", "NNYNYNYNNYYYYYNYYYYYYYYYYNYYNY", "YNYYYYNNNYYYNYYYYYNYYNNNYYYYYN", "YYYYYNNYYNYNYYYNNYNNYYNNYNYNNY", "NYYNNNNYYYNNYNNYYNNNYYYYYYYNYY", "YYYYNYNYYNNNNYYNYYNNYNYYNYYYYY", "YYYYYYYYNYYNNYYNNNNYNNYNYYYYNY", "YYNYYYNYYYNYYNYYYYYYNNYYYNYYYY", "YYYYYYYNYYNYYYNYNNNNYNYYNYYNYY", "YNYYNNYYYNYNNYYNYNNYYYNYNYYNYY", "YYNYYYYYYNYYNYNYNYYYYYNYNYYNYY", "YNYYNYNYYYNYNYNNYNYNYYYYYYNYNY", "YYYNNNYYNNNNNYNNYYNYYNNYYYYYYN", "YYNYYYNYYNNNYYNYYNYNYNYYNYYNYY", "NNYYYYNYYYYYNNYYYYYYNYYYYYYNYN", "YNNYNYYYNYYNNNNYYYNNYNYNYYNNYY", "YNYYNYNYNNYYYYYNNYNYYYNYYYYNNY", "NYNYNNYYNNYYNYYYYYYYYNYNNNYYNY", "NNNYYYYYYYYNYYNNNYYNYYYNNNYNNY", "NYNYNYYNYNYYYNYYYYYYYYYNNNYYYY", "NYYYYYYYYYYYYYYYYNYYYNYYYYNNNY", "YYYYNNNYYNNYYYNNNYYNNNNYNYNNNY", "NYYYYNYNYNYYNYYYYNYYYYNNNYNNNN", "YYNYYYYYNYYYYYYYYYNYNYYYYYYYNN" };
    int d = 590;
    assertEquals(1180, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case56() {
    String[] isFriend = { "NYNNNYYNNNNYNNNNNYNNNNYNYYYNYNYNNNNNNN", "YNYYYNYNNNNNNNNYNNYYYNYNNNNNNYYNNNNNNY", "NYNNNNNNNYYNNYNNYNNNNNNNNNNNNYNNNNNNNN", "NYNNNNNYNNNNNYNNNYNNNNYNNNNNNNYNYNNNYN", "NYNNNYNNNYNNYYYNNNNNNNYNNNNNNNNNNYNNNN", "YNNNYNNNYNYNNNYNNNYYNNYNNYNNNNYNNNNNNY", "YYNNNNNNNNYNNNYNNNNNNNNYNNNNNYNNNYNYNN", "NNNYNNNNYNYYYNNNYYYNYNNNNNNNYNNYNNNNNY", "NNNNNYNYNNNNYNNNNYYNYNNNNNNNYNNNNNYNNN", "NNYNYNNNNNNNNNYNNNNYNNNYNNNNNYNNNNNNNN", "NNYNNYYYNNNNYNNYNNYNNNNNNNYNNNNNYNNNNN", "YNNNNNNYNNNNYNNNNNNYNNYNYNNNNNNNNNNNNN", "NNNNYNNYYNYYNNNYNNYYNYYNNNNNYNNNYNNYYN", "NNYYYNNNNNNNNNNNYNNNNNNNNNNNNNNNYNNNNN", "NNNNYYYNNYNNNNNNNNNNYYNYNNYNNNYYYNNNNN", "NYNNNNNNNNYNYNNNYNNNNNNNNNNYNNYYNNNNNN", "NNYNNNNYNNNNNYNYNYNYNNNNNNNNNNYNNNNNYY", "YNNYNNNYYNNNNNNNYNNNYNNNNNNNNYNNNNNNNN", "NYNNNYNYYNYNYNNNNNNNNYNNYNNYNNNNNYYNNN", "NYNNNYNNNYNYYNNNYNNNNYNNNNYYYNNNNNYNNN", "NYNNNNNYYNNNNNYNNYNNNNNYYNNNYNNNYNYYNN", "NNNNNNNNNNNNYNYNNNYYNNNNNNNNNNYNNNNNNN", "YYNYYYNNNNNYYNNNNNNNNNNNNNNYNNNNNNNNNN", "NNNNNNYNNYNNNNYNNNNNYNNNNNNNNNNNNYYNYN", "YNNNNNNNNNNYNNNNNNYNYNNNNNNNNYNNYNNNNY", "YNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNN", "YNNNNNNNNNYNNNYNNNNYNNNNNNNNYYNNNNNNNN", "NNNNNNNNNNNNNNNYNNYYNNYNNNNNNNNNNNNNNN", "YNNNNNNYYNNNYNNNNNNYYNNNNNYNNNNNNYNNNN", "NYYNNNYNNYNNNNNNNYNNNNNNYNYNNNYNNNNNYN", "YYNYNYNNNNNNNNYYYNNNNYNNNNNNNYNNNNNYNN", "NNNNNNNYNNNNNNYYNNNNNNNNNNNNNNNNNYNNNN", "NNNYNNNNNNYNYYYNNNNNYNNNYNNNNNNNNNNNNN", "NNNNYNYNNNNNNNNNNNYNNNNYNNNNYNNYNNNNNY", "NNNNNNNNYNNNNNNNNNYYYNNYNNNNNNNNNNNNNN", "NNNNNNYNNNNNYNNNNNNNYNNNNYNNNNYNNNNNNN", "NNNYNNNNNNNNYNNNYNNNNNNYNNNNNYNNNNNNNN", "NYNNNYNYNNNNNNNNYNNNNNNNYNNNNNNNNYNNNN" };
    int d = 7;
    assertEquals(21, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case57() {
    String[] isFriend = { "NYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNN", "YNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNYNNNNNNNNNNNNYNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNN", "NNYNNNNNNNNNNNNNNNYNYNNNNNNNNNNNNNNYNNNNNNNNNNNNNN", "NYNNNNNNNNNNNNNNNNNYNNNNNNNYNNNNNNNNNNYNNNNNNNNYNN", "NNNNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNYNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNYNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNYNNNNNNNYNNNNNNNNNNNNNNNNNYNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNYNNNNNNNNNNNYNNYN", "NNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNYNNNNNNNNNYNNNNNNNNNNNNNNNYNNYNNNNNNNYNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNYNNNY", "NNNYNNNYNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNYNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNN", "NNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNYNNNNNNNNNYNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNYYNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNYNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNN", "NNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNYNNNN", "NNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNYNNNNYNNNNNNYNNNNNNYNNNNNNNNNNN", "NNNNNNNNNNNNNNNNYNNNNNNNNNNNNNYNYNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNYNNYNYNNYNNNNNNNN", "NNYNNNNNNNNNNYYNNNNNNYNNNNNNNNNNYNYNNNYNYNNYNNNNNN", "YNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNN", "NNNYNNYNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNYYNNYNN", "NNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNYNNNNNN", "NNNNYNNNNNNNNNNNNNNNNNNNNNNYNNYNYYNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNYNYNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNYNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNYNNNN", "NNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNYNNNNN", "NNNNNYNNNNNNNNNNNYNNNNNNNNNNNNNNNYNNYYNNNNNNNYYNNY", "NNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNYNNNNNYNNNNNNN", "NNNNNNNNNNNNNNYNNYNNNNNNNNNYNNNNNNNNNNNNNYNYNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNN", "NNNNYNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNYNNNNNNNNNNNNN", "NNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNN" };
    int d = 149;
    assertEquals(-1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case58() {
    String[] isFriend = { "NYYYNYNNNNYNYNNYNYNNNYNYNNNNNYNNYNNNNNNYYY", "YNNYNNNNNYNNNNYYYYYNNNNNNNYNNNYNNYNNYYYNNN", "YNNNYNYYNNNYYYYYYNYNYNYNNYNNNNYYNNYNNNYNYN", "YYNNYYNYNYNNNYNYYNYNNYNNNNYNNNNNNYNNYNYNNY", "NNYYNNNNNNYYNNNYNYYYNYYYNYNNNYYYYYNNNNNNYN", "YNNYNNNYYYYNNNNYNNNNYNNNYYYYNYYNNNYNNNNNNN", "NNYNNNNYNNYYYNYYNNNNNNNNYNYNYNYYNNYNNNNNNY", "NNYYNYYNNNNYNNNNYNYNNNNNNNNNYNYNNNNYNNNNNN", "NNNNNYNNNYNNYNNYYNNNNNYNNNNNNNNYNYYYNNNNYN", "NYNYNYNNYNYNNYNNNYYYYYNYNNYNYNYYYNNNYYYYNY", "YNNNYYYNNYNYYYNNNNNNNYNNYYNNYNNNNYYNNNNNYN", "NNYNYNYYNNYNNYNYNYNNNNNNNYYNYYNNYNYNYNNNNN", "YNYNNNYNYNYNNYYNNNNYNNYYNNYYNNNYNYYNYNNNYY", "NNYYNNNNNYYYYNYYYYNNNNNYYNYYNNNNNNYNNNNNNY", "NYYNNNYNNNNNYYNNNYNYYNYNYYYNYYYNNNNNNNYYNN", "YYYYYYYNYNNYNYNNYYNNNNNNNNNYYNNNNNNYNNNNNN", "NYYYNNNYYNNNNYNYNNNNNNNYNNNYNYNYNNNYNNNNYY", "YYNNYNNNNYNYNYYYNNYYNYNNNNYYYNNNNYNNNNNNNY", "NYYYYNNYNYNNNNNNNYNNYNNNYNNNYYYNNYNNYNNYYY", "NNNNYNNNNYNNYNYNNYNNYNNYNNNYNNYNNYYYYNYNYN", "NNYNNYNNNYNNNNYNNNYYNYYYNYNYNYNNNYNNNYNNYN", "YNNYYNNNNYYNNNNNNYNNYNNNNNYNYNYYNYNYYNYYNY", "NNYNYNNNYNNNYNYNNNNNYNNYNNYYNNYYYNYNNYNYNN", "YNNNYNNNNYNNYYNNYNNYYNYNNYNYNNNNNNYNNNNYNN", "NNNNNYYNNNYNNYYNNNYNNNNNNYNNNYNNNNYNYYNYYY", "NNYNYYNNNNYYNNYNNNNNYNNYYNNNNNNYYNNYNNNNYN", "NYNYNYYNNYNYYYYNNYNNNYYNNNNYNNNYNNYNYNNYNY", "NNNNNYNNNNNNYYNYYYNYYNYYNNYNYNNNYNYNYYNNNN", "NNNNNNYYNYYYNNYYNYYNNYNNNNNYNNYNYYNNNNYNYY", "YNNNYYNNNNNYNNYNYNYNYNNNYNNNNNYNYNNNNNNYYN", "NYYNYYYYNYNNNNYNNNYYNYYNNNNNYYNNNYNNYNNNNN", "NNYNYNYNYYNNYNNNYNNNNYYNNYYNNNNNNNYYYYNYYY", "YNNNYNNNNYNYNNNNNNNNNNYNNYNYYYNNNYNNNYYNYY", "NYNYYNNNYNYNYNNNNYYYYYNNNNNNYNYNYNNYYNNYNY", "NNYNNYYNYNYYYYNNNNNYNNYYYNYYNNNYNNNNNNNNNN", "NNNNNNNYYNNNNNNYYNNYNYNNNYNNNNNYNYNNNYNNNY", "NYNYNNNNNYNYYNNNNNYYNYNNYNYYNNYYNYNNNYNYYY", "NYNNNNNNNYNNNNNNNNNNYNYNYNNYNNNYYNNYYNYNNY", "NYYYNNNNNYNNNNYNNNNYNYNNNNNNYNNNYNNNNYNYNY", "YNNNNNNNNYNNNNYNNNYNNYYYYNYNNYNYNYNNYNYNNN", "YNYNYNNNYNYNYNNNYNYYYNNNYYNNYYNYYNNNYNNNNN", "YNNYNNYNNYNNYYNNYYYNNYNNYNYNYNNYYYNYYYYNNN" };
    int d = 827;
    assertEquals(1654, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case59() {
    String[] isFriend = { "NYNNYYYYYNYYYNNYYYYNYYYYNYNYNYYYNYNYYYNNN", "YNYYNYNNYNYYYYYYYNYYYYNYYYNYNYYNNYYNNYYYY", "NYNNYNNYNYYNYYYYYYYYNYYYNYYNYNNYNNYYYNYNN", "NYNNYNYNYNNYYNYYYNYYNYYYYNNNYYYYYNYYYYYYN", "YNYYNNYYYNNYYYYNNYYYYYYNYYNYYNYYNYNYNNYYY", "YYNNNNYYYYYYYNYYYNYYYNYYYYYYYYYNNNNYYNNYN", "YNNYYYNYYYNYYYYYYYYNYYNYNYNNNYYYYYYYYNYNY", "YNYNYYYNYYNYNYNNYNYYYNNYYYNNYYNYYNYYNNNNN", "YYNYYYYYNYYYNNYYYYNNYYYYNYYNYYNYYYNNNYYYY", "NNYNNYYYYNYNYNYYYNNYNYNYNYYYYYYYNNNYYYNYY", "YYYNNYNNYYNNNYYNNYYYYYYYNYNNYNYNNNNYYYNYY", "YYNYYYYYYNNNYYYYYNNNYNYYYNYYYNNNYYNNYYNYY", "YYYYYYYNNYNYNYNYYYYYYYNYYNYYNYNYNNNNYYNNN", "NYYNYNYYNNYYYNNYYYYNNNYYNNYYNYNYNYNYYYYYY", "NYYYYYYNYYYYNNNNNYYYYYYNNYYNYNYYYYYNNYYYN", "YYYYNYYNYYNYYYNNYNNNYYYYNNNYYYYYYNYNYYNYN", "YYYYNYYYYYNYYYNYNYYYNNYYNNYYYNNNNNNYYYYYN", "YNYNYNYNYNYNYYYNYNYYYNYNNYNYNNNYYYNYNYYYY", "YYYYYYYYNNYNYYYNYYNYYYNYNYYYYNNYNYNNNYNNN", "NYYYYYNYNYYNYNYNYYYNYYYNNYYYYNYYYYYYYYYYY", "YYNNYYYYYNYYYNYYNYYYNNNNYYNNNNNYYNNNNNNYN", "YYYYYNYNYYYNYNYYNNYYNNYYYYYYYNNYYYYYYYNNY", "YNYYYYNNYNYYNYYYYYNYNYNNYYYYNNYYYYNYNYNYY", "YYYYNYYYYYYYYYNYYNYNNYNNNYNYYYYYYNYYYYNYN", "NYNYYYNYNNNYYNNNNNNNYYYNNYNYYNYNYNNNYYNYY", "YYYNYYYYYYYNNNYNNYYYYYYYYNNYYYNNYNYYNNNYY", "NNYNNYNNYYNYYYYNYNYYNYYNNNNYYYYNYYYYYYYNY", "YYNNYYNNNYNYYYNYYYYYNYYYYYYNYNNYYYYNYYYYY", "NNYYYYNYYYYYNNYYYNYYNYNYYYYYNYNNNYYYYNYNY", "YYNYNYYYYYNNYYNYNNNNNNNYNYYNYNNYYYYYYNNNY", "YYNYYYYNNYYNNNYYNNNYNNYYYNYNNNNYYYYNYYNYN", "YNYYYNYYYYNNYYYYNYYYYYYYNNNYNYYNYYYYYYNYY", "NNNYNNYYYNNYNNYYNYNYYYYYYYYYNYYYNYYNYYNNY", "YYNNYNYNYNNYNYYNNYYYNYYNNNYYYYYYYNYNYNNYY", "NYYYNNYYNNNNNNYYNNNYNYNYNYYYYYYYYYNYYNNYY", "YNYYYYYYNYYNNYNNYYNYNYYYNYYNYYNYNNYNYNYYY", "YNYYNYYNNYYYYYNYYNNYNYNYYNYYYYYYYYYYNYYNN", "YYNYNNNNYYYYYYYYYYYYNYYYYNYYNNYYYNNNYNYYY", "NYYYYNYNYNNNNYYNYYNYNNNNNNYYYNNNNNNYYYNNY", "NYNYYYNNYYYYNYYYYYNYYNYYYYNYNNYYNYYYNYNNY", "NYNNYNYNYYYYNYNNNYNYNYYNYYYYYYNYYYYYNYYYN" };
    int d = 280;
    assertEquals(560, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case60() {
    String[] isFriend = { "NYNNNNNNNYNNNNNNNYNNYNNNNNNNNNNNYNN", "YNNNNNNNNNNNNNNYNNNNNNNNNNNNNNYYNNN", "NNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNYNNNYNNNNNNNNNNNNYNYNNNNYN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNYN", "NNNNNNNNNNYYNNNNNNNNNYNNNNNNNNNNNNN", "NNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNYNNNNNNNNNNNNYNNNNNNNNNNYNNN", "YNNYNNNNNNNNNNNNNNNNYNYNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNYNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNYNNNNYNNNN", "NNNYNNNNNNNNNNNNNYNYNNYNYNNNNNNNNNY", "NNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN", "NYNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNYNYNNNYNNNNNNNNN", "YNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNYNNNNNNNNNNNNYNNNNYNNNNNN", "NNNNNNNNNNNNNYNNYNNNNNNNYNNNNNNNNNN", "YNNNNNNNYYNNNNNNNNNNNNNNNNNNNNNNNYN", "NNNNNYNNNNNNNNNNYNNNNNNNNNNNNNNNNYN", "NNNNNNNNNYNNNYNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNYNNNYNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNYNYNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNNNNYNNNYNNNNNNNNNNNYYNNNNN", "NNNYNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNN", "NNNYNNNNNNNNNNNNNNYNNNNNNYNNNNNNNYY", "NNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNN", "NYNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNN", "NYNNYNNNYNNNNNNNNNNNNNNNNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYN", "NNNYYNNNNNNNNNNNNNNNYYNNNNNNYNNNYNN", "NNNNNNNNNNNNNYNNNNNNNNNNNNNNYNNNNNN" };
    int d = 646;
    assertEquals(-1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case61() {
    String[] isFriend = { "NNNYNYYYNNNYYYYYYYNYYNYNYNYNYYNYNYYNYYYNNNNY", "NNYYYNNNYYYNYNNNNNYYYNNYNYNYYYYYNNYYYYNYYNNY", "NYNNYYNNYYYYYNNYYNYNNYYNNYYYYYYNNYNNYNNNYYYN", "YYNNYNYYYNNYNNNNYNYNYNNYYNNNNYYYYNYYYYYYYYNN", "NYYYNNNYYYNNNYYYNYYYYNYYNYNNYYNYYNNYYNNYNYNN", "YNYNNNNYNYNYYNYYNYYYNYYNYYNYNNNNYNYNNNYYYNNY", "YNNYNNNYYNYNNNYYYNYYYYYYNNYNYYNYNNYNYNNYYNNY", "YNNYYYYNNYYNNYYYNYYYNNNYNYNYNNNNYYYNNNYNYNYY", "NYYYYNYNNYYYYYYYYYYYNNNNNNYNYYNYYYNNNYYYNYYN", "NYYNYYNYYNNYYNYNYNYNYYYYYYNYYYYYNYYNYYYYYNYN", "NYYNNNYYYNNYNYNNNNYYYYNYNYYYYYYYYYNYNYYYYYNY", "YNYYNYNNYYYNNNNNNYNYNYNYYYNYNYYNYYYYYNYNYNYN", "YYYNNYNNYYNNNNNYYYNYYYNYYNYYYYYNYNNNYYNYYYYY", "YNNNYNNYYNYNNNYYYNYNNYYYNNYNNYYYNYYYYYNYNYNN", "YNNNYYYYYYNNNYNNYNYYYYNNYYNYYNYNYNYNYNYYYYNY", "YNYNYYYYYNNNYYNNNYYNNYYYNNYYYYYYNYYYNYYNNYNY", "YNYYNNYNYYNNYYYNNYNYNNYNYYYNNNYYYYNYYNYYYYNY", "YNNNYYNYYNNYYNNYYNYYYYYNNYYYYNNNYYYNNYYYNNNN", "NYYYYYYYYYYNNYYYNYNNYYYYYYYYYYYNYYYYYNYNYYYY", "YYNNYYYYYNYYYNYNYYNNYNYNNNYNYNNNNNNYYYYNYNYN", "YYNYYNYNNYYNYNYNNYYYNYYNNNNYNYNNNNNYNYYYYYNN", "NNYNNYYNNYYYYYYYNYYNYNNYYNNYYYYNYNNYYYYYYNYY", "YNYNYYYNNYNNNYNYYYYYYNNNYYYYYYYNYNNYYNNYYNYY", "NYNYYNYYNYYYYYNYNNYNNYNNYYYNYNNYYYYYYYNYNYNN", "YNNYNYNNNYNYYNYNYNYNNYYYNNYYYNNNNNYYYYYYYYYY", "NYYNYYNYNYYYNNYNYYYNNNYYNNYYYYYYNNYYYNYNNYYY", "YNYNNNYNYNYNYYNYYYYYNNYYYYNYNYYYNYYYYYYYYNNY", "NYYNNYNYNYYYYNYYNYYNYYYNYYYNNYYYYYNNYYYNYYYY", "YYYNYNYNYYYNYNYYNYYYNYYYYYNNNYYNYYYNNNYNYYNY", "YYYYYNYNYYYYYYNYNNYNYYYNNYYYYNYYNYYNNYNYNNNN", "NYYYNNNNNYYYYYYYYNYNNYYNNYYYYYNNNNNYYYNYYNNY", "YYNYYNYNYYYNNYNYYNNNNNNYNYYYNYNNYYYYNYYYYNNN", "NNNYYYNYYNYYYNYNYYYNNYYYNNNYYNNYNYNNYNNNNYYY", "YNYNNNNYYYYYNYNYYYYNNNNYNNYYYYNYYNYNNNYNYYYY", "YYNYNYYYNYNYNYYYNYYNNNNYYYYNYYNYNYNYNYNYYYNY", "NYNYYNNNNNYYNYNYYNYYYYYYYYYNNNYYNNYNYYYYNYYN", "YYYYYNYNNYNYYYYNYNYYNYYYYYYYNNYNYNNYNYNYYNNY", "YYNYNNNNYYYNYYNYNYNYYYNYYNYYNYYYNNYYYNNYNYNN", "YNNYNYNYYYYYNNYYYYYYYYNNYYYYYNNYNYNYNNNYYYYN", "NYNYYYYNYYYNYYYNYYNNYYYYYNYNNYYYNNYYYYYNNYYN", "NYYYNYYYNYYYYNYNYNYYYYYNYNYYYNYYNYYNYNYNNNYY", "NNYYYNNNYNYNYYYYYNYNYNNYYYNYYNNNYYYYNYYYNNYY", "NNYNNNNYYYNYYNNNNNYYNYYNYYNYNNNNYYNYNNYYYYNY", "YYNNNYYYNNYNYNYYYNYNNYYNYYYYYNYNYYYNYNNNYYYN" };
    int d = 756;
    assertEquals(1512, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case62() {
    String[] isFriend = { "NYNYNNN", "YNYNNYY", "NYNNNNN", "YNNNYNN", "NNNYNNN", "NYNNNNY", "NYNNNYN" };
    int d = 229;
    assertEquals(916, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case63() {
    String[] isFriend = { "NYYNYYNNNNNYYNNNN", "YNYYNYYYYYNNNNNNN", "YYNYYNNYYNNNNNYYN", "NYYNYNNNYNYNNNNNN", "YNYYNYNYNNNNYYYNN", "YYNNYNYYYNNYYNYNY", "NYNNNYNNYYNYYNNNN", "NYYNYYNNYYYNYNNYY", "NYYYNYYYNYNYNYNNN", "NYNNNNYYYNYNNYYYN", "NNNYNNNYNYNNNYNYN", "YNNNNYYNYNNNNNNNY", "YNNNYYYYNNNNNNNNN", "NNNNYNNNYYYNNNYNY", "NNYNYYNNNYNNNYNYY", "NNYNNNNYNYYNNNYNN", "NNNNNYNYNNNYNYYNN" };
    int d = 129;
    assertEquals(387, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case64() {
    String[] isFriend = { "NYYNNYNYYNYNNYNYNYNNNNNNNNYNYNNYNNNNNNNNNNNNNNY", "YNYYYNNYNYYYYNYNYNYYNNYYYNYNYNNYYYNNNYNNYYNNNNN", "YYNNYNYYYNNYYYYNYNYYYNYNNNNNNYNNNNNNNNYNNNNNNNN", "NYNNNNNYYYNYYNNNNYNNNYNNNNNNNYYNNNYNNNNNNNYYNNN", "NYYNNNNNNNYNNNYYNYNNNNNNYNNYYNNNNYNYYNNNNYNNNYN", "YNNNNNNYNYYNYYYNNNYYNNYYNYNYYNYNYNNNYYYYYNYNYYN", "NNYNNNNNNYYNNNNNNNYNNNNYNYNNNYYYNYYYNNNYYNYYYYN", "YYYYNYNNNNNYNYNNNYYNNNYNNYNNNYNNNNNNYNNNNNYNYNN", "YNYYNNNNNYNYNNNNNNNNYYNNNNNYYYNNYNYYNNNNYNYNNYN", "NYNYNYYNYNNNNYNYYYNNNYNNNNNNNNYYYYNYNNYYYNNNNNN", "YYNNYYYNNNNNYNYNNNNYNNYNNNNNNYNNNYNNYNNNNNYNNNN", "NYYYNNNYYNNNYYYNNNYYNNNNNNNNYNYNNYNYNNYNNNNNNYN", "NYYYNYNNNNYYNNYYYNNYNNNYNNNNNYNNNNNNNYYNNNNNNNN", "YNYNNYNYNYNYNNYYNNNYNNNNNYYYNYNNYNNNYNYNNYNNNNY", "NYYNYYNNNNYYYYNYNYYYYYYNNNYYYYNYNNNNNNNNNNNNYNY", "YNNNYNNNNYNNYYYNNNYYNNNNNNYNNNYYNNNYNYYYYNNYYYN", "NYYNNNNNNYNNYNNNNNYNNYYNNYYNYNNNNYYNNNNYYNYYYYY", "YNNYYNNYNYNNNNYNNNYNNNNYYYNYNYNYNNNYNNNNYYNNNNY", "NYYNNYYYNNNYNNYYYYNNNYNNYYNNNNYNNYNYNNNNYNNNNNN", "NYYNNYNNNNYYYYYYNNNNNNYYYYNNNYNNNNNNYNYNYNNNYNY", "NNYNNNNNYNNNNNYNNNNNNNNNYNYNYYNNNNNNYNYYNNNNNNY", "NNNYNNNNYYNNNNYNYNYNNNNYYYNNNNYNNNNNNYYYYNNYNYY", "NYYNNYNYNNYNNNYNYNNYNNNYNNNNNYYNNYNNNYNNNYYNYYN", "NYNNNYYNNNNNYNNNNYNYNYYNNNNNYNNNYYNNNYYYNNNNYNN", "NYNNYNNNNNNNNNNNNYYYYYNNNNNNNNNYNNNYNYNNYYNNNNN", "NNNNNYYYNNNNNYNNYYYYNYNNNNNNYNNNYNYNNYNNYNNNNYN", "YYNNNNNNNNNNNYYYYNNNYNNNNNNYYNNYYNNNYNNYNYYNYNY", "NNNNYYNNYNNNNYYNNYNNNNNNNNYNNNNYNNYNNNNNNNNYYYY", "YYNNYYNNYNNYNNYNYNNNYNNYNYYNNYNNYYYYNNYNNYNNNNN", "NNYYNNYYYNYNYYYNNYNYYNYNNNNNYNNYYNNNNYYYYYNNNNN", "NNNYNYYNNYNYNNNYNNYNNYYNNNNNNNNNNYNNNYYNYNNNYYN", "YYNNNNYNNYNNNNYYNYNNNNNNYNYYNYNNYNNYNNNYNYNNNNN", "NYNNNYNNYYNNNYNNNNNNNNNYNYYNYYNYNNYNYNNNNYNNNNN", "NYNNYNYNNYYYNNNNYNYNNNYYNNNNYNYNNNNNYNNNNYNNNNN", "NNNYNNYNYNNNNNNNYNNNNNNNNYNYYNNNYNNNNNNNNNNNNYN", "NNNNYNYNYYNYNNNYNYYNNNNNYNNNYNNYNNNNNNNNNYYNNNN", "NNNNYYNYNNYNNYNNNNNYYNNNNNYNNNNNYYNNNYYYNNYYNNN", "NYNNNYNNNNNNYNNYNNNNNYYYYYNNNYYNNNNNYNNNYNYNNYY", "NNYNNYNNNYNYYYNYNNNYYYNYNNNNYYYNNNNNYNNNNNNNYNN", "NNNNNYYNNYNNNNNYYNNNYYNYNNYNNYNYNNNNYNNNNNYNYNY", "NYNNNYYNYYNNNNNYYYYYNYNNYYNNNYYNNNNNNYNNNNNYYNN", "NYNNYNNNNNNNNYNNNYNNNNYNYNYNYYNYYYNYNNNNNNNNNYY", "NNNYNYYYYNYNNNNNYNNNNNYNNNYNNNNNNNNYYYNYNNNNNNY", "NNNYNNYNNNNNNNNYYNNNNYNNNNNYNNNNNNNNYNNNYNNNNNY", "NNNNNYYYNNNNNNYYYNNYNNYYNNYYNNYNNNNNNNYYYNNNNNN", "NNNNYYYNYNNYNNNYYNNNNYYNNYNYNNYNNNYNNYNNNYNNNNN", "YNNNNNNNNNNNNYYNYYNYYYNNNNYYNNNNNNNNNYNYNYYYNNN" };
    int d = 58;
    assertEquals(174, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case65() {
    String[] isFriend = { "NNNYYYYYYYNYYYYYYYYYYYYYYYYYYNYYYYY", "NNYYYNYYYYYYYYYYYYYYYYYYYYYYYYNYYYY", "NYNYNYYYYYYYYYYYYYYYYYNYYYYYYNYYYYY", "YYYNYYYNYYYYYNYYNYYYYYYYNYNYNYYYYYY", "YYNYNYYYYYYYNYYYYYYYYYYYYYYYYYYYYYY", "YNYYYNYYNYYYYYNYNYYYYYYYYYYYYYYYYYY", "YYYYYYNYYYYNYYYYYYYYYYYYYYYNYNYYYYY", "YYYNYYYNYYYYYYNYYNYYNNYYYYYNYYYYYYY", "YYYYYNYYNYYYYYYNYYYYYYYNYYYYYYYYYYY", "YYYYYYYYYNNYNYYYYYYNYYYYYYYYYYYYYYY", "NYYYYYYYYNNYYYYYYYNYYYYYYYYYYYYYYYN", "YYYYYYNYYYYNYYYYYYNYYYYYYYYYYYYYYYN", "YYYYNYYYYNYYNYYYYYYYYYYYYYNYYYYNYYN", "YYYNYYYYYYYYYNYNNYYYNYYYYYYYYYYYYYY", "YYYYYNYNYYYYYYNYYYYYYYYYYYYNYYYYYYY", "YYYYYYYYNYYYYNYNYYYYNNNYYYYYYYYYYYY", "YYYNYNYYYYYYYNYYNYYYYYYYYYNYYYYYYYY", "YYYYYYYNYYYYYYYYYNYYYYNYNYYYYYYYYYY", "YYYYYYYYYYNNYYYYYYNYYNYYYYNYYYYYYNY", "YYYYYYYYYNYYYYYYYYYNYYYYYYYYYNYYYYN", "YYYYYYYNYYYYYNYNYYYYNYYYYYYYYYYYYYY", "YYYYYYYNYYYYYYYNYYNYYNYYYYYYYYYYYYY", "YYNYYYYYYYYYYYYNYNYYYYNYNYYYYYYYYYY", "YYYYYYYYNYYYYYYYYYYYYYYNNYYYNYYYYYN", "YYYNYYYYYYYYYYYYYNYYYYNNNYNYYNYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYY", "YYYNYYYYYYYYNYYYNYNYYYYYNYNYYYYYYYY", "YYYYYYNNYYYYYYNYYYYYYYYYYYYNYNYYYYY", "YYYNYYYYYYYYYYYYYYYYYYYNYYYYNYNYYYY", "NYNYYYNYYYYYYYYYYYYNYYYYNYYNYNYYYNY", "YNYYYYYYYYYYYYYYYYYYYYYYYYYYNYNYYYY", "YYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYNYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYY", "YYYYYYYYYYYYYYYYYYNYYYYYYYYYYNYYYNY", "YYYYYYYYYYNNNYYYYYYNYYYNYYYYYYYYYYN" };
    int d = 658;
    assertEquals(1316, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case66() {
    String[] isFriend = { "NYYYNYNYNYNYNNYNNNNNNNNYNNNNNNYNNNNNNN", "YNNYYNNNNYNNNNNNNNNNNNNNNNNNNNNYNNNNNY", "YNNNNNNNNNNNNNNNYNYYNYNNNYNNNNNYYNYNNN", "YYNNNYNNNNNNNNYNNNNNNNNYNNNNNNNNNNNNYN", "NYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "YNNYNNYYNNNNYNNNNYNNNNNNNNNNYYNYNNNYNN", "NNNNNYNNYNYNNNNNYNNNNYNNNNNNNNNYNYNNNN", "YNNNNYNNYNNNNNNNNNNNNNNNNNNYNYNNYYYNNN", "NNNNNNYYNNNNNYNYNNNNYNNNNNNYNNNNNYNNNN", "YYNNNNNNNNYNNYNNYNNNYNNNNYNYNYNYNNNNNY", "NNNNNNYNNYNNYYYNNNNNNNNNNYNNNNYNYNNNYY", "YNNNNNNNNNNNNYNNNYNNNNNNNNNYNNNYNNNNNN", "NNNNNYNNNNYNNYNNYNNNNYNNNYNNYNNNNYYNNN", "NNNNNNNNYYYYYNNNNNNNNYNNNNNNNNNNNNNNNY", "YNNYNNNNNNYNNNNYNNNNNNNNNNNNNNYNNNNNNY", "NNNNNNNNYNNNNNYNNNNNNYNNNNYNNNNNNNNNNN", "NNYNNNYNNYNNYNNNNNNYNNNNNNNNNNNNNNNNNY", "NNNNNYNNNNNYNNNNNNNNNYNNYYYNNNNNNYNNNN", "NNYNNNNNNNNNNNNNNNNNNYNNNNYNNNNNNNNNNN", "NNYNNNNNNNNNNNNNYNNNNNNNYNNYNNNNNYNNYN", "NNNNNNNNYYNNNNNNNNNNNNNNNYYNNNYNNNNNYN", "NNYNNNYNNNNNYYNYNYYNNNYYYNNNNNYNNNNYNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNN", "YNNYNNNNNNNNNNNNNNNNNYNNNNNNYYNNNNNNNN", "NNNNNNNNNNNNNNNNNYNYNYNNNNNNNYNNNNNYNN", "NNYNNNNNNYYNYNNNNYNNYNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNYNYYNYNNNNNNNYYNNNNNNYN", "NNNNNNNYYYNYNNNNNNNYNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNYNNNNNNNNNNYNNYNNNNNNNNNNN", "NNNNNYNYNYNNNNNNNNNNNNNYYNYNNNNNNYNNNN", "YNNNNNNNNNYNNNYNNNNNYYNNNNNNNNNYNNYNNN", "NYYNNYYNNYNYNNNNNNNNNNNNNNNNNNYNNNNNYN", "NNYNNNNYNNYNNNNNNNNNNNNNNYNNNNNNNNNYYN", "NNNNNNYYYNNNYNNNNYNYNNNNNNNNNYNNNNNNNN", "NNYNNNNYNNNNYNNNNNNNNNNNNNNNNNYNNNNYNY", "NNNNNYNNNNNNNNNNNNNNNYNNYNNNNNNNYNYNNN", "NNNYNNNNNNYNNNNNNNNYYNNNNNYNNNNYYNNNNN", "NYNNNNNNNYYNNYYNYNNNNNNNNNNNNNNNNNYNNN" };
    int d = 653;
    assertEquals(3265, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case67() {
    String[] isFriend = { "NYNYYY", "YNYYYY", "NYNYYN", "YYYNNN", "YYYNNY", "YYNNYN" };
    int d = 136;
    assertEquals(272, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case68() {
    String[] isFriend = { "NY", "YN" };
    int d = 1;
    assertEquals(1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case69() {
    String[] isFriend = { "NYYNNNNYYYYNNNN", "YNNNYNNNNNNYYNN", "YNNYNYNNNNYNNNN", "NNYNNYNNNNNNNNN", "NYNNNNYNNYNNNNN", "NNYYNNYNNYNNNYN", "NNNNYYNNYNNNNNN", "YNNNNNNNNNYNNNN", "YNNNNNYNNNNNYNN", "YNNNYYNNNNNNNNY", "YNYNNNNYNNNNNNN", "NYNNNNNNNNNNNNY", "NYNNNNNNYNNNNYN", "NNNNNYNNNNNNYNN", "NNNNNNNNNYNYNNN" };
    int d = 747;
    assertEquals(2988, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case70() {
    String[] isFriend = { "NN", "NN" };
    int d = 1;
    assertEquals(-1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case71() {
    String[] isFriend = { "NYNYYYN", "YNNYYYN", "NNNNYNN", "YYNNYYN", "YYYYNNN", "YYNYNNY", "NNNNNYN" };
    int d = 5;
    assertEquals(20, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case72() {
    String[] isFriend = { "NNYNNN", "NNYNNN", "YYNYNN", "NNYNYY", "NNNYNN", "NNNYNN" };
    int d = 1000;
    assertEquals(3000, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case73() {
    String[] isFriend = { "NY", "YN" };
    int d = 10;
    assertEquals(10, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case74() {
    String[] isFriend = { "NYNYYNNNYN", "YNNYYYYYYY", "NNNNNYNYNY", "YYNNYYNNYY", "YYNYNNYNYY", "NYYYNNYYNN", "NYNNYYNYNN", "NYYNNYYNNN", "YYNYYNNNNY", "NYYYYNNNYN" };
    int d = 1;
    assertEquals(3, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case75() {
    String[] isFriend = { "NYN", "YNY", "NYN" };
    int d = 0;
    assertEquals(0, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case76() {
    String[] isFriend = { "NYY", "YNY", "YYN" };
    int d = 1;
    assertEquals(1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case77() {
    String[] isFriend = { "NY", "YN" };
    int d = 5;
    assertEquals(5, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case78() {
    String[] isFriend = { "NYY", "YNY", "YYN" };
    int d = 10;
    assertEquals(10, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case79() {
    String[] isFriend = { "NYYN", "YNYN", "YYNN", "NNNN" };
    int d = 1;
    assertEquals(-1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case80() {
    String[] isFriend = { "NYY", "YNN", "YNN" };
    int d = 1;
    assertEquals(2, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case81() {
    String[] isFriend = { "NYNN", "YNYN", "NYNN", "NNNN" };
    int d = 1;
    assertEquals(-1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case82() {
    String[] isFriend = { "NYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYN" };
    int d = 42;
    assertEquals(42, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case83() {
    String[] isFriend = { "NN", "NN" };
    int d = 0;
    assertEquals(-1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case84() {
    String[] isFriend = { "NYNY", "YNYN", "NYNY", "YNYN" };
    int d = 5;
    assertEquals(10, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case85() {
    String[] isFriend = { "NN", "NN" };
    int d = 10;
    assertEquals(-1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case86() {
    String[] isFriend = { "NNNY", "NNYN", "NYNY", "YNYN" };
    int d = 1;
    assertEquals(3, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case87() {
    String[] isFriend = { "NY", "YN" };
    int d = 1000;
    assertEquals(1000, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case88() {
    String[] isFriend = { "NYNY", "YNYN", "NYNY", "YNYN" };
    int d = 10;
    assertEquals(20, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case89() {
    String[] isFriend = { "NY", "YN" };
    int d = 2;
    assertEquals(2, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case90() {
    String[] isFriend = { "NYN", "YNY", "NYN" };
    int d = 10;
    assertEquals(20, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case91() {
    String[] isFriend = { "NNNNNYYNNYN", "NNNYNNNNYNN", "NNNYNNNYNNN", "NYYNYNNNNNN", "NNNYNYNNNNN", "YNNNYNNNNNN", "YNNNNNNYNNN", "NNYNNNYNNNN", "NYNNNNNNNYN", "YNNNNNNNYNY", "NNNNNNNNNYN" };
    int d = 1;
    assertEquals(5, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case92() {
    String[] isFriend = { "NYNNY", "YNYNN", "NYNYN", "NNYNY", "YNNYN" };
    int d = 10;
    assertEquals(20, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case93() {
    String[] isFriend = { "NY", "YN" };
    int d = 12;
    assertEquals(12, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case94() {
    String[] isFriend = { "NYNNNNNN", "YNYYNNNY", "NYNNNNNN", "NYNNYNNN", "NNNYNYNN", "NNNNYNYN", "NNNNNYNY", "NYNNNNYN" };
    int d = 100;
    assertEquals(400, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case95() {
    String[] isFriend = { "NNNNY", "NNYNN", "NYNYN", "NNYNY", "YNNYN" };
    int d = 5;
    assertEquals(20, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case96() {
    String[] isFriend = { "NYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNY", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYN" };
    int d = 999;
    assertEquals(999, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case97() {
    String[] isFriend = { "NYYYY", "YNYYY", "YYNYY", "YYYNY", "YYYYN" };
    int d = 1;
    assertEquals(1, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case98() {
    String[] isFriend = { "NYY", "YNN", "YNN" };
    int d = 10;
    assertEquals(20, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case99() {
    String[] isFriend = { "NYNNYNNYNN", "YNYNNNNNNN", "NYNYNYNNYN", "NNYNNNNNNN", "YNNNNYYNNN", "NNYNYNYNNN", "NNNNYYNNNN", "YNNNNNNNYY", "NNYNNNNYNY", "NNNNNNNYYN" };
    int d = 1;
    assertEquals(4, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case100() {
    String[] isFriend = { "NYYY", "YNNY", "YNNY", "YYYN" };
    int d = 10;
    assertEquals(20, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case101() {
    String[] isFriend = { "NYNYNNN", "YNYNNNN", "NYNNNYN", "YNNNYNY", "NNNYNYN", "NNYNYNN", "NNNYNNN" };
    int d = 12;
    assertEquals(48, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case102() {
    String[] isFriend = { "NYNNNNNY", "YNYNNNNN", "NYNYNNNN", "NNYNYNNN", "NNNYNYNN", "NNNNYNYN", "NNNNNYNY", "YNNNNNYN" };
    int d = 1000;
    assertEquals(4000, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case103() {
    String[] isFriend = { "NY", "YN" };
    int d = 50;
    assertEquals(50, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case104() {
    String[] isFriend = { "NYY", "YNN", "YNN" };
    int d = 50;
    assertEquals(100, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case105() {
    String[] isFriend = { "NYYY", "YNNN", "YNNN", "YNNN" };
    int d = 10;
    assertEquals(20, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case106() {
    String[] isFriend = { "NYYNN", "YNNYN", "YNNNY", "NYNNN", "NNYNN" };
    int d = 2;
    assertEquals(8, egalitarianism.maxDifference(isFriend, d));
  }

  @Test
  public void case107() {
    String[] isFriend = { "NYY", "YNY", "YYN" };
    int d = 5;
    assertEquals(5, egalitarianism.maxDifference(isFriend, d));
  }

}
