package topc.test.graph;

import junit.framework.*;
import org.junit.Test;
import static org.junit.Assert.*;
import topc.graph.*;

public class ThreeColorabilityEasyTest {
  ThreeColorabilityEasy threecolorabilityeasy = new ThreeColorabilityEasy();

  @Test
  public void case1() {
    String[] cells = { "Z" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case2() {
    String[] cells = { "NZ", "NZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case3() {
    String[] cells = { "ZZZ", "ZNZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case4() {
    String[] cells = { "NZNZNNN", "NNZNNNZ", "NNNNZZZ", "ZZZNZZN", "ZZNZNNN", "NZZZZNN", "ZZZNZNN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case5() {
    String[] cells = { "ZZZZ", "ZZZZ", "ZZZZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case6() {
    String[] cells = { "N" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case7() {
    String[] cells = { "NN", "ZZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case8() {
    String[] cells = {
      "NZN",
      "NZN",
      "ZNZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case9() {
    String[] cells = { "NNNN", "ZZZZ", "ZZZZ", "ZZZZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case10() {
    String[] cells = { "ZZZNN", "NNNZZ", "NNNZZ", "ZZZNN", "NNNZZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case11() {
    String[] cells = { "ZZZNZZNNZNZ", "ZZZNZZNNZNZ", "NNNZNNZZNZN", "ZZZNZZNNZNZ", "ZZZNZZNNZNZ", "NNNZNNZZNZN", "ZZZNZZNNZNZ", "ZZZNZZNNZNZ", "ZZZNZZNNZNZ", "NNNZNNZZNZN", "ZZZNZZNNZNZ", "NNNZNNZZNZN", "NNNZNNZZNZN", "NNNZNNZZNZN", "NNNZNNZZNZN", "ZZZNZZNNZNZ", "ZZZNZZNNZNZ", "ZZZNZZNNZNZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case12() {
    String[] cells = { "ZNZNNZNZNNNZNZNZZNN", "NZNZZNZNZZZNZNZNNZZ", "NZNZZNZNZZZNZNZNNZZ", "ZNZNNZNZNNNZNZNZZNN", "NZNZZNZNZZZNZNZNNZZ", "ZNZNNZNZNNNZNZNZZNN", "NZNZZNZNZZZNZNZNNZZ", "ZNZNNZNZNNNZNZNZZNN", "ZNZNNZNZNNNZNZNZZNN", "ZNZNNZNZNNNZNZNZZNN", "NZNZZNZNZZZNZNZNNZZ", "NZNZZNZNZZZNZNZNNZZ", "ZNZNNZNZNNNZNZNZZNN", "ZNZNNZNZNNNZNZNZZNN", "NZNZZNZNZZZNZNZNNZZ", "ZNZNNZNZNNNZNZNZZNN", "ZNZNNZNZNNNZNZNZZNN", "NZNZZNZNZZZNZNZNNZZ", "ZNZNNZNZNNNZNZNZZNN", "NZNZZNZNZZZNZNZNNZZ", "ZNZNNZNZNNNZNZNZZNN", "ZNZNNZNZNNNZNZNZZNN" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case13() {
    String[] cells = { "ZZNZZNZZNZNNNNNZZNNNZNZNZZN", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "ZZNZZNZZNZNNNNNZZNNNZNZNZZN", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "ZZNZZNZZNZNNNNNZZNNNZNZNZZN", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "ZZNZZNZZNZNNNNNZZNNNZNZNZZN", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "ZZNZZNZZNZNNNNNZZNNNZNZNZZN", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "ZZNZZNZZNZNNNNNZZNNNZNZNZZN", "ZZNZZNZZNZNNNNNZZNNNZNZNZZN", "ZZNZZNZZNZNNNNNZZNNNZNZNZZN", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "ZZNZZNZZNZNNNNNZZNNNZNZNZZN", "ZZNZZNZZNZNNNNNZZNNNZNZNZZN", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "ZZNZZNZZNZNNNNNZZNNNZNZNZZN", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "ZZNZZNZZNZNNNNNZZNNNZNZNZZN", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "NNZNNZNNZNZZZZZNNZZZNZNZNNZ", "ZZNZZNZZNZNNNNNZZNNNZNZNZZN" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case14() {
    String[] cells = { "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "ZNZZZNNNZNNZNZZNNNZNZNNNZZZNNNNNNZZ", "NZNNNZZZNZZNZNNZZZNZNZZZNNNZZZZZZNN" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case15() {
    String[] cells = { "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "NZZZNNZZZZZNNZNNZZZZZZNNZZZNNNNZZNNZNZNZZNZ", "NZZZNNZZZZZNNZNNZZZZZZNNZZZNNNNZZNNZNZNZZNZ", "NZZZNNZZZZZNNZNNZZZZZZNNZZZNNNNZZNNZNZNZZNZ", "NZZZNNZZZZZNNZNNZZZZZZNNZZZNNNNZZNNZNZNZZNZ", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "NZZZNNZZZZZNNZNNZZZZZZNNZZZNNNNZZNNZNZNZZNZ", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "NZZZNNZZZZZNNZNNZZZZZZNNZZZNNNNZZNNZNZNZZNZ", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "NZZZNNZZZZZNNZNNZZZZZZNNZZZNNNNZZNNZNZNZZNZ", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "NZZZNNZZZZZNNZNNZZZZZZNNZZZNNNNZZNNZNZNZZNZ", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "NZZZNNZZZZZNNZNNZZZZZZNNZZZNNNNZZNNZNZNZZNZ", "NZZZNNZZZZZNNZNNZZZZZZNNZZZNNNNZZNNZNZNZZNZ", "ZNNNZZNNNNNZZNZZNNNNNNZZNNNZZZZNNZZNZNZNNZN", "NZZZNNZZZZZNNZNNZZZZZZNNZZZNNNNZZNNZNZNZZNZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case16() {
    String[] cells = { "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "NNZNZZNZZZZZZZNNNNZZZZZNNNNZNNZZZNZNZZNNZZZNNZNZNN", "ZZNZNNZNNNNNNNZZZZNNNNNZZZZNZZNNNZNZNNZZNNNZZNZNZZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case17() {
    String[] cells = { "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ", "ZNZNNZNZZZZNNNNNZNZZZZZZNZZZZNNNZZZNZNZNZNNZNNNZNN", "NZNZZNZNNNNZZZZZNZNNNNNNZNNNNZZZNNNZNZNZNZZNZZZNZZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case18() {
    String[] cells = { "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "NZNNZNNNZZZZZNZZZNNNZNZNNZNZNZNZZZNZNZZNNNZZNZNZNN", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ", "ZNZZNZZZNNNNNZNNNZZZNZNZZNZNZNZNNNZNZNNZZZNNZNZNZZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case19() {
    String[] cells = { "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "NNNNNZZNZZZZNNNZZZNNZZNNNZZZZNNNZNNNNZZZNNNNZNNZZN", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ", "ZZZZZNNZNNNNZZZNNNZZNNZZZNNNNZZZNZZZZNNNZZZZNZZNNZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case20() {
    String[] cells = { "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "ZNZNZNZNZZZZZNZZNNZZNNZNNNZNZNNNZZNNNNNNZZZZZZZZNZ", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN", "NZNZNZNZNNNNNZNNZZNNZZNZZZNZNZZZNNZZZZZZNNNNNNNNZN" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case21() {
    String[] cells = { "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case22() {
    String[] cells = { "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case23() {
    String[] cells = { "NNZZNZZNZNZZNNNZZNNNNZZZNNNZNNZNNNNNNNZNNNNZNZZZN" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case24() {
    String[] cells = { "Z", "N", "Z", "N", "N", "N", "Z", "N", "N", "Z", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "Z", "N", "Z", "N", "N", "N", "Z", "Z", "Z", "Z", "Z", "N", "Z", "N", "N", "N", "Z", "Z", "Z", "N", "Z", "Z", "Z", "N", "Z", "N", "Z", "Z", "N", "Z" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case25() {
    String[] cells = { "ZZ", "ZN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case26() {
    String[] cells = { "NN", "ZN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case27() {
    String[] cells = { "ZZ", "NZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case28() {
    String[] cells = { "NN", "NZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case29() {
    String[] cells = { "ZZZ", "ZNZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case30() {
    String[] cells = { "ZZZ", "ZZN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case31() {
    String[] cells = { "ZZN", "ZZN" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case32() {
    String[] cells = { "NNZ", "ZNN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case33() {
    String[] cells = { "ZNN", "ZZZ", "ZZZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case34() {
    String[] cells = { "NNN", "NNN", "ZNZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case35() {
    String[] cells = { "NNZ", "NZN", "ZZN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case36() {
    String[] cells = { "NZN", "NZN", "NNZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case37() {
    String[] cells = { "NZZZZNNZZNNNNN", "ZNNNNZZNNZZZZZ", "ZNNNNZZNNZZZZZ", "ZNZNZNNZZNNNNN", "ZNNNNZZNNZZZZZ", "ZNNNNZZNNZZZZZ", "ZNNNNZZNNZZZZZ", "ZNNNNZZNNNZZZZ", "NZZZZNNZZNNNNN", "NZZZZNNZZNNNNN", "ZNNNNZZNNZZZZZ", "ZZZZZNNZZNNNNN", "ZNNNNZZNNZZZZZ", "NZZZZNNZZZNNNN", "NZZZZNNZZNNNZN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case38() {
    String[] cells = { "NNNNNNZZZNZNNZZZNZ", "NNNNNNZZZNZNNZZZNN", "ZZZZZZNNNZNZZNNNZZ", "ZZZZZZNNNZNZZNNNZZ", "ZZZZZZNNNZNZZNNNZZ", "ZZZZZZNNNZNZZNNNZZ", "NNNNZNZZZNZNNZZZNN", "ZZZZZZNNNZNZZNNNZZ", "NNNNNNZZZNZNNZZZNN", "NNNNNNZZZNZNNZZZNN", "NNNNNNZZZNZNNZZZNN", "ZZZZZNNNNZNZZNNNZZ", "NNNNNNZNZNZNNZZZNN", "NNNNNNZZZNZZNZZZNN", "NNNNNNZZZNZNNZZZNN", "NNNNNNZZZNZNNZZZNN", "NZNNNNZZZNZNNZZZNN", "ZZZZZZNNNZNZZNNNZZ", "NNNNNNZZZNZZNZZZNN", "ZNZZZZNNNZNZZNNNZZ", "NNNNNNZZZNZNNZZZNN", "NNNNNNZZZNZNNZZZNN", "NNNNNNZZZNZNNZZZNN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case39() {
    String[] cells = { "ZNZNZZZZZNZNNZZZNNNNNN", "NNZNZZZZZNZNNZZZNNNNNN", "ZNZNZZZZZNZNNZZZNNNNNN", "NZNZNNNNNZNZZNNNZZZZZZ", "ZNZNZZZZZNZNNZZZNNNNNN", "ZZZNZZZZZNZNNZZZNNNNNN", "ZNZNZZZZZNZNNZZZNNNNNN", "ZNZNZZZZZNZNNZZZNNNNNN", "ZNZNZZZZZNZNNZZZNNNNNN", "NZNZNNNNNZNZZNNNZZZZZZ", "ZNZNZZZZZNZNNZZZNNNNNN", "ZNZNZZZZZNZNNZZZNNNNNN", "NZNZNNNNNZNZZNNNZZZZZZ", "NZNZNNNNNZNZZNNNZZZZZZ", "ZNNNZZZZZNNNNZZZNNNNNN", "ZNZNZZZZZNZNNZZZNNNNNN", "NZNZNNNNNZNZZNNNZZZZZZ", "NZNZNNNNNZNZZNNNZZZZZZ", "ZNZNZZZZZNZNNZZZNNNNNN", "NZNZNNNZNZNZZNNNZZZZZZ", "ZZNZNNNNNZNZZNNNZZZZZZ", "ZNZNZZZZZNZNNNZZNNNNNN", "ZNZNZZZZZNZNNZZZNNNNNN", "NZNZNNNNNZNZZNNNZZZZZZ", "ZNZNZZZZZNZNNZZZNNNNNN", "ZNZNZZZZZNZNNZZZNNNNNN", "NZNZNNNNNZNZZNNNZZZZZZ", "ZNZNZZZZZNZNNZZZNNNNNN", "ZNZNZZZZZZZNNZZZNNNNNN", "ZNZNZZZZZNZNNZZZNNNNNN", "ZNZNZZZZZZZNNZZZNNNNNN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case40() {
    String[] cells = { "ZZZNNNZZNNNZZNZZNZZZNNZZZN", "NNNZZZNNZZZNNZZNZNNNZZNNNZ", "NNNZZZNNZZZNNZZNZNNNZZNNNZ", "NNNZZZNNZZZNNZZNZNNNZZNNNZ", "ZZZNNNZZNNNZZZNZNZZZNNZZZN", "ZZZNNNZZNNNZZNNZNZNZNNZZZN", "NNNZZNNNZZZNNZZNZNNNZZNNNZ", "NNNZZZNNZZZNNZZNZNNNZZNNNZ", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "NNNZZZNNZZZNNZZNZNNNZZNNNZ", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "ZZZNNNNZNNNZZNNZNZZZNNZZZN", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "NNNZZZNNZZZNNZZNZNNNZZNNNZ", "NNNZZZNNZZZNNZZNZNNNZZNNNZ", "NNNZZZNNZZZNNZZNZNNNZZNNNZ", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "ZZZNZNZZNNNZZNNZNZZZNNZZZN", "ZZZNNNZZNNNNZNNZNZZZNNZZZN", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "NNNZZZNNZZZNNZZNZNNNZZNNNZ", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "NNNZZZNNZZZNNZZNZNNNZZNNNZ", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "ZZZNNNZZNNNZNNNZNZZZNNZZZN", "NNNZZZNNZZZNNZZNZNNNZZNNNZ", "NNNZZZNNZZZNNZZNZNNNNZNNNZ", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "NNNZZZNNZZZNNZZNZNNNZZNNNZ", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "ZZZNNNZZNNNZZNNZNZZZNNZZZN", "NNNZZZNNZZZNNZZNZNNZZZNNNZ", "NNNZZZNNZZZNNZZNZNNNZZNNNZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case41() {
    String[] cells = { "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNZZ", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "ZZZZZZZZZNNNNNZZZZNNNZNNNNZZZN", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "NNNNNNNNNZZZZZNNNNZZZZZNZZNNNZ", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "ZZZNZZZZZNNNNNZZZZNNNNNNNNZZZN", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "NNNNNNNNNZZZZZNNNNZZZZZNZZNNNZ", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "NNNNNNNNNZZZZZNNNNZNZZZZZZNNNZ", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "NZNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "NNNNNNNNNZZZZZNNNNZZZZNZZZNNNZ", "NZZZZZZZZNNNNNZZZNNNNNNNNNZZZN", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "ZZZZZZZZZNNNZNZZZZNNNNNNNNZZZN", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ", "ZZZZZZZZZNNNNNZZZZNNNNNNNNZZZN", "NNNNNNNNNZZZZZNNNNZZZZZZZZNNNZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case42() {
    String[] cells = { "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZNZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZNZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case43() {
    String[] cells = { "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZNZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZNZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case44() {
    String[] cells = { "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZNZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZNZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZNZNZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case45() {
    String[] cells = { "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNN", "NNZNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NZNNNNNNNNNNZNZNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNZNNNNNNNNZNNNNNNNNNNNZNZNNNNNNNNNNZNNNNNNZ", "ZNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNZNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "ZNNNNNZNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNZNNZNNNNNNZNNNNNNNNNNNZNNNNNNNNNNZNNNNNNNZNN", "NNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNN", "NNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNZNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNN", "NZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNN", "NZNNNNNNZNNNNNNNNNNNNNNZNNNNNNNNNNNNNNZNZNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNZNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNZNZNNZNZNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NZNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNZNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNZN", "ZNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNN", "NNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNZNNNZNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNZNNNNNNNNNNNNZNNZNNNNNZNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNZNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNN", "NNZNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNZNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNN", "NNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNN", "NZNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNZNNZNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNZNNNNN", "ZNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZ", "NNZNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNZNNNNNNNNNNN", "NNZNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNZNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNZ", "NNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case46() {
    String[] cells = { "NNNNNNNNNNNNNNNNNZNZNNNNNNNNNNNNNNNNNNNNNNNNNZNNNN", "NNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNZNN", "NNNNNNNNNNNNNZNZNNNNNNNNNNNNNZNNNNNNNZNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNZNNZNNNNNNNNNNNNNNZZNNZNNNN", "NNNZNNNNNNNZNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNZNNZNNN", "NNNNNNNNNNNNNZNZNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNZNNNZNNNNNNNNNNNNZNNNNNNZNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZZZNNN", "NNNNNNZNNNNNNNNNNNNNNZNNNNNNNNNNNNNNZNNNNZNNNNNNNN", "NNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNZNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNN", "NZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNZNNNNNNNNNNNNNNNNNNNNNZNNNNNNNZNNNNZNNNNZNNNZNN", "NNNNNNZNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNN", "NNNZNNNNNNNNNNNNNZNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNN", "NNNNNNNNNZNNNNZNZNNNNNNNNNNZNNNNZNNNNNNNNZZNNNNNNN", "ZNNNNNNNZNNNNNNNZNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNZN", "NNZNZNNNZNZNZNNNNNNNNNNNNNNNNNNZNNNNNNNNZNNNNNNNNN", "NNNNNNNNNNNNNNNNNNZNZNNNZNNNNNNNNNNNNZNNNNNNNNNNNN", "NNNZNNNNNNNNZZNNNNNNNNNNNNNNNNNNNNNNNNNZNNNZNNNNNZ", "NNNNNNZZNNNNNNZNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNZNNZNNNNNNNNNNN", "NNNNNZNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNZNNZNNNNNZNN", "NNNNNNNNNNZNNNNNNZZNNNNNNNNNNNNZNNNNNZNZZNNNZNNNZN", "NNNNNNNNNNNNNNNNZNNNNNZZNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNZNNZNZNZNNNNNNNNNNNNZNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNZNNN", "NNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNN", "NNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNZNNNZNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNZNNNNNNNNNNNNN", "NNNNNNNNNNNZNNZNNNZNNNNNZNNNNNNNNNNNNNNNNZNNNNNNNN", "NNZNNNNNNNNNNNZNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNN", "NNNZNNNNNNNNNNNNNNNNNNNZNNZNNNZNNNNZNNNNNNZNNNNZNN", "NZNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNZNNNNNNNNNNNNNNZ", "NNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNZZZNZNN", "NNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNN", "ZNNNNNNNNNNNNNNNNNNNNZZNNZNNNNNNNNZNNNNNNNNZNNNNNN", "NNNZNNNNNNNNNZNNNNZNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNZNNNNNZNZNNNNNNNZNNNNNNZNNNNN", "NNZNNNNZNNNNNNNNNNZZNNZNNNNNNNNNNNNNNNNNNNNNNNZNNZ", "NNNNNNNNNNNNNNNNNNNNNNNNNNZNZNNNNNNZZNNZNNNNNNNNNN", "NNNNNNNNNNZNNZNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNN", "NNNNZNNZNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case47() {
    String[] cells = { "NNNNNNNNNNNNZNNNNNZNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNN", "NZNNNNNNNNNZNNNNNNNNNNNNNNNZZNZNNNNNNNNNZNNNNNNZZZ", "NNNNZZNNNNNNNNNNNNNZNNZNNNNNNNNNZNNNNNNZNNNNNNNNZN", "NNNNNNZNNNNNNZNNNZNNZNNNZNNNNNNNNNNNNNNNNNNNNNNZNN", "NZNNNNNNNZNNNNNNZNNNNNZZNNNNNNNNNNZNNNNNNNNNNNNNNN", "ZNNNNNNZNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNZNNNNNNNNNN", "ZNNNNNNNNNNNNNNNNNNZNNZNNNNNNNNNNNNNNNNNNNNNNNNNNN", "ZNNNNNNNNNZNNNZNNNNNNNNNNZNZNNNNNZNNZNNNZNNNNNNNNN", "ZNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNZNZZNNNZNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNZNNNNNZNNNNNNNNNNZZNNNNNNNNNZNZNNNNNNNNZNNNN", "NNNNNZNNNNNNNNNNNNNZNZNNNNNNNNNNZZNZZNNNNNNNNNNNNN", "ZNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNZZNNNN", "NNNZNNNNNNNNNNNNNNNNZNNNNNNNZNNNZNNZNNNNNNNNNNNNNN", "NNNNNNZNNNNNNNNNNNNZNNNZNNNNNNNNNNNNNNNZNNNNNNNNZN", "NNNNNZNNNNNNNNNZNZNNNZNZNNNNNNNNZNNZNNNNNNNNNNNNNN", "NNNNNNNNZNZNZZNNNNNNNNNNNNNNNNNNZNNNNNZNNNNNNNZNNN", "NNNNNNNNNZZZNNNNNNNNNNNNNNNNNNNZNNNNNNNNZNNNNNNZNN", "NNNNNNNNNNNNNNNNNNNZNNNNNNNZNNNZNNNNNNNNNNNNNNNNNN", "NNNNNNNNZNNNNNNZNNNZNNNNNNNNNNNNNNNNNNZNNNNNNNNNNN", "NZZNNNNNNNNNZNNNNNNNNNNNNNNNZNZNZNNNNNNNNNNNZNNNNN", "NZNNNZZNNNNNZNNNNNNNNNZNNNZNNNNNNNNNZNNNNNNNNNNNNZ", "ZNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNZNNNZNNNNNNNNN", "NZNZNNNNNNNNNNNNNNNZZNNNNZNZNZNNNZZZNNNNZNNZNNNNNN", "NZNNZNNNNNNZZNNZNNNNNNNNZNNNNZNNNNNZNZNNNNNNNNNNNN", "ZNNNNNNNNNNNNNNNNNNNNNZNNNNZNNNNNNNNNNNNNNNNZNNNNN", "NNNNNNZNNNNNNNNNNNNZNNNNNNNZNNNNZNNNNNNZNNZNNNNNNN", "NNZNNZNNZNNNNZNNNNNNNNNNZNNNNNNNZNNZNNNNNNNNNZNNNN", "NNNNNNNZNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNNNZNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNZNNNNNZNNNNN", "NNNZZNZNNNNNNNNNNNNZNNNNZNNNNNNNNNNNNNNNNNNZNNZNNN", "NNNNNNNNNNNNNNZNNZZNNNNNNNNZNNNNNZNNNNNNNNNNNNNNZN", "ZNNNNNZNNNNNNNNNZZNNNNNNNNZNNNNNNNNNNZNZNNZNNNZNNZ", "NNZNNNNZNNNNNNNNZNNNNNNNNNNNZNNNNNNNNNNNNZNNNNNNNN", "NZNZNNNNNNNNNNNNNNNZNNNNNNNNNZNNNNNNNNNNNNNNNNNZNN", "NNNNNNNNNZZZNNNNNNNNNZNNNNNNNNNNNNNNZNNNNNNZNNZNNN", "NNNNNNNZNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNZNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNZNNNNNNN", "NZNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNZNNNNNNNNNNZNNZNZNNNNNNNNNNNNNZNNNZNZN", "NNNNNZNNNNNNZNNNNNNZNNNNNNNNNZZNNNNZNNNZZNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNZNNNNNNNZNNNNNNNNNNNNNNN", "NNNZNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZNZ", "NNNNNNNNNNZNNNNNZNNNNNNNNNNNNNZZNNNZNZNNNNNNNNNNNN", "NNNNNNNNNNNNNNNZNNNNNZNNNNNZNNNNZNNZNNNNNNNNNNNNNZ", "NNNNNNZNNZNNNNNNNNZNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNZNZNNNNNNNNNNNNNNZNNNNNNZNNNNNNNNNNZ", "ZNNNNNNNNNZNNNNNNNNNNNZNNNNNZNNNNNNNNNZNNNNNNNNNNN", "NNZNNNNNNNNNNNNNNNNNNNZNNNNNNNNNNNNNNNNNNZNNNNNNNN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case48() {
    String[] cells = { "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "NZZZZNNNNZNNNNZNNNZZZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "NZZZZNNNNZNNNNZNNNZNZZZZZZNNZNZNZNNZNZZNNNNNZNZNZZ", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN", "ZNNNNZZZZNZZZZNZZZNZNNNNNNZZNZNZNZZNZNNZZZZZNZNZNN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case49() {
    String[] cells = { "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZZNNZZZNNNNZNNNNNNNNNZZZN", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "ZNZNZZZNNNNZZNNZNZNNZNNZNZNNNZZZNNNNZNNNNNNNNNZZZN", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ", "NZNZNNNZZZZNNZZNZNZZNZZNZNZZZNNNZZZZNZZZZZZZZZNNNZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case50() {
    String[] cells = { "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNZZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "ZNZNZNNZNZNZNNZNNZNNZZNZNZNNNZNNNZNZZNNZNZNZZZZZZN", "NZNZNZZNZNZNZZNZZNZZNNZNZNZZZNZZZNZNNZZNZNZNNNNNNZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case51() {
    String[] cells = { "NNZZZNNNZZZZNNNZNZZZZNZNZZNNZNZZZNNZNNNZZNNNNZZZNZ", "ZZZZZNZNNZZZZNZNNNNNNNZNZZZZNZNNZZZZZZNZNNNZZZZNNN", "ZNNZZZZZZZZNNNZNZNZNZNNNNZNNZNZNNNZNNZZNZNNNNNNZNN", "ZNZZZNZNNNZNZZNZNNNNNZZNNNZNZNZZZZNNZZNZNZZNZNZZZN", "NNNNNNZNZNNNNNNNNNZZNZNZZZNNNNNNNNZNNZZNNZZZNZZZZZ", "NNNZZNZZZNZNZZZZZZNNNZNZZNNZNNZZZZZZZNNZZNNZNNNNZN", "NZNNZZZZZZNZNNNZZZZNZZNZZZZZZNNZZZZZNNZNZNZNNZZNZZ", "ZZZNZZZZZNNNZNZZNNNZNZZZZNNNNZNNZNZNNNZZZZNNNNNZZN", "ZNNNNNZNZNNNNZNZZNNNZNNZZZNNZZNZNZNZZZZZZNNZNZZZZN", "NZNNZZZZNNNZNNNZZNNNNNZNNZNZNZZZNZNNZNNZZZZZZNNZZZ", "NZZNZZNNNNZZZNZNNNZNZNNZZNNNZZNNNNZZZNNZZZNNZNZNZZ", "NZZNNNNNZNZNZZZZNNZNZZZNZZNZNZZNNZNNZZZZZNNNZZZZZN", "ZZZNZNNZNNNNZZNZZZZZZNNNZZNNZZNNZNNZZZNZZNZZNZZZZN", "NZZNNZZZNNZZNNNZZNZZNZZNZZZNZZZZZNZNZZNNNNNNNNZZNZ", "NZZNNZZNNNZNNZNNNZNNZZNNNNZZZNZZNZNNZNZZNZNZNZNNZZ", "NZZNZZNNNNNNNNNNNNZNNZNNNNZNNNZZZZZNNZNNNZZZZNNZZZ", "NNNZNZZZNNZZNNZNZZZZNNZNZNNZZNNZZZNNNNZNNNZZNZZNZN", "NZZZNZZNZZZNZZZZNNZZZZNNNZZNNZNZZNNNZNNZNZZNNNZZZZ", "NZZNZZZZZZNNZZNNNNZNNZNNNNNZNZZNZNZNNZZNZZNNNNZZZN", "ZZZZNNZNNZZNNZNZZZNNZNNZZNNNNZNNZZNNNZZZZNZNZNZNNN", "ZZZZNNZNZNNNNNZZNZNNZZNNZZZZNNNNNZNZZNNNZZZZZZZZZZ", "ZZZNNZZZNZNNZNZNNZZZZZNNZZNZNZNZNNZNNZNZZZZZNZZZNZ", "NZNZNNNZNNNNZNZZZNZZNNZZNNZNNNNNNNNZZNNZZNNZNNNZZN", "NNNNZNNZNNZZZNNNZNZNNZZNZZZZZZZNZNZZZZNNNNZNNNNNZZ", "NNZNZZZZNZNNNZNZZZZZZZZZZZNZNNZNZZNZNZNZNNZNNNNNNZ", "ZZNNNZNNNZZNNNZNNZNNZZNNZNNNZZZZNZNNZZZZNZZNNZZZZN", "ZZNNZNZZZNZNZNNZNZZZNZZNZZZZZNZNNZZNNNZNZNZNNNNZNN", "ZNZZNNZZZZZNNZNNNNNZZNNZNZZNZZZZNNZZNZZZNZZZZNNZNZ", "NZZNNNNZZNZZNNZNZZZZZNNZZZNNNZNZZZZNNNNZNNNZZZZNZZ", "NNNZNNZZNZNZZZZNNZNZZZNNZZZZNNZZNZNNNZZNNNZNZZZZNZ", "NNNNNNNNZZZZNZZNZNZZNZZNZZNZNNZNZZZZZZZNZNZZZZNNZN", "ZZZZZNZZZZNNNZZNZNZNNNNZNZNNZNNZNZZNZZZZZZZNNZZZZN", "ZZZNZNNNNZNNNZNZZZNNZNNNNNNNNNZNZZNNZNZZZZZZZNNZZN", "ZNNZNZNNNZNNNZNNZNZNZZNNZZZZZZNZNNZNNZZNNZZNZNZNNN", "ZZNZZZNZNNNZZNZZNNNNZZNZZZNNNNZNZZNNZNZZZNNNNNNNZZ", "ZNZNZNNZNNZNNZZZZNNNZNNNZZNNZNNNNNZZNZNNNNZNZNZNNZ", "NNZNNNZNZNZZZZZNNNZNZZZNNZZNZZNZNNZNZNZZZNNNZNNNNN", "NNZZNNNZZNNZNNZNNZNNZNZNNNNZNNZNZZZNZZZNZZNZZNZZNN", "ZZZZNZNNZZNNNNZNZNNNZNNNNZNNZZNZZZNZNZNNNZNNZZZNZZ", "ZNNNNZZZZZNZZZZNZNNNZZNZNZZZZZZZNZZZNNZNZNZNZZZZZZ", "ZNZNZNZNZZZNNZZZZZNZNNNZZNZNNZNNNZNNZNZZNZNNZZNNNZ", "ZZNZZZNZNNZNNNZZNNNNZZZZZNNZZNZNNZNZZZNZNZZZNNNNNN", "NNNZZZNZZNNNNNZZNZNZZNNZZNNZZNZNZZZZNZNNNNZZZNNZZN", "ZZNNNZZZNNZNZNNZZNZZZNZNNNZNNZZNZZZNZNZZZZNNNNZNZZ", "ZNNNZZZNNZNZNZNNNZZZZZZNZNZNZZNNZNNZNZZZZNNNNNZNNZ", "NZZZZZNZNNZNZNZZZNZNNZNZNNZNNNZNNNZNZZZZZZNZNZZNZN", "ZNNNZZZZNZNZZNZZNNZNZZNZNZNZZNNNNNNZZZNZNNNZZZNZNN", "ZNZNZNNZNNZNZZZZNZZZZNNZZZZZZNZNNZNNNZNZNZZZZZZZNZ", "NZZNNNNNNZNNZNNZNZNNZNZNZNNNZNNNZNZZZZZZNZZZZNNZZZ", "NNZNNZZZNNZNZNNNNZZZNZNNZNZNZZZNZZNZNZNZNZNNZZNNZZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case52() {
    String[] cells = { "ZZZNZNNNZZNZNNZNNZZZNZZNZNNZZZNNNNZZNNNNNZNZZNNNZN", "ZNNNZNNNZNZNNZNNZZZZZZZZNNNNNZNZZZNZZNZNNNNNZNNZNZ", "ZZNZZNZZNNZNZNZNZZNZNZZZZZNNNZNZNZZNNZZZNNZNZNZNNN", "ZZZNNNZNZZNNZZNZZNZNNZNNNNZZNZZNNNNZZZNZZNNNNZNZNZ", "ZNZNNNNZNZZZNNNZNZZZZZZNNNNZNNZNZNZZNNNNNNZNNNNNNZ", "NZNNNZNNZZZZZZZZNNNZZNZZNNZNNNZNNNZNNZNNZNNZZNNNNN", "NZZNNNNZZZNNZNNNZNNNNZZNNNNNNNNNZZZNNZNZNNZZNNZNNN", "ZNZNZNNNNNZZNNZNNZZNZNZNZNZZZNZNZNZNZNZNNZNNZNZZNZ", "NNZZNZNNNNZNZNNNNNZZZZZZZZNZNNZNNNNNNNNZZZNZNZZNNN", "NZZNZNNNNZZZNNNZNNNNNNNZZNNNZZZNNZZNNZNZZZNNZNNZZZ", "NZZZNNZNZNNNZZNZZNNZZZZZNZZZNNZZZZZNZZNNNZNNNZNNZN", "ZZZNZZZZZNNZNNNNNZZNNNNNZNZZNZNZNZNZNNNNZZNZZZNZNZ", "NZNZNNZNNNNNZZNNNNNNNNZNZNNZZZZZZZNZNNZZNNNNZZNZNZ", "NNZNNZNNZNZNZNZNNNZNNNZNNNNZZZZZZZZNNNZNNNNNZZZZZN", "NNZZZNZZNNNZZNNNZNNZNZZNNZNZNZNZNNNNNNZZZNZNNNZNZZ", "ZNZNNNZNZZZNZNZZNNZNZNNNNZNZZZNZNNNZNNNNNZZNZNZZZZ", "NNNNNZNZZNZZNZNNNNNZNNZZNNZNZNNNZZNZNZZNNNNZNZZNNN", "NZNNZNNZNZNNNZZNZNZNNNZZZZNNZZZZNZZZNZZZZNZZNZNNZZ", "ZZZNZZNZNZNZNZNNZZNZZZNZNZZNNNNZNZNNZZNNNZNNNNNZZN", "NNZNZNZZZZZNNNZNZNZZZZZZZNZNNZNNNNNNNZZNZNZZZNZZZN", "ZNZNZZZZNZZZZZZZNZNZNNNZNZNNNNZNZNNNNZNNZNNNNZZZNZ", "ZZNZNNNZZZNZZZZZNNZZNNNNNNZNNNZZNZNZNNZZNZZZZZNNNN", "NNNZNZNZZZNNNZZZZZNNZZZZZZNZZZZNZZZNNNZNNZNZNNZNZZ", "ZNNZZZZNZNNZNZZNNZNZZNZNNNZZZNNZNNZZZZNNZNNZNZNZZN", "ZZZZZNNNNNZZNZZNNZZNNNNZNZNZZZNZZZZZNNZNZNZZNNZNNZ", "NZZNZNNNZZZNZNNZZZZNZZZZZZZZNZNNNNNZZZNZNNZNZNZZNZ", "NZNZNZNNNNZNNZNNNZZZZZZNZNZNNNZNZNZNNZZNNZNZNZNNNZ", "NZNNNNZNZZNNZNZZNNNZZNZZNNZZNNZNNZZZZZNNNNZZZNNZNZ", "ZZNZZZNZNZNNZZZNNNZNNNNZNNZZZNNZZNZZNZNZZNZNNZNNNN", "NNNZZNZNZNZZNNNNZNNZZZNNZNZNNZZZNNNZZNNNZZNZNZNNZN", "ZNZZZNNZNZNZNNZNNZZNNZNZNNNZZZZZZZNZNZNZZNZZNZNZZZ", "ZNNNNNZNZZZZZNZZZZZZZNZZZZZNZNZZNNZZZNZZZNZNNZZNZZ", "ZNZZZZNNZZZNZZZNNZZZZZZZZZZNZNNNNNNNNZNNNZNZNZZZZZ", "ZNNZZZZNNZZNZZNZNZZZZZNNZZZZZZZZNZNNNNZZZNNZZZNNZZ", "ZZZNNZZNNNZZZZZZNZNZZNZNZNZZZZNNNNZZNNZNNNNNZZNNNZ", "NNZZZZNNNNZNZNZNZZZZNZNNNNZZZNNNZNNNNNZNZNNZNNNZNZ", "ZNZZNZZNZZZZZZNZZZNNZZNZZNNNNNNZNNNNZZZZNZNNNZNZZN", "ZZZZNZZZNNNNZZNNNNNNZZZNNZNNZNZZZNZNNNNNZZNNNZZZNN", "NNNNZZNNZZZZNNNNNNZZZNNNNNZNNNNNZZZNNZZNZNNNZNNNNN", "ZNZNZNZZZZNZZZNNNNZZZZNZZZNNZNZNNNZNZZNZNZNZNZNNZN", "ZNZNZNNZNNNNZZZNNNZZNZNNNZNNNZNZNNNZZZZNNNNNZNZZZZ", "ZNZZNZZZNZNNZNZNZZZZZNZZZZZNNNZNZNNZNNZZNZNZZZZZZN", "NZZNNNZNNZNZNZZZZZNZNNNNNNNNNZNZZNZNZZZNNZZZNNZZZN", "ZNNZZZZNZNNZZZZZZNZZZNNNNZZZNZNNZNZNZNZNZZZNZZZNZN", "NNNZNZNZZZZNZZNNNNZNZNNNNZNZNZNNNZNZZZZZNZNNNNNNNN", "ZNZZZNNNNNNNZNZZNZZZNZZZNNZNNZZNNNNNZZNZZNNZNNNZZZ", "ZNZZNZZZNNNNZZNZNZNZZNZNZZNZNNNZNZNNZZZNNNNNNZNZNN", "NNNNNNZNNZZNNNZZNZZNZZZZNNNZZZZZNZNZZZNZNZZNNZNZZZ", "NZNZNNNZZNZZZZZNNZNNZZNZNZZNNZZNZNZZZNZZNNZZZNZNZN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case53() {
    String[] cells = { "NZZNNNNZZZZZNZNZZZZZZZZNNZNZNNZNZNNZZZNZZNNNNNNZZZ", "NNNZNNZNNZNNNNNZZNZZZZZZZNZNNNNZZZNZNZNZZNNNZNZNNN", "NNZNNNNNZZZZNZNZNZZZZZZNNNZNZNZZNNZZZZNZNNZNNZZNNN", "ZZNNNNNZZZZZZNZZZZZNZNZNNNNNZNNZNNNNZNZNZZNZNZZZNN", "ZZNZNZNZZNNNZNNNNNNZNZZNNZZZNZNZZNZNZNNZNNNZNNZZZZ", "NZZZNZZNZNNNZNZNZNNNNNZZNNNZZZZNNZZNNZNZNNZZZZZZZZ", "NNNZNZNZZNNZNNNZZZNNZNNZNZZNZNNZZNNZZZZZNNZZNNNZNN", "NZZNNNNZNZZZZNZZZZZZNZNNZZZZZNNZZNNZNNNNNZNZNNNNNN", "NZZNZZZNNZNNZNNZNNZZNZZNNZZNZZNZNNNNZNZZNZNZZNNZNZ", "NNNZNZZNZZNZNZZNZNNZZNNNNZNZNZNZZNZZNZNZZZZZNZNZZN", "ZZNZZZNNZNZNZNZZNNNNZZZZNZZZNZZNZNNNZNZNNZNNZNZZNN", "ZZZNNNNZZNNNZZZZZNNZZNZZNZNNNNZZZZNZZZNNZNNNNNNZNN", "NZZZNZZZZNZZZZZNZNZZNZNNNZZNZNNNNNZNNZZZZNZNZZZNNZ", "NZNNZZZNZZNNNZNNNZZZZZNZNNNNNNZZNNZNNZZNZNZNNZNNZZ", "NZZZZZNZZNNNZNNNZNZZZNNNNNNZZNZZNZZNZZZZZNNNZZNZZZ", "ZNZZZZZNNNZNZZNNZNNZNNZZZZZNNNZNNZZZNNZZZNNZNZZZNN", "ZNZNNNZNZNZNZNZNNZZZZZNNZZNZZZNNNNZZZNZNZNZNNNZZNZ", "ZNNNZZNZNZZNNZZZZZZZZZZZNNNNNNNNNNNZZZZNNNZZNZZNZN", "NNNZZNNNZNZZNZZNZZZNNZZNZZNNZNZZZZNZZZZNNZNNNZNNNN", "ZNNNNNZZZNZZZNNZNZNZZZNNNNNNNNNNZNNNZZNZNNZNZNNZZZ", "NZZZNNZZNZZNZNZZNZZZZZZZNZNZNNNNNNNNZNZZZNZZZNNZZZ", "NZNZNNNNNZZNNNZZNZNNZNZNZZNZZZZZZZZNZNNNNNNZZNNZZZ", "NZNZNNZNZZZNZNZZNZZNNZNNNNNNZZZNZNNNNNNNNNZNNNNZNN", "ZNZZNZZNNZZZZNNNZZNZNNZZNZZNZZNZZNNZNZNZNZZNNZZNNZ", "NZNNNZZZNZNZZZZNNZNNNZNZNNZZNZZNNZNNNZZZZNNZZNZZNN", "NNNNZZZZNZZNZZZNZNNNNNZNZZZNZNNNZNZZZNZZNNZNZZNZZN", "ZZNNNZZZZNZZNNNNNZZNZZZNZNZNZNZZZZNNZNZNZZZZZZNZNN", "ZZZZNZNZZNNZZZZNZNNZNZNNZNNZNNNNNZZNZNNNZZZZZNZZNN", "ZNZZNNZZNZZNNZZZNNNNNZNZNNNZZZZNZNZNNNNZZZNZNNNZZN", "NNZNNNNZNZZZNZZNNNNZZZZNZNZNZNNZNZNZZNZNNZNZNZZNZN", "NNNZNNNZNNNNZNNZNZNNNNZZNNZNZZNNZNNNNZZZZNZNZZNZZN", "NZZNZNZNZZNZZNNNNNZNZZNZNZNZZNZNNZZNZNNNNNZZZZNZZZ", "ZNZNZNZZNZNNNZNZZNZNZNZZNZNZNZZZZNNZNNNZZNNZZZNZNN", "NNZZZNNNNZZNZNNZNNNNNZZZZZZZNNZNNZZNZNNZZZZNNZNNZN", "NNNZZNNNNNZZZZNZNZNZNNNZZZZNZZNZZNNNZNZNNNZNZNZZNZ", "ZZZZNZZZNNZNNNZNNZNZNZNZNZNZZZZNZZNZZNNZZZNNNNNZNZ", "ZZZZNZNNZNZZZNNNZNZZNNZNNNNNZNZZNZNZZZNZNNNNZNZZNZ", "NNNNZNNNZNZZZZNZNZNNZNZNNZNZNNNZZZZNNNZZNNNNNZZZZN", "NZNNNZNZNZZZNZZNNNNNNNZZZZNNNNZNNZNZNZNNNNZZNNZZZZ", "ZZZNNZNZZNZNNNZZZZNZNNNNNNNZNZZZZNNNZNNNNNNNNZZZZZ", "ZZNZZNNNZZZNNZNNNNNNNZNNZZZZNNNNNNZZZNNZNNZNZZZZZZ", "NZZNNNNZNNNNZNNNZZNZNNZNNZZZZZZNNZZNZZZNNNZZZNNNNN", "ZNNNNZZNZZNZZNNZNZNNNNNZNZZZZNNZNZZNZZZZZNNZNNNNZN", "NZZNNZNNZZNNZZZNNNNZNNZNNZNZZZZZNZZNNNZZZNZZNNZZZN", "ZZNNNNNNZNNNZZZZNNZZNNZNZZZZNZNZNNZNZNZZNNNZNZNNNN", "ZZNZZZNNZNZNNZNZZZNZZZNZZZNZNNNNNZNZNNNZNNZNZNNZZZ", "ZZNNNNNZNNZNZZZZNNNNNNNNZNZZNNZNNNNNNNNNZNZZZZNNNN", "NZNNZZZZZZNZNZZNZZNNZNNZNZNZZNNNNNNZNNNZZZNNZNNZZZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case54() {
    String[] cells = { "ZNZNNZZNNZZZNZZNNNNZNZNZZZNNNNZNZNZZZNNZZNZZNZZZNN", "NZZZZZZZNZNZZNZNNZZZNZNZNZZZNZZNZNNZZZNNZZZNNZNNNN", "NNZNZZNZNNNNZZNZNZNNNNZNNZNNNZNNZNNZNNNNZNZZNNZNNN", "ZZZNNNZZZNNZZNZZNNNZNNZZNZZNZZZZNNZNZZNZNNZZZZNZZN", "ZZZZZZNNZNNNZZNNNZNNZZZZNZZZZZNZNZNNNZNNNZZZZZZZZN", "ZZNNNZZNNNNZNNNNZNNZZNNNZNNZNNZNNNNZZNZNNZNNZZZZNZ", "ZNZZNNNZNZNZNNNNNNZZNZNZZZNNZZNNNNZZNNZNZZZZNZZZZN", "NZNZNNNNNNNNNNNZNZZZNNZZNZZNNZZNZNZNNNNNZNNZZZZZZZ", "ZZNZNNNZNNNZZZZNZNNZNNNZZNNZNZZZNNZZZZNZNZZNZNNZNZ", "NZZZNZZNZNNNZZZZZNZNZNNNNNNNZNZNNZNNNZZNZNZNNZNZZN", "NZZZNNNZNZZZZNNNNZZZNNNZZZZZZZNZNNNNNZZNNNNNNZNNZN", "NZZZNNNNNZZZZNNNNZNZNNNNZNNNNNZZZNNNZZNNNNZNZZNNNN", "ZNZZNZNNNNNZZZNNNNZZZZZNNZZNNZZZZZZNZZNZNZZNNZNNNZ", "NNNZZZNNNNNZZZZZZZNZNZZZNNZZNZNNZZZZZNNNNNNNNNZZNZ", "NNNZNZNZZNZNNZNNZZZNNZZNNNZZZZNZNNZNNNZNZZNNZNZNZN", "NNZNNNNNZNNZNNNZZZZNNZNNNZNNZZNNNZZZZNZZNZZZNZNNZZ", "NZZZNNZNNZZNZZNNZZZZNZZNNNNNNNNZZNZZZZNNNZZZNNZZNN", "ZZZZNZNZNZZNZZZZNZNZNNNNNZZNZZZZZZNNNNZZNNNZNZNNNN", "NNNNNNZZNZZNZNZNNNNZNNNNNZNZZZZNZNNZZNZZNZNZZZNZNZ", "NNNNZZNNZNNZNZZZNZZNZNNZZNNZNZNNNZNZNNZNZNNZNZZZZZ", "NZNNNZNNNNZNNNZNZZNZZNZZZNNZNNNZNNZNZNZNZNNNNZNZNN", "NNNZZNZNNZNNZZZZNZZZNNZNZZNZNZNZNZZZNNNNNNNNNNNZNZ", "ZZZZNNNNNNNZNNNZZZNNNNZZNNNZZZNZZNNZNZNZZZZNNNZZNN", "NNNNZZZNNZNNZZNNZNNZNZZZNZZZZNZNZNZZNZNNNZZNNZZZZN", "NZZZZNNZNZZZZNNZZNNNNNZZNZZZZZNZNZZZNNNNNNNZZNZNNZ", "NZZNNZZZZZZZNNNZZZZNZZZNNNNZZNNZNNZNNNNNNZZZZZNNNN", "NZZZZZZNZZZNNNZZNNNNNZNZZZNNNZZNNNZZZNNZNZNZNNZZZN", "NNZNZNNNNNZNNZNNNZNZZZNNNZZZZZZZNZZZNZNNNZNZZNNNZZ", "NZNZZNNNNNNZNNZNNZZNZNZZNNNNZZZNZZZZNZZZNZZZNZNZZZ", "NZZZZNZZZNNZNZNNNNNZZNZNNZZZZZZNNNNNZZZZZNNNZNZNNN", "ZZNZZZZZZNNZNZZNZZNNNNNZZNZNZNZNNZZNZNZNZNZNZNNZNZ", "ZNNZNNZZZNNNNZNNZZZZZZZNZNZZZNZZNNZNZNZZNNZNZNZZNN", "ZNZNNZNZNNNZNNZZZNZNZNZZZZNZNZNNNNNZZZNZNNNNZZNZNN", "ZNZNZNNNNZNNZZNZNNZNNZNNZNNZNNNZZNNNZNZNNZNNZNZNNN", "ZNZZZZZNZZZZNNZNZNNZNZZZNNZNNNZZZZZNZNZZNZZZNNZZNN", "ZNNNZNNZNNZZZZNNZZZNNZNZZNNNZNNZZNZNZZZNZNNNNNZNZZ", "NNNZNNZNZNZNZZNNZZNZZZZNZZZZNZNZZZNZZZZZNNNNNNZNZN", "NNZNZZNNNNZZNNNNZNZZZNNNZNNZZNZNZZNNNNNNNZNNZNNNZN", "NNZZZZNZZZNZNNZNNZZNNNNZNZNZNNNZZNNNZNZZNNZNZNZNNZ", "NNZNNNNNZNNZNNNZNNZZZZNZZNZNNZNNNZNNZZZNNNZZZZNZZN", "ZZZZNNNNZNZNZNZNZNZNNNNNZZNNNZNNZNNZNNZNZNNZNZNNZN", "ZZZNZNZNNNZNZNZZNZNNZNNNNZNZZNZZNNNZNZZNZZZNNZZNZZ", "NZNZNZNNZZNZNZZNNNNZZNNZNZNZZZZZNNZNNNNNNNNZNNNZZN", "ZNZNZNNZZNNNNNZZZNNNNNNZNZNZNZNZNNZZZZNNNZZZNZZNNN", "ZZZNNNZZZZZZNZZZZZNZNZZZNNNNZZZNNZZZNZNNNNNZNZZNNZ", "ZZNNNZZZNNNNZNNNNZNZNNZZNNNNNNZZNNNZNZZNNNNZNNNNNN", "NZNNNZNZNZZNNZNZNZNZZNZZZNZZZZNNNZNNNZNNNNNZZNZNZZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case55() {
    String[] cells = { "ZN", "NZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case56() {
    String[] cells = { "NZ", "ZN" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case57() {
    String[] cells = { "ZN", "ZZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case58() {
    String[] cells = { "ZZZ", "ZZZ", "ZZZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case59() {
    String[] cells = { "NNN", "NZZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case60() {
    String[] cells = { "Z", "N" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case61() {
    String[] cells = { "NZ", "ZZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case62() {
    String[] cells = { "ZZZ", "ZNZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case63() {
    String[] cells = { "NNZ", "ZZN" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case64() {
    String[] cells = { "ZZZZZZZ", "ZZZZZZN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case65() {
    String[] cells = { "NNZNZ", "ZZNZN" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case66() {
    String[] cells = { "NZN", "ZNZ", "ZNZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case67() {
    String[] cells = { "NN", "ZN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case68() {
    String[] cells = { "ZZZNNNNNZZNZNNZZZZNNZZZZNZZNNZZNNZNZZZZZZNZNZZNZNZ", "ZZNNNNNNNZNNZNZZZNNZNZZZZNZNZZZNZZZZZNZNNZZNNNNZNN", "ZZZNZNZZNNZZZZZNNZNNNZNNZNZNNNNZNNZZZNZZNZNZNNNZZN", "NNZZNZZNZNZNZNNNNNNNNNZNNNNZZZZZNZZZNZZNNNZZZNNZZN", "NZNNNZZZZZZZZNNZNZZZZNZNZZNZNZNNNNZZZZZZNZZNZNNNZZ", "NNNZZZZZZNZZZNZZNNZZZZNNNZNNNNNNNZNZNZNZZZZZZZZNZN", "ZNNNNNNZNNZZZNNNZZNNZZZZNNZZZNZZZNNNNNZZNNZNZNNNZZ", "ZNZNNNZZZZZNZZZZZZZZZZNZNZNNNNZZZNNZNZNNZNZNNNNZNN", "ZNZZNZZNNZNZZNNZNZNNNNNZNNNZNZZZZNNNZZNZNZNZNNNZZZ", "NNNZZZNNZNZZNNZZZZNZZZNNZNZZNZZNZZZZNNNNNNNNNZNZNZ", "ZNZZNZZZNNNZZNZZNZZZZZNNNZNZZZZNNNZZNNZZZNZZZZNNZN", "ZZNNNNZNNZNNZNNNNZZZNNZNNZNZNNNNZZNZZNNNZZZNZNNZZZ", "ZZZZZNZZZZNZNZNZNNZNNZZNZNZZZZNNZNNZZZZNZZZZZNNZNZ", "ZZZZNZZNNNZNNZNZZNZZZNZZNNNZZNZZZNNZZNZNNZZNZZNNZN", "NNNZZNZNZZZNNZNNZZZZZZNNZZZNNZZZNZNZNZZNZNNZNNNNNZ", "ZZZNZNZZZNNNNZZZNNZNZZNNZNZNNNNNNNNZZZZZZZZNNZZZZN", "ZZZNNZNNZZZNZZNNZNNNNNNNNNZZNZZNNZNZZZZZZZNNZNNNZN", "NNNNZZNNNZNZZZNZNNNNZZNNZNZNZNNZZZZNZZZNZZZNZZNNZZ", "NNNZNZNZNNNZZNZNZZNNNNNZNZNZNZNNNNNNZNZNZZNZNNZNNZ", "ZZZNZZZZNNNNZNNZZNZNZZNZNZZZZZNNZZNNNNZZZNNZNZNZZN", "ZZNNNZNNNNNZZZNNZZZNZNNZNNNNZZNZNNZNNNNNNNNZZZZZNZ", "ZNNNNZNNZNZZZNNZZZNZZNZNNNNNNZZNNZZNZNNNZNNZNNZNZZ", "ZNNNZZZNZNNNNNZNZNZZNZZZNZNZNZZZZZZNNNNZZNNZNNNNZN", "NNZNNZNZNZNNNNNNZNNZNZZNZZZNZZZZZNNNNNNZZNZZNNZZNZ", "ZNNZNZZZZNNZNZNZZNZNZZZZZZNZZNZZNNZNNZZNZNZNNNNZNZ", "NZZZZNNNZZNNZNNNZZZNNNZNZNNZZNNNZZNZNZNNZZNNNZZZZN", "ZNZZZZNNNZZZNNNNNNZZZZZZZZNNZZNZNZNZNZNZNNZZNNZNNZ", "ZZNNNNZNZNZZNNNNNZZNNZZNNZNZZNZZZZZNNNNZNZZNNZNNZN", "NNNZNZZNNNZZZNZNZNNNNZZZNZNZZZNZNZZNZZNZZZNNNZZNNZ", "ZZZZNZNZNNZNNZNNZZNZNZNNNNZNZNNNZZZZZNNZZZZNZNZZNN", "NZZNZNNZNZNNNZZZNZNNZZNNZZNZNZZZZNNZZNNNZZNNZZZNNZ", "NZNZNZZNNNNZZNZNZNZNNZZZNZNZZNNZNNNZZZZNZZNZZZNNZN", "ZZZZNNNNNZZZNNNZNZZNNZNZZZNZZZNZZNZNNZZZNZZNNNZZNZ", "NNZNZNNNNNNNZZZZNNNZZZNNZNZZZZNZZZZZZZZNNNZZNNZNNZ", "ZZZZZNZNNNNZZZZZZZNNNNZZZNZZZNZNNNZNNNZZNNZZZZZNNN", "ZZNZZZZZNZNZZZZNNNZNNZZZZZZZNNZNNZZNZNNNZZZNNNNZNN", "NNZNNNZZNNNNNZNNNZZNZZZZZZZZNNZNZNNNNZZNZNNNNNNZZN", "ZZZNZNNZZNNNNNZZZZZZNNZZNZNNNNZZZZZNNNZZZZNNNNNZNN", "ZNZNNNZZZNNNZNZNZNNNZNNNZZNNZZZNNNNZNNZNZZZNZZZZZZ", "NNZZZZZZZZNNZZNZNZZNNNZNNZZNZNZZNZNNNZZZZZNNNZZZNN", "ZZZNZNNNNNNZNNZZNNZZNNZNZZZZZNZZNNZNZNZNZNZZZNNZNN", "NZZNNNZZZNNZZNNZZZZZNZZZNNNZNNZZZZNNNZNZNZZZNZZZNN", "NNZZZZZNNZNNZNZZZNZZNZNZZNNZNNZZNNZZZNZNZNNNNNZNNZ", "NZZZNZNNNZNNZNZNZNZZNNZZZZNZNNNZZNZNZNNZZZNNNNNZZZ", "NZNNNZZZZNNNZZZNNNZZNZZZNNZNZZNNNNZNNNZNNZNNNNZNNN", "ZNNZNNNNNZZZNZNNNNNZZNZNZNZNZZZZZZNZNZZZZZZNNZNZZZ", "NZNNZNZZNZZNNZZZZZZNZNNNNNNZZZZZNZNNZZZZZNZZZNZNZZ", "ZNZNNNNNZZNZNNNZZNNZZNZNZZZNNZNZZNZZZZNNZZZNNZNNNZ", "ZNNNNZZNNZNZNZZZNNZNNZNNNZZNNZZNNNZZZZNZNZNNZNNZZZ", "NNNZZZZZZNNZZNNNNZZNZZNNZZZZZZZZZZZNZNZZZNNZZNNZNN" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case69() {
    String[] cells = { "NN", "NZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case70() {
    String[] cells = { "NNN", "ZZZ", "NNN" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case71() {
    String[] cells = { "ZNZ" };
    assertEquals("Yes", threecolorabilityeasy.isColorable(cells));
  }

  @Test
  public void case72() {
    String[] cells = { "ZZZN", "NZZZ" };
    assertEquals("No", threecolorabilityeasy.isColorable(cells));
  }

}
