package topc.test.graph;

import junit.framework.*;
import org.junit.Test;
import static org.junit.Assert.*;
import topc.graph.*;

public class WordTrainTest {
  WordTrain wordtrain = new WordTrain();

  @Test
  public void case1() {
    String[] cars = { "CBA", "DAA", "CXX" };
    assertEquals("ABC-CXX", wordtrain.hookUp(cars));
  }

  @Test
  public void case2() {
    String[] cars = { "ACBA" };
    assertEquals("ABCA", wordtrain.hookUp(cars));
  }

  @Test
  public void case3() {
    String[] cars = { "AUTOMATA", "COMPUTER", "ROBOT" };
    assertEquals("COMPUTER-ROBOT", wordtrain.hookUp(cars));
  }

  @Test
  public void case4() {
    String[] cars = { "AAA", "AAAA", "AAA", "AAA" };
    assertEquals("AAA-AAA-AAA-AAAA", wordtrain.hookUp(cars));
  }

  @Test
  public void case5() {
    String[] cars = { "ABA", "BBB", "COP", "COD", "BAD" };
    assertEquals("BBB-BAD", wordtrain.hookUp(cars));
  }

  @Test
  public void case6() {
    String[] cars = { "BABCB", "BAAAB" };
    assertEquals("BAAAB-BABCB", wordtrain.hookUp(cars));
  }

  @Test
  public void case7() {
    String[] cars = { "BABCD", "BZZZZZAAB" };
    assertEquals("BAAZZZZZB-BABCD", wordtrain.hookUp(cars));
  }

  @Test
  public void case8() {
    String[] cars = { "AAA", "BXDA", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CBC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC" };
    assertEquals("CBC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC-CCC", wordtrain.hookUp(cars));
  }

  @Test
  public void case9() {
    String[] cars = { "MPW", "RQV", "MXYZDMDM", "VVV", "MXA" };
    assertEquals("AXM-MDMDZYXM-MPW", wordtrain.hookUp(cars));
  }

  @Test
  public void case10() {
    String[] cars = { "MPW", "RQV", "MXYZDMDM", "VVV", "MXA", "VALVE", "WPM" };
    assertEquals("AXM-MDMDZYXM-MPW", wordtrain.hookUp(cars));
  }

  @Test
  public void case11() {
    String[] cars = { "MPW", "RQV", "MXYZDMDM", "VVV", "MXA", "VALVE", "WPM", "AUTOMATA", "APLOMB" };
    assertEquals("ATAMOTUA-AXM-MDMDZYXM-MPW", wordtrain.hookUp(cars));
  }

  @Test
  public void case12() {
    String[] cars = { "ABC", "CAB", "AAA", "ABB", "BBB", "BCA", "CCA", "CCC", "CBC", "AAB" };
    assertEquals("AAA-AAB-BBB-BAC-CBC-CCC", wordtrain.hookUp(cars));
  }

  @Test
  public void case13() {
    String[] cars = { "GOGGLE", "GUAGE", "FORGE", "FROG", "GRIEF", "GRAPH", "HIGH", "HUGE", "HUG" };
    assertEquals("EGROF-FEIRG-GRAPH-HGIH", wordtrain.hookUp(cars));
  }

  @Test
  public void case14() {
    String[] cars = { "ANNA", "BLOB", "BULB", "BLURB", "ANNA", "ROAR", "SOAR" };
    assertEquals("BLOB-BLUB-BLURB", wordtrain.hookUp(cars));
  }

  @Test
  public void case15() {
    String[] cars = { "POP", "PUP", "POO", "POOP", "PREEN", "PLANE", "PLAIN", "NOON", "POSSUM", "OPOSSUM" };
    assertEquals("MUSSOPO-OOP-POOP-POP-PUP", wordtrain.hookUp(cars));
  }

  @Test
  public void case16() {
    String[] cars = { "MYEZKFZA", "PHBZRST", "HKEHLBHF", "VCBZE", "PGJRF", "ZWDMUEWH", "LOPZBYHWQ", "JXZ", "KKNGVTZ", "IVFOFRAW", "HKAAMLH", "CXQC", "HZAOF", "DWNJYIM", "LMHX", "NQUZ", "RNLLEBSU", "QMNFVHACYW", "EDBUIEUZR", "MAYLEW", "OQTYO", "PHSXIWV", "GHZTAN", "NPEAEWJN", "MPBUMDJ", "SWW", "MSLPDM", "LZLYAXN", "YUZGH", "COMZNXGM", "AFACASVZ", "QDK", "OUJ", "SUP", "ASIH", "QVODXPMMC", "OOKQM", "GZY", "IGXM", "PDRYNNISTW", "QNDNBQJK", "YBVKZHJXM", "PLIRQW", "YUWPKFKYB", "UEVLKLHCO", "LTQJRUTKZF", "ABSUEYTL", "QYKAX", "KMLM", "QSFNOG" };
    assertEquals("CQXC-COMZNXGM-MDPLSM-MQKOO-OQTYO-OCHLKLVEU", wordtrain.hookUp(cars));
  }

  @Test
  public void case17() {
    String[] cars = { "GGBMKT", "KFKWVPDIQJ", "ZOKXB", "MZYGW", "ULOM", "XWRCCU", "CBEIDIUQX", "TGLHPH", "YHNCFIHRZ", "CZBIK", "LIB", "TAEVQ", "FNZ", "BJJKIFHBVN", "ZAYPGRQQMH", "MTGNXGTTI", "SFUEO", "NCTSWOYCBC", "XMEQTFBYG", "GIULS", "BLAF", "GOVJNXLLC", "HPPXCDKR", "SEUTCNS", "VTCWJ", "VOIM", "VLARWGW", "EAIHPBBV", "CWGOR", "AFXCHTQ", "PLN", "KZTQGE", "SDF", "LMXZLVJWDM", "WILZKTHWRU", "DXTL", "QUJGMAZY", "NWQUBOTZSU", "CMAKX", "ITY", "ECO", "ZXEQ", "WKC", "EWXT", "UAHGLGMQQ", "CWJVTLOZN", "IDN", "HYOH", "UQDGUXBCWY", "XEDZOXY" };
    assertEquals("BIL-LMXZLVJWDM-MOLU-UCCRWX-XEDZOXY-YHNCFIHRZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case18() {
    String[] cars = { "GMY", "KWNK", "IOSBDHRTXG", "XWQXQYITG", "KZZL", "IIC", "OWPLG", "QUB", "YMNE", "ADVPVOLCJ", "FBY", "SHOXGPA", "NBJREROXJY", "NGNLBUVL", "PHEAIRZV", "ZVPMHGLY", "OYG", "VDIJRUEKFE", "ZPSNFTELQ", "SHQQZ", "KEEMYMZSW", "AHWDDXB", "ALCFJ", "ONWW", "ZLA", "IAZ", "ULEER", "JLLYQO", "PAEGDWJP", "PYLM", "NLSVPQFW", "AMKDBUYH", "ESJNXXE", "DKRLLMZ", "LACY", "FRAFUTOMK", "QUXJWKDQ", "QUVDQZ", "YIAKUX", "BPLCRD", "GGKWOHBID", "CUTYJWHJVU", "KRALMVYC", "QHHUAX", "APJFOWCDHK", "CPOG", "BHEM", "SBIIFT", "EBYHUANOS", "HCAMSNPCBG" };
    assertEquals("AHWDDXB-BPLCRD-DIBHOWKGG-GTIYQXQWX-XUKAIY-YLGHMPVZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case19() {
    String[] cars = { "IOU", "FFAXUCHE", "NLDTHZZIJW", "LREFTJKPPU", "KOZV", "XJFRYFUW", "JJZN", "UGITNRW", "YHGG", "HNE", "LQOVSB", "RLJYDTGPST", "IPU", "MXRZJYCZRU", "KMQBVC", "KHEV", "ZXQAKKSRT", "ZGFJE", "RFWTWZF", "XOI", "OCSGLU", "AYLOOEC", "GYVWIZO", "ZUPQWSKBMY", "JTFKWWVVY", "ECWGYODF", "ZOFM", "MWOCFY", "WZQ", "RUTJQNLJ", "PBHIB", "XCY", "MIFHEVXUFC", "EKCVMBYLN", "CSF", "PTPROR", "ZTPRTKBZ", "GPWRIDTZVO", "GLJCXD", "YGFAN", "BCYFUZJCU", "SFWUVL", "EOAPJQ", "UCBZ", "WEWZGUMA", "JCMMSPZR", "XEOHRDJ", "MYWJH", "FXJX", "LHLNEH" };
    assertEquals("AYLOOEC-CFUXVEHFIM-MXRZJYCZRU-UGITNRW-WUFYRFJX-XCY-YMBKSWQPUZ-ZBKTRPTZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case20() {
    String[] cars = { "NVDEBO", "UBMZL", "ORHEO", "VKIKKSFG", "XKNWVGX", "QJSQTZKCJ", "WPIB", "QJKXU", "HHLXFCK", "IKL", "PFUU", "NHMOFO", "LXTRSSHIV", "HYTB", "JVJSIHKHLV", "HGAALEOQDZ", "UCYWFCM", "GYZLJ", "FYNXSBP", "VETRBOXPG", "VZS", "QJBTLSYB", "HTLOXJANOR", "AWNSN", "GJZDWWJXH", "ZRJDLY", "WRDZAIRP", "SZPJS", "QYTBXP", "QPRMRGQQ", "JIHDO", "HRFWV", "IZZLMX", "BOFBZBLOBR", "VWNHDZ", "BKNGXEWZBV", "KUIXX", "OKYNSQUKGK", "NPRILCAL", "DLZYXAYK", "JBLJV", "SBAEWZXO", "JNUNEVOT", "IUI", "LML", "TIYLNNKWCK", "BQCFXDWHBL", "MGVDPKJZ", "RZFJUZVNZL", "GKUASZ" };
    assertEquals("IUI-IKL-LML-LACLIRPN-NHMOFO-OEHRO-OXZWEABS-SJPZS-SZV-VWNHDZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case21() {
    String[] cars = { "YVPVPZ", "WYGZUT", "ENKOQARDD", "MVY", "UHC", "BGF", "QWZDTAAN", "WNBFUWVGTS", "QLJVAI", "BFBHQSQUM", "HSYAUTBLBH", "EALY", "HVWGVFHI", "SVTJH", "LYQHLBC", "UVR", "LEAJGVUCWW", "YKEPLDVI", "ISYJYIXB", "WNYWCXH", "QSAHE", "JXYKMAORL", "TVUBXJM", "KWH", "YDMOMBJFIM", "OSXLRZRGID", "YOCXMOX", "EVIYDCZLH", "AGQJZUIMNC", "GTFQNGBDG", "VJDLOL", "IMJ", "CNTZVBS", "UERSIJFU", "TWGLKNR", "TWQYCZ", "APT", "UUKS", "KEP", "NCTUL", "TJCS", "RINACPE", "DZJCKFJLES", "NMPSHC", "LGBINYOEJL", "DENMRP", "TYQN", "WUDWK", "CTXGGJVXA", "GGI" };
    assertEquals("DDRAQOKNE-EVIYDCZLH-HBLBTUAYSH-HVWGVFHI-IMJ-JXYKMAORL-LGBINYOEJL-LUTCN-NQYT-TUZGYW", wordtrain.hookUp(cars));
  }

  @Test
  public void case22() {
    String[] cars = { "GKINJG", "LFY", "PPSQITNM", "DWSWOUD", "WRFVTYBMQ", "IFKWIBXJQQ", "QJHOHGXYBD", "ZEIECYE", "SDOADMLNWW", "ASCFIZ", "FCDQUZI", "PQFPOWHR", "HYJPVWGCSS", "FZXAVD", "KCQHOSDPEX", "UYMU", "XSEUZCUNM", "RAQ", "RBKJQ", "HKPH", "OCXY", "RNDLGDJJ", "KLHRUFM", "HFEH", "GRPCUYW", "WHMLRC", "MUOWF", "TDHRTP", "EBKSRWI", "HQJLGRIVY", "IJQRXCOR", "DLGVLMY", "SUCKIOD", "QBIOGYMG", "FZHW", "SFTPJQZKC", "BHCVDFRN", "RHVRJ", "VLLHZAF", "QZYHTBE", "UCSRIZ", "FCCUSKGO", "PDF", "ENJXDSAVJZ", "UEFTXGZQVG", "REFTVG", "BIHUUMDU", "KWKTZRAAG", "ZAILBMYYMS", "CXFOBPFXC" };
    assertEquals("DUOWSWD-DVAXZF-FCDQUZI-IFKWIBXJQQ-QAR", wordtrain.hookUp(cars));
  }

  @Test
  public void case23() {
    String[] cars = { "LKPQL", "MOGOUMDPA", "YWBXOWNL", "EOWG", "FZSFKWRVX", "VXMMIHC", "AQMP", "KBUQTZWGTQ", "NOUR", "KHLVYKBNH", "SREGLGZ", "MHDFRYIMJC", "UPLQINQXYR", "KZNIFPGZ", "HKG", "JOPHQBNE", "EPUFTZ", "VHBJCRBCY", "DVBLVTIOS", "THBXHSHC", "JWGRWSYGF", "DUL", "XDHG", "OLRLAGI", "BDXPNAZBG", "JOHCTOZQB", "RADDKVPW", "ZQJVLYS", "FNNM", "ABEJ", "ADQOHI", "VHPDJGNIEM", "JJQMSGUMTW", "BJGOFUT", "SQSHAIZA", "JWLVO", "IEZAI", "NAMWVVKTMX", "XHJHYGMQK", "CACIA", "HDQBTME", "HHLKSYI", "BTOPJKXFU", "UQYXBWBMUB", "JLLJB", "GZBNSCMTL", "TSVHDZUYZ", "KYSYRKDQDG", "JBZOXFE", "MTRJS" };
    assertEquals("BDXPNAZBG-GKH-HHLKSYI-IAZEI-IGALRLO", wordtrain.hookUp(cars));
  }

  @Test
  public void case24() {
    String[] cars = { "VDYKGIUYWI", "MHKF", "BHH", "IXMB", "SXFWQAKB", "GTZ", "AMUV", "CUDZXHSKR", "OJLEHBD", "BCF", "OTJ", "SAFOVC", "WPDCVZCX", "ETGNZNTA", "FXSXN", "JVHRGGM", "AATAITR", "DOWVUBTQ", "KUHKG", "HVJIPCBODR", "MIIGKY", "BLXSVHYXF", "ACNNEH", "NNOY", "LMC", "KSGHZIX", "VHHFOKWN", "HHBO", "UJCFPA", "JLT", "OUU", "RSOGHOFKA", "BHFUPF", "RBKXWH", "FZUZS", "QMVNPDOXUV", "OALOQ", "VMJEQAVT", "SGGFMZPGNP", "ZSYADCPSQ", "FDW", "ZYUWGAGYRT", "HUDZUQMPTH", "IIKPIKLXA", "VDZBLZMRF", "BLJBLQSZBJ", "AEAPBC", "OETFSGSC", "CCQ", "LZQCLC" };
    assertEquals("ACNNEH-HTPMQUZDUH-HHBO-OALOQ-QMVNPDOXUV", wordtrain.hookUp(cars));
  }

  @Test
  public void case25() {
    String[] cars = { "RFQTOMYHU", "SUEO", "ADDOJBVEQZ", "LCA", "SHPXAHCN", "AHNJD", "RGS", "MSEWTWEBU", "JFPVXWLA", "EPBEBVJOD", "LKOTRNDQE", "YENEV", "LOVTQRH", "MTCUHD", "NMKHQA", "HYMUN", "LWHIV", "PVZRVE", "ORF", "HMWQ", "HRNS", "WQMBKNZABT", "SQG", "ULFAB", "ZAMLN", "SWND", "SGT", "FCA", "ISKKA", "KUYEC", "DYQ", "LIGOCMF", "CXW", "OKYBRG", "JHSXQ", "DLSNHBUE", "QPGXCRJDK", "USJAI", "FTILP", "BPTCTJZ", "WJAKFMMDR", "CGGUE", "FERIGE", "NBGRP", "ZTUARHKTGF", "UBRJJZOAJ", "HTUAJS", "PEDOMJRQ", "ESPFSW", "WNMY" };
    assertEquals("AHNJD-DLSNHBUE-EGIREF-FRO-OEUS-SGT-TBAZNKBMQW-WNMY", wordtrain.hookUp(cars));
  }

  @Test
  public void case26() {
    String[] cars = { "XOJ", "CEVSMJ", "SJVDTV", "ZBKGM", "NUZU", "LTZBKTJB", "TBLXYJH", "RIXF", "JRM", "TMRWCSF", "OKSDO", "SZQ", "KEVCMPL", "BYFEHKPNN", "TXCDNWORVN", "BJXWMETJIB", "PQNXZHZEU", "FZPPH", "RFKRLMFZH", "TDY", "UGNZNO", "YWQPDG", "OAHYBM", "OKDKKSDQ", "QAPHX", "VNWYLJAQA", "GXKCKKMYHM", "RWHVA", "AAFSWDAY", "BLN", "FPQQZKJDMX", "HYBDJAMAAW", "RBWKCPVI", "QRBUYDXX", "JWIAMJTZ", "GSWNPW", "ZBANOM", "HGAHERHWZ", "AQRNILERT", "XOI", "EMW", "KXGGEIUT", "YDGC", "PKNRENIOEH", "QBKMA", "ZRMWYLPM", "JLOUCTQQDN", "HHTSLLME", "EJKDUKH", "QYCH" };
    assertEquals("CEVSMJ-JRM-MBYHAO-ODSKO-OKDKKSDQ-QZS-SJVDTV", wordtrain.hookUp(cars));
  }

  @Test
  public void case27() {
    String[] cars = { "RVX", "AKDEVK", "JUQ", "VJNAISQOQ", "STPKEDNMFJ", "XCOSVOHW", "YKXAXQWHH", "QWSENBEDDD", "MHAJZI", "RJDEL", "HOUO", "LIMCBIF", "UWFNAJ", "FEKJHNN", "HKWWYMP", "GWOGLZCJ", "BTDVM", "OBHDVN", "RLNZUSLR", "ZWOSOAY", "EQDHQKXN", "FVXLLENDF", "IKXED", "HRTLOIVXP", "TDHGQNMGV", "QZRZXES", "MGEDCPNSH", "NYTRGFSGY", "PCYQL", "JFDDJGBU", "HCO", "KBY", "VTMICUKHM", "FHXMYC", "GJKOX", "ICHGYTR", "YVJTGQAHHR", "REAOKEYTWK", "GLUGFVRX", "JBMXMWA", "YEDE", "YAOI", "TBQCIXJ", "GMNR", "TSIBIHGHYQ", "UPDUWYB", "OALPTY", "BPOPASTLFM", "KFZRYEPQQ", "OPGAAE" };
    assertEquals("CYMXHF-FDNELLXVF-FIBCMIL-LEDJR-RLNZUSLR-RHHAQGTJVY-YAOSOWZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case28() {
    String[] cars = { "ZJCFH", "WRLHGEUVN", "QCYRI", "OWWCZ", "TZDGZJU", "FQWMJUL", "HVLYV", "YFNLQ", "ZJR", "JRGUKY", "MOXROB", "HRFLXWJLY", "SCGKJ", "UREUZQ", "KUXAOJK", "JMLA", "JXDYPZUCIH", "VHJ", "XABCJB", "TPKW", "FTNKFJUYPK", "UOSHE", "NFTT", "HQKNUWZLZM", "JPJWQX", "FFYMKYZDN", "ZDCHJJ", "DGP", "OQEPQKKEGO", "MZGZV", "FJLU", "IOPDN", "VRQ", "DXYGRMD", "OMEHIUHPS", "KZY", "NQMYOCTLVH", "NPPVMPZQ", "BCJZGAUTVO", "WKHBGTCGHQ", "HRUQ", "QVW", "ORRPHYND", "NJECXFNW", "DWXPOJ", "XYLZQRKITU", "RVHNJXQKR", "GEGUVJ", "KBJHDSVSP", "MTUVGSKMY" };
    assertEquals("DMRGYXD-DNYHPRRO-OGEKKQPEQO-OMEHIUHPS", wordtrain.hookUp(cars));
  }

  @Test
  public void case29() {
    String[] cars = { "WKDQBS", "IVZBH", "YNMDOPGQRZ", "LUFTL", "FROPQNTOH", "KQFJ", "LBTGIKEE", "GQGIRD", "MBZQH", "NCXLEEKQS", "NTA", "HMF", "CXAENKR", "GJJVWDECLS", "FGL", "PHTGMSBQFR", "HUE", "MLUP", "CUIXSMBY", "PAPRM", "WGLSEDQJJ", "GZXQRZ", "CNUUI", "ZEOVCPDF", "AIDIGXPC", "QXJL", "ANTO", "ZQR", "CAMSWHTBL", "FXRWEASCR", "QOBXUGC", "FCQ", "CWTFOH", "USFWHQJF", "JQFM", "TDM", "YXOHBVUF", "TDRUFXS", "RBO", "UJWQ", "RROG", "XNUEHWW", "FVTKITTS", "XHEKBZGRDS", "TSSDMJDGT", "SKVVAFIDJD", "EXFBBPGITQ", "MVKH", "QBJOEUYUN", "EVXKAAY" };
    assertEquals("AIDIGXPC-CWTFOH-HKVM-MLUP-PHTGMSBQFR-RQZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case30() {
    String[] cars = { "KFYKJCB", "EYC", "XQQQSTHWZE", "RLHBHIW", "VYZOGPYV", "WWDQ", "RZRDSSDN", "OBAURTU", "JLLBVBABXE", "GGVE", "VUQOERSL", "CTRYI", "KSINSUBFOM", "WUQNBTANI", "AZRGNCMC", "VFEAHGX", "MRK", "YOZZPCASZ", "QOTDLTK", "BNILMJXDSE", "EEERWUF", "ZELQAGJ", "SACHS", "KTKFPJFY", "UUJQL", "GSIENHV", "BJT", "DSVJVXY", "OWI", "AIUXAID", "ZSRC", "SKG", "XMYVD", "XWAXCDE", "IJQ", "AXAI", "TSICVOPFG", "JTUDJ", "OLKCGKO", "BYRWOEIMU", "DIULBIKQV", "OIRL", "TQAVKNKFR", "DXPGWB", "UWLIUAT", "WUYJ", "BXIX", "KVCOMP", "HSRIVKZH", "GVPYFTELOX" };
    assertEquals("AZRGNCMC-CYE-EVGG-GSIENHV-VYPGOZYV-VFEAHGX", wordtrain.hookUp(cars));
  }

  @Test
  public void case31() {
    String[] cars = { "IDWPW", "HEVMSF", "LNJ", "YCECTRCM", "VLS", "CKANY", "CXBOQAHFM", "XTTRU", "BELUVJGBZF", "VGILKRHP", "JNEDKIPQN", "JEWJJ", "NRX", "NXC", "DDYKP", "ZBKBOKZ", "CTWGOMVDS", "NBTOD", "KOPWMUAH", "MIXNUFJUAP", "VJJZRV", "CDG", "ZDWX", "GUSQCSIKSI", "FYYII", "XVUAKO", "IEBCIAGXTS", "UFIDCZ", "EHXL", "OCDVGZSSV", "SGFHE", "EJP", "FQK", "SLKGBDLD", "RKLJKK", "AOOU", "QIXS", "TVTTNM", "FRVMXJIM", "UPZVL", "BEQYU", "TSL", "JNAFQ", "YOLAGWX", "NRUCJM", "DCBVYGYQSV", "AZT", "GTPTKWZEIP", "UETO", "PAVWPK" };
    assertEquals("BELUVJGBZF-FRVMXJIM-MJCURN-NRX-XWDZ-ZBKBOKZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case32() {
    String[] cars = { "VPFUKZAOL", "IXRMHARS", "BTHMTJLJHF", "NUIWOY", "BSANOS", "RTFJEWV", "DHY", "PVVZNETN", "OUBGUB", "DPDBDBWAI", "UXCPDHHL", "UPMLEWJP", "IZTFSQJINS", "WBNU", "XCTOGOJKS", "OWPQRCJGW", "QMUKSDVTJ", "LYE", "ZCE", "QWUPWXI", "VUV", "UTGWVGOSO", "COKTW", "LNAVQLP", "FRFRUPQYBN", "YEZDNCGPDY", "WUMNG", "XZSATP", "GGBFSKPJ", "EIQQU", "PLUO", "UQDZS", "XIGNDSUQOX", "QQNEQ", "RXGSQA", "WVFBZRJIEO", "CLFWEMIPIA", "ISJ", "ROR", "PSWTMUJWI", "KLVEYC", "UYEWTN", "OLZLSRPGUF", "KLWR", "MEMPRFOY", "CLUYC", "VLYDSQGERT", "EPNTCLWXTM", "DPF", "GDYURRZTBB" };
    assertEquals("AIPIMEWFLC-CLUYC-CYEVLK-KLWR-ROR-RTFJEWV-VUV", wordtrain.hookUp(cars));
  }

  @Test
  public void case33() {
    String[] cars = { "ZTZUCOUVMP", "TFGNX", "VNLLITYJ", "FGFUZRHGYZ", "RITTT", "MKTLTM", "TIMQXTNAG", "SKDWDSXA", "DGSFNYGB", "ANSC", "CSEOX", "MHHN", "YIHEGDWB", "HWMUNDAD", "UEFFNUZ", "TAXPTGTCF", "NUDGNNY", "DLXNLUMW", "XORPBUYHK", "APFHGVZHS", "ZYHGNSR", "XUISCZTHYQ", "DTXXOB", "NUS", "VMYUAIBJQ", "TFZAECTF", "OTNSVQV", "SFXRW", "LJKYQWY", "IQOFCN", "UVYDAAO", "QVZQWA", "IMAHCPE", "SMXI", "XMFKEW", "JYIHSFA", "BZTHKXW", "ORSI", "BKGHFEBW", "PGIJPA", "FHTVAHEJS", "VAZI", "ZGF", "XTIKFGHSN", "SDY", "LLUZIWIMO", "QTQD", "ANIJEZ", "GMVUKWBJC", "EIUAGT" };
    assertEquals("EPCHAMI-IQOFCN-NUS-SFXRW-WEKFMX", wordtrain.hookUp(cars));
  }

  @Test
  public void case34() {
    String[] cars = { "ZIOP", "FOAEZEAZ", "MYLF", "TIYBKCBQAR", "YDGYJR", "EFQBRBZAZA", "CQOCJBFBR", "JWMEHQX", "AON", "AKHWD", "TDYNONI", "VMLCDGG", "IPPYAJYPKB", "XKBNXJJCZR", "TGMIXJYFX", "PKA", "PSMDLPAY", "ZQOIMBVLL", "ALCFFMD", "WRGKR", "XUIHM", "FZK", "TVOVSRXPH", "CDBSXSHB", "TLHJ", "PIT", "XBKUD", "HPN", "QVHZEJAJP", "ZJFVNFWPWE", "EZTIOYLRF", "YKCMCK", "HGBLSREOM", "JGYXTUCB", "RMTFP", "YLZACKR", "HRQOMVSLJT", "XZBCL", "UCTV", "LTXHC", "ALSKEGNHPD", "LRC", "QQJV", "VKRHRN", "OBQSSYAE", "ZOO", "BEJOMIOY", "FIJKMP", "TGOJEWZ", "VOHZXHGR" };
    assertEquals("AZAZBRBQFE-EZTIOYLRF-FIJKMP-PFTMR-RAQBCKBYIT-TGMIXJYFX", wordtrain.hookUp(cars));
  }

  @Test
  public void case35() {
    String[] cars = { "UJLHYIDFC", "HDYNPQS", "MDBSQRZIQV", "TDBR", "FPMBP", "ARGPEE", "OQQDNLSCI", "HNWMV", "DBMBY", "BJQVA", "REJPLU", "PIIMSXQBXS", "PORZCEKJRQ", "SIEUKPZ", "DPEZK", "DNDU", "VBLZPNBNM", "JMO", "DQEK", "KKK", "ROIGDGHEI", "NCI", "NFR", "PQC", "IERRWU", "DEZTBIUAKH", "FUGBQWE", "KFLOO", "BFCGY", "TLTM", "WSTY", "ZFXU", "DNTANTNN", "DJZFVKM", "BPREPN", "SFA", "KNCNMAGTX", "FVBN", "LUW", "QSQBFAYKG", "GCPE", "WVKNWSDE", "QAJKQ", "QLXXLZPV", "BXHH", "BPMHYWXF", "PDDTSMYKK", "KXC", "YRHUADBEI", "TVGWPRJCTU" };
    assertEquals("ARGPEE-EWQBGUF-FVBN-NFR-RBDT-TVGWPRJCTU-UXFZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case36() {
    String[] cars = { "ZQQNV", "CMSFE", "UKRLHARJ", "MCBAUJDWNR", "JRZPBFPFD", "UGHOTRG", "SCQACLVM", "FVHOONE", "JLXMCTQRTR", "WYNYQ", "PKASPFB", "LLXT", "EXFOMK", "EPM", "HZVBY", "XFKSNANPP", "WTTJARYRJ", "JNF", "HCSGFXL", "YZZ", "QPYPQZ", "RMKJ", "VUACS", "PUFLLHZET", "KVVLW", "EGG", "FZDQ", "VQIZED", "TKOSXJGKK", "AYOBQMEBLR", "QPW", "RZRUXZ", "SVAPGK", "EQHE", "ERCGBAJXR", "TQFVUGJ", "LBEA", "QMZIVNU", "NIW", "DJY", "KPUKT", "JYML", "HUCK", "VLOR", "KCPYGPUHZ", "NNFI", "GEE", "FLKMVA", "ZLT", "YPK" };
    assertEquals("CMSFE-EHQE-ENOOHVF-FNJ-JKMR-ROLV-VNQQZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case37() {
    String[] cars = { "HFAU", "FYLOYCZQHS", "VBUXNFXA", "HPR", "WATIX", "BMDIZVZPLL", "RFZVGOXFKU", "MLK", "GICC", "TIOYCP", "BJTEWXET", "ZXNTNT", "AXHQVDI", "YQJTEZTVZE", "MZMCSAXIMA", "RYQKSK", "CJFK", "QIURC", "LIIBQKUOX", "PPRTQHCGX", "QJE", "ZKPGLBJ", "DJXQQVZ", "UGC", "IQNZMWMZB", "ZOPTL", "HWZCENHGM", "ILLJ", "IDGQYPS", "JOITR", "RZCPJJJAP", "CSWS", "UIGQNQWY", "WQBWZC", "DGVHTBZ", "UDSL", "WANYRAWH", "EHHA", "AVXZMWGQO", "IELI", "JCHKFSMW", "XZFNMQGO", "NZNNMUIQKC", "PACGFA", "TAAW", "BDDLVUMCX", "INADMGU", "CCF", "YADTCN", "UPPEGIG" };
    assertEquals("AXHQVDI-IELI-ILLJ-JOITR-RFZVGOXFKU-UIGQNQWY", wordtrain.hookUp(cars));
  }

  @Test
  public void case38() {
    String[] cars = { "XEXZ", "IYOV", "EKFRH", "ZYZDLIFYQ", "XWNS", "DDB", "YYIVXP", "TZBEY", "XCGQX", "KZHTWD", "SJCNATWIK", "OON", "EZCX", "AKBVVREB", "VWOYV", "EEZDKGHRC", "FEUXRNAKX", "YJM", "ALTZLOVOJ", "EILY", "ELVSS", "JBFNBNQ", "VHUUYXTFKT", "BRWJJ", "XXTA", "VZETKXXYVK", "AOTMCIR", "GJGUFVXQTX", "NSJMTGKK", "UIHJFFIOH", "STMWYHAAYQ", "MVSTYDP", "JWFFTUOVJJ", "PBXOMJ", "URLFM", "NOQV", "HWJGLEEA", "OZOLEYHO", "HTMC", "RZKYO", "EOX", "SKMID", "NBCDTHCAA", "JEYTMQQVIU", "PGM", "VMTGHJHW", "JSDWXLKI", "BZSGRIQR", "BZGYWMP", "ZST" };
    assertEquals("AKBVVREB-BRWJJ-JJVOUTFFWJ-JBFNBNQ-QYAAHYWMTS-SNWX-XCGQX-XEXZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case39() {
    String[] cars = { "NWJPAUYG", "VTSKNENCU", "XWFTSBT", "CNISWERUBU", "JEAEZHYO", "MHUTNMABSE", "RTWVEAL", "BBQMGE", "DSLWCX", "RTGQYA", "DYXG", "RCL", "IFRLQMC", "NVREBT", "USAEYOZ", "HHEAGNPO", "SUAQUIA", "REWUATWRK", "RKOLLIMR", "JJSMEJQ", "UXKWQREIW", "EGBWPE", "BWY", "PIMRP", "ZRO", "ZKPJA", "OHSNSUTYM", "CBYB", "KVYIK", "FHDTOEFDPU", "VDA", "LGNWZY", "JRQSPRSLRX", "ORTQ", "NFWRGEFQWW", "XVPQ", "CWFE", "XDQ", "JBZZQMYD", "WMAFVXJW", "XAJB", "XEMTVDUZGE", "JTLNBGMHB", "AYGIOIVGVX", "WSB", "XXDVX", "DIVR", "ALAIM", "NLV", "ZWGCRLJKB" };
    assertEquals("BYBC-CWFE-EGBWPE-ESBAMNTUHM-MYTUSNSHO-ORTQ-QDX-XVDXX", wordtrain.hookUp(cars));
  }

  @Test
  public void case40() {
    String[] cars = { "KDXT", "BMLCVC", "JKRBMYW", "VNUV", "GHATAJALX", "ZFIGAAIEY", "KOS", "BVMKPTFRY", "FECDQX", "PWTVEC", "HDQ", "GQJDZUGSHZ", "FSNHC", "RFSHYTC", "UXRK", "BJGQ", "LTVXF", "GSVJZ", "SWQNAPVUH", "AXMOGRW", "ZFMPJK", "BWPRSP", "PZETES", "GQVZYUKKD", "ARMYBV", "UPMPFS", "RTFIVQQIA", "GPEYRJTTXR", "XFHKXQ", "TLD", "RIP", "XHXYPWXSE", "JRUMJVZCWY", "VRA", "ONZSDX", "RBKCAKAV", "RURSY", "UTZQWFH", "DTM", "DKRY", "FWFFDWM", "WEPWQ", "VLNRFL", "VQEVG", "UWYXSXDZLD", "OFUUGAZP", "NZRIJED", "CRYKSUFMJG", "AADICZQG", "SZRL" };
    assertEquals("BMLCVC-CEVTWP-PIR-RBKCAKAV-VNUV", wordtrain.hookUp(cars));
  }

  @Test
  public void case41() {
    String[] cars = { "XWZDAYNOI", "XIGOI", "EAEQAJBI", "XIMFCY", "LTGVQTYNI", "PVMJEQF", "QRR", "GVDLN", "DEI", "JLPSDWRAP", "QBGII", "AQWLJKHB", "LRHLKM", "JTRES", "TDBRCFJY", "PWSCKXJB", "GTJZ", "OPGFSJLBL", "FYIVANYQ", "RCO", "RHBIN", "FTP", "JNUXMFVRVA", "ZAQZRUXGR", "HQKUC", "YFJEOBX", "MIRS", "TFCTLFUC", "FFSLD", "IKVRSLTWEW", "HIRHJ", "ZGATYVDTA", "QRCSUSKV", "KFDE", "AAPZLOWNO", "WFMQVPW", "HUJY", "PNKVH", "DBVEJCRZ", "UGQ", "EFRYI", "FKJTW", "YDJHE", "TNCCF", "PXCVY", "TPKBTVBF", "AMDJAPNF", "EUMV", "YDVACTH", "NKRLFPFHZ" };
    assertEquals("DEI-INYTQVGTL-LBLJSFGPO-OCR-RGXURZQAZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case42() {
    String[] cars = { "SOPMBAX", "NLIOEBV", "AFQ", "ZLDYZJBX", "KAYLRPIT", "GWJFHASYR", "EWXLLQZ", "DWPZ", "FCAANZNZGV", "CQWRYSN", "KLSY", "KQPCM", "OCQS", "CBQPJSUTE", "CTAHNMU", "ZPZ", "KNRRSWKQH", "WNXLQDVDSX", "YIMQPFUNBU", "UGL", "HDRDNIHPQP", "QTRWWUGDR", "QTAM", "VZTHXNW", "UBHE", "DVXYQVQTJK", "NDQRPVIQM", "HFBAZHZ", "UQTXD", "XSMIXOSUV", "ABOTMU", "IXRAD", "MAVUAGF", "KUIOISLHG", "FFDVDMPI", "FASG", "AJGXHYZINX", "RPJWKJGL", "BWPTP", "ZROYKABNWK", "SYCWSMY", "ZMYF", "IXRBJA", "WOA", "NFPLCHWDB", "XTFGCXR", "UYNXTCRNTI", "RFZLKLIT", "ZBXJXSTMP", "URTJOX" };
    assertEquals("FASG-GHLSIOIUK-KQPCM-MQIVPRQDN-NLIOEBV-VZTHXNW-WNXLQDVDSX-XBJZYDLZ-ZPZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case43() {
    String[] cars = { "MXBI", "NZZZ", "OMLZBAZRCA", "BYHDZQTWM", "JVHDLAZV", "JTOG", "CZQBSR", "HHHMUPADVZ", "QLHRXPD", "CVBJRBJWXU", "LWZWSCDKG", "LXE", "KCOC", "SIKGA", "KJUFLXJMH", "VCBYMYLOG", "REPCIYLMBX", "HIKNZPGZIV", "IKECOXG", "DLMZLZDP", "ZTKPJTYSUK", "FDBTSGJBYW", "BGAMRMK", "TCIFDPVM", "DFIYB", "NJJRBB", "GWEQMGBNXI", "ZII", "QGZYBZK", "ILRCBVTDZ", "PDJ", "WLUMXPNBNO", "WWUAXU", "JXW", "UOBHHIX", "QRMVM", "APS", "FKJQ", "LPWP", "UOFDQOKTFP", "UHXSAL", "FVOCCQFU", "XFVOS", "MHOT", "BNUXMB", "TSB", "JZCPK", "BEAGGS", "DHZKFXFG", "OPD" };
    assertEquals("BMXUNB-BYIFD-DHZKFXFG-GKDCSWZWL-LPWP-PFTKOQDFOU-UOBHHIX", wordtrain.hookUp(cars));
  }

  @Test
  public void case44() {
    String[] cars = { "VUYQWKM", "XZPR", "RIOSBOWJ", "MKACFLVBRX", "NCLQMG", "FGCSTUXTSD", "UWE", "AWIFLB", "EJBA", "HGL", "DIMX", "EOBLKIDQHE", "NNZT", "CKP", "BZRJHCVLPX", "FYFLUA", "SESK", "SLRV", "PZEI", "CMQSQSWTJ", "OMSZVDBRT", "HEA", "UCZ", "TDKEBKANMC", "UUQJD", "TMN", "OHLOME", "UAIW", "QXXOET", "BSSMTZN", "VKTVN", "BNDB", "FMPDY", "JVQAVMUDEX", "QDOOHYEXMP", "YTXAKO", "VGXHZ", "PTMSMMB", "AIBLAZ", "PUFW", "YIZGR", "OWYMVIMBL", "LSK", "HHKVD", "ENYPLGDT", "DODK", "AEHKXMY", "GOIGYPX", "XII", "TZGKXRS" };
    assertEquals("AWIFLB-BDNB-BMMSMTP-PMXEYHOODQ-QXXOET", wordtrain.hookUp(cars));
  }

  @Test
  public void case45() {
    String[] cars = { "ZSO", "ZTIRYBQVJ", "BIVKXQHK", "IDDU", "DGEEDCXUG", "ALSVPEJZTL", "OFNYHRG", "YPQ", "FWGFE", "QTJUWNMYI", "WMDXCU", "JGTOTJ", "EMGOZJFHPN", "GUYPJ", "BECKUYIMB", "AMYWCBDLA", "XIACSPOUG", "UNNZPV", "TRSRMPK", "BZUQZXCHTH", "SCFHPL", "AHO", "LAMD", "NMTZ", "EHYDSG", "VJNZYRWTQU", "FMTY", "XTGK", "UFFYM", "QYH", "UNR", "ODEPQQALH", "AIJI", "SWSQXE", "IEGU", "GGRSQPMAK", "BYNHHPSDZR", "MOVKGYWY", "PRAIC", "VFAZU", "PFNBBCYVUU", "PANUMKUI", "GMSU", "KQIWVBCYET", "IRGBYLFM", "BTQY", "NNGIIR", "WLPZTRGIQ", "DHRJNG", "AEVB" };
    assertEquals("ALDBCWYMA-AEVB-BECKUYIMB-BYNHHPSDZR-RNU-UCXDMW", wordtrain.hookUp(cars));
  }

  @Test
  public void case46() {
    String[] cars = { "SSZNZGC", "JCSCZFVLKW", "EUXKIRWHVT", "KBTJL", "PQKKSMZWT", "OYUBGZIG", "VWDPMKRFS", "PULBGAVV", "CUIZBIMP", "XOPJ", "IJOGEKCOQH", "TCJ", "EMFTVUOG", "QJYIV", "FAVWVIVFRO", "VYGP", "DXG", "DJJAPYPQ", "WTS", "BUXXXIXP", "SRB", "EMNMLAKA", "DRJSS", "QEDJR", "OBRIPRSX", "CQGSLKT", "ECCIO", "QMOBCMPPUQ", "CPJPTT", "QWQ", "YJPVRNU", "ADRKDBDJB", "LVWVEA", "QCUS", "DCDRD", "PBZTHY", "MKVEOJI", "LNZKUYZC", "UYDNJADWFZ", "TVDAEMRCE", "XLUDYVMG", "BNNWTGGSL", "BXZSYWD", "HZLNE", "GATWKXA", "EUSZUMLFF", "AUADULUQ", "NWHYZCXJFM", "PTS", "AIY" };
    assertEquals("ADRKDBDJB-BXZSYWD-DCDRD-DJJAPYPQ-QMOBCMPPUQ-QWQ-QCUS-SFRKMPDWV", wordtrain.hookUp(cars));
  }

  @Test
  public void case47() {
    String[] cars = { "GPWFHN", "PEOTADJL", "PZU", "ADA", "WJKDELOK", "QVCGSFLMFB", "CFZSV", "DZPYRVDX", "RGPP", "XUVYUOY", "KUKM", "AHUOUJJXDD", "OAWKPOXN", "FFRHJLPX", "MQGHIXP", "WKDNC", "EWISG", "RIZDMYVGC", "NFFMWHDI", "RTATAVE", "TPLMVEDNL", "TMSZPLDY", "OMWZZDYEKW", "QPPQGYEY", "AZF", "KKKPBJSUG", "PAMCHKHB", "MMTMSNAAD", "RIIMNZAROS", "UOZYNHIJZ", "BXI", "WVXS", "CUE", "NCLMOHEK", "AUGNBUF", "FCICXQGCHF", "VSZIIFATGG", "ZBXBI", "WRXR", "VRNTFKUGZD", "QAQHKCG", "CDQLRAT", "CTKBGSUWHM", "HTFAVILWE", "IZRYTXNH", "WOTVIDCM", "SLEAS", "AEEGOZV", "YGEEWAIMX", "SPBEBBOSN" };
    assertEquals("CUE-EWISG-GUSJBPKKK-KUKM-MQGHIXP-PPGR-RIIMNZAROS-SAELS-SXVW", wordtrain.hookUp(cars));
  }

  @Test
  public void case48() {
    String[] cars = { "TMXQAJ", "AOZGEPA", "EMQIPYEN", "LLRJQ", "DWZIUT", "TAPE", "FRKTZHNMLJ", "QFL", "VCCFLXJS", "XTOMST", "LKSLBDNQ", "NXIDF", "YTX", "OMFC", "VIPSBHEQG", "AULJAR", "KNGGWJDM", "URBI", "NDXCH", "DQXJC", "EUWSUOGUS", "NNGBFWM", "WPGDWT", "VVPMFTC", "ESFVUJVW", "HNW", "GWOL", "PSB", "ACRRE", "YVPUC", "TGCHC", "RQKZLOIUMW", "IPQYHKSDC", "AEPDAY", "OGJPDQ", "DGRJ", "ZFJGFNK", "JAQD", "BAR", "EBYLJLUOG", "FXGZMAY", "UGI", "NOSVT", "SURYGKUX", "EVJIRTRVC", "FANWBQKO", "FKH", "MUKLUJE", "ULDQUUKH", "FKGI" };
    assertEquals("AOZGEPA-ACRRE-EJULKUM-MWFBGNN-NOSVT-TSMOTX-XTY", wordtrain.hookUp(cars));
  }

  @Test
  public void case49() {
    String[] cars = { "SYHLI", "CPRIXHUT", "ABRTZRE", "LRTWFHPH", "UBWNK", "KHD", "TJMV", "RGN", "YLYLMWF", "QLMWZUMRXE", "GYU", "GYMI", "NYUAPL", "BRBHDODBS", "WBHIXA", "CSMSSS", "LCZ", "XNDPOQANF", "DOSEKPY", "OOPFN", "RTLP", "WOTU", "ROTJ", "OABDFFXMC", "APWZLGAT", "YQZLNVP", "DOJAHSOYM", "ABMLTYWKFH", "JOZSF", "BSUCHYBJQ", "DNDP", "BTVGSI", "EEDHLC", "LCTTI", "ZNY", "VNWENKEDFT", "XWUGFMDFQV", "VMSTN", "YEGW", "NSLC", "MPU", "KZBCOYUX", "SXPHID", "SDLVJ", "DVJPOV", "LXTRCNP", "ACRWKEUE", "XHR", "QFLGZ", "ZOJLYUSDB" };
    assertEquals("ABMLTYWKFH-HPHFWTRL-LPAUYN-NGR-RHX", wordtrain.hookUp(cars));
  }

  @Test
  public void case50() {
    String[] cars = { "GDDFRSAK", "QFA", "RGXHYIAM", "XWAEQ", "EOWLWTHI", "GZSCVOA", "AGFWXJJVCM", "BMF", "CTORI", "MITGYXG", "JMTA", "HRQBYJQXH", "VOTPQNFXF", "ZMBB", "PYXSAPODS", "LQWIXMAY", "ACYEWRZBUV", "CMVNFQKV", "JIVZPD", "JAPATGY", "AEJSGIN", "YQFOFK", "GJEZ", "BUOPRYI", "FPE", "ZHCX", "IZTTZN", "BUYYNOYVYU", "LSBOFFIDB", "DAHDOMGTB", "IKSZYPXR", "NKNOOJ", "HRDM", "ZGQV", "TNDKO", "VTKTG", "EDYO", "UKRSCV", "PWBKLEQK", "XRGZTGCW", "QPAESDLR", "AVO", "NFK", "SKIAPHEEL", "LVAAUSU", "LDEFA", "TIMD", "BWVTZOSB", "GZGTXV", "BKWN" };
    assertEquals("BSOZTVWB-BDIFFOBSL-LVAAUSU-UKRSCV-VQGZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case51() {
    String[] cars = { "XKZNIRF", "MIQEVWXB", "VFAYFPV", "XEM", "FWLEDA", "MSFXV", "FVB", "FGIQMTSCWD", "ECFJ", "FHYTO", "FVHVQPJXVZ", "XSI", "PWGUPLTFVA", "RHJ", "WTSKPHXZA", "ZHQ", "GBYI", "DTRZGUK", "WWZT", "STL", "JNJAULWU", "HIILGBJ", "MKGB", "XPJTANY", "IVSFVAVZ", "JEXGMZ", "JZI", "YQBHDC", "YMYJUII", "NHQPER", "ACCS", "LEXCJSJB", "KPVGOPAZE", "YNOWGZWSOQ", "THSLHRGYC", "LRVTLPP", "JFZZCABOLS", "BLWQ", "MXJU", "PRPU", "BCPLTJGJFW", "MCUSIEI", "ICCL", "CNLHFQN", "ANVZ", "DNPVO", "MEMZHAH", "BLZJYSOWAI", "UFFBOLEB", "NVQJB" };
    assertEquals("BLZJYSOWAI-ICCL-LRVTLPP-PRPU", wordtrain.hookUp(cars));
  }

  @Test
  public void case52() {
    String[] cars = { "XXQJUGPOKJ", "VLCYES", "QESJOSQ", "UDOMRK", "QCPCXJOQ", "ZBXU", "RKGBMWCIQA", "INILWFDT", "GMEEVK", "IEZAEXNPND", "YESWBKJF", "SIE", "JCN", "EQMA", "RJCIZ", "DLEYOW", "MBVGY", "BIGQDBYWQQ", "HWDGSOPE", "KBG", "QOEMMQ", "QZSOTU", "AUNKP", "SWGSHOT", "ZDR", "IZQBQACCUW", "RXNHGFD", "IEHVHDZX", "LTBMA", "EFU", "VASLXBUH", "VIQVCPH", "YIMDHJDKII", "MHBYLJUC", "FWJ", "JACRF", "APWUMASWXF", "GIZNYMVL", "ILPKKEUZ", "WCVVDTLZY", "RVDRGBAZM", "FKZMAZ", "TEIUQJHAR", "NXFIOZJKVG", "WWEAZHH", "OWXOF", "IYV", "XEQMZBC", "VKM", "KOTBBTQJDF" };
    assertEquals("BIGQDBYWQQ-QCPCXJOQ-QESJOSQ-QMMEOQ-QZSOTU-UXBZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case53() {
    String[] cars = { "WAQ", "WZWSUJCV", "TQXNFMWBOB", "XZGZ", "VWMH", "FFIQJICX", "VHQS", "HOPLEJ", "DFNYLQOK", "EDRU", "WFCVKB", "BVMXE", "BTOZTJ", "HHPP", "AQIN", "AXJXJMDNAN", "BBUWJYDBOS", "MWOT", "MHQYTCCU", "XDPRFH", "MKMEFKJCC", "WKSKSGHA", "KGQZDK", "VNT", "RIU", "PFMOZU", "GYUOAWINYZ", "PEQ", "VSZOJ", "YWUJGW", "DNYROVHLO", "IGYF", "CZDW", "WLHPQGCWPX", "BZDHQ", "TIVMKYGQ", "WZLZT", "PFP", "YTXVSWO", "KUPMWNIPY", "YDUGS", "MQAZAM", "UQCUUJLZFN", "IZH", "QBFNICJR", "MPOJB", "UPRALJMP", "WGPTW", "LZJHAQ", "BQYT" };
    assertEquals("HHPP-PFP-PEQ-QGYKMVIT-TNV-VCJUSWZW-WGPTW-WLHPQGCWPX-XZGZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case54() {
    String[] cars = { "BXUQDXQ", "FUAOW", "EAWCBI", "WMDLV", "FORTLA", "JIGTIOLKZ", "EASXWTJEX", "GPZCTF", "CRR", "NWIYGTZOPP", "FEDGLAYTW", "WGUV", "NVHDEYCV", "TQUERPLWJF", "DQYA", "MKZQEK", "OVVYXTSBW", "ZYPDLZKSW", "RMZ", "PRX", "VCLPC", "PFKLN", "QDJMART", "EDLSRNJQ", "YGZRU", "ECJIF", "OLL", "UWZZGDWD", "DOHRUIFKPD", "DDKGAGBYYN", "SSFGMK", "HDSFVL", "NNTY", "MDDNXQJY", "TSNXVEX", "YDQXDMP", "UBYGZIRQUI", "FFU", "RPLXZ", "WKGXZAAK", "SBURH", "YUK", "NBF", "LKNHOHKK", "HHNZCL", "SDLXFEZH", "GSKAPVCIL", "VKCUBMY", "CUJUM", "AFSZ" };
    assertEquals("ALTROF-FTCZPG-GSKAPVCIL-LLO-OVVYXTSBW-WSKZLDPYZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case55() {
    String[] cars = { "YSWU", "DTIAHVDK", "BKH", "MDMMKA", "KMRG", "SAMDBSFVX", "YNXUHUFY", "CRKIPMEGXD", "SXITUGRTND", "WXCERWIGRZ", "GUXWWPMWLE", "FTFYZX", "VKVAUYMSX", "DBXZ", "QPBMF", "RNIUUCQOU", "XLBVJHR", "EIGE", "HDWS", "HUBLVXQUN", "HFJBMOX", "NDHQ", "STRZQYGDCU", "HNAMOGLQBV", "VQNW", "GOQUIBHMZE", "PNQXNM", "QODN", "ICYNNJXYC", "QWJYXNVS", "HFDWVBAZRV", "OIN", "NUCGLCSPC", "VXN", "JQYJSGIB", "BDYOES", "EBISIYPQ", "YVM", "GCAOO", "VAEDRWC", "DQXNIZMZ", "SAPUTUOP", "LBPMCQKA", "RPXYTT", "NIGWV", "EHYSJDW", "QDKFVLE", "YEASCQBZB", "VOP", "MDJGGGNPS" };
    assertEquals("BKH-HUBLVXQUN-NDHQ-QWJYXNVS-STRZQYGDCU-UWSY-YFUHUXNY", wordtrain.hookUp(cars));
  }

  @Test
  public void case56() {
    String[] cars = { "NDCA", "NBBCOMC", "JTKZSGXWH", "AMMV", "DSG", "NYEWMTCFE", "HIBQLESMJC", "EWVUP", "ZXWDJZQL", "ZHZLJM", "TDPPTPL", "UBPRPZQPFY", "MSPODZNNER", "RIEVEEISE", "VTIDN", "MIKOJLPX", "IUBDGTPMXP", "PNCRZ", "SSBIEMYRV", "CWAVOWM", "FBIB", "LXKYV", "QTIO", "NAK", "JGAT", "AWVJHTIO", "IRTTFO", "VVNJEW", "OWPXHZKG", "TVBBBAEW", "FLVMP", "TQATGHC", "EABEJXO", "HDTR", "ZWQ", "OLT", "SYKFXEVZGH", "NYWO", "NSUCM", "KYDXA", "ODTFOB", "XPWVIR", "XTFRR", "XFRQ", "THREEVKJ", "FADSHKB", "IKCTJAI", "TDVQTFSPQL", "ZUGCTD", "VYTWTD" };
    assertEquals("AXDYK-KAN-NYWO-OITQ-QRFX", wordtrain.hookUp(cars));
  }

  @Test
  public void case57() {
    String[] cars = { "WLXDYPZW", "WRCQT", "QXELEQYWTS", "QMAK", "OTPCS", "UVYI", "TZYUNR", "ELVAH", "TTZ", "JCMLKELZFI", "NUMVLMGE", "QGZHLAD", "YZXTBTLC", "CAV", "ICVTTALXF", "JNVZLJA", "AKNKSTP", "MJR", "VACWS", "LCUJXBA", "XITK", "BLKEX", "GPKX", "CRKLGQ", "XRMZ", "ZLN", "TWRCPXQ", "ZGDNCDJRMH", "ZXPPJPHOP", "BOCBD", "NRSMNPEJ", "KLXA", "YKNRJKZ", "JMTTB", "JGSYG", "MRRD", "DDDHSU", "UERISUP", "NIPFOD", "HCC", "SITPMKMIY", "VBXWBHS", "NQDVHZSQSE", "TRAPYGMMWV", "JZPRX", "QIJNH", "PZVNEXG", "TZUSJKH", "SZBTU", "DPWLD" };
    assertEquals("BOCBD-DLWPD-DRRM-MJR-RNUYZT-TQCRW-WLXDYPZW", wordtrain.hookUp(cars));
  }

  @Test
  public void case58() {
    String[] cars = { "AWLQGJPG", "HKZJK", "HHV", "TBWWKR", "EFZQ", "XVWYAK", "SVFCEP", "MHPV", "XLHZXNQAPA", "RRLAOYIK", "EGKYPEXR", "XZBPEBXTBZ", "XMSR", "UBAHQBQQH", "QHPNUEXN", "IMTOEDK", "UHZKSZ", "KPOVBIZR", "COPWKOPQD", "BRNBISGR", "JIAMPYXLH", "NWOKGVF", "VYB", "ESLHDFAPN", "FNHB", "HDVWHUZQXF", "DHH", "CHWFCSMLYQ", "IPXTNL", "HVWYW", "XWOZ", "EIZDSNWA", "CIXYKCCH", "EYHRG", "AAMEOHLS", "SHOZMSUDH", "TCDGQQGIA", "JHBMMHJ", "HRNDBUUXW", "JOGYE", "CDHOYLFSO", "DRFTVNB", "KLJDQVJFRT", "KDUE", "XMK", "QLIXA", "PWWMJASOB", "UZKMHNVIGA", "MRDHDVYCE", "VRGCEHUNCE" };
    assertEquals("BHNF-FXQZUHWVDH-HKZJK-KIYOALRR-RSMX-XWOZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case59() {
    String[] cars = { "GYFCAVIGOX", "SPLKMGJXK", "SVHECRXTF", "UPRSKG", "RXNDUYI", "GPIKDIAS", "JNU", "BPENRRRJKT", "XNTYQF", "YYQKJL", "FBKZVFHIY", "JJVQOB", "XBH", "TUO", "TRWQRGWJZZ", "GXVBPAZ", "ZUXGWAOME", "NIPASBOT", "DMSZ", "XKAWEXOUHH", "HTSMRQ", "EMTNM", "TTPBCGX", "YZLOB", "STWMXSC", "QHPTRWTC", "CHLLS", "LTUXIAGLR", "LJYOUAGNK", "KVVFCZG", "RIZBJ", "ODBURRCMKI", "BTVNMBRYZ", "SVUSHZ", "CZWG", "TOYPH", "HELQS", "REFW", "EJKDLP", "BIJAQ", "JPJBYLFMWS", "PJQRXUPM", "GSKHEREU", "VXL", "QNTJV", "FQWWGE", "APGKKKK", "HMAQWCJEDB", "GXXX", "RDQ" };
    assertEquals("CZWG-GZCFVVK-KNGAUOYJL-LTUXIAGLR-REFW", wordtrain.hookUp(cars));
  }

  @Test
  public void case60() {
    String[] cars = { "YHIQOHOSG", "HPNJTKOOR", "XGBZK", "QJY", "TDO", "TGKTXF", "RQPHVWMJYE", "ZFAIXD", "UCYETNRUS", "IAUHJNKTOM", "YJNITZ", "DITKEI", "APRQFD", "BXC", "SJYV", "PFMCMBHY", "QFVMTAUQR", "GBPW", "YINNMJUKSP", "YZUBDQP", "ABSQTCX", "BETNIKFAQO", "JYBD", "OYVHQYL", "STSD", "NJQGG", "GMSBZBXNLK", "XITRKOKEI", "HJNCVN", "ZJLPU", "RHZTRDUKL", "YQDYSGP", "ZILD", "YTSHOIC", "ATHLMXD", "RGF", "IUTSNIXTX", "CHFJGV", "CTSP", "XLSXUEAZ", "SQQODLA", "KTU", "NAAJTFW", "NMTYVAC", "DENXCEVQN", "SRJQDD", "EUGZJRUHI", "GDOEWSN", "GTEUMOQ", "BWIDAPSO" };
    assertEquals("APRQFD-DDQJRS-SURNTEYCU-UPLJZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case61() {
    String[] cars = { "EWVGDEOWAU", "PDGNRVCHBV", "UMXXTSUCCN", "MYHIN", "PLKKWGEWJM", "MNLA", "VRTLSHLLO", "CAY", "UFFSRLK", "BEG", "OZNLRZ", "FXYS", "MCM", "ZGYBRG", "MIXPCYI", "TSA", "VOCXZQ", "VQPM", "UXPLOUWF", "WJSEM", "FCJEAVHPHZ", "WGCNUZWUPO", "QKAPZRWWN", "AGDTOSIXWX", "ORMF", "KSIXWNJRHZ", "OERSXXRMIQ", "CMOWNOH", "VQDDF", "YIDKS", "ITPE", "LRKVFPU", "XNVMSB", "ABOOELTW", "GZKTWQRZ", "VSMVXHNT", "YRQUCFFD", "PQXTR", "IORJXPE", "QNZGBCW", "QJOGZLN", "XPUUTBRSQB", "UVVUXXVP", "WZXSHCWGE", "GFHGMOYXL", "RKWL", "PMRSRYXY", "NTC", "JSQMCJTXD", "VQHXIMGJQD" };
    assertEquals("EPTI-IYCPXIM-MCM-MYHIN-NLZGOJQ-QNZGBCW", wordtrain.hookUp(cars));
  }

  @Test
  public void case62() {
    String[] cars = { "ZKSODEUV", "FQVCHEKP", "YMCBA", "IYVDRN", "OMH", "EYJQVJ", "YRTZPSFQ", "FKCERD", "XZBKX", "JBTU", "SAKQ", "ZTGTXYK", "QAIHNIMUJ", "KGAJTR", "WVCSNHJDDJ", "CYPMOO", "KRCJI", "QFPOL", "XNDRTF", "HVAVFUAW", "VIGTLCUXCI", "SLQ", "NSSXG", "KACU", "LCCFUVYJ", "NYRC", "YYGEOMVCLY", "MMGWCWEWD", "NEIL", "OHDDRSYNJP", "QDSYPOYSD", "OZWTYANEH", "VSJPYQE", "GLZ", "XHKVJ", "ERRPOLLKG", "BCJ", "PEIUBNXXDC", "IMSGTF", "JINGXTTZPE", "SLMTSE", "UXXFPQHODG", "YCEJEG", "YNRMXOZ", "KYYOILS", "GARROUHRBS", "DFX", "JVTYXOZMAT", "SJSCI", "BYFN" };
    assertEquals("BCJ-JYVUFCCL-LOPFQ-QFSPZTRY-YLCVMOEGYY-YNRMXOZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case63() {
    String[] cars = { "LMY", "DCZRQWF", "YKV", "KJCNBMEFVW", "SBZANPLO", "NKTTUOSQ", "VADK", "IVDEFDSM", "JCDOFRRY", "AYBFNCTVCM", "VEPRPFODQH", "RDJCKKSIN", "YZBPE", "OVXDGCGVRM", "UFWOYLYS", "XVD", "XLY", "PNYENVBHYE", "CSIXY", "PDFJDJ", "RUJKFNO", "XPQORKKU", "NGPLYQ", "KJHD", "GETS", "IFAKKTQ", "PZFHPG", "MWUJALYJ", "MMS", "BGNJ", "FCZBDEZGA", "DOMKZY", "EPNYDY", "ZPJFSJR", "PCQPV", "ZQALKR", "GBUF", "UIWHFXD", "AAQWJ", "HVGJFSBZ", "APILDEZTV", "QSHIFM", "GSCX", "SMLNB", "SFI", "PILA", "NMZDAT", "TIMIXS", "QRAW", "HKNRLTAJV" };
    assertEquals("AAQWJ-JYLAJUWM-MRVGCGDXVO-OLPNAZBS-SYLYOWFU-UKKROQPX-XLY", wordtrain.hookUp(cars));
  }

  @Test
  public void case64() {
    String[] cars = { "SLYQYAWJHV", "VWQIZDNP", "TKURZNRMOO", "PTQP", "UFIYK", "KESXGW", "SBIREOX", "QISVYOQ", "CBATMFC", "KJNV", "IYV", "FIMT", "QUXUSXVDVI", "CQLXK", "QHVJQZBWZC", "EYPZXC", "KJTWANSFEO", "DPHQOZACCB", "ZNEMWMXAW", "QFSGYCEX", "SCTQGSRODL", "VPARI", "CIBWWWE", "VBYNDNO", "XDJZ", "KRSUDIT", "BRCPHKA", "TTWFYUVXU", "MTXNBGNUTU", "ZFHZI", "QUUJBD", "OUYFT", "TZAQMZWHO", "OEYQC", "VVCKWWM", "HOJRV", "QLBS", "NFA", "LNCZVHU", "AWGECNBOA", "QRFHVZAZX", "HRGYEVOOX", "GCEJW", "IBAAPQE", "BTLB", "IGRLUMUQLC", "LEC", "XENVTK", "NJG", "SGM" };
    assertEquals("AOBNCEGWA-AKHPCRB-BLTB-BCCAZOQHPD-DBJUUQ-QISVYOQ-QLBS-SBIREOX-XDJZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case65() {
    String[] cars = { "IWW", "KISVRSCFC", "HZXGJBXLW", "KIMNPX", "LKNNSTZOHB", "XDVJDQH", "OBBEBX", "TOQIGDS", "TNLVURTD", "FCVXNFD", "WFSQMJHC", "YOCAVIG", "BIUIKZWYM", "VMVAPKZSLS", "UFGDNYKOER", "JKYZ", "BYTXRDQR", "ZOP", "YVB", "ATS", "QEEDPL", "NGQUW", "AGUCSCJ", "ASC", "DBW", "GVTKAELU", "DABQZTQ", "QZHOILIXW", "IBSGDWWP", "WWVPJLLP", "ZQVLFVLN", "MLJZNX", "QJEVYAZO", "UKELX", "STJFMZIV", "JORSAM", "NGP", "JVNRMSVUKC", "VKCRQR", "EJXHMX", "RQMSPXFPPI", "QOMPKAKLF", "ASPGFCCPQ", "JAFP", "ONDQFFOX", "PWWX", "KMEWSIYKF", "NZKP", "LHRIR", "QFMQ" };
    assertEquals("ASC-CKUVSMRNVJ-JAFP-PLLJPVWW", wordtrain.hookUp(cars));
  }

  @Test
  public void case66() {
    String[] cars = { "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZAZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ", "ZZZZZZZZZZ" };
    assertEquals("ZZAZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ-ZZZZZZZZZZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case67() {
    String[] cars = { "ABBA", "ABQQQQQQBA", "ABBAD", "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "FABBA", "ABBA", "ABBA", "ABFBA", "ABGGBA", "ABHHHHHBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABPPPPBA", "ABBA", "ABBA", "ABBAC", "ABBA", "ABBA", "ABBA", "ABBA", "DABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABBAF", "ABBA", "ABBA", "ABDDDBA", "ABBA", "ABBA", "ABBA", "ABGGGGBA", "ABBA", "ABBA", "ABBA", "ABNNNNBA", "ABBAC" };
    assertEquals("ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABBA-ABDDDBA-ABFBA-ABGGBA-ABGGGGBA-ABHHHHHBA-ABNNNNBA-ABPPPPBA-ABQQQQQQBA-ABBAC", wordtrain.hookUp(cars));
  }

  @Test
  public void case68() {
    String[] cars = { "AAA", "AAAA", "AAA", "AAA" };
    assertEquals("AAA-AAA-AAA-AAAA", wordtrain.hookUp(cars));
  }

  @Test
  public void case69() {
    String[] cars = { "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA" };
    assertEquals("AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA", wordtrain.hookUp(cars));
  }

  @Test
  public void case70() {
    String[] cars = { "ACBA" };
    assertEquals("ABCA", wordtrain.hookUp(cars));
  }

  @Test
  public void case71() {
    String[] cars = { "ZEAZ", "ZEZ", "ZEND", "YOT", "TOO", "OOOOO", "OOO", "OOO", "ZOZ" };
    assertEquals("OOO-OOO-OOOOO-OOT-TOY", wordtrain.hookUp(cars));
  }

  @Test
  public void case72() {
    String[] cars = { "ACBA", "AGEA", "ADFA", "AEDA", "ACCA", "AGDA", "AGFA", "CCD", "AGAA", "ACAA", "ADDA", "AADA", "AEEA", "AEAA", "ABFA", "AEFA", "BBC", "AAAA", "AFAA", "ADEA", "ADCA", "ACDA", "ADAA", "ABCA", "AGBA", "AECA", "AAB", "AFBA", "AFDA", "AAEA", "AAFA", "ABEA", "ABDA", "AFCA", "ACEA", "AFFA", "AGCA", "AABA", "ABBA", "AEBA", "ADBA", "ACFA", "AACA", "AFEA", "AAAAAAAAA", "ABAA" };
    assertEquals("AAAA-AAAAAAAAA-AABA-AABA-AACA-AACA-AADA-AADA-AAEA-AAEA-AAFA-AAFA-AAGA-ABBA-ABCA-ABCA-ABDA-ABDA-ABEA-ABEA-ABFA-ABFA-ABGA-ACCA-ACDA-ACDA-ACEA-ACEA-ACFA-ACFA-ACGA-ADDA-ADEA-ADEA-ADFA-ADFA-ADGA-AEEA-AEFA-AEFA-AEGA-AFFA-AFGA-AAB-BBC-CCD", wordtrain.hookUp(cars));
  }

  @Test
  public void case73() {
    String[] cars = { "HWV", "SNC", "EPW", "FXA", "DFX", "WYP", "VID", "ADZ", "HZZ", "XAH", "PNC", "NYX", "BXR", "YKF", "MEF", "KSE", "AMI", "VPY", "ALE", "LVO", "CUZ", "NER", "RSJ", "YZR", "MMP", "PSG", "QAS", "NYM", "UXH", "KTP", "HDW", "OGR", "NFN", "TTD", "THK", "GJZ", "ETP", "QRP", "BQY", "QPF", "YVH", "VMC", "BFH", "TGS", "LIJ", "ZJJ", "TOA", "BAR", "ETL", "YBY" };
    assertEquals("AXF-FEM-MYN-NFN-NER-RZY-YBY", wordtrain.hookUp(cars));
  }

  @Test
  public void case74() {
    String[] cars = { "AAB", "BDCB" };
    assertEquals("AAB-BCDB", wordtrain.hookUp(cars));
  }

  @Test
  public void case75() {
    String[] cars = { "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAA", "AAAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAA", "AAAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAA", "AAAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAA", "AAAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAA", "AAAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAA", "AAAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAA", "AAAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAAA", "AAAAAAAA", "AAAAAAAAAA", "AAAAAAAAA", "AAAAAA", "AAA" };
    assertEquals("AAA-AAAAAA-AAAAAAAA-AAAAAAAA-AAAAAAAA-AAAAAAAA-AAAAAAAA-AAAAAAAA-AAAAAAAA-AAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA", wordtrain.hookUp(cars));
  }

  @Test
  public void case76() {
    String[] cars = { "BAD", "CZD", "DEF", "AYB", "AZC" };
    assertEquals("AYB-BAD-DEF", wordtrain.hookUp(cars));
  }

  @Test
  public void case77() {
    String[] cars = { "ZOOZ", "ZOZ" };
    assertEquals("ZOOZ-ZOZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case78() {
    String[] cars = { "AAA", "AAAA", "AAA", "AAA", "AAA", "AAAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAAA", "AAA", "AAA", "AAA", "AAAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAAA", "AAA", "AAA", "AAA", "AAAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAAA", "AAA", "AAA", "AAA", "AAAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAAA", "AAA", "AAA", "AAA", "AAAA", "AAA", "AAA", "AAA", "AAA" };
    assertEquals("AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAAA-AAAA-AAAA-AAAA-AAAA-AAAA-AAAA-AAAA-AAAA-AAAA", wordtrain.hookUp(cars));
  }

  @Test
  public void case79() {
    String[] cars = { "ABABABAB", "BABABABA", "ABAB", "BABA", "ABABABAB", "BABABABA", "ABABABABA", "BABABABAB", "ABABABAB", "BABABABA", "ABABABAB", "BABABABA", "ABAB", "BABA", "ABABABAB", "BABABABA", "ABABABABA", "BABABABAB", "ABABABAB", "BABABABA", "ABABABAB", "BABABABA", "ABAB", "BABA", "ABABABAB", "BABABABA", "ABABABABA", "BABABABAB", "ABABABAB", "BABABABA", "ABABABAB", "BABABABA", "ABAB", "BABA", "ABABABAB", "BABABABA", "ABABABABA", "BABABABAB", "ABABABAB", "BABABABA", "ABABABAB", "BABABABA", "ABAB", "BABA", "ABABABAB", "BABABABA", "ABABABABA", "BABABABAB", "ABABABAB", "BABABABA" };
    assertEquals("ABABABABA-ABABABABA-ABABABABA-ABABABABA-ABABABABA-ABAB-BABABABAB-BABABABAB-BABABABAB-BABABABAB-BABABABAB", wordtrain.hookUp(cars));
  }

  @Test
  public void case80() {
    String[] cars = { "AAA", "ABA", "ACA", "ADA", "AEA", "AAA", "ABA", "ACA", "ADA", "AEA", "AAA", "ABA", "ACA", "ADA", "AEA", "AAA", "ABA", "ACA", "ADA", "AEA", "AAA", "ABA", "ACA", "ADA", "AEA", "AAA", "ABA", "ACA", "ADA", "AEA", "AAA", "ABA", "ACA", "ADA", "AEA", "AAA", "ABA", "ACA", "ADA", "AEA", "AAA", "ABA", "ACA", "ADA", "AEA", "AAA", "ABA", "ACA", "ADA", "AEA" };
    assertEquals("AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-ABA-ABA-ABA-ABA-ABA-ABA-ABA-ABA-ABA-ABA-ACA-ACA-ACA-ACA-ACA-ACA-ACA-ACA-ACA-ACA-ADA-ADA-ADA-ADA-ADA-ADA-ADA-ADA-ADA-ADA-AEA-AEA-AEA-AEA-AEA-AEA-AEA-AEA-AEA-AEA", wordtrain.hookUp(cars));
  }

  @Test
  public void case81() {
    String[] cars = { "CCCCC", "BXXXA", "AEEEC" };
    assertEquals("AEEEC-CCCCC", wordtrain.hookUp(cars));
  }

  @Test
  public void case82() {
    String[] cars = { "ZZZ", "AAZ" };
    assertEquals("AAZ-ZZZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case83() {
    String[] cars = { "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA" };
    assertEquals("AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA", wordtrain.hookUp(cars));
  }

  @Test
  public void case84() {
    String[] cars = { "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA", "AAAAAAAAAA" };
    assertEquals("AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA", wordtrain.hookUp(cars));
  }

  @Test
  public void case85() {
    String[] cars = { "DAS", "SAD", "SSD", "DDS", "ASDA", "ADAD", "SDQE", "FWFF", "POK", "OPK", "OPK", "OKP", "IOH", "SDF", "EWF", "WERF", "WEF", "WSDSDF", "SDF", "FFF", "YTF", "YTFF", "YTFFTY", "YTF", "YTFTYD", "RTDS", "TRDUTR", "UTRD", "UTRDUTRE", "UYTF", "UYTFUTRS", "TRDYTR", "DYTR", "YTDRYT", "YTRD", "YTRD", "YESRE", "TRES", "HTR", "YTRE", "YTR", "YTRD", "TYF", "UYT", "YTRD", "TRD", "TDRY", "RTRD", "YRD", "YTRD" };
    assertEquals("ADSA-ADAD-DRTR-RTDS-SERT-TDRY-YTFFTY", wordtrain.hookUp(cars));
  }

  @Test
  public void case86() {
    String[] cars = { "ABC", "CZZD", "CXX" };
    assertEquals("ABC-CXX", wordtrain.hookUp(cars));
  }

  @Test
  public void case87() {
    String[] cars = { "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAABB" };
    assertEquals("AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAA-AAABB", wordtrain.hookUp(cars));
  }

  @Test
  public void case88() {
    String[] cars = { "AAA", "ZOZOZ", "CAAA", "AAB", "JZH", "AZZZA", "BZB", "BYC", "CCC", "CAC", "CACAC", "CZF", "CZD", "DZE", "FZH", "ZAZ", "ZOZ", "UZV", "TZV", "VZZ", "ZZZZZ", "JZK", "KZL", "JZL", "LZM", "HZG", "FZG", "HZI", "IZJ", "MZN", "LZN", "NZO", "OZP", "NZP", "PZQ", "QZR", "PZR", "RZS", "SZT", "RZT", "TZU" };
    assertEquals("AAA-AZZZA-AAB-BZB-BYC-CAC-CACAC-CCC-CZF-FZG-GZH-HZI-IZJ-JZK-KZL-LZM-MZN-NZO-OZP-PZQ-QZR-RZS-SZT-TZU-UZV-VZZ-ZAZ-ZOZ-ZOZOZ-ZZZZZ", wordtrain.hookUp(cars));
  }

  @Test
  public void case89() {
    String[] cars = { "AAB", "AAC", "AAD", "AAE", "AAF", "AAG", "AAH", "AAI", "AAJ", "BAC", "BAD", "BAE", "BAF", "BAG", "BAH", "BAI", "BAJ", "CAD", "CAE", "CAF", "CAG", "CAH", "CAI", "CAJ", "DAE", "DAF", "DAG", "DAH", "DAI", "DAJ", "EAF", "EAG", "EAH", "EAI", "EAJ", "FAG", "FAH", "FAI", "FAJ", "GAH", "GAI", "GAJ", "HAI", "HAJ", "IAJ" };
    assertEquals("AAB-BAC-CAD-DAE-EAF-FAG-GAH-HAI-IAJ", wordtrain.hookUp(cars));
  }

}
