package topc.test.easy;

import junit.framework.*;
import org.junit.Test;
import static org.junit.Assert.*;
import topc.easy.*;

public class CandidatesSelectionEasyTest {
    CandidatesSelectionEasy candidatesselectioneasy = new CandidatesSelectionEasy();

    @Test
    public void case1() {
        String[] score = { "ACB", "BAC", "CBA" };
        int x = 1;
        assertArrayEquals(new int[] { 1, 2, 0 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case2() {
        String[] score = { "A", "C", "B", "C", "A" };
        int x = 0;
        assertArrayEquals(new int[] { 0, 4, 2, 1, 3 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case3() {
        String[] score = { "LAX", "BUR", "ONT", "LGB", "SAN", "SNA", "SFO", "OAK", "SJC" };
        int x = 2;
        assertArrayEquals(new int[] { 5, 3, 8, 7, 4, 6, 1, 2, 0 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case4() {
        String[] score = { "BBCBABAC", "BCBACABA", "CCCBAACB", "CACABABB", "AABBBBCC" };
        int x = 6;
        assertArrayEquals(new int[] { 0, 1, 3, 2, 4 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case5() {
        String[] score = { "XXYWZWWYXZ", "YZZZYWYZYW", "ZYZZWZYYWW", "ZWZWZWZXYW", "ZYXWZXWYXY", "YXXXZWXWXW", "XWWYZWXYXY", "XYYXYWYXWY", "ZZYXZYZXYY", "WXZXWYZWYY" };
        int x = 3;
        assertArrayEquals(new int[] { 0, 3, 4, 5, 7, 8, 9, 6, 1, 2 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case6() {
        String[] score = { "X" };
        int x = 0;
        assertArrayEquals(new int[] { 0 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case7() {
        String[] score = { "WVMQXRPPLQOLVMKTLVOOPVUKXQTTTRMM", "LMKOXOVRXMVPSQPVLXSLQMVNSPRMXTKX", "NMUPQVKTXPLQWNQONQOLPRRQMTKWUMXL", "TLWVRQLSNLRRUQSRVQVKLRRQQUSVUNNP", "KQMKXUUUNLLOMPKKTKQMNUUMTROWRRTK", "MRNTPUTSQTQPXKTNUQXWWPMMSUNWNWMW", "PLXVPULVVLTVMUTUUVMVUKKNPRVLMUQL", "VUUWOVWOVLXPUXMVULSQLNLLVOXPTPPS", "WLLQVWVXRULTPMVRMWQPRMVQQTQQONMR", "MRPVVNQPNNURRQMPMMVMRPTSUKVLOORU", "LTUVWWRLWXWRTLMMULSMNKVSRSRSQOTK", "QLSWQOXUTMQNVKLVQMWOSQUOSNWVSTUS", "NMNOMNSLOQVWXQOMKOTOTKOKNTPNXWXS", "LMMRTMSKPPQSNLLLRUWWNRWLQNUKOTPO", "MNLVTOSPVPOSQORULOOWUKKPOUWSXKXN", "ROQNNUSWNSXOVRRXKQUVOXQXLLPMNMVX", "LQXLNWOOTUXLVUUVLKQMSRQRPSLXXOLS", "LRRTVNTMNPPNRNSKUMSOVNVRRTSRLTXL", "MRQUMXKOSTLSMSOMKQNMSPTURKKQWMKT", "VNQMSQRPTUKRMUORSLRRMOVPNLNVSNXU", "XXSTKKNVVPTSKSSURRNMXPKUNUXSKPSU", "QQMNPKVWVRTKMNUKRLRUUPKOMXPXPQVX", "UUKOKTWVVRPSTMOKUWXQVLTOSTSWWUSN", "WQRLPPUTRLVWRRNOLVQOULOUPLQQUTOO", "OXTQWSMPSMSRXWUORSPUMSLUVRXUWOPO", "OVOTWXWRNSKONRQNPMMNXQVWQOWPOORP", "SNMLSMRUUMOQRUONVSLMWMVXXUPPONVO", "MXUNOQOSLRNWTOSTTMKSVMPRSNWOPUOK", "RSTPSLPXVWMRMQRRXVKUKXKWPOWUTUPM", "OLXVLXWVMKKLUWTVOWWTTQVSMOOQTWWR", "TXVUVOXXNVNNVSPQNWOVLNWPUOSMUPWR", "NTQSNNSOPNXMPUVOSTQRNWQORKWUQRQV", "RSMPQPPNKNNNROPRQORXWSVQLOSOQKMR", "LQWOLMORWQKPSTNLRXVQMLNTKNNOVLKP", "USTNPMSSVPTTUVUXMMTWSVNTUPLVKPUQ", "OMSUQUUPUMSXMXOVUMKWNSSRVLMTXROS", "RPTXNXPTTWLQOQPWRMOKLTSUQPTXLVNU", "VRMKWWTQNQUQTSKOXPWSLTNOPKWWLOOK", "NSQSMNRXTKWQPKQLLLMKMRXTKRKTRMSL", "WSSXWWKKWNKWMLSKTSPTNUTUUWORUOUM", "WMXUWROPPKLKWTLLQQNTPOKKPXXKRVLM", "VOKSUKPTMKRLOVLPNSKXKTKSQXXPUVPO" };
        int x = 30;
        assertArrayEquals(new int[] { 1, 18, 33, 16, 40, 0, 5, 8, 32, 3, 36, 23, 27, 35, 37, 7, 13, 24, 28, 41, 6, 31, 9, 25, 20, 22, 38, 4, 10, 11, 34, 39, 15, 21, 26, 29, 30, 2, 12, 14, 17, 19 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case8() {
        String[] score = { "YYZXYWWWXWWZWWZWXYWXXYZZZYYXW", "WYZYWXYZZXZYYXZYZWZXYWYXYZZYZ", "XWXYYYYYYXYWWZZYXWXZXWZZZYXYY", "YXXYXZZYXWYZYWYWWWYXWXYXXWWXY", "ZZZXZWZZYWYWZYXZZZXXYYXZYZWXY" };
        int x = 4;
        assertArrayEquals(new int[] { 1, 3, 0, 2, 4 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case9() {
        String[] score = { "UTUUTWVUUTVVU", "USSTUTWVUTUXS", "WTTUSVTXVXVWX", "TWXVVUUVXSXVT", "WXSUUVVWSUXTS", "USSWTXSSVVVXT", "TWXVSVXVSXUXV", "SVUUSXUXWSTTT", "TTSTSUXTUWVTU", "TUUTWWXWSVXSS", "XXXSTWSTVXXWU", "WTUTUSTUUVWVT", "TXWTWWWUTWTUW", "SXXSWUSTWTXVU", "XSVWXSUUTWUVX", "WXXUWXWSXWUTX", "VSSVWVTTWWXVU", "TXXUUXSTSWWUW", "XXSVWSVTTVVUS", "VUTWVTWXTUSUX" };
        int x = 12;
        assertArrayEquals(new int[] { 1, 4, 9, 18, 3, 5, 7, 11, 0, 8, 10, 13, 16, 6, 12, 17, 2, 14, 15, 19 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case10() {
        String[] score = { "SQSPOQPQKOQOTKSMSRLORPNRR", "MQQTTTRNNQPORLKOSPLLTSMLM", "QRKONNKMQQRSLPLQPLNSSLSMT", "POKOPQMSTMKMPTNMSTMLMORLT", "QKLRKNSKKKRPRQSORMNLNPNNN", "NTMNKMPPTTOORLRLTNQQPSOPR", "POQKSMRPQQOKRRMNNSLSKSKRT", "NLMROQPRQMSQQRMPPNTTSPQLQ", "RMKTPMRNQKMOQNPLROOTPRKLQ", "NROPTOTPPNKTQTTPLLSNSPOKN", "LSTMKTPLNMRQTOMRRSLTOQKOT", "OSMRSOLPMMOKKLTKNKOSSSKOM", "TPMLTLTNPRMNMONRQPMMPRLMK", "TRPTRQTQOOMSSMSOSLNKSQTMN", "QQRNRKQLQLSNKPTOTMRNSPONO", "RQNTLOQNTLTQNPLNKKONKSLTQ", "MOQPRRLKKOKLSMQSRKRONQOLT", "NTMLMQRTMSNQRRPLPQOKOTQLP", "RQTMSPTLKRPTOTKOLTQSLMMQR", "KROQMQOQOLORSPNPRPSRMOTNP", "SMSPNOMPRORQMPKNQQRMNLRPP", "MTMSSLMTOTPRSLQPPRNQOTLOS", "OMKNROTQLQSMKQTMLSTSTTORM", "TNOQTQPTQQMKKQTSMKOSOTPTQ", "TLRNQPSKRLKNLROTOMMNKPKOO", "NLKSRSTMRQRTLOMQLKTPNQTQT", "LMNORLKNKLKTPPLPNPKPPKTSR", "OLNTQPSORQPPRNPORSNOQNSQN", "MPLKSNRRLMMOQLNLQNKKKQRMP", "LOQMNMLPPPSQNKLKSTQROPSLK", "MSKTLQSTNQRKKKTQSTNTLSROK", "MSORKTSSLRRKQOSKLQQRSSSKQ", "QRSQNPOKMQSOTLRRSTNONKKKT" };
        int x = 0;
        assertArrayEquals(new int[] { 19, 10, 26, 29, 1, 16, 21, 28, 30, 31, 5, 7, 9, 17, 25, 11, 22, 27, 3, 6, 2, 4, 14, 32, 8, 15, 18, 0, 20, 12, 13, 23, 24 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case11() {
        String[] score = { "BNM", "KGO", "FFA", "IKC", "MEO" };
        int x = 0;
        assertArrayEquals(new int[] { 0, 2, 3, 1, 4 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case12() {
        String[] score = { "FOSSBNGPBGGKHFDRPDROKOKPCEEDHEKSGJOLHQMO", "IOKGMBMOIHHRMQIGLNJBKMHLQPGMRPHHGECLRSMK", "MQJONIFMNBDHOCHRCPEJFDDEDOCDOCGJGCINKJEO", "QJQGRBOHJBNMPJENJCFENQNMSIRCLPHPKDKCGJBB", "ILDJFIGCGKKNJQCDSKMEGENJNNHBLCHOIPOCEPEE", "PDNBDENPDSJBBQIKCGBJKQPOOSJBBRSPMJMDHQGG", "DOCDHLJLBQCRSEPCOKDQMBMSIRRJKRBLNQQMFPSC", "SRMKFNSPCDFIJINLNNISGRMPKRBDEQCCSOOMFLPO", "PRDCPIGEKMNRQGQRPGSJBCMOMJMPLKJSBNKGLCBR", "KNJGKELHIBFBELFDQFFEQDLKCIBMEFOSQKPNHQOB", "QFLSEOHSCSCPKSNJOOIEKCJQBBQRBNJBBESNHOPP", "GNKDRCBDESNJSGNQDHGMEIJCIHOHFJSHNHPPQPJJ", "QOGBSEMJQOPEQFNCEOLOLNMKBKPPNJHMCBLGOHBK", "RENOBJEQNLRBLQBMFLNCDPMCKDOLSJCBNDKHGHRM", "EFJMCCJENEEBCFOPMDINGCFHOBHDLGJHKRLJEEKO", "CDCGRIRDEKEILQDHOOKRCJQMDCHLJEPFEGRSEQDS", "IHRKCKEMQOCLMMBKBEBEHCHRERIBILBBDKMQMJKE", "LILNQGOCCKJRRFNJQIKCRPSQBMIISPQQPBOPDGPG", "PBHISFMGDCLNHRCNDOORGRGLCHBHINCRFKSOFMIM", "JPDQQHCDRRBDPSKFDCLIBNOCEPNNNSOINFCKRNER", "MCFDPMNSPKEFPGOICLSGMCOOGEJKLPKMDCEOHGMK", "HGMJILBCBNCCDIJRSDHOQECCDNEJLJKJKCSIKLPG", "HPDHQQDPRNHGEBHPIHHRLECJJFPBJDGBRSSRMFEG", "CDKJSJIOJSMFKDCIPCLQONCDQRIQESKFPEKNEDSD", "GFQFNNJELIQMDHNQDNFMOIONRSEOKSRCCNCMSKEE", "FBQHQCINCCJLCROJHHIMPLLJMNMDPNDHSELOHIIL", "FBQNFLKGREJFNRJODLCPOQBRKSFKNEPEJFIHKJKQ", "RIGHQSQPLHJRKJIDQIHBHLEQGGOOOBOPLGHIMOIE", "IRGJOKREESESKHDGCRJLLIFFRLFBFFHFOKSMQLIQ", "RNJQQILSOIKDCJGJNDDRQHBSLOEHPRQCPIPHNPEM", "JSKBRSIOPGFQJENSHCBQLMBRBFNNRLLEFQEFKRIP", "SFOPJMSOCJLNPCNBHSSPFJQLMMMOKJQPGMLRHCOM", "EIHHQBEGJPBBMFHLIJBPEMBIBIMNFIFHQLMHDSIP", "NRJPMBHFHPLIORCLDFNLNQRFGNSCFOILLLQGDGQD", "RBLSQOEEHLOOIMLOOLIFENLJROFIBKIBKDPHJDCK", "RGIJEBEOIDBBSKMBEQCMEPSCRSJPRKJEKONSRQOJ", "SPBMOEGEFOSNHJLKJCBBFQKIFSCFEIMNDMRHPNMI", "KNGQHCBCHDKCOLIHESSCBOPQIBNQQQDDJERMOOIG", "QQBSIIOLDIEPOJMMDNNKRPOMQRBBRMKQNOGHONOG" };
        int x = 14;
        assertArrayEquals(new int[] { 13, 16, 4, 18, 23, 33, 0, 15, 28, 3, 9, 29, 2, 22, 32, 1, 5, 27, 37, 21, 26, 19, 34, 36, 35, 38, 7, 10, 11, 12, 17, 24, 30, 31, 14, 20, 25, 6, 8 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case13() {
        String[] score = { "VKOMKKVJHL", "PQSPTRVUQQ", "QORUOSQLJM" };
        int x = 9;
        assertArrayEquals(new int[] { 0, 2, 1 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case14() {
        String[] score = { "BBEDCDEC", "DABEFABC", "BAEEEDDE", "BBBABBEC", "ACEBDACF", "ECDCAEDE", "FFAFFACE", "BFCFCECF", "DDEEDCCF" };
        int x = 7;
        assertArrayEquals(new int[] { 0, 1, 3, 2, 5, 6, 4, 7, 8 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case15() {
        String[] score = { "QWX", "YVV", "UPX", "WVU", "VTO", "RYQ", "RQT", "RRQ", "UUW", "PSO", "SQU", "OOX", "XST", "SVU", "XUX", "TYY", "OYX", "WWU", "PVT", "QRY", "QQY" };
        int x = 1;
        assertArrayEquals(new int[] { 11, 2, 6, 10, 20, 7, 19, 9, 12, 4, 8, 14, 1, 3, 13, 18, 0, 17, 5, 15, 16 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case16() {
        String[] score = { "YWQTVTYQLCWOSPKTKXIFCGKJSQ", "RPQGCWGJRPEYJWODYYMYVGIPVH", "SHCGNDPUNRQFMVVQLJTFLSYCOH", "WRGSQFLGQVOETXHXYYOVSSMEEU", "YEJCISKQGKEILRXIGXXESHSCQE", "PDDHXGIXUOLGTSODUNPEQYELQH", "VHNHTFROQMKHMERLOUGKHDOFYH", "EKTFFFNICRHJYKOPGPQCPUCVEV", "GWTFRKKLWRHMTWUEMIEPTFQQHO", "OJGCGEWILEUNWTIEPUMNLSPSLO", "EMYUEMHPELIKWPKNDLOMHXRJIG" };
        int x = 23;
        assertArrayEquals(new int[] { 2, 4, 3, 6, 0, 10, 5, 1, 8, 9, 7 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case17() {
        String[] score = { "WVXVYWYVXXYXWVWVXV", "VWWWXVVYYXWVXXWWYV", "WYXWXWXVVYXYYVVYVV", "XYVVXWWWYWYWWVVXYV", "WXYXWWVVWVWYYXVWWW", "VYWWYYXVXVWVXYXXWV", "WWYXWXXVXXYVYWVWYY", "WYYXVVYVXXVXXYXVYY", "WYXWWWXYWXWWYXVYYV", "XYYVYVXXXWYWWXXWWW", "XVYWVWWXWVWXYVXYVV", "XVYWWXVXXVWVVXWYXY", "YWYYVYXVVYWYVXXXVY", "XYXYWVXVXWWWXXVYYW", "YXYYVVWWXWYWXXVWYY", "XYYXYYWYVXXWYVVWXY", "WYVVYVWXYXVWYYWVWW", "XVXVYWYXYYWXXVVWVW", "VYVWYVXYYVXWXVVYVW", "VXWYVVXVYVYWWYYYWV", "VYXYWWXXWXXWWYXVXX", "VXVVYYVYXXXWVWXWVX", "YXXWXYWWWWYXYXXVXY", "YVWVYYVVWXXVXYWVYY", "XXVXVWXXYWWYYVYWVY", "WYVVYYYYVWVYVWVVXV", "XVVVXXVWYXXVVXVWWW", "YXVVXVYXWVYVYVVWVW", "XWYXYWXWWWYVWWWVVX" };
        int x = 17;
        assertArrayEquals(new int[] { 0, 1, 2, 3, 5, 8, 10, 19, 25, 4, 9, 13, 16, 17, 18, 26, 27, 20, 21, 28, 6, 7, 11, 12, 14, 15, 22, 23, 24 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case18() {
        String[] score = { "UUWURXSRVPQSORTSOOVVW", "SQXUWRPOOPSQSSSRWQQUW", "TQUQRQRSRTOXXUVUTSVUT", "VWXUTSSPOPOSTWUUXWUXT", "TWSPVTSOXUSPOORUQTQVW", "TWUPQPRUUTSXPUTTVXTRO", "OOWPUQWVTVQUUSTQQSVTX", "XOVOXROOVUWOPRSOXROUX", "OVPTURPWURQVSVQRQVRXT", "SVWXUUUVOUSUSVWOQXPOQ", "TXTUVWWQUSWSPVWRRXSQO", "XVWOOQTSORPVPOQXWXXXQ", "RPPWSUOPTXVXVPRXXOXVS", "TRPXVPSVOVOUQWPPXXOVS", "QRQTQPROPRQVVQPRQXRVQ" };
        int x = 16;
        assertArrayEquals(new int[] { 0, 4, 6, 8, 9, 14, 10, 2, 5, 1, 11, 3, 7, 12, 13 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case19() {
        String[] score = { "QRRQQRRRQRQRRQRQRQRRRQQRQQRQQRRQRRR", "RQRRRRRQRRQRRRRQRRRQQQRRRQRQRRQRRQQ", "RRQRQQRRRQQQRRRRQQQQQQRQRRRRQRRRQQQ", "RRQRQRRRQQQQRRRRRQRRRRQQRQRRQRQQRQQ", "QQRRRRRRRRRQQRQQQQRQQQQQQRRQRQRRRRR", "RRRQRQQQQQRRQQRRQRQRQQRQQQQRRRRRRQQ", "RRRQQQQQQRQQQQRRQRQRQRRRRRQRQQRRRQR", "QRRRRQRRRQQRQRQQRRRQRQQRQRQQQQQRRRQ", "QQRQQQQRQRRQRQRRRQRRQRQRRQRQQQRRRRQ", "RQQQRQQRQRQQRRRQQRRQRQQQRRRQQQRRRQQ", "QQRRRRQRQQRRRRRQQRQRRRRQQQRRRRRQQQR", "RRQQRQRRQQQQRRRQRQRQRQRRRRQRQRQQQRQ" };
        int x = 23;
        assertArrayEquals(new int[] { 2, 3, 4, 5, 9, 10, 0, 1, 6, 7, 8, 11 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case20() {
        String[] score = { "LFMPENNELIMFK", "KNPEKPEDMPJPK", "OMDGNFKMKKENO", "OKPGJDNKEGPNM", "KPOLNKGGFNMNL", "PJHNIGDGMJNNM", "KNDEPLDIOPNJM", "MODDMLFHOEKPI", "FMKKPIKNEFFOE", "HNLOJMMIEPILH", "DHKFJJDKNMPGD", "DMPEOKHHLIIHM", "FIPLNHGPJDGJI", "DMJPIGLKJOLIE", "IPPKPMFLHGMML", "JOFFDNNKFMENL", "NDKHLHKMFFHIF", "PDLDHMGDINFNJ", "GNKEFJKODEGNE", "HFEGEILDGDPEP", "MOMPEPGLEOOFK", "FDPPFHIGNKFGE", "NIMIKKKGOHOEP", "MMFDIDOIDOHMJ", "OKPHILGNEDJNM", "HGMJONFGHFOLG", "HNFPDOFLMKMDG", "FFOLKFDHPGDHE", "NMKNPGIGEDNLI", "KPIEDLKHLDLFK", "GPHMOEDMEEGDL", "EIKGKLEKNEOMF", "KJJMGEPPGEHED", "JNHOELLLNKFLK", "MIJKKOKPLKLOG", "DKENDENMIHDIM", "NMGOENFMIPEKF", "NLGJMELDENLNI", "GKEMHDDHOHKMJ", "HEFJGJPEDNFDE", "FLNNNLDMELJDF", "EGNFDMOFPHMEH" };
        int x = 3;
        assertArrayEquals(new int[] { 7, 17, 23, 1, 6, 11, 18, 29, 10, 15, 41, 2, 3, 19, 31, 16, 24, 22, 25, 37, 39, 8, 14, 34, 4, 12, 27, 30, 32, 38, 5, 28, 35, 40, 9, 33, 36, 0, 13, 20, 21, 26 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case21() {
        String[] score = { "RPRQSPNPRQRSSNPRSSNQPRRSPQOSSPSOSPQNS", "ROQNPQSNPQNSNSPPROPSQQNRRROPNOROONNOP", "QQSNSRQOROSPRPSOOORSPNOORORPNQQONSPSO", "SROSNPNSNPNPNPONPSNNSRPSRQNRPSNORNORN", "SQQPPSOORSPNRPQORPSNPOOSORNPOSRPSOOQQ", "PNRRPROQQQRPQRQQOPNPSQNPSQONPQRSPPRPQ", "OQRPSNOQOSRPSNRRNSQSNQNPRNSONNOQPNSRO", "PQRSOPQNPOPPNQSPPQPQQORQQRNSNQOORPSRS", "QOPRNPNNNNRSRNSROQQQPSQNQONPSQPPOONPQ", "PNRQRPQPPNQNSQSQOQRPOPORSOPSQPNQOQPNP", "SQPPNSPOSQQQPNNOSRSNQOQOSORORQRPPPRPO", "QROSRQSNRRNNPSPSOPONSPSPQPNRNQNSPQOOS", "RSOSNNOSNNRPPSQQSPRQNSOQSRRNPRQSRSRNS", "ORQPNRSQNRNNSROSOOOPPRQNQQNQSPNNORQRO", "ROPSRNSRQSRORPPNSQQORNRQPQQNNOSNPRNNO", "SOQSSPPNQONNSRPQSPPNSPNQQRSOSNOORPPSR", "SQSROOSNRQOONNSQQRSNNQNNSNONNNSPOPQQP", "RPQPNPNPPOPPPOSPQRQORSPNNPQSNQOSOROSQ", "OPSPRRRQROPROROPRNNQPPQOOSPSOQORQSOOS", "OOQQNQQPRORSQNSPPNOORPRQRSQPNOQOSORPN", "SPRPRSPRNOPQSSQQRQSQNRSRPSOQQOQSSPORR", "ROONQQSROONPQONONOPPSRQQORQOOSRPPPOQS", "NNQOQRPPOOPOSSRPQSPSQQRQPPNROPNQNROON", "PRNPPRNOROSRNORNOSPQQQRRONPNPQRRNQSRQ", "NRPSQOPQSSQPQSRPROQSRPRQOORNNOQQSSNSS", "PNQNNPRRONNQNSRORSSNPNOORQOQRSROSQNQS", "OPQQOOQQOOPPOSNPSSPNNQPRRORRPRRNPQQRQ", "NRQSROOQRPQSPRQNQOSPSOONOSQOROPRSNOSS", "RNNSQSQQNQOSRNRQPNQPROOPQPQNNNOSORPQS", "RNNSNNRPSQPNSPORNOPPOPOQQPONPSSQNRQNO", "PSSRPOQOOQQNQOPPOOOPNQROSQOQQSROOROPP", "ORRSOQNROOOOPSRQRQOSPPQQQQQROQPRQRPOR", "QQSOPONORSNSNSOPSSQQPPRRNRQRPSOSQOPOR", "SNPSPPRNPPOPRSQQNORSOQNQSSRPSOORRSROP", "NRPSNNQSSPNNORRNQSROSOSPPPOPRONQPNNSN", "RQPOSRSRNQPPQROSQQQPSOSSONSNOOQPORRSO", "RRSOPONQRRNQSOQNSNSRSNRQRRNSQPRORPSNP", "PQNPRONQNQPPSSOSQOQSOPNNRQNSSQOOSOQQR", "SQPNONQNQSRRQPOOQRPOQSPQSNSSSNNRQRRNQ", "ROOQRRNSNPRSSONONRPOQNROQOQQSONOOPSPQ", "SQORRQQRPRQOQRSPSPNNNNQOSQRNPQPORNSRN", "POQRNPSPOSPONONNRQRNRNONNSQNRPRNNPRSS", "PNRNQPSNSSQQRPRRSPRSPPOQSRPNNQROPNSQP", "RQQRNSOPRORQRORQPNPNOPORQSPSQNRNNNRSO", "QQRRSRPNOSPPQSNOQNRPOSPSQORSSRROOSRPP", "QRNOSQSPOQQQPOPSQNNNSSNONNPNOSQSRPPQP" };
        int x = 17;
        assertArrayEquals(new int[] { 18, 19, 28, 36, 43, 44, 45, 1, 2, 13, 21, 24, 27, 29, 30, 33, 37, 4, 5, 11, 12, 15, 40, 42, 7, 8, 9, 14, 20, 31, 35, 41, 10, 16, 17, 38, 39, 0, 3, 6, 22, 23, 25, 26, 32, 34 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case22() {
        String[] score = { "QRQ", "QPP", "PSS", "SSR", "SQP", "SSS", "QQQ", "PPS", "RPQ", "QRS", "QPS", "PQQ", "PSS", "PSR", "RRS", "PSR", "SRR", "SRQ", "RSR", "PQS", "QRQ", "QSQ", "SSQ", "SPP", "QQP", "PPR", "QRS", "SQS", "SSS", "SPP", "PQQ", "PQQ", "RRR", "RQP", "RQQ", "PPS", "SRP", "PQQ", "RSS" };
        int x = 0;
        assertArrayEquals(new int[] { 2, 7, 11, 12, 13, 15, 19, 25, 30, 31, 35, 37, 0, 1, 6, 9, 10, 20, 21, 24, 26, 8, 14, 18, 32, 33, 34, 38, 3, 4, 5, 16, 17, 22, 23, 27, 28, 29, 36 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case23() {
        String[] score = { "ALPFMELUOANB", "QBDUROAQSPDB", "KQMLFJBMGRJI", "BAFETAFBTBDP", "TBSKHBNUALQF", "BNFJSJFTJCGM", "KCFUIJEOLTPJ", "UIQIAUSTMEAM", "JRNPGSHGJOLE", "UTSMLDOABECL", "UBJDBKODREKO", "GJHNTTHJNGIM", "AGBRINUSHFOS", "AKGEOHDNNNUD", "JNRHHSIIREMC", "SDDOMFNNRUIK", "RQOCDLDPEKGL", "TIJNANOIOHGN", "POGPFGDBIDAG", "SENKDFFIKABL", "ETRHGJQAAJUC" };
        int x = 4;
        assertArrayEquals(new int[] { 7, 17, 10, 16, 19, 2, 18, 8, 20, 4, 14, 6, 12, 9, 0, 15, 13, 1, 5, 3, 11 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case24() {
        String[] score = { "RPJTQIUQLPTLLISMUQJSNIKOPIKL", "JJJUTMJOLMNTTJRUITQSUNSKURLS", "SKIRKKSTSOSJQRNQNRQKMJMLQORL", "JOJLMNLSMLOOOUOIRSRSJLMURRNL", "UTJIMPTIKRLIIPJTLKUPIPMOJQNK", "UTTRKTTNJINJUNPJJJLSLPOPUITK", "ROPIPTSKQMTKKLKRPNQSKMTJSRIQ", "LNIMOLTKRNSTRUPNMPOOUQNLTPQN", "NTUPIPOLNQILPRUNTOLOQPNILISP", "KMTMTNUJRTKKRJNSKKNJILTQIUMR", "RNITLMTTURIOINJOLINQQRRLIUJQ", "LTLRQJKLIOTLRISPLLPPTJNMUJUK", "ULSQMOTSOPIKUOMRJNNNOQKISUSI", "KUPMSRUJRLMLRPIPLMTNISSLPJRQ", "TOIKQRMQUIQMLROJLKQNTUTTIPSQ", "JKQJJQUKUNRUUOQUIJSQNKQMLSIT", "JMPLPQJMORTTLQROTJONUPNTIQTM", "TJQQLKNSNRUMIKJIJPTUOQJMIRTI", "MISMKLIPKRIKMMQRKKOPJPPLJMLQ", "KMNSRMLTMLKLQTUNURKPUJURIRRK", "OKJOJROJRJOSPTOQTJMQQPMIIPPT", "LJLOIIKMNQNRIIPULORRUINNUIIM", "ULOLJMJMMJUJRNPSOKTKULPPSJPO", "IJLTLPPTMOULQRLUQTUJRSSPNLIL", "UPLNMJKPMROIUQROITPQLOKRQLTM", "UQJIIOSMPQMOTRSTOSUILSQOPJRL", "OISJRUMSUSQUUOQPRPJQKJOOISUQ", "POSTLPULUROPQTINQPUQIORJTPSK", "LJPRISJSLPOOJIQKNRNQNRLQKMOM", "OJNIMRUSMPTSUKLSOINKIPNTKINL", "QRKRTJMQLKRILIQTPSNIUQRROILL", "OKITJOKNNMKQJJLPIQQJORJNKSRK", "INOUQKMKKIJSONULTJMNRKSMRJNQ", "OLNSRQJPJJQSOQJIQUQNUPRPLNLQ", "NOPJUNLNOQJMOTKKTNONQKKTLNKL" };
        int x = 16;
        assertArrayEquals(new int[] { 1, 15, 24, 31, 5, 12, 17, 9, 18, 4, 10, 11, 13, 14, 21, 7, 2, 28, 22, 25, 29, 6, 30, 23, 27, 33, 3, 26, 8, 16, 20, 32, 34, 0, 19 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case25() {
        String[] score = { "HJHJICBADFCBHEEECFJFECHJIFG", "HCGEGIIHEEHCIEGAJFDDBFHICEA", "CJCHEEAFJFEFAFCGGEAJCBDFBAC", "GAIICCECAGIFEEFGFJBBFAJHGEI", "IDEHJIEHAHBJHIAFBAJFBDABJJG", "CCFDAGIJADIBGEIJHACGJFDJIGD", "GGHHBABHAGJFHEGHFHIGCHJEHGB", "AJCEGCHIGJCFBHEFHHGIJIHGBJD", "JFIJAIJJJEJHEGADFJJFABAGACI", "HJEBAACGJEEEEFJGCEJEDIACGDI", "GAAEIHECCBAAGIDCDBDGJEFFFFF", "GHABBAJICBFHIHDIFIEGEAAAJEJ", "IGBEAJBBGHBFGFCJIHHEBEJJFIH", "CCIFCCJAGACIJCGBBHEJFEGAICF", "BEFFHFIEBHJBBBHBJEBIAIJABED", "GGJAJIFDBIJGGFAJJHFEGJIBJBG", "HHCCGABDBFBJGDDBBFDFJACAHGD", "CEFCFAABAFAEBAHEHDABIIEBIFE", "ABAFDEAAEGEDAEBHBAIDFFAEJGG", "IJBHDEJFGDHEBECBCCACGDFFDCE", "FIEEGHCCEBJEDCDBIADADEDBGEC", "DJBAHGIGCHFAAHFAJICAHACBEAE", "FEABIHJDHHBHAEEHDCEAHGBEAJI", "ADFAIJIFAFAACJAJIFIAJBICGID", "FCCFBCCJIHJIDGECAEEGJDJEDHB", "GEIJCJFEIJHDHEBAIDHDDJJFDIJ", "HEJAHIHJCDJAEEHBBFCHJACJJFF", "BDBIADHICAFAGDAFBBJEJGCCACD", "DAHIFDHBIIEAHDGBIFBBAGIEGEA" };
        int x = 26;
        assertArrayEquals(new int[] { 1, 28, 6, 24, 2, 20, 5, 7, 14, 16, 23, 27, 17, 19, 21, 10, 13, 26, 0, 4, 15, 18, 12, 3, 8, 9, 22, 11, 25 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case26() {
        String[] score = { "HINIJIPMQLNKHPHNQMHLMPH", "NILIHPLMMINJJOJHKHQHJHL", "JJNQQMNPNIQQIIJPIHNQJQI", "QPJQINOIMNIKJHQQJNPLIHK", "MJLPMIKHQNILHJIOKKNHNOH", "LLKHNIQPNMQNPJOIOJHQPML", "LOMQNIQKLPNIMIQINOMMNMH" };
        int x = 21;
        assertArrayEquals(new int[] { 1, 3, 5, 6, 4, 0, 2 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case27() {
        String[] score = { "LLRVTMTVPPEHH", "OFVDDLOLMVLLF", "IJITLMVDLUVVM", "SUQPRTUOVLFTJ", "JVHKPROGFJUJS", "POKNQPMQKRRUI", "QLKQTPVKMUORE", "PLJSIMHNQNPJG", "ODGERNDFNKGUL" };
        int x = 6;
        assertArrayEquals(new int[] { 8, 7, 5, 1, 4, 0, 3, 2, 6 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case28() {
        String[] score = { "UVSPQVSUTUPPSRRVSRRQPPVPRURQVOTU", "UUPTTQRQVOOPVROQVPOVQUSOQPURQVSQ", "QROUPQVUTPQSPTTQUTOTPURQTRPOVUOV", "VSORVTSSPQSTTOQSQPVPPTSUQURSTUVU", "PRPRSSQRSSUPQVUPOUUSTVVTRSVUORQT", "SRUTRRVPUQOSROVVUUTPPQSPVURORQUQ", "SURVRSRPOTRSUPRUSUTPOTUPTPVPQQRU", "ORRSTUPPPTOTRPPURQTRUPRRQVOVSOVS", "RTQRTOTVPOROPRURVOUUQSUOROTRQOQT", "UVUPPSUUROSSVOQRSRURTOUUTRQQOOUS", "VQSPQUUOTRRVQPSQRSQQPQPTVQTTQSPV", "RRPTPTRTVQVQQTVPSPORUVPTPUOQTSQO", "TRTRPQPRTROTOSUPPRPOSQORUTUSPVUO", "OOOPPSRRVPTSQTTOUPQRVSQRVPUQUOUU", "RVRUTPSVTPUSQVPSTVSOSSUUUVTQPROP" };
        int x = 24;
        assertArrayEquals(new int[] { 11, 1, 3, 7, 0, 4, 8, 2, 6, 9, 12, 14, 5, 10, 13 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case29() {
        String[] score = { "VWVWVWVWWVVWWV", "VWWVVVWWWVVVWV", "VVWVVWWVWVVVVV", "WWVWWWVVVVWWVW", "WVWVWVWWWWVVVW", "WWVWVVWVWVWWWV", "VVWVWVWVVWVWVV", "VVWWWVWWWWWVWV", "WVWWWWWVVVVWVV", "VWVVWWWWVVWVVV", "WWVVVVWWVWWWWW", "WVVWWVVVVVVVVW", "VWWVWVVWVVWWWV", "VVVVVVWVVWWVWW", "VWVWVWVWWWWVWV", "WVVWVWWWVWWWVV", "WWWWWWWVWWWWVW", "WWWWWWVVWVVVWW", "VWVWVVWVWWWWVV", "WVVWVWWVVVVVWV", "VVVWVWVWVWWWWW", "VVWVWWWVVVVWWV", "WWWWWWVVWWVWVW", "VVVVVWVWVWVVWV", "VWWWWVVWVVWWWW", "WVWVVVVVWVVWVV", "VWWWWWVWWWWVWV", "VVWVVWWWWWVVVV", "WVWWWVWVVWVWVW", "VWVWVVVVVWVVVV", "WVVVWWWWVWWVWV", "WWVWVVWVVVWVWV", "VWWVWWVWVWVWWW", "VVWVVWVWWWVWWV", "WWVVWVVWVWWWVW", "WVWVVWVVVWWWVV", "VWVVWWVVWVVVWW", "WVVWVWWVWVVVWV", "WVVWVWVWVVVVWV", "VVVWVWWWVWWWVW", "WWVVVWWWWVWWVV", "WVVVVWVVWWVVVW", "WWWVVWVVWWVWVW", "VWWVVVWVWVWWWW", "WVWVWWVWWVWWWV", "VWWVWVWVWVVWWV", "VWVVWWVWVVVVVV", "VVWWVWVVVVVWWW", "VWVWWWWVVWVVVW" };
        int x = 7;
        assertArrayEquals(new int[] { 2, 3, 5, 6, 8, 11, 13, 16, 17, 18, 19, 21, 22, 25, 28, 29, 31, 35, 36, 37, 41, 42, 43, 45, 47, 48, 0, 1, 4, 7, 9, 10, 12, 14, 15, 20, 23, 24, 26, 27, 30, 32, 33, 34, 38, 39, 40, 44, 46 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case30() {
        String[] score = { "PIOJQMIJTNQMIQIOMOUQNRRMLLLMOIHRPTTQHM", "TMNKIOJLSMOTTPRTHQQRJKOJPKOPKISTNINIHK", "ROIQTKNPOSKMLMSJTMJULHRIMNUIMJULSUJRIR", "JTKQUMIRIJQTRUULLJHONTOULOORLOLIQSMLTU", "URTNLRMJKQRUQQMHOJRRORHONLMQTPLNPSIRLT", "KMHSNHJPPPTOUJOMLTTPKUSIORTRNKUSRQTJUR", "HJSPRUKNHKROINHNMOLSQPHNQHUMIJTQUPLQJP", "MLRUSSJSHMSKUUIPOJMTKKUPRKUKSTUIQHKKLT", "TJHLQJRLJJPQJHNKMTILHROPUTHJLSORIPTSOL", "HOSOSRLLIIROKKNOORNIMSTKUKMLNRLKRNRNIK", "SJLNINKILQHPNJRJTLNKLTLRMMKKQKRQTSMILP", "MTQMJPKTTUNJPRRJNNJLRMPJTUJQHJPQTHKNKR", "THTQKOHITUKSINTMLHJUKIPHHQHLMKKKKQHJIU", "PHRSSUSINRJKILUJJQMKLMIRKKKSKHMMTIUOLN", "PKOQJITROUKLPSHJOJQOMULSLKIRNLJHTSQIQJ" };
        int x = 1;
        assertArrayEquals(new int[] { 12, 13, 0, 6, 8, 10, 14, 7, 1, 5, 2, 9, 4, 3, 11 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case31() {
        String[] score = { "KFIEKOFRPFQMSRKEOIMNJGKI", "FQKEIGFKOOKKNFMKRPGORREP", "IOMPTIRIMLGETNHGNNJKFIFT", "TKSFEENGLRHEIJKGOTIQMTLH", "ETPQIMKTNHEHIEGEFEJFTQPR", "RGRJIQMETRRIFPFROTOPISJP", "ITEHESEFOHEGNHMHIKPHPGKQ", "KJKTHKGILFNHTHNROIGLRQFE", "NFJOGGOJNHNSQIQKHLGEESKF", "FOILPNGITGOJPLSKKLJMRLNQ", "JKGFEFHRQRKSFLINNIRPJGIF", "STJFMQMGSGNEJPTPMGMKENNS", "IQMNTEJKQRPTGRSGSSOGNGKP", "NJSJTTKTRORQLKRQLFOJGIMM", "IIMJJQOLPRTJLLGTHTHQNNOS", "NSLLOTIHKHNOIIEPPOFJNORP", "SQFJNREIFPTROMQKRFFLLKOJ", "RSJEPHQLLQPENQEGOKEGSKMS", "RMMFSOETFGELJRTQMFFEGPJT", "TEMIHQLIJRNRONIJMIOOTOSP", "RQLTHGOFSHHSEOLKJKPSETFP", "RFQKHPRQSNMEMHRNPNMGRPKH", "HIHEESGRKQSKQFPHNTGSPLRG", "FHQPIKQSRLGOMQSNLSOMOKII", "MGGLIPOKRIHINEKLESSLJQPS", "POLFTMFHMILKJMTJGSMNQNIG", "SIGEPEHPOSITLEMFHFHLPKQS", "OJFIMPMMREPPOQPEQNRJTIPN", "HHHQIFJJGFEEGTEOKETFHPHN" };
        int x = 12;
        assertArrayEquals(new int[] { 20, 5, 10, 12, 28, 3, 4, 15, 11, 18, 25, 13, 14, 26, 21, 23, 1, 6, 17, 24, 16, 19, 27, 9, 8, 22, 0, 2, 7 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case32() {
        String[] score = { "JQKQONOJQLKNLMNMMNQLLLNJLJPQNLQMLLMJNLNLQLPPKPOJO", "NQMQONNLKLNJNQNLOOOQKLPPQKNJPMJOJPMPQPKPKOJMLPQLM", "KJPLJNJKJQPOPPLPONONOKKJJPQNPKMQNNLMQJNQLQNQOJPLJ", "LPPLQJNLNNQJKLKOOPLJPNJPJKLMLJKLNMLNKJPOOQPMOPNKP", "QOLNOPPOJQPLOQNPLNNKPPQLMNJKNNJLNKLNMOLNOQQJOMKQN", "NQKPOPQLNNOQNOKKMNKLPJNPLKPOQNONJQLKPMMJOJKPJNLJJ", "LJMKLOPNLKNONNOMPLLJNJNOOLOOKPKKNMLNQNKKLJPJJOQON", "JKLQJJJQPLKLNKKQJLJJOQOPKMLMLMQPJMKKLPOQPNPQMJOJL", "LOLNNNKNMMOPNMOPMJLLKONNQMONLLMPQPJPOOMJJLNJLKKJN", "KKONQMNQLMNNKLNJNPJQMQKKPJPMJKQOQMNQMQLLLLNJPMKOQ", "LNKNJQKOLQOQMNNJKPQKONPKMMOPLNPQPMMOKOJNKOPONKQPM", "MOPNPOMQOQLLMKJKKPLLMNLKQMQQLJLKJJPQKNOQPJLMLKONL", "JNJPJJPJJMKNNLOQJJQQQLOQPKQLKJKMMNJJPNJQJQKQJKNKO", "MLLMOMJNLKPLJKOOJKMMPOMKNQJPLMPJLKMPMNOOMPQKLLPPP", "NQPLPJPQLKOMQKQLOJJNLNLMMJPQMPKMLMLMNKPNPJOLNJMOP", "KQQLOPJNKJMMLJJPOMJOLOLKLQKLQQKNNMKJMOKPPMNOQKNJP", "OOMNOQPJPMOQMOQOLLOKLQQOLJKJOOJMMPLOPOMMKNQLPOOJP", "JMKQNLJKOPJOMQMOMLMOLJQJOLPQOPMQQPNNNLOJQONLJOMNM", "PMLNLJQJQQOMQNPPMMMOJQLPLNNJNNQQNKKKMPOPJOMMNQQLM", "NPOLJNJMQQKQQQQOPOLLLOQJKPNKMNLLMNQKPKJKLJJJJJLQM", "MPKMKLONLPJONPLONNJKNOPPNJKPLNKJJLNKOOMQNLLMPKOKN", "KQOPLMLQOMNQNQPLQLQKMPPOLQMLMJMJPNLPNJMMQJNLJKLML", "LONLLLQMPOONPLMPOJPNLQJONJOKOKNLPKPOPMMLJMOPPLMNN", "MKLJMQOPNNPOPPOOQKKLQMOQQOKMMPLOJQPMMKMQJOPMKJPOQ", "KOJJLOMQPPPJOPJJMLNONOLPLKOMNPKJOLKKQMKNNPMPJNJKN", "MMOMLMKPOQKNJLQLPOPPNMNJMPOOJNNQPMPJLNPOLPJNPQLNO", "OJQJLNOQLKMNNLNPKNKQNLOOPOOPPKQLPLMKOQPQLMLMNPJOP", "PJLOMJMNPOJOLPKQLOLNQLOMPNLOMNJJPNKOOPMQPNPPMJQOJ", "NOLLMKPMQPJKJMKLKLKMQMNNPOPKNKPOPLOQMLKKOKJLOJOQN", "OLMLOPOKNOJMNONOQPJJJPPOJJOJMLJPJMOQLNLJQMJPLPPLQ", "MMOOLQMJPLOKOQKPNPQOOMMJOJJJOLKQLJMMOOQOLPQPQOKNN", "LPONMQQJMJNJPJJJPQJPMQKPJLKMPPOMKKJOJKLQKJMQPKNMN", "KNMKPKLKQNPJLNMNLPMKOOJLPPQOOQLNMQNPNKNNLNNKOKPOQ", "ONQKQPPOQPJQNOMQPMNNJPLLQQKQPPMLJJPLKOMNMQLOPJKON", "NMMKKPKPJLQKLJNOMJPKKLJOLPJLJOMPPLQNMKOPLQNKPKOLO", "PKOMJQJMLMPPQLNJKPJPJJKKJNNQLPJQQQLPJNLNLLMMLOKOM", "NJNNMLNLOJKQOLMPOKQKPJQPLNONPQPMQKQNKKNOJOOMQNJMJ", "MLKOOLLKJPPKKNLMOLJKMPKQNNPLOPKPPMQNNQJQPQLNLOQKQ", "MQPJNKMNQQOPLPMLQJKNQPJJQQOOQJMQKJLJJMMPPNOKQOKPO", "KQLPMPOMLLNKKNNMNPOOMOPNKLQKQNOJLMKNQPKJJPKJJPPNQ" };
        int x = 3;
        assertArrayEquals(new int[] { 23, 24, 26, 38, 6, 32, 33, 34, 2, 3, 14, 15, 19, 22, 28, 29, 13, 20, 25, 35, 4, 8, 9, 10, 11, 16, 18, 31, 36, 27, 30, 37, 5, 12, 21, 39, 0, 1, 7, 17 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case33() {
        String[] score = { "MIIKJHILMKMNMLNILMHNLMMLMLLH", "HIIIKKLMMNJLLMJJHIHILMNKJHIM", "HJINIKLMHHNKHHMLIKNJINJLHLHM", "LKJIHJMMLHLJKKMHHILLJLMKNLHJ", "MMIHJLIMLNHHNLMNLMKMMIKNMJML", "LIKIMIKMMIIKKJIKKJINNNMLLNHI", "KJJJHJKJKKMKLKJLHLKLMLKJNJLH", "HHIHKLNHNNIMJJMJHIMKNJMNHJNI", "MLMHKIKKHLIMIHLMLMHHHNNLIHLI", "MMIKNNIJHNMHIHIJJKHJJHKLNJNK", "MHNNKJLLNINNHHLKKLMMNLJJHHNH", "MKKLNNIHHHHHNNNMKILLMNMILKHJ", "MKIKNHKNHHLIJIMJKMJMIMMIMLMH", "LKINNLNKLIMHKNHMINLIIJMJKHLJ", "JNIIKNIJMINILLNHHHHJNHIKLKKH", "IIHNJLILLJKMHMLHLLKJMHILMLNK", "NHLJMIJIHJNNHKHIIILNMMKJKIIK", "LNHMHMHIJMLMIJHNNKKNIMNLMINL", "NHNHMJJKMNLKJMMLLHHJLMJLNKNM", "IILILKHJKJHJKJJLNHMJIJHKJMJI", "KHKNIIMINLHLKJILJLLILMMLKNKL", "MMHHLMNHINLJJNHKHMILJNKINKMJ", "KHIKINNLNLJMJJLJKLLIMHIKLIMH", "HJJKLLMNNINLILLNMLIIHKKKJHNH", "JKIKKJLHIMLIILMLIHKLHLMKJLMJ", "ILJHJKIHMILNKHHHNHJMHJMJIHIJ", "HHKKIKMLLMLJNIJININJKNNLMJNM", "NIIHIJHLILMJJJLMMNKMJJKHJJNH", "MHHLJJMIILNHNJNNLJNHLIMNJMHN", "MNLLNNNHMMLJLIJHNKJKHNJINKNJ", "IHMLIMJLJKLMHMNINJIJLJLNKKLJ" };
        int x = 11;
        assertArrayEquals(new int[] { 4, 9, 11, 13, 28, 12, 14, 24, 3, 19, 21, 26, 27, 29, 2, 5, 6, 18, 1, 20, 23, 7, 8, 15, 17, 22, 30, 0, 10, 16, 25 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case34() {
        String[] score = { "JKIFHJKHNJHL", "KLNGHHHLFMHM", "NFLFGHLJFMHF", "NMNGIMIJIJHM", "MGLGGKHFMNNL", "GNFGFGMHFMGF", "NNLJHJHFFKGI", "FJJJKHFKFFHK", "LLHJHJMMHNJM", "MNJHLFHMJGHF", "KLFMJNIGGFFH", "INHHIGFJLHIN", "HKJFJKJGLHKL", "MJFFIFLGMGKF", "GJKHMGKFNMKG", "NNNHMHLGKGLH", "JNLFFILJNHHI", "KJHMJHHMNKFK", "JKIIJLFNLMII", "ILJFGHFLMMNH", "FGIKLLIMGMHL", "MFKMJLJHKFNF", "HGNNNJGHKMFM", "LMFIJMNMMHFH", "LJKKJHJLHGFI", "FIFJHLLNMFNF", "GMJJHLMLGGGJ", "FHNMFMILKNJH", "LKKIMIIIGHIK", "LFLHHMHJMKFI" };
        int x = 11;
        assertArrayEquals(new int[] { 2, 5, 9, 13, 21, 25, 14, 10, 15, 19, 23, 27, 6, 16, 18, 24, 29, 26, 7, 17, 28, 0, 4, 12, 20, 1, 3, 8, 22, 11 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case35() {
        String[] score = { "RRXWUWPX", "XVOSPVTR", "WPWXSOPL", "ULUVLORR", "TVMUNWSU", "NPWLLNMV", "QRTLVUQS", "XSWOTRVW", "PLMWRXTV", "MVLVLVVV", "WLLQVVXT", "XMMUWXSR", "NORNLXTO", "PXQVMMQM", "XVOTQWVR", "TXOMNWPV", "MQMMNRML", "NQNWSQMS", "LWUQVXNO", "PULXUTML", "RWNUMWNT", "RQVVMWUR", "XVUVWWNS", "ROTROSMT", "WPSWTLTS", "TTUSLMUQ", "SULVMRVW", "MWSVNUXX", "QNQRQOOO", "RUOOXTPW", "LWUMNUPX", "TUWUWWNV", "RUTRXNTO", "PMQSWMUO", "MVWVLMVR", "PWQPVQSP", "USNXNVSM", "VUTNNRQP", "VVRXLPLV" };
        int x = 5;
        assertArrayEquals(new int[] { 24, 13, 25, 33, 34, 5, 32, 2, 3, 28, 38, 17, 35, 7, 16, 26, 37, 23, 19, 29, 6, 27, 30, 1, 9, 10, 36, 0, 4, 14, 15, 20, 21, 22, 31, 8, 11, 12, 18 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case36() {
        String[] score = { "TSUOVYWPPYQXSOOSQROUYLNTPPYYRUPU", "UPPQYSYUTWVYNVOQYOUSSUMNVPUYURRT", "LXTLWTOPPYXUQLPYNTSNVVQXVRRYUVVT", "OUPXWUZMUUYVSZRVXXXSNZURUYOZXUZQ", "NRQXTZQNUZPPPZLPTLQNQPTLNNQMXPVX", "VRVZOTLYPYZPPYTXYWOSRZMRLTZTRZYW", "OPNLRZNYYTVLPZULPRMTWWQWLYQPTLVQ", "YWMMQNTLWOZVMOOQQZTMZXSPSSYOMQUL", "OXWRRXYZYVSLNLZSWPRRTSSUMMMOSPOU", "RNRYVXMPOPNMYWLSWLMZPRNMLRWONRRP", "WRSNLNYPVMMRRPNZWMQZQMPLRVZNRMXY", "RPURQLUVNSZVYNMXZSWURTWNVZTROQLX", "NRXXQZRNSXSWVNZTXPYPRXWPQWYVWZLM", "OVWRRTNQUQLMLRSLXYVTZPTOWZYPOYPZ", "QNTOQPRPXVLNXLOMXVVXLUVNUMXQMYPS", "MMOWLQSNTSVTYXRZZXUNNQUQOOPLQPML", "NZSOMQPUUSWPZZXMRSNRLPVUMXQYSPNQ", "YLSTUUQPSLYURVOSYQOVSXXVLWNUXZPW", "LMSSZMUQOYUNXVWUTURXSPWNXYOXWZPL", "QXSOLPMZZOTTYOTRSQQSXXYWUTPZTPVY" };
        int x = 26;
        assertArrayEquals(new int[] { 8, 17, 3, 18, 15, 19, 4, 6, 16, 2, 11, 1, 9, 14, 0, 7, 12, 13, 5, 10 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case37() {
        String[] score = { "SURWTTTURRVRTSUURRSSWSSUSWRTTTUWU", "SWTUVSVUSTTVUTWWSWUVWTTTUWUTWRWWV", "VVUVTWWSSRTUUTVVWURWSVRWTSUUSWVUV", "WSSUTSWWSTWURWUTWTVWWRSVRVUUUWVTR", "WVTSVWUSUWVRRVURRTVUVTWSUVVUWSVWT", "VVRWUUVTWUTUWWSVSVUWVTRUSWWSTVUTS", "UVRVUSVSSRUWUTWURWRVWVURWUWUWVWWV", "TVTUSRVTTURUWWVRWSTUVUSWSVSSTURRU", "WTTUWVRSRWTRWTRUWSTTTRSVWRURVSUTW", "RVSUURVUVSUTRVWRUSVRSSVURTRSSVURW", "TUTWVVSRTWWSWUTRSRUTTSWUUUSWSTTRU", "SVRRWVSSUUSRVWWRVWWRRWSUSTVWWVTWR", "WVUSVTUSSUURSRWUVWWTSRRUTSWVWTWSV", "TWRRRWVVUWUUWTSVTVVSSUWSRSTUVUVVT", "TTURUURRTVVUUVRUVSRVRVTUVWUSTSVVS", "UVTUWVURTSVVUVVRWUSTWRWURVWWVSVTV", "SSWTRWTTRURVRUSRTRTSRWSWUVWTRSURV", "VVVSTURRRWUUTTUVSTVSRTWUSTUSTSRUT", "VRRRVSVTVRTVUTUTVURWVSRRTVWTSRWVT", "VSTSWTRSUSUSUWSUUSUVURRUVRWUSURSS", "UVWRTSRTSRRVUTSSTTRTWTUWWRRSSSTTS", "VSSVWSTUWWUWSRUSTWRURWTSRTUSWVVWV", "WWTTVUTTRTRTWTSRSVWRWTTVSRSSSTTUS", "RWVVVSWURUURUVURRVTVSWUVVUWWTWRTS", "URRUSTTUSSSVTTRVTVVWTRUUSVWUWTTVT", "SSRUSRRTVSRWSUWWSVWSRSUUURUTRWWWS", "VWRWTTWTRUWVSUTRVSWRWVVVVUVVURWWR", "UWTWTWUSRSWVUSSVTSWRSSSTTRWURWUUV", "WSSRRRVTTTRURRTTRRUSUWWWVRUSVTTRS", "WRVTSWURRVSSTWSTVRUVSSSRWSRTTWTRR", "VTSWRSWTUWUUVSSUUUTUTUTTVUTWVVRRT", "RWRRWTTRWSWVVSUSVUTWSURRRUVTTSUSV", "VRRTRRSRVRUSSUTRURVTRUVSVTUVUVWTR", "SRRUWTVSSSUVURRSRRWWVSVUTWVRSVSUT", "WWWVUTTTWRUUSRRUSSVTRRUSRSWWURTRV", "RVUUSWURVSUVTTWVTTRUSSSSWVSWSWURR", "RTUUWVUUTTTRVUSSWSSURTSWWSUWRWSTS", "RTURRUWSVWSWSUSSWTTUTVVWWSRTUTWSU", "SVWVTSSUUUTVUTRRTVWUUWUSRVWWSRVWT" };
        int x = 28;
        assertArrayEquals(new int[] { 16, 25, 27, 36, 2, 9, 10, 18, 19, 20, 22, 33, 35, 38, 0, 5, 7, 14, 17, 23, 29, 31, 3, 26, 32, 34, 37, 8, 13, 15, 28, 30, 1, 4, 6, 11, 12, 21, 24 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case38() {
        String[] score = { "OPKYKNMSHXJWWGHVUVTSISOVWQPQTRUX", "ZWPWQIIMZPNINYQHXHVKYQHNZOUHJOQK", "RXLVXVITZYMSLQJWRMNLLRPURKJHVXRL", "XSMZXUSSJTWSHUOIYQYPUIKZUSSHWWWQ", "NTNJSSTTJHUNPOLGSNZOLORJZGHSUMRV", "HTJVHQTZQWHHJGORGUOXTRXYHGGZXLHK", "OKVPMNKNNJOKWPHYWRMIJNGZUHRYITOU", "IYLRNIYXMOXHWQHMHQQRPOYIINXJSLRN", "LZYQYHSZGOTRLPVUQSPSUYKUGUVMRTWR", "THJOJZTZXRPVTXKSPXRIVIRRYIJTUONX" };
        int x = 14;
        assertArrayEquals(new int[] { 0, 6, 7, 2, 9, 4, 3, 5, 1, 8 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case39() {
        String[] score = { "USTSTUUSSSSSUSTTUSSTUUSTUSUSSSUUUUTUUUUUSSTTUTSST" };
        int x = 17;
        assertArrayEquals(new int[] { 0 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case40() {
        String[] score = { "FGGGFGFGGFFF", "FFGGFGFGGFFF", "FGFFFFFFGGFG", "GFFFFGFFGGFG", "GFFFGFGFGGGG", "GGFFGGGGFFFF", "FGFFGFGGGFGF", "GGFFFGFGFGFG", "FGGGFFFGGGFF", "GFGGGFFFGGFF", "GFGFFFFFGGFF", "GFGFGGFFFFFF", "GGFFGGGGFGGF", "GGGGFFGFFGGG", "GGGFGFFGGGGF", "GFFFGGGFGFGF", "GFFGGFGFGGFG", "GFGFFFGFFFGF", "GGFFFFFGGFFF", "FGGGFFGFFFGF", "FFGGGGFFFFFG", "GGFGGGFGFGGF", "FGGGFFFGFFFF", "GGGGGFGFGGFF", "FGGFGGFGGFGG", "GGGGFGGFGGGG", "GGGFFGFFGFGF", "GGGGGGGGGFFF", "FFFFFFFGFFGF", "FFGFFGFGFFGF" };
        int x = 0;
        assertArrayEquals(new int[] { 0, 1, 2, 6, 8, 19, 20, 22, 24, 28, 29, 3, 4, 5, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 23, 25, 26, 27 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case41() {
        String[] score = { "GNIGFLFFJFNJEJLFNGLJMKJLHELHKFNNF", "IJJFEGLGGIJIMEHHFKMFHFJMHILEHGHGJ", "EFFEKEIILIMHJFMLLHLEJHLFHFFGLKMGJ", "EIEHKLKGLIHLNNFEGEMIEKIENFNNHMJHJ", "EGHKLIFHILLGGEHGJEKHHFMMLIJFNLMFN", "IJEHJFFIMEJKIKFIINGKKENJMEKEHJGEH", "MEHFLLEFEHKLGEHMIJFGLHKHJLIHJEIHM", "FIIHMNFLGGJMGJLFHMNIGHJKJNNGLEKEK", "KIKIHKNEJEFJELKHIIKHKIIEJJGLKMLGK", "LEFGMJMNJMLNGLJFIKJGMMHNEMGLFLENF", "JLKGLFIEJIGNKGNIKHLIFIGLFMHIMJIIJ", "LHHINKHGJNNNJFKEHLHMKHGJFHENNLKHL", "HNLJEFLJGFLNKNIFGIELHGHIELLELFKIE", "MEKNFEKGJELIJMFLMNMEKILGFJIIINGFM", "GLMMHFMFELLGHFIFGJKEMINJKJJGLFLNJ", "HMIFGKIGHIMNNIFFJMFLMKKNFHHMNNIGM", "FNFFKLLNMFMLINGMHFHKEEGJFINNHJJNJ", "JLLJIKIJNIJGINHJNENIFKFKKKMKEJNII", "GFNMNGKJKLIMKNLNIMJENFNIGMLHHFEMN", "EMEMNMFHKGGGJKGNNLIJLEILKHIINFGMG" };
        int x = 0;
        assertArrayEquals(new int[] { 2, 3, 4, 19, 7, 16, 0, 14, 18, 12, 15, 1, 5, 10, 17, 8, 9, 11, 6, 13 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case42() {
        String[] score = { "TUTVUTVVVTTUUVUUTVTTVTUTUTTVVVTTVVVTVTVVTUVUUUVUT", "UUTTVUUUVUTVVUUVVTVVUVUVUTUTTUUTUUUVUVVTVVTTVUTTT", "UVUVVVTVUVUTVTUUTVTVTUVVUVUTTUUVTTVTTUUUVUTVTVVTV", "TUVUTVTVUVVVVUTTTVTUVTUVTUVUVUTUVVVTVUTTVUTVUVUUV", "UUVVUTTTVTUTTVUUUTVVTTTTVUVVUVUTTTUTTUTVVVUVUVVTV", "VTVTVVVUVUVVVUVUTUUTTUVUVVVTVTUVTTUVVTTVUUTVVTTVU", "UUUVVVUTUTUUTTVUTVTTUUTUTTTUVVUVUVVTVUVUUVVUTVVVU", "UUVUVVTVUUTVVUTUTUTVUTVTVVVVVTUUVTTVTTVUUVVTVTUVV", "UTUTUVVVUUVTVTVUUVVTUVUVVUTVUUUUVVVUUUTTUTUTUTVTU", "VUVUTTVVVTUUUVVVVTTVVUVVUVUVTTTVUUUVUVTTUVUUTVTUT", "UTVUVTVVVUTVTTUTTUUVTUUTVUTUTVVUUTTTTVTVTVUUVTUUT", "UVTUUVTUVUUUUVTUVVTUTUUTUUUUTVTTTVVTTUTUTUVUUTUTU", "TUUTUUTTTTVVVUUUTVUUTUVTTTUVVUUVUUUTVUVUTVUUVUVVV", "UTVVUUTUVTVTTTUVTVVUTTVVTVTVTTTTUVUVUUUUUVVTTUUVV", "VTUVUTUUTVTUTVTUUUVTTUTTTUTUTTTVTVTTUTUVTUVUVTUVT", "VVUVVUVTTVUUVUTTVTVTVVUVVUVTUTUTUTVUTTUVVTUTVVTTU", "UTVTVUUTVTUTUVUUVTTUVUVVUUUTVVVVTTVUVUTTUVVVVUVVU", "UVTTTTVTTVTVUVUVUVUUTVTVTUVTVUUVUTVTVTUVVUTUVVUUU", "TUUUTTVUVTTTVVUTTTUVTUUVVUUVTVTTVUTVVTUTTUTVUUUTU", "TUTVTVUVTUTTUVVUUVUUUUVTUUTTUVUUUVUUTTUTVTUUVUVUU", "TTVTUUUTUUTVVUVVTUUUVVUUTTUVUUVTTTUTUTTVTUTTUVTTU", "VTTVTVTVVVUTUVVTVUVUVUTVUVVTTUVTTUTVTTTTVVUUVVTVT", "TUTUTTUUTVVVTUUTTTUUTVVTTUUUTVVVTTTTVUVTUVVTUUVVV", "TTTUVTUUVVVUVUVUUVUTVUUVVTUVVTVVTTVTVUUTTTTVUUUUV", "UTUVVVUTVTTTVUTUTUUTUUVUTVUVUVUTUVTTTUUUVVVUUTVUU", "TUUUUVVVVUTUVVTUUUTVVTVTUTTVTVUVUUTUVVVVUTTTTUTVT", "VUUVUUUVUUVUVTUTUUVVTVVUVVVVVTVUTUVVTUTUTTTTVUUVU", "TUUTUTTUVTTUTVTVTVVTUUVUTVUUVUTVTTVUTVVVTVUVVUUUU", "VVTTTUTVVUUTUTVVUVTUTVUUUTVTTVUVVVTTVTVVVTVUTTTTT", "VTVVTUVUTUUUUTTTVUVTTTUVUVTVVTVTTUVTVTUVTUTTUTUTT", "UUUVVTTVTUTVUUVTUTTTUTTVVVVUUVTTVTUUVTTTUUUUUVUVV", "VUTTVUUTUVUUVUVUVUTUUTUTUTUTTTVUVUTVUUTTVTTVVVVVT", "UTUUUTUTUTUTVVUUUTTVUVTTVVVVTTTTTUVTUVVTVTUVUTTTV", "VTVUUVUVTUTVUTUTVVTUVUVVUVVUTUTTUVTVUTUVUVVVTVUUV", "VTVTVTTVVTVTUUTVTTVTTTVTVUTTUTVUUVVTVUVTVVTVVUVVV", "VTVVTTUTTUVVUVVVVUUUUTUTUVTUTUVVVVUVUTUTUTUUVUVUT", "VVVTUVTVUTUTVTUTTVUVTVVUUTTUVTUTUTUTVTTTTTUVVUTTU", "TTTUTVTVTUTVVUVVVTVUVTVUTTTTVUUTVUUUTVVTVTTVTVTVV", "VTVTVVVUTUVVUUUUVTTUTTTVTTVUUUTVTTTTTTVTVVTUVVUTV" };
        int x = 42;
        assertArrayEquals(new int[] { 1, 2, 3, 5, 17, 18, 20, 23, 25, 26, 29, 31, 34, 37, 38, 4, 8, 9, 10, 12, 15, 19, 21, 27, 30, 32, 35, 36, 0, 6, 7, 11, 13, 14, 16, 22, 24, 28, 33 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case43() {
        String[] score = { "EEGMLIDJKIILGHKIMJGGMMEDKGFDJEKJFDLFKJDJHGFJJFGJLF", "HEKMGJDLLMFFFMMDEEEMFMIGJJFKDKEMLFJIHMLHLGEFHFMIIF", "DHMJLLHMHLHMFELGLIIGFIEHKGDMIFKEJJIEIDKHKEIHMEJKLL", "GMKDLDKFLIFFDKFKMKMMMLEMKDFKELELFEGGJHDHFKHDEFKKDE", "GDKKLDDEJEIFGHHKLFMGHEMMMDHJLLKGMIELGGGMFIMJJIDJJH", "IHLKMHEEGHJDIGHGFHKEEMGGIDKLGDDKLEIKIDLGFMJHLELLLE", "GHJHHLDGGEEGLJJFFLLFKLKKIMEKHFDDHLILJJEJMFJIIGFDIJ", "FFGIDGELLFHKEMDGGKGDDEGLEDHGFJKFGMLEHELKDFMKIIEJFJ", "JMKHJEMMMDKLGMGKLEDEGKMFHMMMIFLDILMJIIKELKMLMDKKDF", "FMDHLMDJEMKJLFLKEHJFMMIFMKEEJEMKKDMJJMJLIKFKJGEJHM", "DLGGLIGJKKHLHGKJGDHJMDGJFMHKJGEFMLGJEHKKEKEDLIFDKF", "ELMMHEIIEDFMEIHGMDKLLDFHFFHJJJEEGHHFKDKGEJLMLFFKMI", "JHHIEDGELMLIEKIGMKLGIMEJGMGMIEFMLFIMJHDKJHJGEEHIFG", "HMIDKHHGMKFFLEDJEDEIJFMGFGILJELKHGGMJJKLDHJJLDFMEH", "FHLIJKIMIMIEDHKDDLHMKGIGIFMGIGMMGKEJMILLGHDIGDFFKM", "KKKDHKJIMFILFGKKMLMFLFMHFDLDHIILELLFDHHDLHGJJIIEEL", "DMGDDKGDFMLKFEHJLKJLHHLEEGELDEFIEGHDFDEHLJFDJHMGDD", "FIELHJKMFHEMKDGIFMDMEDDIFEMELKMHHLIKMFKGJMDIMGLEGH", "DHEDFMJJHIMDDEMDGJLLILIKDJLHJLJGEMDLEHFFGHEDIFFHFD", "GIKIGEFHFHEGKLFLFMDLIFKHIFFGIMKGDEIIIHMFDEFKGGFIGJ", "EDILDDELGLJKKDFHLDDEGLJEMDJMKGJHFKELJJFEGHHLHJKGJK", "GILHMLJEGHHLKFGHKFLEEEKKDJLLHIMKEIDGFLEFDKJFJGIJLH", "MKJFGHDJHFKIJLEMLMLJJLDGIIFIJJHGDGFKIDKDGJEGJIFHHM", "HMJEDJMGJILHFJIHLGIGKEDLKKHLGMLHKJFLGFHGFEEDKIEEMF", "MFJDKIFFGJFHEGMJIFDGMHEHFKDEJFJLKGHDMJJDGGDHJLELLI", "EGKGJDFFHDJKDDGLJIKEHGLDMIHEDKMEEIIMLFFJFEHGMFHKJE", "DKHGHMHLLEDFDEJKFIJLDGKDJFHGMDMLDHHDLKHJKIIGFEEJIE" };
        int x = 16;
        assertArrayEquals(new int[] { 14, 1, 9, 13, 5, 6, 17, 19, 26, 7, 10, 18, 24, 25, 21, 2, 4, 8, 16, 20, 22, 23, 0, 3, 11, 12, 15 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case44() {
        String[] score = { "H", "K", "N", "O", "K", "K", "F", "G", "E", "H", "E", "N" };
        int x = 0;
        assertArrayEquals(new int[] { 8, 10, 6, 7, 0, 9, 1, 4, 5, 2, 11, 3 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case45() {
        String[] score = { "IDHFEHIIGBCHGGGB", "FCIAIEDCGFIEIICF", "AGACCCADEEAFIEID", "CCCIDFIDFEIAGGCG", "GGDCCEHAHFFAAACH", "BGIFEECFAHFGDEAG", "CDCIHFHADADAEGID", "EHAEDGFHCDIHDGID", "IDCEFEHIGDBFHBAF", "CFAICGAHFCFHCBEB", "FDFFEABAHEGDBFCG", "DFADIFDEEBFDIHCE", "FEICDACBBGABFECB", "FAHCADACBCIGHCEH", "IFBCCDDGIIEECBCA", "CGGFBIFHEFAAAFDI", "GHECGIEBBDCGGAIE", "HHDFCFEAFBHAFFGD", "IIAGHEHEEAAHGDGI", "IFIAHGIGIEEBFAAI", "IEDHGCDCCDABGCCB", "BICIBAGFEIFEHAEA", "FECBHIFIIIFBHAFA", "FHHEDEIEFAFHGDHB", "BABCGCEAICDABFGG", "HABGBECIAADDIHCA", "CAEABBFGDIBEAAAD" };
        int x = 15;
        assertArrayEquals(new int[] { 14, 21, 22, 25, 0, 9, 12, 20, 23, 2, 6, 7, 17, 26, 11, 16, 1, 8, 3, 5, 10, 24, 4, 13, 15, 18, 19 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case46() {
        String[] score = { "VVUMKUTTKTROOMSRKOQQTKPSUVULPTVNPPKKNORMVNQTLONMK", "OQSSMNMKSTNNTMMNTTKSPULLMLLULKQUSLTSSLRUTOVPMLMSV", "SSKSOTQTVVKOKMQNPMQLNLPLQNQMNKPRULNQPTTMMRPKLVSNL", "VTVPMPVMLRSRNOLKSNQVVUKVVURQMTUKRQMNNQSSLTNNLOSML", "OOSKQUKMUNOMRTUSLVQRLPKVPUVKNOVOUQOOQRQNRSVNSSMRQ", "MMLRNSPMSLLVKUQKLTNSRQNNTVQLQQQRRTSURNNQRSTRLRVMQ", "VTOKKKPTSNRKSQSSTPOTVMQKNVVRNRRTTVKSNOULSSROMSLKS", "VSOMMTTORRKROOLKSRSRSOMKRNQKKPQTKNLRVMNNVQPPMQOTN", "MKQMSMRKTVPTTKLUPQRLPTQSOUOOKKLSNNSMQSLROMVSOSMTQ", "UVSPKOOTMQOMLRRVKTQKKVRPKTSNNVNPVPTLVNRVVNNMSKMUL", "VQMLUOQPRRLLTNKKVSRSTORTTVKRQSVTOUMUNMSSSTUNOOSNK", "PRQKNQURSRPVKOKOURLVKRNTSMVPOQLNPVVPNUTVNUNRQUUUL", "OQLRTKUKOPVMTUTMNVKUQKMRVTTMMKRLMLSPSMSQQLMTPTLUK", "VQKURVKSMUPUQSOTTQOUSNKRLSSPMLMQSQQVSMTSKVMPMPLOL", "SKUUOONRRQOLOPUSSROMSVURMLRRRKRSRLQLNKPVOLQSRUPMQ", "OPTRMQPVRMRVRLSOVUQUOSOKNQPUUUOQPQRMUQRUQSUPLLMVL", "LPPMPLKUTKSMLQSQLMTOOUKQSQMSLKPTMPSUTKLMUNSRULQTS", "VOVLPRKKKKVQQLLVVNKVLRONURMRMORVUQLRSSRTQVLPOUTKQ", "SMMUMUNLVMPORLNTPLUMVPNQUPQRKTRRVMLSLMSMOUQUVUNUL", "NURLQPLLQMNVSPMTLTLOMOOPQUSLSSVPQRVRQUUMOSVPMPTNT", "OVUOMQSLVTMRSLQLUKOOTNLUMURRTNOVOSUNQROPMTKVNLNOL", "NKTOKNPMTKNRPNPTUVRNUVNVOPTOKKSTRQPVPTMMQLMLMPRSP", "LLMLRPLVSOVVPRSQPOSQTMKTTNVQUMTPKMUVQMQMLPUSMSRNO", "KSTTVPNTSKRKUKKSTVRUMVUOTMNRNRQVPMMLNQNLRKNQUQURP", "OQULSLLSQNQTNPSNSSQNRVSSNTQTLRSRSVQPVLRPNQNQKRVNU", "KQKRUONNMQMRPPQUQPRPMTLLRMQMLNLMVORSKLOUKMNQKPRRN", "OLLVMLKQOOTQSUUTMMSRSMVMPVNPSNULLPTRVPRTVRTNKOMMP", "PORMVKNTVKVOUQQLKSQLLOSSPLVKLUVLSKVUVKRONRQKTNUVU", "VPRKRNPUPTRUSTKVKONVNMKRVMVOOOONLLRSULVVUMKNLSSRM", "KVMOSROQRNUOUOTPTSQNNKUONSVNNMUOKRKUQVOSLNTSMLTRL" };
        int x = 36;
        assertArrayEquals(new int[] { 25, 18, 0, 3, 6, 10, 11, 14, 23, 2, 21, 4, 8, 19, 20, 22, 29, 5, 1, 12, 13, 17, 16, 15, 28, 7, 9, 24, 26, 27 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case47() {
        String[] score = { "FJIDFJILEEFCHMC", "IICKJKHMFKEMLEG", "KIKHHMCLHLEJDGC", "MHHJFHJDCFGMICH", "DHDCKDGDKDECIJC", "HIDHCIIKIGLJHHI", "HMDFGJHJIJGMEKE", "FEDGFICGLDGICKL", "KFDLDCFCJMHCHFI", "GDMHHDCHJEECLEE", "CGKKHJLCHLJJFJH", "CKIMHCHHMDGHCCD", "JJGIFGKIEIHCKDD", "KDLJFGJLCHDGMJJ", "MMKMKGGDDCFHGKF", "LKEEJIMCFKKHMFJ", "DJJGIJKEGFIKKLM", "GJICDIEGGGDCDGF", "MCDDCGEMFFLMJEE", "FDDJMIDIHJEHMKC", "DFIGJJHIDHDFMFE", "ELGKEEJKEHMGCKF", "DFFEMCCFHKGJLCD", "MIMJDHKFHMDHKEH", "IGDMDMMMEKGFEHM", "LFMMEEKMDMHEFHE", "HLJFHFDKEHFKKEM", "HHLFMDGMCEJDLID", "KDICFFKCLGLEHCH", "JMIEDGGDLKDIDML", "HGMGCJEFGDEGLKL", "JIFMLECDFEFKMDD", "LDHFDHICGCJJJGG", "CDIHLHLEFEKHJHJ", "IIGEJCJMLEKMELM", "ELHGLEDHHKGDIII", "EHKLEFHGCDLEIIF", "KLCIMIFLJFKLJDC", "CFIIILLICIGGIEK", "EFHDMFIHKKLHMKK" };
        int x = 7;
        assertArrayEquals(new int[] { 8, 10, 15, 28, 32, 3, 4, 14, 29, 31, 16, 33, 22, 23, 30, 7, 17, 36, 9, 11, 35, 39, 12, 19, 20, 38, 6, 5, 21, 26, 0, 2, 13, 37, 1, 18, 24, 25, 27, 34 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case48() {
        String[] score = { "VXRV", "YRUY", "SXXW", "WUWU", "RWVY", "YVYT", "VUXU", "RSXR", "STWT", "UTXX", "YXRY", "SSRV", "USRX", "UWRT", "SYUS", "XUXY", "XUVY", "XWSY", "YTUT", "UYSU", "UVSY", "YXTU", "RUSV", "XXXR", "RYSX", "UYXU", "TTRX", "SUTV", "XRTR", "WVUU", "TWRU", "RVUT", "SWYT", "YUYU", "WUXT", "YXRU", "RVYR", "SXRR", "XSXS", "XYRW", "WYWS", "USSS", "WUUR", "SVUY", "YWVS", "SUXU", "RUVU" };
        int x = 2;
        assertArrayEquals(new int[] { 0, 10, 11, 12, 13, 26, 30, 35, 37, 39, 17, 19, 20, 22, 24, 41, 21, 27, 28, 1, 14, 18, 29, 31, 42, 43, 4, 16, 44, 46, 3, 8, 40, 2, 6, 7, 9, 15, 23, 25, 34, 38, 45, 5, 32, 33, 36 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case49() {
        String[] score = { "PPQSOOOTSQRRROTSPSTQ", "OPOQPQPOSTQTRORTQTPS", "QSOTTSQTOORPSOSPRSOT", "SRSTTSRQTORROTTQOSQR", "QPRQSSRSSRRQQOSTQTOS", "OPRPRQTTTRTQQQPOOPQO", "QSPORPOPQOSSTTTQQPTO", "QTOPQOSPTSPSTSOTPPPQ", "ROOSSRSSQRSPQQOORPTS", "QQQPRPORPRPTOSSPORQP", "RSOQOORSPPPOPOTSRPOS", "OSQPPQSPRRSQPSTSOTSS", "RRSOPOTSSQTSTPQSPOTR", "PQRQRSPQORSQTPQRQPRQ", "SQOSQRSSRTTSQTSPSPSP", "SPSPORTSTOSSTSOORPTS", "PORQRRROPRRPPRQPOPOT", "SPSQOQOSTTQSOTTSPPST", "RPOOQRRSRPRTTQPPSPRO", "TPPSOTTRQPRSSOPRRQTR", "POOPPQOTPPPQRSOPTRTP" };
        int x = 4;
        assertArrayEquals(new int[] { 0, 10, 15, 17, 19, 1, 11, 12, 20, 7, 14, 18, 5, 6, 9, 13, 16, 4, 8, 2, 3 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case50() {
        String[] score = { "VJUVQPVUTVJLTOONOLSLV", "JOVKQTJMSMOLLLORVTVNS", "OVJLOUQJNLRKTSNSRQOKN", "OQMPVLKTMLTULLKVOOPVR", "NPNOKULKRVUSRVTTTSNMQ", "UQPTQRSQNLRPNLKOJSTRP", "MMJUKMTNSJOLMSKTUPRQP", "SNMTJLPOLKMUMOPTNQMUO", "PSTOVTUORLVSNNUOMPJSN", "MVNOQQLMQMOTURPUKMPQO", "QPKQSPSKTMMLRTRQMVUTP", "OSQOLSSTPROSUSTJMKQRQ", "UUVOJJUNTUJUTJQRORRJV", "TLRKVKRKTLQRRRNQKRKQJ", "UNVKJLVOJVVNOONLNTLON", "SUUNJNRVVTQPVLKVULSRM", "JLSTMUUKJKKSQJRLLLONN", "KMVPLSJSKJLQPVTUOKROO", "LJMLOTTUNOUUOPTPMLNTT", "LUMPVJOKMJOMJPNKPLPTR", "RQMSNTRMURQTJQRRNJNNN", "UJJORLVVTMVKVJUMLRORP", "OSVRJPVNQOUQPRSJNTSMR", "LQNKJSPJNRQSSNQTVRPVJ", "NJVNKKOMVLSRJQOJVLSUM", "LPPLSSMVVQKVTOPLPSTOO", "PSJTNJJOMSJQRPMSNSRTR", "UMMJSLRKVTRJSPVRRJKRR", "UKSSPRPTMMOPNVKPPJKRT", "SQVPUPKOORNNUNQMPRKMV", "TMNNTVSRKSJMMPSKRTJQO", "PNPTMJNVUSQJQRVJPUQPT", "KSTROJVQUKPLPKPVJRUNO", "LOVORQKPRLTVNOVOJOUPP", "OTNTJVQRVKPVNJRJVNNVU", "SJKRLTNMSVNSLRQSNTNOU", "NONROLJMTPRQPPVLUJVQM", "OPROKSOUNNMOJUPSVVRSM", "OLQVKJNVNPSUSJQSVQTUL", "KSRLURRUVKUTNRPLVRSPK", "RJJNJRQSKKSSKQPMQOJKS" };
        int x = 1;
        assertArrayEquals(new int[] { 0, 18, 21, 24, 35, 40, 28, 13, 16, 38, 6, 17, 27, 30, 7, 14, 31, 1, 33, 36, 4, 10, 25, 37, 3, 5, 20, 23, 29, 8, 11, 22, 26, 32, 39, 34, 12, 15, 19, 2, 9 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case51() {
        String[] score = { "RTTOHRHPIMITTQSLQJHOMOHPOPKIOSKIKJKQOTMJTPROTQM", "IHPTQINTQPOLONIOJJMTKRRISRMNSSTTSITQTKJRRJHQOIS", "HJPJPRORTNLTMKQSHIIPHMNLRMHLSPQIPMISKKKMKNQTKTS", "QKMRTQTLSLTQRTTJQJJPKKHTJMNSTTHRONQIHSQLJIRSPKR", "HIPLRKOSMNSOINTOSMOKHTRLKHQOMLSSJOPQHILOTHPJOPK", "ORPPRNSJHLMOKHJLMMHQLINHQMPMIROMLMHTLROISNOPHOL", "NKQHSQOONMQJLJJSHSHNJOMOKLIQJPSRTJTOMLJTOIQPQKS", "JOOMOHQSKJQRPKQHQHNTJSQMOHTIPNKLHSIMMNTKTRJSNNT", "KMLTLQPJLQLHIJKROJOJJTIQSLPPJOJSLKTRIIMJJRHTKOP", "PTRIONNILHSSSTRHSOTKHTHISTSSLQOTKOQIOOHHQKNIPPS", "SRNHIQNSMMIMKKOJSNTQKOOIQPRHQTSMKJTNJQQSPOSSIHR", "HQTRPNORHHTLSOJMLITSQORHTHMRLQTMPSQITRJROKPSOOI", "LTHNKOPLSRHNNKTNTMQJTPTQHOLNNKNKKMHMJNMPJOTSJJN", "HNQMTQJLOSMSNJSJOOQRHTMMOHNTJJTPNTSJHKQIOSNLIJI", "QMTRKPHPQLKOPPJPOLRTMTSMNMPJKRSNJMTHNNSTRLQQOIQ", "HTOIOMTJQQIIMSTISQMKQIQMTNHLLRMJJNQSMINSSQOKRNO", "RPPRTRPNQMIRNPMISNTORRJOMPHMRLHQILSMRNMTTNRQHSL", "IRLNKKKMSNMPSQQLNMSIJQTNPJRTLQRRMJLQPPMHQOTSROL", "NTLOMHKOSNIKRTNNSIRSQTSIQKIPHRSTRLRQJIQRMKJKSPM", "QOIRRKOOPIPMOJSMKRMIPHRHQIMLKQLQTQMNPIJSHJMKTRH", "MRSSLLRQLTPQOMSONRHHORRLJIOKMHLJJITRQMHQRPMTPJO", "NOPHHOMHOIRJJJHQMSNHLQTRINHQHKKKHJNOQNRLOMQSHTO", "LPROHTJPQQLPMTNJLPHSIILPOJJQMKQSSOLOSNNJHQPKPTH", "NTJMPQKQKPIJLJQLOORLKHKNNJNSTNMISPNIKMSLLPOITKR", "MJNSHRPRKHTJHRNMSPSNNSKSSMMSMRTOPTTJMLNJJMPHHSS", "LHJHPQQMJRTPJLSRIQQINLKHMMHLNKQKSPMLRMMKRLHOLLJ", "HHQTQTMLOSPKQNHJLKTTSSRKNSPPNTOQPSLIINOSRLMOHMH" };
        int x = 22;
        assertArrayEquals(new int[] { 0, 3, 9, 8, 16, 23, 24, 25, 22, 6, 13, 2, 5, 10, 7, 15, 1, 4, 11, 19, 20, 26, 14, 18, 12, 17, 21 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case52() {
        String[] score = { "PFMJ", "HDPH", "NHEH", "FJOK", "FMDE", "EFHJ", "ILEO", "MEKP", "HIDN", "KFHM", "KPDK", "LPML", "GOLP", "DPIM", "FOGJ", "HEMD", "HHGH", "MHJN", "DJGK", "EIDH", "GIOK", "NNGG", "OIPI", "KKFL", "OGIM", "FNDG" };
        int x = 1;
        assertArrayEquals(new int[] { 1, 7, 15, 0, 5, 9, 24, 2, 16, 17, 8, 19, 20, 22, 3, 18, 23, 6, 4, 21, 25, 12, 14, 10, 11, 13 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case53() {
        String[] score = { "SRSRHKQKQKTHS", "POIFNFPSIMSNN", "LJQSPHLMSORGS", "KRPHPFLPIKIKF", "QHSRFJJHFNQHT", "FFTORKFMOIGPL", "NJTQOSTTKJFLT", "LNJGTSQGQHJOR", "NNMLTSSHOJSGJ", "KIFPOOQTTOGQN", "LOGQKTJSQFJIG", "HPISOPFSITNJH", "PQPSTHIHTLJOH", "LJTKTIHJONLGM", "PSFPSMNKNQHRM", "FQRSOFRGJMTMF", "TNHTHGMMGOHGO", "TFJJGMJGFPTHO", "ISRKQHIFPLGKK", "JNSRIGFHOQGTO", "ORNQHSINJNGLG", "QFKONTGJNMRQO", "LHJLPGTJISNSG", "KGKQORQJPFPTP", "NGJMSFGHLQHKL" };
        int x = 10;
        assertArrayEquals(new int[] { 6, 5, 9, 18, 19, 20, 14, 16, 24, 3, 7, 10, 12, 13, 11, 22, 23, 4, 2, 21, 1, 8, 0, 15, 17 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case54() {
        String[] score = { "LXWYRQRQWLNZXYTM", "RTUZPTPVSZQXNOYZ", "PPUQPTPYYMWQYQNU", "SLSXZVVPWWMSUQZT", "PYPUURTVSUXYWRLP", "XYTYSOXWPPWXTQLN", "LUUNXVLOPUROPOMW", "TYWVSWWMSOVWMTWT", "TLNQNWSZLSUNXQQR" };
        int x = 14;
        assertArrayEquals(new int[] { 4, 5, 6, 2, 8, 0, 7, 1, 3 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case55() {
        String[] score = { "RRSPOUNNTOTTUSQUTSOTSPTUQSOOON", "NOSSQOOONSPSPQPOSPTRTOOSTUNUON", "ONTOPSPOPSRRUUUUROSTPPRUTNSNQS", "RSRQOOTUNUPQSQROTNNRNOUPSTTTQU", "POQUPUORTTPQNSRPRNTSUOQOOORPQN", "USNNQNONNTNRUOTTTSSOQTSSPOSTTP", "TUTUQTRTQQPPTUTTTTNQNTNRNTSUUT", "OUUNNQNQOQUNQNPUSOQNTPPOTQSOPR", "RSORPSTOPQQSRNNRTNORUSTSONUUNP", "UPUOTPSNRPQTUTTQRRNOPRQNNOUNOU", "SPSTNPQTSOPUTNUQPNOORNPTPPRUSR", "QPQURPTRNPNPQTQPTUTSOPNRRPOQTR", "RRNQUSUTRUNSTPNSUQNROSQNSRORNR", "SUQNRNPSOURSUPUNUQNRTUTQRSUNUP", "TOURRRNSRSNSPTTNSNSTPONQUORNRS", "RSUOPTTSPOUSRQTTPTQPOSSPTPNRTQ", "ROPRUPTNOSNPUNSRSUNPTRNSPPNORQ", "RORUNUQSRSQNTSONSOORUTPUOUTQSS", "TORQOSNNUPPRNSUSQPOQOPQRRSPTTT", "OQNPSQQTNUTRRSPQSNPPSOROPRPNOR", "SONNOPQNQTSSRONTUUNUUPRNUOOTSQ", "NOPQQPQSTSQNURPUOUOQUSPUOOUSSP", "NNQUOOSQUSTSQTUNRRNUQTRTSRUUUN", "PSNQRQSQTRSPOOUOSRUSSRUUOOQPQN", "SNPQPSOQNNNOTNORPQTQNTPUOUQPRU", "POSNOQNPPQPUQRTQNUONOTTPRPUUQT", "NTUPSTQSOUURTOSPRSNQNRPPNTRSRU", "STNOTOTRQPPNQOROUUNNQOOORUTNPT", "RNUSNUNUUPUTUNTSQTONPQUSQSOPOP", "PQPSNPORSQSUNQRTORQROSRTPTUORQ", "NQURURSRURUPTTTRQRRTQUSTTQQNSO", "UTSNPTUTPQOPNSTOUQTSTTPRUSSNRU", "SPUUPQTRURUUUOOQOROSTOROUTQRTQ", "OTNSPUTOOOQPPPORPSPUQONPUTNTTU", "PQQNNPTUSQRPNRQQQNUPUSSRRUSOOO", "UQTPRSUOOUPQUOONNRSSSPRNSONSNQ", "NRTUNPNOPNPSRQUQRUNUNUSQTQRQSR", "NRSRQPTOQROQSOORONQUSRSSPUSTOO", "USTOUSSTSPORUTRSQRRQQQTSUUPTUP", "UNOPRQTONTORTUQSROPPQONPUSPOTP", "PNPOUUUQPQRTPPRRQOSTRTNQSQTNSN", "UQUOOSQSQUTNTQOUTPRSPTNPOPSURS", "RRRQTQQRPTOQUUSUSNTOSOSSUUPPOQ", "OPRPTQUOUNUUUNPNNNUNPQSOQRTQRQ", "RUSOOSONOSSSNUQNSTQPPSQPNSUNTO", "USQTSPUOSOQSQUUQSORQUSPNRNSPQU" };
        int x = 11;
        assertArrayEquals(new int[] { 7, 17, 21, 27, 41, 24, 6, 11, 16, 23, 30, 31, 33, 34, 3, 4, 35, 37, 42, 2, 5, 18, 19, 26, 38, 39, 1, 8, 12, 13, 14, 15, 20, 22, 36, 44, 45, 0, 9, 28, 40, 10, 25, 29, 32, 43 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case56() {
        String[] score = { "UPQXSUXWTTTUWWQTSPQVXRQRRP", "SUWUWXUPTSUWUXVTXTVPXPPPXT", "TWWQTQPTUSQPRTUVVRVVWRTTPT", "XRXTSVPSVQSXRUXUSQRUPQXPTU", "XUUUQUPTUWWWVPUTUQVQTWVWUQ", "QSSRXUWWPURVQPPVWVPXUVSPXT", "XSXPQPRQRQVUXRXWVXXWSVRUXP", "RUXQRWWVTQVTWVTRXQTSTRWVUT", "PTPSURWWVSPWXXPRVTWPTUSWVV", "SXRWVWQTRRQTWUSPTSXXSQQTTQ", "URTRRQWPSXQPTWPPUVVRRPSUWQ", "USQTVWVVPVQSXRRPXUUSSVXSTT", "PPVUVXTPUUSSXTWXPTSWWXQXVW", "PSQRSSUTXPPTWQSSTWXWRVSQPX", "TWQWXRVRVTWUQWUUWWTPVQXTQS", "TUUVXXURQSTSUUSWUPSVRRRURX", "WSRTPRPXVRWTQWQXQQXRPRVRXX", "RXXRURXVPTTWXVUPTXXUVVPWVV", "WVUWXRSUWTSXPUVVVPUQPTQSPX", "PSSSUTUQXVTQWRVQPWUVSWRSTT", "SUTVVRTTPVQUSXRSQUURTWWRTX", "VVTWTXXVRTUWRXSPSTWRRWUPWU", "QTTQXURQSVPWSRQVTQRPPVRSQU", "VQTTSXRSRRXWUVTSWRTRXPWRTV", "TXQRSTVVPTRTQPSQQUSXWXQUWP", "VWRWPPUTTQXUWVXXPQQVPUPPWV", "XPQWRWUSRPWRWQXRSQPVRVUVTQ" };
        int x = 15;
        assertArrayEquals(new int[] { 9, 10, 11, 17, 21, 19, 24, 7, 8, 26, 13, 20, 23, 0, 1, 4, 3, 14, 2, 5, 18, 22, 6, 15, 12, 16, 25 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case57() {
        String[] score = { "IIHKKIMHJMJJMLJKMKHIMHHIMLII", "HIHJMLMLJIJMHKKJMLJIIIMIHKHI", "JLLKJKHLKJJKIJHKJMMIMHIIKHMI", "KJKMJLMLKMILLHLJMJJKHIMJIKJM", "JKHKJLJKLHMMHJJJHHIMIMIMKKJL", "KLJMHHLLKKKMJMLKLLHHJLLKJMMH", "KHLKKJIHMIJIJJIKJLJILIJHILHL", "KKIJHMHJJLHKMHJHJKKLKMIKLKKK", "JJJMIJJILLHLLLMJKMKMMHKJHHKL", "LJHKMLKLJKMHKJHJLKLMIHMJMMHI", "JMLIKIIJIHHJMIMLLKJKIIJJHILI", "MJMKJLHLLJMIHJKKHJHJMJIMIKLI", "MHKIKHLLJLMIJLLJJLLMKIHMLHMH", "JIMKKMMIKLKKLHLKIIKLJLIJIJIH", "MLHJLMMMHLLHMHJIJLKILKLMHILI", "KLKKLIHILMJIHLIMJLLMMMHMIKKI", "LIKMMLLMHKLMLJILIJIJLMIKHLLL", "MHKHHIKKJJJIJHMMHIMMIJHMJHIL", "MMMHLIJIJHJMMMJHKMILHJJMHIMM", "LKLJKMHMIKMKLJLKHIKIJHKJKHIL", "KKJJILHHLKJLMJMLKIHLKIKHHIJH", "MJIJHIKMJHMIJKJKJKHJKMJJHLMJ", "KMLIHMKHKKHHIIMHLMKHJMJJMHHK", "MHKKKJIMKMLLMJKLHJIHLHIILLJK", "JHJJMJLJJLKJLKKKHJMLJLKKIMJM", "KMKHLKILLJLKHMHJLMKMHHHJMKHI", "HJIJMKMHJILMKKKMHIKJLLMKHJHK", "LHIIJMKMLJJHMKIMIJMIKJHHKIKI", "LKILIIMILLKMIJMKKJHKHIJKHJML", "JJLMLHHJIIJKILMHJKLKKJMIKLIL", "HHMJMMKKLHKKMLLJHHLHKLKJJKJI", "MMJMLKHJJKMIHHKKHLHLHKIJKIJJ", "KKIJIMKIKLJLKIIHLKIJLJIHKMLM", "LLHLJLLKLMHMIKMJKKHMMHIHHIKJ", "KKJJMLIMHKHJLJKLKHJKJLHMMMIM", "MMHKLJMKKJMIIJLHMMIMLHLHMIHI", "KKIKLJMKKMHHJMIILJJJHIKIKKKK", "LMMHJLJHJIJKKKKKHLMJHJJMMMLI", "KKHJKILJJHIHIMMJLKHLMIJHHJKH", "HJIJLIHJKHLLMKMKJKKJLHIJMIII", "IJHJIMJILHMIHLHIHMMJIKLJKHJI", "LMKHIHJIHIJHIHHJMHMJLJLKIILJ", "LLIJHKMLHJILILHJLLMLLMLLHJJL", "IJKMIHJMKHIHKHMLLMJIMILMMJKH", "HMKJJKMKLJHJHHIIMJJHKJHMKIIK", "KLLLMMLHHILHLHLHIHJKIIJJHHJK", "HLJIKJLHJLKJILIMILIJMHJMMJJM" };
        int x = 5;
        assertArrayEquals(new int[] { 5, 12, 29, 41, 43, 0, 10, 15, 17, 18, 21, 28, 38, 39, 6, 8, 23, 24, 35, 36, 46, 2, 25, 26, 31, 42, 44, 1, 3, 4, 9, 11, 16, 20, 33, 34, 37, 7, 13, 14, 19, 22, 27, 30, 32, 40, 45 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case58() {
        String[] score = { "EEFDCCGGICHDEEIIDGFCCIGHCIDEHCEGDGHGHCCCEIECGCEDF", "CFGCFFFDCFEDHEFDIEICGIECCCFHFDFCIIGCGIDEFIHICECDH", "EHFHGIDHDHFIFFEECFHHCEHDCFIFIFHIIFGCEIEGECHFIHFIF", "DEFHEIIFEIGDGECHHHHDGFFECEEHIDDHFECHIDCHFICGFCGGG", "HIECDGFIDFFCGDDCGECIIGIGCCEGFCFFCFDCGIDFEDGFEDIDI", "GFCIIFIDGFIDFGIIHCCGDICDDGEHCFDGICDFDCHGIEHHHGHHH", "FIGCGICFHEFCHCIIEIIHDCDDHFCDDDGHGFGDHGECEEGHGECHI", "ECGEIHHHCDDECCFEEIEEDHFFEEGDEDDHEECDDHDHHHIIFFHCE", "EDCFIDHCEGHFDEFFDGEFIFEEECFHGEEEHHGFFGEHIHECEHDGF", "GEFFHEFHCGDIECHFGDGIHGEHIIHDCIIHDHEHFDDECEDFDEEFE", "HFGIHIGCCIHCICCICHHCFDDFFEHFHHCDCCIFICGEGGFGICGCH", "ICDGEGIIDCECFIHIDGHHIHFEEEFFFEIEGDGFEIFGEFFCCIFHE", "EIHCDEGFCIGGHHCHIFIEHGFCDGDFCEEHIDFIIDCEEDFDCGHHH", "IFCHEFEIFHHGHDCHHHGDFGGHGIFDGHFECFEDDHEECFHGDCHCG", "EDCHDIHHCEIEEHHHIHHCFFFGHGFEGHHECDCFFIHHIHDHGCDFC", "FCFEDIFFCFIIIFFIIIHDIFHDIICIHGDDHGFCEGHEFCIDDGEHH", "IGDHHDDCHGDFEFHEDFIDEFFFEIFEGHIHDFCGGDCEHCGCIGEIG", "IHEIIIHEGEDEGCIEFHEFEFEGDFDIDECGHFCFFFEIHHHHDFDIH", "FHHEDCDCIHGGDIHGIFCGGCICDGEDGFDCGICGDEDEDICCHICDD", "ICHHCFHECECEIHFHFFFFCHEEHCCHCDCHCHDCCDHIGFCIFHCHH", "CIEHCEDFIEFDEGHEGEDGHCFEHICCHGGEHEHGCDHCIDCHDCIFI", "GHGDEECIEIDDCGDDGIFIICICICCCEIDEEGDCGEIIHFCFGHCEE", "IIDDGIFCHGCGCDGDCGIFDECHEFGEGIEEDGEEGCHFFCEGIHDIC", "FHHFEDFDFCGGGDEFHCECFCHFHFHFIICFCFGEIIGICIGHFCIDC", "EDIFDECGIFIECEHCDDEFFHDGDGIDICEIDDCFCDCGGCGCIHGDD", "FGGIGHEEIEDFHEFHICHCIIDCICIHHEHFDFFDGFEGEHHGEHFGF", "CFCGGFGDICFFHDEFGCGDICEEIFIHDHIICFEIGIFHIDDDGGEGF", "GIGIFIIGGDGDIDDFFFHEEEHHFIHHCDGHGFECEDDGEECEEEGDG", "FDIIECCCDHFEHEFECEFIFDCGIGCIFEDGCDCCHFFIECCHEECIC", "ECCCFIDFDGEHCGHHEEDCGCIFDGFEFEEDDCEFCDDDDHGFFDCDE", "ICEGGCHFIFHIEGEEEFDGCFHDDFDIDCFHCGFFCHGECICDDIDEE", "FDIDCHECFCICFEHCGCFHDCHIGCHHHIDIDGCGGFDHCDEDFGGEE", "CCDGICICIDEDDCEEFGDCDHFEFDDFIEIHICIDIIGCFICDFGFIH", "ICFEFGHIEFCFIDICGFDDFCGFIHEEDIEECIDCEECIHFFEDFDEI", "GFHDGDFGDHEEEHCIFCEDEIDCIIIIGDFCHCCFDGDCHGGFCCHCD", "GIDGHFIHCFEIFDIEFFHDCCCIHEFGEDCHGGGHGEEICEFGHHFEE", "DEHDGIGCFCFHDDGEIEIIFCCDDIDEICICDCFEHFEEGEGDDGDIE", "IICFCGDGEGFCFECGCGEDCDDDCDCGGIDHICCFHEFCHCEFIIDEG", "HHFDGIDIGIHIGEFCGCCHGDIFCCCDFHGHDCFHFFIICFEDGFCDC", "ICIHGHCGGDFFIHCEIDGIFDCDDGEEIICHDFIGGDHHFHDFIIIFD" };
        int x = 33;
        assertArrayEquals(new int[] { 5, 10, 29, 32, 34, 36, 37, 38, 11, 12, 14, 24, 28, 3, 7, 20, 2, 4, 6, 13, 16, 17, 23, 25, 26, 27, 39, 0, 15, 21, 22, 30, 31, 35, 8, 9, 19, 1, 18, 33 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case59() {
        String[] score = { "UVVVWWUVUWUWV", "UWWUWWUVVWVUU", "UWWWUWUVWUWUU", "WVVUWUWWVUUVV", "UWVWVWUUVWVVV", "WUUUUWWUVUWUU", "VUWUWUUWVUWWU", "VVUUWUUWWUWVU", "VVWWUVWVUUVWW", "VVVVVWVUUWWWW", "WWWUWVUUWWWUU", "WWVWVVWWWUUUU", "VVUVWUUWUUUVV", "WVUVUWWVUUWUU", "WVUVVWUWVWUUU", "VUVVVVUVWUWVV", "VVVUUWVWWVWVU", "WUWUVWUWWVUVU", "VVVVVWVWVWUVW", "WVUWWVUUUUVUV", "VVVVWUVUVWWVU", "WUWVVUWUVUUVU", "VWWWUWVVUVVVW", "VUWUWWVVWWVWW", "WWVUWVVWWUWWV", "UUVVVUVVUWUWU", "VWUVUVUUUUVVV" };
        int x = 0;
        assertArrayEquals(new int[] { 0, 1, 2, 4, 25, 6, 7, 8, 9, 12, 15, 16, 18, 20, 22, 23, 26, 3, 5, 10, 11, 13, 14, 17, 19, 21, 24 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case60() {
        String[] score = { "LQOSQRQOKKORPOPOPKNKSKORKNQ", "MPKPPSRPNKSOPLORNQNOPMSKSNP", "OMSLQPQLPLMNQNKNLKRNLSMSKNQ", "MSNMNQORNRNKLNSPOSRMNNKPRPL", "OMMRROMPNNMORNLSMNPMMQOLQKR", "SSPPPOMNKROROMNSPQSMRNNMSKL", "SPPORNKSRMOPSPSRKOOKKQOOKSP", "KORPPLRNRPQMQQOKKMSQMMMQSOP", "MLOOQRQORSQOPQMNMQMNORQPLNK", "QRPMLMNMKKMOMLSPROMOSMRLOOM", "KOPSLPNLSSOLSRQRNMLLMKMNLPK", "KSLRPNSRNMRONKQNNPRSQQLRSRP", "RRRLNPLQKRMNKMPSPNNONMNORKP", "OROPOQKSKKRQQPSOMQPQSMSSLRK", "KQOQSQNOQPPNNSOORNRLOSLONMO", "LNQKMOPOOONKRSQQRNMPSMOOPML", "NPLOPQOROPRMONLKPLMLLRSNNOR", "RMPQNNMKLPLPSRRMNSRMPOLPLNP", "QQSRQKLNKSPROLNSSSLQSRPMMPR", "OSPSOPOMQQKMLQKONPKKPMPOLQL", "RPSLKQMRRLPKMRNSNQPRKKLNRPM", "KQSOOSPNNKKROSQSQRQOOLNPNSL", "KQSMROKSORNQSPONSMRROOSNLOM", "MPLSKSQNQMQMRLNMSMKPLKPKLQS", "PKQRNKPKPOPLOORKPSLSOQKQNKO", "RSLQOMPLQNRMRPMNLLLNOPNQSML", "RQSKQQKLRSNONQPMPOOQQPNSSPQ", "KOPLLRLMPKPKOSPOPQLLSPRPORQ", "NMKPQMRQONSSNMLSQNNSOQSKNMP", "OSNQNMLRPRPSQQOPPKSSKKRMQPR", "SSNPKMLMKMNNMRNPNPRSPMPPPQQ", "PLSOPRMNMMPSLMNLSRLKROQKSOL", "MMPLSPQLMSNRRSMPSOMLSQOLQSO", "KRQRLLPLSMSKQNLLNPOQORMNNLQ", "SPPONRSLPMQONLLRMOKQOMKKOMP", "ONNNQSNSRLSQRSPSLRORMLKKLRM", "OPSMQNKNMQKLOROLKKNRMSOQRRS", "OOLLOORKSOQOQOQLLNQKRLKLKRS" };
        int x = 12;
        assertArrayEquals(new int[] { 12, 3, 19, 31, 9, 20, 30, 11, 14, 26, 28, 34, 5, 16, 18, 21, 24, 27, 36, 0, 1, 8, 2, 7, 13, 29, 33, 37, 4, 15, 23, 25, 32, 35, 6, 10, 17, 22 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case61() {
        String[] score = { "MMPMNNPPQPONNPMQPPOMNMQQQPPQNQO", "OOMMQMOMNQPNQMNOMNQNPMQOQNQOPPQ", "OOOOMONNPMMMNQMNONOQPPMMMNONMNN", "QPMPMQOMMMOQOQNNQOPPMNOPMQMOMMQ", "OQQMOQNQPNNNPMPNNPPNOQPPONQQQQN", "NPNMMNQOOONQMQNQNQQQMMOPMMQMPNO", "NNNONMONPQNQNPNQOPONQQQQMOQMNNQ", "OMNQMNMPNPMQPPOPMMNMQOQPPOQNNPN", "MMOPPNMMNQPMPOPMMMOOPPNPONMMPQM", "MMQQOMMNQPNOMMOMOPPNQQQOMONMNQN", "PMNNPPNPPPPOOOPPPOQQMMNMPPMNOQN", "QQQOQQPQOMNPQNOOPMOQPOPNOMMMNNN", "QMPOPQPMMPOQOQNPMNNOPPMMOOQQPNN" };
        int x = 0;
        assertArrayEquals(new int[] { 0, 8, 9, 5, 6, 1, 2, 4, 7, 10, 3, 11, 12 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case62() {
        String[] score = { "FGEGEFDGEF", "FDDEDDDDDG", "DEGGEFDEEE", "DEEDEGGEEF", "FGEFDDEEDG", "EDFFDDDFEG", "FFDEFFFEFD", "EGEFDEEEEG", "EGFEEDFEED", "DDDDDGEDGE", "EDDEDDEEFF", "DDFFFFGFGE", "FGFEFGGGDF", "EGGFFFEDEG", "EDGEFFDFGE", "DDGEFDGGFG", "DEEDFDEGGE", "DEEFDEDEDD", "EGDDDDDEDG", "GEGFEDGGGG", "EGDGDFGDFF", "DDFDDFEGED", "EDEFFEDFGF", "GGGEGFEDDG" };
        int x = 9;
        assertArrayEquals(new int[] { 6, 8, 17, 21, 2, 9, 11, 14, 16, 0, 3, 10, 12, 20, 22, 1, 4, 5, 7, 13, 15, 18, 19, 23 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case63() {
        String[] score = { "ONL", "OIG", "FHL", "HMG", "JHF", "KIG", "JLM" };
        int x = 0;
        assertArrayEquals(new int[] { 2, 3, 4, 6, 5, 0, 1 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case64() {
        String[] score = { "NNONP", "NONNP", "ONPNN", "NONNO", "ONNPN" };
        int x = 1;
        assertArrayEquals(new int[] { 0, 2, 4, 1, 3 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case65() {
        String[] score = { "PPQQPQQQPPPPPP", "QQPQQQPQPPPQPP", "PPPPQQPQPQPPPQ", "QQQPPPPQQPPQPQ", "PQPQQQQPPQQQQP" };
        int x = 9;
        assertArrayEquals(new int[] { 0, 1, 3, 2, 4 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case66() {
        String[] score = { "WUVXVVRUUVWXR", "RVTXSVUTXXVVU", "VXWRXXUVVXTXV", "XVRTWUSRTUXWX", "XXTRUVTXSUVUV", "XWSRVVWXTXWTX", "XTSVXWVVSSWXW", "VVWTUTRWVSUXT", "UVXTSURVXUUTX", "RXUSWVTXVTVTW", "SSUXXXVTSXXUX", "RVSXXRTUWUVRX", "RRSVTXWSSVXSU", "VXRRWWVTTWXWT", "XTUVUTWXSUSST", "WXSVUWSXWVTXX", "TURVVVRWTXRWX", "VTRTUURWRWRVT", "USWSRXVVSWUTX", "XXRURUXWRSXVV", "SWVWUWTXTRXVX", "XWVSXRUXSWWVV", "TUTVSRRWXRSUX", "XSRSTUXRWRVVR", "WXUXVSVWURUUT", "RSTTWXVSWSUUR", "WWSVSVVUVTXVX", "SUVUSUTXXUWUV", "SVVTWUUUUUTUW", "RXWSRTSXUVVUU", "WVVVXWSVVVRVU", "XXXXWXSWWUVUS", "RXTTTSWVWWXXV", "UWTUTRUTTTWSW", "RUSXSWTWUVRUR", "XXXSWSXRUUSVV" };
        int x = 6;
        assertArrayEquals(new int[] { 0, 7, 8, 16, 17, 22, 3, 15, 29, 30, 31, 4, 9, 11, 20, 27, 34, 1, 2, 21, 28, 33, 6, 10, 13, 18, 24, 25, 26, 5, 12, 14, 32, 19, 23, 35 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case67() {
        String[] score = { "ACB", "BAC", "CBA" };
        int x = 1;
        assertArrayEquals(new int[] { 1, 2, 0 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case68() {
        String[] score = { "BBCBABAC", "BCBACABA", "CCCBAACB", "CACABABB", "AABBBBCC" };
        int x = 6;
        assertArrayEquals(new int[] { 0, 1, 3, 2, 4 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case69() {
        String[] score = { "A", "C", "B", "C", "A" };
        int x = 0;
        assertArrayEquals(new int[] { 0, 4, 2, 1, 3 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case70() {
        String[] score = { "A", "A" };
        int x = 0;
        assertArrayEquals(new int[] { 0, 1 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case71() {
        String[] score = { "DFDJNEKVMS", "FDJNEKEWSV", "KGFNRKELSM", "FDRREWGFRS", "DRRRWDGRGB", "SERTTYGDSW", "FGTESCGHJY" };
        int x = 8;
        assertArrayEquals(new int[] { 4, 6, 0, 3, 1, 2, 5 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case72() {
        String[] score = { "AXXYWZWWYXZ", "XYZZZYWYZYW", "AZYZZWZYYWW", "AZWZWZWZXYW", "BZYXWZXWYXY", "CYXXXZWXWXW", "AXWWYZWXYXY", "BXYYXYWYXWY", "DZZYXZYZXYY", "AWXZXWYZWYY", "DXXYWZWWYXZ", "WYZZZYWYZYW", "AZYZZWZYYWW", "CZWZWZWZXYW", "BZYXWZXWYXY", "DYXXXZWXWXW", "ZXWWYZWXYXY", "BXYYXYWYXWY", "AZZYXZYZXYY", "AWXZXWYZWYY", "AXXYWZWWYXZ", "PYZZZYWYZYW", "AZYZZWZYYWW", "AZWZWZWZXYW", "BZYXWZXWYXY", "CYXXXZWXWXW", "AXWWYZWXYXY", "BXYYXYWYXWY", "DZZYXZYZXYY", "AWXZXWYZWYY", "DXXYWZWWYXZ", "CYZZZYWYZYW", "AZYZZWZYYWW", "CZWZWZWZXYW", "BZYXWZXWYXY", "DYXXXZWXWXW", "ZXWWYZWXYXY", "BXYYXYWYXWY", "AZZYXZYZXYY", "TWXZXWYZWYY", "OXXYWZWWYXZ", "PYZZZYWYZYW", "QZYZZWZYYWW", "CZWZWZWZXYW", "BZYXWZXWYXY", "DYXXXZWXWXW", "ZXWWYZWXYXY", "BXYYXYWYXWY", "AZZYXZYZXYY", "MWXZXWYZWYY" };
        int x = 0;
        assertArrayEquals(new int[] { 0, 2, 3, 6, 9, 12, 18, 19, 20, 22, 23, 26, 29, 32, 38, 48, 4, 7, 14, 17, 24, 27, 34, 37, 44, 47, 5, 13, 25, 31, 33, 43, 8, 10, 15, 28, 30, 35, 45, 49, 40, 21, 41, 42, 39, 11, 1, 16, 36, 46 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case73() {
        String[] score = { "LAX", "BUR", "ONT", "LGB", "ZAN", "ZNA", "ZFO", "OAK", "ZJC" };
        int x = 0;
        assertArrayEquals(new int[] { 1, 0, 3, 2, 7, 4, 5, 6, 8 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case74() {
        String[] score = { "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A" };
        int x = 0;
        assertArrayEquals(new int[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case75() {
        String[] score = { "Z", "Y", "X" };
        int x = 0;
        assertArrayEquals(new int[] { 2, 1, 0 }, candidatesselectioneasy.sort(score, x));
    }

    @Test
    public void case76() {
        String[] score = { "ZXY", "ADZ", "RBC" };
        int x = 0;
        assertArrayEquals(new int[] { 1, 2, 0 }, candidatesselectioneasy.sort(score, x));
    }

}
