package topc.test.easy;

import junit.framework.*;
import org.junit.Test;
import static org.junit.Assert.*;
import topc.easy.*;

public class UniqueTest {
    Unique unique = new Unique();

    @Test
    public void case1() {
        String S = "banana";
        assertEquals("ban", unique.removeDuplicates(S));
    }

    @Test
    public void case2() {
        String S = "aardvark";
        assertEquals("ardvk", unique.removeDuplicates(S));
    }

    @Test
    public void case3() {
        String S = "xxxxx";
        assertEquals("x", unique.removeDuplicates(S));
    }

    @Test
    public void case4() {
        String S = "topcoder";
        assertEquals("topcder", unique.removeDuplicates(S));
    }

    @Test
    public void case5() {
        String S = "a";
        assertEquals("a", unique.removeDuplicates(S));
    }

    @Test
    public void case6() {
        String S = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab";
        assertEquals("ab", unique.removeDuplicates(S));
    }

    @Test
    public void case7() {
        String S = "z";
        assertEquals("z", unique.removeDuplicates(S));
    }

    @Test
    public void case8() {
        String S = "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        assertEquals("ba", unique.removeDuplicates(S));
    }

    @Test
    public void case9() {
        String S = "abaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        assertEquals("ab", unique.removeDuplicates(S));
    }

    @Test
    public void case10() {
        String S = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        assertEquals("a", unique.removeDuplicates(S));
    }

    @Test
    public void case11() {
        String S = "bccbbbbbccccbbbcbbcbccbcbbbbbcbbbbcbcbbccbbcbbbccccbccbbbbbbbccbbbbcccbbbbcbcccbccbcbbcbcccbbbbbcbcbbcccbccbbcbccccccbccbbbbcbcccbcbcccccccbcbcccbccbcbbbccccbcbcbbcbbcbccbcbcccccbccbccccccbcbbbccbbbbbcbcbcbbcccbcbcbbcbccbbccccbccbbccccbbccbbbcbcbcccbbbbbccbcbcbcccbccccbcbcbcbcbccbcbbbbbbbbcbbccccbbcbbbbbcbbcbccbbccbcbbcbbbbcbbcbcbbcccccbbcccbbbcbbccbbbcccbcccccccccbbcccbbbbccbbbbcccbbbcbbcccbbcbcbcbbccccbcccccbbbcbbccbbcbccbbcbcbcccbcbbbccbcbcccbbcbcbcbccbcbbcbccbbbcbbbbbbbbcbcccbcbcbccbbcbcbbcbbbcbcbcbbbcbcbcccbcbbbbccbbbbbbccbcccccbcbbcbcbcbcccbccbccbccbbcbccccbbccbbcccbccbccbbccccbbbccbbbccccccbbccccbbbbccccbbbbcbbbcbbccbcccbbbccbbbccbcbcbbbbbcbbbbbcbbccbbcbccbccbccbbbccbccbbccbbcbbbbbbccbbbbcbbbbbccbcbcbbbbbbccbbbcbccccccccbcccbbbccccbccbbccccbcccccbbcccbccbbccccccbcccbcbcbbbbbbbccbbbccbccbbcbbccbbccbbcccccbccbbcccbbcbccbbbbcbbcbbccbbccbcbcbcbcbbbbbbcbcccbcbccccbcbbcccbbbcccbcbbcbccbbccccccbcccbbcbbccccbbccbbbccbbcbbbbcbbbccccbbbbcbcccccbcccccbbbcccbcbbbccbcbbccccbcccbbcbcbcccbbcbc";
        assertEquals("bc", unique.removeDuplicates(S));
    }

    @Test
    public void case12() {
        String S = "wowwhhwidewowswowiiotiwwsitwoeeotwwooowowtswhiowdihdsiiidoiwwgieggdheewigwiiisetgeihwoehdeiiseodgehiodgoiogidoweghoidsieeiosotsiiottitgwdwotioiwwghewhitdiiehwiodshiioiiwiiweswiswwiohtgiioowsossswtgwwwishdgswwiwsidosigdwwwsottweotwisgdtgdhissdhwiewhdiogetdhdowtiwgiesiwiowwihthhgidswiiiiwwihtsgewwiddidswehowtiehohitsogiiiiddgwgwseohsihiwihstdgdgdtigewdtshwgwoitwhtoigehhsswtwgsiseitiweisethwteedtitweewosdsooswtiewgwgieihwositdtiiiwdwdweiowgdsdtghwowdishwwwiwowetdwwigtesoshwwwhdtwsddowwwtewtdsidwioggtiwwwtdediiigsisswwwetiddgtitwdiwtddwitwoiswoiighiotwssoidtwwiwwiggotowiwdswgwdwtwetdtsotdhwwgdothgtewhditsigwdgeswgwwoohegsgothttiehsigewiohiewsswitdgodtgwoeodhwtiehihwtigwwhtdgwiwiiisgstiwswtiitiwgeiigsiiitiitegowiotgdowoitogedwsttwsotigosisswwiswswstwwegiseieitwwsiihodhtwwwgooedthitidiiihoehwosswidwohwgewsttdsshgoegiwidwiodhiggewewiiiotiisedgtdewwwiwiotwoiowitwggewostwwtsdseetdteodidwosgdwwwowsstgwewiwiwedieddiwhwwetgodeidgwiiwiidithsiosihwtoihsgishiwisetgieiwotoowiswigiidwoweigdohhtihdwiwsg";
        assertEquals("wohidestg", unique.removeDuplicates(S));
    }

    @Test
    public void case13() {
        String S = "wlmghfzzvwmjoohpwugennkqjpcuwlulwsheqttpfijjxelodxmzwrwesgdihfexbxicyootmsoobakawzsjvnqiidgudubqsowmiokpghssjhjbqwdxmgirbvvkmwpujsqviaonnexjjoajfqgmxoyrbhapcjffdiomhqqbhmxyfaijjdldyeguwuqpmdvhoqddskogbrbxydnjegvcnctluyiykupjvjfgqxejfhsrwjnkognwyqkxwzurcokgnqsayypygznvvceppvzpayedmzbafzbprtqalvaajhxbbgvriuxsxeqvqmnwbqqkgpgjfipwdtbulbojjdwdbtwoalacuaarmhcijuoiqexginhtckwbziudtoqztsjjlebnypqntlwvvtbxnlqdpqerqcrhtrfemzvwdbwshogwsfyljewofastlosfpkpcvkdumefvlijkvcjpvsqsjmpvkplscaxtquhppbabcchzkkkgvrufzqtkvnlznuvznrcpczkmtdsjxtfusegraqaanczgafovtvrebocxyyqsiwmimtoxgblcmoveplsrlyetoxqvfzutdharrcnxaynrdhhhztdnbizkorhhwldssvpvuzliwumcteplaskwqusxhchwcfirhpbocwtoqkkexqxcvhojgapdqopogtaokybephmsnodgqymomqflurjiggztdjmhpwmfkuyozxibguvmkbzhtmzbnkyolosbwoouxamxsmikpzanubzjedzizbhugrfzhzwzmpkesivominggmsleqimrubeeupzmutlaklhimvncosxqtekdmazzwvaosxzbfwgugbkeauxmlttcrtevbnrnbvlmllsfvwnrsbspnlaqidjxsanhztvzdsoixgebhsaewypdskbbagsxmbgyrwhdbzzozekscxmyosddyezllzdbdvxdtwjuvehvsrycreuwztszvzxiwhqqmxghbwjktve";
        assertEquals("wlmghfzvjopuenkqcstixdrbya", unique.removeDuplicates(S));
    }

    @Test
    public void case14() {
        String S = "gjxntqnljjauxqvxqjjdtuuuvuexgolquoglnegvnvjduxnxaeojgndvllgdllegaqguugdouvluoxodqatuvdagneoeuqovaujljttgvooedxtvlnvqgdnaoouenavjalntetqojgaqvaddttvvetvdxqadgoxtdlxuqtuvelugdtqanjxxotgluujqqajtgexuddeuntglqntgjxqqgglugxjgxaldqgagxjqjxoteqeqxedxjxutnaevngognagqvqjqaalqujjeuxxgjaxjjdvjuololjuttnjlqeoxxgxjooojolavqllgtxdeqntdvoutxtdxeagnjualdjqegdvjaxaaaevvtaloxvneonnxloxullxdxxllveddglvauqjttlteajtxleljlnaqvqnjauaqndueqjdjnexvgvaqxndntltdjxeggdxjvgqajoegtedqnaaoettlttattxtqodloaoaalaatoxtovudujgaeoxgltduglunxaottntjleeqegjvdnjxgtagltxvenljnloltnxttgggqoxtoeqenogggnuaoanuojgxujxonxvglnveexggagldqlqxluvougvuxuovxounqneqtellvvodnxtxnnjvvnxxlntxlllevutdutgduxoavlaxnojgoulgegnqxdglvvougaldldaujneovoleljedunoexqgoxaxjxuogjtgojlgaeaontgtlxoxavjggudguetuaovlovqgtnduqudglnnxxdnegoaqeuaxquoljjgaoattqogxnjaexvnoaonnoaeeluooxjdnegljvvvdjlxtotvuutxjquxqqqjxnotjotdnqxenttavxedxuedvdjqenxavoudqlanndloulnqjjujaqutaexaxoloadgqqgqnegngaujqaonauqqoaxqjvggudaelnjdgjlqgntngdtntunuejavgqljgaolaejvoonudlxddqdge";
        assertEquals("gjxntqlauvdeo", unique.removeDuplicates(S));
    }

    @Test
    public void case15() {
        String S = "vwaojjemkhhmqagrnnouprbngehizibpvxvjyyhdsagrtmpotdeejdaluchbxuhgoiltumxhzireyrzyjionwlkvgsqzlejhaqkabpnvoaaslsmmuipjvvonlmsxawjgowlleeuhngimuuqoskreoynbejpmgkejgdhnhhouywczcwfswtfluwijcnlrbvabudjhtqdjtxyadxpbiqibszqwxdbynoqpssimhhflmvftgrblhkdygwewcqodivngigmjhonxigkqtrzxqzhqdyknazwdgpjtirriamqtxijfipolqoqmolmvbusnllzyzqzhachovkhjnkvxeijiajehmoximrfpsmupjjvqafzohkmmaehkpejnzfewiokkyjanknpmmvewjxohsrkqqarjkhpuxldjrncanfnnlbhamgccjsyizflmzpromopnifyaklcjrgdssvmdtaunxxvufevmbcbhwveikptaozvlmukyqcvewyqwcfmhwynqevqrhgntqjyuewaevxdtdurcqmvpnzflfvvycrqwvavdxtakvevongyykcgywkwablslyzjxvdhqzextuksytctatafikquqrpufnpyeaieixynbdihmjxqrzxxxvtlkqcngabtsvonmzkramcudowrqhrqgvtrluqspqbboycrjroytqtvlovdwuqtldijoyvxudjeyoxpekmidizmvmgilmzdrerhjopzjmmepociberjtybhqxmsadlvqpvclakcobeyqunmtikstxocyjxjlectzfmztyahywvnogkgnjxfesimwkcaoliecqjxqvtrusbckbudmucueyauvuopamaljdhumxinscdpputfbyuzlyzjsqxbjjedkfbbhbdjrmqkgeievssuwsbcvhcylpnzosusanqamzlprkpqkwvlchmvspvdgsvchhkzbrgkzxoicmgfnirdrhobqtqwwsahoeanujqwfdwag";
        assertEquals("vwaojemkhqgrnupbizxydstlcf", unique.removeDuplicates(S));
    }

    @Test
    public void case16() {
        String S = "jjtaevqanxgllxluvtjoleeugdauexlqjauqlvqvvutaedduodoqjvoulxjjojaaxqltgxagtjtoenaatxoadxxtoexxdotuqnulueqvgenueutxduqaonlnvdqunoteddugxlnxnnadvdxlunvedtvtnagdxqajxaqqnuvtqxneqdxndtqtqoevgtjvaqqvjondllvavvdqoontovnetgdundvjelljtlglnotvuddvggjjxglqtgqonvxdgovvtvuueqtdeentujtlvnteooantqxdxxjnetotnlqdnnluovjgunllejudlvgqexjevungadontxqeovjeqtnultjlvlaaexoagqaqulgetdtavuqjuoxatogjgxuxevuxadnggungevgeveuaqngqlxoeongvjvdnueouaaxvjvldljqxjgntlexvovggnjveleeeaautjaeldxqugvqvjultngotqqloxnnnqxledqlvvqgggnxjtxaanjjjdqdnuxgegoxqqedeeajavgvgadnanjlxudannxoaggxntujnvgjagluttudetttagtgjatjvaeattqtxggueulvdlndtjtvtoltequovxtedqudueaxxjeqxeoqxqujoxuvgeullooxdqoxgtxuadjegxllalangeglvnvtdndqqdnnqgxxqdxtjnaagajntvtedgqeeudvootueeejxnxnjvdoveoeajtquqjljdlldaxtqoalxujtvglnvlnuuoajljqtvtgtetqeueleogelqvgonglggqotqnndgnddddolveadguetaajlxvendttujetgvuxgndodotnollloxoqdvgqnxdqlnjueoauoxjjoajlgvovotavtnaaaxgegejttljoejudvvvoqgvvettolqgjulxqaoxoggtouqduonqvldxqjvevqggaqovvadgndvottjxtgvaxneagxaugdnlonnojtxuveeoeta";
        assertEquals("jtaevqnxgluod", unique.removeDuplicates(S));
    }

    @Test
    public void case17() {
        String S = "pjvwamnjmjwljgckwpeytbljxdxodfsprvjjzhpibcmbutgaxnpyxyjfmshennjjptutwvnkqxwidsoncrboxpidshmpnklkrvrxlxkrrpkaawxxjkgpleqniqmncathmudmhwryewnqfwewozwbzwrxozemrfrnelvjuqfhtjrqthzuegodaktngjajvpzqkakozfpumqlrpqlkhsubblzjrwaivkyndegcqvffohqhbyhoimqqgspojdvypwqxbfgzmonjybbinhvlxevmgoaajrtvttcktxlndzypezujrjxhemcbzwikvnkhwfzrpumozzvioxivlgkxmtcaijvdncmhxbvnnzjlozkmmgypklejacthlmnqejxzjsfaxouhaavbkxihbqtkiduqgclznieepzgzrhhnuydnupwijloiovbjtvsbypoiuyenuaqfykucysqdhkjxxmsaojsfznszkyoqzjtroizdunwhvoqotravlolttrucggoyptnbxgcefdlegihrgtuvdzlkhncamoewsnviywmrypbjbztnhpbknffugdqvxiijgaihfxzgpiasfflapsgwupcebtfbzwxwyivdfkeltwzwbdawvxpuskusjbtqfqnhyeifymqemhauicxgmdcybrplgliplwcpahuwmepphokwqpkrifizedqiwhdigpnocqkucvxeqljcwwsvpugnuusnvyeoozccicchcjyoisktkitdjjhnyolxmidzvwpweecakgiboktxruvvioppakpvmfusqvefcxrcfruaoheooqfonpyhaujrebpmtixjjmqtabbqsefjyqabgmuwfqpezxrakwvyirngktffumdiwngbackkddgaaivsrgidzivaofosociwyxvmllccvpxphxgjjgfyninoulbzbfnasqrxmirexefdjcviurxexguxcsssserpjkgoktnsavuhjmimqaajbyzpqxns";
        assertEquals("pjvwamnlgckeytbxdofsrzhiuq", unique.removeDuplicates(S));
    }

    @Test
    public void case18() {
        String S = "eotnnjlnxdgoatnjjdxatdtnalndeqleqadtaaotqxnxxvdauxdgvungqeqnqqqdqqxxqjtleljvjdxutjujdolalaaaxoequqtdaetjvaxunqqnuvtdneonggnoednunaaeldoqllxultjeaegvgajneantjxeavauvgggoneojjndgtvuqttjvuoejgdjngtqgquvexnjndxtgjtglgedqujanlngganegjuvvdoqttldquqdjotqluguvngaeoetjtgljeudlvxdoajxdvlongnjgqxqqovlxgejalendvoxdavudvxjngejjdeadtxjglnudujvjoxqlouxvduendvlaldtgxugvguxnqxtlxvueoeqvotvldnadaajxaauolxuatgnlnvvgqagjuueueuvanqqljtavnxetxjnutgtglvdooqqjeujdnlaelojexxuqxegttveuvxoldolovqdqvqjnjdouuvldvdloeqnqlnqqvannnjoovqjuqjavxjgtutlvldatdjnujdevxjjgalxadnluadvgneldtqvduqxojgdnleggqduaotvqloxagdgullutettdtouajnnuaevvvtjdlllettvoldoedugxovgxjoogtodvguetlddqtjnqjvxnudlqjvdejvveoegvlvunglnolteuajejqqodojgxxveojondoxutxeqegngudoqtlqxlloolunuvnvgodvxdgtqeugjoadxdnnuuaavvjdxjloaxeuvxtdqoeejgquvgdoveqajjqeeloevanveeelagqnodlultvndvloonodotvadgvalanoujjexaangjglutoglvgulenandvuqvuanuougxteuqllognvdgoeunueovtjuduolvuujagltlqgentqnjoqgovqxuxdvvuvolntaeojedxvjatqejnduuuedntjjaxgeujxunvudxuvxeetuajaaeendttdaluvgv";
        assertEquals("eotnjlxdgaqvu", unique.removeDuplicates(S));
    }

    @Test
    public void case19() {
        String S = "wzjsuwyjrdcmxekwbsxallgnxjlmutgjbdmrhgbpcucjvqnrvwfknpvklhdgehigjgqkjjcsihctcjgwsizjinhqkjirmsxsvazvtxlwedzbxcqelsikpzbhtcycnmrvhyrkyhukprfruqcthkvhuqnhwggldfsootficuzasynimilvjaiqwvuuxyfmrpjtjlnblgwuajsxeqyclzkjttfrezbikonzmhnkojqupxjufshybyffwryzzghwwgydvlbyfdetxbzamyvwvekorzkwaymciqzvqccxpcwfavyeupvdmnznpiwfftdsogygsjjmhyajxnjtfcniwruxpfncfssplucczhcgoiodzkrjeruskkprixwilxfswzwiddrfkwfeylrxgffisduhbommjldzleahgjtljrqjkuuumbylusaxsakbeomflwopxwenwpzvcecmdjrgfftuwxejqnmkgrwgxooxacftgcsmtldjxoaojfoyklivdvkdrpqifoqiwqwqddriqkzfjowepjqtykopezcwawjmqredbabsfkvaejjgjgrowzprqshwhozyslkqognfrkbudlbrvomylvnapnljkwuloqwxwjpwjskdjdgnfkvupkcmkyktomhaxopxpbetowpliqomyhenhkwrhedasraltxeetmkwucllmiranmolxfwytnfiecukjoqqxfglqomdormhvrlwjgjpmhtaqkxhwlzfeavisautcojdetshmnxgrztnrmvbdzwycnacgwivircaqjylxyirrokymzivbldelaghtdakzaklkprtwcgrkmwpwvouqddlfckiceqnkyagwxasemjemrrfvwyxhcyldawqykolnoydclgtnrpfhtavgaspoxbvnqabydgbeyqlgcchooqadetnlfcgowpaixwjkgufoirrcepvncggwclypfaeypaubywpzbdbfwwaaitcqlzxgduvvswl";
        assertEquals("wzjsuyrdcmxekbalgnthpvqfio", unique.removeDuplicates(S));
    }

    @Test
    public void case20() {
        String S = "xgglgtvqljttnnxtjljlluavtldntjvqnlxxjdxtenexooqjqxtlgtqldxvuuaxgouxxgeouqxtqaqnlvtedxeqtovnvjvugqdlvtdgugutddxatdljdxvtutlqxuqjuntlagogvuqnnvjeaqtddlaxgtjondgdjglnulevdgttddqangxguvnnqtjeleqnxgvqudlnxqqlqnxttantevguxjxqqlojoudtjtlednjtvlloqqloxtnanxxlagajeanuqvldduoqujxoueuexxonaaqtxagnxqquvovdnuluelullxaoqqoqvlnvxlolagjaqtdxvqoongnxglvlqjjjnododevdndxjxqloxeqxdetetojonlxeaejjntentjxdteejaduuvqtdajlxqugqveajnoanugevqlxevegqdolotudtqqjatvlgjaeltqtluvevotdejjlovguxogojvolntjxuedngqeljgnxovaolnoenqdenxjxevoeljgljutlqotunxqeljlgllnuloxqvdtaevqoetjjjqtgulgqlavxdunjjexoogqgdxlojtvnajqjvjxjqgvjxlgnlxojxqqoadeduegutlqdunjgjgxxgtuxjudedgnvladdqtteadanvggxjxluvnuojvjggoelnqqaqqudgtattalxaglevjvlnjvnujqjnuuxxonldlgoooajneojjjdntvvavgxxunttjjudvjndxxenutaoogtxatdeggnvnutdlqgxxlggvdanoxvtvjgdoelgauetljagaogejejuegoquqvnuaauqvqtojlqdnxexeagueltdoulqejuooltldejvxdatvlgdaeelaxqxuexeelunenjovlxaoaveodnexdxeovqnuxqgxjgxtvgglovlxqugtdjoaentudagoquugglnjgdneaequugqqvltudleattlutdxdqvjduduquooagjevtjdjeoen";
        assertEquals("xgltvqjnuadeo", unique.removeDuplicates(S));
    }

    @Test
    public void case21() {
        String S = "kjywbkszsawpvcwrvuvuqpublqqddzgayvtglvohyetlqmqdvspgohardxxttrsbjkrikyjahvdkjxcellbglifmqtjoyivuddiavpkzcbjhudqvigjjpbezsbuolqhjohrrdbzavppwyrpgilgyfnhefleluqvdmkonxdguwzkslbfwxmopkuzpnpngkavrdvlaypuxszeypuyrbyzwigiaeosgtpqkbxggplyvyxocnwvbhybgitwsnoyhakptnslvcbkratsmpluzaoufjdcumopqwrvnwvixhagmvdrxbvkwphcushythqfqkeukmjhepcdwmfaxjbbbijomdljhfdocbgydksyjwdppcvphnyiovcjbpedrgahnfkcpvrnpanwpbnazemzrwqizupkuowyvtndhkrvjnyuzhyuqukmskpgpzqxafnnhxibspkkyiayvgoinzhtsrpgajkinrlyggpqznycvbskyfojgqphvexqbpahrqmsqqpykfeoonwkzdpgwbxelweawchksfmmgrbmlceemhbytpasudondbxhiihymymshtxyfzssaunbmhqtdyurjmpprhevyjsgsyqmxowuaablsdsipvscdckdpoedwfhjfncuzzulwdiiziakfsrvlqxbxgcracskvgxqwbesdfckmtnluwinpuisysgnnctepgbjbyqclfftupnxlzehiknoovupkjiupeomfhydqloscmrrsflehwxjhqrnbssgrmhniogmmaqseeiqqpawriycjjfllfqtfsogevsqjjnzgzwzbnycrlntqtnvtnrjrdrvqktxogvwjvrpjicurfvxxwgephrhejqhekhjgqsmopakwoslpevkymrqhscyflqtepfecqoauepglwxskquuboqkxfoxdjwvezdejlrjbbpxenwtholxhtntdglqgzdsblrcikdiombiizlicrgmvmfzydqfxpvjkwtoztdtp";
        assertEquals("kjywbszapvcruqldgtohemxifn", unique.removeDuplicates(S));
    }

    @Test
    public void case22() {
        String S = "vnoajtodtaauotoqougtltvqujxqjudvdxxnqnxdtxdedxnujaggxvluudngqqgnnoadaauanjvtjvuvglqdagqdlgolnnqjndtgljjolltollqulntoxntjqqgxvqoggenjnanvvqelttenlxxlxgugjdttujxgdjxjvovnxltvnggdnounnjtxddxtnaelnlvjavqlueoqujlxeneteldlavttxgqnnqqnxgevunvodxugojejdexqaadujgtgvjuooadnuguvutvqnnjjtxgtgugjddjevujuevxadvxleadgtvvggtoqevtlxgjevtdxtogagaxvdjgovlxoqjexgtattjjgeengqexgveaxgquqaouauxntealatnvdalltgtduvqljqutqujjtdaudgvxluxjjdejnulvaejtttljxulqjtegodjggntqxgedttaluonqqgdaggeextqjjxevddlvtngndjoaaxangdexqjexgoqneqtxueelaeeugtdoejulgotuettutaexxaxvatxvgaoeqouauvtqnxujxoxldadoveajaogdotjtxanqlljnudgojxlvxtjleveejuennjaglavjueqgjunoqndvjulvvaldaodjjgntaxevdlnqxggduvqntdxgevgngxoueddaaavnlqxldvutnxqnanedlodvtjgdatoovdvuvavqatvnvldngdvaegqaolejjgdxexjaelegoudtoevqdotxjggutnjatvuoqoqjxudnaqjuantujglxlxdgaeajlolgvdajgdauveetalnddototxtgqvvvexntodddvjqveggjnelqvtgujogvgvnttguvxtdoljotggjntjoellutxxqqxuanatqqojtjnlueoejunejutgtvaaeegeggqvvnajtjlatdqlxnltttnquenaqgdjnaqjxaeoqnxetxaaqqqnleeanvjxxaaxugdnealalvo";
        assertEquals("vnoajtduqglxe", unique.removeDuplicates(S));
    }

    @Test
    public void case23() {
        String S = "spdejbaajkuqsxjgcuodfeyeeqxzipykxqhcunwcnvplsyicvehkdvlemgvxvukqawuimakfngjqhyeqjjjnczhyxyxzvonmhdluybqkjspyacdmjbhphttdorcczgjcpmmvivpeimzsftqvvxvvtevtuxkdhuvxyiygrhivefxvlvelmginwyhacbkklmlydbxosgdzefzphljhnfyvdpncolqhyvbcbxuqrbjccnnuoaxxsgmbwdwpglzmlerzozywatrgxafruepxvptomutprufqasadqzdsbqjpmxmszcookwmnihomuuqzkiidynpnmzgdabibuszmcqtxtzectfjruugcnqlzupqarjmyzakyudvovswgdiebhbllehjidukdralxhobtivlwkxfeyeczcrdofugvjnwlgzxafapoctkvfouoabrzwqrkdmupbzmercrsymweshmoacmekgcxvttbsiisgfzywqpkswtcwzgapvgwtfqdlivjxpisgdlpyhtcrcqbaryppskiibrevivoepsugyjlnaigtyrzylwztkjsmftmooakgclxchmgrzfjegzpsqmckeyrwglbdzmiyngfbimsrpsltclsxnmyvpvyoesstsalmufmvqhyadjkyqhomzllmjxtpqfvulzcrpleuqxawwidnzmznztcptdneyttjbjlibokcznadhwhcagicpvuswhaudkpgbvvgeoebdizhwwduafyrpfkktrlaohqqrttwwqczttdxeciumxfhhilyfvjedwpumkvehkfbfjypeftftqbegrmltwkjwqfxyoyoiwcnzvsnrqmfultbpurlqtzmdzjvgdfofwytaibchcqvoivcbarblxjpscvwmtddvmwnsmqiywbuvrddyzgbyxioypfqbcfulfyioleefvnlwitetgxfwtzidlgvubavhubfnkgxaxfvowpyafoxfnbhkhnmhuximlwadcd";
        assertEquals("spdejbakuqxgcofyzihnwvlmtr", unique.removeDuplicates(S));
    }

    @Test
    public void case24() {
        String S = "djjenvlalneqxqlqtoauaxxvveltqgaovquaendletgvtgouxvtoveexojoeulgqnnnauotjxjuxegvvedoounxlvoujajogdgteadjlvnvjuqqoeltaegdqxqgjganundlatnaodaeulvuonenogdvlvqunaloatlxoqjtolxjqqnxvtollatlauutxnodjuaulvuaojeqjaeetlggjnuuqdqneltgvevgauantaxndugvxuaxvlxanxxgejqauneuqdvuatdnavagnaedjajqdenuduuntqoudetuqgjgxalnleuqglxvxoqqugdqvduvqlqjljaqeeonaeulddxjlxjleqavugdeaeujexunnetglvlgjgvxtvdtoeqonuvxdoqetudajnojdaaqutuvuuuxvgnaevonadqtvjlxoolddtgloaeedvnndqtvqujeeonqvjjvvjloeldneovqanaddxgvxgtegggnjqjooeugtltxlvvejvvoxljxgtajngqtajxttjxndaotxjtalnoteuvdxxodouvleqvjlljqaxedgljdnvevvlevtxojavgooxaodnvluouonuuqtnjjquqtvvuatgqdlggdjeottoltuxdquvxeunednqvoxneooutdatgueqnlvxdaqjjduaadoqjandnnjgqugunngoejxxujlolglqundjdqvuqjtxujduagagdalolgqxqvaqjgvxaogxdntuxttqelxtjdglxgqtqetulvaeeodqadjudeltxgagnneetgtggunevoqvollguoxeteglgtegtelgldjvodqjnvngtnojtlqguegjjuejggojeuqtgxuxtqolnuddoooeldauunvndejvtooaeotnqqlaadxqxxolaqjegtouxgengandxltgoavqoeoogdlnldlututdvoxejvgvnxtdotxluoqqvouvevnutudxvnvtjnatdtqlxjunjxavvdq";
        assertEquals("djenvlaqxtoug", unique.removeDuplicates(S));
    }

    @Test
    public void case25() {
        String S = "aikffjxzieknrzjjrgfvmguaqcnbdyonkrlclqjhifasdpucqobivkwlgzypzdxewosvibjgebyadidxfafsngdlkqiaqqotdznsuiflxyfixhamqjzpmygedfnuvnawtxunxeojzeffpdeutszixxpcrejgfiadplvpkfhmanjrzmbeaeozkxrxgcsnrnvwpxglkjmpfogjubpoupvnghhhsgrraehonseyvfeorhbxcwfiyahpuexfaglpmbtsghhuptyzlkxsgdnotqrkzcwzaxocfmdsuetugmybqrjhoswbnlotgvciiabjtjcxarwlduwpeipkfgphfzevqsxcgtzafflzykcrwqwjqesscxrirmuiqyszzafrsoibqyvtzayxmwqhfkryfsirhwtnnkhfeltfnwrpugxqtqzkshtdnwjlqileyeiqpdtoylwpalrfjppbkzjkhuqhkrhhbpcmljuchcudfgetlbfinweussfcbborkufgumbkspbnovrwlpaascgvadezwbkchjcutxwibojgnxwixigcrifhmrdxmuozvperdhdamruqnfqbnfslehgugiisthpdoxhkfpvwybtvmnkstchlnfykscfctvbmojfioytkpbymsryjbmevnenqmkgihrooolagdmjgccvvefkjzbhbbhpbkpqjwjtcyjpwfhxxsircrngptazgizseotnshuqebdlwiscztutmgapnwguvueqmjxawzaaueesffhltnspbqdzyijptuemwjsnapaafoobefwzjgxbovibhtlymgkajwgrbyabxztwwzhuupmwinsjqmmsdlmkbbxljlafgpumpadanewbpvmbibvsjcqfoegqvocstbcnqonslxltgqkwwlwmagukvfhuxjcfxtbnxrgakfchnepgnwlavbchwzxhdfpkzqpggujtxrzbiopmeybuucmaitzawcodovruqndldevtrmuqo";
        assertEquals("aikfjxzenrgvmuqcbdyolhspwt", unique.removeDuplicates(S));
    }

    @Test
    public void case26() {
        String S = "exqnnndnlxtnttvldoxgndoeutjnentaeotnnjxxdttjxggaljvuquoqaqqxlaqetgxaulqldvtvvdjtnavaletgdttuvedganlogtnvtnutotadujexvaluvqvuluaxnvnntouqglqlgaogjggjjentqjqeugjxnqugulledgqlgugvtoltonqxqvgajlaaovxjxloaqatnntqxlaquxelugudtooanonetoulggueqtxnaqqvqqxvooqxqtovlaeujvnlxtxojengxxxujuldvoaqjaqeujjgqetlntxjlnnltqltvtaedjvgnxltogutueeuuaaggovnvxxjxaaxaexejnqvanlgglnltqjoenvtuleotjxuavovjulqtjjgqvavnxeogeaevodvoalllnqvlddutxvogtdoaeexguoelntuotuanqduuugnljejelngndujgvdgnutxtalotooxdoqdjqvntjvvgegeetoqjavtjenudvlvlujdltnqdqujjenvvetejqloladxuqoqveloaeangqteaaedxlnavaadtnaqdgdtxetlaednlqoglodalvqtvjqelevjllqjlojgdadqounnavljqodgaddajlxjdnlxeaqeexaejdjjexuttlqxvgdaqxqgxuegdaqnxduxtjeevtlqnultqdagdadtjejvogognagveneoqvttujxlvxxoajujjdvgavlojuagalqjunqoaltteaxojnqgotjoqvqvjjqotjolqjuaadougaqxnunxgnndodaeuxxjgtqnvxjxquqaxqlovvdgxvnjnjeotodqxvuleadlvauggjtnaegtdxuxxdajxddqaojxxnvdlnvvllxugqtejtgvenqgnnaqneqvnjdxlequjelaaotvlqddtutulqxqdxexegaatjjdgutqalgudvnulateudqqqgvtdvddvqxnjxxtqjtvdaunxogtdagnqnnje";
        assertEquals("exqndltvoguja", unique.removeDuplicates(S));
    }

    @Test
    public void case27() {
        String S = "awplrxxywxmvbrdgnchtwqraoeeqecliqhrxkbruzzlpemrecbwmkildtsjymskqdcuogoeprenptccfwanmxdnfgxuajnnodncinoqtxvvbcijxqcozqtdncqeslrvozdhyauxoojwmbvhqwrsnqeziohqwtcbjmrzvtzpzxyycszzaeoreqyyqvcavpbrdfgqmhdjrrtiaqchroaeqhkvpvkwkwqzyqrxwntuitmcfoqehkginpxlvxbpjdyhdihbidasgatijjqrihozbvubtqubrhxjygwumxopiwrekfvpdisydrhqyqgrgmqzbpksosrddfaxftnievcyxfioknkqrkrpoxnoxwmskshkcoarozrbdwsieiuynxsuirljzeufbxqfaifrtqnuoqfelicglzuuujlgjhchrddwxurftijrwjuchcmnnqntzkisvljrmqplphrmsruslrogexoocawwzdrfqemknnoloegttfvpkvrsyruflqkhwbrdzwzmvlvypplgkbzdkusnncnkpyjgzmystzvnlsnqyrzeavydvqhphkozqcnhslsylffddfhdzeyrxvzlxtxnffdmcoknunrzabgoynaczzraidirhivvudyvojumcoypcyldlzbzvazahdgfldgbmvrbzlotsmcpxubhqcxofdwytnexrzthqlaupvyiwacvvkgxwisyivlvyxrpqamjwmtvcpairjlsybjeifahppjbomdusupcuyvcmqmtsxxbtpesvblkjptepnqtvcbgdolaqrpfnzjuzlxwpenhlvtkjhafvaxgcvvxjpnamayrlrifivcybyzxgttidmplypxhpmnztvrjgnepodlngghvohtzfjnvcnmdibfzzkxcecfaoqcsjiugomaglrnfkjqklimhurkwuxcnnqzvakfwmdmlzcxhamewxpvpyvholrhabxfizbgpswesrmtrmemmnibothcvrkggv";
        assertEquals("awplrxymvbdgnchtqoeikuzsjf", unique.removeDuplicates(S));
    }

    @Test
    public void case28() {
        String S = "oajgtqqlqojqxonjdttjtujqeouuvevtdvxjxoggelnnqtnqxtoelvjqlnvqjxnuvdolvntodvaandqlevlujlxaljetegoadqetunjuxuetljdgqultqlgatlxjougqgjgvlojlvuddjeloaaxlualnuuevneelgajgqjveqxnvlnxtjlgonljddjaolqnuondndodltgvagoqjgajlxlunuuaexxxgjutqoaenajevvojxoxlxxlvoggtungnueuatonxonagvdledoadqnuxolaljetvdutnxagqtatuxateojdugduxvudogexgunnquoeevxxdjjgjoxddnatgogtdqvqudxoaqegnxexdnlvjtvjetuejduvnuvnooleajtjqjjqlluuljqenegelqxvovxdxqdgtvjljngvqdtjegjeqtxjjnvxgdeotnaegllenjjoqjujaggqjquqvduaeenulueexajdouevxdglvgqaonxvquqnvleuquudtojdllouxjeqjjeqvxjxvjdlqngttoduqeqqjvjlnqaldxjolutealduxdaolloluuqdxvegotjanqdvjtlvajvjooxqnodeoqjxenuxuqlevqlleelnqlqnjdjdvanaxagvjvtxajoadndlljgglqtqdaevttlvjaqqovjqutjdnagveunegdlnjtvjexgttjoxugulettulxgjjgjotaoaxegoqdqqtetqqugdvvdjvxtvqaglegdlqoqlgeqlvdxvavoaalodqnevnvngnqvlaooeoolovuguoxdjgoxaedunnldntavtdaljvvexqdagqalvoqjxgjqjetttjuqugvagegutunuqnlletjnoogdqltalnaojojgddnejnntxjoqdlljlxvoaldgxjdnudauggonadolnexggavjxgeqqglvxgluvjvaqlnlvedxqeeqvoedaodjjjoqnuaoxeqgqxuantgjlqu";
        assertEquals("oajgtqlxnduev", unique.removeDuplicates(S));
    }

    @Test
    public void case29() {
        String S = "woymbhnslffuatuezxnhnbogefgtmgannjxcxfrbdyqxrwhfuapjxevuilrdguffgprstmhnqhyqlnohjfcphdozkrdstxwbrshcnjutstuienzjzfrrmikyrvqgqkawbughrwyarodwdxatcfwnxpdcjuiuqugrwdxdvlnajoqdfxcwydowvdkdzgionkpcxektdzigelnxsjoafxzrznxqjgtcwkquohdtqcdahicmcxopokwhxgsyaeeegpwnjrhbmdzrcdkbzhvwzeptpvafuecrroocjbuqfxznpppntxkpuhtdakdzvpwokxjqcmfjzdwoucyqzpoyatpkwohcfltzmricwytkqskcjflvxhjqhrglsgwtagtxplgxhnvmegtylcaybhhedccmljaqjyogzjcrzmyipbmhiwkemkqlnxvyekxyzfahzeerjcabxzixgqbbecsnoctmupnvawajelxhwfqbdikbvhhtkakwblhbtvdwwzsqhivkybooywckmfnglqndgiqafyfnfplyikyydxlyvjhuurpotjxntyzyubnkdexcglvilrspfbprtpbnhhqgucjzvopafgksizusxggphrtjxwonetarowwcseprtihxiufzvalczpsctjublalupbgbtjolnskopfsibhlqiznmfpgqkctqrwbjbpgxyljnaslclkkceypvmatnktckfvchlzhryushhcdlicmzsnsemgzxbledzsgjffwtksrtwghjuukcxbngkoypofwkjgfwgmmlkolyqrpszuqraduszzenlvuzumxijwipyaelskagwfnvlurzpqqyesdawyiczesqglisqsedhlxqdstqevpqztavynvsdttqcotzjxybbcecfznunobxrownurnohztqgyoroenfdimkzuoumemjqfshkwvtyzipstbazadhyhsdmpufgmpwwxxvhdioaaqvqnijgzwceikyzlok";
        assertEquals("woymbhnslfuatezxgjcrdqpvik", unique.removeDuplicates(S));
    }

    @Test
    public void case30() {
        String S = "laxtaluljetlxqnxlngvjvgtnxndtvaujlvextgqlnqjaeaveexajlnqeuoxaeunutgallndeaajvvvqdgvgqudnlegenqegdqjxqxolqgdjludnoalxatuvvxgooudedtulxetdaxgqjgtlejoqlgjvdqdvuvajtegjndxjldjaaetevqaajegtlxljauedovotlgetdqvjooegvjugqtggjtuaguttognxxqxaldnvetxtetdunxatnggjujuvdutxlxvootgjlgjqetgxetvqqgxggxxeltgogtnggujljgxqqlqdnjxjtuanxoaogqagjealtvgndudgjeenxuqagulgvdgutvexeajxlulutgotnnodjlqxdxqxgggdnolntloojvttdtjneqaldqeadjxjqgqjdvlgxjxvajguadgegxvjtgxojqluoueangqvanetdldljlglaajnglenjuxtqgetxvjvgqgdlxauujqltdgduavdxlvlglvxnoljllgqgxtxnnjxqjoeeqdujgvltltqnelontetvteaqaeojuqvaoxlgevgljexqltloltvttnnajoeletjqxadqtvnlqnoxdetgglvgljxvqqgxoaodleualtdaxqgoqllentjjoooaunonduvqldxlguedtogvtxqlltdxaglutxntvaveugxavdodvqxvqdxjalnxeluoavxljtvoutxoqxxjlxleexldxodlajleqgqedajglotxueeaogjalvloxqgdellunoejtoajgettujqovldxltlvtltgnjnexteedjjnotdjeaeqdeoeggexxjetveetgtjetvagjuxqnooldtvtjqgqutgeovvaogqadddtelolevjlgvlaqggxlxvdegajtgegjelnqngdqjdotvegjeotojdoojudaglqdojxqudadglugtqxvuguxaqqluoveutdngvegdqevnjgtvaeaaajqqn";
        assertEquals("laxtujeqngvdo", unique.removeDuplicates(S));
    }

    @Test
    public void case31() {
        String S = "idclvoyfzsrzasxsqkpkpevglgvptlboyhvfcdghkzpziqyvuwvngkwxvsmfbgkehtjaoouboltlocqfmaetimdwmykhnbbnywwslfpnhbphueymwjvcsbknvbndkgyapsrubulirdiqglrpuomwikjpupynflhcnrpixkwgsfulyhckvusfwstfnvhlzxbaellytkzyrgumxeeakmbgsqcdhlypostzsjrglrtgldvjzxauzoxzvfztfysfnbbvukzgrhlzesgqugqgihrccosumxezltbatwpmdidvogiikrqfgfmyxitjcjnfontrkgmdlbsmksdmiqseowubfswpiugoqjivdylvralbvnddgtlbtwgszitpjvnfuqrdvstlwkqqrypckfjwexcvgplcqixzmejgvmthomdgpgohtbqhmuubtqwbijiylwheywztqzpbiaoyzdkgrjodcdkzhuopobpgwnurpkujtackwlztidwgbaeawgmlobdbxempnxbmxngwljwktykbzcsvyyzcidyunawhiprmcisufyxrzemgvyppdcdgxncvczroaxwdjtmlfgqgudgrvogqavhquemcjciedlhqsjymxpgwnnpilfwxvtkategrjthnrkvndtteyxwjxcyhrfgmctaxiixunhixmvamgezflcorltoxlrdxnwscfujsnffkmwnmsrsecjljytgqnyiwyuahwfywrjowvdfihozlqxtcfkozceddimgbbpgwmzolgoufmvxptufaqvvjcqmcburimlnurckuwajblrqltyelgjowcddmozgldastvepvcvhxyuswucczatdxtihqwuhtyyjtqpirjvkuricsqihnkxorrrwsoyfihkrzqkfcxlgwbswlafzohrwfkhlvgcqsnvzycdfnmbjbxvycezomostjvlwbygahwwlwviisjvntmjqfiaaxtriztgmvmumzcmpuporworvn";
        assertEquals("idclvoyfzsraxqkpegtbhuwnmj", unique.removeDuplicates(S));
    }

    @Test
    public void case32() {
        String S = "vdgqevttjgvteqvxaovgonlejojdvgugndelgdxtdoouxdgeqogotvelddtggtlvoqlvvnetdoadtguenvnuxvanuljxlvleqjelltojonooqleqvxjjlnxodxxuvuedldoxtxnlaoteejuloetuxqaavolxvdxotlqvugdguotjjvouuultqlqvgqvxttvqqloanejaugnlgxaogqjgxqgovadqqqjdqlddxunldaaudtdjoqajjggtguutlvglqonouoelxqxunnlqqvjajtxaavaegqtlqegulvnunxonatuotvtjovllnqovtjettdlxunogevtgauvugaxdvajavvnddddqjlvonatjqvontgqugletljggaovxaqogtutoqlnxexttdjnoluqtnlaxdeqanvnqxongnxddtdvjqtoeexqaxqtltndaeqtqvxqavuvuuuajodvluxqggqoexueaxenlexdexgaoqeolgvooxtneaxalgvnluvoojotvldtovdgxjalxddavvxqqnxaxqndodtulvvxodggaxaxovquegudqvuquenlluvjujudeanjauoaolljqddnogduvdovugtenjadgetntanxduldxeaundadqnnvqodalvaoaeggvxnvxavjnnanxugxvxxnxxlqnaxdxevxueaelqvtanqagutdtqejdgvveleettjuduttauluaxqeqjtnquunjugqjntqqjvalnugvdjoulqvatjgnqnvlxglgduevuludouoeovggoqngdvgveeoveoloxuldgudueatvdlejuglxvllgjaaxjvuljqxxqjqxexexoalexgteenajxduovelttetxjvnggjotalvlgjlenoqxxttodqlxlelxgjanlutnqvadoodddjlggjndvootnvvdgltlanndgaaaltjeqxaqqoxeuvdjtdveqlnjtnqaeluvjjaduuvaedldjqnodunn";
        assertEquals("vdgqetjxaonlu", unique.removeDuplicates(S));
    }

    @Test
    public void case33() {
        String S = "rqqgcsnjgclisnadotmdqkibgbnrkyqktstofsidibshrpwarfbuiquyumhvotspfzdbeozaogbavoggnlgotwrnphyonzmyafxksotrdbppqpvgsnynjicailreezlcoztokgnwdhiqesixcwryprknbqkqfdobsxunjbtpopaseuhncrsgrszrdbseyvwubvpvcywbrhlkgqobzgvljqggdqlsrdwfjxvzvzimvzbbloncpsmixosyaahdjyfeylhtzizwzafpxtzmsyiohgcettzrhuubwkwhwngffjctaozlwmpiismzmzrfbtglkcmrmbzzxuzexrqhqmmkgmxycxqfttxhgtccfbrsojuroopvmpdeofxunbtsxfytuhaptlhklavqrdmwwoxdspvukggyxoixnsjbwqwiwtnmoojseasdvsktyenuwekqjnjhacunfpbadfbcoldktmcxurmgourkkfzlgodpdtpljaqqqcisptaesslmwsdhzfapzctmskrhfaosjmshpehhhymhtzwypwqjtxwmkohxpdqwsgihouwugewkwlyrrwdujsrkftezjwsjaypcsnkhwigpixadyhbgsezhwgfbgpsolgtijvbsilychdokreefkqdrxtlboetnzsdqvvshwgmpkkashkvapquuykibkjzwczvghvjjjfuubyctgvlqhsrvhbcoqphqtmxewmjeddqgjmftcmsfgicdfarssfaikbawqkxjaqpbzzdhmorayumjpmivjxvoquvtcglkdkpptmcgwfvqmcobnftajlxqagpphzndmlkndjitibmuvqsnnwjenxbuilotrakvsmpvtpwnnqivixowvlvbmjyuhgdxwwezxdydxwdtlaxpkqtlfmiaafwbncsawlsxutejzkvgkznaacvdthqhbftacqgnpvtuenvhajlaykidpvaikglzvoeyjvorvcvokeafnfnrjtgaddws";
        assertEquals("rqgcsnjliadotmkbyfhpwuvzex", unique.removeDuplicates(S));
    }

    @Test
    public void case34() {
        String S = "axevjvqeqgejajojxxntnqagxengqqdqudnganvaqdttvtqjxqoaddlevuljajgelndddeltuxodlxnejlldglaenutvojeqtvtxaxandalxeoeqnxdongxqunljexqtdjdudxtdxendudgxjjnavunqtqdtvtgdxjttqovvxnxduxqaqvequauouquenvqonleldanttgdjltlttlvnaxxdalddttttxajglgjvlgdddgvluooldjgvajtvundejtddvdnndoxqevteulaolaattunteaotjndvvlxquqdoanulgdxneqxxgtduanujjqjxgavelovqujlxexgogglunnonjgvxognxuaqadeveangvltvejdgoaqduvtddllvqgdlugulgqeeguudnvvagaqajnxvladnvtlvedndoxgelultdljdgqoeuxntdjovugoxlojlxaqtjtvoxaxlejxxqntvxdaloxaldeulgegaoxltdtlaqtxjxeaqevxxuqaaquuldgdadtttgajqotuooqveqadnqdxltvtellvldxxtdtvlqlnjtuqvjvnooeujjaqotdovqnqlxdnvttonevjogajajaaglvevdxxdgagaolnnvjquqjlelggtxtatuelejxqvaxlunjqoxeexngqgtqlnnoltedetgvutaogaoaxoalqdoqjuglljtununnjougxlqanoeujtelxgutdveajnqtvlalqnqevjaeoxtjettgaudggnuldoldlaaxxaldljotqjjvdqtjllogoatjetvdvuuedgavvdvuuoxouljggoeuaotlevjxeqnlejenglajqvvqlqqllqoutvqxddvgeqxdjvgqdgtujtvjjgevnoajuloqadjvuvueltuualagglgunvovanatggvouoeqovujeeqngdnatdnqjduavetqgdeuvavavuqvaxenjgoetqnauovtevexdvodvojtqen";
        assertEquals("axevjqgontdul", unique.removeDuplicates(S));
    }

    @Test
    public void case35() {
        String S = "ujgaeduuwdqgaqpnrllvbzatlggtxbxdxiindllevlimxzpsxvzbtiwpusuiledycjacvjjozknikbkmcmponbvlxxhrugzpgpjligwnhipjbzbzyzzximkdnfedbjvirpyovmyfmomnmhmxqkviknxdndbnrikkshyptztxyznxmbdcudvfadsfpvberkajdczylppfvuzenwhjzzwlhgnmodsygdebvirkmovlyiwyafksjvtjkygsdemsjiximrqdkprsvkxuenunlcbcsdanywvbfuuxihrwqyquixwclpitdwkkoudavsnhqotsxgrxgiylhkmrdfovlqlmctbpyuycfksibnjrtrzylxbtaohwtkzriyqvrlbemstjicuadwvnjfvybvpfbcqqlscmmkdhhgruapjjklwichxkgrerymvnbgiswqyiodatuuxakxjazcgrxtkxqoswrtegfpnglbcxmolmrpuvzwbbszybwptdhcvuyogqxkeaoxdrcrscqnwmbjtpidcifvstdswoyxiahmcilzfbtzievtpuxiwvrqrmyfatkfwlfebveaztpjoovilxskvxlqpirsaazuozeppuzsqzjzlozkxpgplqddkyzwaipxknjktbuwbyocvqrwngulvbczsmhszacpswnutlutgldxdyrueaoqnolnbvcbxxcbwsxfgapyrccxcdczkiceeiysfnzezgdpvnkicdesjemicegvopjyxspikqfowacifzdcevydtebgcddxeuminqifetiwivcbsvtqrrlpfimwzfoucslzdtvojjkppthijiboodbxnnbwdaphulgvpuooxsjhtsbifnpamuqavzadyugpbovyuggevjgpdsphinimgqawjenhbdbldnelsxwzzzwqpgiuylkytgtpffrlwpheqeddhaaqcbwcoadxgdlvwhprqqpecvgcvenjaishqttftvuaxqztowjfxs";
        assertEquals("ujgaedwqpnrlvbztximsycokhf", unique.removeDuplicates(S));
    }

    @Test
    public void case36() {
        String S = "lxjueeeqdvlxxuganlqvotxggovvlgottjengxnevqqjdxqdjaaxvlonxvtgtaqjvtqgntvalungjxqxteoggdddvxxotutotqangadgqgquajeenggqunjaxovudevgqxlagqgjtqjvtaeequendxqajvxxanjxvtjgqjgnaeleggejjnqvujdatxvatvetxatajnxajaduddudjeevvvejjgjjaaxluouotueuqqxltgndadeojlljnaaxuungqengnalejdoeojdujlgengdgoeavtvnaaxenjduqqujndglqtdxljnvjujdlvdategjvoxvgljjojxvlgjqqxgqoaevlenvejvxlavodxvxlonlldalejgaoaextddglqnloqdeolqxaxvvxxuvluatjuldxxnaudvevqtgjxgququuatjqggelgeutqovuolqnnxgdnjdagonoendqouglejtqxjoxlxltvvgvuqndlqajgxqoolngotnoaeduqeouetuxggtedeqaqtgegvjuagulugventavxdnojnadjeuqgaonxtauxldqjnongdenuvxlxjqagvdouaejlojjedxequxxttlugovottxgdeuogtjltjgdttgeoejgdoueoxljetlaggdtgdaeuxoaxdtdvanegjjedotaaeeldjdlededdvagntxuavaxavvatdlovuduanugqteoxdvltujjeqvulnqaxunvggggqujquutladxxnxdeeatteloddggoxdttdeulggudntnqttxntjlelovtjnuandlnaqttevuxloxeojaxxxettgxotojtjtgnlvxtlnentgllxodejejejovqoaxqtuataqnntaaejgtudgxgovdteddlguqegloeovloddtatoajeldagqlluodtetdxjedexoeaoaogjnxvvqeqndadveeolnqljgetxxdxuajgalqagvduaglogdddjvuan";
        assertEquals("lxjueqdvganot", unique.removeDuplicates(S));
    }

    @Test
    public void case37() {
        String S = "ursurtansvjmauhbtfqbkfmzdzkubtdksuooxyctxwgmwetqhpsuablthliknnooaokienwmoottpuntbiuxwockswjduirichtswflrxyphmcjcrassefpcccehugqmqzqlqguohdxsecvtcqxyilymmvpykczujzyzyhzaygrguepekdypnoqacqslcnpugotkjdpvtryrwoxingviszjrgpoqzusnzehehaxgohiuclrntmwxkmujascouiydtytzdsakljzlfofytssighlissaykwfffdslqlbzrcdiiqqooaphyawaydltkjaajfkvwrfwtazomigrwbjgggwcncecxibuuzxpvvkjkdbhspytkrimqzdumilzcbifrrztursinctqsuzanmlepcpejufsqaumdblhambpecizkqzbxrypdjegpafxikzfyjbtpbjaxeynuuooisdqpgeynygmaywgdodhouwgartksuxufxmyzppoumazrbzeqtjxynvnaapgfsbasbxpyxjakwkiluvhdemopzsepmjrcewihfxeslkhgejwduuqcmrkcxdeurfyyuvmtbuzcpssxppikenqyakqyegefjaddnojofxuxrphkydvrrltepwpoflihoupcrcckdpluicmkzcpsaavgaicthtbmtyrvpivvbzwsthdrhaqvljmtpxbcddxiobdjhnqcrapeapppzfpuxmvpzdunlyzegojuhsmrujbmusilbmypgmlcykxufnkfscfusrepenexlnrntfphsyolmpxjfhgovlxukbacsizmxvhpghnyunitrbfiymgwsaldrphjqjavkifdsnncgqpmojtafarxaucoeusqbkrgdodbfcdwzvibibdnujqlzaxvbzrtutdeqngjeojyijydpcwjlptxfozsatscbkkkhaunoowhfjbyqypkeugzzxgvaefmvxscepkfyzjmsxfeeanfnye";
        assertEquals("urstanvjmhbfqkzdoxycwgepli", unique.removeDuplicates(S));
    }

    @Test
    public void case38() {
        String S = "jvunxjjtjujjjteqeovjuxoxjjjoavqjotetgnxdegdqtnavvojlaxnevlnlqeodxeeqedejjeglldjnlxlqxaxleounxqdgljdlluqjvealjtaqexdxlqvngdvgquuuanjtnuuluvjvaaloejutnqeuuvngnudxlududjlnjnlnqvjxdxtauonguqjuovjvxqaevqnnludatdqnjxljvulljtxtqetuedujjuxxljgujeejtgauvnxlnnlvlgnoxngdxqqlgltunddjvnnqaxjxuladgojoounutnngavtlgaquexounnunjveedelqxdexootjgqtegdvogdaqddtnueoedolnvovgtvqxuldenlnetounlnanvnvldaneonxxjueguggvllvelqadullaoovonaexdxjvveatuvnaoaglluqogutnegenoagddoxquoggaojeeoqltlndgejoduxjoqadtegovdunoneeoxvduquvnxaodujudjttqggqdaleoluglgxluvvejvvvauqngtjggtudavxuoduteoeqduevggvtogugjuxeledtvvvnutotdlvqgejvlxllqqgxxxvtgoujxqueuujldlvlenuataqgxgdqxuvnugovgeuvgxjnndaquoldadltdvaneojlatnqaeedaoqaaojtxodogulldtllxxoauutjntuxgoujqexduotovtlddetejnueoelvjouojlvelguxjleuudqxqoevndveqxlxgulugteveqgxtedgdljtgevvxxqadenenljnojtvxoadualavoxuotlxnvxdueuneaexdjneluvgtjuojdoavaealajuuttvnqvltvxqoxxonxjlovljtdlxdqueoexlagojvavduvvejnoagqvajdtoadnxvldllaenxeaatajlxdjuedvvtqotdtqqgovvxqvalttdxnlvleoxuneqetanvnolodjxtond";
        assertEquals("jvunxteqoagdl", unique.removeDuplicates(S));
    }

    @Test
    public void case39() {
        String S = "fvyryirxspxjzwrlvnneocbbphhvbxaezrdfsirpordxdwugzswqqzymotcveqghfjroudpjwygpkswgpdpatvzbpcrnxwlcsmxsffqeipdbuotcctheehksbfsmceapbirajxhnyfljrsfokelreuottntglnaoildkhvaomtkpiqrvqzegmlgephvkanxnuwcosjnswzdkgewaacyiqbcgmhfrijhsqhhpmdsxjeifutoxcqwzkrnnqxsvqhdfttwxyvrgdsefgjeoedgjvucuveehlxvrmxqhcpwxvwaacxtqidczwiaxgvcrojcieluoyielyesgqufmpmlukdefzzczyfwwtqqvbxkgvccuwaamrvczsdtfaswhaqemljlxfkyjrzzpcqrtzlrvyowfdsghtugkgrxvxbtsqwtifoybvsuvcbeledfnujwacmlpwrwvszuokbwzupkeomfugfxewmbkrtbgxbvjohuvhafrzoojnyddlpufuvevpnbozjwnvdjorpusfayzqkyqwcfnjxnresqvexkesvyyippigrbulxpdnomwpgyrcbginvlvwlpygixqrzibslmfdgrnolnehxpuygqumgecnwovhpullvfxtwfsndtqigndrnvjmwrdbzbppnahufjggjecvrbwqmfictipqlvdzmvyttxlwhuxdmvkjmttclcrctynlsiftosbcndwmlrazebcikmhirkmavawqvtpqyzasxexlntyuxvsmnakdxaoyyslyplnplbkrctbylifrbrjezgogvvmoshvijzhmilnfqfoiduxgkszpxpyqkrbnqrrmazdqdqvrvsogltmqlzpalsirzqmvqirohoeocltdntfccrkfxjyroxzsgeesrdarjddxnbuaihulaacoggcazrjcmmuoknmikugrnsulopqatrthtvsofnkdefuehqjvjinmegogvddhyhxecspzbfrivkvpmlu";
        assertEquals("fvyrixspjzwlneocbhadugqmtk", unique.removeDuplicates(S));
    }

    @Test
    public void case40() {
        String S = "ugouutuuvaeuqqjqqqnlnnvenxugoquuuodonqqqqoxutlvjgvutjvxajuegujxxdvejaxxdxjnuxleegegdadugjulluoglgjgloljdgouqqxqovgvetxjxteauotlgoeqlvuaxjujtedvatvgulgvaqugjoxjdxdexttqqagegjqnaeoqgddggdnxxvnjqdqaoeajdjvgxnqxelvodgnggeljgtonaxgqtjvnjjontjxggxduvqdlnlgnnooxaooqooljvgejallgxdljdgtoxtuqaaldjqqnltuanexljauqegogtuqaxdvgqonlugjvljjedtnaaenqexeexquevnxtdqjdnjvvjelugqlnjauqaloeudtdooeoqjoaeuougoulgxdeldxxngaulugjltutevxlejxjaoaaogovqxntotovlndeqxeooxdunvjnuxdtjtqqxnxlgajddenjtqnjouqvonqeddexudveltogdvdtgugqnjgquatnaejvtovtntudgooleuaeatajjunoqxvqdaxjoxleoavganjooeolunxuguooeuxddneeujqxtogdexetdualxnuottvdlngadntxueddlgntujntaxjltnlqevtdeeoqxtlugqdoqatevtnnalqeagxngunuutdgtgnluetoxvuudquvojojexvlgxlalottdjvnagleoxggooglaogtvdgqtnnqglevuddaxdaunltxtvlloetqnnvddldoxqqooglajqnggjdvxvtjxltuonjdjeuvnteuxgjvjdlvuvetqdxlllttdxvxxdoadqndeljgvneojnalvuaajtdxqelqnlnnqlnlxqdotutnuevgttqeuutuxondjdgqavotadnguvnuvqvdvxntdlljugovqxqutqgllvnxnttqndguxtnudnadjuulgjouvujxludooqltdxdexgganxqauqqxtdqaallxxajvonxlx";
        assertEquals("ugotvaeqjnlxd", unique.removeDuplicates(S));
    }

    @Test
    public void case41() {
        String S = "cpjkgalrpdpbwarjtxmkututzirbtuehkklxoqtnxfociroxfwxtqutdqhdymxkbibgjtczcmiopcryavdahsasvsatkzbnnjmekbrqhkvctpdhuevmqkeobjmhjxjimujiwzhqlcjbbnkqwvhqylczndaskzyevgatrmnpllkojthuxeivzeofplamymaievxksbquiwgftnbrxmzcvumjaftbkcovtbhrfinjcwtknkppreqfonqgrjebfifcqijufcdirgnlfcicevrbnndbntsayjcqvjhblqskuvuwhxudjwxgbiqobnnnjcwobladkbouiieffxcmpnxnrximnnmjsdkvncsmfhjyidhlvbaekfmvmksrhpclacojwxohsdsrdjtowcdzjbyjbdnpwikdbgzhxkzaollwwjypopckvkaoxwzohtdugcadurrbtltybgioqhlainqymjtytwnqgndycgfwtvylgesaxebgyfctzzvgdxfvdyrwhdpzyzibzrvvheuhxudzypxrwzqbwmspnbbqwowkbjzajmauewctumaxuqphjbwntmcnqivluaaspqdzruihdgmxyqorizhiqalcnkuumftcfjjymayddjktawtnsntlxahwahwjdcpsdrgulececoofcwnoccsehhnazbtlcyrouvmilmmtnjxnxnmjjhwqpmewsvreqxqzwfdfsriylnhnfgkxxkdjuzhwhbhuuwnizoynviozafkbydshaywaeazdrkjevvhpzedkqsavvfjhlyntdaamqfrhpuhubesjxovblspdylpepelgsxliolrlhserkwipktvxaznhvywuxfmbqawxfibzphkudaarjbvknziuztktiggwyvtxrsbstcwvznkppyclpmemxmxifynjfdlpbxnhdfqrutxxfsgnjhuosxyinflvjslxvhebjfepbbymxpmxylsgyhnndsbtbuontrpaximdc";
        assertEquals("cpjkgalrdbwtxmuziehoqnfyvs", unique.removeDuplicates(S));
    }

    @Test
    public void case42() {
        String S = "qlvequlnvaudqajguvelegxxauvtgonoauujoeuaoqgdoltjgveetluououeqgxguqolnllvvldtatxetnnjgxaodxnxuuvvavjulttejoledlouavljexdlanglxdgavxljgjqlqqluvqolglveoujgaaolvgnqdvoojenqotxlgoveojjlaqxvdajvogexnujuonnngxdxegdtqqtadgtxetgtogloteloeeooudtuxlvevjnqoxoxaevluuluuljaatvevxtovdvtounuvonnoogtvogndavtnlltljgnttlonalevatlgogngtxtdxnvedadlovdllgdngoaugnlavtaqjvdqalexnvnjggjdunqejejqaqaagjtqlaodoateadjugnuauoeuaojvedjgvnjnanagvgqtotanluuoelvaaaxeutlxqgeuuxtexuvgedotejjtjalqgoeauetgjnegljgvqdalnxtvolatdqltdvuqqonaavaldddvgoeaxjjqeeuvudoovdxxqeuxogugeajetonjegevotnldoleldotvnxevuejxoqutundnolxeootntaljvanaqulnoejgjaellgtaxoenootqqqqooxlnvnnguxgxgeuudgtnojxjequjdujjlloogoujtqeveqxjaaqaxeojvtjlxxgjnojdxaotnuljtuqjtleqvandxeoxvejvaeeangonquxuaxnlxndxtnxljjaonxtunqugejaetoengnlgaoxxeelqeljvvgavjnlgetoxvvllxuqjoutngtettajlnqoetdjxgvoqlxjtlauujjqodgdojnaqvvqxxjoqajnvqtxgglajxaotoqjaqxqdqgxvvauvaodjdlqgxxoegttglqgxotjnllqxlxavgvaalnjldelvjoxxoottjltloqgxvuagxvdetqqutoqunadjgtjuvvdnxvqxqqvvqgxqonettooddddnov";
        assertEquals("qlveunadjgxto", unique.removeDuplicates(S));
    }

    @Test
    public void case43() {
        String S = "yzkwtgipiilujdhffukazencosqvjkyfqdeijkxepnvqpsiqjlaamyhgrrvcaiefgtankgnjseyeocjjuhitrhggpmkyfamtfavbznfgmkzofictsmyyeuqalexvxrvwdfndhadviezfrqktjgiukgnhnfftqvygpfttcljrgeireblvxiallvrcfjdnkssobuhzjpqoghtkkxzzzwhjaoffliepezcytozolrzwcristsfasyivhyazggwexerefmnyynlylzyzthplnzmzetcbrfcmdavomffeluntmmmsschhkjrydrojcevcepwvrwtagmhhxppywklhmvkstzdbbdqytzxavelgclrgwlgspqshroadlvtqnijbsczhitkrpwxkufdltnlafebsfholjsxojebgcjdnnjaskwmvzeihwozqnargcwtcpnfuswmzfjyzgkknlhglekdtpcuriwvrdswftjpzysifveiihabbuglkbxtmqcpoixnoeqluynjrwmiezeadygzsilyljvnakpvjglmbmwaciwluxluarfydcnhwkkaugwweejbealnqsmopydguoccahezxfoakitvqlmovdnsnhwahrtduuajsfccxemsmvzylchtvehmfilfrwgrbeqgcxopviskeugurjcgerdtvtrefhmuafekokfcytrqialnejoihdpnpyzovnprjfuwfvvbrwlcuwywfdbiodscwniyvomhthflwneyxpqajqwpuqebbrrncpevyumopeatyhgxxigifqptlmrnedadfwxkhrltpjjhgdecxfjpcurrsmlflyehqxktoidpwohirrxlifnxeuwgqouqrxbtgqholoqyyaqfcduxguiyktskvpklgxxzhgcqovboaubtdpzammxyxsdkrqbfqdxwcbqjtezoheoqkxbbosdrirgpsuecbrznkjlyliklivhwyccukvfhmhipkmxofkmht";
        assertEquals("yzkwtgiplujdhfaencosqvxmrb", unique.removeDuplicates(S));
    }

    @Test
    public void case44() {
        String S = "nxveendovvdglxtulggxtujadtxvovxtevdneauuaaleoejqduljntoldvleettendlxuxxvtovoaeujdedtaxntduootdagtleavdeujxljjjentdguxoqjxuexoxvgxoljuvnelnjjxxgjqxtvxvqdtoaottdxovdaddueeteudduxdlaaellqtgedjjqngoonvxdjvqdjjvgnaulunlejnaajxelunonuxaquaauvlajdjlqoevgleujoteveuqjtejdnnvvutgulaogujjjoexxagnvljxnttqvdvaaogdeugundtltltevgagegotunxgvjevlnojgvugtaejgvloqanjuaxxjanllvgtaxaqadloluqqdojugooaoatvnnqvutddaulgueanxdqoxnaxjxeneeuqadxdootaoxjxnndgvgaalxaqggoelegjgnvduqoaedqeotvujuxvtajluggtoegqgntgqxnogjjeqtdenatdtvouqlvdqvaxautdovxvngjgouvuulqnagqlanavgvugjqodoujnnjelntujgudtxvdljtxdtoaagaldvolxvnegqxnqgqejgnxagovtgoaaugtldutqgqoxnaqxvvnvjaenegoegaatndnuuaggtdajjuevoxalqaouxlqvgoeaeqllgxnaogaeqgqxqvdxlqqlgjdlaeduundngqtxejgtanuanntxtovdjjgnvonunnonjueanduloxlategdntoxqjtujjoltjjujuxaneqqxvjvjujexqgjxeadunujvgovvnntgtvxtggoajvjtlqgnddxdvgnjoenduqluvunqxvoajlqvotvuquljeuoqouxogneludejeqjdxgjjdgeguneodnggxoqtnlenlqdvlvlggndouonvjoqtuuguqtqgtouuntotoejjgojqggttdedxgqangjdqentdlxdeeteqjqjtnndodudojnlqatdqn";
        assertEquals("nxvedogltujaq", unique.removeDuplicates(S));
    }

    @Test
    public void case45() {
        String S = "tnxnldxfrqjbhtdwrkjqtozugxfrpzyezfwyamtacbmqdqswyhoynkemvibnzmooemcuqwlnlehopqxreurbiuustkskemiojfzgsosgnzgfpwzfpmkastjgxxjntgeselfuzdvtdcfxrbexkpfjiocovantnzlmsewcsorlvsrbhklijynqvotlohwytjfahflhbmlhqmyjlgeztdezxhzdksdlddvyblhiokpmnbdgryggmzhtbzhngryhrrlgqzhsyljnvwinexejjdwzeirljoivgnvwlvxzcabzdentqqoxpkexxgkuaggrkegvdrjngbqisunovqyjnstswyecrysaalidyqitdyhdvdtulavsyurcqvnqyrsrtqegwkqetijoafusmwaqrqovrhtdszloynokfogqhfqfbjzmbcphsyvnruhhguuiapvtyivwjmgrxggcahhmkunlhxsisceuezsyekhjaiygtrbnokxeuuduojjsadvejvairarxedtwozjgtsdcgsibasmnlscspiumlqngniktuevokkvcagyacrgvqyakyttgcahhixxluoxuexwpkihrzfjzkgpgnlataazrzfclbcljnesyzgkdqzhhuffwxnxbxgkegkancaezlyivuevkteuhiruapfvofzxobxbefdvohudelsyvtyywmmbhjjkejolyrptweubfpjukefwedujpffvbfcjnrkykhmdtuirhprmylercrxwfasutjxlismqtsvpytzxqiddyhezxunqwoifllpqhxgwbcdjcrjtavnmlcdfgbhpeqpxdsyqssjwbeczzjemdbybupgdusgbyabibiniitawvoohvjwctdcjgvmjlyltvrbgsxquwzehmjsdoimmqladiksnkikqhxrljreohyurldccrreibbqymbnftstbqwkmoskxqhjpdlueusldvrbilfarlcipbbpydtfdgytviaxpc";
        assertEquals("tnxldfrqjbhwkozugpyeamcsvi", unique.removeDuplicates(S));
    }

    @Test
    public void case46() {
        String S = "ldvdnjnttjladgeuogjgnddadxuuxjanlluejaaovaxgevjuugdxejnldajlvqqjlgxqeadxdlqjovnegtnxonulngaxdunjquadadlxnjqtodtodovgaejoqlvjgngaovluqandoovteuxtnqlqevnvxvqjaxogxjxjjnxutujuoouaauvetuoavxqgxatngvajqvxqqtuevnoxttteuovdjdaqjojqjxxvangaedoedajjdelutgaleltjvnxnqogqvdllolaedlnjjullntgnljenlduonvguaxoxodtnvatvqlltlejgonxqdenqqlvveqavnqxdlnvjlvjuojxutajeolvddqtjtjegntoqennjjjtgvlxeenguaxgogelxqaxlvljeaqndgjnqnvnjdoevavljgvenuljxvxotqjtqtjuoloagdudtegloajtvadtvoeoxxtxuexnovdxxnuuuxqtvuqeeeuxulevedvxoadeotgojlulaaeqlonuevgqulvotqouueeqgjaadexqlqengdgaljgeujdugqgleqvjlnqjlnvnuedaqjqjgdjlldlvvqjxoggqxlaqetdjaeaxqlugtotuxjjenaoxgdooqdnjdvvxqeuqveoqnljggxegalaagqxagvneglogoatjjolxxvtvljxavqgqjuognalelnedqagjjgdexnxtxgoevjgvnldqnvdjejoexengjdexglnujaajqaxxgdxgqaqegljtdtxqtqlxdvujoldqgtxtdgueadlvuevegqaooxvjdjgjxaeqoatjquextovjuextdolatgttjlvutddudjuxtdxxaxxxqvutuneojlxojjvxuvoteqnqtuuqdlxanqnuxotontlxoavjjgavtetnxaualevlgtaxdxgolnnxvddulloxauovatgauenqeqnaedqvnvqqqjgeuldqoatojoodtnqtxdvgovudjuetjango";
        assertEquals("ldvnjtageuoxq", unique.removeDuplicates(S));
    }

    @Test
    public void case47() {
        String S = "izotucgdoocaurjbbvajuotpxvpwqndukibziboelwcjhhqmplzytqvxcxzufkowrusltilflinrufrnajatprntgpmyxcfvatktpeobrvdhiwfclgowjjhntdrorrxamowdfqcfrbqilzdxbvzocclozcibtrjznvmudxpdcvpuezktrypkklqrwtmvznkmoctxyftdspaggzmaiiwxuivwuknjhtqozqtnwkhexwvyupmgarvnjirzgxixzcosddchxndvfyhgrnlfwegzlxribfrxgrqseigixxdrerzxmyzhrdsfhqdunirrwljfmhlfltavarvtzcnjgoibtltnpoezutofnshrigyyrhvmfbwodoqrwuoottirhagehimlabnfgyhuzkrhqhuxmfpbdxjsclijxvjcqtbctdylvjjayizkwmvmtlogzvhbxkikkhruoewupcqnmdkvlapzdtxduwwsrwhxxjslinijojewkmrksoispwzjistvilvmpmqqzyyqcmqoilqcxzdyzxxnfoqqcuwscplohzamdmvafdzdbtpxnahthxwaxhsyysmpasiwxlcqrimlombfxuzslmoenwbmjkzwqkoezmafjnkoglswxuhuuuyklhitexmhwmdeykelwkrjvposxjnbokkyafdyzjhgpcnsxrigwghzxhzxfajlaxuuzrwezvnnzidezfocrlagebardxhuxtwhzojbuebitsuyaptbfydnonalklogloifovbsrjmjvlsrtwiyjwfsjgjesqbfzhdhhlcwokcsxahtpdbwaxflsmpgqpcvdhtymijdovnzvzqsqcguimbcunzavpsctutncrknwlzvbgclmpuudffvrcwvxdltceuagxvetmrljrbsnjirxkfqqelykkrmzkbwifkmiyjhyhlcxyrscrijqoexxyeyiuaqqldfqebtaxqgnrwwbocyfxxdzzvvvzsiweegoiyl";
        assertEquals("izotucgdarjbvpxwqnkelhmyfs", unique.removeDuplicates(S));
    }

    @Test
    public void case48() {
        String S = "xgnudgqjeoqvgldqogxntgdxvtltqggavojolqejnjjdddetvejvtdnvjgnolaauttutonxoqjjneglxdugvugnuovnxjgodtqlugngojgaagvoaoqgeennttqqddgualuovjqtdnxouxdxjvxxaogtlgljxvjulaguteaqavllquggltggaqvalloottvaaajnaqejoalxljgttvvxegllnllegtgagexoogtxtequealvejvvatguudonxqxtvdvdtunlxvludeotqaadltvvunuqxtuxevaavgaulaojodqxqdejaeueoeodjadvjjnjeoqulaqxjedtjgtaquuvdjtjuvjxxednxqlldgxqtgnjoegvoljttltuqxgeueeunjuvgqguxujoetdqodjajqjdxxuntdaaaoqoauqdxlnnggxvtdteduuteugvdxxuggltdqdvtdgjdljgddodaltngggnovodtjgtaoulqtunqgtjaqvealtovatxxqanjqgadqxnvqvejalqlnvjeavxuxxxxuelqooeqvqvejeeajjlleettvujdxuvaxgejqtuelooxgavoxgxxqqeuqvjunnaqnoeqlxquutnttnnxxxnuojjuunexdgvjlntdxgvxejodnejdgajoenejtaaqvaatnauvjvaltalxgndqgnnjvdtqgqdtavegggeeleeotaxatogojuouvoxjquleduvgodatdnuajalnvadaqtjggnxljaudjegaxuatadeqluaxujdjjqtgtjdooedqdegdelnqqgedavtxolvugevejeoaelxgdadogexqovaoljnujqjldxtlnnogdeeenxgelvxatlegltonedvaqtaatqonoaajgxqdaqqelvjuoeddudejujtvjuovaexdttaexvndvqelnvgnqvxudauvxjuavdulxdxjlqqajqaaxqgugqglxaxtqeauvongauxvlvaoqdxo";
        assertEquals("xgnudqjeovlta", unique.removeDuplicates(S));
    }

    @Test
    public void case49() {
        String S = "bicyhcpvrsjljmpwvakgkqyksxobplpslxvumfwwyabvxclgrioqzbthpkqvjwbqqwyvlvgykpmsdhiswyqxwjkpfxfolcpvbqutuhigbhkttbpopbytmpmdhjbsodvzhzrqccrlhwvxjymnaxyohtshhlqtlefkfraddifiokxhxjlxoaxwyxpoxzamvbavemhifpbgmgdbbkzkpssshtdmcaeeghxvdugaqpejzszdkhobyszltbxxzwydxfjojfsdrqprjhergqbcqspibbpkmkfopfdozjephljjfnkjlszytipksbgajwxzcxcynqgombjqjjxskdwdwyvbhlvqjpzngahvignitmjvqestruixjmxoanizqpxwbibsgskjbnbzpqzspwhhalhwpwatuyhkbgyceqmenicwsstdcvwwpnjzvsbfcguowdyiwrsusahelsjapfohxomefwcxnicscxbqhfssicojdomnaxmntnihgdwzwbfqtfrbbrhnckrguscetfnsgdltlqzbcokkkziwbmcvfkpbavqzzjhrrmivpxsmjtuokfvrzncfdgpvuvdxxepbesloxbjoizwbsjzzliwvgzwrasqpofpgbdplyegrvsaojjespculmqqznamnjgtirhncmthfxnvwoughbgumtgjzgpshtjvvichmwexafyztiylysdpotkeahrdchpfetlomedhldshqvpuvqiriqcojnpngpckuzbdidbmdhxjknotpudthmqjikfkujdgfhnescxzhqlfgwqzdynecaauejmksjcghukuydwlqemtywhpsqcpktayrcaakpbesajxxrhfggkiaqzfvnacqsjszjeyfelbbsphgotuitpoirxrfqrmvqsgyuthddgwnxopqvzicficowftrszvqwqadponmxaxvbxrhnjphzklkdupffkzpabosxhylwdefpakbxivnclmsjmwjxnvotnqw";
        assertEquals("bicyhpvrsjlmwakgqxoufztdne", unique.removeDuplicates(S));
    }

    @Test
    public void case50() {
        String S = "alelluenxajtjqtouvnjgqudldlaaxnanalaxjxtngxxalajejvxvaonldvaenqlexnnlnqedjlalaldgeooqaqaonequqeegxexuqonoovxtvxgtxdueqtdoognuouxanooxjegnuedlgnualjxnnatodatjglxdujxoqqneejdjeeqoajneqvvnltdedejvexqtlvqlqgxvjqqxeoxntddqvvqvaooaatgouxjnedvdgntjoolqnlujgnuaojluoxqtunnltxnvtqvoxoqqqqjxoadgeavutlgnenduttxlatdvvguxgtnegeedvqlngexojxdoqgaeatuglqtdxuoetaojoqaxtdxeqtanxgdujvjaxjdvodvxxdelojvanveujxnaxxnajdvqaqantoluqvxaejnnoladlvvedajvdlljlvegevgjgovuxtnoggdaqnlettdduqqjnuaaunaoexaavqatqgovqonqtulavuuedaqluovqaqddvataqlxojavaevdquvaxaxlxleqndedevdvqajonodjdxlaxedjnjgavdvaeqddugnogeveqjqxluonovneeegavqeneudaeunnvggugnddlealanuaqagnjjjxtedugjnnnejujlxotaavuglltdlddooodndauvttagoxnoetgjvndgaloouvqdntddaognavlqdnjvuqvxatgojltjxlunxtvtvxongeeaejojvojxldugoodovjovdogolnaeoaovvvqtveteuaatgveeeooqtdqjxluxtloooeanotauqvgxgdqtequduogqtaujjoegnvguvatvjuxaeuevdxqlequteannlnatdtollqeuaetvxuljgxlujlqnoeeetljggjnooetjgvlxtjngdvxdjotatvulgogvuujnonudlluqtvngtqxttdvovdxuodqaujguangavvdltolxguvqqqenuguaoeodouoqlj";
        assertEquals("aleunxjtqovgd", unique.removeDuplicates(S));
    }

    @Test
    public void case51() {
        String S = "forbvemjpirihwfobxijxcdbrbrypvpkhnzoaxjbjiuhqrkjzbtbdzlnmlodzcocgwbevdnpkbxrhzlybejqisqqinrnrsuuiyvrcklqicxpleahqflciodyyviyzydquinzhlyqepxglgealosyadzeaslpkramdkyceausyseperuqzgvaqycurehjtaexngdjrcefrwbpzhpgoqexjcqzypupyeajwubrxxvsolaomuhuxzrqnurucvkiqjdwihfzgzvnbotxdntdwlttboleyqiqawxqoedfoynlmzbaqrqavoswrbpgjujanplhnajuhrnawgcqudsgucbevrpcnlpurhlwqopdmpkqcknkocfrsomoozpchzmhmsxhrndnapoxkuxrebxjeowrcjklpdieqzalrexsmzpkudjichvlbmnahmjawejdcumrrexgpohfmuzeessckxdguzotvwmjamcjrsdcfbzbqamxkwcfzelvmtwtmuvxrbmelhmsdmvrpdgbmgyxtpvyxxdpjlujftmdriwjccnwyicwclrekxtnmnalkrlqvswkgecichfsizrzzashideglwvlyyvetxuczacwqaymfitazfutfjtnxsbcltxlwkjjfgtrdbuzmtnoogzkbdgjdbvrhpgsbgenyoccogvwhhikgmjlrcvidakrfdeqlghxkiduayydqdjahikkpdclriexzymaugfgeukubtrputdtqlwdhzstvdqjkjghdugawzuntorkplfrsmcyhvmoyqofavrwgrltvnejsggucnjxlocgywiqoaoxndglcbdbfxrnavuvwrggjcxrnujhokncodqepmetsqjjoqczajgvnoxgqutmhskrokhcuciitquaitmvjexgvvofnnidugbvuvpbpxpgnddgqkwvrrdgnjibgsfolrxysudoszjnirayebdypfovljciuzfeierrgmoiomnkiuzrvyib";
        assertEquals("forbvemjpihwxcdyknzauqtlgs", unique.removeDuplicates(S));
    }

    @Test
    public void case52() {
        String S = "elllvqtlldxlunojuvxouddavulolutqtaagdvgdttlajlujndjvngueateggeueqqdgeolaelqvaoovldouvjtlxtttatdaojqqloegtogneaxtoxxjdlljgaxgdvxejxevxjdduuqntejatldeouaveevdlxoaggvuagnqjnelvgquaeuvuevlgvudajxtagnoqljevtqtajgxuoneggoeantuxxqqgxantjtaauduavgadvejtanoonvnogtveqduotgluxqdjdoelguaevvujngeuluxxojdgvtxetntouueujjnonljvuadvqddlvelnaovtvqxjdnunldganltoddqtjujuvduaxqduluxxanjujnleeeqvxunelxovaveuuneeaqljjgtjtaqajxvgoedjvqvoqqauxxgtxuqgddxulgduqexgqnagttjojonugxnedunxuqxtoudenenottovonealxxojdxvjxaulnoaovonllollnxanagnddljjvudjxgxxgtvtxuxduxavqvquvddtotqoqnateavtqnqntdnjgejuvgagxjvetgqgxvuattgnjgogludxuvjoaqldodugelatluetdqdanguddjoxjuvqaonavnlqnddoqeaavjeevdlvdaonuxguulegaaxjeoajottduguxdnuateelgllgngvagogglnlxalentjtjdnaujgvunljoajdulugdtejnaguxgaqaolatlvluvaugxegajoxjouelvgddotlggejtoojadagguxjdqtjvutajjqeetaegeqvnxenndtovdoluuonjtjxonlnljqaddnxdnouvnjajqoxqjduvdvxtgdqendoqxvulvudgvxqqxgtvetadujoeqgnajjtuqleltunvtxvjelonnutjnvgoeooonaegevoxavddqxaegxdngxjdjjqvxxougqnduqleogottqgjvjdqoqatqxoaqq";
        assertEquals("elvqtdxunojag", unique.removeDuplicates(S));
    }

    @Test
    public void case53() {
        String S = "bbbcbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
        assertEquals("bc", unique.removeDuplicates(S));
    }

    @Test
    public void case54() {
        String S = "bbbbbbbbbcbbbbbbbbbbdbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbcbbbbbbbbdbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbcbbbcbdbbbbbbbbbbbbbbbbbbbbcbbbbbbccbbcbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbcbbbbbcbbbbcbbbbbbbbbbbbbbbbbbbbcbbbbbbbdbbbbbbbbbbcbbbbcbbbbbcbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbcbbbbbbbbbbbcbbbbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbdbbbbbbbbbbcdbcbbdcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbcbbbbcbbbbbbbbbbbbbcbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbdbbbbbbbcbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbcbbbbbbbbbbbbbbbbbcbbbbbbbbcbbbbcbbbbbbbbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbcbbbbbbbbbbcbbbbbbbbbcbbbbbbbdbbbbbbbbbbbbbbbbddbbbbbbbbbbbbbbb";
        assertEquals("bcd", unique.removeDuplicates(S));
    }

    @Test
    public void case55() {
        String S = "bcbcccbbbcccbcccbcbcbcccbcbccbccbcbbbccccbcccbccbccbcbbcbcbccbcbbcbcccbcbbbcbbccbbbbcccccccbcccbcbcbcbcbbcbccbbccccccccbccbccbcccbbbbcccbcbbccbcbbbccccccbcccbbcbcccbccccbbbbbbcccbbbcbbcbbcbbbbccbbcbbcbbcccbcbcbbccccccbbcbcbbcbbcbbbbbcccbbbcccbbcccbcbcbbccbbcbbccbcbcccccbbccbbccbbcbcbbcbcbbbcbcbbbbcccbbccbbcccbbbcbbcccbbcccbcccccbcbccbbbcbcbbbbccbbcbcccbccbcbccbcbbccbbbccccbccccbbcccbcbbbbcbcbcbbbccccbcbbcbcbbbbbcbccbcbbccbbbbbbbbbcbcbcbccbbccbcbbbcbbcccbccbbbbbccbccccccccccbbccccbbbcbcccbcbcbcbccccbccccccbcbbbcbbcccccbccccbcbccccbbcbbcbbcbcbccbcccbcbcbbbbbbbbbbbbbbbcbbbbccbbbcbcbcbbbbcbbcccccbccccbbcbbcbccbccccbcbbccbcccbccbbccbbcbbbbccbbbbbbcbbbbcccccbcccccbbbcbcbccccccbccbbbcccbcbbbbccbbcbbccccccbbbbbcccbcbbbbbcbbcbbccbccbbbcbbbbcbcbbbbbcccbcbccccbccbbcbccbcccccbcbbccbbccccbcbccbbcbcbccccbbbcbbbcbccbbccbbcbbbbccbbbcbbbbcbbcbbbbcbccccbbcbbcccbbcccbbcbcccbcbbbccbbbcbcbccbccccccbbbccbccccbbbcbcbcbbccccccbcccbccbbbcbbbccbcccbcbcbccbcccbbccbbbbcccbbccbbcccbbbbcccbbbcccbcccbccbbbcbcbcbcecb";
        assertEquals("bce", unique.removeDuplicates(S));
    }

    @Test
    public void case56() {
        String S = "abababababababa";
        assertEquals("ab", unique.removeDuplicates(S));
    }

    @Test
    public void case57() {
        String S = "ababab";
        assertEquals("ab", unique.removeDuplicates(S));
    }

    @Test
    public void case58() {
        String S = "abbb";
        assertEquals("ab", unique.removeDuplicates(S));
    }

    @Test
    public void case59() {
        String S = "abacaddddd";
        assertEquals("abcd", unique.removeDuplicates(S));
    }

    @Test
    public void case60() {
        String S = "bacbac";
        assertEquals("bac", unique.removeDuplicates(S));
    }

    @Test
    public void case61() {
        String S = "aaabb";
        assertEquals("ab", unique.removeDuplicates(S));
    }

    @Test
    public void case62() {
        String S = "aaaaaaaaaaaaaaaaaaaaa";
        assertEquals("a", unique.removeDuplicates(S));
    }

    @Test
    public void case63() {
        String S = "asdasdasdfdasfdsadasdasdasafdsadasxzcbxzbnc";
        assertEquals("asdfxzcbn", unique.removeDuplicates(S));
    }

    @Test
    public void case64() {
        String S = "abcdefabcxyz";
        assertEquals("abcdefxyz", unique.removeDuplicates(S));
    }

}
