package topc.test.dynamic;

import junit.framework.*;
import org.junit.Test;
import static org.junit.Assert.*;
import topc.dynamic.*;

public class AlphabetCountTest {
  AlphabetCount alphabetcount = new AlphabetCount();

  @Test
  public void case1() {
    String[] grid = { 
        "ABC", 
        "CBZ", 
        "CZC", 
        "BZZ", 
        "ZAA" };
    int length = 3;
    assertEquals(7, alphabetcount.count(grid, length));
  }

  @Test
  public void case2() {
    String[] grid = { "AAAA", "AAAA", "AAAA" };
    int length = 1;
    assertEquals(12, alphabetcount.count(grid, length));
  }

  @Test
  public void case3() {
    String[] grid = { "ABAB", "BABA", "ABAB", "BABA" };
    int length = 2;
    assertEquals(24, alphabetcount.count(grid, length));
  }

  @Test
  public void case4() {
    String[] grid = { "HIJKLMNOPQZZZONMLKHIDZYQR", "GYXWVUTSRASTZZPSTUJGECPXS", "FZABCDEFARQPUQRAAAVWFBOWT", "EONMJIHGAJMNOVAAAAAYXANUV", "DCBLKDEFIEKLEDWAAAZFGHMLK", "UVAZYBCGHFDFCAYXNPQZEDIJA", "TSWXAKLZGCZBGZIJOMZRUTCBZ", "RQPONMJIHBAZZHZZKLZZSVWXY" };
    int length = 26;
    assertEquals(7, alphabetcount.count(grid, length));
  }

  @Test
  public void case5() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXY", "ZZZZZZZZZZZZAAAAAAAAAAAAZ", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ZZZZZZZZZZZZAAAAAAAAAAAAA", "ABCDEFGHIJKLMNOPQRSTUVWXY" };
    int length = 26;
    assertEquals(2, alphabetcount.count(grid, length));
  }

  @Test
  public void case6() {
    String[] grid = { "CZC", "ZBZ", "AZA" };
    int length = 3;
    assertEquals(4, alphabetcount.count(grid, length));
  }

  @Test
  public void case7() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ" };
    int length = 26;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case8() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVW", "ABZZZZZZZZZZZZZZZZZZZZZ", "AZZZZZZZZZZZZZZZZZZZZZZ" };
    int length = 23;
    assertEquals(977462654, alphabetcount.count(grid, length));
  }

  @Test
  public void case9() {
    String[] grid = { "BDBCBACABDDCCADCBDDCBDDDBCCCCABACADDDCCCBADDDBADCA", "DCBBBACBDBACCADABCCAABACDBADBCBBABACBCADADCBDABBBD" };
    int length = 4;
    assertEquals(20, alphabetcount.count(grid, length));
  }

  @Test
  public void case10() {
    String[] grid = { "EEA", "EAC", "CCE", "BEA", "CBE", "AAD", "DDD", "AAD", "DBA", "BAD", "EEE", "ECD", "DDE", "CBC", "CBE", "ACE", "ACB", "BAD", "DDB", "DAE", "DEB", "AAA", "CDD", "CBD", "DAD", "AEE", "DEB", "ECA", "BAD", "EDD", "BBC", "AEC", "AEA", "ABA", "BCC", "ADC", "BBB", "DCA", "BAD", "BEA", "ECA", "ADD", "CEB", "EAC", "EDC", "CBA", "AEC", "ACB", "CDB", "BED" };
    int length = 5;
    assertEquals(31, alphabetcount.count(grid, length));
  }

  @Test
  public void case11() {
    String[] grid = { "CBABCBCCBCAAAAACAABAABCAACCBBBBBAAAABACCACCBCACCCB", "CABBBBBABAAABCBBBAAAABBAACCBCCBACBCBCABABACABBBCAC", "BBAAACABBAABCCACCBCCCACCACCACABCBAACAAACBBABACBACB", "BBCABCCACBBBCCBCACBACBAAAACCACBBAAACACCBCCBABABBAB", "ABCBCBABCBAAABACBACAABAACABBCACAABACBABAABCBBABBCC", "BBBAAAABBCBABACABBABBABCAABCCABACBCAACACBCBBCABCAC", "CACBABACABBCBCACABCAAAABCBAAABBBCCBCBABBACBBAABAAB", "BBBABBCCCACABABCCABCAACCACBBCABAACCACABBCBCCAABCCB", "CBBCABABBAABACCCCCBBBBABCACBAAAACBBCABBAACACCCCCBB", "BACCCCCCCABCCACBCAACCBBACCCBACBBCACCABBAABCBCCAAAC", "ABAACBBCABACCABBBACBABCACCACAACBCCCABACBACCCAACBAA", "ABBBCAABBCBBBCCACBABCACCBCCABAACBBAAABCACBBBBBBAAB", "ACBCBCBBABAABAACCCCBCCCBAAACBBBABCABBBCBAAACCACBCA", "BCBBAAACAABCCCABCCABAABACACCABCAAABCCBCABAAACCBAAC", "CBACCCBCCBBBCAABBABBCAAACBABBCBABAABCCAAABBCBBBBAC", "CBCBBACBCBBBBCBCBBBCCBCBCACCCAAACBBAACBCABCBABAABA", "ABCCBABCABCCACBABCCBBCCCCCBCBBACCBBBBCCCCABCBBBCBB", "BBACACBACAACAACBABBACBAAACBABCACCCBBCACCCAABABACAA", "BBCBBCCCABABCAAAABCAAACABABAACBCCAAAACBCCABBACAAAB", "ACBACBBBCBCABCCAAABCABABBAACCAACAABCCCCABBCACBAACC", "ABABBCCAACBBCCCACCCCACACBAACCCAACAABABCBCCAABBAABA", "ACCAAAACBBBCBABAABBAAABCCBBAAACBCAACBBAABBCCCAABAC", "ACAAABCAABCCBACABABACBCBBCAABABBAABAABABCBCABCBBAA", "BCACACCACBABBBAABAABAABCBBAAABAABBCACCCCCBBCBBCABC", "BBBABACCBBBBABACBCABACABAACACBCACACAACACAACCBBBAAA", "BAAACBBBAABAAACCCACAAACCCACACBBABBCAAABBCBBBCBBBAA", "ABCABCAACAACACBAAACCCCABCBAAABCCCBBBACCABACCBBCACB", "BCBCBBABAAAACBCCBCACCBACCAAABACCAABBBCBBBBCAABABAB", "BCCBABCBBAABABCCBCBCBBACAAABBCAABAACBAABCBCABACBBC", "ABCBBABABAABBBCCBCCABCCBBABCBACACBCACBCACBCCCCCCAC", "CCBBBABCABBCAACCBAAAACACCBACCAACBAAABCBABCCAACBCCB", "ACCBBCAACBCCBBABCACACCCCAABBABCBABBACCCCCBABBBBBBC", "CAAABCACCCCCBACCACABACABCBABACCCBACACCBABCCACCBABB", "CABBBAAABCACBCCCBCABACBABCAACBAAABAACCBCBCBBCBBBBA", "CCBAAACCACACBACBCCAACACCCABCAABCCCABABACBABCBBBCCC", "ACBCAAACCCCBCCCBCBBCBCCACCBCAAABACBACBCACCCACCAABA", "ACCABACBBAABBBBBBBBCACBCCAACBABCBAABAAAAAABCCBBCBB", "BABABBABCCBBCABCBCCBACACCACBCBABBAACBCABACAABCACAC", "CCABBBAAAACBBCCBBACCBACBAAACBCCAACCCBACCABBCBBBBAA", "BABBACBCACCCBABACBBAAACAAABACCBCBCACABCBABBACCABCC", "BBACBACAABBBBBBBCCABBCBCCCBCCBBBCABACCCCCAABCBCCBB", "CAAACABCBCCABACABBBACCAACACAABACBBBCCCBACCCABCBACB", "AABBCBCBCACCCCBCABACCBBAAAAAACCBCBBBAABBBBBACABBAB", "CCABABCCACCBBACBBCCAABCABAAACCABBABABBAACAACBBCACC", "ABACBACBAABACCBABCACCACACABBBCBCACAAAACCBCCCBCCAAC", "AABBCCAACBCBBCABBAAABCAACCAAAACCCBBACCAABAABBCBACB", "BBAABBAACBCCACCBCCBBBABAAACBAACACACCBABBAABACAAABA", "AACACBBBBACBBABACAABBAAABCBCCBCCBACBBABABBABBCACAC", "CAAACCBACACCCCBAAACCCABCABACBACCCAAAACBCABABBCBCAB", "BBCCCCBCCAACBACBCCAACBABAABCCCCBCBABBCBABBBBAACCAC" };
    int length = 3;
    assertEquals(4882, alphabetcount.count(grid, length));
  }

  @Test
  public void case12() {
    String[] grid = { "HAGBBEGDDJEGJHAGCGEBFAGEIHAHAJCGGFGFFIFAFEBJECIIII", "CCIDFEJFGIEEAICEJBIFIIEJDIHBCIGBCCJCEJFCCDHGIEJDII", "ADFJCEGICGJIGCEGCDJJFBGJBJEDHBCCJJCJBCEAHGGEFICGDC", "BEJGJEBBEGDIBCGEDIDDHDHJBBEBJADEFJGIIHGFAAHCBFEDEB", "DEBCGEGIIHGIGECCDFGEGHDBDAIBCGECEGCGCIDHDCFGFFJBFA", "IJDADIEHEJCCFJDECAEJJJCGAFIHCJGFEJEDBDCIHDICBAIFAB", "JADBDDIHGDAFBEDFAICGBGDIIFEJDEJFAIIGDDGEFCJGDFCCFH", "GEBIHIEGFJHHEGEGJDCIJIIIHECCCDDDHEJHCEIDIBFDDIIJAC", "CGAFGBEDCCDCHHDFBCFIFHHAIDHBHICAFBHBIDHCJDJBBIDJHH", "EEFIFGFCEGGFFJJEAFCACHBJCGGJFIIJGHFGGJIAHBAFIDAEII", "BHDBFGDIIAJAIHHHHJCGCEDHHGIJFCHGFFCGCHCEJIAHCDACEB", "DIBGAADFHCJFGGEAGIFFAEGECBBEDAIBDBACFBDJGACDDJFIHC", "JJGFHCGCFEAJCIEGGABCBCBICCJHJGHEHIGEGGICHBFIBDAIIH", "BBCGBDJCJCEGHBBADJBEIBHCEJHDBCAFDDHGEFCBJBAACHDFEA", "DEADAIJDCEBCHJCAFJEGHDBAHJCCEACDAGABEGJICIJHJGDEEG", "CEDGGDHFEHDDGEAIAEEGHEDBIIHHHFFBFBBHJEBAEHHJIDHCAI", "DCDIFDCJEDBIBJCFJFGIDEABEIIGADDEDHBGHDHAGCCHIFHGHD", "AGBCHAAAJGDHCHJECHAJCJJFFCGFACCCFEHGDEFGCGGCJIABDH", "FGHGGICIAEEADAGFFDEEGIJIEHBBFJCIBDHCDGGDGADICIEBBA", "GEHDGCGDGGBIFGAGHFHHIEEDCEAIABDFAIDGFDDEJHAFHFBGJA", "CBBGFBDAHDCCBDBBJGIJAJJCDGDEIDCDDDJJIGACEAAHAJHDCG", "BJDHBFIIGCJFAEGDADJIEIGDIGBHEGEJDFGIIIAGJIFBHEEDAA", "AHCCJBDCHEBGDCGACGAFCFACEECGFCFHAFCAJEDAFCJGJADJII", "DDAJGIBAHIIDFEAICHIEHDAHBEIIEEBGGBEJBHJDAFBAECEBGE", "DEECHGCHGFGDEEJDIFBAAJDCHAIEBFDBCCHHIDBCCAIECFJCDG", "BDGEBACICAJFBDDGFIJCCGBEEEHHAEGBEHBAFBGCAIEGICBDJH", "DGHJCGCGHFHEGBFDBCCFHJJBEHAJJDJFAGHHDDFAAFBDJBCAHD", "DJIDFJFGBDBCIEHJACDAGAGGBHAFFGJHCABCECFDFDACFFAJCG", "GIHICIBBFJFGJHADFIEBFJEEEHEGFAIBBCHDBIGFADCCCDHEFH", "EJCBFDCJEAJDFGFEGEAEIAEEJHBDBHGHDDDJGCADBDFBIDBJAD", "DCEEGIJDHCHCIDFHEHJEBGIBHBJHHEAJEIEFFJJGCFGDIHEICF", "BEAAEFCHBEDIJJGBBJBFBEFBEJHDIGBADFAEEAHGCEFFJACFHA", "HDEBACECGJBHBJDJFGJHHIIIIGFJDIIJBEIBJGFJBFJIBCFHII", "ABAICJAFCCFDEHIJGHBDFGGFHIBFJGCBGFHFJEBEICEHGFFFIA", "GHHACGGJBFFFFCBBBHJBHHGHEIDAJFIHCCIEJIDGEAEBBJJIFH", "IAFDAGDJICEGFAHICBCIIICDAIEIJEDFIAJEGHHIEICACEBIAD", "CBBBACJAFDFFFCEHDGHGHAECGIJJJIGGGCEGBGJDIJGDEGHIGE", "FJJAGHFEBAFAFHDEAJJFIDGCBEDAAECCDJGIHDGEFGABIIGDEJ", "EAFEDCJHIHBFAJAIBGBJHBHJHHEBJAAGAIBIAFICBDDGHBCCEF", "IBHEBBIEAEEDIEFBFIHFIEICIJDCIJIJHFAFEJIIBIJCEDEAFF", "EIADDCFDDAAIJGDCABBACHJEJJAEJBGJFHFHJBGAHCBIAEAAGA", "AFIAHGJHJFFCAJAEHABIJDCJCGECBCGDBGBJJGGDHABCGEBHIE", "JJFHEBHDIGGFEHBEGAAAAEEGDIFEHCHHFJCJAAIAGGHGAACADF", "BGHEDEBACEABEEGGEABHDFBACDDJEACCJIBHBHJJEDEJCBCGBD", "JJFBJIAAJFCFFABDGAEDGIHAEHICCFHJDABGCJFHFGABDIDBDE", "DFBCDHFCBDDIBJIIIBBFIDDDAIEBAGGJFFFGCCCFGFJJCIDJAE", "CDCJBEGBGHDJBCIDGIIIGCDHHCIFFGHHJFGJHICACIDHEHABFF", "HDIEIAEGGBBBEJEDAJCGDHJGDFGIIAIEEGEGBJBICGGACCDHJB", "DICDCBCJAAGIHCBCEJGBCHJIGIJJCAFDFBBGGCDEAHIEJEGHHC", "JHADAEIABDHDFIDFFEJDDDCIHDAJHFJJAIHABFFHHCEHCHDFCF" };
    int length = 10;
    assertEquals(1, alphabetcount.count(grid, length));
  }

  @Test
  public void case13() {
    String[] grid = { "CDFAHEABAFFGEAEGCGBCFHDGGHDHCAHFHDBDCBHDECHBAAEEEC", "FCAHBBFBEFHFBCDFADDGDGDDDGBAFECDCEAADHEFCADFDBDCEE", "DDAGHADBEAEHABCEGCAABAGFCFDBCCCCBAEEGACDHBDGAADCDB", "EDGDEEBGGEGEHFFDHDCDDBFBFCCCAHCGEGAFCDBAGGAAGGCFEF", "BGDBEFGBBBEGAHDEEECDAEDDCGHHFHGFGABEGFEEAHHAGAAEGD", "DGCGEFHCCGBAFDAFEDEHFGFGGFGGHCAADCCEGDBCHGDDHAFDHF", "CEFHGGFGFHHCBBACHEFGHDHCDCEDACGEEEFGDFCECCFEEDBGDD", "GFBCCAECDEGEBEBEGBBHFFGBGCDADFBBAACGCEAEHDDGACFEGH", "DBBCGGBFHAEBFEGCEHHDEEBFFHEBBCDFADAFAHBCABFDBAFCDD", "DBFECDBHHFDABBHAAFAEACHGEDAEDCECCADGACFFDACCDCAHEC", "GHGBFEADGBGAHHBCDEEECGEEDBGDAAGEFCCFGBCGFECACEDCBE", "AAHGDEHHAGGCHEBBECFEACGCFBADFAHAEEEEDHBFDCBHBBEFBD", "HBDFCBDHFECCCFFBBEFBFGFHBAABAHHDAADDGDGCCHCGHDBABB", "BAFFGDDBBBHHCACGEHADACDEBAFHAHGEEEBGDGHBDFBFFFFBFF", "ECDFDDEABCBCBBHFADHGGDHADCCHCGAHGCGADBAEDFDGBECHFA", "DCHHAHDCCAHEHBGEGHDGDHCGDFAGDGGBDGAHCEFEAFAFBDEHCF", "HACHBBBGAACEFHECEHAFDCBEHAAFCEECFEDAGFFEHEABGBGCHH", "FADCEFCACDFECFCEAEGCFEGBDBDGGFDAAAFCFEDCBHGCDHACDC", "BAFFBHAFHHEGBCGDDGFFECCHDEBBGBDCHCBGHECEEAHEACEHHB", "CAEHBEEEFBEBFHACDDGGEDDHFBCDHDGDHAECEDBHABCGHCDAAB", "FAABAEFDBCDFCEHBBFBHGACABGGHBHGEFDBCCDDDGHEBHAFECE", "ABBCEDHHCGAECBHDFDCADHHCHFHBBAEAEDBFABHDHDFHGBADCE", "GADDBBGGBFFFHDBGBDAAHCAEEDBBCHBDACCFCDCAEDGECAEHBF", "BGEGCDFACCAHBCHGBFAHEGADAEEEADAFECBAFDAGAEHADGFHCB", "DFEBBGBDABCDCEGCBCEHAGGCHFAFADEHEDGFFCBCGBDEADHBGG", "AGEGCECCBGFAEDDFBGGCFDGEGCHAHDDAGHHAFFDDGGFEHBFHHF", "BHHDBGDBCGBBAHGDCCFHHAACEEBDGDGBFEHHAHBCAGDDAHEBGC", "DECBFFDHAGCABGHADCCCEEFDDBFDHCFCAACHHBGBHHDDEACEAH", "EGCGHDHBCFFDBBEEGCFAFGDBGGCHCHHEECAFDBAGAAHEHCGAAH", "BBFDGDAHFFCEDEDHFCFFEACHAGHDCABFBDEFBBAFBHCBHCGHCF", "EGDDHFEECHAHGCEEACCCCHEHCCBBGEDDHFAHFBHBABGHCGCGCE", "HGDBBDDEHHFGHFCEBEEAFAGEFFBHEEFDGAAABCADEADFDAFGAB", "EGCBEHCBAFCECDEBBBGCHEHCFGGHABDCCHGEECBFFFBDHBHEEF", "EFCEAGHHGADDCABEBEGADHAABBFGHDBGEGEEDAHHDCDCADBCBC", "AADCDFDFCFDAFGCAAGDCEFCGGCEEGGHHCECHHDAGGDFCCGEGDH", "FFGEGBBCHEHHGGAFEHBEFCCEGCCCACBHGEFDDABDBABGGDDDBE", "DFGHHACFAFBACGHFGFGCFGEACAAFCGGHBDAEEDFDBBHBAEEBAA", "HECGDFDAGHAFFCEFBEBAEGACACGEEECHFEHCDCEEGBBCADEDHA", "CCCGGAAGFAHHDGABGHCAHCBEHAEDEEAHFDFFFHFCHHDEAFCACH", "FBAEDCEGEBAGFDEDHGCAEFGGBHCHHFDBAGAEECCACHAEFFFBDD", "GDDBDBGADBGCDFABGDGCHEGEDHAAFCADABADEEHCDEHBHFEHDD", "CBGBFGEADHGCDAHCHBDHBGGCEEEDCHEFHGBDAGHABBFAECHGBB", "CHAGFHFCEHCADFCGBEGBGFADCAFAHCGGADEEDDGEDEAGGDDHFB", "DGEDEHBCEBAAACDEEGAHAHGFCGCHAFACAGCAGHCHHHFGGEHHEH", "GAADCDBDAAEDBEDHCCCAFBBHDFEGEGHBFEDBCEHHEGFHDDDDCC", "EGHBGHBDDCDAHBGFBAGFEFCFDGABGDCFBDGAEBCDBFEGEGAHGE", "FHCCFBGBBAFADCBGGCEFEEFEBEEFAAAAHHGHGGEGDDCFAEHBHE", "BHHGDAFCFFAFEGFHFCAHFADGFHCDEBGGFCAACGCACCDBACBHCE", "EBECBCGDBHEBFAHAHGEHHCHCHACEAABHABHEHBFDBAHECBAFDH", "DGBDCABHFFBCGDHBDEGBHBCGAAGAFFHDFDDCACGHEDAHGEACHE" };
    int length = 7;
    assertEquals(158, alphabetcount.count(grid, length));
  }

  @Test
  public void case14() {
    String[] grid = { "B" };
    int length = 1;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case15() {
    String[] grid = { "BC", "DA" };
    int length = 4;
    assertEquals(1, alphabetcount.count(grid, length));
  }

  @Test
  public void case16() {
    String[] grid = { "A" };
    int length = 1;
    assertEquals(1, alphabetcount.count(grid, length));
  }

  @Test
  public void case17() {
    String[] grid = { "A" };
    int length = 2;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case18() {
    String[] grid = { "A", "A" };
    int length = 2;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case19() {
    String[] grid = { "C", "A" };
    int length = 2;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case20() {
    String[] grid = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ", "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK", "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL", "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO", "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP", "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ", "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU", "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ", "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK", "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL", "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO", "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP", "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ", "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU", "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV", "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" };
    int length = 24;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case21() {
    String[] grid = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" };
    int length = 4;
    assertEquals(15720, alphabetcount.count(grid, length));
  }

  @Test
  public void case22() {
    String[] grid = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ" };
    int length = 10;
    assertEquals(4621330, alphabetcount.count(grid, length));
  }

  @Test
  public void case23() {
    String[] grid = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ", "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK", "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL", "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO", "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP", "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ", "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ", "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK", "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL", "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO", "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP", "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ", "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ" };
    int length = 15;
    assertEquals(440196976, alphabetcount.count(grid, length));
  }

  @Test
  public void case24() {
    String[] grid = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ", "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK", "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL", "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO", "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP", "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ", "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ", "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK", "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL", "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO", "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP", "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ", "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS", "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ" };
    int length = 16;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case25() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX", "BCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXY", "CDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ", "DEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZA", "EFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZAB", "FGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABC", "GHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCD", "HIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDE", "IJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEF", "JKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFG", "KLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGH", "LMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHI", "MNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJ", "NOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJK", "OPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKL", "PQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLM", "QRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMN", "RSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNO", "STUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOP", "TUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQ", "UVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQR", "VWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRS", "WXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRST", "XYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTU", "YZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUV", "ZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX", "BCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXY", "CDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ", "DEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZA", "EFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZAB", "FGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABC", "GHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCD", "HIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDE", "IJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEF", "JKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFG", "KLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGH", "LMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHI", "MNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJ", "NOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJK", "OPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKL", "PQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLM", "QRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMN", "RSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNO", "STUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOP", "TUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQ", "UVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQR", "VWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRS", "WXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRST", "XYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTU" };
    int length = 26;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case26() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "BCDEFGHIJKLMNOPQRSTUVWXYZA", "CDEFGHIJKLMNOPQRSTUVWXYZAB", "DEFGHIJKLMNOPQRSTUVWXYZABC", "EFGHIJKLMNOPQRSTUVWXYZABCD", "FGHIJKLMNOPQRSTUVWXYZABCDE", "GHIJKLMNOPQRSTUVWXYZABCDEF", "HIJKLMNOPQRSTUVWXYZABCDEFG", "IJKLMNOPQRSTUVWXYZABCDEFGH", "JKLMNOPQRSTUVWXYZABCDEFGHI", "KLMNOPQRSTUVWXYZABCDEFGHIJ", "LMNOPQRSTUVWXYZABCDEFGHIJK", "MNOPQRSTUVWXYZABCDEFGHIJKL", "NOPQRSTUVWXYZABCDEFGHIJKLM", "OPQRSTUVWXYZABCDEFGHIJKLMN", "PQRSTUVWXYZABCDEFGHIJKLMNO", "QRSTUVWXYZABCDEFGHIJKLMNOP", "RSTUVWXYZABCDEFGHIJKLMNOPQ", "STUVWXYZABCDEFGHIJKLMNOPQR", "TUVWXYZABCDEFGHIJKLMNOPQRS", "UVWXYZABCDEFGHIJKLMNOPQRST", "VWXYZABCDEFGHIJKLMNOPQRSTU", "WXYZABCDEFGHIJKLMNOPQRSTUV", "XYZABCDEFGHIJKLMNOPQRSTUVW", "YZABCDEFGHIJKLMNOPQRSTUVWX", "ZABCDEFGHIJKLMNOPQRSTUVWXY" };
    int length = 26;
    assertEquals(33554432, alphabetcount.count(grid, length));
  }

  @Test
  public void case27() {
    String[] grid = { "AABBCCDD", "AABBCCDD" };
    int length = 3;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case28() {
    String[] grid = { "NZHGPYZWNHNJKNGTFGLMNOSTQWXUYIZDCTGAGPOKCAACBDHPSQ", "EYRQFYXVGOIPOMWSETPIPOQXUPYRGJYXUSGHDIQTTGYHINOTUR", "VWXKXZSKFSCQAMZDXYBMQXSYYXLLMNTUVQRDAMSUWZLNLYCZWX", "MTIWVZFGBVYIDEYFWFJLVRZXPZRNYEBVWIQONKVWVMWVXMRDYA", "JPEFJKREUZWXFZXAGHKPCZNXWVMQFWWJZNPHRJZUZHSTZNHWDU", "YRQMVLXZXLUZKOWDAADOQOYWUNRPZXNOIHXIUSTYNOPRQYXFVT", "SQLRBMYUQNMEQPMKMCBMPZITTSOIYGLMGWUVVRPOJGSQWSPRGI", "NKLOSVSTOZPFSRLNBRQDAVIFUGWCAKKMBFTTWCDDFQTWTSOKJD", "JHPKBPQSWNOVRIGOKPSRBCYNDFCBABNZYTZXBAUYXYUXYULMJY", "ITGBAATYZPONZHFHZMGTDONCDUXABEVXXYSWYZTZRGPUWZTOZV", "SFURXDCZURSYXOQGWYUEXGKCEFBEFBTVWBUVSNRSQQOMLMSDPQ", "RPVYAZEXZTWHGEPHOXDIFJLOBZNGLCRUUTPFTSKCRPNLKQJIHW", "QRWAYWFHWRKVGFDEBCJKGHPCBYOYTIRQTSMZXLVISOEMDJNGUX", "STOXBENPQSIRFDCADAMFRQPRCVRZXSPPRQXPYWBTDYAHIEGEZY", "MJNCZITOLKTPONBABVZGWVOBIJSPLWDYZYBOVTCCZTXBYFPXEL", "LKIGYKRSIJUOMPMSCYYXUTDWWZZTTKXWNMOGBASUVWUCQSVZNM", "DCFHXZLAHVCNFLYUXTFPMVFZYTYRSUVVJLHCSRQMTOHYVUFSLO", "JBQUWBCBEWMDMBWSRGJJSXWLWSRXQZOKJKFGKOJMLKZEBURGPM", "APFQTGKJETXNZAPZVKPNQWZXXVUTWPPYXTEQLKLYPHJCVXCQLN", "ACGVTZLISUJYLOYJWLQSZUXZTWBBAOGSOAQVPNXZWIGWGUYDFO", "DEWUYZYXWVZZOXNFDBBZYUBQHECGMNHRDPOOOWSRVFZXQLKSGP", "BCDXRNPNVYTPQUOGHACWXSXYPFCDJLREQMNEZZVAPQKPBEATUQ", "OYKMQQYNVGSRQYJKLDZVTYREOGABXSNKLKLYHRYHSRHQODJZVX", "MZXJPORZDMFUSRXNPSVUXVZQKEHBRTDHIJYYTDXTIYIMOLRYXY", "OQWMUZZUEEAYOQFROMTWNPPUJLIIOVUUIAFEXNWPJKLPONQNOB", "PKMVLKJVDCZACDEGINLMDAZOIYMYJWEBARBDYOVCEAOWQSUXCZ", "UVUIXGIESQBWJWPVUCFKLBNAXZXKQSDKCHCEUVFDDHJMLVWTRQ", "ATVGHPXYLPAXVHGTBEJIPMDWPULYRTOLDEMJYWABWYIKQXJZUP", "VBCFYVGIFBYZQONSUQWHKODFTQGMUXMMKGFKXZQVXEZHMYZVZV", "KWDEWUHDANCSREMUUYYXBCDMLINPMYWJIYXNLHTUDUHGQTUXWF", "ZYYZASKEBQCIDONYXTZKTCXKJOSRNZVUKWMGDEZYXGIIRSTYZG", "XZNONLVWRCPAKCMZWZQMOBGFRQPVUZYTNLHJFTXBIDFQDLMKOA", "HIJOTUXLDSYXWLHHKRXRPDCGZNMROXZMWIZUKWCRPJPNQCZLJA", "FGDSRZYJEWTVKJIGDUTPLKJFTOQMSWYTUIMNVEDNQKOXWRYMIB", "QUACKHDCDFUTKCFEDGVMQVKIXUYLKTIOPSTGOUTAFOWVYXQNCA", "VIBJPQBJCLGLDEDDBANLZSBLWVZIJRJNMRLHJSZCVNOXUTPNMD", "HGZYNOKHFHPMFACACRMQQYOXCZQFQPKLOQJIIKRIQSZQZSCWVC", "FWXZGTRLGUWRVZBBUWXVZXWVYPOGNJNOPKGFYGLPOTRYEFZABD", "EROSTLUMQXVWXYCHVTDYDVUTYKGZUXNYLLJIBXMOUWWXYYYUPK", "ODCJRVWANRWTXDADEMJECATZGIJVYWVVRMKCEAUXYZVNKIZXWC", "KNUTAXEBOUSMZYZRGFNPFIPSCDFRHZFURVICEZYJXZSOGSHJGH", "UWVQOZYCAIEUYSZHIZOGKMVUXBAGJEPITQPJLDEWVULRNQRMXA", "YZKDDDBCBCJKXURTJYRJHLTVZWEPQOWJVUQPJCXCXRPPQMPZLK", "UZEIYMETRVGNWVTQPGQQIRIGPQLDACVKWTRIBPYYKQCEFNZKYZ", "TYJHLRNSUWKIQBLOOYTMSKQFCRMKVUUXHSOCAZVZXCPGLVYIEW", "XGXKSWMYIXYDCNKNXUVUYTLPUGEHJTYDVZDYZRJNHWOKJXWAFG", "APFUVLFWVZIZGHJRVTKZXVZOZHFRYRKNIEYEPOGFBNLUZLECDH", "AESIMLGOVTUXMZIDUNOLVEWYNWUTSZLJHGMORMABCFMTKYMXYI", "DBBZUMUVWSSVWYFDCVMCFGFYXYVNGPONVSPNENILDEUSOPMWUZ", "CDXYTQNRTRQPQGZCBTSAZRSWZPKMINAOUFKFDCJKSOAVRQPVKT" };
    int length = 15;
    assertEquals(24, alphabetcount.count(grid, length));
  }

  @Test
  public void case29() {
    String[] grid = { "AGQUVVPQXWVMLUTVWAGNMKCFDENOYWVDLKGNAJIJIJZIHGAUCA", "FEHKLNOYRUSTWVTUXFBOLJEECLMZXXYNORJZBZIDFHKYPQRVAB", "DMAIFMZCSTUZZFZAOYFCFLHFKWSQYRWQSQYIHHWPGMNOSMESWC", "FLNPQYFEHVYQURPNRZJDRMKPQRVSEZYVUTLSYZVNMMMFEVTGXD", "IDSMWKIWIIJYXVWMLKGHUTJWMNTFGMOPGOTXFTUJOLKHSEHUYI", "JHLNOPGVILKTEWIMKMNFCFHWXUUDIJVWTRNUSRYPEUTZTIGMNH", "RKGIVWZYGMQVXKVNLKIOQDGPRJVCBVKXLMLITYGDLVWSYJPMKS", "XTZTUXUXLPQWLJGUZHERSZYQSLAACGFDYFJKTWXCBZXRZOQYTU", "UWMLYUJMOVMLOZTFPGFYYZVUTGDZGANOPZWRUWZAVHYUIRKZYZ", "VWXZWZNIHVKJPXYUBCWXHWXYTFEHLMFBMNQDLIJATROTJSMQOW", "ZETJYXOCYFTILWTBAVVUQBZFXYQVYZXOQLEMKKAGERASTYLKJH", "YWGIICKADXSQVREIIQHUGROTXWUWXVWYZIUONLIFCDWUOHCTEI", "VXNMHNOWXFRLTULKRPTXHCUXTVZTJGKLXTDPHAMNHTXZYBWUQP", "SRPKMLJYUBEAMODHOSLGAKMOSUWYSCFJQEFQQRSIMKGWXARXVO", "RQNORFZRQTDLMFGMIKIMNOBEQUEQNDENRYHIRDTQJLXCEZQSNO", "JKUMEABIRSFPMJFEKHGUMCDHKNJOMRCDZGXGZUPFGSRFYATPNP", "IGLFZMJWQDSLQGDXLMIPWXIGLOWPSHXWUTFWHAVXHIHGZXIOMQ", "HYEHLNMLHGRURZZYMJRQVZCJCSXVTKLYVYVHMXBWYKLYVWFJNC", "HKJILNOAKIFWVYXTSRDSECFGTZYCULRZTRULYQYEUZUVQEDHDE", "GLMZJCTPJGSTVNQUQBCQDFIHMUXZXOHILTSZKXVZITMROXIZWV", "LPYNLZZQQRQHVCJVMBEPNELJQZVUHSLKDJRPYUSJJTSWBJBTYK", "QXOLHYQRVROKIAGNYBFBFLSRYHJWTGMBFAHLFXTKBHXZLCNITX", "WRJNZPNWSXCJBLPXCIAGYNTUXKYXYQYZVUKMRPYSAIKYMDLMWL", "VUWXOWMOVZYBCFRDEHKPOOVWRZMOPNKLMPNJSTRZIJLMNEONQV", "TMLHBVPZSSYCUSPUGFQUIJTYZNSRMOBWQTODKBUKLHYFGSTSTA", "RMGKIQXYKVOXWRTHGRWTQSKGUTRZSNASUATYAOZMGCTDHJLUBM", "ZHNJTRGTULGYTVBIUXXZRPRPOQNVTWLMRVURPZNYFFRTKWVOLD", "YFIOZPNNKLKMPOMLKPYSJYOITUOWXUVZYYZCQYHSEVUZGCXMKC", "ZXRPYDEZMXWRPNQRSYJWTKJXHQECBUPWXZYFQZEZTMNYDNONFT", "WSGQCBOFYVNMSQESTRXUCLTCGFZDTXYJTUWXDRWYUQPOHJOIVG", "VHIDCAAUGZULPQTUVUYNBUSYXTYXWVZZYSVQEFBVEHGNGPWLHW", "DXJKAXFTWHKACODYXZZTUMZPOIWTOMVBJRRDJHPDZFTUQZYTHZ", "BFNYZWPOXIJFNMLMZJRPASLZFEJKIUXWZMBOKXLNGIKSVPDXDC", "JMVQXUQNKYGEJHKONFSTRQXQSMLRSFSYEJAALNYOWMLRWEFWSR", "HUYFRGCRSJIBIGPQVCZIKOMVPRNDWRRQPKHIOQOZLKSOQXVTRQ", "LRXAWVUTRSZANYTURWDJHLNUWPYOECMLONJHPJRGUTRIPMQROP", "QFIDXVZSZPXGZJRTSXYGGFEHVXPZFEDHMEGDCTSAFFCFEDHSNE", "EHJCUYINTVOWSYIHCXYTLDCGFMNOHIGOPDYZYUFTTGDXWBTLTD", "UKBZQXQMXZXSOWXOPBSRMYQDCZXVJKXWZXCXZVHIHKLVYQPWCY", "QVLNYEGKEYGTNVSQMWFHNSRBIGEPSRSYVYUTWTNDJHLXUZSZXM", "WNSOVJFDVJLFOTUJHLGOGESLQSFRRPXVOQSVXVCOLJVYWBMZYL", "YZQUIDNYHKEPLDCDKELQPFOPFTVOKEWURNAWZWNIKZTZVFZSVX", "JCHJWUMABGTQDJCEAAJPQPVEDUPYNJKLTSHBJOXMMWSDQIXYRW", "DDBEXNRQFLYSRKIHKJMNZONBCZBAGIDJIGFMOWLPPMVRJPSTVT", "JIWTFHIKEEHSQLMVDLDWUMCZLTWXHFHIKBWNDPZQOJHITONUFO", "OKHSQGWMCDGATONWXZFCVTBYXKQIBZJEJIXVDQFVFJIHBLXWQP", "NTGIPVKBNXSUPMRSYZHVBTFGTWJOCZLKXGYVTSRXUKKCRQYZUL", "VUHKJMUYHZVYJQPTJIFBWUHMSVMCWYXSJIDUQTTSYZQLDFSTWM", "ZXULGPSPSYXCIBUKNYPZYINOQOJNORWVWHZNRJYQCMMOKGEDFE", "LYOFLOQRXWXAAAVWXZLXVUJKOPVPQUQPXYMFMTSABEGVQHCDAD" };
    int length = 14;
    assertEquals(2, alphabetcount.count(grid, length));
  }

  @Test
  public void case30() {
    String[] grid = { "SRGSRPGBAHISBCMKRPIJSCROSTQQMMQRKJTAKDOEACEETSRQLM", "PTMTNQECPQROTDLTRPQTSTNMPRBQHLPSNIQSOMDHTBDHHJPONJ", "CDLLMTKMNOTMPSRTOPMRDOTSLCFGPITONOPFNPLIGSNGIKJPQL", "DHIFDEJLAPNSLCHNJFFECSHTDGEQJBDGDKMSTSQSOTRFLRAQHR", "CKGNFATBLCRKJAMLDENBKRNQNOTEKBIHFEHGEFRSRJMNEJBGFS", "QMLMQGSCGQEDBTFNCTSKOQPOPSAMMLBDTSGLSGITRQHCRDCPBT", "RSHKIHNDGHCTAEKMEDTNSNCKNCRPONTPOORIJTTSRPBAELGSAP", "TRQFINMBIFECTTJFASPTQRKOPFQORTLKNASTKJKEGOEBABOSTT", "SPELKJCJLBPSQIHGBDGJPOKJIQPTSDQROMRQSLTFLFABGNMPRS", "LAODRKKJEFGRPRTPJEHIHNTJRBFRDIESCPBTRATKHGFKAHENQS", "MNKSQMPRIHQIHMSCFKLMNSQFSTATCFTTOCDAESRTBCDEIBFGPR", "MJTTNOBTSNPFJOQKJJPTQRPRGDSSQCFHJGEBFMKTOMDFCELNPL", "INOSCDFFKOKFDOMIHOHSLONHDRPTNPQQRATANJSRHNRLKKHSRQ", "HTTPBBGKPOMLGDKLBQRPLMDSBTOCDFGKPSBDHOQQRONLTMGTJA", "GQEQAAHTRSIBPJSDTSABOKKCRNMNIHEJLOCGJPCFQOIMNDEFEF", "KFEDDCBNTFEDSICENTIANILHMLIJQDGMTTDTFBMGMRHBBCEDMD", "DQGTCPOLTBGHDFPJKOJOLMSKEHKLCRHINRSESAJTSNBGDECFHN", "ISNIJQKILRSRIJMQLIHPKRTDMKITBOLGDHQPBAOTCECDCDDGTQ", "HTRMRGHHQOSFBLRLPGKLMNRPKJLAJPFSRKKOODPSBDGEOFEHMS", "PSMHEJSFNNAABHNSEBAJTRQPJLTHIKRPOLMNTKJGAMSFJKCPOL", "OJKLNDAIJMSGFEABTCBIHPSTMLKJDFIMNPSEGCHGFQTKIIQTSJ", "FECRSDBKLJIEHRQASRDHLHOQGMONECGJPTTFDRTBTSPLHJRKCB", "ABDSPGNCJHNISPLIATEKMFGAFHNPDHHKJIHCSSIOSONGRTNQJD", "OMCDREDPNPSASFJLJBCJEJACTSQHIEGHCKRBLRTTDEFSTOSBIE", "BPBJEHFTQRTGMPEMLSPNTSIBCRCEHJKLBFLMNQSPOCJEGHDHGF", "ACQEFGSGPOAPMLOJHOQRDTMJJESTPRQPOARTCPQNNLTSQEGCGA", "IOTSRGMEKDFBONKGIGDBCEHIHLTRQHLNGIRSRBEFMLKTONMDRA", "STSSRLENABPGHBEQITAEFLEJOAQNKAMOKKMQHLDCCASQOGETOQ", "GIDSPQOSTQRJIADDJHSNPKHDPRSTBLOPRJNLFIHDDBDAKLHGFN", "HCJATPMIRPKSBABCBKEMQRTJKEGPODNQIBDOQFIJKCBEKIHKBE", "GFBTFIHHQRLODRTNLLNPRISTGRTNGLTRRALTREDATRCLTOIJDT", "HLAGHRHOFPQGQSKOKIOQTAHBFSRMBOPSDNMSOTKCSAQECSPQMS", "HIKIJGOSTKBFNPSPIJOFEBGECRQILJTTOTMNTSOQHCPNMORPRH", "GKJADEFRTNOJEOKHQNGBABDDGOPKASLFASLKJRRPINOOALKQOI", "LJBCRLMKLMQPDCFNMRSAJBCFEHPOPBMGARKJNKPFJLMDPCPJRF", "IMRTRPQLKRFDABIGEJTJAKTTTSINMRNOBQILFQRSKLCFQBAIGM", "ERSOPGRADTSLRASHQRSILGRNRKLJKIGSCHATOJKJCHKJERGHIE", "KPMMLOABJCHSOCQRGOOTCSESLIEKJKHFRGFQSBIABAKJMSCICG", "ETPTLKBCABMNTSRHTMNPKLTKJIJTSFJMEQOEDCCEDQANDTPOBA", "GJOSIFDDSFGFIQOJSQJJRPEGMNLRQIATNOQCEBAGFADOGQRPED", "OLJRTHASEFHJKAOBDPHSQDRPFJOMPEHBHMKFANEGBRPJOHSHQC", "PQSKGPRQTPILMNACFOTRQESRINCPFTDCLLJAFEHDCMLSEPGILR", "GERTNFLCCBEDCBTDFGISSTADHIGBQSCKJHIGMNJISPQPTDGQTS", "CDDBJKEDFFARABTSRHBTKLBEGEKSRDTFEHSQJOKTTRKNQATRPS", "FGAENMNJIGSRSQRSNMKGHJICFHCPTERSCQPNKSTBISTMBESJRL", "AHIGLMQTHMSIQPIQLNLIFRHEFPIOBFQARMOLMTSKIHSRDCKKNQ", "ACDJSRSPAGKJFJQPOLMDEFGIIJNMATKOANDJNORDEHDGHNGDKP", "BQIFDTAJBSAEKSRMNPJCGAFTKHTKLHMNBCIFOQKCQRJTIIHELH", "PORJKTIPJNHLFFLONKOIHALTROPOTGRPQTHGCPPPIHSSMJSRTO", "ESTMSTQOOMMCEQTSHMECQRSTSQNFDCQSTSONDOAOMBANOPQCNS" };
    int length = 16;
    assertEquals(3, alphabetcount.count(grid, length));
  }

  @Test
  public void case31() {
    String[] grid = { "AADCCADFBABAABDFABCBFAEBACFDCAABEFFEFABCDDABCECEBA", "DBEFEDECEDCDEFECEFCCCFCAEBEBBACCDEDEBAFECECFFADFBA", "EFFECBBDEFDBCFCFDDEDDEBFBDFEFBFFAFBADEFECFCDFEDEDC", "DEBECECACAEEADECCBCFEAFDCCFEADFEBBEAEFDEFEAADFEDDC", "CDCBFEDCDAFEFFDBEFBEECCDEADBBADCACBBCBBDDFAEBEFCEE", "EFFEDBEBFCBCDBBDCFABFDBEECAECCDBDAEDCAACDCFFDAFBED", "EADFEBCECDAAEBEADBAABAEAFBBEDDEFEFAAFDFEEFAFABFBDC", "EFBCBDAFFCBCEDEEBEAEBFBFCABAFBFEECBEEBCECBEDEDECFE", "FEADEEFCFADFDAFBDFBFDEECBDCCDEFFADCCCFEDFFFDEFCFEF", "ACDCBFFEDAEEBACFFACCDFDFEECDDADFEDCDCDCFFECEEDBCDE", "FBDFAADFFFAEFECEEDFAECFEDFAECABEFFEBBFABFBBEDADABC", "AECEDABEECCFFDBFFEEDABBCABFEFEFBEEABACCEEFCDFEABAF", "FBEEFCBBAEBBECAAAEEDBCDBCECCAEACCFACDFDBEFEFBFDCEC", "DFBBBDCACCDABCEFEFEFCDCEEAFDAADABDDBECCAFEDCCBFDFB", "FDECEFBFEEAABBDECFBCEFFFFEEBBCECBCECFEBAFFCCFECECC", "CFFDAEADCBEFDCBAFACEFCABEBFADFFFBAFEDACABEAABCBCDB", "EDEEBFDBDADFEBCCFBDEDBCFFACCFEEEDCEEFEDFECADABBBEA", "ADABACFECEBAEBCEDBCEADDEEABEAADADEDCDEFFBDDCEFCAFD", "AFEACECFFCFFEADBECAAEEBFDFBECAFCFFBCFFBCAFEAECFCBE", "DDEFFEBDDBAAFBBFFEBBCDBCEBAFBFBBCECEEDEBBFDACDBBEF", "DEFEFADEBFEBCDAFDDEECFEFAAEEEAECEDFBFEBFFEBFBCEABD", "FEBEFEFCEDFDCECFEFDAFEBFBBFDCFBAFECACCBDDDCBFBCDFD", "EACCDCDDFBEEFDABDABCDAAEDCCBEDBCBEFBFEAEEFCAAEEBFE", "ADDECFEFCBAECEFCABCFCFEDCBCAADCFDBDAEEEDAFCDBDFBEF", "DCBEABECAFEBFCBCCAFCDBEDCBDABDFEFCDDBFDCACBECECACD", "CBDCADCDAECEDABBFDBBDCFDEDEDCDAEBAEFBCDFBBFAFDBDFE", "BCEDBAEAEDFDBCFEFBAAEFECCFCDEECCDBBABDFECEECAEDCEC", "BFDFBFCDBBCEDCABACFBCBDBFBEFBDFEBAADABCDEFBDBFFEBE", "CBEEEFBFACDBFECFDCEEFFEFACBFEFACEBEFCEAFFEDCEAAEFC", "ADDEFDEFCFEEFFDFEABCBADFEDEFBABDBAACADBACEFBBBFCAF", "EFEDEECCDEFEDDAEEEABACFDBFDADCDEFDDDEACCDEEDEBBDEB", "DFCBDEADEFBCCFEEDCFAAECFEAFEEDFDFAFFDEDAECFCDFDFCC", "BABACDACAEADEDFDBAEBFABDDABCADFEBCEBFBCFAFBCEDBEDB", "BCFDCFEFDCAFFEAACBDCEBECEFDFEBEDDBDEDAEBABBFEDCEEF", "AEEABBDBECBEAEBEFEDAEDDFFEAFAFFCEFFCEDEBDFACABCDDD", "ACCEFBFEBAAFDCDCFFFCBCBFCBBADEAACFBFEFDCEDBDDFADAE", "BEFDCCECACEDEBAEDFDECAAEECCEFEBCDCCAFBBACFEFAEEEFD", "DCAEEDEFDBCFFFCFECEDFACDFDBAFDFEDBBBDFEFDFDAEFEECA", "ECBFEFDFEBFDEDDAFDBFCBCDFAEDCEFEFFFCFCDEFFBCDFDDBA", "DFACDDACCEEAAAFECFFEBBBEEBCBEFBAEDBDEBADFEABEDCCDA", "EACAECDBADCEBEFBEDDEDCEFDBAAFCCFACAAFEDDADBCDCBDED", "DBEEFDFEFBEFBDAAEFFFFDCCAFCEAFEDBFCFFDBAECEAEEFFEF", "AFDDABDDBECFBEFEDFFDEABBDEDBDEEDBFDEFDBFDFDCFBDECB", "FEFBAFECEDFBAFDEFBEDADBBBEAACDBEFACDEDEFAFDBCCECBF", "DEDCFEEAFECABAFEACCCBECFCFABECDAFBBAEDBBBCADCBAEBD", "CAFEDFFDBCDCDBCCDEFAAEBDEEDCCFCECDFFAACBABEFFAFDEC", "FCACFBCDCABABFBDECBCCBDBFDFEEFDFAFEEDBACAFCEBBEDDB", "EBEDDEDFEABAEECAEFDDCECDECDEFFEDCDDFDFEFDDDFCFFCBE", "DBDFECEEFEBCFDBACFEBDEEFEEEDBDECECAECECDACEAFDEEFC", "CABCDFFBADDFACCDEDEAFEFFAABCADBABDABBDABDCAFABCDBA" };
    int length = 6;
    assertEquals(2677, alphabetcount.count(grid, length));
  }

  @Test
  public void case32() {
    String[] grid = { "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
    int length = 1;
    assertEquals(2500, alphabetcount.count(grid, length));
  }

  @Test
  public void case33() {
    String[] grid = { "ABBAAABAABABBAABAAABABBBAABAABAAABAABBBAABABBBBAAA", "ABBBBABBBAABABBBBBBABBABAABBAABBBABAAAAAAAABBBABBA", "AAAABBBAAAAAAAABABAABABBBAABBAAABABBBABABBAABABAAB", "BAABAABAABBABABAABBABAABABBAAABAABBBABBBBABBAABAAB", "BABAABABBBBBBBABBBAABABBABAABAAABAAAAAAAAABBABABBB", "AABBABBAABAAAABBBBAABBAABABABBBAABBABBBBBBABABABAB", "BBBAAABABBBABAAAAABBAABBBABBBAABBABAABABBAAAAABABB", "BBBBBBABAAABAABBAABABBBAABABAABABABABAABBAABBAABAA", "AABABBBABABBABABBAABABBBABABBABABABAAABABBABAAAABA", "AAAAAAABBABBBABABBBBAAAABABBBAAAABBAABABAAABAABBAB", "ABBAABABBAABAABAAAAAABABAABAABABABABABBABBAAAAABBA", "BBBBBBAABBBBBABAABBABABAAAAABAAABAABABAABBBABBABBB", "AABAABBAABBAAABABABBAABBBBABAABAABBBBBBBBAAABBBBAB", "ABBAABBABBABBAABBBBABBAAAABBABAABBABBBBABABBBAAABB", "AAAABAABBAAAAABAAABAAAABBAAAABBABBAAAAAABBAABAABBA", "BBBABBABAABBBABAAABBBABABBABAABAAAAABABBABAABBBBBA", "AABAAAABABABABABBABAABBBBABAABABBBBAABAAAABBAABABB", "AABBABBBABABABABAABBBAABBAAAABBBBABABBABBBABBABBBA", "ABBBBABBAAABBBAABBAAABABBBABAAAAAABBABAAAABABAAABA", "BAABAAABAABABBAABABBABBABBBBBBABABAAABAABAABBAABBA", "ABBBABAABABBAABAABBABBABBAAABBAABABBBBAABAABBABBBA", "BAABABABBAAAABAAABAAAABBABABBABBAAAABAABBBBABBAAAB", "ABAAABAABBBABABBABBABBAAABBABBBABBABBBABAABBAAABAB", "BBABBBAABBAAABABABAABAABBAAAABBBABABABBBAAAABBBABA", "ABBBABABABABBABABABBABABBABABAABAABBABAABBBAAAABBB", "AAABABABBBABBAABAAAAABABBBABABABBABAAABAAABBBBBBBA", "ABBABABAABAAABBABBBBBABAAABBBAABABBABAAABBBBAAAAAB", "ABBBABABBABAAABBABABABABBAAABABABABBAAABABAAABABBA", "BAABBBABABABBAAAAAABBAAABABBABBBBAAABABBABBBABBABA", "BAAAABBAABABABBBBBAABBBABAAAABBAAABBBABBAAABAAABBA", "ABBBBBAAABBBAABAAABBABABBABBAAAABABBBAAABBBABABABA", "AABBAABBBAAAAABAABAAABABAAABBABBABAABBBBBBABBBABAB", "BAABABABBBBBBBBBBBBAABABABBBABABBABBBAAAAAAAAABBAA", "ABBAAAAAAAAAAAABBBABBABBABBBBABABBAABAABABABBABAAB", "BBBABBABBBBABBAAAAAABABAAABABAABBABAABBAABAABABBAB", "BAABAABAABABABBABBBBBBABBAABBABABBAABBAABBAAABBBBA", "AABAAABAABBAAABAAAAABBBAABBAAAAABBBABAABBBABABBBBA", "ABBBBABAABBBABABBABBBABBBBBBBBBABABABABABBBBAABBAB", "ABABBABABAABAAABBBABAABBAABBBABABABABBAAAABBAAABAA", "BBAAAAAABBABABABBAAAAAABABAAABBBAAABABBABBBBBBBABB", "ABBABBBAAAABAAAABBABABBBBABBBAAAABBBBABAAAAAAAAABA", "AAABBABABBBABAABABABAAABBAABBBBBBAAAAABBBAABBBBAAB", "BAABABBBAABAAABBABBBBBABBBAAAAABABBABABABABAABABAB", "BABAABBABABABAABBABAABAABABBABBABBABAAABABBBBBABBA", "AABABAABAAAABABBAAABABABBAAAAAABABABABABABABAAAABA", "BBABBAABABBBAAABBBABBABBAAABABABAABABBAABAAAAABBBA", "ABBAABAABAABABAABAAAABAABAABBBBABBBBABABBABBBABAAB", "BAAABBABABABABBABABBABBBABAAAAAABBAABBAAAAAABBAABB", "BBBBBBBABBABBBBABABABBBBAABBAABBAABAABBABBBBAABBBA", "ABAABAABBAABAAABBBAAAABAABAABABABAABAAABAABAAABAAB" };
    int length = 2;
    assertEquals(5309, alphabetcount.count(grid, length));
  }

  @Test
  public void case34() {
    String[] grid = { "AAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "ABBAAAACBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "ABCCBADDBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "ABCDDEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "ABDDEFGHIJKLMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "ACCAEFGHIJKLMNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "ABBAAAGHIJKLMNOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAHIJKLMNOPQRSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAIJKLMNOPQRSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAJKLMNOPQRSTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAKLMNOPQTUUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAALMNOPAVVVVAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAWWWWWAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAXXXXXAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAVWXYYYXAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAUVWXYZYXAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAATUVWXYYYXAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAASTAVWXXXXXAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAARSTAAAWWWWWAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAARQAAAAVVVVVAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AABCDEFGHIAQPAAAUUUUUAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AABCDEFGHIJAPONAATTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AABCDEFGAIJKLMNAPQRSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AABCDEFGHIJKLMNOAQRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AABCDEFGHIJKLMNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AABCDEFGHIJKLMNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AABCDEFGHIJKLMNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" };
    int length = 26;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case35() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ" };
    int length = 26;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case36() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYA" };
    int length = 24;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case37() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY" };
    int length = 26;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case38() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY" };
    int length = 26;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case39() {
    String[] grid = { "ZBCDEFGHIJZZMNOPQRSTUVWXYZ", "ZBCDEFGHIJKLMNOPQRSTUVWXYZ", "ZBCDEFGHIJKLMNOPQRSTUVWXYZ" };
    int length = 26;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case40() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY" };
    int length = 26;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case41() {
    String[] grid = { "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ", "DBCDEFGHIJKLMNOPQRSTUVWXYZ" };
    int length = 26;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case42() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA", "ABCDEFGHIJKLMNOPQRSTUVWXYXWVUTSRQPONMLKJIHGFEDCBA" };
    int length = 25;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case43() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ" };
    int length = 21;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case44() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ" };
    int length = 21;
    assertEquals(131836323, alphabetcount.count(grid, length));
  }

  @Test
  public void case45() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY" };
    int length = 26;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case46() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ" };
    int length = 23;
    assertEquals(768398401, alphabetcount.count(grid, length));
  }

  @Test
  public void case47() {
    String[] grid = { "B" };
    int length = 1;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case48() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTU", "BBCDEFGHIJKLMNOPQRSTU", "CCCDEFGHIJKLMNOPQRSTU", "DDDDEFGHIJKLMNOPQRSTU", "EEEEEFGHIJKLMNOPQRSTU", "FFFFFFGHIJKLMNOPQRSTU", "GGGGGGGHIJKLMNOPQRSTU", "HHHHHHHHIJKLMNOPQRSTU", "IIIIIIIIIJKLMNOPQRSTU", "JJJJJJJJJJKLMNOPQRSTU", "KKKKKKKKKKKLMNOPQRSTU", "LLLLLLLLLLLLMNOPQRSTU", "MMMMMMMMMMMMMNOPQRSTU", "NNNNNNNNNNNNNNOPQRSTU", "OOOOOOOOOOOOOOOPQRSTU", "PPPPPPPPPPPPPPPPQRSTU", "QQQQQQQQQQQQQQQQQRSTU", "RRRRRRRRRRRRRRRRRRSTU", "SSSSSSSSSSSSSSSSSSSTU", "TTTTTTTTTTTTTTTTTTTTU", "UUUUUUUUUUUUUUUUUUUUU" };
    int length = 21;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case49() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "BCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWY", "CDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYA", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFG", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFH", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "FGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCD", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "CDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYA", "BCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWY", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "BCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWY", "CDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYA", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "FGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCD", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFG", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFH", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "FGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCD", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "CDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYA", "BCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWY", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "FGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCD", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFG", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFH", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE" };
    int length = 25;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case50() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA" };
    int length = 26;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case51() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYAZ", "ABCDEFGHIJKLMNOPQRSTUVWXYAZ", "ABCDEFGHIJKLMNOPQRSTUVWXYAZ" };
    int length = 26;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case52() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY" };
    int length = 25;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case53() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY" };
    int length = 26;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case54() {
    String[] grid = { "BCDEFGHIJKLMNOPQRSTUVWXYZ", "BCDEFGHIJKLMNOPQRSTUVWXYZ", "BCDEFGHIJKLMNOPQRSTUVWXYZ", "BCDEFGHIJKLMNOPQRSTUVWXYZ", "BCDEFGHIJKLMNOPQRSTUVWXYZ", "BCDEFGHIJKLMNOPQRSTUVWXYZ" };
    int length = 26;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case55() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ" };
    int length = 26;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case56() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "BCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWY", "CDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYA", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFG", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFH", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "FGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCD", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "CDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYA", "BCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWY", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "BCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWY", "CDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYA", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "FGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCD", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFG", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFH", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "FGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCD", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "CDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYA", "BCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWY", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "FGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCD", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFG", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFH", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE" };
    int length = 23;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case57() {
    String[] grid = { "ABC" };
    int length = 2;
    assertEquals(1, alphabetcount.count(grid, length));
  }

  @Test
  public void case58() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ" };
    int length = 24;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case59() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "BCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWY", "CDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYA", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFG", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFH", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "FGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCD", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "CDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYA", "BCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWY", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "BCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWY", "CDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYA", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "FGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCD", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFG", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFH", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "FGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCD", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "CDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYA", "BCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWY", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "ABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVW", "DEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYAB", "EFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABC", "FGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCD", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFG", "IJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEFH", "HIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDEF", "GHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWYABCDE" };
    int length = 26;
    assertEquals(0, alphabetcount.count(grid, length));
  }

  @Test
  public void case60() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYA" };
    int length = 26;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case61() {
    String[] grid = { "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "ZYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY", "ZYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXY", "ZYXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXY", "ZYXWVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWXY", "ZYXWVUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUVWXY", "ZYXWVUTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTUVWXY", "ZYXWVUTSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSTUVWXY", "ZYXWVUTSRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRSTUVWXY", "ZYXWVUTSRQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQRSTUVWXY", "ZYXWVUTSRQPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQRSTUVWXY", "ZYXWVUTSRQPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPQRSTUVWXY", "ZYXWVUTSRQPONNNNNNNNNNNNNNNNNNNNNNNNNNNOPQRSTUVWXY", "ZYXWVUTSRQPONMMMMMMMMMMMMMMMMMMMMMMMMMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLLLLLLLLLLLLLLLLLLLLLLLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKKKKKKKKKKKKKKKKKKKKKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJJJJJJJJJJJJJJJJJJJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIIIIIIIIIIIIIIIIIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHHHHHHHHHHHHHHHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGGGGGGGGGGGGGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGFFFFFFFFFFFGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGFEEEEEEEEEFGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGFEDDDDDDDEFGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGFEDCCCCCDEFGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGFEDCBBBCDEFGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGFEDCBABCDEFGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGFEDCBBBCDEFGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGFEDCCCCCDEFGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGFEDDDDDDDEFGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGFEEEEEEEEEFGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGFFFFFFFFFFFGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHGGGGGGGGGGGGGHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIHHHHHHHHHHHHHHHIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJIIIIIIIIIIIIIIIIIJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKJJJJJJJJJJJJJJJJJJJKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLKKKKKKKKKKKKKKKKKKKKKLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMLLLLLLLLLLLLLLLLLLLLLLLMNOPQRSTUVWXY", "ZYXWVUTSRQPONMMMMMMMMMMMMMMMMMMMMMMMMMNOPQRSTUVWXY", "ZYXWVUTSRQPONNNNNNNNNNNNNNNNNNNNNNNNNNNOPQRSTUVWXY", "ZYXWVUTSRQPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPQRSTUVWXY", "ZYXWVUTSRQPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQRSTUVWXY", "ZYXWVUTSRQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQRSTUVWXY", "ZYXWVUTSRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRSTUVWXY", "ZYXWVUTSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSTUVWXY", "ZYXWVUTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTUVWXY", "ZYXWVUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUVWXY", "ZYXWVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWXY", "ZYXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXY", "ZYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXY", "ZYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY" };
    int length = 26;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case62() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ" };
    int length = 25;
    assertEquals(1000000000, alphabetcount.count(grid, length));
  }

  @Test
  public void case63() {
    String[] grid = { "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA", "ABCDEFGHIJKLMNOPQRSTUVWXYA" };
    int length = 26;
    assertEquals(0, alphabetcount.count(grid, length));
  }

}
